-- 003_vehicles.sql — 32 vehicle generations (US market), fit attributes for the configurator
-- Idempotent: safe to re-run. Values compiled from manufacturer spec sheets (2026-09); verify flagged attrs before publishing.
-- Conventions: bed_lengths_in = inside bed length rounded to whole inches; roof_type ∈ bare | raised-rails | flush-rails | fixed-points | removable
--              hitch_class = factory/most-common aftermarket receiver class; receiver_in = 1.25 | 2 | 2.5; tow_rating_lb = max with factory tow package
-- Optional attrs keys read by the vehicle hub (each replaces generated text where it would mislead): hitch_fact, hitch_check, hitch_blurb,
--              tow_fact, roof_fact, roof_type_fact, roof_phrase, roof_check. Keep their text free of apostrophes and double quotes.

INSERT INTO makes (slug, name) VALUES
 ('ford','Ford'),('chevrolet','Chevrolet'),('gmc','GMC'),('ram','Ram'),('toyota','Toyota'),('jeep','Jeep'),
 ('nissan','Nissan'),('honda','Honda'),('subaru','Subaru'),('tesla','Tesla'),('kia','Kia'),('hyundai','Hyundai')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO vehicles (make_id, model_slug, model_name, gen_slug, gen_name, year_from, year_to, body_style,
  bed_lengths_in, roof_type, roof_load_lb, hitch_class, receiver_in, tow_rating_lb, tire_size, bolt_pattern, rows_seating, attrs, summary)
VALUES
-- ===================== TRUCKS =====================
((SELECT id FROM makes WHERE slug='ford'),'f-150','F-150','2021-present','14th Gen (P702)',2021,NULL,'truck',
 '{67,79,98}','bare',NULL,'4',2,14000,'275/65R18','6x135',2,
 '{"bed_utility_track":"optional (XLT+)","tailgate_step":"optional","variants":["Lightning 2022+","Raptor","Tremor"],"bed_material":"aluminum","verify":["tow max is 3.5L EcoBoost Max Tow"]}',
 'Three bed lengths (5.5 / 6.5 / 8 ft). Check for the optional bed utility track before buying rail-clamp covers; Lightning shares the 5.5 ft bed.'),

((SELECT id FROM makes WHERE slug='ford'),'f-150','F-150','2015-2020','13th Gen (P552)',2015,2020,'truck',
 '{67,79,98}','bare',NULL,'4',2,13200,'275/65R18','6x135',2,
 '{"bed_utility_track":"optional","bed_material":"aluminum","variants":["Raptor 2017+"]}',
 'Aluminum-bed generation with 5.5 / 6.5 / 8 ft beds (67.1 / 78.9 / 97.6 in at the rail). Some liners, soft covers and racks are listed for both 2015–2020 and 2021+ trucks, but BAK, Retrax and Gator hard covers use separate 2021+ part numbers, so match the year range and part number on the listing.'),

((SELECT id FROM makes WHERE slug='chevrolet'),'silverado-1500','Silverado 1500','2019-present','4th Gen (T1)',2019,NULL,'truck',
 '{70,79,98}','bare',NULL,'4',2,13300,'275/60R20','6x139.7',2,
 '{"tailgate":"Multi-Flex optional (2021+)","bed_names":{"70":"Short 5ft 8in","79":"Standard 6ft 6in","98":"Long 8ft"},"bed_material":"steel (Durabed)","variants":["Trail Boss","ZR2 2022+"]}',
 'Beds are 5''8", 6''6" and 8 ft. Multi-Flex tailgate (2021+) changes tailgate-side clamp fit on some covers — check the listing.'),

((SELECT id FROM makes WHERE slug='gmc'),'sierra-1500','Sierra 1500','2019-present','5th Gen (T1)',2019,NULL,'truck',
 '{70,79,98}','bare',NULL,'4',2,13200,'275/60R20','6x139.7',2,
 '{"tailgate":"MultiPro standard on most trims","bed_material":"steel or CarbonPro composite (option)","carbonpro_fit_warning":true,"variants":["AT4","AT4X","Denali"]}',
 'Same beds as Silverado (5''8" / 6''6" / 8 ft). MultiPro tailgate and the CarbonPro composite bed both affect tonneau fit — many covers exclude CarbonPro.'),

((SELECT id FROM makes WHERE slug='ram'),'1500','1500','2019-present','5th Gen (DT)',2019,NULL,'truck',
 '{67,76}','bare',NULL,'4',2,12750,'275/55R20','6x139.7',2,
 '{"rambox":"optional — needs RamBox-specific covers/racks","bed_names":{"67":"5ft 7in","76":"6ft 4in"},"tailgate":"multifunction split optional","variants":["TRX 2021-2024","RHO 2025+","Classic (DS) sold alongside 2019-2024"]}',
 'Two beds: 5''7" and 6''4". RamBox trucks need RamBox-specific covers and racks. Do not confuse with the Ram 1500 Classic (DS) sold alongside — different bed rails.'),

((SELECT id FROM makes WHERE slug='toyota'),'tacoma','Tacoma','2016-2023','3rd Gen (N300)',2016,2023,'truck',
 '{61,74}','bare',NULL,'4',2,6800,'265/70R16','6x139.7',2,
 '{"bed_rail_system":"factory deck rails with cleats","bed_material":"composite (SMC)","bed_names":{"61":"5ft short","74":"6ft long"},"variants":["TRD Pro","Trail Edition"]}',
 'Composite bed with factory deck-rail system — most bed racks clamp to those rails. 5 ft and 6 ft beds; the 6 ft is Access Cab / some Double Cab.'),

((SELECT id FROM makes WHERE slug='toyota'),'tacoma','Tacoma','2024-present','4th Gen (N400)',2024,NULL,'truck',
 '{60,74}','bare',NULL,'3',2,6500,'265/70R18','6x139.7',2,
 '{"bed_rail_system":"deck rails","bed_material":"composite","hybrid":"i-FORCE MAX option","fit_note":"few 3rd-gen covers carry over; buy 2024+ listings only","verify":["tow max by trim"]}',
 'All-new 2024 platform: 5 ft and 6 ft composite beds with deck rails. 2016–2023 fitments do NOT carry over — buy 2024+ listings only.'),

((SELECT id FROM makes WHERE slug='toyota'),'tundra','Tundra','2022-present','3rd Gen (XK70)',2022,NULL,'truck',
 '{66,79,98}','bare',NULL,'4',2,12000,'265/70R18','6x139.7',2,
 '{"bed_rail_system":"deck rails","bed_material":"composite (SMC)","bed_names":{"66":"5.5 ft","79":"6.5 ft","98":"8.1 ft"},"variants":["TRD Pro","Capstone","i-FORCE MAX hybrid"]}',
 'Composite bed with deck rails, three lengths (5.5 / 6.5 / 8.1 ft). 2007–2021 fitments do not carry over.'),

((SELECT id FROM makes WHERE slug='jeep'),'gladiator','Gladiator','2020-present','JT',2020,NULL,'truck',
 '{60}','removable',NULL,'3',2,7700,'255/75R17','5x127',2,
 '{"trail_rail":"optional Trail Rail cargo system — affects bed rack + cover fit","roof":"removable hardtop/soft top — no roof racks, use bed racks","spare":"under-bed","variants":["Rubicon","Mojave"]}',
 'Single 5 ft bed; optional Trail Rail system changes cover and rack fit. Roof is removable, so overland loads go on a bed rack.'),

((SELECT id FROM makes WHERE slug='ford'),'ranger','Ranger','2019-2023','4th Gen (T6, US)',2019,2023,'truck',
 '{61,73}','bare',NULL,'4',2,7500,'265/65R17','6x139.7',2,
 '{"bed_names":{"61":"5 ft (SuperCrew)","73":"6 ft (SuperCab)"},"supercab_bed":"6 ft bed on SuperCab; cover makers list it as 6 ft 1 in or 72.7 in, stored as 73","variants":["Tremor package, model year 2021 on (SuperCrew 4x4, XLT or Lariat)"],"hitch":"receiver came with the optional Trailer Tow Package (53R on the 2019 towing guide); no trim confirmed with it standard"}',
 'US-market SuperCrew has a 5 ft bed (61 in); SuperCab has a 6 ft bed (72.7 in, stored as 73). Check under the rear bumper for the factory hitch receiver; the 7,500 lb maximum needs the tow package.'),

((SELECT id FROM makes WHERE slug='ford'),'ranger','Ranger','2024-present','5th Gen (P703)',2024,NULL,'truck',
 '{60}','bare',NULL,'4',2,7500,'265/65R17','6x139.7',2,
 '{"bed_names":{"60":"5 ft"},"variants":["Raptor 2024+ (5,510 lb max towing; Trailer Tow Package standard)"],"fit_note":"2019-2023 covers, racks and liners do not carry over","cab":"SuperCrew only in the US (MotorWeek launch report; Ford pages list no other cab)","hitch":"Class IV receiver comes with the Trailer Tow Package (53R): standard on Raptor, optional on XL/XLT/Lariat; 3,500 lb bumper-only limit; 2 in opening not confirmed on Ford pages","bed_rails":"plastic rail caps; optional Ford cargo management rails change cover and rack fit (RealTruck lists the RetraxPRO XR as not compatible with the bed cargo management system)","hitch_fact":"Class IV receiver with the Trailer Tow Package (standard on Raptor, optional on XL, XLT and Lariat per Ford)","hitch_check":"The hitch receiver comes with the Trailer Tow Package: standard on the Raptor and optional on XL, XLT and Lariat (Ford towing guides), so look under the rear bumper before buying a hitch.","tow_fact":"7,500 lb max with the Trailer Tow Package; Raptor 5,510 lb (Ford)"}',
 'US-market SuperCrew with one 5 ft bed (59.6 in, stored as 60). 2019–2023 covers, racks and liners do not carry over. Check under the rear bumper for the factory hitch receiver; the 7,500 lb maximum needs the Trailer Tow Package (Raptor: 5,510 lb).'),

((SELECT id FROM makes WHERE slug='chevrolet'),'colorado','Colorado','2023-present','3rd Gen',2023,NULL,'truck',
 '{62}','bare',NULL,'4',2,7700,'265/70R17','6x120',2,
 '{"bed_names":{"62":"5ft 2in"},"tailgate":"StowFlex storage tailgate (standard on 2023 ZR2, optional on other trims)","variants":["Trail Boss","ZR2","ZR2 Bison"],"fit_note":"confirm 2023+ fit on multi-generation cover listings"}',
 'Crew Cab only, with one 5''2" bed (61.7 in) on every 2023+ truck. Many sellers list 2015–2026 on one cover SKU; buy 2023+-specific listings or confirm with the seller.'),

((SELECT id FROM makes WHERE slug='ford'),'maverick','Maverick','2022-present','1st Gen',2022,NULL,'truck',
 '{54}','bare',NULL,'3',2,4000,'225/65R17','5x108',2,
 '{"bed_names":{"54":"4.5 ft FLEXBED"},"hitch":"factory 2 in Class III receiver with the 4K Tow Package; no factory receiver confirmed without it","flexbed_slots":true,"hybrid":"standard 2.5L hybrid"}',
 'Compact 4.5 ft FLEXBED with slots for DIY dividers. The factory 2 in receiver comes with the 4K Tow Package; on other trucks, look under the bumper before buying a hitch. Rated 2,000 lb, or 4,000 lb on AWD trucks with the package.'),

((SELECT id FROM makes WHERE slug='nissan'),'frontier','Frontier','2022-present','3rd Gen (D41)',2022,NULL,'truck',
 '{60,73}','bare',NULL,'3',2,6720,'265/70R17','6x114.3',2,
 '{"bed_rail_system":"Utili-track optional","bed_names":{"60":"5 ft","73":"6 ft"},"variants":["PRO-4X"]}',
 '5 ft (Crew Cab) and 6 ft (King Cab / Crew LB) beds; optional Utili-track channels affect clamp-style covers.'),

-- ===================== SUVs =====================
((SELECT id FROM makes WHERE slug='toyota'),'4runner','4Runner','2010-2024','5th Gen (N280)',2010,2024,'suv',
 '{}','raised-rails',120,'3',2,5000,'265/70R17','6x139.7',2,
 '{"trd_pro_factory_rack":"TRD roof rack new for 2019 and exclusive to the TRD Pro (Toyota 2019, 2020 and 2021 releases); 2022-2024 not confirmed; Trail and Venture Special Editions carry Yakima cargo baskets (Toyota 2021 release)","rear_window":"power roll-down","third_row":"optional (Limited/SR5)","roof_load":"120 lb per a reader comment on Trail4Runner citing a 2016 SR5 owner manual; not confirmed from a Toyota document, and the comment does not say whether it is the rail limit or the roof limit; confirm in the owner manual; a Toyota dealer parts page for the Genuine Toyota cross bar kit PT278-89170 gives 132 lb evenly distributed across both bars, which is a bar rating and not a roof limit, and the page lists no model years","fit_note":"Crossbar kits clamp to raised rails. TRD Pro (TRD roof rack, new for 2019) and the Trail and Venture Special Editions (Yakima basket) carry a factory rack or basket, so look at the roof first.","hitch":"integrated tow-hitch receiver and wiring harness standard on all grades per Toyota 2017, 2019, 2020 and 2021 releases; Toyota names no hitch class or receiver size in those releases; Class 3 and 2 in are not confirmed from a Toyota document, read the label on the receiver","tow":"5,000 lb maximum with 500 lb maximum tongue weight on all models (Toyota 2017, 2019, 2020 and 2021 releases)","hitch_fact":"factory receiver standard on all grades per Toyota (2017 to 2021 releases); Toyota names no hitch class","hitch_check":"Toyota lists a tow-hitch receiver and wiring harness as standard on all grades (2017 to 2021 releases), so look under the rear bumper before buying a hitch.","hitch_blurb":"Toyota lists an integrated tow-hitch receiver and wiring harness as standard on all grades in its 2017, 2019, 2020 and 2021 releases and names no hitch class, so look under the rear bumper before buying a hitch and read the label on the receiver. An aftermarket hitch never raises the vehicle rating.","tow_fact":"5,000 lb max with 500 lb tongue weight on all models (Toyota)","roof_fact":"120 lb per a 2016 SR5 owner manual figure cited by a reader; not confirmed from Toyota"}',
 'Factory raised rails on most trims; the TRD Pro has a TRD roof rack from 2019. Long generation = huge aftermarket; Toyota lists a tow-hitch receiver and wiring harness as standard on all grades, with 5,000 lb towing and 500 lb tongue weight.'),

((SELECT id FROM makes WHERE slug='toyota'),'4runner','4Runner','2025-present','6th Gen (N500)',2025,NULL,'suv',
 '{}','raised-rails',NULL,'4',2,6000,'265/70R18','6x139.7',2,
 '{"hybrid":"i-FORCE MAX standard on Platinum, TRD Pro and Trailhunter; available on TRD Off-Road, TRD Off-Road Premium and Limited","fit_note":"New roof and rail geometry: 2010-2024 crossbars and racks do not fit. Rail style and factory crossbars are not confirmed by grade (Toyota lists an ARB roof rack on the Trailhunter), so look at your roof.","verify":["roof load rating (165 lb dynamic / 770 lb static is from the GearJunkie first-drive review, not a Toyota document; one owner cites 125 lb for factory crossbars)","rail style and factory crossbars by grade, including the TRD Pro roof","hitch receiver class and which grades ship with a receiver (no Toyota source found)","third row by grade (GearJunkie: non-hybrid SR5 and Limited only)","grille light bar on grades other than TRD Pro and Trailhunter","model code N500 is from Wikipedia, not a Toyota page"]}',
 'All-new for 2025 on TNGA-F. 2010-2024 roof racks, crossbars and floor liners do NOT carry over. Roof load, rail style by grade and hitch class are not confirmed from Toyota.'),

((SELECT id FROM makes WHERE slug='jeep'),'wrangler','Wrangler','2018-present','JL',2018,NULL,'suv',
 '{}','removable',NULL,'2',2,5000,'255/75R17','5x127',2,
 '{"doors":["2-door","4-door Unlimited"],"roof":"removable hardtop / soft top / Sky One-Touch","spare":"tailgate-mounted — bike racks need spare-tire clearance","hitch":"factory Class II 2 in (3,500 lb) on Trailer Tow package, read the receiver label against the owner manual rating; aftermarket Class III common","tow":"2018–2023: 2,000 lb 2-door / 3,500 lb 4-door (dealer guides; Jeep 2018 release: up to 3,500 lb with towing package); 2024+: 5,000 lb confirmed by Jeep only for 4-door Rubicon 2.0L or 3.6L automatic on 33 in tires; all other 2024+ configurations not confirmed above the 2018–2023 figures, use the towing chart in the owner manual; 4xe and 392: 3,500 lb (dealer guides)","variants":["Rubicon","392","4xe"],"hitch_blurb":"The 5,000 lb maximum is confirmed by Jeep only for 2024 and later 4-door Rubicon automatics on 33 in tires; 2018 to 2023 Wranglers are listed at 2,000 lb (2-door) or 3,500 lb (4-door), so read the towing chart in your owner manual. An aftermarket hitch never raises the vehicle rating."}',
 'Removable roof means roof racks bolt to the hardtop or a cage-style rack. Tailgate spare tire dictates bike-rack and cargo-carrier choice. Tow rating runs from 2,000 lb to 5,000 lb by year, doors and trim; 5,000 lb is confirmed only for 2024+ 4-door Rubicon automatics on 33 in tires.'),

((SELECT id FROM makes WHERE slug='ford'),'bronco','Bronco','2021-present','6th Gen (U725)',2021,NULL,'suv',
 '{}','removable',NULL,'2',2,3500,'285/70R17','6x139.7',2,
 '{"doors":["2-door","4-door"],"roof":"removable hardtop / soft top; hardtop has factory rail mounting points on some trims","spare":"tailgate-mounted","variants":["Raptor","Badlands","Sasquatch pkg (35 in tires)"]}',
 'Removable hardtop or soft top; roof racks bolt to the hardtop''s factory attachment points or rain gutters, and a soft top needs a bridging rack. Most models tow up to 3,500 lb and the Raptor 4,500 lb. Tailgate spare affects bike racks.'),

((SELECT id FROM makes WHERE slug='toyota'),'rav4','RAV4','2019-present','5th Gen (XA50)',2019,2025,'suv',
 '{}','raised-rails',165,'3',2,3500,'225/65R17','5x114.3',2,
 '{"rails":"raised rails standard on XLE and up; LE has bare roof; crossbar listings treat Adventure and TRD Off-Road rails as a separate fit; the hybrid Woodland Edition has high profile rails with standard cross bars (2024); Toyota sells separate Adventure cross bars (PT278-42191, 2019-2024, per a Toyota dealer catalog)","hitch":"No factory receiver on most versions. Toyota accessory hitch PK960-42K10 has a 2 in receiver tube; its Toyota parts page calls it Class II in the description but leaves the class field blank. A Toyota dealer catalog lists PK960-42R10, titled Class III, as its replacement; no Toyota page for that number could be opened. A Toyota dealer says the 2024 Adventure and TRD Off-Road include a receiver with Tow Prep; size not confirmed. Aftermarket 2 in Class III common","tow":"2024 Toyota dealer figures: 1,500 lb gas LE, XLE, XLE Premium and Limited; 1,750 lb Hybrid; 2,500 lb Prime; 3,500 lb Adventure and TRD Off-Road with Tow Prep. Adventure and TRD Off-Road were discontinued for 2025. For other years check the owner manual","hybrid":"RAV4 Hybrid and Prime (renamed Plug-in Hybrid for 2025) do not share every fit with gas models: some floor liners are gas only and hitch listings name Hybrid and Prime by year; Toyota says the Prime battery is mounted under the floor; Hybrid battery location not confirmed","fit_note":"2026 RAV4 is a new generation — these fitments stop at 2025","hitch_fact":"2 in on the Toyota accessory hitch and most aftermarket hitches; no factory receiver on most versions","hitch_check":"Most RAV4s have no factory receiver. A Toyota dealer lists one with the Tow Prep Package on the 2024 Adventure and TRD Off-Road; its size is not confirmed, so measure it before buying a rack or ball mount.","hitch_blurb":"Most 2019-2025 RAV4s have no factory receiver. A Toyota dealer says the 2024 Adventure and TRD Off-Road include one with the Tow Prep Package, which is the 3,500 lb version; its size is not confirmed, so measure it. The Toyota accessory hitch and most aftermarket hitches use a 2 in receiver, and no hitch raises the vehicle rating.","tow_fact":"3,500 lb max (2024 Adventure and TRD Off-Road with Tow Prep); 1,500 lb gas, 1,750 lb Hybrid, 2,500 lb Prime in 2024 dealer figures","roof_fact":"Check the owner manual; no Toyota figure confirmed. RAV4Resource lists 176.4 lb (80 kg) for 2019-2024"}',
 'Compact SUV sold as gas, Hybrid and Prime (renamed Plug-in Hybrid for 2025). Raised rails on XLE and up; the LE is bare roof and needs a different crossbar kit. Tow rating depends on trim and powertrain, from 1,500 to 3,500 lb in 2024 dealer figures, and most versions have no factory hitch receiver.'),

((SELECT id FROM makes WHERE slug='honda'),'cr-v','CR-V','2023-present','6th Gen',2023,NULL,'suv',
 '{}','bare',NULL,'3',2,1500,'235/60R18','5x114.3',2,
 '{"rails":"gas LX, EX and EX-L: no factory rails (door-frame clamp crossbars, or Honda accessory rails listed at 165 lb total by a Honda parts dealer); hybrid Sport, TrailSport, Sport-L and Sport Touring: black roof rails standard per Honda 2023 and 2026 specifications (2024 and 2025 tables not read)","hitch":"no factory receiver confirmed; Honda accessory hitch 08L92-3A0-100 is Class I per a Honda parts dealer (receiver size not stated); the aftermarket hitches in the hitch guide are Class 3 with a 2 in receiver","hybrid":"Sport, TrailSport (new for 2026), Sport-L and Sport Touring are hybrids: 1,000 lb tow rating, black roof rails, and some hitches and cargo liners are listed by powertrain","fit_note":"2017-2022 mats and racks do not fit","tow":"1,500 lb gas (LX, EX, EX-L); 1,000 lb hybrid (Sport, TrailSport, Sport-L, Sport Touring) per Honda 2023 and 2026 specifications","roof_type_fact":"bare on gas trims; black roof rails on hybrid trims (Honda 2023 and 2026 specifications)","roof_phrase":"your roof (bare on gas trims, black roof rails on hybrid trims per Honda)","hitch_fact":"no factory receiver confirmed; aftermarket hitches are Class 3 with a 2 in receiver, and the Honda accessory hitch is Class I","hitch_check":"We could not confirm that any CR-V ships with a receiver, so look under the rear bumper. Honda sells a Class I accessory hitch; the aftermarket hitches in the hitch guide have a 2 in receiver.","tow_fact":"1,500 lb gas trims; 1,000 lb hybrid trims (Honda)"}',
 'Gas LX, EX and EX-L have a bare roof, so crossbars use door-frame clamps; the hybrid trims carry black roof rails per Honda. Honda rates towing at 1,500 lb on gas trims and 1,000 lb on hybrids. 2017–2022 fitments do not carry over.'),

((SELECT id FROM makes WHERE slug='toyota'),'highlander','Highlander','2020-present','4th Gen (XU70)',2020,NULL,'suv',
 '{}','flush-rails',NULL,'3',2,5000,'235/65R18','5x114.3',3,
 '{"rails":"flush side rails with fixed mounting points on railed trims (etrailer and The Rack Shop); a flush rail has no gap under it; some roofs may be bare - confirm; Toyota lists black roof rails on the 2021 XSE; HEKA sells a separate crossbar set for L and LE as models without factory side rails","third_row":true,"hybrid":"Hybrid: up to 3,500 lb towing and battery under the second-row seats (Toyota 2025 release); roof and hitch listings are shared with gas models, but some floor liner sets exclude the Hybrid","grand_highlander":"different vehicle (2024+) — do not mix","tow":"up to 5,000 lb on 2.4L turbo models and 3,500 lb on all Hybrid models (Toyota 2025 release); on 2021 V6 models the available towing package enables 5,000 lb (Toyota 2021 release)","hitch":"no factory receiver confirmed on any grade; Toyota sells Tow Hitch Receiver PT228-48174 as an accessory; aftermarket hitches in the hitch guide have a 2 in receiver","hitch_fact":"no factory receiver confirmed; Toyota sells an accessory receiver, and aftermarket hitches have a 2 in receiver","hitch_check":"We could not confirm that any grade ships with a receiver. Toyota sells one as an accessory, so look under the rear bumper before buying a hitch.","tow_fact":"5,000 lb max on 2.4L turbo models; 3,500 lb on Hybrid models (Toyota 2025 release)","roof_type_fact":"flush side rails with fixed mounting points on railed trims (etrailer); some roofs may be bare","roof_phrase":"flush factory side rails (or a bare roof on some trims)","roof_fact":"no Toyota roof figure confirmed; Toyota crossbars are listed at 165 lb (75 kg) by a Canadian Toyota dealer and Thule and Yakima systems at 165 lb, bars and cargo included; the owner manual is the authority","fit_note":"A fifth-generation Highlander was unveiled on February 10, 2026 with sales set to start in late 2026 (Wikipedia); nothing listed here is confirmed for it.","roof_check":"Factory side rails are flush with fixed mounting points (no gap under the rail): buy bars listed for the 2020 and newer Highlander by name, compare the mount in the listing photos with your rail, and check for a bare roof on base trims such as L and LE."}',
 'Three-row family SUV. Railed trims have flush side rails with fixed mounting points; some roofs may be bare. Toyota lists up to 5,000 lb towing on 2.4L turbo models and 3,500 lb on the Hybrid. Grand Highlander is a different vehicle.'),

((SELECT id FROM makes WHERE slug='subaru'),'outback','Outback','2020-present','6th Gen (BT)',2020,2025,'suv',
 '{}','raised-rails',150,'2',2,3500,'225/60R18','5x114.3',2,
 '{"rails":"raised rails with integrated, retractable crossbars on every trim except Wilderness (Subaru: 150 lb maximum capacity); Wilderness (2022-2025) has fixed ladder-type rails with no built-in crossbars (Subaru: 200 lb dynamic, 700 lb static)","hitch":"2 in Subaru accessory hitch (L101SAN000, Class II, harness included); 2 in aftermarket Class III common","tow":"2,700 lb with the 2.5L (Base, Premium, Limited, Touring; Onyx Edition from 2023); 3,500 lb with the 2.4L turbo (Onyx Edition XT, Limited XT, Touring XT, Wilderness)","fit_note":"crossbar kits are rail-specific: bars for the standard raised rails and bars for the Wilderness ladder rails do not interchange; roof figures are from the Subaru 2022, 2023 and 2025 trim sheets, and the owner manual is the authority; 2026 Outback is a new generation"}',
 'Roof rails with integrated, retractable crossbars (150 lb per Subaru) on every trim except the Wilderness, which has fixed ladder-type rails and no built-in crossbars (200 lb dynamic, 700 lb static). Check which rail you have before buying a crossbar kit.'),

((SELECT id FROM makes WHERE slug='subaru'),'forester','Forester','2019-2024','5th Gen (SK)',2019,2024,'suv',
 '{}','raised-rails',176,'2',1.25,1500,'225/60R17','5x114.3',2,
 '{"rails":"raised rails standard on Premium, Sport, Limited, Touring; optional on Base (Subaru 2019, 2022, 2024 sheets), so a Base can have a bare roof; Subaru: 176 lb maximum (2022, 2024 sheets), 700 lb static (2022 release); Wilderness (2022-2024) rails 220 lb dynamic / 800 lb static; Subaru lists a fixed crossbar set accessory for the Base only (2022, 2024 sheets)","tow":"1,500 lb; Wilderness 3,000 lb (Subaru sheets); tongue 150 lb, Wilderness 300 lb per the Subaru dealer listing for the 2022-2024 hitch; the dealer page for the 2019-2021 hitch prints 176 lb, so 2019-2021 owners should use the owner manual","variants":["Wilderness 2022-2024"],"fit_note":"2025 is a new generation except the Wilderness: Wikipedia says only the Forester Wilderness was still offered for the 2025 model year and the redesigned Wilderness went on sale as a 2026 model, and a Subaru dealer lists the 2025 Wilderness on the 2022-2024 accessory hitch L101SSJ005, so confirm 2025 Wilderness parts by VIN","hitch":"no factory receiver confirmed; Subaru accessory hitch L101SSJ001 (2019-2021, 1-1/4 in) or L101SSJ005 (2022-2024 and 2025 Wilderness, 2 in, harness included); aftermarket 1.25 in Class II and 2 in Class III","hitch_fact":"no factory receiver confirmed; Subaru accessory hitch is 1-1/4 in (2019-2021) or 2 in (2022-2024), and aftermarket hitches come in 1.25 in and 2 in","hitch_check":"We could not confirm that any Forester leaves the factory with a receiver, so look under the rear bumper. A Subaru dealer listing for the 2022-2024 hitch gives 150 lb of tongue weight on standard trims and 300 lb on the Wilderness; for 2019-2021 check the owner manual.","tow_fact":"1,500 lb; 3,000 lb on the Wilderness (Subaru)","roof_fact":"176 lb on the standard roof rails (Subaru 2022 and 2024 sheets); Wilderness 220 lb dynamic, 800 lb static","roof_type_fact":"raised rails standard on Premium, Sport, Limited and Touring; optional on Base (Subaru)","roof_phrase":"raised roof rails (optional on the Base, so check the roof)","roof_check":"Subaru lists the raised roof rails as standard on Premium, Sport, Limited and Touring and optional on the Base, so check a Base for a bare roof; the 2022-2024 Wilderness has its own rails and needs Wilderness-listed bars."}',
 'Raised rails standard on Premium and up, optional on Base; Wilderness (2022–2024) has its own rails and a 3,000 lb tow rating. The 2025 Forester is a new generation; Wikipedia says the outgoing Wilderness was still offered for 2025, so confirm a 2025 Wilderness by VIN.'),

((SELECT id FROM makes WHERE slug='tesla'),'model-y','Model Y','2020-present','1st Gen incl. 2025 Juniper refresh',2020,NULL,'ev',
 '{}','fixed-points',165,'3',2,3500,'255/45R19','5x114.3',2,
 '{"roof":"glass roof with 4 fixed mounting points (Tesla-spec crossbars only)","hitch":"2 x 2 in square receiver with the Tesla Tow Package (sold with the car or later through the Tesla Shop); Tesla prints no hitch class, Class 3 is the aftermarket makers label; owner manual: do not install an accessory carrier on a Model Y not equipped with the tow package; receiver designed for vertical loads up to 160 lb","tow":"3,500 lb / 350 lb tongue for 5-seat and Performance with 5 or fewer occupants; 6- and 7-seat cars: lower limits by wheel size and occupied seats, some combinations not permitted (see the owner manual table); Trailer Mode must be active when towing","juniper_2025":"refreshed 2025 (US availability from March 2025; a 2025 can be either body); mats/liners differ, and aftermarket roof bars and hitches are split by body","third_row":"optional 7-seat in the US until the 2025 refresh","variants":["Model Y Standard (October 2025 on): no front light bar, no rear screen, headliner over the glass roof","Model Y L (US launch July 2026): 6-seat 2-2-2, 7.0 in longer; excluded from the Tesla Roof Rack"],"hitch_blurb":"Tesla prints no hitch class; Class 3 is the aftermarket makers label. The Tesla owner manual says not to install an accessory carrier on a Model Y that is not equipped with the Tesla tow package, so ask Tesla before fitting an aftermarket hitch. An aftermarket hitch never raises the vehicle rating.","hitch_fact":"2 in receiver with the Tesla Tow Package (Tesla prints no hitch class)","hitch_check":"No receiver unless the car has the Tesla Tow Package. The Tesla owner manual says not to install an accessory carrier on a Model Y without it.","tow_fact":"3,500 lb max with the Tesla Tow Package (5-seat and Performance); less on 6- and 7-seat cars","roof_fact":"165 lb (the Tesla rating for its own roof rack)"}',
 'Glass roof with fixed points: only Model Y-specific fixed-point crossbar kits fit, and Tesla rates its own rack at 165 lb. The Tesla Tow Package adds a 2 in receiver (Tesla prints no hitch class): 3,500 lb for 5-seat and Performance cars, less on 6- and 7-seat cars depending on wheels and occupied seats. Tesla owner manual says not to install an accessory carrier on a Model Y without the tow package. The 2025 Juniper refresh, the Standard (October 2025) and the six-seat Model Y L (US, July 2026) change some fitments.'),

((SELECT id FROM makes WHERE slug='tesla'),'model-3','Model 3','2017-present','1st Gen incl. 2024 Highland refresh',2017,NULL,'ev',
 '{}','fixed-points',NULL,'none',NULL,NULL,'235/45R18','5x114.3',2,
 '{"roof":"glass roof with fixed mounting points; owner manual says to use only roof rack systems approved by Tesla and prints no roof load; the Tesla Shop rates the Tesla Model 3 Roof Rack at 150 lb (static load limit 495 lb)","hitch":"no receiver unless the car has the Tesla Tow Package (Tesla Shop: 2 in receiver and 4-pin connector, for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later, not the Performance); Tesla prints no hitch class; owner manual: do not install an accessory carrier on a Model 3 not equipped with the towing package; receiver designed for vertical loads up to 121 lb; aftermarket hitches are sold (mostly 2 in, one 1.25 in) and Tesla gives no figure for them","highland_2024":"refreshed car (Highland): North American orders opened January 10, 2024 (Wikipedia); mats/liners differ, and aftermarket roof bars and hitches are split by body; some rack sellers split by build month (to October 2023, from November 2023), so check the door-jamb build date","tow":"with the Tesla Tow Package: 2,200 lb with trailer brakes, 1,650 lb without, 200 lb tongue weight; Trailer Mode must be active when towing; Vehicle Loading page in the 2017-2023 and the current owner manual: do not use Model 3 for towing purposes","variants":["Model 3 Performance: not compatible with the Tesla Tow Package"],"hitch_fact":"2 in receiver only with the Tesla Tow Package, sold for 2024 and later Rear-Wheel Drive and All-Wheel Drive cars","hitch_check":"No receiver unless the car has the Tesla Tow Package, which Tesla lists only for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later. The Tesla owner manual says not to install an accessory carrier on a Model 3 without it.","hitch_blurb":"Tesla lists its Tow Package only for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later, not the Performance: 2,200 lb with trailer brakes, 1,650 lb without, and 121 lb for an accessory carrier. The Tesla owner manual says not to install an accessory carrier on a Model 3 that is not equipped with the towing package, so ask Tesla before fitting an aftermarket hitch. An aftermarket hitch never raises the vehicle rating.","tow_fact":"2,200 lb with trailer brakes (1,650 lb without), only with the Tesla Tow Package on 2024 and later Rear-Wheel Drive and All-Wheel Drive cars; no Tesla tow figure for other Model 3s","roof_fact":"150 lb (the Tesla Shop load rating for its own Model 3 Roof Rack; the owner manual prints no roof load)","roof_phrase":"a glass roof with fixed mounting points","roof_check":"Glass roof with fixed mounting points and no rails: the Tesla owner manual says to use only roof rack systems approved by Tesla with a Tesla mounting accessory, so ask Tesla before fitting any other bars."}',
 'Glass roof with fixed mounting points. The Tesla owner manual says to use only Tesla-approved roof racks and prints no roof load; Tesla rates its own Model 3 rack at 150 lb. Tesla lists a Tow Package (2 in receiver, up to 2,200 lb) only for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later, not the Performance, and its owner manual says not to install an accessory carrier on a Model 3 without the towing package. The 2024 Highland refresh changes mats and liners, and aftermarket roof bars and hitches are split by body.'),

((SELECT id FROM makes WHERE slug='ford'),'explorer','Explorer','2020-present','6th Gen (U625)',2020,NULL,'suv',
 '{}','raised-rails',NULL,'3',2,5600,'255/55R20','5x114.3',3,
 '{"rails":"raised side rails standard; Ford 2027 Explorer page lists a Slick Roof Conversion that deletes them on Active, ST-Line, Platinum and ST - check the roof","third_row":true,"hybrid":"Hybrid 2020-2023 (retail); Police Interceptor Utility kept the 3.3L hybrid","tow":"with factory tow package: 5,300 lb 2.3L / 5,600 lb 3.0L (2020-2024), 5,000 lb (2025-2026); 3,000 lb without the package per Ford 2024 towing guide","fit_note":"2025 facelift keeps roof/hitch fit; Class III Trailer Tow Package standard from 2025 (Ford)"}',
 'RWD-based three-row SUV with raised side rails (a rail-delete Slick Roof Conversion is listed on some trims) and a 2 in factory receiver with the tow package: 5,300 lb (2.3L) or 5,600 lb (3.0L) for 2020-2024, 5,000 lb for 2025-2026.'),

((SELECT id FROM makes WHERE slug='jeep'),'grand-cherokee','Grand Cherokee','2022-present','5th Gen (WL)',2022,NULL,'suv',
 '{}','flush-rails',NULL,'4',2,6200,'265/60R18','5x127',2,
 '{"rails":"factory flush side rails on most trims","grand_cherokee_l":"3-row L variant — longer roof, different rear mats","4xe":"PHEV: roof and crossbar fit unchanged; no hitch here excludes the 4xe, but CURT 13525 excludes the two-row Trailhawk (4xe-only from 2023 per Wikipedia); floor liners differ by listing (Husky 95411 excludes the 4xe, reason not confirmed); tow 6,000 lb on Trailhawk and higher trims, 3,500 lb on base trims (one dealer guide); not on the Jeep 2026 pages as read","tow":"6,200 lb 3.6L V6 and 2026 2.0L Hurricane 4 Turbo (Jeep 2026 capability page); 7,200 lb 5.7L V8 where offered (Wikipedia: 2023 two-row models no longer offered it; dealer guide: dropped from the lineup for 2025); 4xe 6,000 lb Trailhawk and higher, 3,500 lb base trims (one dealer guide); use the towing chart in the owner manual","hitch":"factory 2 in receiver only on vehicles built with the available Trailer-Tow Package (a dealer towing guide calls it a Class IV hitch receiver; the Mopar replacement receiver listing says Class III, same as production), read the receiver label; aftermarket Draw-Tite 76595 and CURT 13525 are concealed 7,500 lb hitches","hitch_fact":"Class IV 2 in receiver only with the available Trailer-Tow Package (class per a dealer towing guide)","hitch_blurb":"The factory 2 in receiver comes only with the available Trailer-Tow Package; a dealer towing guide calls it Class IV, and 6,200 lb is the Jeep figure for the 3.6L V6 and the 2026 2.0L turbo. Aftermarket hitches for this body are concealed designs that mount behind the rear fascia, so follow the maker instructions and check that the listing names your model year. An aftermarket hitch never raises the vehicle rating.","fit_note":"2026 refresh brings a new grille, new fascias and redesigned headlamps (Jeep); Draw-Tite 76595 and CURT 13525 list 2026, but ask the seller of any hitch, liner or crossbar listing whose years stop at 2024 or 2025"}',
 'WL generation; two-row (the Grand Cherokee L is three-row with a longer roof). Flush side rails on most trims. Factory 2 in receiver only with the available Trailer-Tow Package (Class IV per a dealer towing guide); up to 6,200 lb with the 3.6L V6 or the 2026 2.0L turbo.'),

((SELECT id FROM makes WHERE slug='chevrolet'),'tahoe','Tahoe','2021-present','5th Gen (T1)',2021,NULL,'suv',
 '{}','flush-rails',NULL,'4',2,8400,'275/60R20','6x139.7',3,
 '{"rails":"flush side rails (per etrailer and The Rack Shop); Z71 uses its own fit kit","rst_performance_edition":"2025 RST Performance Edition package removes the roof rack (per Edmunds); side rails not confirmed, check the roof","second_row":"bench (8 seats) or bucket seats (7); buckets standard on Premier and High Country, available on LT, RST and Z71 (per Chevrolet); 9-seat front bench is an LS-only option (per Edmunds, 2025)","factory_steps":"assist steps standard on Premier and High Country, power-retractable optional on Premier and in the High Country Deluxe Package (per GM Authority); tubular assist steps on Z71 (per Chevrolet); LS, LT, RST not confirmed","third_row":true,"suburban":"same fit for roof/hitch; different third-row liners, cargo liners and running boards","variants":["Z71","RST","High Country"]}',
 'Full-size three-row SUV; flush side rails, Class IV hitch, up to 8,400 lb tow. Suburban shares roof and hitch fit.'),

((SELECT id FROM makes WHERE slug='kia'),'telluride','Telluride','2020-present','1st Gen',2020,2025,'suv',
 '{}','flush-rails',220,'3',2,5000,'245/60R18','5x114.3',3,
 '{"rails":"flush side rails on LX/S/EX/SX/SX-P; raised, bridge-type rails with a gap on X-Line/X-Pro (2023+)","third_row":true,"variants":["X-Line 2023+","X-Pro 2023+"],"fit_note":"Kia skipped the 2026 model year; the next generation is the 2027 Telluride","tow":"5,000 lb; 5,500 lb on the X-Pro (Kia 2023 press kit)","tow_fact":"5,000 lb; 5,500 lb on the X-Pro (Kia)","roof_fact":"220 lb evenly distributed (Kia 2024 owner manual); brand-name crossbar systems are rated 165 lb"}',
 'Three-row with flush side rails (raised on X-Line/X-Pro, 2023 on). Kia lists 5,000 lb towing, 5,500 lb on the X-Pro, and its 2024 owner manual prints a 220 lb roof rack load. The next generation starts with the 2027 model year.'),

((SELECT id FROM makes WHERE slug='hyundai'),'palisade','Palisade','2020-2025','1st Gen (LX2)',2020,2025,'suv',
 '{}','flush-rails',220,'3',2,5000,'245/60R18','5x114.3',3,
 '{"rails":"flush side rails (Thule/etrailer classify them as flush)","third_row":true,"variants":["XRT 2023+"],"fit_note":"2026 is a new generation","tow":"5,000 lb with trailer brakes, 1,650 lb without (Hyundai 2020, 2023 and 2024 specification sheets)","hitch":"Hyundai specification sheets list no tow hitch as equipment (2020, 2023, 2024); aftermarket Class 3 hitches with a 2 in receiver are listed for 2020-2025","hitch_fact":"no tow hitch in the Hyundai spec sheets; aftermarket hitches are Class 3 with a 2 in receiver","hitch_check":"The Hyundai spec sheets we read list no tow hitch as equipment, so look under the rear bumper before buying one.","tow_fact":"5,000 lb with trailer brakes; 1,650 lb without (Hyundai)","roof_fact":"220 lb roof rails load capacity (Hyundai 2020, 2023 and 2024 spec sheets)"}',
 'Three-row SUV with flush side rails; the Hyundai spec sheets list a 220 lb roof rails load capacity and 5,000 lb towing with trailer brakes, and list no tow hitch as equipment. 2026 is a new generation.'),

((SELECT id FROM makes WHERE slug='honda'),'pilot','Pilot','2023-present','4th Gen',2023,NULL,'suv',
 '{}','raised-rails',165,'3',2,5000,'255/60R18','5x120',3,
 '{"rails":"roof rails standard on Sport, TrailSport, Touring and Elite (Honda Info Center, 2023 and 2024); LX and EX-L have a bare roof and need a door-frame clamp kit; up to 165 lb on the rails with accessory crossbars (Honda)","third_row":true,"tow":"5,000 lb AWD; 3,500 lb 2WD (Honda)","variants":["TrailSport","Black Edition 2025+","Touring Blackout 2026"],"hitch":"integrated Class III trailer hitch standard on the TrailSport only (Honda Info Center); other trims have no factory receiver unless a dealer fitted one","roof_type_fact":"roof rails on Sport, TrailSport, Touring and Elite; bare roof on LX and EX-L (Honda, 2023 and 2024)","roof_phrase":"your roof (rails on Sport, TrailSport, Touring and Elite; bare on LX and EX-L per Honda)","roof_fact":"165 lb on the roof rails with accessory crossbars (Honda)","hitch_fact":"Class III factory hitch on the TrailSport only (Honda); other trims need one added","hitch_check":"Only the TrailSport has a factory hitch (Honda). On other trims look under the rear bumper for a dealer-fitted receiver before buying one."}',
 'Roof rails are standard on the Sport, TrailSport, Touring and Elite; the LX and EX-L are bare-roof and need a clamp kit. Honda quotes up to 165 lb on the rails with accessory crossbars. Tow 5,000 lb AWD, 3,500 lb 2WD; only the TrailSport has a factory hitch.'),

((SELECT id FROM makes WHERE slug='toyota'),'sequoia','Sequoia','2023-present','3rd Gen (XK80)',2023,NULL,'suv',
 '{}','raised-rails',NULL,'4',2,9520,'265/70R18','6x139.7',3,
 '{"rails":"raised or flush side rails (etrailer lists both for 2023 and names no grades); not confirmed by grade; the Toyota releases read do not describe the roof rails","third_row":true,"hybrid":"i-FORCE MAX standard","variants":["SR5","Limited","Platinum","1794 Edition","TRD Pro","Capstone"],"fit_note":"shares Tundra platform; different roof/mats","tow":"up to 9,520 lb (Toyota releases for the 2023, 2025 and 2026 model years); the January 2022 reveal said 9,000 lb","tow_fact":"up to 9,520 lb (Toyota)","roof_type_fact":"side rails; etrailer lists factory installed raised rails and flush mounted rails for 2023 and names no grades, so check the roof","roof_phrase":"your side rails (etrailer lists raised and flush types for 2023)","factory_steps":"power running boards standard on Capstone (Toyota 2023 and 2025 releases); other grades not confirmed","roof_check":"Slide your fingers under the side rail between its end mounts: a gap means raised rails and no gap means flush rails, and etrailer lists both for the 2023 Sequoia without naming grades.","seating":"captain chairs standard on TRD Pro, Platinum and 1794 Edition; bench or captain chairs on Limited (Toyota 2023 reveal and 2025 release); SR5 and Capstone not stated"}',
 'Hybrid-only full-size three-row on the Tundra platform; Class IV, up to 9,520 lb tow (Toyota); side rail type varies, confirm on the roof.')

ON CONFLICT (make_id, model_slug, gen_slug) DO UPDATE SET
  gen_name=EXCLUDED.gen_name, year_from=EXCLUDED.year_from, year_to=EXCLUDED.year_to, body_style=EXCLUDED.body_style,
  bed_lengths_in=EXCLUDED.bed_lengths_in, roof_type=EXCLUDED.roof_type, roof_load_lb=EXCLUDED.roof_load_lb,
  hitch_class=EXCLUDED.hitch_class, receiver_in=EXCLUDED.receiver_in, tow_rating_lb=EXCLUDED.tow_rating_lb,
  tire_size=EXCLUDED.tire_size, bolt_pattern=EXCLUDED.bolt_pattern, rows_seating=EXCLUDED.rows_seating,
  attrs=EXCLUDED.attrs, summary=EXCLUDED.summary, updated_at=now();
