-- 004_fitment_pages.sql — GENERATED by db/content/build_pages_sql.py; edit pages_v1.py, not this file.
-- status 'draft' until fitments exist for the page; app renders drafts as noindex. Flip to 'published' with 005 or by hand.

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2021–2025 Ford F-150 (5.5 / 6.5 / 8 ft Bed)$t$, $m$Fit-checked tonneau covers for the 14th-gen F-150 sorted by bed length, with the utility-track and Lightning gotchas most listings skip.$m$, $i$Every cover below is matched to a specific F-150 bed. Measure inside the bed from bulkhead to tailgate: 66 in = 5.5 ft, 78 in = 6.5 ft, 96 in = 8 ft. Soft roll-ups are the cheapest, hard tri-folds are the sweet spot, retractables cost the most but seal best.$i$, $g$- **Bed utility track** (optional on XLT and up) blocks most clamp-on side rails — buy a cover that states utility-track compatibility or remove the track (4 bolts per side).
- **Lightning (2022+)** shares the 5.5 ft bed; most 5.5 ft covers fit, but confirm the listing names Lightning because the tailgate is different.
- **Tailgate work surface / step** does not affect cover fit. **Tailgate applique** on Lariat+ can — measure before buying a low-profile hard cover.
- **Bed-side steps** and **BoxLink cleats** must be removed or relocated for full-length rail covers.$g$, $f$[{"q": "Do 5.5 ft F-150 covers fit the F-150 Lightning?", "a": "Most do — the bed is identical. Confirm the listing lists 2022+ Lightning; a few hard covers foul the Lightning tailgate handle."}, {"q": "Will a tonneau fit with the bed utility track?", "a": "Only covers that state utility-track compatibility. Others need the track removed, which is four bolts per side and reversible."}, {"q": "Hard vs soft cover for an F-150 that works?", "a": "Hard tri-fold: 400 lb distributed capacity, lockable with the tailgate. Soft roll-up if you haul tall loads weekly and want full bed access in 10 seconds."}, {"q": "Can I keep my bed-side steps?", "a": "Retractable side steps under the bed are fine; step pads that bolt on the bed rail conflict with rail-mounted covers."}]$f$::jsonb, $v$**Budget:** soft roll-up. **Best overall:** aluminum hard tri-fold. **Premium:** low-profile retractable with a canister — check it clears the utility track.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='ford' AND v.model_slug='f-150' AND v.gen_slug='2021-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2019–2025 Chevy Silverado 1500 (5'8" / 6'6" / 8 ft)$t$, $m$Tonneau covers verified for the T1 Silverado 1500 by bed length, including Multi-Flex tailgate and Durabed rail notes.$m$, $i$The T1 Silverado has three beds: 5'8" short (70 in), 6'6" standard (79 in) and 8 ft long (98 in). The short bed is on every Crew Cab and is where most cover stock sits. Matching your bed length is the only spec that matters more than cover type.$i$, $g$- **Multi-Flex tailgate (2021+)** has an inner gate that swings inside the cover's tailgate seal — most covers fit but a handful of low-profile hard covers block the inner-gate release.
- **Durabed corner steps** and **cargo tie-downs** are below the rail and do not interfere.
- **2019 LD / Limited** (old-body-style trucks sold as 2019s) use the previous-gen bed — check the VIN body style before ordering.
- **ZR2 / Trail Boss** share the short bed; no fit difference.$g$, $f$[{"q": "Which Silverado bed do I have?", "a": "Crew Cab = 5'8\" (70 in) unless ordered with the 6'6\" bed; Double Cab = 6'6\"; Regular Cab = 8 ft. Measure inside the bed to confirm."}, {"q": "Do covers work with the Multi-Flex tailgate?", "a": "Yes for roll-ups and most tri-folds. Look for 'Multi-Flex compatible' if you use the inner gate as a step."}, {"q": "Do Silverado and Sierra covers interchange?", "a": "Yes — same bed unless the Sierra has the CarbonPro composite bed, which needs a CarbonPro-specific cover."}]$f$::jsonb, $v$**Budget:** soft tri-fold. **Best overall:** hard tri-fold with a Multi-Flex-compatible tailgate seal. **Premium:** electric retractable.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='chevrolet' AND v.model_slug='silverado-1500' AND v.gen_slug='2019-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2019–2025 Ram 1500 DT (5'7" / 6'4" Bed, RamBox Guide)$t$, $m$Ram 1500 DT tonneau covers by bed length, with a clear split between standard beds and RamBox-equipped trucks.$m$, $i$The DT Ram has two beds — 5'7" (67 in) and 6'4" (76 in) — and the single biggest fit question is RamBox. RamBox trucks have a narrower bed opening with factory rails, so they need RamBox-specific covers. Everything below is labelled standard or RamBox.$i$, $g$- **RamBox** = separate SKU. A standard-bed cover will not seal on a RamBox truck and vice-versa.
- **Ram 1500 Classic (DS)** was sold alongside the DT through 2024 — it has the older bed and different covers. Check the tailgate badge: DT has the 'RAM' letters across the gate.
- **Multifunction (split) tailgate** works with roll-ups and most tri-folds; a few hard covers need a spacer kit.
- **TRX / RHO** use the 5'7" bed and standard covers.$g$, $f$[{"q": "How do I know if my Ram has RamBox?", "a": "Lockable storage bins built into the bed sides above the wheel wells. If you have them, buy RamBox-specific covers only."}, {"q": "Does a 5'7\" DT cover fit the Ram 1500 Classic?", "a": "No. The Classic uses the 2009–2018 bed; buy DS-specific covers."}, {"q": "Is the multifunction tailgate a problem?", "a": "Only for a few hard covers that rely on a full-width tailgate seal. Roll-ups and tri-folds are fine."}]$f$::jsonb, $v$**Standard bed:** hard tri-fold. **RamBox:** RamBox-specific roll-up or tri-fold — fewer choices, so buy on reviews. **Premium:** retractable, standard beds only.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='ram' AND v.model_slug='1500' AND v.gen_slug='2019-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2019–2025 GMC Sierra 1500 (MultiPro & CarbonPro Fit Guide)$t$, $m$Sierra 1500 tonneau covers by bed length, split for MultiPro tailgate and the CarbonPro composite bed.$m$, $i$The Sierra shares its 5'8", 6'6" and 8 ft beds with the Silverado, but two GMC-only options change the answer: the MultiPro six-way tailgate (standard on most trims) and the optional CarbonPro carbon-fiber bed (AT4 / Denali). CarbonPro needs its own covers.$i$, $g$- **CarbonPro bed** has different rail geometry — most standard covers do not clamp. Only buy covers that list CarbonPro.
- **MultiPro tailgate** needs a cover whose tailgate seal clears the inner gate; most roll-ups and tri-folds are fine.
- **Sierra 1500 Limited (2019)** is the previous body style — different bed.
- **Denali Ultimate** ships with CarbonPro standard on some model years — check the build sheet.$g$, $f$[{"q": "How do I know if I have the CarbonPro bed?", "a": "Bed floor is dark carbon composite with a molded pattern, not spray-in liner over steel. It is listed on the window sticker as CarbonPro."}, {"q": "Do Silverado covers fit the Sierra?", "a": "Yes for steel beds. Not for CarbonPro."}, {"q": "Which covers keep the MultiPro step usable?", "a": "Roll-ups and soft tri-folds. Hard covers must be folded first to use the inner gate."}]$f$::jsonb, $v$**Steel bed:** hard tri-fold. **CarbonPro:** the few CarbonPro-listed roll-ups — expect to pay more. **Premium:** retractable, steel beds only.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='gmc' AND v.model_slug='sierra-1500' AND v.gen_slug='2019-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2022–2025 Toyota Tundra (5.5 / 6.5 / 8.1 ft Bed)$t$, $m$Fit-verified tonneau covers for the 3rd-gen Tundra's composite bed, by bed length, with deck-rail notes.$m$, $i$The 2022+ Tundra has a composite bed with a factory deck-rail system on three lengths: 5.5 ft (66 in), 6.5 ft (79 in) and 8.1 ft (98 in). The deck rails sit inside the bed rail cap, so most clamp-on covers fit, but the composite rail cap dents easier than steel — use rubber-padded clamps.$i$, $g$- **2007–2021 Tundra covers do not fit** — the bed and rails changed completely in 2022.
- **Deck rail cleats** must be slid out of the way or removed for clamp-style rails on some covers.
- **TRD Pro / Capstone** share beds with the rest of the range.
- **Composite rail cap**: over-tightened metal clamps crack it. Torque to the cover maker's spec.$g$, $f$[{"q": "Which Tundra bed do I have?", "a": "CrewMax = 5.5 ft standard, 6.5 ft optional; Double Cab = 6.5 ft or 8.1 ft. Measure inside the bed."}, {"q": "Do I need to remove the deck rails?", "a": "No — the rails are inside the bed. Only the sliding cleats may need repositioning."}, {"q": "Hard or soft for a hybrid Tundra?", "a": "No difference — the i-FORCE MAX has no bed-mounted hardware."}]$f$::jsonb, $v$**Budget:** soft roll-up with padded clamps. **Best overall:** hard tri-fold listed for 2022+. **Premium:** retractable.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='toyota' AND v.model_slug='tundra' AND v.gen_slug='2022-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2020–2025 Jeep Gladiator (5 ft Bed, Trail Rail Guide)$t$, $m$Gladiator JT tonneau covers verified for the 5 ft bed, split between standard beds and the optional Trail Rail cargo system.$m$, $i$The Gladiator has one 5 ft (60 in) bed. The fit question is the optional Trail Rail cargo management system — its rails sit inside the bed and change how clamp-style covers seat. The Gladiator also has a taller bed rail than most midsize trucks, so low-profile hard covers look best.$i$, $g$- **Trail Rail system**: covers must state Trail Rail compatibility or you remove the rails (Torx bolts, reversible).
- **Removable roof** means the bed is your only weatherproof storage — lockable hard covers earn their price here.
- **Bed rail caps** are plastic — use padded clamps.
- **Mojave / Rubicon** share the standard bed.$g$, $f$[{"q": "Can I keep the Trail Rail system with a cover?", "a": "Only with covers listed as Trail Rail compatible. Otherwise remove the rails; keep the bolts."}, {"q": "Do Wrangler accessories fit the Gladiator bed?", "a": "No — the Wrangler has no bed. Only Gladiator-specific covers."}, {"q": "Which cover works with a bed rack?", "a": "None at the same time; choose a cover-rack combo product or a bed rack with an integrated cover."}]$f$::jsonb, $v$**Budget:** soft tri-fold. **Best overall:** hard tri-fold with Trail Rail compatibility. **Premium:** retractable — rare for the JT, so check stock.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='jeep' AND v.model_slug='gladiator' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2022–2025 Ford Maverick (4.5 ft FLEXBED)$t$, $m$Maverick tonneau covers verified for the 4.5 ft FLEXBED, with notes on the bed slots, tie-downs and the hybrid.$m$, $i$The Maverick's 4.5 ft (54 in) FLEXBED is unique — no other truck shares it, so only Maverick-listed covers fit. The bed rails have molded slots for DIY dividers and the tailgate has a mid-position stop; both are compatible with most covers.$i$, $g$- **FLEXBED slots** are below the rail cap; clamp-style covers fit over them.
- **Tailgate mid-position** works with roll-ups; hard covers must be folded first.
- **Hybrid and EcoBoost** share the same bed.
- **Factory bed cover (Ford accessory)** uses the same clamp points — aftermarket is cheaper.$g$, $f$[{"q": "Will a Ranger 5 ft cover fit the Maverick?", "a": "No. The Maverick bed is 54 in; Ranger is 60–61 in. Buy Maverick-specific."}, {"q": "Does a cover stop me using the tailgate as a table?", "a": "No — the tailgate still drops; roll the cover back first."}, {"q": "Do I lose the FLEXBED slots?", "a": "No — the slots are inside the bed; the cover sits on the rail cap."}]$f$::jsonb, $v$**Budget:** soft roll-up. **Best overall:** hard tri-fold listed for Maverick. **Premium:** retractable — limited choice for the 4.5 ft bed.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='ford' AND v.model_slug='maverick' AND v.gen_slug='2022-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2024–2025 Ford Ranger (5 ft Bed, New Generation)$t$, $m$Tonneau covers verified for the all-new 2024+ Ranger's 5 ft bed — 2019–2023 covers do not fit.$m$, $i$The 2024 Ranger is a new platform with a 5 ft (60 in) bed. Many sellers list one SKU for 2019–2026, but the new bed is not identical to the old one, so treat 2019–2026 listings as unverified until the seller confirms 2024+ — the fit pill on each card shows what we could verify.$i$, $g$- **2019–2023 covers are not automatically compatible** — the 2024 bed rail cap and width differ; only buy listings that name 2024+ or confirm with the seller.
- **Raptor** shares the bed with the rest of the 2024+ range.
- **Bed rail caps** are plastic; padded clamps only.
- **Factory tie-downs** are fixed; they do not interfere with rail covers.$g$, $f$[{"q": "Can I use my 2023 Ranger cover on a 2024?", "a": "Not without checking — the 2024 bed differs. Ask the maker for a 2024+ fit confirmation before reusing it."}, {"q": "Is the Ranger Raptor bed different?", "a": "No — same bed, same covers."}, {"q": "Why are there so few covers for the 2024 Ranger?", "a": "New platform; makers release fitments over 12–24 months. Check back — we update this page monthly."}]$f$::jsonb, $v$**Budget:** soft tri-fold listed for 2024+. **Best overall:** hard tri-fold with confirmed 2024+ fit. **Premium:** wait — retractables are still arriving.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='ford' AND v.model_slug='ranger' AND v.gen_slug='2024-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Bed Racks for 2016–2023 Toyota Tacoma (Deck Rail Mount, Tent-Ready)$t$, $m$Overland bed racks verified for the 3rd-gen Tacoma's deck-rail system, for rooftop tents, bikes and cargo.$m$, $i$The 3rd-gen Tacoma's composite bed has factory deck rails that most racks clamp to — no drilling. Pick by height: low-profile (cab height) for MPG and tents; mid-height for bed access under a tent; high (over-cab) for max storage.$i$, $g$- **Deck rails are the mount** — racks without deck-rail clamps need drilling into the composite bed; avoid.
- **5 ft vs 6 ft bed** need different rack lengths; most listings specify.
- **Rooftop tent load**: the composite bed rail is rated lower than steel — stay under the rack maker's dynamic rating (typically 300–500 lb).
- **Tonneau + rack**: only combo systems allow both.$g$, $f$[{"q": "Do I need to drill?", "a": "No — deck-rail-mount racks clamp into the factory channels."}, {"q": "What height for a rooftop tent?", "a": "Mid-height keeps the tent below the cab roofline for wind and lets you open the tailgate."}, {"q": "Will a 3rd-gen rack fit the 2024 Tacoma?", "a": "No — the 4th-gen bed rails changed. Buy 2024+ listings for the new truck."}]$f$::jsonb, $v$**Budget:** low-profile steel deck-rail rack. **Best overall:** mid-height aluminum. **Premium:** full over-cab system with accessory tracks.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='bed-racks'
WHERE m.slug='toyota' AND v.model_slug='tacoma' AND v.gen_slug='2016-2023'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Bed Racks for 2020–2025 Jeep Gladiator (Rooftop Tent & Overland)$t$, $m$Gladiator bed racks verified for rooftop tents and cargo, with Trail Rail and bed-height notes.$m$, $i$With a removable roof, the Gladiator's bed rack is the overland platform. Racks either clamp to the bed rail cap or bolt into the Trail Rail channels. Bed rails sit high, so most tents end up level with the cab roof on a mid-height rack.$i$, $g$- **Trail Rail**: some racks use it as the mount; others need it removed.
- **Bed rail cap** is plastic — clamp racks need the padded feet.
- **Tent weight**: keep total (tent + gear + occupants when parked) under the rack's static rating.
- **Rubicon / Mojave** share the bed.$g$, $f$[{"q": "Can I mount a tent on the Gladiator roof instead?", "a": "Not on the removable hardtop — the bed rack is the correct load path."}, {"q": "Does the rack block the tailgate?", "a": "Mid-height and high racks clear a dropped tailgate; low-profile racks may not."}, {"q": "Will a Wrangler rack work?", "a": "No — different vehicle; Gladiator racks only."}]$f$::jsonb, $v$**Budget:** low-profile clamp rack. **Best overall:** mid-height with Trail Rail mounting. **Premium:** modular over-cab system.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='bed-racks'
WHERE m.slug='jeep' AND v.model_slug='gladiator' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Bed Racks for 2024–2025 Ford Ranger (Overland & Rooftop Tent)$t$, $m$Bed racks with confirmed 2024+ Ranger fitment — the new bed does not accept 2019–2023 racks.$m$, $i$The 2024 Ranger bed has no factory rail channels, so racks clamp to the bed rail cap or bolt through. Most Amazon racks are adjustable universal clamp designs listed across several generations — check the fit pill and confirm bed-width compatibility with the seller.$i$, $g$- **2019–2023 fitment is not automatic** — confirm 2024+ with the seller before ordering.
- **Bolt-through racks** need drilling — decide if you want holes in a new truck.
- **Raptor**: same bed, but check clearance with the wider fenders on over-cab racks.
- **Tonneau + rack** needs a combo system.$g$, $f$[{"q": "Do any 2024 Ranger racks avoid drilling?", "a": "Yes — clamp-style racks that grab the bed rail cap. Check the listing."}, {"q": "What tent size fits?", "a": "Up to a standard 2-person hardshell on a mid-height rack; check the rack's dynamic rating."}, {"q": "Will more racks come?", "a": "Yes — new-platform fitments arrive over 12–24 months. We update monthly."}]$f$::jsonb, $v$**Budget:** clamp-on low-profile. **Best overall:** mid-height clamp rack with confirmed 2024+ fit. **Premium:** modular system when available.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='bed-racks'
WHERE m.slug='ford' AND v.model_slug='ranger' AND v.gen_slug='2024-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Roof Racks & Crossbars for 2010–2024 Toyota 4Runner (Raised Rails vs TRD Pro)$t$, $m$Crossbars, platforms and baskets verified for the 5th-gen 4Runner's raised rails, with a separate answer for TRD Pro.$m$, $i$Most 5th-gen 4Runners have factory raised rails — crossbar kits clamp on with no drilling. TRD Pro trims ship with a factory basket rack instead, which needs basket-specific mounts. Roof load is 165 lb dynamic; that caps rooftop tents to lightweight softshells.$i$, $g$- **TRD Pro** = factory basket, no raised rails. Buy TRD-Pro-listed mounts.
- **165 lb dynamic roof load**: a 130 lb hardshell tent plus crossbars is at the limit — use the bed of a truck or a lightweight tent.
- **Sunroof**: rear crossbar must clear the glass when opened; most kits place it behind.
- **Rear window roll-down** is unaffected by racks.$g$, $f$[{"q": "Do I need to drill for a 4Runner rack?", "a": "No — raised-rail clamp crossbars or a full platform on the rails."}, {"q": "Can I put a rooftop tent on a 4Runner?", "a": "Lightweight ones (under ~120 lb) on a full-length platform; heavy hardshells exceed the 165 lb rating."}, {"q": "Do 5th-gen racks fit the 2025 4Runner?", "a": "No — new roof geometry. See the 2025+ page."}]$f$::jsonb, $v$**Budget:** aero crossbars on raised rails. **Best overall:** low-profile full-length platform. **TRD Pro:** basket-compatible platform adapter.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='roof-racks'
WHERE m.slug='toyota' AND v.model_slug='4runner' AND v.gen_slug='2010-2024'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Roof Racks & Crossbars for 2025+ Toyota 4Runner (6th Gen)$t$, $m$Crossbars and platforms with confirmed 2025+ 4Runner fitment — 5th-gen racks do not fit the new roof.$m$, $i$The 6th-gen 4Runner moved to the TNGA-F platform with a new roof and rail geometry, so 2010–2024 racks do not carry over. Trailhunter ships with a factory rack; other trims have raised rails. Verified 2025+ fitments only below.$i$, $g$- **5th-gen racks do not fit.**
- **Trailhunter** has a factory ARB-designed rack — buy accessories for it, not a second rack.
- **Roof load rating**: confirm in your owner's manual before a tent; early listings vary.
- **Hybrid (i-FORCE MAX)** has no roof-fit difference.$g$, $f$[{"q": "Can I reuse my old 4Runner crossbars?", "a": "No. Rail spacing and profile changed."}, {"q": "Which trims have raised rails?", "a": "All except Trailhunter (factory rack); verify on your build sheet."}, {"q": "Is stock limited?", "a": "Yes in 2026 — we list only confirmed fitments and update monthly."}]$f$::jsonb, $v$**Budget:** raised-rail crossbars listed for 2025+. **Best overall:** low-profile platform with 2025+ fit. **Trailhunter:** accessories for the factory rack.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='roof-racks'
WHERE m.slug='toyota' AND v.model_slug='4runner' AND v.gen_slug='2025-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Roof Racks for 2021–2025 Ford Bronco (Hardtop, Soft Top & 2-Door vs 4-Door)$t$, $m$Bronco roof racks verified by top type and door count, from hardtop crossbars to full exo-racks.$m$, $i$The Bronco's roof is removable, so racks mount one of three ways: crossbars on the hardtop's factory rail points, an exo-rack that bolts to the body, or nothing on a soft top. 2-door and 4-door need different rack lengths.$i$, $g$- **Soft top** = no roof rack; use a rear cargo carrier or exo-rack.
- **Hardtop rail points** exist on most hardtops; some early builds lack them — check for the plastic caps.
- **2-door vs 4-door** racks are different lengths.
- **Tailgate spare** blocks some rear-mounted cargo boxes when opened.$g$, $f$[{"q": "Can I put a rooftop tent on a Bronco hardtop?", "a": "Lightweight tents only, on rack systems rated for it; the hardtop is fiberglass and load-limited."}, {"q": "Do Wrangler racks fit the Bronco?", "a": "No — different roof and body mounts."}, {"q": "Do I lose the ability to remove the roof panels?", "a": "Front panels usually stay removable with rail crossbars; exo-racks vary."}]$f$::jsonb, $v$**Budget:** hardtop crossbars. **Best overall:** low-profile hardtop platform. **Heavy duty:** body-mounted exo-rack.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='roof-racks'
WHERE m.slug='ford' AND v.model_slug='bronco' AND v.gen_slug='2021-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Roof Racks & Crossbars for 2020–2025 Subaru Outback (Integrated Rails vs Wilderness)$t$, $m$Crossbars and platforms verified for the 6th-gen Outback's swing-out integrated rails, plus the fixed Wilderness rack.$m$, $i$Most 2020+ Outbacks have raised rails with integrated crossbars that swing out from the rails — great for occasional use, but capped at 176 lb and not ideal for tents or heavy boxes. Aftermarket kits either clamp to the rails with the factory bars stowed, or replace them. The Wilderness trim has a fixed ladder-style rack that takes different mounts.$i$, $g$- **Wilderness** = fixed rack, not swing-out bars; buy Wilderness-listed mounts.
- **Swing-out factory bars** must be stowed or removed for most aftermarket crossbars.
- **176 lb dynamic / 700 lb static (Wilderness)** — tents are viable on Wilderness only.
- **Sunroof** clearance: rear bar placement matters.$g$, $f$[{"q": "Can I use the factory swing-out bars for a cargo box?", "a": "Yes up to 176 lb total; for daily use aftermarket bars are stiffer."}, {"q": "Does the Wilderness roof hold a rooftop tent?", "a": "Yes — Subaru rates it for static tent loads; standard Outbacks are not."}, {"q": "Do Forester crossbars fit the Outback?", "a": "Some raised-rail clamp kits do; check the listing for both models."}]$f$::jsonb, $v$**Budget:** raised-rail clamp crossbars. **Best overall:** low-profile platform. **Wilderness:** ladder-rack-specific platform.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='roof-racks'
WHERE m.slug='subaru' AND v.model_slug='outback' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Roof Racks for 2020–2025 Tesla Model Y (Fixed-Point Glass Roof, Juniper Included)$t$, $m$Roof racks that mount to the Model Y's four fixed points — the only safe way to carry loads on the glass roof.$m$, $i$The Model Y has a panoramic glass roof with four hidden fixed mounting points under plastic caps. Only fixed-point crossbar kits fit — no clamp bars, no door-jamb bars, ever. Tesla's own rack and a handful of aftermarket kits use these points. The 2025 Juniper refresh keeps the same mount points.$i$, $g$- **Never use door-jamb or clamp crossbars** on the glass roof.
- **Juniper (2025+)** uses the same fixed points; listings that say 2020–2024 usually fit but confirm.
- **Load limit 165 lb** dynamic; tents are not recommended by Tesla.
- **Range**: expect a 5–10% hit with bars, more with a box.$g$, $f$[{"q": "Do Model 3 racks fit the Model Y?", "a": "No — different fixed-point spacing."}, {"q": "Can I leave the rack on?", "a": "Yes, but it costs range; remove when not needed."}, {"q": "Will a rack void the warranty?", "a": "Fixed-point kits used within the load rating do not; glass damage from clamp bars does."}]$f$::jsonb, $v$**Budget:** aftermarket fixed-point crossbars. **Best overall:** Tesla-spec bars with a low-drag box. **Bike carrier:** hitch mount instead of roof.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='roof-racks'
WHERE m.slug='tesla' AND v.model_slug='model-y' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Rooftop Cargo Boxes for 2019–2025 Toyota RAV4 (Raised Rails, Hybrid & Prime)$t$, $m$Cargo boxes and crossbar pairings verified for the 5th-gen RAV4, with sizing for the hatch and the rails.$m$, $i$The RAV4's raised rails (XLE and up) take standard clamp crossbars; LE has a bare roof and needs a different kit. A 12–16 cu ft box is the sweet spot — anything longer than 80 in can foul the hatch when open. Hybrid and Prime share the roof.$i$, $g$- **LE trim** has no rails — needs a bare-roof crossbar kit before any box.
- **Hatch clearance**: mount the box forward; boxes over 80 in long may hit the hatch.
- **165 lb dynamic roof load** includes bars + box + contents.
- **Adventure / TRD Off-Road** have the same rails.$g$, $f$[{"q": "Which crossbars do I need first?", "a": "Raised-rail clamp bars (XLE+) or a bare-roof kit (LE); the box mounts to the bars."}, {"q": "Will a box hit the RAV4 hatch?", "a": "Not if it is under 80 in and mounted forward on the bars."}, {"q": "How much can I put in the box?", "a": "Total roof load 165 lb minus bars (~10 lb) and box (~35–50 lb) leaves ~100 lb of cargo."}]$f$::jsonb, $v$**Budget:** 12 cu ft box + clamp bars. **Best overall:** 16 cu ft low-profile box. **Skis/long gear:** narrow 18 cu ft.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='cargo-boxes'
WHERE m.slug='toyota' AND v.model_slug='rav4' AND v.gen_slug='2019-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Rooftop Cargo Boxes for 2020–2025 Subaru Outback$t$, $m$Cargo boxes verified for the Outback's integrated crossbars and aftermarket rails, with hatch-clearance sizing.$m$, $i$The Outback's long roof takes big boxes well, but the factory swing-out bars sit close together — short boxes fit, long ones overhang. For 16 cu ft and up, use aftermarket bars with wider spread. Wilderness owners mount to the fixed rack.$i$, $g$- **Factory swing-out bars**: bar spread is fixed — check the box's minimum spread.
- **Hatch clearance** is generous on the Outback; most boxes under 90 in are fine.
- **Wilderness**: use ladder-rack mounts, not clamp bars.
- **176 lb roof load** limit.$g$, $f$[{"q": "Can I mount a cargo box on the factory Outback crossbars?", "a": "Yes if the box's mounting slots match the factory bar spread; most 12–16 cu ft boxes do."}, {"q": "Do I need aftermarket bars?", "a": "For 18+ cu ft boxes or frequent use, yes — stiffer and adjustable spread."}, {"q": "Will the box work with a sunroof?", "a": "Yes; place the front bar so the sunroof tilts without touching."}]$f$::jsonb, $v$**Budget:** 13 cu ft box on factory bars. **Best overall:** 16 cu ft on aftermarket bars. **Wilderness:** rack-mounted box up to 18 cu ft.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='cargo-boxes'
WHERE m.slug='subaru' AND v.model_slug='outback' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Rooftop Cargo Boxes for 2020–2025 Kia Telluride$t$, $m$Cargo boxes and crossbar pairings verified for the Telluride's raised rails and long roof.$m$, $i$The Telluride's flat, long roof with raised rails is one of the easiest three-row SUVs to load: clamp crossbars, then almost any box up to 22 cu ft fits without hatch issues. Roof load is 220 lb, higher than most rivals.$i$, $g$- **Raised rails** on every trim; factory crossbars are an accessory — aftermarket clamp bars are usually better.
- **Hatch clearance** is good; boxes to 90 in fit mounted forward.
- **X-Pro / X-Line** share the rails.
- **Panoramic sunroof** — keep the front bar behind the tilt line.$g$, $f$[{"q": "Do I need Kia crossbars?", "a": "No — aftermarket raised-rail clamp bars fit and are usually stiffer."}, {"q": "Biggest box the Telluride can take?", "a": "Up to ~22 cu ft with a 220 lb roof load; watch total weight with contents."}, {"q": "Palisade the same?", "a": "Yes for the roof; Palisade boxes and bars interchange."}]$f$::jsonb, $v$**Budget:** 14 cu ft + clamp bars. **Best overall:** 18 cu ft low-profile. **Family road trips:** 21–22 cu ft.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='cargo-boxes'
WHERE m.slug='kia' AND v.model_slug='telluride' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Trailer Hitches for 2022–2025 Ford Maverick (Class III 2 in Receiver)$t$, $m$Bolt-on Class III hitches verified for the Maverick, plus what the factory 4K Tow Package already gives you.$m$, $i$Mavericks without the 4K Tow Package have no receiver (or a 1.25 in Class I on some builds). Aftermarket Class III hitches bolt to the existing frame holes and add a 2 in receiver for bike racks, cargo carriers and small trailers — within the truck's 2,000 lb (hybrid) or 4,000 lb (4K package) rating.$i$, $g$- **Hitch rating ≠ truck rating**: a Class III hitch says 5,000 lb, but the Maverick tows 2,000 lb (hybrid) or 4,000 lb (EcoBoost + 4K package).
- **4K Tow Package trucks** already have a 2 in receiver and 7-pin — no hitch needed.
- **Wiring** is separate: 4-pin harness plugs into the taillight connector.
- **Spare tire** under the bed may need lowering to fit some hitches.$g$, $f$[{"q": "Can I tow with a hybrid Maverick?", "a": "2,000 lb max. Fine for a small utility trailer or jet ski."}, {"q": "Do I need to drill?", "a": "No — bolt-on to factory holes; 30–45 min with a jack."}, {"q": "Is a 2 in receiver worth it just for a bike rack?", "a": "Yes — 2 in hitch bike racks are stiffer and carry e-bikes."}]$f$::jsonb, $v$**Bike rack only:** Class III bolt-on 2 in. **Towing:** same hitch + 4-pin harness. **Already have 4K package:** buy only a ball mount.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='hitches'
WHERE m.slug='ford' AND v.model_slug='maverick' AND v.gen_slug='2022-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Trailer Hitches for 2019–2025 Toyota RAV4 (Hybrid & Prime Included)$t$, $m$Class III 2 in hitches verified for the 5th-gen RAV4 with ratings by trim, hybrid battery clearance and wiring notes.$m$, $i$Most RAV4s leave the factory with no receiver. Aftermarket Class III hitches give a 2 in receiver for bike racks and small trailers. Tow rating is 1,500 lb on most trims, 3,500 lb on Adventure / TRD Off-Road — the hitch never raises that.$i$, $g$- **Hybrid / Prime**: the battery sits ahead of the rear axle; hitches list hybrid compatibility — buy those.
- **Bumper cover trimming** is required on some hitches; 'no-cut' hitches exist and cost more.
- **Tow rating by trim**: 1,500 lb standard; 3,500 lb Adventure / TRD Off-Road.
- **Wiring**: 4-pin plug-and-play harness available.$g$, $f$[{"q": "Can a RAV4 Hybrid tow?", "a": "1,750 lb (Hybrid) / 2,500 lb (Prime) — check your owner's manual; the hitch does not change it."}, {"q": "Hidden or visible hitch?", "a": "Hidden hitches sit behind the bumper and need trimming; visible ones bolt below with no cut."}, {"q": "1.25 in or 2 in?", "a": "2 in — better bike-rack selection and no adapter wobble."}]$f$::jsonb, $v$**Bike rack:** no-cut Class III 2 in. **Light towing:** same + 4-pin harness. **Adventure/TRD:** hitch + brake controller not needed under 3,500 lb.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='hitches'
WHERE m.slug='toyota' AND v.model_slug='rav4' AND v.gen_slug='2019-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Trailer Hitches for 2020–2025 Tesla Model Y (Bike Racks, Cargo & 3,500 lb Tow)$t$, $m$Hitches verified for the Model Y — the factory Tow Package option, the retrofit, and aftermarket 2 in receivers.$m$, $i$The Model Y tows 3,500 lb with Tesla's Tow Package (2 in receiver + trailer mode). If you didn't order it, you have two options: Tesla's retrofit, or an aftermarket bolt-on 2 in receiver for bike racks and cargo carriers (no trailer mode, so no towing without it).$i$, $g$- **Aftermarket hitch = no Trailer Mode** — fine for bike racks, not for towing.
- **Juniper (2025+)**: check the listing — rear structure changed slightly.
- **Tongue weight** for bike racks: keep under 160 lb on aftermarket hitches.
- **Range** drops 15–30% with a loaded rack.$g$, $f$[{"q": "Can I tow with an aftermarket Model Y hitch?", "a": "Not advised — no trailer mode disables stability logic. Use it for racks and carriers."}, {"q": "Is the Tesla retrofit worth it?", "a": "If you tow, yes. For a bike rack, aftermarket is a third of the price."}, {"q": "Does a hitch affect the rear camera or sensors?", "a": "Standard bolt-on receivers do not; some cargo carriers trigger parking sensors."}]$f$::jsonb, $v$**Bike rack:** aftermarket 2 in bolt-on. **Towing:** Tesla Tow Package / retrofit. **Cargo carrier:** aftermarket + lightweight aluminum tray.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='hitches'
WHERE m.slug='tesla' AND v.model_slug='model-y' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Trailer Hitches for 2020–2025 Toyota Highlander (Class III, 5,000 lb)$t$, $m$Class III hitches verified for the 4th-gen Highlander and Highlander Hybrid, with wiring and no-cut options.$m$, $i$The Highlander is rated 5,000 lb with the factory tow package; without it, an aftermarket Class III hitch bolts to the frame for bike racks, cargo carriers and small trailers. Hybrids share the hitch fitment.$i$, $g$- **Grand Highlander** is a different vehicle — separate hitches.
- **Hybrid** shares the fitment; verify the listing includes Hybrid.
- **No-cut vs trim**: most Highlander hitches are no-cut; a few require removing a lower fascia panel.
- **7-pin** needs a converter for trailer brakes; 4-pin harness is plug-and-play.$g$, $f$[{"q": "Can I tow 5,000 lb without the factory tow package?", "a": "The hitch is rated for it, but Toyota's 5,000 lb rating assumes the package's transmission cooler. Without it, treat 3,500 lb as the practical limit."}, {"q": "Which wiring do I need?", "a": "4-pin for lights only; 7-pin plus brake controller for trailers over 1,500 lb with brakes."}, {"q": "Is a hidden hitch available?", "a": "Yes — behind-bumper Class III units with a removable receiver tube."}]$f$::jsonb, $v$**Bike rack:** no-cut Class III. **Towing:** Class III + 7-pin + brake controller. **Clean look:** hidden hitch with removable tube.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='hitches'
WHERE m.slug='toyota' AND v.model_slug='highlander' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Floor Mats & Liners for 2025+ Toyota 4Runner (6th Gen)$t$, $m$Laser-fit floor liners and rubber mats with confirmed 2025+ 4Runner fitment — 5th-gen mats do not fit.$m$, $i$The 6th-gen 4Runner has a new floor, so 2010–2024 mats are the wrong shape. This list covers full-coverage liners (raised edges) and flat rubber mats, for 2-row and 3-row (Limited / Platinum) configurations.$i$, $g$- **5th-gen mats do not fit.**
- **3rd row** (Limited/Platinum) needs the 3-row set; 2-row sets leave the third row bare.
- **Hybrid (i-FORCE MAX)** has a raised cargo floor — cargo liners differ from non-hybrid.
- **Factory retention hooks** are used by fitted liners; flat mats rely on nibs.$g$, $f$[{"q": "Do 5th-gen 4Runner mats fit the 2025?", "a": "No. New floor pan and hooks."}, {"q": "Which cargo liner for a hybrid?", "a": "One listed for i-FORCE MAX — the floor is higher and the shape differs."}, {"q": "Liner or mat?", "a": "Liners for mud/snow (raised lip); rubber mats if you want cheaper and easier to clean."}]$f$::jsonb, $v$**Budget:** rubber mats listed for 2025+. **Best overall:** laser-fit liners, 2-row or 3-row. **Hybrid:** liners + hybrid-specific cargo liner.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='floor-mats'
WHERE m.slug='toyota' AND v.model_slug='4runner' AND v.gen_slug='2025-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Floor Mats & Liners for 2023–2025 Honda CR-V (Incl. Hybrid)$t$, $m$Fitted floor liners and rubber mats verified for the 6th-gen CR-V and CR-V Hybrid — 2017–2022 mats do not fit.$m$, $i$The 2023 CR-V grew and changed its floor, so previous-gen mats are the wrong shape. Hybrid and gas share the front and rear floor; the cargo area differs because the Hybrid's floor sits slightly higher.$i$, $g$- **2017–2022 mats do not fit** the 2023+ floor.
- **Hybrid cargo floor** is different — buy Hybrid-listed cargo liners.
- **Rear seat 40/60 split** is unaffected by mats.
- **Retention**: fitted liners use the two front hooks.$g$, $f$[{"q": "Do Hybrid and gas CR-V share floor mats?", "a": "Front and rear passenger mats, yes. Cargo liners, no."}, {"q": "Which is better for snow?", "a": "Raised-edge liners — they hold slush; flat mats spill."}, {"q": "Do mats fit the Sport Touring?", "a": "Yes — all 2023+ trims share the floor."}]$f$::jsonb, $v$**Budget:** rubber mats. **Best overall:** laser-fit liners front + rear. **Dog owners:** liners + Hybrid/gas-specific cargo liner.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='floor-mats'
WHERE m.slug='honda' AND v.model_slug='cr-v' AND v.gen_slug='2023-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Floor Mats & Liners for 2020–2025 Tesla Model Y (Juniper vs Pre-Refresh)$t$, $m$All-weather liners and mats verified for the Model Y, split for 2020–2024 and the 2025 Juniper refresh, including frunk, trunk well and 7-seat.$m$, $i$The Model Y has more mat zones than most SUVs: front, rear, trunk floor, trunk well, frunk and — on 7-seaters — the third row. The 2025 Juniper refresh changed the floor and centre console, so mats are not interchangeable across the refresh.$i$, $g$- **Juniper (2025+)** mats ≠ 2020–2024 mats. Check the year on every piece.
- **7-seat** needs a third-row set and a different trunk floor mat.
- **Frunk liner** is worth it — it takes wet gear.
- **Trunk well liner** must match the sub-trunk depth (changed on Juniper).$g$, $f$[{"q": "Do Model 3 mats fit the Model Y?", "a": "Front mats, no; some sellers cross-list but the shape differs."}, {"q": "What's in a full set?", "a": "Front, rear, trunk floor, trunk well, frunk — five pieces; seven with third row."}, {"q": "Are Tesla OEM mats better?", "a": "Similar quality to top laser-fit brands at roughly double the price."}]$f$::jsonb, $v$**Budget:** 3-piece cabin set. **Best overall:** 5-piece laser-fit set for your year. **7-seat:** 7-piece set listed for your year.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='floor-mats'
WHERE m.slug='tesla' AND v.model_slug='model-y' AND v.gen_slug='2020-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Floor Mats & Liners for 2022–2025 Jeep Grand Cherokee (WL, 4xe, and L)$t$, $m$Floor liners verified for the WL Grand Cherokee, with separate notes for the 4xe hybrid and the three-row Grand Cherokee L.$m$, $i$The 2022+ WL platform has different floors for the two-row Grand Cherokee and the three-row Grand Cherokee L, and the 4xe hybrid changes the cargo floor. Match all three variables — model, rows, powertrain — before buying.$i$, $g$- **Grand Cherokee L** (3-row) has a longer rear floor; 2-row liners will not fit.
- **4xe**: cargo floor is higher; use 4xe-listed cargo liners.
- **2011–2021 WK2 mats do not fit** the WL.
- **Rear seat heaters / vents** don't interfere.$g$, $f$[{"q": "Do WK2 (2011–2021) mats fit the 2022+?", "a": "No — new floor pan."}, {"q": "Is the L cargo liner the same as the 2-row?", "a": "No — different shape and third-row cutouts."}, {"q": "Do 4xe front mats differ?", "a": "No — only the cargo area."}]$f$::jsonb, $v$**Budget:** rubber mats. **Best overall:** laser-fit liners front + rear. **L / 4xe:** full set listed for your exact variant.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='floor-mats'
WHERE m.slug='jeep' AND v.model_slug='grand-cherokee' AND v.gen_slug='2022-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Floor Mats & Liners for 2021–2025 Ford F-150 (SuperCrew, SuperCab, Lightning)$t$, $m$Fitted floor liners verified for the 14th-gen F-150 by cab and features — rear under-seat storage, Lightning and the Interior Work Surface.$m$, $i$The 14th-gen F-150 has three cab types and several features that change mat shape: the fold-flat rear seat with under-seat storage, the Max Recline front seats, and the Lightning's flat floor. Match cab + those options.$i$, $g$- **SuperCrew vs SuperCab** rear mats differ; Regular Cab has no rear.
- **Rear under-seat storage / fold-flat floor** (Lariat+) has a different rear mat shape.
- **Lightning** shares front mats; rear mats differ on some trims due to the flat floor.
- **Vinyl floor (XL)** takes the same liners as carpet.$g$, $f$[{"q": "Do 2015–2020 F-150 mats fit the 2021+?", "a": "Front, sometimes; rear, no. Buy 2021+ listings."}, {"q": "Do Lightning mats differ?", "a": "Front mats are shared; check the listing for the rear."}, {"q": "One-piece rear or two-piece?", "a": "One-piece if you have the fold-flat floor; two-piece if the hump is present."}]$f$::jsonb, $v$**Budget:** rubber mats. **Best overall:** laser-fit liners front + rear for your cab. **Work truck:** liners + rear seat cover.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='floor-mats'
WHERE m.slug='ford' AND v.model_slug='f-150' AND v.gen_slug='2021-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best LED Light Bars for 2018–2025 Jeep Wrangler JL (Hood, Bumper & Windshield Mounts)$t$, $m$LED light bars and brackets verified for the JL Wrangler, by mount position, with wiring and legality notes.$m$, $i$The JL Wrangler takes light bars in four places: hood cowl (20–22 in), stubby/steel bumper (20–30 in), windshield / A-pillar (50–52 in) and the roof (only with a rack). Brackets are JL-specific and often sold separately — check whether the bar includes them.$i$, $g$- **JK brackets do not fit** the JL windshield or hood.
- **52 in windshield bars** need JL-specific A-pillar brackets and cause wind noise on soft tops.
- **Factory bumper** (plastic) needs a bumper-specific bracket; steel aftermarket bumpers have tabs.
- **Legality**: forward-facing auxiliary lights must be covered on public roads in many states — see the state law pages.$g$, $f$[{"q": "Which bar fits a stock JL bumper?", "a": "20–22 in bars with a JL plastic-bumper bracket kit, or a cowl-mount 20 in bar."}, {"q": "Do I need a wiring harness?", "a": "Yes — use a relay harness with a dash switch; never tap the headlight circuit."}, {"q": "Are 52 in windshield bars legal?", "a": "Only off-road in most states unless covered. Check your state's aux-light rule."}]$f$::jsonb, $v$**Budget:** 20 in cowl-mount bar + harness. **Best overall:** 20 in bumper bar with relay harness. **Off-road:** 52 in curved windshield bar + covers.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='led-light-bars'
WHERE m.slug='jeep' AND v.model_slug='wrangler' AND v.gen_slug='2018-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();

INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t$Best Tonneau Covers for 2024–2025 Toyota Tacoma (4th Gen, 5 ft & 6 ft Bed)$t$, $m$Tonneau covers with confirmed 2024+ Tacoma fitment — the new composite bed and deck rails do not accept 2016–2023 covers.$m$, $i$The 4th-gen Tacoma keeps a composite bed with deck rails, but the bed rail cap and width changed, so 2016–2023 covers do not fit. Two beds: 5 ft (60 in) and 6 ft (74 in). Hybrid i-FORCE MAX trucks share the bed.$i$, $g$- **2016–2023 covers do not fit.**
- **Deck rail cleats** may need sliding for clamp-style side rails.
- **Composite rail cap**: padded clamps, torque to spec.
- **Trailhunter / TRD Pro** share the bed; Trailhunter's bed utility bar conflicts with some hard covers.$g$, $f$[{"q": "Can I reuse a 3rd-gen Tacoma cover?", "a": "No — bed width and rail cap changed in 2024."}, {"q": "Which Tacoma trims have the 6 ft bed?", "a": "Xtracab (2-door) and some SR/SR5 Double Cab builds; measure to confirm."}, {"q": "Does the hybrid change anything?", "a": "No bed-mounted hardware; same covers."}]$f$::jsonb, $v$**Budget:** soft roll-up listed for 2024+. **Best overall:** hard tri-fold with confirmed 2024+ fit. **Premium:** retractable as fitments arrive.$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='tonneau-covers'
WHERE m.slug='toyota' AND v.model_slug='tacoma' AND v.gen_slug='2024-present'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();
