"""Explainer pillar — Floor Mats vs Floor Liners.
No invented testing. Material names, warranty terms, temperature ratings and prices below were read on the maker
pages listed in sources: most via the site's fit-checked floor-liner guides (checked 2026-09-24), the rest on the
WeatherTech pages and the NHTSA-hosted Toyota recall notice fetched 2026-10-03.
"""

KIND = "explainer"
SLUG = "floor-mats-vs-floor-liners"
CATEGORIES = ["floor-mats"]

TITLE = "Floor Mats vs Floor Liners: Coverage, Materials and Fit Compared"
META = ("Floor mats vs floor liners compared on wall height, TPE vs rubber, retention posts, cold ratings, "
        "cleaning, warranty and price bands from about $70 to $280.")

FAQ = [
 ("What is the difference between floor mats and floor liners?",
  "A floor mat is a flat sheet of carpet or rubber that covers the area under your feet. A floor liner is a molded tray cut to one vehicle's floor pan, with raised edges that run up the sides of the footwell to hold water, mud and snow. The mat protects what it covers and nothing more; anything that runs off the edge reaches the carpet. The liner contains the mess until you empty it. That difference in shape is also why liners are sold by generation, cab and seating layout, while flat mats are more forgiving about fit."),
 ("Are floor liners worth it over rubber mats?",
  "If the vehicle sees snow, salt, mud, kids or a dog, yes. The value of a liner is the wall: WeatherTech describes a raised lip that traps drink spills, tracked-in snow, mud, sand and rain, and a flat rubber mat has nothing to stop that water once it reaches the edge. In a dry climate with clean shoes, a flat mat does the job for less money and is easier to pull out and shake. On the site's guides, a two-row budget liner set starts at about $70 to $110, so the price gap to a decent rubber mat is often small."),
 ("Is TPE better than rubber for floor liners?",
  "Neither wins on every count. TPE (thermoplastic elastomer) is lighter, holds a molded shape and tall walls well, and has little odor. Rubber is heavier, which helps it stay put, and it stays more flexible in the cold, but rubber sets on the site's guides have lower walls than molded TPE liners. Makers also blend their own versions: WeatherTech calls its FloorLiner material a patented TPE blend that is rigid yet flexible, and Husky uses its own ProGard formula. Fit, wall height and driver-side retention matter more than the name of the compound."),
 ("Can I put floor liners on top of my factory mats?",
  "No. Take the factory mat out first, every time. A liner is shaped to sit directly on the carpet and lock onto the driver-side retention posts or hooks, and those are built for one mat. A Toyota recall notice in NHTSA's files says it plainly: more than one floor mat should never be used in the driver's seating position, because the retaining hooks are designed to accommodate only one floor mat at a time. A stacked liner can slide forward and hold a pedal. Store the carpet mats in the garage for resale day."),
 ("Do universal trim-to-fit floor mats work?",
  "They work as a cheap cover for rear footwells, older vehicles and short-term use. They are a poor choice for the driver's side. A universal mat is one shape trimmed with scissors, so it rarely lines up with the factory retention posts and it has no walls shaped to the footwell to hold it in place. That leaves it free to creep toward the pedals. If the budget only stretches to one custom part, buy a vehicle-specific front pair, which runs about $70 to $130 on the site's guides, and use trim-to-fit mats in the back."),
 ("Do floor liners crack or get stiff in the cold?",
  "Some do, and the maker's paperwork is the best guide. LASFIT rates its TPE liners for −13°F to 167°F. Husky backs WeatherBeater liners with a lifetime warranty against cracks and breaks, which is the usual way a rigid liner fails on a vehicle parked outside in winter. Husky also says its X-act Contour line is 22% more flexible and 10% softer than WeatherBeater. A liner that stiffens and curls at the edges stops sealing at the door sill, so in a northern state prefer a brand that states a cold rating or a crack warranty."),
 ("How do I clean floor liners?",
  "Pull them out, shake off the loose dirt, hose them down and scrub with mild soap and a stiff brush. WeatherTech says its FloorLiner can be hosed down, pressure washed or wiped clean. Let the liner dry before it goes back in, so water isn't trapped between the liner and the carpet. Skip tire shine and silicone protectants: they make the surface slick under wet shoes, which is the last thing you want next to the pedals. In salt season, empty the trays every few days so melted slush doesn't spill over the walls."),
 ("How much do floor liners cost?",
  "On the site's F-150, Silverado 1500 and RAV4 guides, budget two-row TPE sets run about $70 to $150, laser-fit TPE sets from brands that publish specs about $120 to $170, Husky WeatherBeater two-row sets about $130 to $230, and WeatherTech two-row sets about $200 to $280. A front-row pair alone is about $70 to $130, and a molded cargo liner about $90 to $140. Amazon prices move daily, and the same brand costs more for a large crew-cab truck than for a compact SUV, so treat these as bands and check the live price."),
 ("Do I need liners for every row?",
  "Only for the rows people use. The front footwells get dirty first, so a front pair is the sensible first purchase if the back seat is usually empty. Add the second row if you carry passengers, and a third-row piece only if that row is in regular use. On an SUV, a cargo liner often matters more than a third-row liner, because that is where groceries, sports gear and wet dogs go. Buying in stages also gives you time to check which rear seat and storage layout your vehicle has before ordering the rear piece."),
 ("Will floor liners from the same model but a different year fit?",
  "Sometimes. Liners follow the floor pan, and makers split part numbers when the floor changes. Husky lists its WeatherBeater 94041 set for 2015 through 2026 F-150 SuperCrew trucks, which spans two generations because the cab floor carried over. The 2019 RAV4, by contrast, moved to a new platform and 2013–2018 liners don't fit it. Within one generation, a seat or storage option can still change the rear piece. Read the year range, the cab and the layout notes in the listing rather than trusting the model name."),
]

ARTICLE = {
 "dek": "A floor mat lies flat on the carpet. A floor liner is a molded tray with raised walls, cut to one vehicle's floor pan. Here is how the two differ on coverage, materials, pedal safety, cold weather, cleaning, price and warranty, using maker pages and the site's fit-checked guides instead of marketing.",
 "author": "jake-morrison",
 "reviewed": "2026-10-03",
 "method": "We did not install or test these mats and liners. This page compares the types using what makers publish (material names, wall design, retention, origin, warranty, temperature ratings) on the WeatherTech, Husky Liners and LASFIT pages that the site's floor-liner guides read in September 2026, plus two WeatherTech pages and a Toyota recall notice held by NHTSA, fetched on 2026-10-03. Price bands are the ones recorded in the site's F-150, Silverado 1500 and RAV4 guides. Where a maker publishes nothing, we say so. For part numbers that fit your vehicle, use the guides linked below.",
 "takeaways": [
  "**The wall is the difference:** a mat is flat and stops at its edge; a liner is a molded tray with a raised lip that holds water, mud and snow.",
  "**Liners are vehicle-specific:** they are laser-measured to one floor pan, so generation, cab, seat layout and under-seat storage decide the part number.",
  "**One mat on the driver's side, hooked down:** never stack a liner on a factory mat; retention hooks are designed for one mat at a time.",
  "**Material names are mostly brand names:** WeatherTech's TPE blend, Husky's ProGard and LASFIT's recycled TPE differ in feel; fit and wall height matter more.",
  "**Prices overlap less than you'd think:** about $70–$150 for a budget two-row TPE set, about $130–$230 for Husky WeatherBeater and about $200–$280 for WeatherTech.",
 ],
 "compare_table": {
  "caption": "Floor protection types compared (price bands from the site's F-150, Silverado 1500 and RAV4 guides)",
  "head": ["Type", "Shape", "Fit", "Containment", "Driver-side retention", "Price band", "Best for"],
  "rows": [
   ["Carpet mat (factory style)", "Flat, carpet pile on a backing", "Cut to the footwell outline", "None; soaks up water", "Factory posts or hooks", "Not covered in the site's guides", "Dry climates, appearance"],
   ["Universal trim-to-fit rubber mat", "Flat with molded grooves", "One shape, trimmed with scissors", "Grooves only; runs off the edge", "Rarely reaches the posts", "Not covered in the site's guides", "Rear rows, older vehicles"],
   ["Custom rubber liner", "Heavy molded rubber, medium walls", "Vehicle and layout specific", "Medium", "Post holes per listing", "About $90–$130 (KUST, two rows)", "Budget, storage-box trucks"],
   ["Budget TPE liner", "Molded tray, raised edges", "Vehicle and layout specific", "Medium to medium-high", "Post holes per listing", "About $70–$150 (two rows)", "Most family vehicles"],
   ["Laser-fit TPE with published specs", "Molded tray, softer surface", "3D laser-scanned (LASFIT)", "Medium-high", "Post holes per listing", "About $120–$170 (two rows)", "Value with a stated cold rating"],
   ["Premium molded liner", "Firm tray, high walls", "Laser-measured (Husky, WeatherTech)", "High", "Factory hooks and retention devices", "About $130–$280 (two rows)", "Winter states, work trucks, long-term owners"],
   ["Cargo liner", "One-piece tray for the load floor", "Vehicle and powertrain specific", "High", "Not applicable", "About $90–$140 (Husky 25501)", "SUVs that haul gear or dogs"],
  ],
 },
 "sections": [
  {"h": "Flat mat or molded tray: how each one works",
   "body": "A floor mat is a flat sheet. Factory carpet mats are a pile surface on a backing, cut to the outline of the footwell and held by the vehicle's retention posts or hooks. All-weather mats swap the carpet for rubber or a similar compound with grooves molded into the top. Both protect the area under your feet and stop there. The edge of the mat is the edge of the protection, and whatever runs off it lands on the carpet.\n\nA floor liner is a tray. The maker measures one vehicle's floor pan and molds a part that follows it, then raises the edges into walls. WeatherTech describes its FloorLiner as laser measured \"to protect the front, back and even up the sides\" of the footwell, with a raised lip that traps drink spills, tracked-in snow, mud, sand and rain. Husky says its WeatherBeater liners are laser-measured using vehicle-specific data, and LASFIT says its liners are 3D laser-scanned.\n\nThat method has two consequences. First, a liner holds a puddle that a mat would shed onto the carpet, which is the whole reason to buy one in snow country. Second, a liner only fits the floor it was measured from. A flat mat tolerates a floor that is a little different; a molded tray with walls does not. That is why liners are sold by generation, cab, seat layout and sometimes powertrain, and why every guide on this site starts with the fit question rather than the brand."},
  {"h": "Materials: carpet, rubber, TPE and the makers' own names",
   "body": "Most of the material names on listings are brand names for a maker's own compound, so read them as a description of feel rather than a ranking.\n\n**Carpet** looks the most finished and is quiet underfoot, but it absorbs water and salt and has to be dried or shampooed.\n\n**Rubber** is heavy and grips well underfoot. On the site's Silverado guide, the KUST rubber set is described as heavy enough to stay put, with lower walls than a molded TPE liner and more weight to carry to the hose.\n\n**TPE (thermoplastic elastomer)** is the material most liners use. It is lighter than rubber, has little odor and holds a molded shape, which is what lets the walls stand up. Within TPE, makers tune the feel. WeatherTech calls its FloorLiner material a patented TPE blend that is \"rigid yet flexible\", built on high-density core materials, and says it contains no latex, PVCs, cadmium or lead and is 100% recyclable. Its FloorLiner HP is injection molded from what WeatherTech calls a rubber-like TPE with a soft-touch feel. Husky's WeatherBeater uses its ProGard formula, which Husky positions as its firmer, traditional liner; its X-act Contour line is 22% more flexible and 10% softer, according to Husky. LASFIT says its liners are GRS-certified recycled TPE, free of PVC and phthalates.\n\nFirm liners hold their walls and shape better. Softer ones grip a wet boot better and fold more easily for cleaning. You may see other abbreviations and trade names on listings. We repeat only the ones on pages we read; if a listing uses a name that isn't in the table below, ask the seller what the base material is.",
   "table": {"caption": "How makers describe their liner materials (maker pages listed in sources)",
             "head": ["Product", "Material as the maker names it", "What the maker says about it"],
             "rows": [["WeatherTech FloorLiner", "Patented TPE blend", "Rigid yet flexible; high-density core; no latex, PVCs, cadmium or lead; 100% recyclable"],
                      ["WeatherTech FloorLiner HP", "Injection-molded TPE", "Rubber-like, soft-touch feel; beveled high walls; anti-skid underside"],
                      ["Husky WeatherBeater", "ProGard", "Firm, traditional liner; StayPut nibs underneath; made in the USA"],
                      ["Husky X-act Contour", "Husky's softer formula", "22% more flexible and 10% softer than WeatherBeater; DuraGrip surface"],
                      ["LASFIT", "GRS-certified recycled TPE", "No PVC or phthalates; rated −13°F to 167°F"],
                      ["KUST", "Rubber (per listing)", "No maker spec page the site's guide could check"]]}},
  {"h": "Coverage and containment: walls, sills and the center hump",
   "body": "Coverage is where a liner earns its price. Three areas decide how much carpet stays dry.\n\n- **The door sill.** Shoes drag over the sill edge every time someone climbs in, and on a truck that edge takes the most abuse. Look at how high the liner rises at the door opening and whether it stops short of the sill plate.\n- **The sides of the footwell.** A front liner that covers the carpet up the side of the center console and the dead pedal is worth more than one that stops at the floor. WeatherTech's FloorLiner HP uses high walls with a beveled edge that, in WeatherTech's words, keeps them from curving in.\n- **The rear hump.** The second-row pieces in the site's truck guides are one-piece liners that run across the rear floor, including the center hump, so there is no gap between two separate mats for slush to find.\n\nDeeper walls hold more water but are stiffer to fit, and a wall only helps if you empty it. The site's guides note that softer TPE sets such as LASFIT's have a shallower lip at the sill than Husky's WeatherBeater, so deep slush can reach the carpet at the edge if it is left to build up. A flat mat, whether carpet or trim-to-fit rubber, has no wall at all. Its grooves hold a little water under your heels, and the rest runs to the lowest edge.\n\nOne limit applies to every type: front liners cover the footwells, not the floor under the seats or the full width of a bench truck's center floor. On a 40/20/40 front bench, two-piece front liners leave the middle strip exposed unless the set includes a center piece."},
  {"h": "Retention posts, hooks and pedal safety",
   "body": "The driver's mat is the only one that can cause a crash, so treat its retention as a safety item rather than a convenience.\n\nVehicles have retention posts or hooks in the driver footwell to stop the mat from sliding forward. A Toyota safety recall notice from 2007, held in NHTSA's recall files, describes what happens when an all-weather mat is not secured: \"the mat can move forward and interfere with the accelerator pedal returning to the idle position.\" The same notice gives the rule that every liner maker repeats: \"More than one floor mat should never be used in the driver's seating position, as the retaining hooks (clips) are designed to accommodate only one floor mat at a time.\" It also says that a properly secured mat will not interfere with the pedal.\n\nIn practice that means four things:\n\n1. Remove the factory mat before fitting a liner. Never stack.\n2. Buy a driver liner cut for your vehicle's posts or hooks. WeatherTech says its FloorLiner works with factory hooks and retention devices; Husky adds StayPut nibs on the underside to grip the carpet.\n3. After fitting, push the liner toward the pedals with your heel. If it moves more than a fraction of an inch, it isn't seated.\n4. Press the brake and accelerator through their full travel before the first drive, and check again after every cleaning.\n\nOn a vinyl floor, as on some F-150 XL trucks, nibs have less to grip, so the posts and the walls do the work. Husky's 94041 listing specifies carpeted floors for that reason."},
  {"h": "Universal trim-to-fit vs custom fit",
   "body": "A universal mat is one shape sold for hundreds of vehicles, with trim lines you cut along until it roughly matches the footwell. A custom-fit mat or liner is made for one floor pan.\n\nThe universal mat's advantages are price and convenience: one part number, in stock everywhere, and it moves with you to the next vehicle. Its weaknesses are the ones that matter most.\n\n- **Retention.** A trimmed mat may not reach the factory posts, so nothing stops it from sliding forward. On the driver's side that is the failure described in the recall notice above.\n- **Edges.** Once trimmed, the mat ends wherever your scissors stopped. There is no wall, and gaps at the console and sill let water through.\n- **Shape.** A flat sheet can't follow a dead pedal, a footwell that rises toward the firewall or a rear hump.\n\nCustom fit costs more and is less forgiving. A liner bought for the wrong generation, cab or seat layout simply won't lie flat. The site's guides list the layouts each set names for that reason.\n\nA sensible split, if money is tight: a vehicle-specific pair for the front row, which the site's guides put at about $70–$130, and trim-to-fit mats in the rear footwells, where nothing can reach a pedal. Replace the rear ones with a fitted second-row liner when the budget allows."},
  {"h": "Rows, seats and storage: why the layout changes the part number",
   "body": "Front footwells are fairly consistent within a generation. The rear floor is where orders go wrong, because seat and storage options change its shape. The site's guides found these splits in listings and maker fit notes:\n\n- **Under-seat storage.** F-150 SuperCrew trucks come with a plain rear floor, under-seat storage or a fold-flat load floor, and Husky sells a different second-row piece for fold-flat trucks. Silverado 1500 Crew Cabs come with carpeted storage, a molded plastic storage box or neither, and listings name which one they fit.\n- **Bench or buckets.** On the Silverado, front liners wrap up the side of the console or the bench base, so the cut differs. LASFIT's Silverado set is listed for bucket seats only, and WeatherTech sells its front-bench layout under separate part numbers.\n- **Cab.** A Double Cab has a shorter rear floor than a Crew Cab and takes its own rear liner, even when the front pair is shared.\n- **Powertrain.** On the 2019–2025 RAV4, Husky's WeatherBeater set and its front pair are both listed as not fitting hybrid models, and cargo liners differ by powertrain too.\n- **Second-row seats and third rows.** On three-row vehicles, a second-row bench and captain's chairs use different liners, and the third row is usually a separate piece.\n\nBefore ordering a rear piece, lift the rear cushions, look at the floor and compare it with the listing photos. It takes thirty seconds and prevents the most common return.",
   "table": {"caption": "Layout details that change which liner fits (from the site's guides)",
             "head": ["Detail", "Versions", "Effect on the liner"],
             "rows": [["Rear under-seat storage (F-150 SuperCrew)", "Plain floor, under-seat storage, fold-flat load floor", "Fold-flat trucks need a fold-flat-specific second-row piece"],
                      ["Rear storage (Silverado 1500 Crew Cab)", "Carpeted storage, plastic storage box, none", "Each version needs a rear liner cut for it"],
                      ["Front seats", "40/20/40 bench or buckets with a console", "Front cut can differ; a bench leaves a center strip to cover"],
                      ["Cab", "Crew Cab or Double Cab", "Double Cab uses a shorter rear liner"],
                      ["Powertrain (RAV4)", "Gas, Hybrid, Prime", "Some sets are gas only; cargo liners differ"],
                      ["Floor covering", "Carpet or vinyl", "Nibbed liners are cut for carpet; check the title"]]}},
  {"h": "Cold weather and cleaning",
   "body": "Winter is the hardest season for floor protection: liners fill with salt slush, get folded for cleaning while cold, and sit in a vehicle that may be parked outside for days.\n\nMakers publish two kinds of evidence. One is a temperature range: LASFIT rates its TPE liners from −13°F to 167°F. The other is a warranty that names the failure: Husky covers WeatherBeater liners for life against cracks and breaks. Budget sets in the site's guides mostly publish neither. A liner that stiffens and curls at the edge stops sealing at the sill, so if you park outside in a northern state, a stated cold rating or a crack warranty is worth paying for. Firm liners can also arrive with shipping curl; the site's guides suggest leaving them in a warm cab to relax before judging the fit at the edges.\n\nCleaning is the same for every molded liner. Pull it out, shake it off, hose it down and scrub with mild soap and a stiff brush. WeatherTech says its FloorLiner can be hosed down, pressure washed or wiped clean, and sells its own cleaner kit. Dry the liner before it goes back in so water isn't trapped against the carpet. Avoid tire shine and silicone protectants, which leave the surface slick under wet shoes.\n\nCarpet mats need more work: vacuuming, shampooing and time to dry, and salt stains tend to come back. Flat rubber mats rinse as easily as liners, but because they have no walls, the carpet around them still needs attention at the end of winter."},
  {"h": "What each type costs, and what the warranty covers",
   "body": "The bands below are the Amazon price bands recorded in the site's F-150, Silverado 1500 and RAV4 guides in September 2026. Larger vehicles sit at the top of each band, and live prices move daily. As a cross-check from a maker's own store, WeatherTech's FloorLiner page for the fourth-generation Ram 1500 showed a range of $104.95 to $251.90 across the options on that page when we read it.\n\nThe site's guides don't cover carpet or universal trim-to-fit mats, so there is no band for them here. They are the cheapest route, and they are cheap for the reasons given above.\n\nWarranty is the one quality signal you can hold a maker to, and it varies more than price does:\n\n- **WeatherTech:** a lifetime limited warranty for the life of the original purchaser, with liners made in America.\n- **Husky WeatherBeater and X-act Contour:** a lifetime warranty against cracks and breaks, made in the USA.\n- **LASFIT:** 45-day returns on its own store; the collection page the site's guides read doesn't state a warranty length.\n- **Budget brands:** the listings the site's guides checked for Mixsuper, KARPAL, Powerty, AOMSAZTO and KUST publish no comparable terms, so confirm with the seller.\n\nOn the site's F-150 guide, a Husky set costs roughly $40 to $80 more than a budget TPE set, and that money buys the written terms as much as the plastic.",
   "table": {"caption": "Price bands by type (Amazon bands recorded in the site's guides)",
             "head": ["Type", "Examples in the guides", "Band"],
             "rows": [["Front-row pair, budget TPE", "KARPAL (F-150)", "About $70–$100"],
                      ["Front-row pair, premium", "Husky WeatherBeater 18361 (F-150)", "About $90–$130"],
                      ["Two-row budget TPE set", "AOMSAZTO, Powerty (RAV4); Mixsuper (F-150)", "About $70–$150"],
                      ["Two-row rubber set", "KUST (Silverado)", "About $90–$130"],
                      ["Two-row laser-fit TPE, published specs", "LASFIT, 3W", "About $120–$170"],
                      ["Two-row premium, USA-made", "Husky WeatherBeater", "About $130–$230"],
                      ["Two-row premium, laser-measured", "WeatherTech FloorLiner", "About $200–$280"],
                      ["Second row only", "Husky WeatherBeater 14401 (F-150 fold-flat)", "About $80–$120"],
                      ["Cargo liner", "Husky WeatherBeater 25501 (RAV4)", "About $90–$140"]]}},
 ],
 "decision": [
  {"if": "you drive through snow, salt or mud for months of the year", "then": "Buy a molded liner with high walls and a stated cold rating or crack warranty. Husky WeatherBeater and WeatherTech publish those terms; LASFIT publishes a −13°F to 167°F range."},
  {"if": "the vehicle lives in a dry climate and the cabin stays clean", "then": "A flat mat is enough. Keep the factory carpet mats or fit a custom rubber mat, and make sure the driver's side hooks to the retention posts."},
  {"if": "you want protection now for the least money", "then": "Buy a vehicle-specific front pair at about $70–$130 and add the rear row later. Don't save money with a trim-to-fit mat on the driver's side."},
  {"if": "the back seat carries kids, a dog or work crews", "then": "Get a one-piece second-row liner cut for your rear seat and under-seat storage, and on an SUV add a cargo liner for your powertrain."},
  {"if": "you plan to keep the vehicle for many years", "then": "Pay for a written lifetime warranty. It costs roughly $40–$80 more than a budget set on the site's F-150 guide and is the only durability claim you can enforce."},
  {"if": "you aren't sure which rear floor or seat layout you have", "then": "Order the front pair first, check under the rear cushions, then buy the matching rear piece from the guide for your vehicle."},
 ],
 "avoid": [
  {"h": "Stacking a liner on the factory mat", "body": "Retention hooks are designed for one mat. A stacked liner can slide forward and hold a pedal. Take the old mat out first."},
  {"h": "A trim-to-fit mat under the pedals", "body": "A universal mat rarely reaches the retention posts. Use a vehicle-specific driver liner and keep universal mats for the rear."},
  {"h": "Ordering by model name alone", "body": "Generation, cab, bench or buckets, under-seat storage and powertrain can each change the part. Read the layout notes in the listing."},
  {"h": "Silicone dressings and tire shine", "body": "They make TPE and rubber slick under wet shoes. Soap, water and a brush are all a liner needs."},
 ],
 "verdict": {
  "thesis": "Buy molded floor liners if the vehicle sees weather, kids or work, keep flat mats only for clean, dry use, and never compromise on a driver-side part that locks to the retention posts.",
  "body": "The choice between a mat and a liner is a choice about walls. A flat mat, carpet or rubber, protects the patch under your feet and lets everything else reach the carpet. A liner is measured to one floor pan and holds what lands in it, which is why it costs more and why it has to match your generation, cab, seats and storage. On the site's guides, a two-row liner set runs from about $70 for budget TPE to about $280 for WeatherTech, with Husky's USA-made WeatherBeater in between at about $130–$230. The material name matters less than three checks: does it name your layout, does it lock to the driver-side posts, and does the maker put a warranty in writing.\n\nOnce you know the type, the fit decides the product. Each vehicle guide below lists floor liners by the layout they are sold for, with the storage, seat and powertrain notes that rule sets in or out. On a truck, running boards cut down the mud that reaches the sill in the first place, and a tonneau cover does for the bed what liners do for the cab."
 },
 "sources": [
  ["WeatherTech FloorLiner HP product spotlight (WeatherTech)", "https://www.weathertech.com/blog/product-spotlight/new-weathertech-floorliner-hp.html"],
  ["WeatherTech FloorLiner, Ram 1500 fourth generation (WeatherTech)", "https://www.weathertech.com/floorliner-ram-ram-1500-4th-gen.html"],
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["LASFIT floor mats collection (LASFIT)", "https://www.lasfit.com/collections/floor-mats"],
  ["Toyota all-weather floor mat safety recall owner notice, recall 07E-082 (NHTSA)", "https://static.nhtsa.gov/odi/rcl/2007/RCONL-07E082-2445.pdf"],
 ],
}
