"""Explainer pillar — Running Boards vs Nerf Bars vs Rock Sliders.
No invented testing. Step widths, ratings, warranties and prices below were read on the maker/retailer pages listed
in sources: most via the site's fit-checked running-board guides (checked 2026-09-24), the rest on the RealTruck
(Go Rhino RB30, AMP Research PowerStep) and Cali Raised pages fetched 2026-10-03.
"""

KIND = "explainer"
SLUG = "running-boards-vs-nerf-bars"
CATEGORIES = ["running-boards"]

TITLE = "Running Boards vs Nerf Bars vs Sliders: Which Step Fits Your Truck"
META = ("Running boards, nerf bars, drop steps, power steps and rock sliders compared on step width, mounting, "
        "weight ratings, clearance, finish and price bands.")

FAQ = [
 ("What is the difference between nerf bars and running boards?",
  "A nerf bar is a round or oval tube with step pads at each door, like the 4 in and 5 in oval tubes in Westin's PRO TRAXX line. A running board is a flat, wider platform that runs the length of the cab, like the Go Rhino RB20, which RealTruck lists at 7.5 in wide at the front and 6.5 in at the rear. Nerf bars look sportier and give you a foothold. Running boards give a larger, flatter place to stand, which matters most for kids and older passengers. Both usually bolt to the same rocker mounting points."),
 ("Are rock sliders the same as running boards?",
  "No. A running board is built for stepping and bolts to the body's rocker mounting points. A rock slider is armor: heavy steel tube bolted or welded to the frame so the truck can land on it. Cali Raised, for example, builds its sliders from 1.75 in DOM steel tube with a .120 in wall and bolts them to the frame with five mounting legs. Many sliders have a flat top plate you can step on, but they sit higher and tighter than a board. Using a running board as a slider usually ends with a bent board."),
 ("How much weight can running boards hold?",
  "It depends on the product, and many makers don't say. RealTruck lists the Go Rhino RB30 at up to 600 lb per side, and the AMP Research PowerStep at up to 300 lb per door. Westin's page for the PRO TRAXX 5 doesn't state a figure. Budget listings sometimes put a rating in the description; if it isn't there, ask the seller. A rating describes someone standing on the step, not a jack under it or a rock against it, so don't read it as a measure of impact strength."),
 ("Do running boards need drilling?",
  "Most custom-fit kits don't. Westin says its PRO TRAXX nerf bars are bolt-on with no drilling on most applications, and RealTruck lists the Go Rhino RB20 and RB30 as no-drill installs with vehicle-specific brackets on the rocker panel. Power steps are the exception to watch: RealTruck's AMP Research PowerStep page says drilling is required on select applications and recommends professional installation. Check the listing for your cab and trim, and look for factory rock rails or rocker covers that may already occupy the mounting points."),
 ("Do running boards reduce ground clearance?",
  "Yes, a little. Anything that hangs below the rocker between the wheels reduces side clearance and breakover clearance. It does not change approach or departure angles, which are set by the bumpers. Slim boards and close-fitting nerf bars cost the least clearance, full-width boards a bit more, and drop steps the most because they are the lowest point on the side of the truck. Power steps retract against the body when the doors close, and frame-mounted rock sliders are designed to take the hit instead of the rocker."),
 ("Are power running boards worth it?",
  "They solve the clearance problem: the step drops when a door opens and tucks up when it closes. The cost is price and complexity. RealTruck lists the AMP Research PowerStep from $1,249.99, more than twice a Go Rhino RB20, and the kit adds motors, hinges and wiring to a part that lives in road spray. AMP's design uses aluminum with stainless steel hinge pins and carries a 5-year limited warranty. They make sense on a lifted road truck or a family truck with short passengers. On a tight budget, fixed boards do the same job."),
 ("Should I buy cab-length or wheel-to-wheel steps?",
  "Cab-length steps run under the doors only. Wheel-to-wheel steps continue past the cab to the rear wheel well, which adds a place to stand beside the bed. That helps when reaching over the bed side, into a toolbox or under a bed rack. The trade-offs are a longer install, less clearance along more of the truck and one more fit variable: wheel-to-wheel bars are bed-length specific as well as cab specific. If you rarely reach into the front of the bed from the side, cab-length is enough."),
 ("How wide should a running board be?",
  "The figures in the site's guides run from 4 in oval nerf bars to 7.5 in boards. RealTruck lists the Go Rhino RB20 Slim at a 5.5 in step, the RB30 at 7 in and the full RB20 at 7.5 in front and 6.5 in rear; budget aluminum boards are about 6 in. Wider is easier to stand on in boots and for small feet. Narrower keeps more side clearance and looks cleaner. On a truck that stays on pavement and carries family, go wide. On a truck that sees trails, go slim or go to sliders."),
 ("Which finish resists rust best?",
  "Look at what is under the top coat. RealTruck describes Go Rhino's RB20 and RB30 as 16-gauge zinc-coated galvanized steel under a textured powder coat or bedliner finish, so a chip exposes zinc rather than bare steel. Westin offers polished 304 stainless steel with a lifetime warranty, or black powder coat over e-coated steel with 3 years. Aluminum boards don't rust, though the site's guides note that heavy road salt can still corrode them. In a salt state, avoid plain painted steel with no stated undercoat."),
 ("Do drop steps help on a lifted truck?",
  "Yes. A drop step hangs below the bar or board at each door, so the first step is lower. The budget drop steps in the site's F-150 and Tacoma guides list a 4 in drop, and Go Rhino sells its RB20 as a kit with two pairs of drop steps. That helps short passengers and anyone climbing into a truck with a lift or bigger tires. The cost is clearance: the drop step becomes the lowest point on the side of the truck, so it is a road-truck part."),
 ("Can I jack up my truck on running boards or nerf bars?",
  "No. Running boards and nerf bars aren't jacking points; jacking on one can bend the board or its brackets. Use the frame or the jacking points in the owner's manual. Frame-mounted rock sliders are different. Cali Raised says properly engineered rock sliders mounted to the frame can support the full weight of the vehicle. Even then, check the slider maker's instructions before putting a jack under one, because a slider is only as strong as its mounts."),
]

ARTICLE = {
 "dek": "Running boards give you a wide place to stand. Nerf bars give you a foothold and a cleaner look. Drop steps lower the first step, power steps hide when the door shuts, and rock sliders are armor you can also step on. Here is how they differ on width, mounting, ratings, clearance, finish and price, from maker specs.",
 "author": "jake-morrison",
 "reviewed": "2026-10-03",
 "method": "We did not install or test these steps. This page compares step styles using the published specs (step width, material, finish, mounting, warranty, weight rating) and price bands that the site's fit-checked running-board guides read on Westin and RealTruck pages in September 2026, plus the RealTruck pages for the Go Rhino RB30 and AMP Research PowerStep and the Cali Raised rock slider specification page, fetched on 2026-10-03. Where a maker doesn't publish a figure, we say so and don't estimate one. For the part numbers that fit your cab, use the vehicle guides linked below.",
 "takeaways": [
  "**Boards are for standing, bars are for a foothold:** flat boards in the site's guides run 5.5–7.5 in wide; oval nerf bars are 4–5 in tubes with step pads.",
  "**Cab length decides fit:** steps bolt to rocker or body mounting points, so crew, extended and regular cabs take different parts.",
  "**Few makers publish a rating:** RealTruck lists the Go Rhino RB30 at 600 lb per side and the AMP PowerStep at 300 lb per door; Westin states none for the PRO TRAXX 5.",
  "**Every fixed step costs clearance:** drop steps hang lowest, slim boards least; power steps retract and frame-mounted sliders protect the rocker.",
  "**Prices span about $140 to $1,250:** budget 6 in boards about $140–$220, Go Rhino boards about $430–$600, and power steps from $1,249.99 at RealTruck.",
 ],
 "compare_table": {
  "caption": "Side step styles compared (specs and price bands from the site's F-150, Ram 1500 and Tacoma guides and the pages in sources)",
  "head": ["Style", "Step surface", "Mounts to", "Published rating", "Clearance", "Price band", "Best for"],
  "rows": [
   ["Flat running board", "5.5–7.5 in flat platform (Go Rhino RB20 Slim, RB30, RB20)", "Rocker panel points, no drilling", "600 lb per side (RB30, RealTruck)", "Fair; slim versions good", "About $430–$600; budget 6 in boards about $140–$220", "Families, daily use"],
   ["Oval or round nerf bar", "4–5 in tube with molded step pads (Westin PRO TRAXX 4, 5)", "Rocker points; no drilling on most applications", "None on Westin's page", "Good; sits close to the body", "About $220–$400", "Clean look, adult foothold"],
   ["Drop or hoop step", "Separate step hung below the bar; 4 in drop on budget kits", "Body points, or added to a board (Go Rhino RB20 kit)", "Not published on the listings checked", "Lowest point on the side", "About $160–$260; about $600–$750 as an RB20 kit", "Lifted road trucks, short riders"],
   ["Wheel-to-wheel bar or board", "Cab length plus a step beside the bed", "Rocker points, extended toward the rear wheel", "Not published on the listings checked", "Less clearance along more of the truck", "About $170–$240 budget; about $450–$650 Westin", "Reaching into the bed"],
   ["Power-retracting board", "6 in aluminum step that deploys with the door (AMP PowerStep)", "Vehicle-specific brackets, motors and wiring", "300 lb per door (RealTruck)", "Best of the steps when retracted", "From $1,249.99 at RealTruck", "Low step without losing clearance"],
   ["Rock slider", "1.75 in DOM steel tube, optional top plate (Cali Raised)", "Frame, bolt-on with five mounting legs", "Maker says frame-mounted sliders can support the vehicle's weight", "Best; built to take impacts", "Not covered in the site's guides; slider-style steps about $200–$280", "Trail use, rocker protection"],
  ],
 },
 "sections": [
  {"h": "The five styles and how each is built",
   "body": "All of these parts live in the same place, under the doors, and that is why they get confused. They are built for different jobs.\n\n**Flat running boards** are a continuous platform along the cab. The Go Rhino RB20 is the reference in the site's guides: RealTruck describes it as 16-gauge zinc-coated galvanized steel with a textured powder coat or bedliner finish. Its sibling, the RB30, has an open flow-through step surface that RealTruck says prevents dirt, mud and snow from building up. Budget boards are usually 6 in aluminum in a factory-style shape.\n\n**Nerf bars** are tubes. Westin's PRO TRAXX 5 uses a 5 in oval tube with injection-molded step pads, seamless domed ends and 30° factory-style bends; the PRO TRAXX 4 is the 4 in version. You step on the pads, not on the tube between them.\n\n**Drop steps and hoop steps** hang an individual step below the bar at each door. Go Rhino sells the RB20 as a kit with two pairs of drop steps, and the budget kits in the site's guides list a 4 in drop.\n\n**Power-retracting boards** are hinged. RealTruck's page for the AMP Research PowerStep says it deploys automatically when the door opens and retracts tight and out of sight when the door closes.\n\n**Rock sliders** are armor first. Cali Raised builds its sliders from 1.75 in DOM steel tube with a .120 in wall and mounts them to the frame. Its Step Edition runs flat at 0°, and its Trail Edition tilts up 20° toward the body. A kick-out at the rear deflects rocks away from the rear tire and protects the rear quarter panel."},
  {"h": "Step width and drop: what your foot actually gets",
   "body": "Two measurements decide how a step feels: how wide the surface is, and how far below the door sill it sits.\n\nWidth first. The figures the site's guides read, plus the RB30 and PowerStep pages, are in the table below. The spread is larger than it sounds. A 4 in oval tube gives the ball of your foot a place to push off. A 7.5 in board lets a child stand with both feet flat. If the regular passengers are adults in work boots, a nerf bar or slim board is enough. If they are kids, grandparents or anyone who steps up slowly, buy width.\n\nDrop is the other half. A board mounted tight to the rocker on a lifted truck can still leave a tall first step, because the board went up with the body. That is the case for a drop step: it puts the surface lower, 4 in lower on the budget kits in the site's guides. On a stock-height truck with adult passengers, a drop step mostly costs clearance for no gain.\n\nSurface matters as much as size. Look for molded pads, a textured top or an open slotted surface, and check the listing photos. The RB30's flow-through slots are aimed at snow country, where a solid step packs with slush and ices over.",
   "table": {"caption": "Published step widths (maker and RealTruck pages, and listings in the site's guides)",
             "head": ["Product", "Style", "Step width", "Source"],
             "rows": [["Westin PRO TRAXX 4", "Oval nerf bar", "4 in oval tube", "Westin"],
                      ["Westin PRO TRAXX 5", "Oval nerf bar", "5 in oval tube", "Westin"],
                      ["Go Rhino RB20 Slim", "Slim running board", "5.5 in", "RealTruck"],
                      ["Budget aluminum boards (Nilight, PZ)", "Running board", "6 in", "Listings"],
                      ["AMP Research PowerStep", "Power-retracting board", "6 in", "RealTruck"],
                      ["Go Rhino RB30", "Slotted running board", "7 in", "RealTruck"],
                      ["Go Rhino RB20", "Running board", "7.5 in front / 6.5 in rear", "RealTruck"]]}},
  {"h": "Cab-length vs wheel-to-wheel",
   "body": "Every side step is sold by cab, because the mounting points and the door openings set its length. A crew-cab board won't fit an extended cab, and the site's guides are split the same way: SuperCrew versus SuperCab on the F-150, Crew Cab versus Quad Cab on the Ram 1500, Double Cab versus XtraCab on the Tacoma. Generation matters as much. The 2024 Tacoma has a new body, and Go Rhino sells separate kits for 2005–2023 and 2024 trucks. From 2019 to 2024 Ram sold the new DT body alongside the older Classic, with different rocker mounting points, and listings say which one they fit.\n\nWithin a cab, you choose between two lengths.\n\n- **Cab-length** steps run under the doors, between the wheel wells. This is the default, and it is what Go Rhino means by 'cab length' in its listing titles.\n- **Wheel-to-wheel** steps continue past the rear door to the rear wheel well, adding a step beside the bed. Westin's wheel-to-wheel PRO TRAXX 5 for the Ram 1500 Crew Cab is listed for one bed length, so the part depends on the bed as well as the cab.\n\nThe bed-side step is useful if you reach into a toolbox, a RamBox or the front of the bed from the side, or load a bed rack. It costs more, takes longer to fit because it mounts farther back, and puts more length below the rocker. Check that the rear section clears any mud flaps before ordering."},
  {"h": "Mounting: rocker and body mounts vs the frame",
   "body": "Where a step bolts on tells you what it can take.\n\nRunning boards, nerf bars and most drop steps bolt to the vehicle's rocker or body mounting points with vehicle-specific brackets. RealTruck lists the Go Rhino RB20 and RB30 as rocker panel mounted with no drilling required and a mounting kit included. Westin says the PRO TRAXX 5 is bolt-on with no drilling on most applications, with a mount kit in the box. The install is a driveway job with a helper: brackets on hand-tight, board on, level it, torque to the figures in the instructions and recheck after a week of driving.\n\nTwo things can get in the way. Higher trims with factory running boards, fixed or power, need those removed first, because aftermarket boards replace them. And off-road trims may already have factory rock rails or rocker protection on the same points; the site's Tacoma guide flags the TRD Pro and Trailhunter for that reason.\n\nRock sliders mount to the frame. Cali Raised describes its sliders as frame mounted and bolt-on, with five mounting legs on the Tacoma, 4Runner and Tundra and 3/16 in steel mounting plates. That is the reason a slider can take the truck's weight on a rock and a running board cannot: the load goes into the frame rather than into sheet metal at the rocker. It is also why sliders are heavier and take longer to fit. Cali Raised lists about 120 lb per set for the Tacoma and about 160 lb for the Tundra.\n\nBecause boards mount to the body, they move with it. On a truck with air suspension that lowers for entry, the board drops closer to the ground too."},
  {"h": "Weight ratings: what makers publish and what the number means",
   "body": "Weight ratings are thinner on the ground than you would expect for a part people stand on. From the pages we and the site's guides read:\n\n- **Go Rhino RB30:** up to 600 lb per side, per RealTruck.\n- **AMP Research PowerStep:** up to 300 lb per door, per RealTruck.\n- **Westin PRO TRAXX 5:** no weight rating on Westin's product page.\n- **Budget boards and drop steps (Nilight, PZ, Just-V, TAC and similar):** no rating the site's guides could check on the listing summaries; some state one in the description.\n- **Rock sliders:** Cali Raised gives no number, but says properly engineered sliders mounted to the frame can support the full weight of the vehicle.\n\nNote the units. 'Per side' and 'per door' are not the same claim, so compare like with like. And all of these describe a standing load, a person's weight pressing down on the step surface. They say nothing about a sideways hit from a rock, a curb strike or a jack under the tube.\n\nIf a rating matters to you, because of a heavy driver, a work crew or a board that doubles as a place to stand while loading a roof rack, buy a product with a published figure rather than assuming one. If the listing is silent, ask the seller for the rating in writing before ordering.",
   "table": {"caption": "Published ratings and warranties (pages listed in sources)",
             "head": ["Product", "Rating as published", "Warranty"],
             "rows": [["Go Rhino RB30", "Up to 600 lb per side", "Limited lifetime structural, 5-year finish"],
                      ["Go Rhino RB20 / RB20 Slim", "Not stated in the site's guides", "Limited lifetime structural, 5-year finish"],
                      ["Westin PRO TRAXX 5", "None published", "Lifetime on polished stainless, 3 years on black"],
                      ["AMP Research PowerStep", "Up to 300 lb per door", "5-year limited"],
                      ["Cali Raised rock sliders", "No figure; frame-mounted, can support the vehicle's weight", "Not read"]]}},
  {"h": "Ground and breakover clearance: the trade-off",
   "body": "A side step sits between the wheels and below the rocker, which is exactly the part of the truck that touches down first when you crest a ridge or straddle a rut. So every fixed step trades some breakover and side clearance for easier entry. It does not change approach or departure angle; the bumpers set those.\n\nIn rough order, from least clearance lost to most:\n\n1. **Rock sliders** tuck tight to the body, and an angled design such as Cali Raised's 20° Trail Edition tilts up toward it. They are meant to touch the ground so the rocker doesn't.\n2. **Power steps** fold up when the doors are shut. RealTruck's PowerStep page says they retract to maximize ground clearance and shield the rocker panels.\n3. **Slim boards and nerf bars.** Go Rhino designs the RB20 to sit tight to the rocker, and the 5.5 in RB20 Slim sticks out less than the full board.\n4. **Full-width and wheel-to-wheel boards**, which put more width or more length below the rocker.\n5. **Drop steps**, the lowest point on the side of the truck.\n\nOn a road truck, the loss rarely matters outside steep driveways and high curbs. On a trail, a running board that catches a rock can bend, because it is built for stepping and not for carrying the truck. That is the line between the two categories: if the truck leaves pavement often, buy sliders or slider-style steps and accept a higher step. If it doesn't, buy the step that suits your passengers."},
  {"h": "Materials, finish and corrosion",
   "body": "A step lives in road spray, so the finish system matters more than the top coat's color.\n\n- **Galvanized steel under a coating.** RealTruck describes the Go Rhino RB20 and RB30 as 16-gauge zinc-coated galvanized steel with a textured black or protective bedliner finish. If gravel chips the coating, the steel underneath is still zinc-coated. The bedliner finish is rougher and more chip-resistant. Go Rhino's finish warranty covers red rust, peeling, flaking and cracking for five years, with a limited lifetime structural warranty.\n- **Stainless steel.** Westin's polished PRO TRAXX 5 is 304 stainless and carries a lifetime warranty against manufacturer defects.\n- **E-coated steel with powder coat.** Westin's black PRO TRAXX uses black powder coat over e-coated steel, covered for 3 years. The same product, in a different finish, gets a much shorter warranty, which tells you how Westin rates the two.\n- **Aluminum.** Budget 6 in boards and the AMP PowerStep are aluminum. It is light and doesn't rust, though the site's guides note it can corrode in heavy salt and is less stiff than galvanized steel.\n- **Sliders.** Cali Raised sells its sliders in powder coat, bedliner or raw steel. Raw steel has to be painted or coated by the owner, and any slider that does its job will get scraped, so plan to touch up the finish.\n\nBudget brands in the site's guides rarely publish finish or warranty terms. In a salt state, pay for galvanized or stainless, or expect to replace a painted steel step sooner."},
  {"h": "Power steps: wiring, install and what can go wrong",
   "body": "A power-retracting board is the only style that gives a low step without a permanent clearance penalty, and the only one with an electrical install.\n\nRealTruck's page for the AMP Research PowerStep describes a 6 in wide slip-resistant step in corrosion-resistant aluminum with a powder coat finish and stainless steel hinge pins. The kit includes a vehicle-specific mounting kit with the brackets, hardware, wiring and motors. On wiring, the page describes a plug-n-play design with 'no improvised attachments, no complicated wiring', and says newer applications connect through an OBD II module. Integrated LED lighting illuminates the step, and an optional override switch is available for manual control.\n\nThe same page is candid about the install: drilling is required on select applications, and professional installation is recommended. Budget for that if you aren't comfortable routing a harness and mounting motors under the truck.\n\nWhat can go wrong is what you would expect from a moving part in road spray. A fixed board has brackets and bolts. A power step adds motors, hinges, wiring and a door trigger, so there is more to fail in mud and salt, and the 5-year limited warranty is shorter than the lifetime structural terms on a Go Rhino board. Trucks with factory power boards are in the same position: when those wear out, an aftermarket kit replaces them rather than bolting on alongside.\n\nBuy power steps for a lifted road truck or a family truck where a low step and a clean rocker both matter. Skip them for a trail truck or a tight budget."},
  {"h": "What each style costs",
   "body": "Price bands from the site's F-150, Ram 1500 and Tacoma guides, recorded in September 2026, plus RealTruck 'from' prices where we read them:\n\n- **Budget 6 in boards, mostly aluminum:** about $140–$220 (Nilight, PZ, BINARY STAR, YITAMOTOR)\n- **Budget drop steps:** about $160–$260 (SMANOW, Just-V, TAC)\n- **Budget wheel-to-wheel boards:** about $170–$240 (BINARY STAR, Tacoma)\n- **Slider-style steps:** about $200–$280 (CLAMBER, Tacoma)\n- **Oval nerf bars:** about $220–$400 (Westin PRO TRAXX 4 and 5)\n- **Go Rhino slim boards:** about $300–$420 for the RB10 Slim, about $430–$550 for the RB20 Slim and RB30 Slim; RealTruck lists the RB20 Slim from $449.99\n- **Go Rhino full boards:** about $450–$600; RealTruck lists the RB20 and RB30 from $519.99\n- **Wheel-to-wheel nerf bar:** about $450–$650 (Westin PRO TRAXX 5, Ram 1500)\n- **Board plus drop steps:** about $600–$750 (Go Rhino RB20 kit)\n- **Power-retracting boards:** from $1,249.99 (AMP Research PowerStep at RealTruck), before any installation labor\n\nWe did not read a price on the Cali Raised page, and the site's guides don't cover frame-mounted sliders, so there is no band for them here.\n\nTwo patterns stand out. A name-brand galvanized board costs about three times a budget aluminum one, and the difference is mostly the steel, the finish system and the written warranty. And a slim board costs nearly as much as the full-width version of the same product, so choose width for how you use the truck, not to save money."},
 ],
 "decision": [
  {"if": "kids or older passengers ride in the truck every week", "then": "Buy a wide flat running board. The Go Rhino RB20 at 7.5 in front and 6.5 in rear is the widest step in the site's guides; a 6 in aluminum board is the budget version."},
  {"if": "you want a cleaner look and only adults use the step", "then": "An oval nerf bar such as the Westin PRO TRAXX 4 or 5 gives a foothold and sits close to the body. Pick polished stainless for the lifetime warranty."},
  {"if": "the truck is lifted and stays on the road", "then": "Add drop steps, or buy a board-plus-drop-step kit. Accept that the drop step is now the lowest point on the side."},
  {"if": "the truck goes off-road regularly", "then": "Buy frame-mounted rock sliders, or slider-style steps, instead of running boards. A flat-top or 0° slider still gives you somewhere to step."},
  {"if": "you want a low step and full clearance", "then": "A power-retracting board does both, from $1,249.99 at RealTruck for the AMP PowerStep. Plan for wiring and possibly professional installation."},
  {"if": "you reach into the bed from the side", "then": "Choose a wheel-to-wheel bar or board, and confirm the bed length as well as the cab in the listing."},
 ],
 "avoid": [
  {"h": "Ordering for the wrong cab or body", "body": "Steps are cab-length and generation specific. Check the cab name, the model years and, on a 2019–2024 Ram 1500, whether the listing excludes the Classic."},
  {"h": "Treating running boards as rock sliders", "body": "Boards bolt to rocker points and are built for stepping. On rocks they bend. Sliders bolt to the frame for a reason."},
  {"h": "Assuming a weight rating", "body": "Many makers publish none. If the listing doesn't state one, ask the seller, and never use a board or nerf bar as a jacking point."},
  {"h": "Plain painted steel in a salt state", "body": "Choose galvanized steel, stainless or e-coat under powder coat, and read the finish warranty separately from the structural one."},
 ],
 "verdict": {
  "thesis": "Buy a flat running board for the widest, easiest step, a nerf bar for a foothold and a cleaner look, and frame-mounted rock sliders, not boards, if the truck leaves pavement.",
  "body": "Every style on this page solves the same problem, getting into a tall vehicle, with a different compromise. A flat board gives 5.5 to 7.5 in of platform and costs some clearance. A 4 or 5 in nerf bar gives up surface for a tighter fit. Drop steps lower the first step and become the lowest point on the truck. Power steps hide when the doors shut, from $1,249.99, with motors and wiring to look after. Rock sliders bolt to the frame, protect the rocker and make a higher, narrower step. Decide who uses the step and where the truck goes, then check the published rating and the finish warranty before the price.\n\nAfter the style comes the fit. Each vehicle guide below lists running boards and nerf bars by cab and generation, with the trim, body-style and factory-rail notes that rule parts in or out. Side steps also keep mud off the sill, so floor liners stay cleaner, and a tonneau cover or trailer hitch is the usual next upgrade on the same truck."
 },
 "sources": [
  ["Westin PRO TRAXX 5 oval nerf bars (Westin)", "https://www.westinautomotive.com/pro-traxx-5-oval-nerf-step-bars"],
  ["Go Rhino RB20 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb20-running-boards/"],
  ["Go Rhino RB20 Slim running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb20-slim-running-boards/"],
  ["Go Rhino RB30 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb30-running-boards/"],
  ["AMP Research PowerStep (RealTruck)", "https://realtruck.com/p/amp-research-powerstep/"],
  ["Rock slider engineering specs (Cali Raised)", "https://caliraisedled.com/blogs/news/rock-slider-engineering-specs"],
 ],
}
