"""Explainer pillar — Trailer Hitch Classes Explained.
No invented testing. Class ranges come from CURT's and etrailer's class pages (fetched 2026-09-28), tongue-weight and
adapter guidance from etrailer and CURT, hitch-type definitions from NHTSA's towing guide (Oregon reprint), and
vehicle/hitch examples from the site's fit-checked hitch guides and the maker pages they cite.
"""

KIND = "explainer"
SLUG = "trailer-hitch-classes-explained"
CATEGORIES = ["hitches"]

TITLE = "Trailer Hitch Classes Explained: Class 1 to 5, Receiver Sizes and Ratings"
META = ("Trailer hitch Classes 1–5 explained: receiver sizes, gross trailer and tongue weight ranges from CURT and etrailer, "
        "and why your vehicle's rating always wins.")

FAQ = [
 ("What are the five trailer hitch classes?",
  "Classes 1 through 5 group receiver hitches by capacity and receiver size. CURT lists Class 1 at up to 2,000 lb gross trailer weight and 200 lb tongue weight on a 1-1/4 in receiver, Class 2 at up to 3,500 lb and 350 lb on 1-1/4 in, Class 3 at up to 8,000 lb and 800 lb on 2 in, Class 4 at up to 10,000 lb and 1,000 lb on 2 in, and Class 5 from 16,000 lb on 2 in up to 20,000 lb on 2-1/2 in. Other makers publish slightly different ranges."),
 ("Does a Class 3 hitch mean I can tow 8,000 lb?",
  "No. 8,000 lb is the top of CURT's Class 3 range, not the rating of every Class 3 hitch and certainly not your vehicle's rating. Real Class 3 hitches in the site's guides are rated 3,500 lb (CURT 13493 for the Bronco) and 4,500 lb (Draw-Tite 76527, B&W for the RAV4). And both CURT and etrailer say the same thing: you are limited by the lowest-rated part of the setup. A 4,500 lb hitch on a RAV4 rated for 1,500 lb tows 1,500 lb."),
 ("What is the difference between a 1-1/4 in and a 2 in receiver?",
  "The opening size and, with it, the capacity. Class 1 and 2 hitches use a 1-1/4 in receiver and top out at 3,500 lb gross trailer weight and 350 lb tongue weight on CURT's chart. Class 3 and 4 hitches use a 2 in receiver. Most hitch bike racks and cargo carriers are made for 2 in, so a 2 in receiver gives you more accessory choice. Pick 1-1/4 in only if you already own 1-1/4 in gear or the vehicle only takes a small hitch."),
 ("How much tongue weight should a trailer have?",
  "etrailer's guidance is 10–15% of the loaded trailer's weight, so a 10,000 lb trailer should put 1,000–1,500 lb on the ball, and a 3,000 lb trailer 300–450 lb. NHTSA's towing guide explains why it matters: too little tongue weight can make the trailer sway, and too much takes weight off the tow vehicle's front wheels. The resulting figure must fit inside the hitch's tongue-weight rating and the vehicle's own tongue-weight limit from the owner's manual."),
 ("Can I use a 1-1/4 to 2 in adapter?",
  "You can, but it costs capacity. CURT says a 1-1/4 to 2 in adapter reduces the hitch or vehicle's tongue weight capacity by up to 50%, which leaves a Class 1 hitch at around 100 lb of tongue weight or less, and that towing capacity can drop 30% or more depending on the adapter and hitch. That is not enough for a loaded 2 in bike rack. Going the other way, etrailer notes that adapters let you carry Class I and II accessories on a larger hitch; the limit is then the accessory's own rating."),
 ("Where do I find my vehicle's towing capacity?",
  "Start with the owner's manual or the maker's towing guide, which list tow and tongue ratings by engine, drivetrain and tow package. Then check the labels on the driver's door jamb: the certification label gives the gross vehicle and axle weight ratings, and the tire and loading placard gives the most weight of people and cargo the vehicle should carry. Tongue weight counts against that payload. If the manual lists several ratings, use the one that matches your exact configuration."),
 ("When do I need a weight-distribution hitch?",
  "When the vehicle's owner's manual or the hitch's ratings call for one, and when the trailer is heavy enough to make the rear sag and the front go light. NHTSA's guide describes weight-distributing hitches as a receiver hitch plus special parts that spread tongue weight across all the tow vehicle's and trailer's axles. Only use one on a hitch rated for it: CURT's 13493 lists a weight-distribution rating, while the Reese 06192 Class 2 is not rated for weight distribution at all."),
 ("Do I need a 4-way or 7-way connector?",
  "A 4-way flat connector carries the basic lights (tail, turn and brake signals plus ground) and suits most small utility trailers, bike trailers and light boat trailers. A trailer with electric brakes needs a 7-way connector, which adds a brake circuit, a 12 V power feed and a reverse circuit, and a brake controller in the cab. Many vehicles take a plug-in, vehicle-specific harness, such as CURT's 56434 for the RAV4, which avoids splicing into factory wiring."),
 ("Do I need a brake controller?",
  "If the trailer has electric brakes, yes: the controller in the cab is what applies them. Requirements for trailer brakes are set by each state, often by trailer weight, so check your state's rules and your owner's manual. Oregon's reprint of NHTSA's towing guide, for example, says Oregon law does not require trailer brakes but strongly encourages them. Also check whether your vehicle has a factory controller; Bronco owners note that adding a hitch later does not add the tow package's controller."),
 ("Is a bike rack on a hitch the same as towing?",
  "No, a hitch rack is pure tongue weight: the rack and bikes hang on the receiver with no trailer axle carrying any of it. etrailer's example is a 200 lb rack with two 50 lb bikes, 300 lb in total, which can overload a small hitch. Compare the loaded rack weight to the hitch's tongue-weight rating and the vehicle's tongue limit, and remember that the further the load sits from the bumper, the more leverage it puts on the receiver."),
]

ARTICLE = {
 "dek": "Hitch classes tell you what a receiver can take, not what your vehicle can tow. Here are the Class 1–5 ranges from CURT and etrailer, the three receiver sizes, tongue weight, weight distribution, wiring and brakes, and how to find the rating that actually limits you.",
 "author": "jake-morrison",
 "reviewed": "2026-09-28",
 "method": "We did not tow with or install these hitches. Class ranges come from CURT's and etrailer's published class charts, which differ slightly and are shown side by side. Tongue-weight and adapter guidance comes from etrailer and CURT, hitch-type definitions from NHTSA's towing guide as reprinted by Oregon DOT, and the vehicle and hitch examples from the site's fit-checked hitch guides and the maker pages they cite. Nothing here replaces your owner's manual.",
 "takeaways": [
  "**The lowest rating wins:** hitch, ball mount, accessory, vehicle or trailer, whichever is lowest sets your limit.",
  "**Classes map to receivers:** Class 1–2 use 1-1/4 in, Class 3–4 use 2 in, and Class 5 uses 2 in or 2-1/2 in (etrailer also lists 3 in).",
  "**Ranges vary by maker:** CURT's Class 2 tops out at 350 lb tongue weight; etrailer's chart goes to 525 lb. Read the hitch's own label.",
  "**Aim for 10–15% tongue weight:** etrailer's rule of thumb; too little causes sway, too much unloads the front wheels.",
  "**Adapters cost capacity:** CURT says a 1-1/4 to 2 in adapter can cut tongue weight capacity by up to 50%.",
 ],
 "compare_table": {
  "caption": "Hitch classes by receiver size, gross trailer weight (GTW) and tongue weight (TW), as published by CURT and etrailer",
  "head": ["Class", "Receiver", "CURT GTW / TW", "etrailer GTW / TW", "Typical use"],
  "rows": [
   ["Class 1", "1-1/4 in", "Up to 2,000 / 200 lb", "1,000–2,000 / 100–200 lb", "Bike racks, small cargo trays, very light trailers"],
   ["Class 2", "1-1/4 in", "Up to 3,500 / 350 lb", "2,000–3,500 / 200–525 lb", "Small utility and jet-ski trailers, racks"],
   ["Class 3", "2 in", "Up to 8,000 / 800 lb (WD up to 12,000)", "3,500–8,000 / 300–800 lb", "The common SUV and pickup hitch; campers, boats"],
   ["Class 4", "2 in", "Up to 10,000 / 1,000 lb (WD up to 12,000)", "5,000–12,000 / 500–1,200 lb", "Heavier travel trailers on full-size trucks"],
   ["Class 5", "2 in (Xtra Duty) or 2-1/2 in (Commercial)", "16,000–17,000 / 2,400–2,550 lb; 18,000–20,000 / 2,700 lb", "10,000–25,000 / 1,000–4,000 lb (2, 2-1/2 or 3 in)", "Heavy-duty and commercial trucks"],
  ],
 },
 "sections": [
  {"h": "What a hitch class actually rates",
   "body": "A hitch class is a capacity band for the receiver hitch itself, the square tube and cross member bolted to the vehicle's frame. Each class comes with a receiver size and two numbers:\n\n- **Gross trailer weight (GTW):** the most the loaded trailer can weigh.\n- **Tongue weight (TW):** the most downward force the trailer tongue, or a hitch-mounted rack, can put on the receiver.\n\nThe class is a label for the range; the hitch's own rating label is what counts. Two Class 3 hitches can carry very different numbers. In the site's guides, the CURT 13493 for the 2021–2026 Bronco is a Class 3 rated 3,500 lb GTW and 350 lb TW, while the Draw-Tite 76527 for the same truck is Class III at 4,500 lb and 675 lb. Both sit comfortably inside CURT's Class 3 range of up to 8,000 lb and 800 lb, and neither comes close to its top.\n\nNaming isn't consistent either. Toyota describes its PK960-42K10 RAV4 hitch as Class II but with a 2 in receiver tube, even though CURT and etrailer both put Class 2 on 1-1/4 in. So read three things on any listing: the receiver size, the GTW and the TW. The class word alone doesn't tell you enough."},
  {"h": "Class ranges differ by maker",
   "body": "There is no single chart that every maker prints. The compare table above shows CURT's and etrailer's published ranges side by side, and they disagree in places:\n\n- **Class 2 tongue weight:** CURT lists up to 350 lb; etrailer's range runs to 525 lb.\n- **Class 4 capacity:** CURT lists up to 10,000 lb GTW and 1,000 lb TW; etrailer's range goes to 12,000 lb and 1,200 lb.\n- **Class 5 receivers:** CURT splits Class 5 into Xtra Duty on a 2 in receiver (16,000–17,000 lb GTW) and Commercial Duty on 2-1/2 in (18,000–20,000 lb); etrailer lists 2, 2-1/2 or 3 in and a 10,000–25,000 lb range.\n\nThe published ranges are summaries of what hitches in each class are usually rated for, not certifications. What matters for your setup is the number stamped on the hitch's label and printed in its instructions, which is the rating the maker tested it to. When a listing gives a class but no GTW and TW, the site's guides treat that as a reason to confirm with the seller."},
  {"h": "Your vehicle's rating caps everything",
   "body": "CURT's class page puts it plainly: towing capacity is always limited to the lowest-rated component, whether that's the hitch, an accessory, the vehicle or the trailer. etrailer says the same thing in fewer words. A hitch never raises what your vehicle can tow.\n\nThe site's RAV4 guide shows how wide the gap can be. The fifth-generation RAV4 is rated 1,500 lb on gas LE through Limited trims, 1,750 lb as a Hybrid, 2,500 lb as the Prime, and 3,500 lb on Adventure and TRD Off-Road with the Tow Prep Package, per Toyota dealer figures. The B&W and Draw-Tite hitches listed for it are rated 4,500 lb. Bolting a 4,500 lb Class III hitch to a 1,500 lb XLE still leaves a 1,500 lb tow rating; the extra hitch capacity is margin, not permission.\n\nThe Bronco guide makes the same point in the other direction. Ford rates most 2021–2026 Broncos at 3,500 lb and the Raptor at 4,500 lb, so a 3,500 lb CURT hitch matches most trucks while only a 4,500 lb hitch like the Draw-Tite 76527 matches the Raptor.\n\nThe chain includes more than the hitch and vehicle. The ball mount, the hitch ball, the coupler, the safety chains and any adapter each carry their own rating. Add them up in your head as the lowest number in the list, not the highest."},
  {"h": "How to find your vehicle's real rating",
   "body": "Four places, in this order:\n\n1. **The owner's manual or the maker's towing guide.** These list maximum trailer weight and maximum tongue weight by engine, drivetrain, cab and bed, axle ratio and tow package. Use the line that matches your exact vehicle, not the headline figure for the model.\n2. **The certification label on the driver's door jamb.** It lists the gross vehicle weight rating (GVWR) and the gross axle weight ratings (GAWR). NHTSA's towing guide warns that the rear axle rating on this label must not be exceeded, and tongue weight lands mostly on the rear axle.\n3. **The tire and loading information placard,** also on the door jamb. It gives the most weight of occupants and cargo the vehicle should carry. That is your payload, and trailer tongue weight or a loaded bike rack counts against it along with passengers and gear.\n4. **The hitch's own label.** It gives the hitch's GTW and TW and, where applicable, a separate weight-distribution rating.\n\nThe smallest relevant number wins. A half-ton pickup with a full cab of people and a bed of gear can run out of payload before it reaches its advertised tow rating, which is why the door-jamb labels matter as much as the brochure."},
  {"h": "Tongue weight and the 10–15% rule",
   "body": "Tongue weight is the downward force the trailer puts on the ball. etrailer's guidance is that it should be 10–15% of the loaded trailer's weight: 1,000–1,500 lb on a 10,000 lb trailer, or 300–450 lb on a 3,000 lb one.\n\nNHTSA's towing guide explains why the range matters. Too little tongue weight can make the trailer sway. Too much causes problems of its own, including not enough weight on the tow vehicle's front wheels, which affects steering and braking.\n\nThe figure has to fit inside three limits at once: the hitch's TW rating, the ball mount's rating and the vehicle's tongue-weight limit in the owner's manual. On a small SUV the vehicle's limit is usually the one that bites first. Loading heavier items ahead of the trailer axle raises tongue weight; moving them back lowers it. A tongue-weight scale, or a bathroom scale and a lever for light trailers, takes the guesswork out.",
   "table": {"caption": "Target tongue weight at etrailer's 10–15% guideline",
             "head": ["Loaded trailer weight", "10%", "15%"],
             "rows": [["1,500 lb", "150 lb", "225 lb"], ["3,000 lb", "300 lb", "450 lb"], ["5,000 lb", "500 lb", "750 lb"], ["7,500 lb", "750 lb", "1,125 lb"], ["10,000 lb", "1,000 lb", "1,500 lb"]]}},
  {"h": "Weight-carrying vs weight-distributing hitches",
   "body": "NHTSA's guide draws the line clearly. **Weight-carrying hitches** carry all of the trailer's tongue weight on the receiver and the vehicle's rear axle. That is how every hitch works out of the box. **Weight-distributing hitches** add spring bars and brackets to a receiver hitch so the tongue weight is spread across all of the tow vehicle's and the trailer's axles, putting weight back on the front wheels.\n\nMany hitches publish two sets of ratings, one weight-carrying and one weight-distributing. In the site's Bronco guide, the CURT 13493 is rated 3,500 lb and 350 lb weight-carrying and 4,000 lb and 400 lb with weight distribution; the Draw-Tite 76527 is 4,500 lb and 675 lb either way. CURT's class chart lists weight-distribution capacity up to 12,000 lb on its Class 3 and Class 4 hitches. Some hitches aren't approved for it at all: the Reese 06192 Class 2 for the RAV4 is not compatible with weight distribution.\n\nA weight-distribution system never lifts the vehicle's own maximum tow rating. What it does is restore steering and braking feel with heavier trailers, and many owner's manuals specify one above a certain trailer weight. Check yours, and only use one on a hitch that lists a weight-distribution rating."},
  {"h": "Receiver sizes, bike racks and cargo carriers",
   "body": "**1-1/4 in** receivers belong to Class 1 and 2. They tuck under small cars and crossovers and carry light bike racks and trays. CURT's chart tops them out at 3,500 lb and 350 lb.\n\n**2 in** receivers are the standard for Class 3 and 4 and fit most hitch bike racks, cargo carriers and ball mounts. On most SUVs and pickups this is the size to buy. The site's RAV4 guide recommends 2 in unless you already own 1-1/4 in gear, because brand-name Class III hitches cost about the same as Class II.\n\n**2-1/2 in** receivers appear on CURT's Commercial Duty Class 5 hitches and on heavy-duty trucks.\n\nA hitch rack is pure tongue weight. etrailer's example: a 200 lb rack with two 50 lb bikes puts 300 lb on the receiver, which can overload some small hitches. Heavy e-bike racks add up quickly, and the further the load sits from the bumper, the more leverage it applies. Weigh the rack and bikes together and compare them to the lower of the hitch's TW and the vehicle's tongue limit before you load."},
  {"h": "Adapters, reducers and extenders",
   "body": "Adapters look like a cheap way around a receiver-size mismatch. They cost capacity.\n\n- **1-1/4 in to 2 in adapters** (a small receiver made to take 2 in gear): CURT says these reduce the hitch or vehicle's tongue weight capacity by up to 50%, leaving a Class 1 hitch at around 100 lb of tongue weight or less, and can cut towing capacity by 30% or more depending on the adapter and setup. A loaded 2 in bike rack on an adapted Class 1 hitch is the classic overload.\n- **2 in to 1-1/4 in reducers** (a sleeve so small accessories fit a large receiver): etrailer notes these let you carry Class I and II accessories on a larger hitch. The limit is then the accessory's rating.\n- **Extenders** push the load further back to clear a tailgate spare or a rear door, which adds leverage. Treat any extender as reducing capacity, and follow the extender maker's derating.\n\nIf you find yourself needing an adapter to run a rack, the better fix is usually the right receiver in the first place."},
  {"h": "Wiring: 4-way flat vs 7-way",
   "body": "A trailer needs working lights before it goes on the road, and the hitch doesn't include them.\n\n- **4-way flat** connectors carry the ground, tail lights and left and right turn and brake signals. They cover most small utility trailers, bike trailers and light boat trailers. A vehicle-specific plug-in harness such as CURT's 56434 for the RAV4 connects to factory plugs without splicing.\n- **7-way** connectors add an electric-brake circuit, a 12 V power feed for a trailer battery, and a reverse-light circuit. Campers and any trailer with electric brakes use them.\n\nFactory wiring isn't guaranteed. Ford's own Bronco receiver kit says a wiring harness is sold separately, and the Bronco guide lists Ford's 4/7-pin harness as an extra. Avoid splice-in kits that cut factory wires where a plug-in harness exists, and route the harness clear of the exhaust. Safety chains are the other must: NHTSA's guide says they should cross under the trailer tongue and have enough slack for sharp turns without dragging."},
  {"h": "Brake controllers",
   "body": "Electric trailer brakes need a controller in the cab that applies them when you brake and lets you apply them on their own to settle sway. Without a controller, a 7-way plug does nothing for the brakes.\n\nWhen a trailer needs its own brakes is set by state law, usually by trailer weight, and the rules differ. Oregon's version of NHTSA's towing guide, for example, says Oregon law does not require trailer brakes but strongly encourages them. Check your state's rules and your owner's manual, which may require trailer brakes above a certain weight regardless of the law.\n\nDon't assume a factory controller comes with a hitch. Bronco6G owners point out that adding a hitch after delivery doesn't add the brake-controller hardware that comes with Ford's Trailer Tow Package, so budget for an aftermarket unit if you tow a braked trailer. Many trucks with a factory tow package have a controller built into the dash; many SUVs and crossovers don't."},
 ],
 "decision": [
  {"if": "you only carry bikes or a cargo tray", "then": "A 2 in Class 3 hitch is the flexible choice because most racks are built for it. Choose 1-1/4 in only if you already own 1-1/4 in gear, and check the loaded rack weight against both tongue limits."},
  {"if": "you tow a small utility or jet-ski trailer", "then": "A Class 2 or Class 3 hitch plus a 4-way flat harness covers it, provided the trailer stays under your vehicle's own rating."},
  {"if": "you tow a camper or boat over a few thousand pounds", "then": "Buy a Class 3 or 4 hitch with a published weight-distribution rating, a 7-way connector and a brake controller, and check the door-jamb payload with the family and gear aboard."},
  {"if": "your vehicle already has a factory receiver", "then": "Don't buy a hitch. Spend the money on the ball mount, wiring and brake controller instead, and confirm the receiver's own label."},
  {"if": "a listing gives a class but no GTW and TW", "then": "Treat it as unrated until the seller confirms both numbers in writing, or pick a maker that prints them."},
 ],
 "avoid": [
  {"h": "Reading the class as your tow rating", "body": "A Class 3 or 4 hitch doesn't make a 1,500 lb crossover a 5,000 lb tow vehicle. The owner's manual rating is the limit."},
  {"h": "Ignoring tongue weight", "body": "A trailer inside the GTW can still overload the hitch or the vehicle's tongue limit. Aim for 10–15% and check it against both ratings."},
  {"h": "Running a 2 in rack on an adapted 1-1/4 in hitch", "body": "CURT says the adapter can halve tongue-weight capacity. A loaded rack can exceed what is left."},
  {"h": "Towing a braked trailer without a controller", "body": "The 7-way plug only carries the signal. Without a brake controller in the cab, the trailer's brakes never engage."},
 ],
 "verdict": {
  "thesis": "Pick the receiver size for what you'll put in it, pick a class with margin over the load, and then tow only to the lowest rating in the chain, which is almost always the vehicle's.",
  "body": "Hitch classes are a useful shorthand for receiver size and capacity, but they aren't consistent between makers and they don't tell you what your vehicle can tow. CURT and etrailer agree on the structure (1-1/4 in for Class 1 and 2, 2 in for Class 3 and 4, 2 or 2-1/2 in for Class 5) and disagree on some of the numbers, so the hitch's own label and the owner's manual are the figures to trust.\n\nFor most SUVs and pickups, a 2 in Class 3 hitch listed for your exact generation, a plug-in harness and, for braked trailers, a brake controller cover everything. Each vehicle guide below lists the trailer hitch options sold for that generation alongside its factory tow ratings, so you can see the real limit before you buy. If the bed of your truck needs covering too, the tonneau cover guides are the next stop."
 },
 "sources": [
  ["Types of trailer hitches and hitch classes (CURT)", "https://www.curtmfg.com/types-trailer-hitches"],
  ["The complete guide to 1-1/4 in receiver hitches (CURT)", "https://www.curtmfg.com/1-1-4-inch-receiver-hitch-guide"],
  ["How to choose the right trailer hitch class (etrailer)", "https://www.etrailer.com/faq-hitchclasses.aspx"],
  ["How much weight can I put on my trailer hitch? (etrailer)", "https://www.etrailer.com/faq-how-much-weight-can-i-put-on-my-trailer-hitch.aspx"],
  ["Towing a Trailer: Being Equipped for Safety (NHTSA, Oregon DOT reprint)", "https://www.oregon.gov/odot/Safety/Documents/TowingATrailer.pdf"],
  ["CURT 13493 Class 3 Trailer Hitch (CURT)", "https://www.curtmfg.com/part/13493"],
  ["Draw-Tite 76527 Class III Trailer Hitch (Draw-Tite)", "https://www.draw-tite.com/product/76527_class-iii-trailer-hitch"],
  ["Reese 06192 Class II hitch (Reese)", "https://www.reeseprod.com/product/06192_class-ii-trailer-hitch"],
  ["Toyota hitch receiver PK960-42K10 (Toyota Auto Parts)", "https://autoparts.toyota.com/products/product/hitch-receiver-pk96042k10"],
  ["CURT 56434 custom wiring harness (CURT)", "https://www.curtmfg.com/part/56434"],
  ["2024 Toyota RAV4 towing capacity by trim (Toyota Vallejo)", "https://www.toyotavallejo.com/blogs/5095/2024-toyota-rav4-towing-capacity"],
  ["Ford Bronco towing capacity by year and engine (Aaron Ford)", "https://www.aaronfordofpoway.com/ford-bronco-towing-capacity.htm"],
  ["Do all 2025 Broncos come with a hitch? (Bronco6G)", "https://www.bronco6g.com/forum/threads/do-all-2025-broncos-come-with-a-hitch.129087/"],
 ],
}
