"""Generate db/migrations/004_fitment_pages.sql from pages_v1.py (idempotent upsert, dollar-quoted)."""
import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from pages_v1 import PAGES

out = ["-- 004_fitment_pages.sql — GENERATED by db/content/build_pages_sql.py; edit pages_v1.py, not this file.",
       "-- status 'draft' until fitments exist for the page; app renders drafts as noindex. Flip to 'published' with 005 or by hand.", ""]
for make, model, gen, cat, title, meta, intro, gotchas, faq, verdict in PAGES:
    g = "\n".join(f"- {x}" for x in gotchas)
    f = json.dumps([{"q": q, "a": a} for q, a in faq], ensure_ascii=False)
    out.append(f"""INSERT INTO fitment_pages (vehicle_id, category_id, title, meta_desc, intro_md, gotchas_md, faq, verdict_md, status, verified_at)
SELECT v.id, c.id, $t${title}$t$, $m${meta}$m$, $i${intro}$i$, $g${g}$g$, $f${f}$f$::jsonb, $v${verdict}$v$, 'draft', CURRENT_DATE
FROM vehicles v JOIN makes m ON m.id=v.make_id JOIN categories c ON c.slug='{cat}'
WHERE m.slug='{make}' AND v.model_slug='{model}' AND v.gen_slug='{gen}'
ON CONFLICT (vehicle_id, category_id) DO UPDATE SET title=EXCLUDED.title, meta_desc=EXCLUDED.meta_desc, intro_md=EXCLUDED.intro_md,
  gotchas_md=EXCLUDED.gotchas_md, faq=EXCLUDED.faq, verdict_md=EXCLUDED.verdict_md, verified_at=EXCLUDED.verified_at, updated_at=now();
""")
dest = os.path.join(os.path.dirname(__file__), "..", "migrations", "004_fitment_pages.sql")
open(dest, "w", encoding="utf-8").write("\n".join(out))
print(f"wrote {dest} with {len(PAGES)} pages")
