"""Long-form article — Best Running Boards & Side Steps for 2019–2026 Chevy Silverado 1500 (T1).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker/RealTruck pages in sources (checked 2026-09-24).
"""

KEY = ("chevrolet", "silverado-1500", "2019-present", "running-boards")

TITLE = "Best Running Boards for 2019–2026 Chevy Silverado 1500 Crew Cab: 6 Picks, Not for the 2019 LD"
META = ("Six Silverado 1500 Crew Cab running boards and nerf bars from Westin, Go Rhino, Rough Country, 3STONZ, OEDRO "
        "and TAC, with the 2019 LD trap and finish and warranty notes.")

FAQ = [
 ("What is the 2019 Silverado LD and why is it excluded?",
  "In 2019 Chevrolet sold the new T1 Silverado 1500 alongside a carryover of the previous truck, badged Silverado LD (and the Sierra 1500 Limited at GMC). The LD uses the older body and rocker mounting points. Westin's listings say 'Exc 2019 Silverado LD/Sierra 1500 Limited', and budget listings say 'excl. 2019 LD'. If your 2019 has the older-style body, buy parts for the 2014–2018 truck."),
 ("Do Silverado running boards fit the Sierra 1500?",
  "Yes, for the same cab. Westin, Go Rhino, Rough Country and the budget boards on this page all list the Silverado and Sierra 1500 together."),
 ("Do these fit the Silverado 2500HD and 3500HD?",
  "Some do. Westin's PRO TRAXX 5 21-54130 and Rough Country's RPT2 list the 2020–2025 heavy-duty Crew Cabs too. The budget boards list the 1500 only. Check the title."),
 ("Do I need to drill?",
  "Not usually. Westin says its PRO TRAXX bars are bolt-on with no drilling on most applications, and RealTruck lists the Go Rhino RB20 as no-drill. The Silverado has factory mounting points on the rocker."),
 ("Crew Cab or Double Cab boards?",
  "Every pick here is Crew Cab. The Double Cab has shorter rear doors and needs shorter boards; Westin sells Double Cab versions such as the PRO TRAXX 5 21-54120."),
 ("What's a wheel-to-wheel nerf bar?",
  "A longer bar that runs from the front wheel well to the rear wheel well, giving a step at the bed as well as the cab. Westin sells wheel-to-wheel PRO TRAXX 5 versions for the Silverado by bed length, such as 21-534680 for the 5 ft 5 in bed."),
 ("Does the ZR2 or Trail Boss need different steps?",
  "The ZR2 has factory rocker protection, and off-road-focused trims benefit more from rock sliders than running boards. Running boards that list the Crew Cab bolt to the same points, but they reduce side clearance."),
 ("How much weight can running boards hold?",
  "It depends on the product. RealTruck lists the Go Rhino RB30, a close sibling of the RB20, at 600 lb per side. Westin doesn't publish a figure for the PRO TRAXX 5 on its page. Ask the seller if the listing doesn't state it."),
 ("Stainless or black?",
  "Westin's polished 304 stainless carries a lifetime warranty against manufacturer defects; its black powder coat over e-coat is covered for 3 years. Stainless costs more but ages best in salt states."),
 ("Can I install them myself?",
  "Yes, with a helper and basic hand tools. Bolt the brackets to the rocker points, set the boards, level them, torque the bolts and recheck after a week."),
 ("Will running boards affect my Silverado's power steps or rocker covers?",
  "If your truck has factory power-deployable steps (offered on higher trims), aftermarket boards replace them; you'd remove the power steps and their brackets first. If your truck has plastic rocker covers or plugs over the mounting points, most kits have you remove the plugs to reach the threaded holes. Keep the plugs if you ever plan to return the truck to stock."),
 ("Do running boards help floor liners last longer?",
  "Indirectly, yes. A step keeps boots off the painted sill and knocks off some mud before passengers climb in, so less grit reaches the footwells and the liner edges. On a Crew Cab used by a family, that shows up as less wear on the front liner lips and cleaner carpet at the sill."),
]

ARTICLE = {
 "dek": "Six running boards and nerf bars listed for the T1 Silverado 1500 Crew Cab, from Westin's stainless PRO TRAXX 5 and Go Rhino's galvanized RB20 to $130 tube steps. One trap first: the 2019 Silverado LD is the old truck, and none of these fit it.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these steps ourselves. We ranked them on the fitment each listing states for the 2019–2026 Silverado 1500 Crew Cab, on published maker and retailer specs (tube or step width, material, finish, warranty, drilling) and on listing details. Westin specs come from Westin's product page; Go Rhino specs from RealTruck, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Not the 2019 LD.** The carryover old-body truck needs 2014–2018 parts.",
  "**Crew Cab only here.** Double Cab boards are shorter.",
  "**Silverado and Sierra share boards.** Every pick lists both.",
  "**No drilling on most kits.** Factory rocker mounting points.",
  "**Stainless gets the longest Westin warranty.** Lifetime on polished; 3 years on black.",
 ],
 "top_picks": [
  {"asin": "B07H5T9958", "role": "Best nerf bar", "why": "Westin PRO TRAXX 5 polished stainless, Crew Cab, lifetime warranty on that finish"},
  {"asin": "B086DF82C2", "role": "Best running board", "why": "Go Rhino RB20, galvanized steel, lifetime structural warranty"},
  {"asin": "B0B5FDWJ61", "role": "Best mid-price board", "why": "Rough Country RPT2, 1500 and HD Crew Cab"},
  {"asin": "B0DG8QB7RY", "role": "Best aluminum value", "why": "3STONZ 6 in aluminum, Crew Cab"},
  {"asin": "B07MCDNK9S", "role": "Best budget tube step", "why": "TAC 5 in oval side steps"},
 ],
 "fit_table": {
  "caption": "2019–2026 Silverado 1500: fit checklist",
  "head": ["Variable", "Versions", "What to buy"],
  "rows": [
   ["Body", "T1 (2019+) or 2019 LD carryover", "All picks are T1; LD needs 2014–2018 parts"],
   ["Cab", "Regular, Double, Crew", "All picks are Crew Cab"],
   ["Sister truck", "GMC Sierra 1500", "Every pick lists it"],
   ["Heavy duty", "2020+ 2500HD/3500HD", "Westin 21-54130 and Rough Country RPT2 list them"],
  ],
 },
 "look_for": [
  {"h": "T1 body, not the 2019 LD",
   "body": "The 2019 model year had two Silverado 1500s: the new T1 truck and the Silverado LD, a carryover of the 2014–2018 body sold for fleets and value buyers. GMC did the same with the Sierra 1500 Limited. The LD has different rocker mounting points, so none of these boards fit it. Westin's listings exclude it by name, and the budget 2-step listing says 'excl. 2019 LD'. If your 2019 has the older body, buy parts for 2014–2018. From 2020 on, every Silverado 1500 is a T1."},
  {"h": "Nerf bar, board or wheel-to-wheel",
   "body": "Westin's PRO TRAXX 5 is a 5 in oval nerf bar with molded step pads, a clean look that sits close to the body. Go Rhino's RB20 and Rough Country's RPT2 are flat running boards with a wider step; RealTruck lists the RB20 at 7.5 in at the front and 6.5 in at the rear. Westin also sells wheel-to-wheel versions that extend to the rear wheel well, giving a step to reach into the bed; those are sold by bed length. Pick by who rides and whether you reach into the bed often."},
  {"h": "Finish and warranty",
   "body": "Westin offers the PRO TRAXX 5 in polished 304 stainless steel with a lifetime warranty against manufacturer defects, or black powder coat over e-coated steel with a 3-year warranty. The 21-54130 listing here is the polished pair. RealTruck lists the Go Rhino RB20 as galvanized 16-gauge steel with a textured powder coat, a limited lifetime structural warranty and a 5-year finish warranty. In salt states, stainless or galvanized steel holds up best."},
  {"h": "Mounting and install",
   "body": "The T1 Silverado has factory mounting points on the rocker. Westin says the PRO TRAXX 5 is bolt-on with no drilling on most applications, and Westin also sells a separate 27-2255 mount kit for 2019–2026 Silverado and Sierra Double and Crew Cab. RealTruck lists the RB20 as no-drill with a vehicle-specific bracket kit. Budget boards use the same points. Plan on a helper and recheck bolt torque after a week."},
  {"h": "Clearance and trims",
   "body": "Any side step reduces side clearance. On a ZR2 or Trail Boss that sees trails, a board can catch on rocks and ledges. The ZR2 has factory rocker protection; rock sliders are the better off-road choice. For road trucks, the convenience of a step outweighs the small clearance loss. Drop-style steps hang lowest."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Body", "Excludes 2019 LD / Sierra Limited", "Listings that don't say"],
   ["Cab", "Crew Cab named", "Double Cab boards on a Crew Cab"],
   ["Mounting", "Bolt-on to factory points", "Kits that need drilling"],
   ["Finish", "Stainless, galvanized, or e-coat + powder coat", "Bare paint in salt states"],
   ["Step", "Textured or molded pads", "Slick tops"],
   ["Warranty", "Stated terms by finish", "No terms"],
  ],
 },
 "types_table": {
  "caption": "Side step types for the 2019–2026 Silverado 1500 Crew Cab",
  "head": ["Type", "Example", "Step", "Finish", "Price band", "Best for"],
  "rows": [
   ["Oval nerf bar", "Westin PRO TRAXX 5", "5 in oval, molded pads", "Polished stainless", "$300–$450", "Long warranty, clean look"],
   ["Galvanized board", "Go Rhino RB20", "7.5 / 6.5 in (RealTruck)", "Galvanized + powder coat", "$450–$600", "Wide step, durability"],
   ["Mid-price board", "Rough Country RPT2", "Flat board", "Per listing", "$250–$400", "1500 and HD owners"],
   ["Aluminum board", "3STONZ, OEDRO", "6 in", "Aluminum / paintable", "$150–$230", "OE-style value"],
   ["Tube step", "TAC 5 in oval", "5 in oval", "Per listing", "$130–$190", "Budget"],
  ],
 },
 "picks": [
  {"asin": "B07H5T9958", "role": "Best nerf bar", "price": "$300–$450",
   "pros": ["Polished 304 stainless steel", "Lifetime warranty against manufacturer defects on this finish", "Lists 2019–2025 1500 and 2020–2025 HD Crew Cab", "5 in oval with molded step pads", "Bolt-on, no drilling on most applications"],
   "cons": ["Excludes the 2019 LD / Sierra Limited", "Narrower step than a flat board", "Polished finish costs more than black"],
   "body": "Westin's PRO TRAXX 5 21-54130 is the polished stainless nerf bar for the T1 Silverado and Sierra 1500 Crew Cab, listed for 2019–2025, plus the 2020–2025 heavy-duty Crew Cab, and excluding the 2019 Silverado LD and Sierra 1500 Limited. It uses a 5 in oval tube with injection-molded step pads, domed ends and 30° factory-style bends, according to Westin.\n\nThe polished 304 stainless finish is why it's the pick: Westin covers it with a lifetime warranty against manufacturer defects, compared with 3 years for the black powder-coat version. In salt states, stainless doesn't rely on a coating to resist rust.\n\nWestin says installation is bolt-on with no drilling on most applications and includes a mount kit. The oval step is narrower than a flat board, so it suits adult riders more than small kids. Westin also sells wheel-to-wheel versions by bed length if you want a step to reach into the bed.",
   "who": "Owners who want a clean nerf bar with the longest finish warranty.",
   "specs": [["Part #", "Westin 21-54130"], ["Tube", "5 in oval"], ["Finish", "Polished 304 stainless"], ["Fits", "2019–2025 Silverado/Sierra 1500, 2020–2025 HD Crew Cab (exc 2019 LD/Limited)"], ["Mounting", "Bolt-on, no drilling on most applications"], ["Warranty", "Lifetime (polished stainless)"]]},
  {"asin": "B086DF82C2", "role": "Best running board", "price": "$450–$600",
   "pros": ["Galvanized 16-gauge zinc-coated steel", "Limited lifetime structural, 5-year finish warranty", "Wide step per RealTruck", "Bolt-on, no drilling", "Lists Silverado and Sierra Crew Cab 2019–2025"],
   "cons": ["Costs the most here", "Heavier than aluminum", "Confirm 2026"],
   "body": "Go Rhino's RB20 69404887PC is listed for 2019–2025 Silverado and Sierra Crew Cab. RealTruck describes the RB20 as galvanized 16-gauge zinc-coated steel with a textured powder coat or bedliner finish, a limited lifetime structural warranty and a 5-year finish warranty, and lists the step at 7.5 in at the front and 6.5 in at the rear.\n\nThat wide, flat step suits families: kids and older passengers get a real platform instead of a tube. The galvanizing under the powder coat matters in salt country, because the steel is protected even where the top coat chips.\n\nRealTruck lists it as a bolt-on install with no drilling and a vehicle-specific bracket kit, starting at $519.99. Go Rhino also sells RB20 kits with drop steps for lifted trucks. Confirm a 2026 with the seller.",
   "who": "Families who want a wide step with a structural warranty.",
   "specs": [["Part #", "Go Rhino 69404887PC"], ["Type", "Flat running board"], ["Width", "7.5 in front / 6.5 in rear (RealTruck)"], ["Material", "Galvanized 16-ga steel"], ["Warranty", "Limited lifetime structural, 5-yr finish"], ["Fits", "2019–2025 Silverado/Sierra Crew Cab"]]},
  {"asin": "B0B5FDWJ61", "role": "Best mid-price board", "price": "$250–$400",
   "pros": ["Lists 2019–2025 1500 and 2500HD/3500HD Crew Cab", "Non-slip step", "Rust-resistant finish per listing", "Sleek profile", "Well-known brand"],
   "cons": ["Rough Country's warranty terms not confirmed on pages we read", "Narrower than the RB20", "Confirm 2026"],
   "body": "Rough Country's RPT2 running boards are listed for 2019–2025 Silverado and Sierra 1500, 2500HD and 3500HD Crew Cab. The listing describes a sleek profile, non-slip step, rust-resistant finish and easy install.\n\nIt sits between the budget aluminum boards and the Go Rhino on price, from a brand many truck owners already buy lifts and lights from. We didn't find Rough Country's warranty terms on the pages we read, so check the listing before ordering.\n\nFor owners who want a flat board that also fits a heavy-duty truck they might move to later, it's a sensible middle choice. If you might move to a 2500HD later, the HD fitment in the title means the boards could transfer; confirm cab and year with the seller at that point.",
   "who": "1500 and HD owners who want a mid-price flat board.",
   "specs": [["Model", "Rough Country RPT2"], ["Fits", "2019–2025 Silverado/Sierra 1500, 2500HD, 3500HD Crew Cab"], ["Step", "Non-slip (per listing)"], ["Finish", "Rust-resistant (per listing)"], ["Price band", "$250–$400"]]},
  {"asin": "B0DG8QB7RY", "role": "Best aluminum value", "price": "$160–$230",
   "pros": ["6 in aluminum board", "Lists 2019–2025 Crew Cab", "OE-style look", "Aluminum doesn't rust", "Low price"],
   "cons": ["No published warranty we could check", "Aluminum can corrode in heavy salt", "Lighter-duty than steel"],
   "body": "3STONZ's 6 in aluminum running boards are listed for 2019–2025 Silverado and Sierra 1500 Crew Cab. They give an OE-style look and a flat step at a fraction of the Go Rhino's price.\n\nAluminum is light and rust-free, though road salt can corrode it over time, and it's less stiff than galvanized steel. 3STONZ doesn't publish a weight rating or warranty we could check.\n\nOEDRO's 6 in boards, with paintable step plates, are a close alternative in our product list. Compare live prices. If you live where roads are salted, rinse aluminum boards along with the undercarriage through winter; it's the easiest way to slow the white corrosion that shows up on bare aluminum.",
   "who": "Owners who want an OE-style board on a budget.",
   "specs": [["Width", "6 in"], ["Material", "Aluminum"], ["Fits", "2019–2025 Silverado/Sierra 1500 Crew Cab"], ["Warranty", "Confirm with seller"], ["Price band", "$160–$230"]]},
  {"asin": "B07MCDNK9S", "role": "Best budget tube step", "price": "$130–$190",
   "pros": ["5 in oval tube", "Lists 2019–2025 Crew Cab", "Lowest price here", "Clean look", "Bolt-on per listing"],
   "cons": ["No published warranty we could check", "Narrower step than boards", "Finish specs thin"],
   "body": "TAC's 5 in oval side steps are listed for 2019–2025 Silverado and Sierra 1500 Crew Cab. They're a budget version of the nerf-bar look, at roughly half the price of Westin's black PRO TRAXX.\n\nTAC doesn't publish warranty or finish specs we could check. In a salt state, the finish is what ages first on budget tubes, so wash the undercarriage in winter.\n\nFor a work truck that needs a step and not a showpiece, it's the cheapest route.",
   "who": "Budget buyers who want a tube step.",
   "specs": [["Type", "Oval tube step"], ["Tube", "5 in oval"], ["Fits", "2019–2025 Silverado/Sierra 1500 Crew Cab"], ["Warranty", "Confirm with seller"], ["Price band", "$130–$190"]]},
  {"asin": "B0CW3NM48D", "role": "Budget 2-step board", "price": "$140–$200",
   "pros": ["2-step design", "Title excludes the 2019 LD", "Lists 2019–2025 Crew Cab", "Low price", "Bolt-on per listing"],
   "cons": ["Generic brand", "No published warranty", "Less continuous step area"],
   "body": "This 2-step running board is listed for 2019–2025 Silverado and Sierra 1500 Crew Cab and excludes the 2019 LD in its title, which is a helpful sign the seller knows the body split.\n\nA 2-step design puts a step pad at each door rather than a continuous board. It's a budget option with little documentation.\n\nFor a truck that needs a step for occasional passengers, it does the job.",
   "who": "Budget buyers who want individual steps.",
   "specs": [["Type", "2-step board"], ["Fits", "2019–2025 Silverado/Sierra 1500 Crew Cab (excl. 2019 LD)"], ["Warranty", "Confirm with seller"], ["Price band", "$140–$200"]]},
 ],
 "install": [
  "Confirm a T1 Crew Cab (not the 2019 LD or a Double Cab).",
  "Locate the factory mounting points on the rocker; remove plugs if present.",
  "Bolt the brackets on hand-tight.",
  "With a helper, set the board on the brackets and start all bolts.",
  "Level the board and torque every bolt to spec.",
  "Recheck torque after the first week.",
 ],
 "avoid": [
  {"h": "2019 LD / Sierra Limited", "body": "Old body; these boards don't fit."},
  {"h": "Double Cab boards", "body": "Shorter cab, shorter boards."},
  {"h": "Bare paint in salt states", "body": "Choose stainless or galvanized."},
  {"h": "Skipping the torque recheck", "body": "Brackets settle after a week."},
 ],
 "verdict": {
  "thesis": "Buy Westin's polished PRO TRAXX 5 for a nerf bar with a lifetime finish warranty, Go Rhino's RB20 for the widest galvanized step, and 3STONZ for an OE-style board on a budget.",
  "body": "Running boards for the T1 Silverado bolt to factory points and are shared with the Sierra. Rule out the 2019 LD, match the Crew Cab, and choose by step style and finish. Westin's stainless nerf bar has the longest finish warranty, Go Rhino's RB20 the widest step and a structural warranty, Rough Country fits both 1500 and HD, and the aluminum and tube steps cover the budget end.\n\nWith steps on, less mud reaches the sill, which keeps floor liners cleaner. A tonneau cover is the other common first upgrade for the bed."},
 "sources": [
  ["Westin PRO TRAXX 5 oval nerf bars (Westin)", "https://www.westinautomotive.com/pro-traxx-5-oval-nerf-step-bars"],
  ["Go Rhino RB20 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb20-running-boards/"],
  ["Go Rhino RB30 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb30-running-boards/"],
  ["Westin 21-54130 listing", "https://www.amazon.com/dp/B07H5T9958"],
  ["Westin 27-2255 Silverado/Sierra mount kit listing", "https://www.amazon.com/dp/B07H639S3W"],
  ["Rough Country RPT2 listing", "https://www.amazon.com/dp/B0B5FDWJ61"],
  ["Chevrolet Silverado (Wikipedia)", "https://en.wikipedia.org/wiki/Chevrolet_Silverado"],
 ],
}

FITS = [
 ("B07H5T9958","Westin 21-54130 PRO TRAXX 5 Oval Nerf Bars Polished, 2019-2025 Silverado/Sierra 1500 & 2020-2025 HD Crew Cab (exc 2019 LD/Limited)","Westin","$300–$450",{"cab":"Crew Cab"},"Excludes 2019 LD / Sierra Limited."),
 ("B086DF82C2","Go Rhino RB20 Running Boards & Brackets 69404887PC, 2019-2025 Silverado & Sierra Crew Cab","Go Rhino","$450–$600",{"cab":"Crew Cab"},"Galvanized; confirm 2026."),
 ("B0B5FDWJ61","Rough Country RPT2 Running Boards, 2019-2025 Silverado & Sierra 1500/2500HD/3500HD Crew Cab","Rough Country","$250–$400",{"cab":"Crew Cab"},"Also lists HD."),
 ("B0DG8QB7RY","3STONZ 6 in Aluminum Running Boards, 2019-2025 Silverado/Sierra 1500 Crew Cab","3STONZ","$160–$230",{"cab":"Crew Cab"},"Crew Cab only."),
 ("B07MCDNK9S","TAC 5 in Oval Side Steps, 2019-2025 Silverado/Sierra 1500 Crew Cab","TAC","$130–$190",{"cab":"Crew Cab"},"Budget tube steps."),
 ("B0CW3NM48D","2-Step Running Boards, 2019-2025 Silverado/Sierra 1500 Crew Cab (excl. 2019 LD)","Generic","$140–$200",{"cab":"Crew Cab"},"Not 2019 Limited/LD (old body)."),
 ("B0BHWGXLHC","OEDRO 6 in Running Boards, 2019-2025 Silverado/Sierra 1500 Crew Cab","OEDRO","$150–$220",{"cab":"Crew Cab"},"Paintable step plates."),
]
