"""Long-form article — Best Rooftop Cargo Boxes for 2020–2026 Ford Explorer (6th gen, U625).
Mirrors the approved F-150 tonneau pilot. No invented hands-on testing: box specs come from Yakima, Thule,
INNO (via etrailer), SportRack and Rightline Gear (via RealTruck) pages fetched 2026-09-27; vehicle facts from
db/migrations/003_vehicles.sql and the Explorer roof-rack article (raised rails, 165 lb brand-name bar ratings,
58-65 in bars, adjustable spread). Boxes are universal; the Explorer-specific part is raised-rail bars,
spread, the panoramic roof and liftgate clearance.
Source fixes 2026-10-04: Hybrid years changed from 2020–2024 to 2020–2023 for retail buyers (Ford Authority); the bare
"tows up to 5,600 lb" now carries engine and year (Ford towing guides, Wikipedia); "Class III" dropped from the factory
receiver wording; readers told to check that their roof has rails because Ford lists a Slick Roof Conversion (rail
delete); six sources added.
"""

KEY = ("ford", "explorer", "2020-present", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2020–2026 Ford Explorer: 7 Picks for Its Raised Rails"
META = ("Seven Yakima, Thule, INNO, SportRack and Rightline cargo boxes for the 6th-gen Explorer: raised-rail bars, "
        "165 lb bar math, spread and liftgate checks.")

FAQ = [
 ("What is the best cargo box for a 2020–2026 Ford Explorer?",
  "The Yakima GrandTour 16 is the best cargo box for the 2020–2026 Explorer. It holds 16 cu ft, is 18 in deep for bulky gear, opens from both sides and fits a 24 to 36 in bar spread. The Yakima CBX 16 gives the same volume 3 in lower with a flat floor for square loads. The Thule Motion 3 XL is the ski pick, with 18 cu ft and room for 200 cm skis. The INNO Wedge 660 is the lowest profile at 11 in if a garage door is the limit, and the Rightline Gear Sport 3 soft carrier is the budget choice. Fit raised-rail crossbars first, and let the 165 lb bar rating and your manual's roof figure decide the load."),
 ("What size cargo box fits a 2020–2026 Ford Explorer?",
  "Most Explorer owners are best served by 16 to 18 cu ft. The roof is long and the raised-rail crossbars are wide (58 to 65 in on etrailer's systems), so a full-width 16 cu ft box such as the Yakima GrandTour 16 (79 x 35 x 18 in) or CBX 16 (83 x 38 x 15 in) sits easily with room left over. The Thule Motion 3 XL adds 18 cu ft and 200 cm skis. Bigger boxes weigh more, so check the box plus cargo against your bars' rating before you size up."),
 ("How much weight can I put in a cargo box on an Explorer?",
  "Two limits apply. The brand-name raised-rail systems on etrailer's Explorer lists are rated at 165 lb, and the Explorer's own roof limit is in your owner's manual; we could not confirm that figure from Ford for this page. The box and its contents count against the bar rating, and the bars count too against the roof limit. A 51.5 lb GrandTour 16 on 165 lb bars leaves 113.5 lb for gear at most, and less if the manual figure is lower."),
 ("Do I need special crossbars for a cargo box on an Explorer?",
  "You need crossbars, but not special ones. The sixth-gen Explorer's raised side rails have a gap underneath, so any raised-rail crossbar that names the Explorer will clamp on without a vehicle-specific fit kit. Look at your own roof first: Ford's current Explorer page, which shows the 2027 model, lists a Slick Roof Conversion that deletes the rails on the Active, ST-Line, Platinum and ST. Every box on this page mounts to those bars. Our Explorer roof rack page lists fit-checked bars, from about $250 brand-name sets to budget Amazon kits."),
 ("Will a roof box hit the Explorer's liftgate?",
  "A long box mounted too far back can. etrailer's experts measure from the front crossbar to the line where the roof meets the hatch, then compare that with the box maker's figure; Thule lists more than 52 3/32 in of front clearance for the Motion 3 XL. On the Explorer, slide the box forward on the long bars, open the power liftgate slowly the first time, and lower its opening height if it still gets close."),
 ("Can I open the Explorer's panoramic roof with a cargo box on?",
  "Don't plan on it. An etrailer expert says a rack installs fine on a 2022 Explorer ST with the panoramic roof, but notes that most manufacturers say to avoid opening the sunroof because it may contact the rack or accessories. etrailer gives the same advice for cargo boxes on panoramic roofs: the box can be used, but keep the glass closed while it is installed."),
 ("What cargo box does etrailer recommend for the Explorer?",
  "For a 2022 Explorer, an etrailer expert named the Thule Pulse Large (TH615): 16 cu ft, 76 x 33 x 16-1/2 in, with a 23-5/8 to 34-3/8 in crossbar spread. It is on this page as the lightest hard box we list, at 36 lb. Its trade-offs are a 110 lb cargo rating and a lid that opens only from the passenger side."),
 ("How far apart should the crossbars be on an Explorer for a cargo box?",
  "Set them inside the box's range. The raised-rail clamps slide along the rails, so the Explorer can meet almost any box: Yakima lists 24 to 36 in for the GrandTour 16 and 24 to 35.5 in for the CBX 16, etrailer lists 24 to 39 in for the INNO Wedge 660 and 21-13/16 to 36-9/16 in for the Thule Motion 3. The SportRack Vista XL uses fixed positions at 25-7/8, 27-7/8 or 29-7/8 in, so set the bars to one of those."),
 ("Is a roof box or a hitch cargo carrier better on an Explorer?",
  "Both have a place. Ford's tow package adds a 2 in receiver, and with it the Explorer is rated at 5,300 lb (2.3L) or 5,600 lb (3.0L) for 2020–2024 and 5,000 lb for 2025–2026, so a hitch carrier handles coolers and heavy bins without touching the roof limit. A roof box keeps the liftgate and rear camera clear, locks, and keeps soft bags dry. Three-row families often run both: bags up top, heavy gear on the hitch."),
 ("Will a cargo box fit in my garage with an Explorer?",
  "Measure before you drive in. The boxes here add 11 in (INNO Wedge 660), 15 in (CBX 16), 16-1/2 in (Thule Pulse L), 17 in (Motion 3 XL), 18 in (GrandTour 16, Rightline Sport 3) or 19 in (SportRack Vista XL) on top of the crossbars, which already sit above the raised rails. Measure the Explorer with bars fitted, add the box height, and compare it with the garage door opening."),
 ("Does a cargo box fit the 2025–2026 Explorer and the Hybrid?",
  "Yes. Boxes clamp to crossbars, not the vehicle, and the 2025 facelift kept the raised-rail rack approach on etrailer's 2025 Explorer list. The Hybrid, sold to retail buyers for 2020–2023, shares the same roof. For a 2026 Tremor or Active 100A, check that your roof has raised rails with a gap, then buy bars that name 2026."),
]

ARTICLE = {
 "dek": "Seven rooftop boxes from Yakima, Thule, INNO, SportRack and Rightline Gear matched to the sixth-generation Explorer's raised rails, from an 11 in tall low-profile box to an 18 cu ft Thule Motion 3 XL and a $140 soft bag. For each we list volume, length, height, box weight and crossbar spread, and what those numbers mean for 165 lb bars, the panoramic roof and the power liftgate.",
 "author": "jake-morrison",
 "reviewed": "2026-10-04",
 "method": "We did not mount these boxes ourselves. We ranked them on published specs from Yakima and Thule, etrailer's figures for the INNO Wedge 660, the Thule Pulse and the Thule Motion 3 spread, SportRack's own page, and RealTruck's Rightline Gear listing: volume, exterior size, box weight, cargo rating, crossbar spread, ski length and warranty. We then checked those numbers against the Explorer's raised rails, the 165 lb rating of brand-name Explorer bar systems, etrailer's Explorer cargo box and panoramic-roof answers, and the liftgate. Prices were checked in September 2026; Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Crossbars first.** The Explorer's raised rails have a gap underneath, so any raised-rail bar that names it clamps on without a fit kit. Check that your roof has them: Ford lists a Slick Roof Conversion that deletes the rails on some trims. Every box here mounts to those bars.",
  "**Spread is easy on this SUV.** Raised-rail clamps slide along the rail, so you can set the 24 in, 32 in or fixed-position spread a box needs.",
  "**The bars set the working limit.** Brand-name Explorer systems are rated at 165 lb; the roof figure is in your owner's manual. Box plus cargo must stay under both.",
  "**Keep the panoramic roof closed.** etrailer's experts say a rack is fine on a panoramic-roof Explorer ST, but advise against opening the glass with a rack or box installed.",
  "**Long roof, but watch the liftgate.** Measure from the front crossbar to the roof-hatch line and slide long boxes forward before the first opening.",
 ],
 "top_picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "why": "16 cu ft, 18 in deep for bulky gear, dual-side opening, 24–36 in spread, $709"},
  {"asin": "B0C41RZ4HM", "role": "Most usable space", "why": "Yakima CBX 16: flat floor, 15 in tall, made in the USA, 24–35.5 in spread"},
  {"asin": "B0HGC24R2P", "role": "Best for skis", "why": "Thule Motion 3 XL: 18 cu ft, 200 cm skis, 165 lb cargo rating, widest spread range"},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "why": "INNO Wedge 660: 11 in tall for garages, 24–39 in spread, 110 lb rating"},
  {"asin": "B0012INT98", "role": "Best budget", "why": "Rightline Gear Sport 3: 18 cu ft waterproof soft carrier, $139.99, folds away"},
 ],
 "fit_table": {
  "caption": "2020–2026 Explorer: what the box mounts to",
  "head": ["Years / trims", "Roof", "Crossbar notes", "Box notes"],
  "rows": [
   ["2020–2024 incl. XLT, ST, Timberline (2021+), Hybrid (2020–2023)", "Raised side rails with a gap", "Raised-rail clamps; 58–65 in bars on etrailer; 165 lb brand-name ratings", "Any box here; spread adjustable"],
   ["2021–2022 ST with panoramic roof", "Raised side rails", "etrailer: rack installs fine", "Keep the glass closed with a box on"],
   ["2025 (Active, ST-Line, ST, Platinum)", "Raised side rails", "Same systems on etrailer's 2025 list", "Same boxes"],
   ["2026 (adds Tremor, Active 100A)", "Check your roof", "Buy bars that name 2026", "Boxes carry over"],
   ["Any year, no rails (Ford lists a Slick Roof Conversion that deletes them)", "Naked roof", "Door-jamb clip systems", "Soft bag can strap on without a rack"],
  ],
 },
 "look_for": [
  {"h": "Raised-rail crossbars come before the box",
   "body": "A cargo box never touches the Explorer; it clamps to crossbars, and the crossbars carry the fit. The sixth-gen Explorer's rails stand off the roof on end posts, so raised-rail bars wrap around the rail through the gap without a vehicle-specific fit kit. That keeps the bar cost low: etrailer lists Malone's AirFlow2 for the Explorer at $245.60 to $260.95. Don't let the word flush on a bar listing confuse you; on Explorer listings it usually describes the bar shape, not the rail. Buy bars that name the Explorer and your years, then choose the box. Our Explorer roof rack page lists the fit-checked sets."},
  {"h": "The 165 lb bar rating and the roof limit",
   "body": "Every brand-name raised-rail system on etrailer's Explorer lists is rated at 165 lb. Some Amazon bars print 260 to 330 lb, but that is a bar figure, and the Explorer's own roof limit in the owner's manual caps it. Do the math with the lower number. The hard boxes here weigh 36 lb (Thule Pulse L) to 57 lb (Yakima CBX 16), which leaves roughly 108 to 129 lb for gear on 165 lb bars before the manual's figure is applied. Some boxes also carry their own cargo limit: 110 lb for the Pulse L and the INNO Wedge 660, 165 lb for the Motion 3 XL."},
  {"h": "Crossbar spread on long raised-rail bars",
   "body": "Every box has a minimum and maximum distance between the bars. The Explorer is forgiving here: raised-rail clamps slide along the rail, and Malone lists a 24 in minimum spread for its AirFlow2. Yakima lists 24 to 36 in for the GrandTour 16 and 24 to 35.5 in for the CBX 16; etrailer lists 23-5/8 to 34-3/8 in for the Thule Pulse L, 24 to 39 in for the INNO Wedge 660 and 21-13/16 to 36-9/16 in for the Motion 3. The SportRack Vista XL mounts at fixed positions of 25-7/8, 27-7/8 or 29-7/8 in, so set the bars to one of them."},
  {"h": "Liftgate clearance and box length",
   "body": "The Explorer's roof is long, but its power liftgate swings up toward the back of the roof, and a long box mounted too far back sits in its arc. etrailer's experts measure from the front crossbar to the line where the roof and hatch meet and compare that with the box maker's figure. Thule lists more than 52 3/32 in of front clearance for the 84.7 in Motion 3 XL. The shorter boxes, like the 63 in Vista XL and the 76 in Pulse L, leave the most margin. Mount any box as far forward as the windshield allows and open the liftgate slowly the first time."},
  {"h": "Height, garages and the panoramic roof",
   "body": "The Explorer is already a tall SUV, and raised rails lift the bars a little more. The boxes here add 11 in (INNO Wedge 660) to 19 in (SportRack Vista XL) on top of the bars, so measure the Explorer with bars fitted before the first trip into a garage or parking structure. The panoramic roof is the other height-related catch. etrailer's expert says a rack fits a 2022 Explorer ST with the panoramic roof, but most makers advise against opening the glass while a rack or box is installed. Keep it shut while the box rides up top."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbars", "Raised-rail bars that name the Explorer and your years", "Flush-rail feet or fifth-gen (2011–2019) bars"],
   ["Box weight", "Under about 50 lb to leave more of a 165 lb bar rating for gear", "Heavy boxes packed to their volume"],
   ["Crossbar spread", "A range that includes where your bars sit (most boxes here start at 24 in or lower)", "Fixed-position boxes without setting bars to match"],
   ["Length", "Under about 85 in, mounted forward, for liftgate room", "Boxes pushed back over the hatch line"],
   ["Height", "11–15 in boxes if you park in a garage", "Guessing garage clearance with a 19 in box"],
   ["Opening", "Dual-side, so you load from the curb", "Single-side boxes if you park on both sides"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Explorer (makers' specs; INNO, Pulse L and Motion 3 spread per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Explorer notes"],
  "rows": [
   ["Yakima GrandTour 16", "16 cu ft", "79 × 35 × 18 in", "51.5 lb", "24–36 in", "Deepest 16 here; dual-side"],
   ["Yakima CBX 16", "16 cu ft", "83 × 38 × 15 in", "57 lb", "24–35.5 in", "Flat floor; heaviest here"],
   ["Thule Pulse L", "16 cu ft", "76 × 33 × 16.5 in", "36 lb", "23-5/8 to 34-3/8 in", "etrailer's Explorer pick; 110 lb cargo"],
   ["Thule Motion 3 XL", "18 cu ft", "84.7 × 35 × 17 in", "51 lb", "21-13/16 to 36-9/16 in", "200 cm skis; check liftgate"],
   ["INNO Wedge 660", "11 cu ft", "80 × 33 × 11 in", "42 lb", "24–39 in", "Lowest; 110 lb cargo"],
   ["SportRack Vista XL", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed at 25-7/8, 27-7/8 or 29-7/8 in", "Shortest; rear-opening"],
   ["Rightline Gear Sport 3", "18 cu ft", "48 × 36 × 18 in", "Soft bag", "Straps; rack optional", "No lock; folds away"],
  ],
 },
 "picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "price": "$709",
   "pros": ["18 in deep, the most room for bulky three-row gear here", "Dual-side opening, so you load from the curb", "24–36 in spread, easy to meet with sliding raised-rail clamps", "79 in long, leaving the liftgate plenty of room on the long roof", "SKS locks and a limited lifetime warranty"],
   "cons": ["51.5 lb, which uses a third of a 165 lb bar rating", "18 in tall, so measure your garage", "About $110 more than the SkyBox 16 on Yakima's store"],
   "body": "For a family Explorer, the GrandTour 16 is the box that takes the awkward loads: camp chairs, a folded stroller, duffels that won't fit behind the third row. Yakima lists it at 16 cu ft and 79 x 35 x 18 in, which makes it the deepest 16 cu ft box on this page, and it opens from both sides, which matters on an SUV this tall because you can load it from the curb instead of the traffic side. It takes skis and boards up to 185 cm, comes with SKS locks and a limited lifetime warranty, and Yakima lists it at $709.\n\nIt suits the Explorer's rack well. Its 24 to 36 in spread range is easy to hit because raised-rail clamps slide along the rails, and at 79 in it is short enough to sit well forward of the power liftgate. The costs are weight and height. At 51.5 lb it takes almost a third of a 165 lb brand-name bar rating, leaving 113.5 lb for gear before you apply the roof limit in your owner's manual, and its 18 in height on top of raised-rail bars can decide whether you clear a garage door. Measure before the first trip home.",
   "who": "Explorer families who want one deep, easy-loading box for soft, bulky gear.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "79 × 35 × 18 in"], ["Box weight", "51.5 lb"], ["Crossbar spread", "24–36 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS locks included"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0C41RZ4HM", "role": "Most usable space", "price": "$699",
   "pros": ["Flat, unobstructed floor that Yakima says maximizes usable space", "15 in tall, 3 in lower than the GrandTour 16", "24–35.5 in spread", "Made in the USA; about 10-minute install", "Dual-side opening, SKS locks, limited lifetime warranty"],
   "cons": ["57 lb, the heaviest box here", "38 in wide, filling more of the bars", "83 in long, so check the liftgate gap"],
   "body": "The CBX 16 is Yakima's box for people who pack square things. Yakima lists it at 16 cu ft and 83 x 38 x 15 in, and says the flattened floor gives it market-leading usable space, which is what you want for bins, carry-ons and hard-sided coolers packed empty. It opens from both sides, takes skis and boards up to 185 cm, and comes with SKS locks and a limited lifetime warranty. Yakima says it installs in about 10 minutes, lists it as made in the USA, and prices it at $699.\n\nOn the Explorer, its low 15 in profile is the reason to pick it over the GrandTour 16: the same 16 cu ft sits 3 in lower, which helps at garage doors and in crosswinds. The long raised-rail bars, 58 to 65 in on etrailer's systems, leave room beside a 38 in wide box for a narrow bike or ski mount. The trade-off is weight. At 57 lb it is the heaviest box here, which leaves 108 lb for cargo on 165 lb bars, so pack it with bulky, light gear and put the heavy items on a hitch carrier. Its 83 in length also calls for a slow first opening of the liftgate.",
   "who": "Explorer owners who pack bins and boxes and want a low 16 cu ft box.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "83 × 38 × 15 in"], ["Box weight", "57 lb"], ["Crossbar spread", "24–35.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Install", "About 10 min"], ["Made in", "USA"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0HGC24R2P", "role": "Best for skis", "price": "$1,149.95 (Thule)",
   "pros": ["18 cu ft with skis up to 200 cm", "Thule rates it for 165 lb of cargo", "21-13/16 to 36-9/16 in spread (etrailer), the widest here", "One-handed dual-side opening, PowerClick mounts, SlideLock", "Limited lifetime warranty per etrailer"],
   "cons": ["$1,149.95 at Thule, the priciest box here", "84.7 in long; Thule lists more than 52 3/32 in of front clearance", "This Amazon listing is a Limited Edition finish; confirm the color"],
   "body": "For an Explorer that heads to the mountains, the Thule Motion 3 XL takes the longest skis on this page. Thule lists it at 18 cu ft, 84.7 x 35 x 17 in and 51 lb, with a 165 lb maximum load and room for 5 to 7 pairs of skis up to 200 cm. The lid opens from either side with one hand, SlideLock separates locking from opening, and PowerClick mounts show when the clamps are torqued. etrailer lists a 21-13/16 to 36-9/16 in spread and a limited lifetime warranty for the Motion 3 line. Thule lists it at $1,149.95; this Amazon listing is a Limited Edition version, so check the finish.\n\nThe box's 165 lb rating matches the Explorer's brand-name bar rating, but the box weight counts first: 51 lb of box on 165 lb bars leaves about 114 lb for skis, boots and bags, before the owner's manual roof figure applies. Length is the other check. Thule lists a front clearance of more than 52 3/32 in, so measure from your front bar to the line where the roof meets the liftgate, as etrailer's experts suggest, and slide the box forward until you have it. Open the power liftgate slowly the first time.",
   "who": "Ski families who want 18 cu ft and 200 cm ski length on a long SUV roof.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "84.7 × 35 × 17 in"], ["Box weight", "51 lb"], ["Max load", "165 lb"], ["Crossbar spread", "21-13/16 to 36-9/16 in (etrailer)"], ["Ski length", "Up to 200 cm"], ["Front clearance", "More than 52 3/32 in (Thule)"], ["Mount / lock", "PowerClick / SlideLock"]]},
  {"asin": "B009NN4ZDS", "role": "Lightest 16 cu ft", "price": "$786.47 (etrailer)",
   "pros": ["36 lb, the lightest hard box here", "The box etrailer's expert named for a 2022 Explorer", "76 in long, short for liftgate room", "23-5/8 to 34-3/8 in spread", "One-Key SecureLock; key only comes out when locked"],
   "cons": ["Single-side lid, opening from the passenger side only", "110 lb cargo rating", "Skis up to 181 cm"],
   "body": "When an Explorer owner asked etrailer which cargo box to buy for a 2022 model, the expert named the Thule Pulse Large. etrailer lists it at 16 cu ft and 76 x 33 x 16-1/2 in, with a 23-5/8 to 34-3/8 in crossbar spread, a 36 lb box weight and a 110 lb maximum load. It holds 6 to 8 pairs of skis up to 181 cm, uses an oversize SecureLock with a Thule One-Key core, and the key can't be removed unless the box is closed and locked. etrailer lists a limited lifetime warranty and a price of $786.47, marked down from $917.32.\n\nThe low weight is its Explorer advantage. At 36 lb it leaves the most of a 165 lb bar rating for other things, which helps if you plan to add a bike mount beside it on the long bars. The limits are the box's own 110 lb cargo rating and the single-side lid, which opens only from the passenger side, so curbside loading works but you can't reach in from the driver's side. At 76 in it is among the shortest boxes here, which gives the liftgate the most room.",
   "who": "Explorer owners who want a light, short 16 cu ft box and load from the curb side.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "76 × 33 × 16.5 in"], ["Box weight", "36 lb"], ["Max load", "110 lb"], ["Crossbar spread", "23-5/8 to 34-3/8 in"], ["Ski length", "Up to 181 cm"], ["Opening", "Passenger side"], ["Warranty", "Limited lifetime (etrailer)"]]},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "price": "$864.97 (etrailer)",
   "pros": ["11 in tall, the lowest box here", "24–39 in spread, the widest top end here", "Tool-free Memory Mount hardware", "Dual-side opening; key only comes out when the lid is closed", "Limited lifetime warranty"],
   "cons": ["11 cu ft, the smallest here", "110 lb cargo rating", "Pricier per cubic foot than the 16s"],
   "body": "If your Explorer lives in a garage, the INNO Wedge 660 is the box that is most likely to clear. etrailer lists it at 80 x 33 x 11 in with 11 cu ft, an interior of 72 x 25-5/8 x 8-1/2 in, a 42 lb box weight and a 110 lb maximum load. It fits crossbar spreads from 24 to 39 in, mounts with tool-free Memory Mount hardware to round, square, aero, elliptical and factory bars, and opens from both sides. The lock's key can't be removed unless the lid is properly closed. etrailer lists a limited lifetime warranty and a price of $864.97; the Amazon listing says it is made in Japan.\n\nThe trade is space for height. Eleven cubic feet holds 6 to 8 pairs of skis or 4 to 6 snowboards, per etrailer, or a family's soft bags, but not bulky camp gear. At 11 in tall it is 4 to 8 in lower than every other hard box here, which can be the difference at a garage door on a tall SUV with raised rails. It also carries less wind load. The 80 in length is moderate, so mount it forward and check the liftgate once.",
   "who": "Explorer owners who park in a garage and carry skis or soft bags.",
   "specs": [["Volume", "11 cu ft"], ["Exterior", "80 × 33 × 11 in"], ["Interior", "72 × 25-5/8 × 8-1/2 in"], ["Box weight", "42 lb"], ["Max load", "110 lb"], ["Crossbar spread", "24–39 in"], ["Mount", "Memory Mount, tool-free"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B00BCLL8C0", "role": "Budget hard box", "price": "$449.95",
   "pros": ["18 cu ft for $449.95 at SportRack", "63 in long, the shortest hard box here", "Tool-free mounting hardware and a lock", "Fits square, round and most factory bars, per SportRack", "UV-resistant ABS shell"],
   "cons": ["Rear-opening lid on a tall SUV", "19 in tall, the tallest here", "Box weight, load rating and warranty not published; confirm"],
   "body": "The SportRack Vista XL is the low-cost way to lock 18 cu ft on an Explorer. SportRack lists it at 63 x 38 x 19 in with 18 cu ft, a UV-resistant ABS shell, tool-free mounting hardware and a lock, for $449.95, less than half the price of the Motion 3 XL. It is short and wide rather than long, which works in the Explorer's favor: at 63 in it sits far forward of the liftgate's arc. etrailer's expert gives three fixed mounting positions, 25-7/8, 27-7/8 and 29-7/8 in center to center. Because raised-rail clamps slide along the rails, you can set the Explorer's bars to one of those exactly.\n\nThe compromises come from the price and the shape. The lid opens at the rear, which keeps you away from traffic but means reaching up and forward from behind a tall SUV; a step stool helps. At 19 in tall it adds the most height here, so measure your garage. SportRack's page doesn't list a box weight, a load rating or warranty terms, so confirm all three on the listing before you plan a load against 165 lb bars.",
   "who": "Budget buyers who want a big, short, lockable box and don't mind loading from the rear.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "63 × 38 × 19 in"], ["Opening", "Rear"], ["Mounting positions", "25-7/8, 27-7/8 or 29-7/8 in (etrailer)"], ["Hardware", "Tool-free; lock included"], ["Material", "UV-resistant ABS"], ["Box weight / max load", "Not published; confirm"], ["Price", "$449.95 (SportRack)"]]},
  {"asin": "B0012INT98", "role": "Best budget", "price": "$139.99 (RealTruck)",
   "pros": ["18 cu ft for $139.99", "Welded seams and a waterproof zipper, per RealTruck", "Works with or without a roof rack", "Folds into a stuff sack when not in use", "Straps and car clips included"],
   "cons": ["No lock", "Soft sides; no skis or rigid shape", "1-year warranty"],
   "body": "If you need roof space twice a year, a soft carrier costs a fraction of a hard box. RealTruck lists the Rightline Gear Sport 3 at 18 cu ft and 48 x 36 x 18 in, with welded seams and an SZIP waterproof zipper that Rightline describes as 100 percent waterproof, no zipper flap required. It is made for SUVs and minivans with or without a roof rack, and comes with four attachment straps, four car clips and a stuff sack. RealTruck lists it at $139.99 with a one-year warranty, and showed it as temporarily unavailable when we checked.\n\nOn the Explorer, the raised rails give the straps something solid to wrap, and on crossbars the bag sits even more securely. At 48 in long it stays well clear of the liftgate. The trade-offs are security and shape: there is no lock, so empty it at hotels, and soft sides flap and sag if the bag isn't packed full. It won't carry skis. Count its contents toward the same 165 lb bar rating and roof limit as any box, and fold it away when you are done to get back the mileage.",
   "who": "Occasional road-trippers who want 18 cu ft of dry roof space for under $150.",
   "specs": [["Volume", "18 cu ft"], ["Size", "48 × 36 × 18 in"], ["Type", "Soft carrier"], ["Weatherproofing", "Welded seams, SZIP waterproof zipper"], ["Mounting", "With or without roof rack; 4 straps, 4 car clips"], ["Lock", "None"], ["Warranty", "1 year"], ["Price", "$139.99 (RealTruck)"]]},
 ],
 "install": [
  "Fit raised-rail crossbars that name the 2020–2026 Explorer, wrap the clamps around the rails through the gap, and torque them to the bar maker's spec.",
  "Note the bar rating (165 lb on brand-name Explorer systems) and look up the roof limit in your owner's manual. Plan box plus cargo under the lower number.",
  "Slide the bars to fit the box's spread range, or to 25-7/8, 27-7/8 or 29-7/8 in for the SportRack Vista XL.",
  "With a helper, set the box on the bars, center it side to side, and slide it forward. Measure from the front bar to the roof-hatch line and compare it with the box maker's clearance figure.",
  "Snug the clamps, open the liftgate slowly to check the gap, then tighten to spec, lock the box and mounts, and rock it from each corner.",
  "Keep the panoramic roof closed while the box is on, load heavy items low and centered between the bars, and recheck the clamps after the first drive.",
 ],
 "avoid": [
  {"h": "Buying the box before the bars", "body": "A box needs crossbars. On the Explorer that means raised-rail bars that name your model year; flush-rail feet won't grip."},
  {"h": "Loading to the box's volume", "body": "A 16–18 cu ft box holds more than 165 lb bars allow once the box weight is counted. Pack light, bulky items up top."},
  {"h": "Opening the panoramic roof with a box on", "body": "etrailer's experts advise against it; the glass or its frame can make contact with the rack or box."},
  {"h": "Mounting the box over the hatch line", "body": "A long box set too far back can meet the power liftgate. Measure, mount forward and open slowly the first time."},
 ],
 "verdict": {
  "thesis": "Fit raised-rail crossbars, then choose the Yakima GrandTour 16 for most families, the CBX 16 for square loads, the Thule Motion 3 XL for skis, or the Rightline Sport 3 on a tight budget.",
  "body": "The sixth-gen Explorer is the easy case for a cargo box: raised rails, long bars and clamps that slide to whatever spread the box needs. The GrandTour 16 is the all-round pick for a three-row family, the CBX 16 gives the same volume 3 in lower with a flat floor, and the Thule Motion 3 XL is worth its price if the trips involve 200 cm skis. The Thule Pulse L is the light, short choice etrailer's expert recommends, the INNO Wedge 660 is the one to buy if a garage door is the limit, and the SportRack Vista XL and Rightline Sport 3 cover budget hard and soft options. Whatever you choose, the 165 lb bar rating and your manual's roof figure decide how much goes inside.\n\nStart with the bars; our Explorer roof rack page lists raised-rail crossbars by trim and year. For heavy gear, a 2 in trailer hitch takes a hitch cargo carrier or bike rack, and laser-fit floor liners protect the cabin on muddy trips. The vehicle hub lists every fit-checked accessory for your Explorer.",
 },
 "sources": [
  ["Yakima GrandTour 16 (Yakima)", "https://yakima.com/products/grandtour-16"],
  ["Yakima CBX 16 (Yakima)", "https://yakima.com/products/cbx-16"],
  ["Thule Motion 3 XL (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-motion-3-xl-_-639850"],
  ["Thule Motion 3 spread and warranty (etrailer)", "https://www.etrailer.com/Roof-Box/Thule/TH59PN.html"],
  ["Thule Pulse Large TH615 (etrailer)", "https://www.etrailer.com/Roof-Box/Thule/TH615.html"],
  ["INNO Wedge 660 (etrailer)", "https://www.etrailer.com/Roof-Box/Inno/INBRM660BK.html"],
  ["SportRack Vista XL (SportRack)", "https://www.sportrack.com/product/vista-xl-cargo-box/"],
  ["SportRack Vista XL mounting positions (etrailer)", "https://www.etrailer.com/question-156482.html"],
  ["Rightline Gear Sport 3 (RealTruck)", "https://realtruck.com/p/rightline-gear-cargo-bags/rlg-100s30/"],
  ["Explorer cargo box and panoramic roof answers (etrailer)", "https://www.etrailer.com/answers.aspx?AnswerModel=Explorer&Manufacturer=Thule&Filter=fit&AnswerMake=Ford"],
  ["2023 Ford Explorer roof rack systems by rail type (etrailer)", "https://www.etrailer.com/roof-2023_Ford_Explorer.htm"],
  ["Ford Explorer, 2027 model shown: standard roof rails and the Slick Roof Conversion that deletes them (Ford)", "https://www.ford.com/suvs/explorer/"],
  ["2024 Ford Explorer drops 3.3L V6 hybrid powertrain (Ford Authority)", "https://fordauthority.com/2023/10/2024-ford-explorer-drops-3-3l-v6-hybrid-powertrain/"],
  ["2024 Ford Explorer Towing Guide: 5,300 lb 2.3L, 5,600 lb 3.0L, 3,000 lb without the package, tongue load (Ford)", "https://www.ford.com/content/dam/brand_ford/en_us/brand/towing/pdf/2024-Ford-Explorer-Towing-Guide.pdf"],
  ["2025 Ford Explorer comparison page: Class III Trailer Tow Package standard, up to 5,000 lb (Ford)", "https://www.ford.com/local/chicago-cedar-rapids-quad-cities/competitive-compare/suvs/explorer/2025/2025-ford-explorer/"],
  ["2026 Ford Explorer Towing Guide: 5,000 lb, standard Class III Trailer Tow Package (Ford)", "https://www.vdm.ford.com/content/dam/brand_ford/en_us/brand/towing/pdf/2026-Ford-Explorer-Towing-Guide.pdf"],
  ["Ford Explorer sixth generation: 5,300 lb 2.3L and 5,600 lb 3.0L tow ratings (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_Explorer_(sixth_generation)"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Explorer roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B083KP48XC","Yakima GrandTour 16 Premium Rooftop Cargo Box, 16 cu ft, dual-side opening","Yakima","$700–$900",{},"Universal box; 24-36 in spread, confirm liftgate gap and garage height (18 in tall)."),
 ("B0C41RZ4HM","Yakima CBX 16 Aerodynamic Rooftop Cargo Box for Cars, Wagons and SUVs","Yakima","$650–$800",{},"Universal box; 24-35.5 in spread, 57 lb. Confirm hatch clearance (83 in long)."),
 ("B0HGC24R2P","Thule Motion 3 XL Rooftop Cargo Box, 18 cu ft, Limited Edition","Thule","$1,100–$1,250",{},"Universal box; 21-13/16 to 36-9/16 in spread. Confirm finish and liftgate clearance."),
 ("B009NN4ZDS","Thule 615 Pulse Cargo Box, Large, Black","Thule","$750–$950",{},"Universal box; 23-5/8 to 34-3/8 in spread, 110 lb max. Confirm spread and hatch clearance."),
 ("B06VX9L59C","INNO BRM660BK Wedge Cargo Box, 11 cu ft, Gloss Black","INNO","$850–$1,000",{},"Universal low box (11 in tall); 24-39 in spread. Confirm spread on your bars."),
 ("B00BCLL8C0","SportRack Vista XL Rear Opening Cargo Box, 18 cu ft, Black","SportRack","$400–$500",{},"Universal box; fixed positions, confirm bar spread, box weight and load rating."),
 ("B0012INT98","Rightline Gear Sport 3 Waterproof Rooftop Cargo Carrier, 18 cu ft, Black","Rightline Gear","$120–$160",{},"Universal soft carrier, no lock; confirm strap routing on your rails or bars."),
]
