"""Pilot long-form article — Best Tonneau Covers for 2021–2026 Ford F-150 (14th gen).
Playbook: /areas/rigconfigurator-article-playbook (best-of skeleton). No invented hands-on testing:
every spec below comes from the manufacturer/retailer pages listed in SOURCES (checked 2026-09-24).
"""

KEY = ("ford", "f-150", "2021-present", "tonneau-covers")

TITLE = "Best Tonneau Covers for 2021–2026 Ford F-150: 6 Fit-Checked Picks by Bed Length"
META = ("Six tonneau covers matched to the 14th-gen F-150 by bed length — 5.5, 6.5 and 8 ft — with load ratings, "
        "warranties, install times and the Lightning, Raptor and Pro Access tailgate notes most lists skip.")

FAQ = [
 ("What is the best tonneau cover for a 2021+ F-150?",
  "For most owners, the BAKFlip MX4 (448339 for the 5.5 ft bed): aluminum panels with polymer cores, 400 lb distributed load rating, auto-latching, a 5-year warranty and a sub-30-minute clamp-on install. If you want a hard cover for about half the money, the Gator EFX is the value pick; if you need the whole bed open without panels stacked against the cab, go RetraxPRO MX."),
 ("Do 2015–2020 F-150 tonneau covers fit a 2021 F-150?",
  "Sometimes. Some soft covers are sold as one part for both generations — the TruXedo Lo Pro 597701 is listed for 2015–2026 on the 5.5 ft bed. Hard covers from BAK, Retrax and Gator use separate 2021+ part numbers (448339, 80378, GC24029). Buy the part number your model year is listed for; don't assume a 13th-gen cover fits."),
 ("Do these covers fit the F-150 Lightning and Raptor?",
  "Both have the 5.5 ft (67.1 in) bed only. The BAKFlip MX4, RetraxPRO MX, Gator EFX and TruXedo Lo Pro listings all name the Raptor and the 2022+ Lightning; the Tyger T3 names the Lightning. For any cover not on this list, look for Lightning or Raptor in the listing title."),
 ("How do I know if I have the 5.5, 6.5 or 8 ft bed?",
  "Measure inside the bed at the rail, from the front bulkhead to the inside of the closed tailgate. About 67 in is the 5.5 ft box, about 79 in is 6.5 ft, and about 98 in is 8 ft. SuperCrew trucks come with 5.5 or 6.5 ft; the 8 ft box was only on SuperCab and Regular Cab, and Ford dropped the SuperCab 8 ft for 2024."),
 ("Will a tonneau cover work with the 2024+ Pro Access tailgate?",
  "The covers here seal against the top of the tailgate and don't attach to it, so they don't stop the tailgate from dropping normally. The makers we checked don't mention the swing-out Pro Access section, though. If you use the swing-out door a lot, ask the seller whether the rear seal clears it before you buy."),
 ("Hard or soft cover — which is better on an F-150?",
  "Hard covers (MX4, EFX, Retrax) lock under a locked tailgate, carry 300–500 lb spread evenly, and hold snow. Soft covers (Lo Pro, T3) cost $230–$520, weigh less and open fast, but a knife gets through vinyl. Buy hard if gear stays in the bed overnight, and soft if you mostly want to keep weather and road dirt out."),
 ("Can I stand on or carry cargo on top of a tonneau cover?",
  "Only on hard covers, and only up to the maker's evenly distributed rating: 500 lb for the RetraxPRO MX, 400 lb for the BAKFlip MX4 and 300 lb for the Gator EFX. The ratings assume the load is spread flat across the cover. A heavy point load, such as a knee or a toolbox corner, can still dent the panels. Soft covers are not built to carry anything on top."),
 ("Do I need to drill to install one?",
  "No. Every cover here clamps to the inside of the bed rails. The makers quote 5–10 minutes (Tyger T3), up to 30 minutes (MX4, EFX) and under an hour (Retrax, Lo Pro). A bedliner that wraps over the rails is the usual snag: Tyger says small holes must be cut in over-rail liners."),
 ("Is a retractable cover worth the extra money?",
  "Only if you need the full bed open often. Nothing stacks against the cab, the cover locks in any position, and the aluminum RetraxPRO carries 500 lb. The costs: the canister takes roughly 10–11 in at the front of the bed, the price is close to $1,850, and if a roller fails, the canister has to come out to be fixed."),
 ("What about a bed rack or rooftop tent with a cover?",
  "A standard folding cover rules out most bed racks unless the rack is built to sit over one. Retrax sells the PRO in an XR version with T-slot rails along the bed, which lets you mount crossbars and racks with the cover in place. If you plan on a rack, choose that before you choose the cover."),
]

ARTICLE = {
 "dek": "Six covers that fit the 14th-generation F-150's 5.5, 6.5 and 8 ft beds, ranked from a $229 soft tri-fold to a $1,850 retractable. For each one we list load rating, warranty and install time, and the fit details for the Lightning, Raptor and Pro Access tailgate.",
 "author": "md-hanzala",
 "reviewed": "2026-09-24",
 "method": "We did not install these covers ourselves. We ranked them on published specs (load rating, materials, warranty, install time), on the fitment the maker lists for the 2021–2026 F-150, and on what F-150 owners report on the F150gen14 and F150Forum boards. Prices were checked at the manufacturer or RealTruck store in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Measure first.** The 14th-gen F-150 comes with three beds: 5.5 ft (67.1 in), 6.5 ft (78.9 in) and 8 ft (97.6 in). A cover for the wrong length won't seal, and no brand fixes that.",
  "**Hard covers from BAK, Retrax and Gator have their own 2021+ part numbers.** Some soft covers, such as the TruXedo Lo Pro 597701, fit 2015–2026. Match the part number to your model year.",
  "**Lightning and Raptor use the 5.5 ft bed only.** Every hard cover here names both in its listing.",
  "**Load ratings are a real difference:** 500 lb for the RetraxPRO MX, 400 lb for the BAKFlip MX4 and 300 lb for the Gator EFX. Soft covers have no load rating.",
  "**Security comes from the tailgate.** A hard cover is only as secure as the tailgate below it, so lock the tailgate or the cover is just a lid.",
 ],
 "top_picks": [
  {"asin": "B08L44X6NZ", "role": "Best overall", "why": "Aluminum panels with polymer cores, 400 lb rating, 5-year warranty, installs in under 30 minutes"},
  {"asin": "B08L71GBX7", "role": "Best value hard cover", "why": "All-aluminum tri-fold with auto slam-latches for about half the price of the MX4"},
  {"asin": "B08L46PC1S", "role": "Best retractable", "why": "500 lb rating, locks at any position, no panels stacked at the cab"},
  {"asin": "B00ONO665M", "role": "Best soft roll-up", "why": "Sits ¾ in above the rails; tension adjusts itself"},
  {"asin": "B0B94WC2F1", "role": "Best budget", "why": "Aluminum-frame soft tri-fold with a 5-year warranty for about $229"},
 ],
 "fit_table": {
  "caption": "2021–2026 F-150 beds (the cover must match the bed, not the cab)",
  "head": ["Bed", "Inside length at rail", "Cabs", "Notes"],
  "rows": [
   ["5.5 ft (sold as 5'7\")", "67.1 in", "SuperCrew", "Only bed on the Raptor and Lightning. Most covers are made for this length."],
   ["6.5 ft (sold as 6'7\")", "78.9 in", "SuperCrew, SuperCab, Regular Cab", "Order the 6.5 ft part number (MX4 448337, RetraxPRO 80379)."],
   ["8 ft", "97.6 in", "SuperCab (through 2023), Regular Cab", "Ford dropped the SuperCab 8 ft for 2024. Fewer cover options."],
  ],
 },
 "look_for": [
  {"h": "Bed length — it outranks brand",
   "body": "Tonneau covers are sold by bed length, and the F-150 has three. Retailers often print 5'7\", 6'7\" and 8'2\" rather than Ford's 5.5, 6.5 and 8 ft names, so check the inches. Measure inside the bed at the rail, from the bulkhead to the inside of the closed tailgate: about 67 in, 79 in or 98 in. If a cover is even an inch short, the tailgate seal won't close up and water gets in at the back corners."},
  {"h": "Generation-specific part numbers",
   "body": "The 2021 redesign kept the 5.5 and 6.5 ft lengths, but BAK, Retrax and Gator still list separate 2021+ part numbers: BAKFlip MX4 448339 vs 448329 for 2015–2020, RetraxPRO MX 80378 vs 80373. Some soft roll-ups carry over. TruXedo lists the Lo Pro 597701 for 2015–2026. The practical rule is to buy the part number the maker lists for your model year, not one from a forum post about a 2018."},
  {"h": "Load rating and what 'hard' really means",
   "body": "For hard covers, the published distributed-load rating is the clearest way to compare. RetraxPRO MX aluminum slats are rated at 500 lb, BAKFlip MX4 aluminum/polymer panels at 400 lb and Gator EFX aluminum panels at 300 lb. Soft vinyl covers carry no rating. They are weather covers. If snow sits on your truck for days, or you want to strap a cooler on top, buy something rated."},
  {"h": "How much bed you get back",
   "body": "Folding covers stack against the cab when open. The MX4 folds flush against the cab, and Gator says the EFX gives roughly two-thirds of the bed when folded. A retractable rolls into a canister that takes about 10–11 in at the front, but the rest of the bed is fully open and the cover can stop anywhere. Roll-ups give the whole bed but leave a rolled bundle strapped at the cab."},
  {"h": "Warranty length is a quality signal",
   "body": "The warranties here range from 2 years (Gator EFX) to 5 years (BAKFlip MX4, Tyger T3) to limited lifetime (RetraxPRO MX, TruXedo Lo Pro, both non-transferable). A longer warranty usually means better seals and latches, which are the parts that fail first on a cover that gets opened every day."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "Part number listed for 2021–2026 F-150 and your bed length in inches", "\"Fits most full-size trucks\" or a range that stops at 2020"],
   ["Frame", "Aluminum frame or rails, no-drill clamps", "Plastic clamps, or listings that don't name a frame material"],
   ["Load rating", "Published distributed rating (300–500 lb) if you need a hard cover", "\"Heavy duty\" with no number"],
   ["Seals / drainage", "Tailgate seal and drain tubes named in the listing", "No mention of drainage"],
   ["Warranty", "2 years minimum; 5 years to lifetime is better", "90 days or nothing stated"],
   ["Brake light", "Third brake light stays visible in every position", "A folded stack that blocks the CHMSL"],
  ],
 },
 "types_table": {
  "caption": "Cover types compared on the F-150",
  "head": ["Type", "Price on this page", "Security", "Bed access", "Load on top", "Best for"],
  "rows": [
   ["Soft roll-up", "~$520 (Lo Pro)", "Low (vinyl)", "Full bed", "None", "Hauling tall loads often"],
   ["Soft tri-fold", "~$229 (T3)", "Low (vinyl)", "About ⅔; can be removed", "None", "Budget weather cover"],
   ["Hard tri-fold", "~$549 (EFX)", "High with tailgate locked", "About ⅔", "300 lb", "Security on a budget"],
   ["Hard fold (MX4)", "~$1,050", "High with tailgate locked", "Nearly full; folds against the cab", "400 lb", "Best all-round"],
   ["Retractable", "~$1,850 (RetraxPRO)", "High; locks at any position", "Full, minus ~10–11 in canister", "500 lb", "Daily open/close, contractors"],
  ],
 },
 "picks": [
  {"asin": "B08L44X6NZ", "role": "Best overall", "price": "$1,050",
   "pros": ["400 lb distributed load rating", "Aluminum panels with high-density polymer cores", "Patented auto-latching system", "Third brake light visible in every position", "5-year warranty; made in Missouri"],
   "cons": ["More than 4× the price of a soft tri-fold", "Stacked panels ride against the cab when open", "Separate part number (448337) for the 6.5 ft bed"],
   "body": "The MX4 is the cover the others get compared to, and it comes out on top on the specs that matter. The aluminum panels have polymer cores, and BAK rates the cover for 400 lb evenly distributed, which is enough for snow or a sheet of plywood laid on top. The latches engage by themselves when you close it. The panels fold flat against the cab, and the third brake light stays visible in every position, which is worth checking on any folding cover.\n\nPart 448339 is listed for the 2021–2026 F-150 5.5 ft bed, including Raptor and the 2022+ Lightning. BAK quotes a one-person install in under 30 minutes with no drilling. The cover clamps inside the rails, so stake-pocket accessories stay usable. RealTruck lists it at $1,049.99 (list price $1,199.99) with a 5-year warranty. One owner's install thread on F150gen14 reports no leaks after setup.",
   "who": "Owners who want a secure hard cover that stays on the truck year-round and will pay once rather than replace a soft cover twice.",
   "specs": [["Type", "Hard folding (tri-fold)"], ["Part #", "448339 (5.5 ft) · 448337 (6.5 ft)"], ["Fits", "2021–2026 F-150 incl. Raptor, 2022+ Lightning"], ["Material", "Aluminum panels, polymer cores"], ["Load rating", "400 lb distributed"], ["Latching", "Auto-latch, locks with tailgate"], ["Install", "<30 min, no drill"], ["Warranty", "5 years"], ["Made in", "USA (Missouri)"]]},
  {"asin": "B08L71GBX7", "role": "Best value hard cover", "price": "$549",
   "pros": ["All aluminum, multi-layer panels", "Automatic dual slam-latches, single pull-cable release", "Drain rails and flush perimeter seals", "Cargo retriever tool included", "About half the price of the MX4"],
   "cons": ["300 lb rating (MX4: 400 lb)", "2-year warranty only", "About ⅔ of the bed is open when folded"],
   "body": "The EFX gets you most of the hard-cover benefits for about half the MX4's price. The panels are multi-layer aluminum. Twin slam-latches lock it automatically, Gator says it has twice as many latch points along the length, and one pull cable releases them. Water is handled by flush perimeter seals and drain rails. At $549 (list $599) at RealTruck, it's the cheapest cover here that locks and carries weight on top.\n\nYou give up some load rating and some warranty. Gator rates the EFX at 300 lb against the MX4's 400 lb, and the warranty is 2 years rather than 5. When the cover is folded, Gator says about two-thirds of the bed is open, so long loads either go diagonal or need the cover off. GC24029 is listed for the 2021–2026 F-150 5'7\" bed, including Raptor and the 2022+ Lightning.",
   "who": "Buyers who want a lockable hard cover under $600 and don't need a 400 lb rating or a long warranty.",
   "specs": [["Type", "Hard tri-fold"], ["Part #", "GC24029 (5.5 ft)"], ["Fits", "2021–2026 F-150 incl. Raptor, 2022+ Lightning"], ["Material", "Multi-layer aircraft-grade aluminum"], ["Load rating", "300 lb distributed"], ["Latching", "Automatic dual slam-latches"], ["Install", "≤30 min, no drill"], ["Warranty", "2 years + 30-day exchange"]]},
  {"asin": "B08L46PC1S", "role": "Best retractable", "price": "$1,850",
   "pros": ["500 lb rating, the highest here", "Locks at any position (TraxLatch)", "Works independently of the tailgate", "Drain tubes in the water-management system", "Limited lifetime warranty"],
   "cons": ["Most expensive cover here", "Canister takes about 10–11 in at the front of the bed", "Roller repairs mean pulling the canister out", "Not fully waterproof at the tailgate gap in heavy rain"],
   "body": "A retractable is the only style here that opens the whole bed and still locks at any point, so you can leave the front 2 ft covered and the back open. The RetraxPRO MX uses double-wall aluminum slats rated for 500 lb, the highest on this page, and it opens and closes regardless of the tailgate. RealTruck lists the 5.5 ft 80378 at $1,849.99 (list $2,149.99) with a limited lifetime warranty.\n\nThe canister takes roughly 10–11 in at the front of the bed, although flat items like plywood or rods can slide underneath it. Rack Attack's breakdown notes that these covers aren't completely watertight at the tailgate gap in hard rain, and that a roller failure means unbolting the canister. If you want crossbars or a bed rack as well, look at the XR version (T-80378), which adds T-slot rails.",
   "who": "Contractors and daily users who open the bed several times a day and want it fully open and locked in any position.",
   "specs": [["Type", "Retractable (manual)"], ["Part #", "80378 (5.5 ft) · 80379 (6.5 ft) · XR: T-80378"], ["Fits", "2021–2026 F-150 incl. Raptor & Lightning"], ["Material", "Double-wall aluminum slats"], ["Load rating", "500 lb distributed"], ["Lock", "Key-lockable TraxLatch, infinite positions"], ["Bed space lost", "~10–11 in (canister)"], ["Install", "<60 min, 4 clamps"], ["Warranty", "Limited lifetime (non-transferable)"]]},
  {"asin": "B00ONO665M", "role": "Best soft roll-up", "price": "$520",
   "pros": ["Sits ¾ in above the rails, the lowest-profile roll-up TruXedo makes", "Self-adjusting spring tensioner keeps it tight in cold weather", "Quick-release; comes off without tools", "One part fits 2015–2026 (and Raptor, Lightning)", "Limited lifetime warranty; assembled in South Dakota"],
   "cons": ["Vinyl gives no real security", "No load rating", "Costs about as much as the Gator EFX hard cover"],
   "body": "For anyone who hauls tall loads every week, a roll-up is the practical choice. It rolls to the cab in seconds and gives the whole bed back. The Lo Pro sits only ¾ in above the rails, so it looks almost flush. Its spring tensioner adjusts itself, which fixes the usual roll-up problem of vinyl going slack in cold weather and flapping at highway speed.\n\nThe 597701 is one of the few covers sold as a single part for 2015–2026 F-150s with the 5'7\" bed, including Raptor and Lightning. That matters if you're buying used or moving the cover to another F-150 later. At $519.99 it costs about the same as the Gator EFX. Choose the Lo Pro for full bed access, and choose the EFX for security.",
   "who": "Owners who haul tall or bulky loads often and care more about full bed access than security.",
   "specs": [["Type", "Soft roll-up"], ["Part #", "597701 (5.5 ft)"], ["Fits", "2015–2026 F-150, 2017+ Raptor, 2022+ Lightning"], ["Material", "Industrial-grade vinyl, leather-grain finish"], ["Profile", "¾ in above rails"], ["Tension", "Self-adjusting spring tensioner"], ["Install", "<1 hr, no drill"], ["Warranty", "Limited lifetime (non-transferable)"]]},
  {"asin": "B0B94WC2F1", "role": "Best budget", "price": "$229",
   "pros": ["$229, the lowest price here", "24 oz marine-grade vinyl on aluminum frames", "Stainless steel clamps", "5–10 minute install (Tyger's estimate)", "5-year warranty, longer than the Gator EFX's"],
   "cons": ["No real security (vinyl)", "Over-rail bedliners need small holes cut", "5.5 ft bed only"],
   "body": "The T3 is the cheapest way to keep rain, road dirt and casual thieves out of an F-150 bed without buying a no-name cover. It uses 24 oz marine-grade vinyl over aluminum frames with stainless clamps, weighs 31.6 lb, and Tyger backs it with a 5-year warranty, longer than you get with the Gator EFX at more than twice the price. Tyger lists it at $229 for the 2021–2026 F-150 and 2022+ Lightning 5.5 ft bed.\n\nOne detail from Tyger's own fitment notes: if your truck has a bedliner that wraps over the rails, you'll need to cut small holes in it for the clamps. Under-rail and spray-in liners need nothing. Tri-folds also flip up against the cab or come off completely, which a roll-up can't do as neatly.",
   "who": "First-time cover buyers, lease trucks, and anyone who wants the bed covered for under $250.",
   "specs": [["Type", "Soft tri-fold"], ["Fits", "2021–2026 F-150, 2022+ Lightning, 5.5 ft"], ["Material", "24 oz marine vinyl, aluminum frames"], ["Clamps", "Stainless steel"], ["Weight", "31.6 lb"], ["Install", "5–10 min (maker's figure), no drill"], ["Warranty", "5 years (US)"]]},
  {"asin": "B0DK3928N1", "role": "Budget hard tri-fold", "price": "$300–$400",
   "pros": ["Hard FRP panels for well under $500", "No-drill clamps", "Listing spans 2015–2025 on the 5.5 ft bed"],
   "cons": ["No published load rating", "Warranty and seal details thinner than name brands", "Check the listing for 2026 fit"],
   "body": "If you want hard panels and $549 for the Gator is too much, FRP (fiberglass-reinforced plastic) tri-folds like this OEDRO are the next step down. The listing covers the 2015–2025 F-150 5.5 ft bed. It doesn't publish a load rating the way BAK, Retrax and Gator do, so treat it as a lockable weather cover, not a platform for cargo. Before you buy, read the listing's warranty terms and recent reviews about the seals.",
   "who": "Buyers who want hard panels under $400 and accept thinner specs and warranty.",
   "specs": [["Type", "Hard tri-fold (FRP)"], ["Fits", "2015–2025 F-150, 5.5 ft (per listing)"], ["Load rating", "Not published"], ["Install", "No drill (per listing)"]]},
 ],
 "install": [
  "Take everything out of the bed and remove any rail caps, BoxLink cleats or accessories that sit where the clamps land.",
  "Set the rails or frame inside the bed rails with the front seal tight against the bulkhead. BAK and Gator frames sit on the inside lip of the rail.",
  "Install the clamps loosely first, typically 4–6 per side, then center the cover so the tailgate seal lines up.",
  "Close the tailgate, check the seal all the way along it, then tighten the clamps evenly. Overtightening one side twists the frame.",
  "Route any drain tubes the cover comes with (Retrax, Gator) down through the stake pockets or corner drain holes.",
  "Re-check the clamps after the first week of driving and then every so often. Retrax lists regular clamp checks as a condition of its warranty.",
 ],
 "avoid": [
  {"h": "Covers listed only as \"fits full-size trucks\"", "body": "A cover has to match your bed to within a fraction of an inch. A listing that doesn't name the 2021–2026 F-150 and a bed length is a guess."},
  {"h": "2015–2020 hard covers on a 2021+ truck", "body": "The makers that sell separate part numbers do it for a reason. Buy the 2021+ SKU unless the listing names your year."},
  {"h": "Relying on a soft cover for security", "body": "Vinyl stops the weather and people looking in. It doesn't stop a knife. Gear worth stealing needs a hard cover and a locked tailgate."},
  {"h": "A folding cover when you want a bed rack", "body": "Most folding covers leave nowhere to mount a rack. If a rack or rooftop tent is planned, look at a railed retractable (RetraxPRO XR) or a rack made to sit over a cover."},
 ],
 "verdict": {
  "thesis": "Measure the bed first, then pick: the BAKFlip MX4 if you can spend $1,050, the Gator EFX if you can't, and the RetraxPRO MX if you open the bed ten times a day.",
  "body": "The best F-150 cover is the one sold for your bed length and model year. After that, the choice depends on how you use the bed. The MX4 has the best mix of load rating, warranty and daily use. The EFX gives you a lockable hard cover for about half the money. The Retrax is worth its price only if full-bed access that locks in any position saves you time every day. For a cover under $250, the Tyger T3's 5-year warranty beats cheap no-name listings.\n\nOnce the cover is on, the next upgrades are bed-side: a bed mat or liner under the cover and a tailgate-lock check. Use the vehicle hub to see every fit-checked accessory for your F-150.",
 },
 "sources": [
  ["BAKFlip MX4 448339 (RealTruck)", "https://realtruck.com/p/bakflip-mx4-tonneau-cover/bak-448339/"],
  ["RetraxPRO MX 80378 (RealTruck)", "https://realtruck.com/p/retraxpro-mx-tonneau-cover/rtx-80378/"],
  ["Gator EFX GC24029 (RealTruck)", "https://realtruck.com/p/gator-efx-hard-fold-tonneau-cover/guc-gc24029/"],
  ["TruXedo Lo Pro 597701 (RealTruck)", "https://realtruck.com/p/truxedo-lo-pro-tonneau-cover/trx-597701/"],
  ["Tyger T3 TG-BC3F1064 (Tyger Auto)", "https://www.tygerauto.com/tonneau-cover/tyger-t3-soft-trifold/tg-bc3f1064/tyger-t3-soft-tri-fold-fit-2021-2026-ford-f-150-lightning-55-bed.html"],
  ["Retrax ONE vs PRO, MX vs XR (Rack Attack)", "https://rackattack.com/retrax-tonneau-cover-review-one-pro-mx-xr-guide"],
  ["Ford F-Series 14th generation (bed and cab configurations)", "https://en.wikipedia.org/wiki/Ford_F-Series_(fourteenth_generation)"],
  ["BAKFlip MX4 owner install thread (F150gen14)", "https://www.f150gen14.com/forum/threads/bakflip-mx4-tonneau-cover-installed-no-leaks.25411/"],
 ],
}

# Product list for this page (replaces the v1 generic list). (asin, name, brand, band, cond, note)
FITS = [
 ("B08L44X6NZ","BAKFlip MX4 Hard Folding Tonneau Cover 448339, 2021-2026 F-150 incl. Raptor/Lightning, 5.5 ft (67.1 in)","BAK","$1,000–$1,200",{"bed_length_in":67},"5-year warranty; 400 lb rating."),
 ("B08L71GBX7","Gator EFX Hard Tri-Fold Tonneau Cover GC24029, 2021-2026 F-150 incl. Raptor/Lightning, 5.5 ft","Gator","$520–$600",{"bed_length_in":67},"300 lb rating; 2-year warranty."),
 ("B08L46PC1S","RetraxPRO MX Retractable Tonneau Cover 80378, 2021-2025 F-150 incl. Raptor/Lightning, 5.5 ft","Retrax","$1,750–$2,150",{"bed_length_in":67},"Canister uses ~10-11 in of bed."),
 ("B00ONO665M","TruXedo Lo Pro Soft Roll-Up Tonneau Cover 597701, 2015-2026 F-150, 5.5 ft","TruXedo","$480–$540",{"bed_length_in":67},"Also fits 2015-2020."),
 ("B0B94WC2F1","Tyger Auto T3 Soft Tri-Fold Tonneau Cover, 2021-2026 F-150 & Lightning, 5.5 ft","Tyger Auto","$220–$260",{"bed_length_in":67},"Over-rail bedliners need small holes cut."),
 ("B0DK3928N1","OEDRO FRP Hard Tri-Fold Tonneau Cover, 2015-2025 F-150, 5.5 ft","OEDRO","$300–$400",{"bed_length_in":67},"No published load rating; confirm 2026 on listing."),
 ("B08L447MY5","BAKFlip MX4 Hard Folding Tonneau Cover 448337, 2021-2026 F-150, 6.5 ft (78.9 in)","BAK","$1,050–$1,250",{"bed_length_in":79},"6.5 ft version of #1."),
 ("B08L46D1CG","RetraxPRO MX Retractable Tonneau Cover 80379, 2021-2025 F-150, 6.5 ft (78.9 in)","Retrax","$1,800–$2,200",{"bed_length_in":79},"6.5 ft version of #3."),
]
