"""Long-form article — Best Running Boards & Side Steps for 2021–2026 Ford F-150 (14th gen) incl. Lightning.
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker/RealTruck pages in sources (checked 2026-09-24).
"""

KEY = ("ford", "f-150", "2021-present", "running-boards")

TITLE = "Best Running Boards for 2021–2026 Ford F-150 SuperCrew: 6 Picks From Westin and Go Rhino to $150 Steps"
META = ("Six F-150 SuperCrew running boards and nerf bars from Westin, Go Rhino, Nilight, YITAMOTOR and Just-V, with "
        "step width, finish, warranty and Lightning fit notes.")

FAQ = [
 ("Do 2015–2020 F-150 running boards fit a 2021+ F-150?",
  "Often, yes, for the SuperCrew. Westin lists its PRO TRAXX 5 21-53945 for 2015–2026 F-150 Crew Cab and 2022–2026 Lightning, and Go Rhino lists its RB20 69415587PC for 2015–2024 F-150 SuperCrew. The cab and rocker mounting points carried over. Check the listing names your cab and years before ordering."),
 ("Do I need to drill to install running boards on an F-150?",
  "Not usually. Westin says its PRO TRAXX nerf bars are bolt-on with no drilling on most applications, and RealTruck lists the Go Rhino RB20 as a bolt-on install with no drilling required. Both use the F-150's factory mounting points on the rocker with vehicle-specific brackets."),
 ("What's the difference between a nerf bar and a running board?",
  "A nerf bar is a round or oval tube with step pads, like the Westin PRO TRAXX 5's 5 in oval tube. A running board is a flat, wider platform, like the Go Rhino RB20. Nerf bars sit a little higher and look sportier; running boards give a bigger stepping surface. Drop steps hang lower for shorter riders or lifted trucks."),
 ("Do running boards fit the F-150 Lightning?",
  "Many do, because the Lightning uses the SuperCrew cab. Westin's PRO TRAXX listings name the 2022–2026 Lightning. Go Rhino's title lists the F-150 SuperCrew; confirm the Lightning with the seller. Check that nothing interferes with the Lightning's underbody battery shielding before tightening brackets."),
 ("How much weight can running boards hold?",
  "It depends on the product. The Go Rhino RB30, a close sibling of the RB20, is rated at 600 lb per side according to RealTruck. Westin's page doesn't state a figure for the PRO TRAXX 5. Budget listings often state a rating in the description; if it isn't listed, ask the seller."),
 ("Will running boards reduce ground clearance?",
  "Slightly. Boards and nerf bars hang below the rocker. Go Rhino's RB20 is designed to sit close to the rocker for clearance. Drop steps like Just-V's hang lower. On a Tremor or Raptor that goes off-road, consider rock sliders instead."),
 ("Do these fit the F-150 SuperCab?",
  "No. Every product here is for the SuperCrew. The SuperCab has a shorter cab with rear-hinged doors, and boards are cab-length specific. Westin sells SuperCab versions under different part numbers, such as the PRO TRAXX 4 21-23935."),
 ("Are aluminum boards better than steel?",
  "Aluminum, like the Nilight 6 in board, is lighter and doesn't rust, though it can corrode in salt. Galvanized steel, like the Go Rhino RB20, is heavier and very strong, with a zinc coating under the finish. Stainless steel, like Westin's polished PRO TRAXX, resists rust and carries Westin's lifetime warranty on that finish."),
 ("Can I install running boards myself?",
  "Yes, with basic tools and a helper. Loosen the rocker plugs or mounting points, bolt the brackets on, then bolt the boards to the brackets. RealTruck's install video for the RB20 is short, and most kits include vehicle-specific instructions. Torque the bolts to spec and recheck after a week."),
 ("What about factory power running boards?",
  "Higher F-150 trims offer factory power-deployable running boards. If your truck has them, aftermarket boards replace them rather than bolting alongside. Aftermarket power steps exist too, but they need wiring and cost more."),
]

ARTICLE = {
 "dek": "Six running boards and nerf bars listed for the 14th-gen F-150 SuperCrew, from Westin's PRO TRAXX 5 and Go Rhino's galvanized RB20 to $150 aluminum steps. Most bolt to factory mounting points without drilling; the choices are step style, width, finish and warranty.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these steps ourselves. We ranked them on the fitment each listing states for the 2021–2026 F-150 SuperCrew and Lightning, on published maker and retailer specs (tube or step width, material, finish, warranty, drilling) and on listing details. Westin specs come from Westin's product page; Go Rhino specs from RealTruck's product pages, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**SuperCrew only here.** Boards are cab-length specific; SuperCab needs its own part.",
  "**Many 2015+ parts fit.** Westin and Go Rhino list 2015 through 2024–2026.",
  "**No drilling on most kits.** Westin and Go Rhino bolt to factory points.",
  "**Warranty differs by finish.** Westin: lifetime on polished stainless, 3 years on black powder coat.",
  "**Drop steps help lifted trucks.** Go Rhino sells an RB20 kit with drop steps.",
 ],
 "top_picks": [
  {"asin": "B00S11FZ32", "role": "Best nerf bar", "why": "Westin PRO TRAXX 5 oval, 2015–2026 F-150 Crew Cab incl. Lightning"},
  {"asin": "B074V9B4J7", "role": "Best running board", "why": "Go Rhino RB20, galvanized steel, lifetime structural warranty"},
  {"asin": "B077PD749M", "role": "Best for lifted trucks", "why": "Go Rhino RB20 with 2 pairs of drop steps"},
  {"asin": "B0CTK467CG", "role": "Best aluminum value", "why": "Nilight 6 in aluminum boards, bolts to factory holes"},
  {"asin": "B0CT5H96YH", "role": "Best budget drop step", "why": "Just-V 4 in drop-down steps, SuperCrew"},
 ],
 "fit_table": {
  "caption": "2021–2026 F-150: fit checklist",
  "head": ["Variable", "Versions", "What to buy"],
  "rows": [
   ["Cab", "SuperCrew, SuperCab, Regular Cab", "All picks are SuperCrew"],
   ["Lightning", "SuperCrew (2022+)", "Westin names it; confirm others"],
   ["Factory boards", "None, fixed or power (by trim)", "Aftermarket replaces factory boards"],
   ["Lift", "Stock or lifted", "Drop steps suit lifted trucks"],
  ],
 },
 "look_for": [
  {"h": "Step style: nerf bar, board or drop step",
   "body": "Side steps for the F-150 come in three shapes. Nerf bars like the Westin PRO TRAXX 5 use a 5 in oval tube with molded step pads; they look sporty and sit close to the body. Running boards like the Go Rhino RB20 give a wide, flat platform; RealTruck lists the RB20 at 7.5 in wide at the front and 6.5 in at the rear. Drop steps hang below the board at each door, which helps shorter passengers and lifted trucks. Pick the shape by who rides in the truck: kids and older passengers benefit most from a wide board or drop steps."},
  {"h": "Cab length and year range",
   "body": "Running boards are cut to the cab. Every product here is for the SuperCrew, and several list 2015 onward because the 13th- and 14th-gen SuperCrew share rocker mounting points. Westin's PRO TRAXX 5 21-53945 lists 2015–2026 F-150 Crew Cab plus 2022–2026 Lightning and the Super Duty Crew Cab. Go Rhino's RB20 lists 2015–2024 SuperCrew. The SuperCab uses shorter parts. Read the title for your cab and year before ordering."},
  {"h": "Material, finish and warranty",
   "body": "Westin offers the PRO TRAXX 5 in 304 stainless steel with a polished finish, covered by a lifetime warranty against manufacturer defects, or e-coated steel with black powder coat, covered for 3 years. RealTruck lists the Go Rhino RB20 as galvanized 16-gauge zinc-coated steel with a textured powder coat or bedliner coating, a limited lifetime structural warranty and a 5-year finish warranty. Budget aluminum and carbon-steel boards rarely publish comparable terms. In salt states, galvanized or stainless holds up best."},
  {"h": "Install and mounting",
   "body": "Westin says the PRO TRAXX 5 is bolt-on with no drilling on most applications and includes a mount kit. RealTruck says the RB20 is bolt-on with no drilling and a vehicle-specific mount kit. Both attach to the F-150's factory rocker mounting points. Budget boards usually use the same points. Plan on a helper to hold the board while you start the bolts, and recheck the torque after a week of driving."},
  {"h": "Clearance and off-road use",
   "body": "Any side step hangs below the rocker and reduces side clearance a little. Go Rhino designs the RB20 to sit tight to the rocker for clearance. Drop steps hang lowest. On a Tremor or Raptor that sees trails, a board can catch on rocks; rock sliders protect the rocker better. For a road truck, the convenience outweighs the small clearance loss."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fit", "SuperCrew and your year named", "\"Fits F-150\" with no cab"],
   ["Mounting", "Bolt-on to factory points, mount kit included", "Kits that need drilling"],
   ["Finish", "Galvanized, stainless or e-coat + powder coat", "Bare paint in salt states"],
   ["Step surface", "Wide, textured or molded pads", "Slick tops"],
   ["Warranty", "Stated structural and finish terms", "No terms"],
   ["Clearance", "Close-to-body design for trails", "Low drop steps off-road"],
  ],
 },
 "types_table": {
  "caption": "Side step types for the 2021–2026 F-150 SuperCrew",
  "head": ["Type", "Example", "Step", "Finish", "Price band", "Best for"],
  "rows": [
   ["Oval nerf bar", "Westin PRO TRAXX 5", "5 in oval tube, molded pads", "Stainless or black", "$250–$400", "Clean, sporty look"],
   ["Flat running board", "Go Rhino RB20", "7.5 in front / 6.5 in rear (RealTruck)", "Galvanized + powder/bedliner", "$450–$600", "Wide step, durability"],
   ["Board + drop steps", "Go Rhino RB20 kit", "Board + 2 pairs drop steps", "Galvanized", "$600–$750", "Lifted trucks"],
   ["Aluminum board", "Nilight 6 in", "6 in", "Aluminum", "$150–$220", "Budget, no rust"],
   ["Drop-down steps", "Just-V 4 in", "4 in drop", "Steel (per listing)", "$180–$260", "Short riders on a budget"],
  ],
 },
 "picks": [
  {"asin": "B00S11FZ32", "role": "Best nerf bar", "price": "$250–$400",
   "pros": ["5 in oval tube with molded step pads", "Lists 2015–2026 F-150 Crew Cab and 2022–2026 Lightning", "Bolt-on, no drilling on most applications", "Mount kit included", "Seamless domed ends, 30° factory-style bends"],
   "cons": ["Black finish has a 3-year warranty (lifetime is for polished stainless)", "Narrower step than a flat board", "Westin doesn't publish a weight rating on its page"],
   "body": "Westin's PRO TRAXX 5 is the nerf bar to start with for a 14th-gen SuperCrew. The 21-53945 listing covers 2015–2026 F-150 Crew Cab, 2022–2026 Lightning and 2017–2026 Super Duty Crew Cab, which shows Westin cut it to the shared cab and rocker. It uses a 5 in oval tube with injection-molded step pads, seamless domed ends and 30° factory-style bends at each end, according to Westin.\n\nWestin says it's a bolt-on install with no drilling on most applications, with a mount kit included. The finish choice affects the warranty: polished 304 stainless steel carries a lifetime warranty against manufacturer defects, while the black powder coat over e-coated steel is covered for 3 years. This listing is the black pair.\n\nThe oval tube gives a narrower step than a flat running board, so it suits drivers who want a clean look and a place to put a boot, rather than a wide platform for kids. If you want the polished stainless version for the longer warranty, Westin sells it under a separate part number.",
   "who": "SuperCrew and Lightning owners who want a clean, sporty step.",
   "specs": [["Part #", "Westin 21-53945"], ["Tube", "5 in oval"], ["Fits", "2015–2026 F-150 Crew Cab, 2022–2026 Lightning"], ["Finish", "Black powder coat over e-coat (this listing)"], ["Mounting", "Bolt-on, no drilling on most applications"], ["Warranty", "3 yr black / lifetime polished stainless"]]},
  {"asin": "B074V9B4J7", "role": "Best running board", "price": "$450–$600",
   "pros": ["Galvanized 16-gauge zinc-coated steel", "Limited lifetime structural warranty, 5-year finish", "Wide step: 7.5 in front, 6.5 in rear per RealTruck", "Bolt-on, no drilling", "Sits close to the rocker for clearance"],
   "cons": ["Title lists 2015–2024; confirm 2025–2026", "Costs more than budget boards", "Heavier than aluminum"],
   "body": "Go Rhino's RB20 is a flat running board with an off-road look, listed for 2015–2024 F-150 SuperCrew. RealTruck describes it as galvanized 16-gauge zinc-coated steel with a textured powder coat (this listing) or a bedliner coating, a limited lifetime warranty on structural defects and a 5-year finish warranty against rust and coating failure. RealTruck lists the step at 7.5 in wide at the front and 6.5 in at the rear.\n\nThat combination of a wide step, galvanized steel and a published structural warranty makes it the best all-round board here. The galvanizing under the powder coat is what matters in salt states: even if the top coat chips, the steel underneath is zinc-coated. Go Rhino designs it to sit tight to the rocker for clearance.\n\nIt installs with a vehicle-specific bracket kit and no drilling, per RealTruck. The title stops at 2024, so confirm a 2025 or 2026 with the seller. RealTruck lists it from $519.99.",
   "who": "Owners who want a wide, durable step with a real warranty.",
   "specs": [["Part #", "Go Rhino 69415587PC"], ["Type", "Flat running board"], ["Width", "7.5 in front / 6.5 in rear (RealTruck)"], ["Material", "Galvanized 16-ga steel"], ["Finish", "Textured powder coat"], ["Warranty", "Limited lifetime structural, 5-yr finish"], ["Fits", "2015–2024 F-150 SuperCrew"]]},
  {"asin": "B077PD749M", "role": "Best for lifted trucks", "price": "$600–$750",
   "pros": ["RB20 board plus two pairs of drop steps", "Same galvanized steel and warranty", "Drop steps help short riders and lifted trucks", "Bolt-on", "One kit"],
   "cons": ["Most expensive here", "Drop steps reduce clearance", "Confirm 2025–2026"],
   "body": "This Go Rhino kit pairs the RB20 board with two pairs of drop steps for the 2015–2024 F-150 SuperCrew. The drop steps hang below the board at each door, so the first step is lower. That's the fix for a lifted F-150 or a truck that carries kids or older passengers.\n\nIt shares the RB20's galvanized 16-gauge steel and warranty terms described by RealTruck. The trade-off is clearance: drop steps are the lowest part of the side of the truck, so they're a poor choice for trail use.\n\nIf your truck is stock height and the main riders are adults, the standard RB20 is enough. Confirm 2025 and 2026 with the seller.",
   "who": "Lifted trucks and families with short passengers.",
   "specs": [["Part #", "Go Rhino 6941558720PC"], ["Includes", "RB20 boards, brackets, 2 pairs drop steps"], ["Material", "Galvanized steel"], ["Fits", "2015–2024 F-150 SuperCrew"], ["Price band", "$600–$750"]]},
  {"asin": "B0CTK467CG", "role": "Best aluminum value", "price": "$150–$220",
   "pros": ["6 in aluminum board", "Bolts to factory rocker holes", "Lists 2015–2026 SuperCrew", "Aluminum doesn't rust", "Low price"],
   "cons": ["No published structural warranty we could check", "Aluminum can corrode in heavy salt", "Lighter-duty than galvanized steel"],
   "body": "Nilight's 6 in aluminum running boards are listed for 2015–2026 F-150 SuperCrew and bolt to the factory rocker holes. At $150–$220, they cost a third of the Go Rhino.\n\nAluminum's advantages are weight and rust resistance; its drawbacks are that it can corrode in heavy road salt and it's not as stiff as galvanized steel. Nilight doesn't publish a weight rating or warranty we could check on the listing summary we saw, so ask before ordering.\n\nFor an OE-style look on a daily-driven truck, it's the value pick. YITAMOTOR's 6 in boards, in our product list, are a close alternative.",
   "who": "Owners who want an OE-style board on a budget.",
   "specs": [["Width", "6 in"], ["Material", "Aluminum"], ["Fits", "2015–2026 F-150 SuperCrew"], ["Mounting", "Factory rocker holes"], ["Price band", "$150–$220"]]},
  {"asin": "B0CT5H96YH", "role": "Best budget drop step", "price": "$180–$260",
   "pros": ["4 in drop-down steps", "Lists 2015–2025 SuperCrew", "Lower first step", "Budget price", "Individual steps at each door"],
   "cons": ["Reduces clearance", "No published warranty we could check", "Less step area than a full board"],
   "body": "Just-V's 4 in drop-down steps are listed for 2015–2025 F-150 SuperCrew. They put a lower step at each door without a full-length board, which is a budget way to help shorter riders into a tall truck.\n\nThe trade-off is clearance and step area. Drop steps hang low and cover less length than a board. Just-V doesn't publish warranty terms we could check.\n\nFor a stock-height truck that carries kids occasionally, they're a practical, cheaper alternative to Go Rhino's drop-step kit.",
   "who": "Budget buyers who want a lower step.",
   "specs": [["Type", "Drop-down steps"], ["Drop", "4 in"], ["Fits", "2015–2025 F-150 SuperCrew"], ["Warranty", "Confirm with seller"], ["Price band", "$180–$260"]]},
  {"asin": "B08DD4WMLQ", "role": "Budget 6 in board", "price": "$150–$220",
   "pros": ["6 in running board", "Lists 2015–2025 SuperCrew", "OE-style look", "Low price", "Bolt-on per listing"],
   "cons": ["No published warranty we could check", "Material specs thin", "Confirm 2026"],
   "body": "YITAMOTOR's 6 in running boards are listed for 2015–2025 F-150 SuperCrew. They're a budget OE-style board, similar to Nilight's.\n\nCompare the two on live price and material: check whether the listing says aluminum or steel and whether it states a weight rating. YITAMOTOR doesn't publish warranty terms we could check.\n\nFor a daily driver where the goal is an easier step and a factory-like look, either budget board works.",
   "who": "Budget buyers comparing OE-style boards.",
   "specs": [["Width", "6 in"], ["Fits", "2015–2025 F-150 SuperCrew"], ["Style", "OE-style board"], ["Warranty", "Confirm with seller"], ["Price band", "$150–$220"]]},
 ],
 "install": [
  "Confirm your cab (SuperCrew) and whether the truck has factory running boards to remove.",
  "Locate the factory mounting points on the rocker; remove plugs or covers per the instructions.",
  "Bolt the brackets to the mounting points hand-tight first.",
  "With a helper, set the board or nerf bar on the brackets and start every bolt.",
  "Level the board front to rear, then torque all bolts to the values in the instructions.",
  "Recheck bolt torque after the first week of driving.",
 ],
 "avoid": [
  {"h": "SuperCab boards on a SuperCrew", "body": "Boards are cab-length specific."},
  {"h": "Bare paint in salt states", "body": "Choose galvanized, stainless or e-coat under powder coat."},
  {"h": "Drop steps on a trail truck", "body": "They're the lowest point on the side of the truck."},
  {"h": "Skipping the torque recheck", "body": "Brackets settle; recheck after a week."},
 ],
 "verdict": {
  "thesis": "Buy the Go Rhino RB20 for a wide, galvanized step with a lifetime structural warranty, Westin's PRO TRAXX 5 for a clean nerf bar that also lists the Lightning, and Nilight for an OE-style board on a budget.",
  "body": "F-150 side steps are easy to fit: most bolt to the factory rocker points without drilling, and many 2015+ parts fit the 14th gen. The real choices are style and durability. Go Rhino's RB20 gives the widest step and the strongest published warranty; Westin's PRO TRAXX 5 is the sporty nerf bar; the drop-step kit suits lifted trucks; Nilight and YITAMOTOR cover the budget end.\n\nRunning boards also keep mud off the sill, which helps your floor liners stay cleaner. If you haven't protected the bed yet, a tonneau cover is the other common first upgrade."},
 "sources": [
  ["Westin PRO TRAXX 5 oval nerf bars (Westin)", "https://www.westinautomotive.com/pro-traxx-5-oval-nerf-step-bars"],
  ["Go Rhino RB20 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb20-running-boards/"],
  ["Go Rhino RB30 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb30-running-boards/"],
  ["Westin 21-53945 listing", "https://www.amazon.com/dp/B00S11FZ32"],
  ["Go Rhino 69415587PC listing", "https://www.amazon.com/dp/B074V9B4J7"],
  ["Ford F-150, fourteenth generation (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_F-Series_(fourteenth_generation)"],
 ],
}

FITS = [
 ("B00S11FZ32","Westin 21-53945 PRO TRAXX 5 Oval Nerf Bars Black, 2015-2026 F-150 & 2022-2026 Lightning Crew Cab","Westin","$250–$400",{"cab":"SuperCrew"},"No drilling on most applications."),
 ("B074V9B4J7","Go Rhino RB20 Running Boards & Brackets 69415587PC, 2015-2024 F-150 SuperCrew","Go Rhino","$450–$600",{"cab":"SuperCrew"},"Galvanized; confirm 2025-2026."),
 ("B077PD749M","Go Rhino RB20 Running Boards + 2 Pair Drop Steps 6941558720PC, 2015-2024 F-150 SuperCrew","Go Rhino","$600–$750",{"cab":"SuperCrew"},"Drop steps; confirm 2025-2026."),
 ("B0CTK467CG","Nilight 6 in Aluminum Running Boards, 2015-2026 F-150 SuperCrew","Nilight","$150–$220",{"cab":"SuperCrew"},"SuperCrew only; bolts to factory rocker holes."),
 ("B0CT5H96YH","Just-V 4 in Drop-Down Running Boards, 2015-2025 F-150 SuperCrew","Just-V","$180–$260",{"cab":"SuperCrew"},"Drop steps; SuperCrew only."),
 ("B08DD4WMLQ","YITAMOTOR 6 in Running Boards, 2015-2025 F-150 SuperCrew","YITAMOTOR","$150–$220",{"cab":"SuperCrew"},"SuperCrew only."),
 ("B00S11FYI8","Westin 21-23945 PRO TRAXX 4 Oval Nerf Bars Black, 2015-2026 F-150 & 2022-2026 Lightning Crew Cab","Westin","$220–$350",{"cab":"SuperCrew"},"4 in oval version."),
 ("B0D3XG4Y5L","6 in 2-Step Side Rails, 2015-2026 F-150 SuperCrew","Generic","$140–$200",{"cab":"SuperCrew"},"Budget."),
]
