"""Long-form article: Best Running Boards, Side Steps & Rock Sliders for 2021–2026 Ford Bronco (6th gen, 2-door and 4-door).
No invented hands-on testing: fit facts come from the Amazon listing titles recorded in FITS (found 2026-10-05 through
amazon.com-restricted searches); specs and prices come from the maker and retailer pages in sources (read 2026-10-05).
Read but not listed in sources (9-entry limit): Rough Country's 2-door BA2 page (41008, same price as on the category page)
and Rough Country's rock slider category for the 2024 Bronco, which showed no products. Ford's media.ford.com Bronco release
could not be fetched (robots.txt error), so wheelbases come from Wikipedia and the factory rock rail trims from Ford's own
accessory store page. Title-only pick, worded that way in the text: Rough Country Rock Sliders. Hooke Road's 4-door drop steps
and the other budget rows at the end of FITS are also title-only and are not picks.
Not verified and worded as such: factory step or rail equipment on Wildtrak, Raptor, Big Bend and Sasquatch builds; Raptor
fit for any pick; the door count of Go Rhino D14131T; why two rail-mounted step listings exclude the 2025 Badlands and Big Bend.
No AMP Research pick: the PowerStep listings our searches returned did not name the Bronco or a model year in their titles.
"""

KEY = ("ford", "bronco", "2021-present", "running-boards")

TITLE = "Best Running Boards & Rock Sliders for 2021–2026 Ford Bronco: 6 Picks by Door Count"
META = ("Six 2021–2026 Bronco side steps by door count: Rough Country power and BA2 boards, Westin drop steps, "
        "Go Rhino D1 and rock sliders, plus factory rock rail notes.")

FAQ = [
 ("What are the best running boards for a 2021–2026 Ford Bronco?",
  "Rough Country's BA2 is the best running board for a 2021–2026 Bronco 4-door. It is a 5 in steel board with a no-drill bolt-on install and a 5-year limited warranty, and Rough Country lists it for 2021–2026. Rough Country's dual-motor power boards fold away for trail clearance and carry a 660 lb per-side rating. For the 2-door, Westin's Outlaw Drop gives the lowest step, and Rough Country's oval nerf steps are the budget bar if the rocker is bare. Go Rhino's D1 has the longest warranty once the seller confirms the door count. Count the doors and look for factory rock rails first, since most steps here go on in place of them."),
 ("Do 2-door Bronco running boards fit the 4-door?",
  "No. A side step runs between the wheel wells, and the two bodies are different lengths there. Wikipedia lists a 100.4 in wheelbase for the 2-door Bronco and 116.1 in for the 4-door, a gap of 15.7 in, with overall lengths of 174.8 in against 189.4 to 190.5 in. Every maker we read sells the two bodies as separate parts. Rough Country's BA2 board is 41008 for the 2-door and 41007 for the 4-door, and Westin's Outlaw Drop is 20-14185 for the 2-door and 20-14195 for the 4-door. Count your doors, then buy a listing whose title names that count."),
 ("Do Bronco Sport running boards fit the full-size Bronco?",
  "No. The Bronco Sport shares the name and nothing under the doors. Wikipedia describes the Bronco Sport as a compact crossover, while the sixth-generation Bronco is based on the Ford Ranger pickup. Rough Country keeps a separate Bronco Sport page for steps and running boards, and the Amazon title for Westin's 20-14185 says it excludes the Bronco Sport. Search results mix the two vehicles constantly. Skip any listing that says Sport, and be careful with one that says only Bronco next to a photo of a crossover."),
 ("Which Broncos come with factory rock rails or side steps?",
  "Ford's accessory store sells the factory rock rails as a part and says they are the OE rails that come standard on Black Diamond, Badlands and First Edition models. A Bronco6G owner reading Ford's Build and Price tool reported a powder-coated tube step as standard on the Outer Banks; we could not confirm that on a Ford page. We also could not confirm what the Wildtrak, Big Bend, Everglades or Raptor carry, or whether equipment changed in later model years. Two Amazon titles for rail-mounted steps exclude the 2025 Badlands and Big Bend, which may point to a change we could not confirm. Look under your doors and check the window sticker."),
 ("Can I add steps to a Bronco that already has factory rock rails?",
  "There are two routes. The first is to take the rails off. Rough Country says its power running boards need factory rock sliders removed, RealTruck says Go Rhino's Dominator D1 requires removal of the OE rock rails if equipped, and Rough Country says its 2-door oval nerf steps do not fit models with factory rock sliders at all. The second route is an add-on step that bolts to the rail itself. The ROADER listing in our product list names the Bronco with rock rail, 2-door and 4-door, for 2021 to 2024. The first route gives a wider step. The second keeps the armor."),
 ("Do these steps fit the Bronco Raptor?",
  "We could not confirm it for any pick. Wikipedia says the Raptor arrived for 2022 as a 4-door only and is wider than other Broncos at 85.7 in. None of the Rough Country, Westin or RealTruck pages we read names the Raptor as a fit or as an exclusion, and none of the six pick titles names it. One rail-mounted step listing we saw says in its title that it does not fit the Raptor. If you own a Raptor, send the seller your VIN and ask for the part number in writing before you order."),
 ("Do these steps fit a Bronco with the Sasquatch package?",
  "No maker page we read mentions the Sasquatch package, so treat it as unconfirmed. The package's 35 in tires make the sill sit higher off the ground. Westin lists its Outlaw Drop for the Bronco as a rocker panel mount, and RealTruck says Go Rhino's Dominator D1 mounts to the rocker panel. That is a reason to expect the same brackets to line up, not proof. A taller Bronco also makes a drop step more useful. Ask the seller to confirm the part for a Sasquatch build before you buy."),
 ("Are power running boards worth it on a Bronco?",
  "They are the only type that gives a low step at the curb and nothing below the rocker on the trail. Rough Country lists its dual-motor 4-door kit, PSR51330, at $1,399.95 on its own site, with 6 in aluminum boards, a 660 lb capacity per side and a no-drill install. Its HT-Series 4-door kit is listed there at $999.95 on sale from $1,099.95. The dual-motor kit costs more than three times the BA2 board, and its motors live in mud and road salt. Rough Country also says factory rock sliders must be removed. For a Bronco that stays on pavement, a fixed board does the job for much less."),
 ("What is the difference between a running board and a rock slider?",
  "A running board is built for feet. A rock slider is built to carry the vehicle when the rocker comes down on a rock. Ford's accessory page shows the gap: it describes the factory rock rails as heavy-gauge steel with a load-bearing design, made to support up to 1.5 times the vehicle weight. No running board on this page publishes anything close to that. Rough Country's power boards quote 660 lb per side, which is a rating for people. If the Bronco crawls over rocks, keep or buy rails. If it carries passengers on roads, a board or drop step is easier to use."),
 ("Do I need to drill to install Bronco side steps?",
  "Not for the documented picks. Rough Country describes the BA2 boards as a no-drill, direct bolt-on installation, and says the same of its power boards and its 2-door oval nerf steps. Westin lists the Outlaw Drop as a bolt-on installation with no drilling required and includes the hardware and mounting brackets. RealTruck lists Go Rhino's Dominator D1 as a no-drill installation on most applications. We could not read a maker page for Rough Country's Rock Sliders or for the Hooke Road drop steps in our product list, so check those listings for the mounting method before the Bronco goes up on stands."),
 ("How much weight can Bronco running boards hold?",
  "Only one maker page we read gives a number. Rough Country quotes a 660 lb weight capacity per side for its power running boards. Its BA2 and oval nerf pages give no rating, Westin gives none for the Outlaw Drop, and RealTruck gives none for Go Rhino's Dominator D1. One budget listing in our product list, from Broaddict, states 350 lb in its title. A rating covers a person stepping, per side. It does not make the board a jacking point or a tie-down. If the listing gives no figure and a heavy rider will use the step, ask the seller first."),
]

ARTICLE = {
 "dek": "Six side steps listed for the sixth-generation Bronco, from Rough Country's 2-door oval nerf bars to its dual-motor power boards for the 4-door, with Westin drop steps, Go Rhino's all-steel D1 and rock sliders in between. Door count decides fit first. Factory rock rails on some trims decide what has to come off.",
 "author": "jake-morrison",
 "reviewed": "2026-10-05",
 "method": "We did not install these steps ourselves, and we have not driven a Bronco with any of them. Each pick is an Amazon listing whose title names the Ford Bronco and a model year from 2021 on; listings for the Bronco Sport were skipped. We ranked the picks on the door count and years in those titles, and on the specs, fit notes, warranties and prices published by Rough Country and Westin on their own sites and by RealTruck for Go Rhino, all read in October 2026. One pick, Rough Country's Rock Sliders, had no maker page we could read, so everything said about it comes from the listing title and is marked that way. The same goes for the budget listings at the end of our product list. Factory rock rail facts come from Ford's accessory store, wheelbases from Wikipedia, and one owner report from a Bronco6G thread. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Count the doors first.** The 2-door has a 100.4 in wheelbase and the 4-door 116.1 in (Wikipedia), so every step is sold by door count.",
  "**Check for factory rock rails.** Ford says its OE rails come standard on Black Diamond, Badlands and First Edition models. Several steps need them removed.",
  "**Not the Bronco Sport.** It is a compact crossover with its own parts. Skip any listing that says Sport.",
  "**One published load rating.** Rough Country quotes 660 lb per side for its power boards. No other pick publishes a figure we could read.",
  "**Titles lag the makers.** Most Amazon titles stop at 2023, 2024 or 2025, while Rough Country, Westin and RealTruck list the same parts through 2026. Confirm later years.",
 ],
 "top_picks": [
  {"asin": "B0C31HSQYX", "role": "Best overall (4-door)", "why": "Rough Country BA2, 5 in steel board, no-drill bolt-on, 5-year limited warranty, maker lists 2021–2026"},
  {"asin": "B0BWSHMVMT", "role": "Best power step (4-door)", "why": "Rough Country dual-motor boards, 6 in aluminum, 660 lb per side, LED lights, retracts when the doors close"},
  {"asin": "B0CLPJHSSN", "role": "Best for the 2-door", "why": "Westin Outlaw Drop 20-14185, 4 in drop step plates, no drilling, 3-year warranty"},
  {"asin": "B0B57FF3SD", "role": "Best warranty", "why": "Go Rhino Dominator Xtreme D1, all-steel 5.5 in step, limited lifetime structural warranty"},
  {"asin": "B0B5FDGKT9", "role": "Best budget (2-door)", "why": "Rough Country oval nerf steps, 4.5 in step area, no-drill, 5-year limited warranty"},
 ],
 "fit_table": {
  "caption": "2021–2026 Bronco: what decides side step fit",
  "head": ["Variable", "Versions", "What to buy"],
  "rows": [
   ["Doors", "2-door (100.4 in wheelbase) or 4-door (116.1 in), per Wikipedia", "A listing whose title names your door count: Rough Country 41008 or Westin 20-14185 for the 2-door, 41007 or 20-14195 for the 4-door"],
   ["Bronco or Bronco Sport", "Full-size Bronco or the compact Bronco Sport crossover", "Full-size parts only; skip any title that says Sport"],
   ["Factory rock rails", "Standard on Black Diamond, Badlands and First Edition (Ford accessory store)", "A step that replaces the rails, or an add-on step that bolts to them"],
   ["Other trims", "Outer Banks tube step reported by an owner; Wildtrak, Big Bend and Everglades not confirmed", "Look under the doors and check the window sticker"],
   ["Raptor", "4-door only, 85.7 in wide (Wikipedia)", "No maker page we read names it; confirm with the seller"],
   ["Sasquatch package", "35 in tires", "No maker page we read mentions it; confirm with the seller"],
   ["Model year", "2021 to 2026", "Titles often stop early; check the maker's fit line and ask about later years"],
  ],
 },
 "look_for": [
  {"h": "Door count sets the length",
   "body": "A Bronco step is cut to the distance between the wheel wells, and the two bodies differ there by more than a foot. Wikipedia lists a 100.4 in wheelbase for the 2-door and 116.1 in for the 4-door, with overall lengths of 174.8 in and 189.4 to 190.5 in. The extra length is where the rear doors are. Makers handle it with separate part numbers. Rough Country's site lists many of its Bronco steps twice, once per body: BA2 boards as 41008 and 41007, power boards as PSR51230 and PSR51330. Westin's Outlaw Drop is 20-14185 for the 2-door and 20-14195 for the 4-door. A title with no door count, such as Go Rhino's D14131T on this page, needs a question to the seller before you order. A 2-door step on a 4-door leaves the rear door with nothing under it."},
  {"h": "Factory rock rails change the job",
   "body": "Some Broncos leave the plant with steel rails already bolted under the doors. Ford's accessory store sells them as a part for 2021–2026 4-door models and says they are the OE rails that come standard on Black Diamond, Badlands and First Edition models. Ford describes heavy-gauge steel, a black powder coat and a load-bearing design made to support up to 1.5 times the vehicle weight. That is real armor, and it sits where most aftermarket steps mount. Rough Country says its power boards need factory rock sliders removed, RealTruck says the same of Go Rhino's D1, and Rough Country's 2-door oval nerf steps do not fit a Bronco that has them. Decide whether you want a step in place of the rails or a small step added to them."},
  {"h": "Board, drop step, tube or slider",
   "body": "The four fixed types trade step height against clearance. A flat board such as Rough Country's BA2 gives a 5 in stepping area and sits close under the rocker. A drop step such as Westin's Outlaw Drop hangs a die-stamped plate 4 in below the bar at each door, which is the lowest and easiest first step and also the first thing to catch a rock. An oval nerf bar such as Rough Country's 2-door part, with its 4.5 in step area, has the lowest maker price on this page. A rock slider is built for impacts first and feet second. On a Bronco the choice follows how the vehicle is used: drop steps and boards for road and gravel, rails or sliders for rocks, and a power board when you want both."},
  {"h": "Power steps and their cost",
   "body": "A power board drops when a door opens and folds up when it closes. On a Bronco that solves the clearance argument, because nothing hangs below the rocker while you drive. Rough Country's dual-motor kit for the 4-door, PSR51330, is listed on its own site at $1,399.95 with 6 in aluminum boards, a 660 lb capacity per side, LED lights, an automatic SAFE-STOP feature and an interior bypass switch. Its HT-Series 4-door kit is listed at $999.95 on sale from $1,099.95. Both cost more than twice the BA2 board, and the motors and linkages sit where mud and salt collect. Rough Country also says factory rock sliders have to come off, so a Badlands owner gives up steel rails to fit them. The AMP Research listings our searches returned did not name the Bronco in their titles, so none is listed here."},
  {"h": "Year ranges, warranty and what is published",
   "body": "The Bronco has been one generation since 2021, but Amazon titles are often older than the maker's fit list. Most Rough Country titles on this page stop at 2024 or 2025 while its site lists the same boards for 2021–2026. Westin's Amazon title for 20-14185 says 2021–2024 and Westin's application list says 2021–2026. Go Rhino's title says 21-24 and RealTruck's fit line says 2021–2026. Use the maker's range as the reason to ask, and get the seller's answer for your year. Warranty terms differ more than prices do: Rough Country gives 5 years limited on BA2 boards and oval nerf steps and its lifetime warranty on the power boards, Westin gives 3 years, and RealTruck lists a limited lifetime structural warranty with 5 years on the finish for Go Rhino's D1."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Doors", "2-Door or 4-Door in the title", "Titles with no door count, unless the seller confirms"],
   ["Vehicle", "Ford Bronco with a year from 2021 on", "Bronco Sport parts, or a bare 'Bronco' with a crossover in the photo"],
   ["Factory rails", "A clear statement that the kit replaces or bolts to the OE rock rails", "Assuming the rocker mounting points are free"],
   ["Mounting", "Bolt-on, no drilling, brackets and hardware included", "Kits that do not say how they mount"],
   ["Load", "A published per-side figure (660 lb on Rough Country's power boards)", "'Heavy duty' with no number when a heavy rider will use it"],
   ["Warranty", "Written terms: 3 years (Westin), 5 years (Rough Country), lifetime structural (Go Rhino)", "No terms stated"],
  ],
 },
 "types_table": {
  "caption": "Side step types for the 2021–2026 Bronco",
  "head": ["Type", "Example", "Doors", "Clearance when driving", "Price band", "Best for"],
  "rows": [
   ["Flat board", "Rough Country BA2 (41007 / 41008)", "4-door / 2-door", "Medium", "$300–$400", "Daily drivers, road and gravel"],
   ["Power board", "Rough Country dual-motor (PSR51330)", "4-door", "Full (folds up)", "$1,300–$1,450", "Road comfort without losing clearance"],
   ["Drop step", "Westin Outlaw Drop 20-14185", "2-door", "Low", "$490–$530", "Lowest first step"],
   ["All-steel side step", "Go Rhino Dominator Xtreme D1", "Confirm", "Medium", "$550–$600", "Long warranty, wide tread"],
   ["Oval nerf bar", "Rough Country 21012", "2-door", "Medium", "$200–$240", "Budget, close to the body"],
   ["Rock slider", "Rough Country Rock Sliders", "4-door", "Built for impacts", "Check listing", "Rock trails"],
  ],
 },
 "picks": [
  {"asin": "B0C31HSQYX", "role": "Best overall (4-door)", "price": "$350–$400",
   "pros": ["Wide 5 in stepping area (Rough Country)", "Heavy-duty steel construction", "No-drill, direct bolt-on installation", "5-year limited warranty", "Maker lists it for 2021–2026 4-door Broncos"],
   "cons": ["No published weight rating", "Amazon title stops at 2025; confirm 2026", "Maker's page does not say how it works with factory rock rails"],
   "body": "Rough Country's BA2 is the plain answer for a 4-door Bronco that needs a step and nothing more. The Amazon title lists it for the 2021–2025 Ford Bronco 4-Door and describes wide 5 in non-slip side steps. Rough Country's own page for the 4-door board, part 41007, lists the 2021–2026 Bronco, 4-door models only, and describes heavy-duty steel construction, a wide 5-inch stepping area and a no-drill, direct bolt-on installation. Rough Country lists it at $379.95 with a 5-year limited warranty.\n\nThe page does not give a weight rating, and it does not say what happens on a Bronco with factory rock rails. Rough Country's other Bronco steps either need the factory sliders removed or do not fit with them, so ask before you order for a Black Diamond or Badlands. A flat 5 in board gives more foot room than a tube and sits higher than a drop step, which suits a daily driver that sees gravel more often than rocks. The title stops at 2025 while the maker's page reads 2021–2026, so a 2026 owner should confirm with the seller. The 2-door board is part 41008, which Rough Country lists at $299.95. We did not find it in an Amazon result, so it is not in our product list. For a lower first step on the 4-door, Hooke Road's 5.4 in drop-down steps are in the product list; their title names 2021, 2022 and 2023 only, and we could not read a maker page for them.",
   "who": "4-door owners who want a documented fixed board with a written warranty and no wiring.",
   "specs": [["Part #", "Rough Country 41007 (4-door); 41008 is the 2-door board"], ["Type", "Flat running board"], ["Fits", "2021–2025 Bronco 4-Door (listing title); 2021–2026 (Rough Country)"], ["Step", "5 in stepping area"], ["Material", "Heavy-duty steel"], ["Install", "No-drill, direct bolt-on"], ["Warranty", "5-year limited"], ["Price", "$379.95 (Rough Country)"], ["Weight rating", "Not published; ask the seller"]]},
  {"asin": "B0BWSHMVMT", "role": "Best power step (4-door)", "price": "$1,300–$1,450",
   "pros": ["Folds up when the doors close, so nothing hangs below the rocker", "660 lb weight capacity per side (Rough Country)", "6 in aluminum boards with an anti-slip surface", "Integrated LED lights, SAFE-STOP feature and an interior bypass switch", "No-drill installation, covered by Rough Country's lifetime warranty"],
   "cons": ["Several times the price of a fixed board", "Factory rock sliders must be removed (Rough Country)", "Amazon title stops at 2025; confirm 2026"],
   "body": "A power board is the one type that gives the Bronco a low step in the driveway and nothing below the rocker on the trail. The Amazon title lists Rough Country's Power Running Boards with LED step lights for the Ford Bronco 4-Door, 2021–2025, with dual motors and a textured anti-slip surface. Rough Country's page for the 4-door dual-motor kit, PSR51330, lists 2021–2026 and describes aluminum boards 6 inches wide, a 660 lb weight capacity per side, integrated LED lights that illuminate the board when it deploys, an automatic SAFE-STOP safety feature, an interior bypass switch and a no-drill installation. Rough Country lists it at $1,399.95 and says it is covered by its lifetime warranty.\n\nThe 660 lb figure is the only per-side rating published for any pick on this page. Two cautions come from the same source. If the vehicle has factory rock sliders, Rough Country says they will need to be removed, so a Badlands or Black Diamond owner trades steel rails for aluminum boards with motors. And the page as we read it does not describe the wiring, so read the instructions for where the harness connects before you start. Rough Country also lists a 2-door kit, PSR51230, at the same price, and a lower-priced HT-Series kit for the 4-door at $999.95 on sale from $1,099.95. The HT-Series is in our product list. The Amazon title stops at 2025, so confirm 2026 with the seller and match the part number on the listing to PSR51330.",
   "who": "4-door owners who carry passengers every day, still leave pavement, and will pay for steps that disappear.",
   "specs": [["Part #", "Rough Country PSR51330 (4-door); PSR51230 is the 2-door kit"], ["Type", "Power-retractable board, dual motor"], ["Fits", "2021–2025 Bronco 4-Door (listing title); 2021–2026 (Rough Country)"], ["Board", "6 in wide, aluminum"], ["Weight capacity", "660 lb per side"], ["Lights", "Integrated LED"], ["Install", "No-drill; factory rock sliders must be removed"], ["Warranty", "Rough Country lifetime warranty"], ["Price", "$1,399.95 (Rough Country)"]]},
  {"asin": "B0CLPJHSSN", "role": "Best for the 2-door", "price": "$490–$530",
   "pros": ["4 in drop die-stamped step plate for a low first step", "1.5 in mandrel-bent steel tube with a fully welded top plate", "Textured black powder coat over an E-coated base coat", "Bolt-on, no drilling; hardware and brackets included", "3-year warranty against manufacturer defects"],
   "cons": ["Drop plates are the lowest fixed part on the body side", "Amazon title stops at 2024; Westin lists 2021–2026", "No published weight rating"],
   "body": "Two-door owners have fewer step choices, and Westin's Outlaw Drop is the best documented of them. The Amazon title lists part 20-14185 for the 2021–2024 Ford Bronco 2-Door and says it excludes the Bronco Sport. Westin's own application list shows 20-14185 for the 2021–2026 Bronco 2-door with a rocker panel mount, and 20-14195 for the 4-door. Westin describes a 1.5 in diameter mandrel-bent steel tube with a fully welded cab-length top plate and a 4 in drop die-stamped step plate that gives traction while clearing dirt, mud and debris. The finish is a textured black powder coat over an E-coated base coat for corrosion protection.\n\nThe drop is the reason to buy it. The step plate sits 4 in below the bar, so the first step is lower than a board or a nerf bar gives. It is also the reason to skip it on rocks, because the plates are the lowest fixed point on the side. Westin lists the installation as bolt-on with no drilling required, with hardware and mounting brackets included, and backs it for three years from the date of purchase against manufacturer defects. Westin prices the Outlaw Drop line from $493.99 to $528.99 depending on the vehicle. Westin's page does not mention factory rock rails or give a weight rating, so ask about both. The Amazon title stops at 2024; a 2025 or 2026 owner should confirm with the seller. We did not find an Amazon title for the 4-door 20-14195 that names a model year, so it is not listed here.",
   "who": "2-door owners who want the lowest fixed step from a maker with a published fit list and warranty.",
   "specs": [["Part #", "Westin 20-14185 (2-door); 20-14195 is the 4-door part"], ["Type", "Drop nerf step bar"], ["Fits", "2021–2024 Bronco 2-Door (listing title); 2021–2026 (Westin)"], ["Tube", "1.5 in mandrel-bent steel"], ["Step", "4 in drop die-stamped plate"], ["Finish", "Textured black powder coat, E-coat base"], ["Mount", "Rocker panel, no drilling"], ["Warranty", "3 years"], ["Line price", "$493.99–$528.99 (Westin)"]]},
  {"asin": "B0B57FF3SD", "role": "Best warranty", "price": "$550–$600",
   "pros": ["Heavy-duty all-steel construction with plate steel accents (RealTruck)", "Full-width 5.5 in stepping surface", "Dimpled tread with a raised hexagonal pattern for grip", "Limited lifetime structural warranty, 5 years on the finish", "Rocker panel mount, no-drill on most applications"],
   "cons": ["Neither the title nor RealTruck's fit line names a door count", "OE rock rails must be removed if equipped", "Amazon title says 21-24; RealTruck lists 2021–2026"],
   "body": "Go Rhino's Dominator Xtreme D1 is the heaviest-built fixed step on this page that has a spec sheet behind it. The Amazon title lists part D14131T, D1 side steps with a rocker panel mounting bracket kit, for the Ford 21-24 Bronco. RealTruck lists the same part number at $574.99 for the 2021–2026 Ford Bronco and describes heavy-duty all-steel construction with plate steel accents, a full-width 5.5 in wide stepping surface, a dimpled step tread with a raised hexagonal pattern for grip, and a corrosion-resistant textured black powder coat. It mounts to the rocker panel and is a no-drill installation on most applications.\n\nThe warranty is the strongest here for a fixed step: RealTruck lists a limited lifetime structural warranty with 5 years on the finish. The kit pairs Go Rhino's D10057T side steps with its D64129TK mounting brackets, plus hardware and instructions. Two things need care. RealTruck says installation requires removal of the OE rock rails if the Bronco has them, so this is a replacement for factory rails, not an addition. And neither the Amazon title nor the RealTruck fit line we read names 2-door or 4-door. Another Go Rhino listing we saw, for 73 in long DSS boards, also names the 21-24 Bronco, so Go Rhino makes more than one length. Send the seller your door count and ask which body D14131T is cut for before you order. The title stops at 2024, so later-year owners should confirm that too. RealTruck does not publish a weight rating for it.",
   "who": "Owners who want an all-steel step with a lifetime structural warranty and will confirm the door count first.",
   "specs": [["Part #", "Go Rhino D14131T (steps D10057T + brackets D64129TK)"], ["Type", "All-steel side step, cab length"], ["Fits", "Ford 21-24 Bronco (listing title); 2021–2026 (RealTruck); door count not named"], ["Step", "5.5 in wide, dimpled hexagonal tread"], ["Finish", "Textured black powder coat"], ["Mount", "Rocker panel; OE rock rails removed if equipped"], ["Warranty", "Limited lifetime structural, 5-year finish"], ["Price", "$574.99 (RealTruck)"]]},
  {"asin": "B0B5FDGKT9", "role": "Best budget (2-door)", "price": "$200–$240",
   "pros": ["Wide 4.5 in stepping area (Rough Country)", "Steel construction with 30-degree angled ends", "No-drill installation", "5-year limited warranty", "Lowest maker price of the documented picks"],
   "cons": ["Does NOT fit models with factory rock sliders (Rough Country)", "Higher step than a drop bar", "Amazon title stops at 2025; confirm 2026"],
   "body": "Rough Country's Oval Nerf Steps are the low-cost way to put a step on a 2-door Bronco. The Amazon title lists them for the Ford Bronco 2-Door, 2021–2025, as classic OEM-style rails with 4.5 in side steps. Rough Country's page for part 21012 lists the 2021–2026 Bronco 2-door and describes durable steel construction, a 30-degree angled end design, a wide 4.5-inch stepping area, a black finish and a no-drill installation, with a 5-year limited warranty. Rough Country lists it at $209.95 on sale, from a regular $229.95.\n\nOne line on that page matters more than the rest: Rough Country says the part does NOT fit models with factory rock sliders. That rules it out for a 2-door Black Diamond or Badlands with the OE rails in place, unless you plan to take them off and the seller confirms the brackets then fit. On a Bronco with a bare rocker, an oval bar is a sensible choice. It sits close to the body, keeps more clearance than a drop step, and still gives a toe-hold for reaching the roof. The step is higher than Westin's Outlaw Drop, so shorter passengers will notice the difference. Rough Country lists the 4-door version, 21011, at $279.95. We found it only on an Amazon page we could not tie to a single product, so it is not in our product list. The title stops at 2025; confirm 2026 with the seller.",
   "who": "2-door owners without factory rock rails who want a brand-name bar for the least money.",
   "specs": [["Part #", "Rough Country 21012 (2-door); 21011 is the 4-door bar"], ["Type", "Oval nerf step bar"], ["Fits", "2021–2025 Bronco 2-Door (listing title); 2021–2026 (Rough Country)"], ["Step", "4.5 in stepping area"], ["Material", "Steel, black finish"], ["Install", "No-drill"], ["Not for", "Models with factory rock sliders"], ["Warranty", "5-year limited"], ["Price", "$209.95 on sale, $229.95 regular (Rough Country)"]]},
  {"asin": "B0B6CR4C48", "role": "Rock slider (4-door)", "price": "Check listing",
   "pros": ["Sold as rock sliders, not as a step", "Title names the 4-door, so the length question is settled", "Sold as a pair", "Known brand with its own support line", "Fixed, so no wiring"],
   "cons": ["No maker page we could read, so no specs beyond the title", "Title stops at 2024", "Not on Rough Country's own Bronco pages when we looked"],
   "body": "For a Bronco that drags its rockers over ledges, a slider is the right part and a running board is the wrong one. The Amazon title lists Rough Country's Rock Sliders for the Ford Bronco, 2021–2024, fits 4-door, sold as a pair. That is everything we can confirm about this pick. Rough Country's rock slider category for the 2024 Bronco showed no products when we opened it, and the sliders are not on its Bronco steps page, so there was no maker spec sheet to read. Treat the listing as your only source and read it closely.\n\nThe questions to answer there are the ones that separate armor from decoration. Does it mount to the frame, the body, or both? Does it need drilling? What is the steel thickness, and does the maker state any load or impact rating? Does it replace the factory rock rails on a Black Diamond or Badlands, and does it have a flat top you can stand on? For comparison, Ford describes its own OE rock rails as heavy-gauge steel made to support up to 1.5 times the vehicle weight. If your Bronco has those, you may not need this pick at all, and an add-on step for the rails is the cheaper move. If it does not, ask the seller for the part number and the mounting method in writing. The title stops at 2024, so owners of later years should also confirm fit before ordering.",
   "who": "4-door owners without factory rails who run rocky trails and want protection before a step.",
   "specs": [["Brand", "Rough Country"], ["Type", "Rock slider, pair"], ["Fits", "2021–2024 Bronco, 4-Door (listing title)"], ["Mounting", "Not read; confirm on the listing"], ["Material", "Not read; confirm on the listing"], ["Wiring", "None"], ["Warranty", "Not read; confirm on the listing"]]},
 ],
 "install": [
  "Confirm your door count and model year, then look under the doors. If the Bronco has factory rock rails or tube steps, find out whether your kit replaces them, bolts to them, or does not fit with them.",
  "Remove the factory rails or steps if the kit calls for it, and keep the hardware. Go Rhino's D1 and Rough Country's power boards both require the OE rails off.",
  "Find the mounting points on the rocker panel that the instructions name for your body, and clear any plugs or covers.",
  "Bolt the brackets on hand-tight. With a helper, set the board or bar on the brackets and start every bolt before tightening any of them.",
  "For power boards, route the harness away from the exhaust and moving parts, connect it as the instructions show, then open and close each door to check that the board deploys and retracts.",
  "Level each side, torque every bolt to the value in the instructions, and check that the doors open fully without touching the step.",
  "Recheck the bolts after the first week of driving and again after the first trail day.",
 ],
 "avoid": [
  {"h": "2-door steps on a 4-door, or the reverse", "body": "The wheelbases differ by 15.7 in (Wikipedia). The brackets will not line up, and makers sell separate part numbers for each body."},
  {"h": "Bronco Sport listings", "body": "The Sport is a compact crossover with its own steps. A title that says Sport is for a different vehicle."},
  {"h": "Ordering before you check for factory rails", "body": "Ford says its OE rock rails are standard on Black Diamond, Badlands and First Edition models. Several steps here need them removed or do not fit with them."},
  {"h": "Treating a step as a rock slider or a jacking point", "body": "Boards and drop steps are rated for feet, if they are rated at all. Use the frame, or rails built to carry the vehicle."},
 ],
 "verdict": {
  "thesis": "Count the doors and look for factory rock rails first. Then buy Rough Country's BA2 board for a 4-door daily driver, its dual-motor power boards if you want the step to fold away, and Westin's Outlaw Drop or Rough Country's oval nerf steps for the 2-door.",
  "body": "The Bronco's step market splits by door count, then by what is already under the doors. A Black Diamond, Badlands or First Edition has factory rock rails, per Ford, and most steps on this page go on in place of them. If the Bronco sees rocks, keep the rails and add a small rail-mounted step. If it carries passengers on roads, the BA2 is the best-documented fixed board for the 4-door, Go Rhino's D1 has the longest warranty once the seller confirms the door count, and Rough Country's power boards are the only pick with a published 660 lb per-side rating. Two-door owners should start with Westin's Outlaw Drop for the lowest step, or Rough Country's oval bar on a budget if the rocker is bare.\n\nA step also makes the roof easier to reach, which matters once the Bronco carries a roof rack, and trail builds usually add an LED light bar at the same stage. Whatever you choose, buy by the door count in the title and the maker's fit line for your year. Raptor and Sasquatch owners should get the part number confirmed in writing, because no maker page we read names either one.",
 },
 "sources": [
  ["Ford Bronco Steps & Running Boards: product list and prices (Rough Country)", "https://www.roughcountry.com/steps-and-running-boards/ford/bronco"],
  ["BA2 Running Boards, 4-Door, 41007 (Rough Country)", "https://www.roughcountry.com/product/ba2-running-boards-41007"],
  ["Power Running Boards, Dual Electric Motor, 4-Door, PSR51330 (Rough Country)", "https://www.roughcountry.com/product/electric-running-boards-psr51330"],
  ["Oval Nerf Steps, 2-Door, 21012 (Rough Country)", "https://www.roughcountry.com/product/ford-bronco-oval-steps-21012"],
  ["Outlaw Drop Nerf Step Bars: specs and Bronco applications (Westin Automotive)", "https://www.westinautomotive.com/outlaw-drop-nerf-step-bars"],
  ["Go Rhino Dominator D1 Side Steps D14131T (RealTruck)", "https://realtruck.com/p/go-rhino-dominator-d1-side-steps/grh-d14131t/"],
  ["Bronco 2021-2026 4-Door Rock Rails, OE rails and trims (Ford accessories)", "https://www.ford.com/product/rock-rails-4-door-p2880480058"],
  ["Rock rails standard on Badlands, Black Diamond and First Edition? (Bronco6G thread)", "https://www.bronco6g.com/forum/threads/are-the-rock-rails-standard-and-included-with-the-badlands-black-diamond-and-first-edition.10650/"],
  ["Ford Bronco (sixth generation): wheelbases, trims, Raptor (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_Bronco_(sixth_generation)"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note)
FITS = [
 ("B0C31HSQYX","Rough Country BA2 Running Boards for Ford Bronco (2021-2025) 4-Door, Wide 5 in Non-Slip Side Steps","Rough Country","$350–$400",{"doors":"4-door"},"No-drill; 5-year limited warranty; maker lists 2021-2026, confirm 2026 with seller."),
 ("B0BWSHMVMT","Rough Country Power Running Boards with LED Step Lights for Ford Bronco, 4-Door (2021-2025), Retractable Electric Side Steps w/Dual Motors","Rough Country","$1,300–$1,450",{"doors":"4-door"},"660 lb per side (maker); factory rock sliders must be removed; confirm 2026 with seller."),
 ("B0CLPJHSSN","Westin 20-14185 Outlaw Drop Nerf Step Bars, 2021-2024 Ford Bronco 2-Door (Excl. Bronco Sport)","Westin","$490–$530",{"doors":"2-door"},"2-door only; Westin lists 2021-2026, confirm 2025-2026 with seller."),
 ("B0B57FF3SD","Go Rhino D14131T Dominator Xtreme D1 Side Steps with Rocker Panel Mounting Bracket Kit, Ford 21-24 Bronco","Go Rhino","$550–$600",{},"Title names no door count; confirm doors and 2025-2026 with seller. OE rock rails removed if equipped."),
 ("B0B5FDGKT9","Rough Country Oval Nerf Steps for Ford Bronco 2-Door (2021-2025), OEM Style Rails with 4.5 in Side Steps","Rough Country","$200–$240",{"doors":"2-door"},"2-door only; does not fit models with factory rock sliders (maker); confirm 2026."),
 ("B0B6CR4C48","Rough Country Rock Sliders for Ford Bronco (2021-2024), Fits 4-Door, Pair","Rough Country","Check listing",{"doors":"4-door"},"Title-only data; confirm mounting, material and 2025-2026 fit on the listing."),
 ("B0BL3FT89T","Hooke Road Bronco Running Boards Drop Down 5.4 in Side Steps, Ford Bronco 2021 2022 2023 4-Door, Steel Rock Slider Rails","Hooke Road","Check listing",{"doors":"4-door"},"Title names 2021-2023 only; confirm 2024+ fit, mounting and warranty with seller."),
 ("B0GXCLXDTM","Rough Country HT-Series Power Running Boards for Ford Bronco (2021-2026) 4 Door","Rough Country","$1,000–$1,100",{"doors":"4-door"},"Lower-priced power board; confirm rock rail removal and warranty on the listing."),
 ("B09SM3FWNF","Rough Country SRX2 Adjustable Aluminum Steps for Ford Bronco (2021-2025) 4-Door, Modular Running Boards with Slide-Adjust Steps","Rough Country","$450–$500",{"doors":"4-door"},"Aluminum rail with adjustable steps; confirm 2026 with seller."),
 ("B0D98YMPJ4","Rough Country SRL2 Aluminum Side Steps for Ford Bronco (2021-2025) 4-Door, Modular Running Boards with Adjustable Step Placement","Rough Country","$450–$500",{"doors":"4-door"},"Aluminum rail with adjustable steps; confirm 2026 with seller."),
 ("B0BMFNB35T","ROADER Bronco Side Steps, Ford Bronco 2021 2022 2023 2024 2/4 Door, fit Ford Bronco with Rock Rail, 2PCS","ROADER","Check listing",{},"Add-on steps for Broncos with factory rock rails; confirm your trim, door count and year with seller."),
 ("B0DMVRRF6R","TAC Running Boards, 2021-2025 Ford Bronco 2 Door, Rocker Steps / Rocker Slider, Fine Texture Black (2pcs)","TAC","Check listing",{"doors":"2-door"},"Budget 2-door option; confirm mounting, rating and 2026 fit with seller."),
 ("B09Q64VKB5","CLAMBER Running Boards for Ford Bronco 2021-2026 2 Door (Not for Bronco Sport), 5.2 in Textured Black Nerf Bars","CLAMBER","Check listing",{"doors":"2-door"},"Budget 2-door option; confirm rating and warranty with seller."),
 ("B0B9MLJW3R","Broaddict 4 Door Running Boards, Ford Bronco 2021-2025 2026, Off-Road Aluminum Side Steps, 350 LBS Capacity","Broaddict","Check listing",{"doors":"4-door"},"Budget aluminum board; 350 lb per the title; confirm mounting with seller."),
]
