"""Long-form article — Best Floor Mats & Liners for 2020–2026 Ford Explorer (6th gen, U625).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("ford", "explorer", "2020-present", "floor-mats")

TITLE = "Best Floor Liners for 2020–2026 Ford Explorer: 6 Three-Row Sets for 6- and 7-Passenger"
META = ("Six 6th-gen Explorer floor liner sets from Husky, 3W, LASFIT, DrCarNow and KUST, matched to 6- vs "
        "7-passenger seating, the second-row console and the Hybrid.")

FAQ = [
 ("How do I tell a 6-passenger from a 7-passenger Explorer?",
  "Look at the second row. Six-passenger Explorers have two captain's chairs, sometimes with a center console between them. Seven-passenger Explorers have a three-person bench. The second-row floor liner is shaped differently for each. 3W, LASFIT and DrCarNow on this page are 6-passenger only."),
 ("Do 2011–2019 Explorer liners fit the 2020+ Explorer?",
  "No. The 2020 Explorer moved to a new rear-wheel-drive-based platform with a new cabin floor. Husky's catalog shows the split: 13761 front liners for 2015–2019 and 99321 for 2020–2026. Buy 2020+ listings."),
 ("Do these liners fit the Explorer Hybrid, ST and Timberline?",
  "The Hybrid (2020–2022), ST and Timberline share the 6th-gen floor. 3W's listing names the hybrid; Husky's 99321 is listed for the 2020–2026 Explorer without trim exclusions. Confirm seating layout, which matters more than trim."),
 ("What does Husky's 6-piece Explorer set include?",
  "Front, second and third row liners plus a cargo liner, for 2020–2025 Explorers with a second-row bench or buckets with a center console, according to its title. It's the most complete Husky option for this vehicle."),
 ("Does the 2025 refresh change the liners?",
  "The 2025 Explorer got a refreshed interior with a new dash and console, but most listings here run through 2025 or 2026, which suggests the floor carried over. Confirm with the seller for 2025 and 2026 trucks, especially for the second-row piece around the console."),
 ("Do I need a third-row liner?",
  "If the third row gets used, yes. It's carpeted and kids climb over it. Husky sells a third-row liner and cargo mat bundle that folds with the third row, and 3W and LASFIT include the third row in their 3-row sets."),
 ("Can I use Explorer liners in a Lincoln Aviator?",
  "No. The Aviator shares the platform, but its interior and floor details differ. Buy liners that name the Aviator."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto Ford's retention posts and clear of the pedals at full travel. Remove the factory mat first and heel-test it toward the pedals."),
 ("How do I clean three-row liners?",
  "Pull each row, shake out crumbs, rinse and scrub with mild soap. Dry before reinstalling. Skip silicone protectants."),
 ("Is KUST's rubber set a good budget pick?",
  "For front and second row only, it's the cheapest here. Rubber is heavy, grips well and stays flexible in the cold. The walls are lower than a molded liner, and the listing asks you to check 6- vs 7-passenger. It doesn't cover the third row."),
 ("Should I buy a cargo liner that folds with the third row?",
  "If you fold the third row often, yes. Husky's third-row liner and cargo mat bundle is designed to fold up and down with the seats, so the cargo floor and the back of the folded third row stay covered in either position. A flat cargo mat only protects the floor behind the upright third row, which leaves the seatbacks exposed when they're folded for luggage or sports gear."),
 ("Do Explorer liners fit the Police Interceptor Utility?",
  "The Police Interceptor Utility is based on the 6th-gen Explorer but uses a fleet-specific interior, often with vinyl flooring and different equipment. Retail liners aren't listed for it. If you own a retired Interceptor, check with the liner maker, since the floor covering and seating can differ from a retail Explorer."),
]

ARTICLE = {
 "dek": "Six liner sets listed for the 6th-generation Explorer, from Husky's made-in-USA WeatherBeater to $80 rubber. The second row decides fit: captain's chairs or bench, with or without a console between the chairs.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2020–2026 Explorer (seating, console, hybrid, rows covered), on published maker specs (material, origin, warranty) and on coverage in listing photos. Husky and LASFIT claims come from their own sites, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Second row decides fit.** Captain's chairs (6-passenger) or bench (7-passenger); console or open walkway.",
  "**New platform in 2020.** 2011–2019 liners don't fit.",
  "**Husky covers every row.** 99321 front and second; 6-piece set adds third row and cargo.",
  "**3W names the Hybrid.** Useful for 2020–2022 Hybrid owners.",
  "**Budget rubber skips the third row.** KUST is front and second only.",
 ],
 "top_picks": [
  {"asin": "B07ZG9HW9G", "role": "Best overall", "why": "Husky WeatherBeater 99321 front and 2nd row, 2020–2026, made in USA"},
  {"asin": "B0DLH8MJPC", "role": "Most complete", "why": "Husky 6-piece: front, 2nd, 3rd row and cargo"},
  {"asin": "B09MQGKWHR", "role": "Best 3-row TPE", "why": "3W 3-row liners, 6-passenger incl. hybrid"},
  {"asin": "B0CC4YY6XR", "role": "Best recycled TPE", "why": "LASFIT 3-row, 6-passenger"},
  {"asin": "B08LZH21RT", "role": "Best budget", "why": "KUST rubber front and 2nd row"},
 ],
 "fit_table": {
  "caption": "2020–2026 Explorer: second-row layouts",
  "head": ["Layout", "Seats", "Liner note"],
  "rows": [
   ["Captain's chairs, open walkway", "6", "3W, LASFIT, DrCarNow list 6-passenger; confirm walkway coverage"],
   ["Captain's chairs with console", "6", "Husky 6-piece lists buckets with console"],
   ["Second-row bench", "7", "Husky 6-piece and 99321; KUST asks you to check"],
   ["Hybrid (2020–2022)", "6 or 7", "3W names hybrid"],
  ],
 },
 "look_for": [
  {"h": "Captain's chairs or bench",
   "body": "The 6th-gen Explorer offers a second-row bench for seven passengers or two captain's chairs for six. The captain's chair layout can have an open walkway to the third row or a center console between the chairs. Each changes the second-row floor liner. The 3W, LASFIT and DrCarNow sets here are 6-passenger only. Husky's 6-piece kit lists a second-row bench or buckets with a center console. KUST asks you to check the layout. Look at your second row before comparing prices; it's the one detail that causes most returns on this vehicle."},
  {"h": "How many rows to cover",
   "body": "A three-row SUV has four zones: front, second row, third row and cargo. Husky's 99321 covers the front and second row in four pieces. Its 6-piece kit adds the third row and cargo. Husky also sells a third-row liner and cargo mat bundle that folds up and down with the third row. 3W and LASFIT sell 3-row sets; KUST covers only front and second row. If the third row rarely gets used, a two-row set plus a cargo liner may be all you need."},
  {"h": "Generation and refresh",
   "body": "The 2020 Explorer moved to a new rear-drive-based platform, so earlier liners don't fit. Within the generation, the 2025 refresh changed the dash and console, but most listings here still run through 2025 or 2026. If you have a 2025 or 2026, confirm the second-row piece with the seller, since console changes can affect the front-to-rear transition."},
  {"h": "Warranty and material",
   "body": "Husky says WeatherBeater is laser-measured, designed and made in the USA from ProGard, anchored by StayPut nibs and covered by a lifetime warranty against cracks and breaks. LASFIT uses GRS-certified recycled TPE rated from −13°F to 167°F. 3W's maker is a TPE mat manufacturer in Taizhou, China. DrCarNow and KUST don't publish comparable terms. In a family SUV kept for years, the warranty is a reasonable tiebreaker."},
  {"h": "Retention and pedal clearance",
   "body": "Ford uses retention posts in the driver footwell, and an Explorer-specific liner has holes for them. Seat the driver liner on the posts, heel-test it toward the pedals and press the brake and accelerator to the floor. Never stack a liner on the factory mat."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2020+ in the title", "2011–2019 listings"],
   ["Seating", "6- or 7-passenger named", "Kits that don't state seating"],
   ["Console", "Console or walkway named for 6-passenger", "Assuming one 2nd-row liner fits both"],
   ["Rows", "The zones you use", "Paying for rows you don't need"],
   ["Retention", "Hook holes for Ford's posts", "Loose mats"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2020–2026 Explorer",
  "head": ["Type", "Example", "Coverage", "Walls", "Price band", "Best for"],
  "rows": [
   ["USA-made molded liner", "Husky 99321", "Front + 2nd", "High", "$150–$210", "Families keeping the car"],
   ["USA-made full kit", "Husky 6-piece", "Front, 2nd, 3rd, cargo", "High", "$280–$380", "Maximum coverage"],
   ["3-row TPE", "3W, LASFIT, DrCarNow", "Front, 2nd, 3rd", "Medium-high", "$110–$190", "6-passenger value"],
   ["Rubber mats", "KUST", "Front + 2nd", "Low-medium", "$70–$110", "Budget"],
  ],
 },
 "picks": [
  {"asin": "B07ZG9HW9G", "role": "Best overall", "price": "$150–$210",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs", "Front and 2nd row, 4 pieces", "Lists 2020–2026"],
   "cons": ["Third row and cargo sold separately", "Firm feel", "Confirm second-row layout with Husky"],
   "body": "Husky's WeatherBeater 99321 is a four-piece front and second-row set listed for the 2020–2026 Explorer. Husky says WeatherBeater is laser-measured using vehicle-specific data, designed and made in the USA from ProGard and anchored by StayPut nibs, with a lifetime warranty against cracks and breaks.\n\nThe front and second row are where most of the mud and snow lands in a family Explorer, so this set covers the zones that matter most. Its long year range, through the 2025 refresh to 2026, is useful for newer vehicles.\n\nThe short title doesn't specify second-row layout, so run your Explorer through Husky's fit tool before ordering. Add Husky's third-row and cargo bundle if the back gets regular use, or step up to the 6-piece kit. The firm material takes a warm day to relax after shipping.",
   "who": "Explorer owners who want the best-documented front and second-row liners.",
   "specs": [["Part #", "Husky 99321"], ["Pieces", "4"], ["Fits", "2020–2026 Explorer"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B0DLH8MJPC", "role": "Most complete", "price": "$280–$380",
   "pros": ["Front, 2nd and 3rd row plus cargo", "Lists bench or buckets with console", "Made in the USA", "Lifetime warranty against cracks and breaks", "One maker across the whole cabin"],
   "cons": ["Most expensive here", "Title covers 2020–2025; confirm 2026", "Open-walkway captain's chairs: confirm"],
   "body": "Husky's 6-piece WeatherBeater kit covers the front, second and third rows plus the cargo area of 2020–2025 Explorers with a second-row bench or buckets with a center console. It's the most complete option here and the only one that pairs every zone with a lifetime crack warranty.\n\nFor a family that uses all three rows and the cargo area, buying one kit keeps the fit and warranty consistent across the cabin. It costs the most, but less than buying Husky's pieces separately.\n\nIf your 6-passenger Explorer has an open walkway between the captain's chairs rather than a console, confirm the second-row piece with Husky. For a 2026, check the fit tool. Husky's firm WeatherBeater material holds the tall walls upright in every row, which matters most in the front footwells where snowmelt collects. The cargo liner in the kit also protects the load floor when you slide in heavy items like a cooler or a stroller.",
   "who": "Families who want every zone covered by one US-made brand.",
   "specs": [["Pieces", "6"], ["Covers", "Front, 2nd, 3rd, cargo"], ["Fits", "2020–2025 Explorer, 2nd-row bench or buckets with console"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"], ["Price band", "$280–$380"]]},
  {"asin": "B09MQGKWHR", "role": "Best 3-row TPE", "price": "$150–$190",
   "pros": ["3-row liner set", "Lists 2020–2026 6-passenger", "Names the hybrid", "TPE from a TPE-mat specialist", "Covers the newest year"],
   "cons": ["6-passenger only", "No published warranty", "Cargo not included"],
   "body": "3W's TPE 3-row liners are listed for 2020–2026 Explorer 6-passenger models, including the hybrid. That hybrid mention is useful for 2020–2022 Explorer Hybrid owners, since few listings address it directly.\n\n3W's maker, Zhejiang Zhenya in Taizhou, China, specializes in TPE mats but doesn't publish warranty terms. The value is three rows covered for roughly half the price of Husky's 6-piece kit.\n\nConfirm whether your captain's chairs have a console or an open walkway, and check the listing photos for the second-row piece shape before ordering. The third-row piece matters more than it looks: kids climbing into the back step on the third-row floor with every entry, and that carpet is hard to reach for cleaning. A molded TPE piece there comes out in one pull. Pair the set with a cargo liner if you carry sports gear or a stroller.",
   "who": "6-passenger owners, including Hybrid, who want three rows covered.",
   "specs": [["Rows", "3"], ["Fits", "2020–2026 Explorer 6-passenger incl. hybrid"], ["Material", "TPE"], ["Maker", "Zhejiang Zhenya (3W)"], ["Price band", "$150–$190"]]},
  {"asin": "B0CC4YY6XR", "role": "Best recycled TPE", "price": "$140–$180",
   "pros": ["GRS-certified recycled TPE", "Rated −13°F to 167°F", "3-row, 4-piece set", "3D laser-scanned", "45-day returns on LASFIT's store"],
   "cons": ["6-passenger only", "Title covers 2020–2025", "Warranty length not stated"],
   "body": "LASFIT's 4-piece TPE set covers three rows of 2020–2025 Explorer 6-passenger models. LASFIT says its liners are 3D laser-scanned and made from GRS-certified recycled TPE, rated from −13°F to 167°F.\n\nThe cold rating and return window make it a strong alternative to 3W for families in snow country. The softer surface grips kids' shoes and folds for cleaning.\n\nIt doesn't name the hybrid or 2026, so confirm those with the seller if they apply. For a gas 6-passenger Explorer through 2025, it's a well-documented middle option. LASFIT's recycled TPE is also free of PVC and phthalates, which some families care about in a car that carries young children. If you drive a 7-passenger Explorer with the bench, this set isn't for you; look at Husky's 99321 or 6-piece kit instead.",
   "who": "6-passenger families in cold climates.",
   "specs": [["Rows", "3 (4 pieces)"], ["Fits", "2020–2025 Explorer 6-passenger"], ["Material", "Recycled TPE (GRS)"], ["Temp range", "−13°F to 167°F"], ["Returns", "45 days (LASFIT store)"]]},
  {"asin": "B0BHZB7VWP", "role": "Budget 3-row", "price": "$110–$150",
   "pros": ["3-row set", "Lists 2020–2026 6-passenger with bucket seats", "Low price for three rows", "All-weather material", "Covers the newest year"],
   "cons": ["6-passenger only", "Little maker documentation", "No published warranty"],
   "body": "DrCarNow's 3-row all-weather mats are listed for 2020–2026 Explorer 6-passenger with bucket seats. It's the cheapest three-row option here.\n\nDocumentation is thin, so warranty and material grade are unknowns. For a family that wants the third row covered without paying for a premium brand, it's a reasonable choice.\n\nAs with any 6-passenger set, confirm your second-row console or walkway before ordering. Check the listing photos for the driver-side retention holes and for how the second-row pieces handle the space between the captain's chairs. A liner that covers the walkway saves the carpet where third-row passengers step through. If the walkway piece is missing, add a small mat there.",
   "who": "6-passenger owners on a budget.",
   "specs": [["Rows", "3"], ["Fits", "2020–2026 Explorer 6-passenger, bucket seats"], ["Material", "All-weather (per listing)"], ["Price band", "$110–$150"]]},
  {"asin": "B08LZH21RT", "role": "Best budget", "price": "$70–$110",
   "pros": ["Cheapest here", "Heavy rubber grips and stays put", "Flexible in the cold", "Lists 2020–2026", "Front and 2nd row"],
   "cons": ["No third row", "Lower edges than molded liners", "Check 6- vs 7-passenger"],
   "body": "KUST's rubber liners cover the front and second row of the 2020–2026 Explorer. The listing asks you to check 6- vs 7-passenger, which is the right question.\n\nRubber is heavy, grippy and stays flexible in the cold, so it's a practical choice for a commuter Explorer. The edges are lower than molded TPE or WeatherBeater, so empty them after heavy snow.\n\nIt doesn't cover the third row or cargo. For a family that rarely uses the third row, that's fine. If you later want the third row covered, you can add a third-row liner from Husky or 3W without replacing the KUST front and second-row pieces; mixing brands by row works fine as long as each piece names the 2020+ Explorer.",
   "who": "Commuters who want front and second row covered cheaply.",
   "specs": [["Rows", "Front + 2nd"], ["Fits", "2020–2026 Explorer (check seating)"], ["Material", "Rubber"], ["Walls", "Low-medium"], ["Price band", "$70–$110"]]},
 ],
 "install": [
  "Check your second row: captain's chairs (console or walkway) or bench.",
  "Remove the factory mats from every row and vacuum.",
  "Hook the driver liner onto the retention posts and heel-test it toward the pedals.",
  "Fit the passenger and second-row liners; slide and tilt the second row to check clearance.",
  "Fit the third-row and cargo liners; fold the third row up and down.",
  "Press the pedals to the floor before driving.",
 ],
 "avoid": [
  {"h": "Wrong second-row layout", "body": "Captain's chairs and bench take different liners."},
  {"h": "2011–2019 listings", "body": "The 2020 platform has a new floor."},
  {"h": "Aviator liners", "body": "Shared platform, different floor."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy Husky's 99321 for the best-documented front and second-row liners, Husky's 6-piece for every zone, and 3W or LASFIT for three rows of TPE on a 6-passenger Explorer.",
  "body": "The 6th-gen Explorer is fit by its second row. Once you know captain's chairs or bench, and console or walkway, the choice is easy. Husky has the strongest warranty and covers every zone. 3W names the Hybrid and covers three rows, LASFIT adds a cold rating, DrCarNow is the budget three-row pick and KUST covers the front two rows for the least money.\n\nAfter the floors, most Explorer owners add a roof rack on the factory rails and a trailer hitch; check whether your Explorer has the modular steel bumper option before ordering a hitch."},
 "sources": [
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners 99321 Explorer listing", "https://www.amazon.com/dp/B07ZG9HW9G"],
  ["Husky Liners Explorer 6-piece listing", "https://www.amazon.com/dp/B0DLH8MJPC"],
  ["Husky Liners 3rd row + cargo bundle listing", "https://www.amazon.com/dp/B0C8XTPF5G"],
  ["LASFIT floor mats (LASFIT)", "https://www.lasfit.com/collections/floor-mats"],
  ["Ford Explorer, sixth generation (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_Explorer_(sixth_generation)"],
 ],
}

FITS = [
 ("B07ZG9HW9G","Husky Liners WeatherBeater 99321, 2020-2026 Ford Explorer, front & 2nd row, 4-pc","Husky Liners","$150–$210",{"rows":2},"Confirm second-row layout."),
 ("B0DLH8MJPC","Husky Liners WeatherBeater 6-pc front, 2nd, 3rd row + cargo, 2020-2025 Explorer (2nd-row bench or buckets w/ console)","Husky Liners","$280–$380",{"rows":3},"Confirm open-walkway layouts and 2026."),
 ("B09MQGKWHR","3W TPE 3-Row Floor Liners, 2020-2026 Explorer 6-passenger incl. hybrid","3W","$150–$190",{"rows":3,"seats":6},"6-passenger (2nd-row buckets)."),
 ("B0CC4YY6XR","LASFIT TPE 3-Row Floor Liners 4-piece, 2020-2025 Explorer 6-passenger","LASFIT","$140–$180",{"rows":3,"seats":6},"6-passenger only."),
 ("B0BHZB7VWP","DrCarNow 3-Row All-Weather Floor Mats, 2020-2026 Explorer 6-passenger with bucket seats","DrCarNow","$110–$150",{"rows":3,"seats":6},"6-passenger only."),
 ("B08LZH21RT","KUST Rubber Floor Liners front & 2nd row, 2020-2026 Explorer","KUST","$70–$110",{"rows":2},"Front + 2nd row; check 6- vs 7-passenger on listing."),
 ("B0C8XTPF5G","Husky Liners WeatherBeater 3rd Row Liner + Cargo Mat (22321 & 19321), 2020-2023 Explorer","Husky Liners","$130–$180",{"rows":3},"3rd row + cargo; confirm 2024+."),
]
