"""Long-form article — Best Running Boards & Side Steps for 2019–2023 Ford Ranger (4th gen US, T6), SuperCrew and SuperCab.
No invented hands-on testing: fit facts come from the listing titles recorded in FITS, specs from the Westin, RealTruck,
Ford Media Center and Wikipedia pages in sources (read 2026-10-05). Facts we could not confirm are worded as such.
"""

KEY = ("ford", "ranger", "2019-2023", "running-boards")

TITLE = "Best Running Boards & Side Steps for 2019–2023 Ford Ranger: 7 Picks, SuperCrew vs SuperCab"
META = ("Seven 2019–2023 Ranger side steps, from Westin HDX drop steps and PRO TRAXX nerf bars to AMP Research and "
        "Westin power boards, matched to SuperCrew or SuperCab.")

FAQ = [
 ("Do SuperCrew running boards fit a Ranger SuperCab?",
  "No. The SuperCrew has four full-size doors and a longer cab, and the SuperCab has small rear-hinged doors and a shorter cab. Boards and nerf bars are cut to the cab length, and the bracket spacing differs, so a SuperCrew part is too long for a SuperCab. Westin sells separate part numbers for each cab: the PRO TRAXX 5 21-54145 is the SuperCab bar, and the HDX Drop 56-14155 is listed for the SuperCrew. Count the doors before you order, then read the title for the cab name. If the title does not name a cab, ask the seller."),
 ("Which 2019–2023 Ranger trims came with factory running boards?",
  "We could not confirm this from Ford's own pages. Ford's 2019 Ranger media release names the XL, XLT and Lariat trims and the FX4 Off-Road Package, but does not mention running boards. Ford's 2021 Ranger media page lists hoop-style steps as part of the Tremor Off-Road Package. For any other trim, check the window sticker or the owner's manual, or look under the rocker panel. If your truck has factory steps, an aftermarket set replaces them and uses the same body mounting points in most cases, but confirm that with the seller."),
 ("Do 2019–2023 Ranger running boards fit the 2024 and newer Ranger?",
  "It depends on the part, so go by the maker's fit list, not by the generation. Westin's own Pro-e page lists the 29-24155 power board for the 2019–2026 Ranger SuperCrew, and RealTruck lists the Westin HDX Drop 56-14155 for the 2019–2026 Ranger. RealTruck lists the AMP Research PowerStep 76136-01A for the 2019–2023 Ranger only. Several Amazon titles on this page stop at 2023, and a few run to 2025 or 2026. For a 2024 or later truck, order only a part whose fit list names your year, and confirm with the seller in writing."),
 ("Do these steps fit the Ranger Tremor?",
  "The Tremor was sold from the 2021 model year on XLT and Lariat SuperCrew 4x4 trucks, so it takes SuperCrew-length parts. Ford's 2021 media page lists hoop-style steps as part of the Tremor package, which means an aftermarket board would replace the factory steps rather than bolt on beside them. None of the listings on this page names the Tremor. Before ordering, ask the seller whether the brackets fit a Tremor with its factory steps removed, and whether the package's suspension height changes the step height."),
 ("What is the difference between a nerf bar, a running board and a drop step?",
  "A nerf bar is a round or oval tube with step pads, such as Westin's 5 in oval PRO TRAXX 5. It sits close to the body and gives a narrower step. A running board is a flat platform, such as the APS 5 in stainless board or TAC's 4.25 in board, which gives more foot room. A drop step, such as Westin's HDX Drop, hangs a stamped step plate below the bar at each door for a lower first step. Power boards, such as the AMP Research PowerStep and Westin Pro-e, fold out when a door opens and tuck away when it closes."),
 ("Are power running boards worth it on a mid-size truck?",
  "They are the most expensive option here. RealTruck's list price for the AMP Research PowerStep 76136-01A is $1,749, and Westin's Pro-e is a power board with a 6 in step. In return you get a full-width step that disappears when the doors close, which keeps side clearance on trails and keeps the truck's lines clean. Both makers quote 300 lb per side. The trade-offs are motors and wiring that can fail, a longer install, and a price that buys three sets of fixed steps. On a Ranger that stays on pavement and carries older passengers, they make sense. On a trail truck, a fixed slider-style step is simpler."),
 ("Do I need to drill to install running boards on a Ranger?",
  "Usually not. RealTruck says the Westin HDX Drop 56-14155 needs zero trimming, cutting, drilling or other modifications, and lists the PRO TRAXX 5 21-54145 as a no-drill install. Westin's Pro-e page says no-drill DIY install. The AMP Research PowerStep is the exception: RealTruck says drilling is required on select applications and that the board needs trimming on SuperCab models. Budget listings from TAC, APS and others usually say no drilling, but check the listing and the included bracket kit for your cab before you start."),
 ("How much weight can Ranger running boards hold?",
  "Only two makers on this page publish a figure. RealTruck quotes 300 lb per door for the AMP Research PowerStep, and Westin's Pro-e page quotes 300 lb per side. Westin does not state a rating for the HDX Drop or PRO TRAXX 5 on the pages we read, and the TAC and APS listings we found do not publish one in their titles. A rating is per step or per side, not for the whole truck, and it assumes a person stepping, not a jack or a tie-down point. If the listing gives no number, ask the seller before you buy."),
 ("Will running boards reduce the Ranger's ground clearance?",
  "Yes, a little. Any fixed step hangs below the rocker panel, and drop steps hang lowest. On a 2019–2023 Ranger FX4 or Tremor that sees rocks, that is the first thing to catch. A slider-style step such as TAC's Sidewinder is built to take a hit, and a power board retracts flush when the doors are closed, so it keeps the stock clearance while you drive. Approach and departure angles are set by the bumpers and do not change with a board; breakover and side clearance do."),
 ("Which finish lasts longest in a salt state?",
  "Stainless steel resists rust without relying on a coating, which is why the APS 5 in board's stainless construction matters at its price. Westin's HDX Drop and PRO TRAXX 5 use steel under a textured or gloss black powder coat, and the HDX Drop's stamped step areas are made for traction. Aluminum, used on the AMP Research PowerStep and Westin Pro-e, does not rust but can corrode where salt sits. Whatever you buy, rinse the brackets after winter drives and touch up chips, because the brackets rust first."),
]

ARTICLE = {
 "dek": "Seven side steps listed for the 2019–2023 Ranger, from Westin's HDX drop steps and PRO TRAXX nerf bars to AMP Research and Westin power boards, plus budget flat boards and a slider-style step from TAC and APS. The one fit rule that matters: the board must be cut for your cab, SuperCrew or SuperCab.",
 "author": "jake-morrison",
 "reviewed": "2026-10-05",
 "method": "We did not install these steps ourselves. We ranked them on the fitment each Amazon listing title states for the 2019–2023 Ranger and its cab, on published maker and retailer specs (step width, material, finish, warranty, weight rating, drilling) from Westin's and RealTruck's product pages, and on listing details. Vehicle facts come from Ford's 2019 and 2021 Ranger media pages and Wikipedia's Ford Ranger (T6) page, all read in October 2026. Where a maker publishes no figure, we say so. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Cab decides the part.** The SuperCrew has four full doors and the 5 ft bed; the SuperCab has small rear-hinged doors and the 6 ft bed. Steps are cut to the cab, not the bed.",
  "**Westin is the best-documented brand here.** RealTruck lists the HDX Drop 56-14155 and PRO TRAXX 5 21-54145 as no-drill installs with a 3-year warranty.",
  "**Two power boards name this truck.** AMP Research's PowerStep 76136-01A and Westin's Pro-e 29-24155 both quote 300 lb per side.",
  "**Factory steps are a Tremor thing.** Ford's 2021 media page lists hoop-style steps in the Tremor package; we could not confirm factory boards on any other trim.",
  "**Check the year range.** Some titles stop at 2022 or 2023; some makers list the same part through 2026. Buy by the maker's fit list.",
 ],
 "top_picks": [
  {"asin": "B07QJKN563", "role": "Best overall", "why": "Westin HDX Drop 56-14155, one-piece steel, stamped step plates, no drilling, 3-year warranty"},
  {"asin": "B084L5K547", "role": "Best power step", "why": "AMP Research PowerStep, aluminum, 300 lb per door, LED lights, 5-year warranty"},
  {"asin": "B07QF88CZM", "role": "Best for SuperCab", "why": "Westin PRO TRAXX 5 21-54145, 5 in oval tube cut for the SuperCab, no-drill"},
  {"asin": "B097CNPK26", "role": "Best slider-style step", "why": "TAC Sidewinder 4 in drop step with rocker slider design, SuperCrew"},
  {"asin": "B07VNKLDNX", "role": "Best stainless board", "why": "APS 5 in stainless steel running boards for the SuperCrew"},
 ],
 "fit_table": {
  "caption": "2019–2023 Ranger: fit checklist for side steps",
  "head": ["Variable", "Versions", "What to buy"],
  "rows": [
   ["Cab", "SuperCrew (four full doors, 5 ft bed) or SuperCab (rear-hinged doors, 6 ft bed)", "A part whose title names your cab"],
   ["Trim", "XL, XLT, Lariat", "Same body; steps fit by cab and year"],
   ["Packages", "FX4 (all 4x4 models), Tremor (2021+, XLT/Lariat SuperCrew 4x4)", "Tremor has factory hoop-style steps; confirm removal and fit"],
   ["Factory steps", "Unconfirmed by trim", "Check the window sticker or look under the rocker"],
   ["2024+ Ranger", "New generation", "Buy only a part whose fit list names 2024 or later"],
  ],
 },
 "look_for": [
  {"h": "SuperCrew or SuperCab: the one fit rule",
   "body": "Wikipedia's Ranger (T6) page states that the North American truck is sold in four-door SuperCab and four-door SuperCrew configurations. The SuperCrew's rear doors are full size; the SuperCab's are small and rear-hinged, so its cab is shorter. Running boards and nerf bars are built to the cab length and bracket spacing, which is why Westin sells the PRO TRAXX 5 as 21-54145 for the SuperCab and the HDX Drop as 56-14155 for the SuperCrew. Every pick on this page names a cab in its title except the AMP Research PowerStep, which names both, and RealTruck says that board needs trimming on SuperCab models. Count the doors, then read the title. A listing that only says Ranger is a guess until the seller confirms the cab."},
  {"h": "Step shape: tube, board, drop step or power",
   "body": "The Ranger sits lower than a full-size truck, so a step is more about convenience than reach. A 5 in oval tube such as Westin's PRO TRAXX 5 gives a sporty look and a narrower step. A flat board such as the APS 5 in stainless or TAC's 4.25 in gives more foot room. Westin's HDX Drop hangs a stamped step plate below the bar at each door for a lower first step, which helps kids and older passengers. Power boards from AMP Research and Westin deploy when a door opens and retract flush when it closes, so there is nothing hanging below the rocker on the move. Pick the shape by who rides in the truck and where it goes."},
  {"h": "Material, finish and warranty",
   "body": "RealTruck describes the Westin HDX Drop 56-14155 as fully welded one-piece steel with a textured black powder coat and a 3-year warranty against manufacturer defects, and the PRO TRAXX 5 21-54145 as heavy-duty steel with a gloss black powder coat and the same 3-year term. Westin's own HDX Drop page adds that stainless models carry 5 years. The AMP Research PowerStep is corrosion-resistant aluminum with stainless hinge pins and a 5-year limited warranty, per RealTruck, and Westin's Pro-e is aluminum with a 5-year warranty and a limited lifetime warranty on its LED lights. The APS board's title says stainless steel; the TAC listings say textured black. Budget brands rarely publish warranty terms, so ask."},
  {"h": "Drilling, brackets and install time",
   "body": "RealTruck says the Westin HDX Drop needs zero trimming, cutting, drilling or other modifications and takes about an hour with hand tools. It lists the PRO TRAXX 5 as a no-drill install, and Westin's Pro-e page says no-drill DIY install with vehicle-specific brackets. The AMP Research PowerStep is the exception: RealTruck recommends professional installation, says drilling is required on select applications, and notes the board must be trimmed on a SuperCab. Budget steps from TAC and APS normally bolt to the same body points; check the listing for the bracket kit and whether it names your cab. Plan on a helper to hold the bar while you start the bolts."},
  {"h": "Clearance on FX4 and Tremor trucks",
   "body": "Wikipedia lists the FX4 Off-Road Package for all 4x4 models, and the Tremor for 2021 and later XLT and Lariat SuperCrew 4x4 trucks. Both are trucks that leave pavement, and a fixed step is the lowest part of the body side. Drop steps hang lowest; a slider-style step like TAC's Sidewinder is shaped to take a rock hit; a power board retracts flush so the stock clearance is there while you drive. Ford's 2021 media page lists hoop-style steps in the Tremor package, so a Tremor owner is replacing a factory step, not adding one. Ask the seller whether the brackets fit with the factory steps removed."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fit", "SuperCrew or SuperCab named, year inside 2019–2023", "\"Fits Ranger\" with no cab"],
   ["Mounting", "Bolt-on to body points, no drilling, bracket kit included", "Kits that need drilling to fit"],
   ["Material", "Stainless, aluminum, or steel under powder coat", "Bare or thin paint in salt states"],
   ["Step surface", "Stamped or textured pads, wide step", "Smooth tube with no pads"],
   ["Weight rating", "A published per-side figure (300 lb on the power boards)", "\"Heavy duty\" with no number"],
   ["Warranty", "Stated term (3 years Westin steel, 5 years AMP and Pro-e)", "No terms stated"],
  ],
 },
 "types_table": {
  "caption": "Side step types for the 2019–2023 Ranger",
  "head": ["Type", "Example", "Step", "Cab", "Price band", "Best for"],
  "rows": [
   ["Drop step bar", "Westin HDX Drop 56-14155", "Stamped step plate at each door", "SuperCrew", "$600–$700", "Lower first step, all-round"],
   ["Power board", "AMP Research PowerStep 76136-01A", "Full-width aluminum, 300 lb per door", "SuperCrew / SuperCab (trim)", "$1,500–$1,800", "Clearance plus an easy step"],
   ["Power board", "Westin Pro-e 29-24155", "6 in aluminum, 300 lb per side", "SuperCrew", "Check listing", "No-drill power step"],
   ["Oval nerf bar", "Westin PRO TRAXX 5 21-54145", "5 in oval tube", "SuperCab", "$500–$600", "SuperCab owners"],
   ["Slider-style drop step", "TAC Sidewinder", "4 in drop", "SuperCrew", "Check listing", "FX4 and trail trucks"],
   ["Stainless flat board", "APS 5 in", "5 in flat board", "SuperCrew", "Check listing", "Salt states on a budget"],
   ["Budget flat board", "TAC 4.25 in", "4.25 in board", "SuperCrew", "Check listing", "Lowest price"],
  ],
 },
 "picks": [
  {"asin": "B07QJKN563", "role": "Best overall", "price": "$600–$700",
   "pros": ["Fully welded one-piece steel construction (RealTruck)", "Stamped step plate at each door for a lower, grippier step", "Zero trimming, cutting or drilling (RealTruck)", "About 1 hour install with hand tools (RealTruck)", "3-year warranty against manufacturer defects"],
   "cons": ["Drop steps hang lowest on the body side", "Title names the SuperCrew only", "No published weight rating on the pages we read"],
   "body": "Westin's HDX Drop is the step we would start with on a SuperCrew. The 56-14155 listing names the 2019–2025 Ranger SuperCrew in textured black, and RealTruck lists the same part for the 2019–2026 Ranger. RealTruck describes it as fully welded one-piece steel with a corrosion-resistant textured black powder coat, a notched bar design and a heavy-duty step plate at each door. Westin's own HDX Drop page says the die-stamped step areas give over 2 more inches of toe and heel room than competitors, and that the bar protects the rocker panel.\n\nThe drop plate is the point. The Ranger is not a tall truck, but a step that sits a few inches below the rocker makes the climb easier for kids and older passengers without the price of a power board. RealTruck says the install needs zero trimming, cutting, drilling or other modifications and takes about an hour with conventional hand tools, and RealTruck lists it at $654.99 with Westin's 3-year warranty against manufacturer defects.\n\nTwo cautions. The drop plates are the lowest part of the body side, so on an FX4 that sees rocks, look at the TAC Sidewinder instead. And Westin does not publish a weight rating for this bar on the pages we read, so ask if that matters to you. The title stops at 2025 for this listing; RealTruck's fit line runs to 2026, so a 2024 or later owner should confirm with the seller.",
   "who": "SuperCrew owners who want a lower step with a brand-name warranty and a no-drill install.",
   "specs": [["Part #", "Westin 56-14155"], ["Type", "Drop step bar"], ["Fits", "2019–2025 Ranger SuperCrew (title); 2019–2026 (RealTruck)"], ["Material", "Fully welded one-piece steel"], ["Finish", "Textured black powder coat"], ["Install", "About 1 hour, no drilling (RealTruck)"], ["Warranty", "3 years (RealTruck)"], ["Price", "$654.99 (RealTruck)"]]},
  {"asin": "B084L5K547", "role": "Best power step", "price": "$1,500–$1,800",
   "pros": ["Deploys when a door opens and retracts out of sight (RealTruck)", "Supports up to 300 lb per door", "Corrosion-resistant aluminum with stainless hinge pins and hardware", "Integrated LED step lighting", "5-year limited warranty"],
   "cons": ["RealTruck list price is $1,749, the highest here", "Drilling required on select applications; board needs trimming on SuperCab models", "Amazon title names 2019 only; RealTruck lists 2019–2023"],
   "body": "AMP Research's PowerStep is the power running board that other power boards get compared to, and the 76136-01A is the Ranger part. The Amazon listing title names the 2019 Ford Ranger SuperCrew and SuperCab; RealTruck's fit line reads 2019–2023 Ford Ranger and adds that trimming of the board is required on SuperCab models. RealTruck describes it as corrosion-resistant aluminum with an advanced powder coat finish, stainless steel hinge pins and hardware, support for up to 300 lb per door, and integrated LED lighting that lights the step in the dark.\n\nThe board deploys when a door opens and retracts tight and out of sight when it closes. On a Ranger that is the best of both: a full-width step when you need it and stock side clearance when you are moving. AMP's plug-n-play design connects through the truck's wiring without improvised attachments, and RealTruck says newer applications connect through an OBD II module for a factory-level install.\n\nThe costs are real. RealTruck's list price is $1,749, and the part showed as unavailable there when we read the page. RealTruck recommends professional installation, says drilling is required on select applications, and the SuperCab needs the board trimmed. The warranty is a 5-year limited term on materials and workmanship. Because the Amazon title names 2019 only, a 2020–2023 owner should confirm the part with the seller before ordering.",
   "who": "Owners who want a step that disappears when the doors close and will pay for motors and LEDs.",
   "specs": [["Part #", "AMP Research 76136-01A"], ["Type", "Power retractable board"], ["Fits", "2019 Ranger SuperCrew/SuperCab (title); 2019–2023 (RealTruck), SuperCab needs trimming"], ["Material", "Aluminum, stainless hinge pins"], ["Rating", "300 lb per door"], ["Lighting", "Integrated LED"], ["Install", "Professional recommended; drilling on select applications"], ["Warranty", "5-year limited"], ["Price", "$1,749 list (RealTruck)"]]},
  {"asin": "B07QF88CZM", "role": "Best for SuperCab", "price": "$500–$600",
   "pros": ["Cut for the SuperCab, which most listings skip", "5 in oval tube with a wide anti-slip stepping area (RealTruck)", "Heavy-duty steel under gloss black powder coat", "No-drill install (RealTruck)", "3-year warranty against manufacturer defects"],
   "cons": ["Narrower step than a flat board", "RealTruck's price, $587.99, is high for a nerf bar", "No published weight rating"],
   "body": "Most Ranger step listings are SuperCrew parts, so the SuperCab owner's shortlist is short. Westin's PRO TRAXX 5 21-54145 is listed for the 2019–2023 Ranger SuperCab in black, and RealTruck's fit line reads 2019–2023 Ford Ranger with a cab-length configuration. RealTruck describes it as a 5 in oval tube in heavy-duty steel with a gloss black powder coat, a wide stepping area for anti-slip footing, and a no-drill install, backed by Westin's 3-year warranty from the date of purchase against manufacturer defects.\n\nThe oval tube sits close to the body, which keeps the SuperCab's short cab looking clean and keeps more side clearance than a drop step. The step is narrower than a flat board, so it suits adults who want a place to put a boot rather than a platform for children. Westin also sells the 4 in version, 21-24145, for the same cab; it is in our product list.\n\nRealTruck lists the 21-54145 at $587.99, which is more than we expected for a steel nerf bar, so compare the live Amazon price before you buy. Westin does not publish a weight rating for this bar on the page we read. If you have a SuperCrew, do not order this part; Westin sells the SuperCrew bar under a different number, and the lengths differ.",
   "who": "SuperCab owners who want a brand-name no-drill nerf bar cut for their cab.",
   "specs": [["Part #", "Westin 21-54145"], ["Type", "Oval nerf bar"], ["Tube", "5 in oval"], ["Fits", "2019–2023 Ranger SuperCab"], ["Material", "Heavy-duty steel"], ["Finish", "Gloss black powder coat"], ["Install", "No drilling (RealTruck)"], ["Warranty", "3 years"], ["Price", "$587.99 (RealTruck)"]]},
  {"asin": "B0CLTPV47M", "role": "Best no-drill power board", "price": "Check listing",
   "pros": ["6 in aluminum step, 300 lb per side (Westin)", "Two IP68 waterproof motors per side", "Integrated LED step lighting with a limited lifetime LED warranty", "No-drill DIY install with vehicle-specific brackets (Westin)", "5-year warranty"],
   "cons": ["We could not read a price; check the listing", "Amazon title names 2019–2022; Westin's fit list runs to 2026", "SuperCrew only"],
   "body": "Westin's Pro-e is the other power board that names this truck. The Amazon listing title reads 29-24155 Pro-e Electric Running Boards for the 2019–2022 Ranger SuperCrew in textured black, and Westin's own Pro-e page lists 29-24155 for the 2019–2026 Ranger SuperCrew Cab Pickup. Westin describes a 6 in aluminum step with a textured black powder coat, 300 lb of weight capacity per side, two heavy-duty IP68 waterproof motors per side, and integrated LED lighting for a visible stepping surface.\n\nThe boards deploy when a door opens and retract flush against the body when it closes, which is the same clearance argument as the AMP Research board. Where the Pro-e differs is the install: Westin calls it a fast, easy, no-drill DIY install with included vehicle-specific brackets and all hardware, while RealTruck says the AMP board may need drilling and professional installation. Westin backs the Pro-e with a 5-year warranty and a limited lifetime warranty on the LED lights.\n\nWe could not read a price for this part on Westin's or RealTruck's pages, so the Amazon button is the number to go by. The Amazon title stops at 2022, so a 2023 owner should confirm with the seller, even though Westin's fit list covers the year. Like every power board, it adds motors and wiring that a fixed bar does not have, so keep the warranty paperwork.",
   "who": "SuperCrew owners who want a power step they can install themselves.",
   "specs": [["Part #", "Westin 29-24155"], ["Type", "Power retractable board"], ["Fits", "2019–2022 Ranger SuperCrew (title); 2019–2026 (Westin)"], ["Step", "6 in aluminum"], ["Rating", "300 lb per side"], ["Motors", "Two IP68 per side"], ["Lighting", "Integrated LED, limited lifetime LED warranty"], ["Install", "No-drill DIY (Westin)"], ["Warranty", "5 years"]]},
  {"asin": "B097CNPK26", "role": "Best slider-style step", "price": "Check listing",
   "pros": ["4 in drop step shaped as a rocker slider (per listing)", "Lists 2019–2025 Ranger SuperCrew", "Lower step at each door", "Fine-texture black finish per listing", "Sold as a two-piece bolt-on set"],
   "cons": ["No maker spec page we could read", "No published weight rating or warranty", "Title runs to 2025; confirm 2024+ with the seller"],
   "body": "TAC's Sidewinder is the budget answer for a Ranger that leaves pavement. The listing title names the 2019–2025 Ranger SuperCrew, a 4 in drop side step and a rocker slider design. The shape puts a step at each door while running a bar along the rocker that is meant to take a glancing hit from a rock, which a plain drop step is not built for.\n\nWe could not open a TAC spec page for this part, so everything we know comes from the listing title: 4 in drop, fine-texture black finish, two pieces, SuperCrew fit. TAC does not publish a weight rating or warranty we could check. Treat it as a step with some rocker protection, not as a frame-mounted rock slider that you can jack from. Read the listing's mounting section before ordering, since a true slider bolts to the frame and a step bolts to the body, and the two install very differently.\n\nFor the SuperCab, TAC sells the same Sidewinder style under a separate listing that names the Super Cab; it is in our product list. The title here runs to 2025, past the 2024 redesign, so a 2024 or later owner should confirm fit with the seller before ordering. For an FX4 or Tremor SuperCrew on a budget, it is the step we would check first.",
   "who": "FX4 and trail-driven SuperCrew owners who want a low step with some rocker protection on a budget.",
   "specs": [["Brand", "TAC"], ["Line", "Sidewinder"], ["Type", "Drop step, rocker slider style"], ["Drop", "4 in (per listing)"], ["Fits", "2019–2025 Ranger SuperCrew (title)"], ["Finish", "Fine-texture black (per listing)"], ["Warranty", "Confirm with seller"]]},
  {"asin": "B07VNKLDNX", "role": "Best stainless board", "price": "Check listing",
   "pros": ["Stainless steel construction per the listing title", "5 in flat board with more foot room than a tube", "Lists 2019–2023 Ranger SuperCrew, 4-door", "Matte black finish", "Stainless resists rust without a coating"],
   "cons": ["No maker spec page we could read", "No published weight rating or warranty", "Title stops at 2023"],
   "body": "APS's 5 in running boards are the stainless option on this page. The listing title names the 2019–2023 Ford Ranger SuperCrew Cab, 4-door, a 5 in matte black board and stainless steel construction. A flat 5 in board gives more foot room than Westin's oval tubes, and stainless resists rust without relying on a powder coat, which matters in a salt state where a chipped coating is the first place steel bars rust.\n\nWe could not open an APS spec page for this part, so we cannot give a weight rating, a steel grade or a warranty term; ask the seller for all three. The listing title says the boards are side steps and side bars for the SuperCrew, and it does not name the SuperCab. APS sells a separate SuperCab board that names two full-size doors and two rear-hinged doors; it is in our product list.\n\nThe title stops at 2023, which matches this generation, so there is no 2024 question here. For a Ranger that stays on pavement in a salt state, a stainless board at a budget price is the sensible middle ground between a coated steel bar and a power board. Check the listing photos for the step pad design and the bracket kit before ordering.",
   "who": "SuperCrew owners in salt states who want a flat stainless board without a brand-name price.",
   "specs": [["Brand", "APS"], ["Type", "Flat running board"], ["Width", "5 in (per listing)"], ["Material", "Stainless steel (per listing)"], ["Finish", "Matte black"], ["Fits", "2019–2023 Ranger SuperCrew"], ["Warranty", "Confirm with seller"]]},
  {"asin": "B07TK37H2D", "role": "Best budget board", "price": "Check listing",
   "pros": ["4.25 in flat board per the listing title", "Lists 2019–2023 Ranger SuperCrew", "Heavy-texture black finish", "Flat board gives more foot room than a tube", "Two-piece bolt-on kit"],
   "cons": ["No maker spec page we could read", "No published weight rating or warranty", "Coating is the only rust protection"],
   "body": "TAC's 4.25 in running boards are the budget flat board for a SuperCrew. The listing title names the 2019–2023 Ford Ranger SuperCrew, a 4.25 in board in heavy-texture black, sold as a two-piece set. The flat board gives more foot room than a 3 in or 4 in tube, and the textured finish hides scuffs.\n\nWe could not open a TAC spec page, so we cannot confirm the material, the weight rating or the warranty; the title does not state them. Ask the seller before ordering, and look at the listing photos for the bracket kit and whether the step pads are textured. TAC also sells a 4 in oval bar and a 3 in bar for the SuperCrew, and BETTER AUTOMOTIVE sells a similar 4 in oval bar, all listed for 2019–2023; they are in our product list, and the live price usually decides between them.\n\nThe coating is the only rust protection on a textured black steel bar, so rinse the brackets after salty drives and touch up chips. The title stops at 2023, which matches this generation. For a work truck or a lease that needs a step for the least money, it is the practical choice; for a truck you plan to keep, Westin's HDX Drop or the APS stainless board will hold up longer.",
   "who": "Budget buyers with a SuperCrew who want a flat board and will confirm the specs with the seller.",
   "specs": [["Brand", "TAC"], ["Type", "Flat running board"], ["Width", "4.25 in (per listing)"], ["Finish", "Heavy-texture black (per listing)"], ["Fits", "2019–2023 Ranger SuperCrew"], ["Material", "Confirm with seller"], ["Warranty", "Confirm with seller"]]},
 ],
 "install": [
  "Confirm your cab (SuperCrew or SuperCab) and model year, and check whether the truck already has factory steps, as a Tremor does. Factory steps come off first.",
  "Locate the body mounting points along the rocker and remove any plugs or covers; the instructions show which holes each bracket uses for your cab.",
  "Bolt the brackets to the mounting points hand-tight. For a power board, route the wiring and connect the harness or OBD II module before the boards go on.",
  "With a helper, set the bar or board on the brackets and start every bolt before tightening any of them.",
  "Level the step front to rear and side to side, then torque every bolt to the value in the instructions.",
  "For a power board, cycle each door several times and check that the step clears the rocker and body in both positions.",
  "Recheck bolt torque after the first week of driving and after the first trail run.",
 ],
 "avoid": [
  {"h": "SuperCrew parts on a SuperCab", "body": "The cabs are different lengths. Westin and TAC sell separate SuperCab parts; order those."},
  {"h": "Trusting a title that only says Ranger", "body": "No cab and no year means a guess. Ask the seller for the cab and year in writing."},
  {"h": "Drop steps on a rock trail", "body": "They are the lowest part of the body side. Use a slider-style step or a power board that retracts."},
  {"h": "Jacking from a running board", "body": "Steps are for feet. A body-mounted bar bends under a jack; use the frame."},
 ],
 "verdict": {
  "thesis": "Buy Westin's HDX Drop for a SuperCrew that wants a lower step, Westin's PRO TRAXX 5 for a SuperCab, and AMP Research's PowerStep or Westin's Pro-e if you want the step to disappear when the doors close.",
  "body": "Side steps on the 2019–2023 Ranger are easy to fit once you know the cab. Westin's HDX Drop and PRO TRAXX 5 are the best-documented fixed bars, with no-drill installs and a 3-year warranty per RealTruck. The AMP Research PowerStep and Westin Pro-e both quote 300 lb per side and keep the stock clearance when the doors are closed, at a price that buys several fixed sets. TAC's Sidewinder is the budget step for an FX4, the APS stainless board suits salt states, and TAC's 4.25 in board covers the lowest price.\n\nSteps keep mud off the sill and off your floor liners, so they pair well with a liner set cut for your cab. A tonneau cover for the 5 ft SuperCrew or 6 ft SuperCab bed is the other common first upgrade. If you have moved to the 2024–2026 Ranger, shop that truck's parts by its own fit list; some Westin parts span both trucks, but only the maker's list says which.",
 },
 "sources": [
  ["Westin HDX Drop 56-14155 (RealTruck)", "https://realtruck.com/p/westin-hdx-drop-nerf-step-bars/wes-56-14155/"],
  ["Westin HDX Drop Nerf Step Bars (Westin)", "https://www.westinautomotive.com/hdx-drop-nerf-step-bars"],
  ["AMP Research PowerStep 76136-01A (RealTruck)", "https://realtruck.com/p/amp-research-powerstep-running-boards/amp-76136-01a/"],
  ["Westin PRO TRAXX 5 21-54145 (RealTruck)", "https://realtruck.com/p/westin-pro-traxx-5-oval-nerf-bars/wes-21-54145/"],
  ["Westin Pro-e Electric Running Boards, 29-24155 application (Westin)", "https://www.westinautomotive.com/pro-e-electric-running-boards"],
  ["2019 Ford Ranger: cabs, trims, FX4 package (Ford Media Center)", "https://media.ford.com/content/fordmedia/fna/us/en/products/trucks/ranger/2019-ranger.html"],
  ["2021 Ford Ranger: Tremor package with hoop-style steps (Ford Media Center)", "https://media.ford.com/content/fordmedia/fna/us/en/products/trucks/ranger/2021-ranger.html"],
  ["Ford Ranger (T6), North American cabs, FX4 and Tremor (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_Ranger_(T6)"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note)
FITS = [
 ("B07QJKN563","Westin 56-14155 HDX Drop Nerf Bars Textured Black, 2019-2025 Ranger SuperCrew","Westin","$600–$700",{"cab":"SuperCrew"},"No drilling (RealTruck); title runs to 2025, RealTruck lists 2019-2026; confirm 2024+ with seller."),
 ("B084L5K547","AMP Research 76136-01A PowerStep Plug N Play Electric Running Boards, 2019 Ford Ranger SuperCrew/SuperCab","AMP Research","$1,500–$1,800",{},"Title names 2019; RealTruck lists 2019-2023. SuperCab needs board trimming (RealTruck); confirm year with seller."),
 ("B07QF88CZM","Westin 21-54145 PRO TRAXX 5 Oval Nerf Bars Black, 2019-2023 Ranger SuperCab","Westin","$500–$600",{"cab":"SuperCab"},"SuperCab only; no-drill (RealTruck)."),
 ("B0CLTPV47M","Westin 29-24155 Pro-e Electric Running Boards Textured Black, 2019-2022 Ranger SuperCrew","Westin","Check listing",{"cab":"SuperCrew"},"Title stops at 2022; Westin's fit list reads 2019-2026 SuperCrew; confirm 2023 with seller."),
 ("B097CNPK26","TAC Sidewinder 4 in Drop Side Steps, Rocker Slider style, 2019-2025 Ranger SuperCrew","TAC","Check listing",{"cab":"SuperCrew"},"SuperCrew only; title runs to 2025, confirm 2024+ with seller."),
 ("B07VNKLDNX","APS 5 in Stainless Steel Running Boards Matte Black, 2019-2023 Ranger SuperCrew 4-Door","APS","Check listing",{"cab":"SuperCrew"},"SuperCrew only; confirm weight rating and warranty with seller."),
 ("B07TK37H2D","TAC 4.25 in Running Boards Heavy Texture Black, 2019-2023 Ranger SuperCrew","TAC","Check listing",{"cab":"SuperCrew"},"SuperCrew only; confirm material and warranty with seller."),
 ("B07QC6C6J3","Westin 21-24145 PRO TRAXX 4 Oval Nerf Bars Black, 2019-2023 Ranger SuperCab","Westin","Check listing",{"cab":"SuperCab"},"4 in oval version for the SuperCab."),
 ("B09ZQ1PCD2","TAC Sidewinder 4 in Drop Side Steps, Rock Slider Armor style, 2019-2023 Ranger Super Cab","TAC","Check listing",{"cab":"SuperCab"},"SuperCab version of the Sidewinder."),
 ("B07RJWZ22X","APS Running Boards Black Powder Coat, 2019-2023 Ranger Super Cab (2 full doors + 2 rear-hinged)","APS","Check listing",{"cab":"SuperCab"},"SuperCab version."),
 ("B07W5M4SJR","TAC 3 in Stainless Steel Side Bars, 2019-2023 Ranger Super Cab","TAC","Check listing",{"cab":"SuperCab"},"Stainless tube for the SuperCab."),
 ("B07TK4P5ZV","TAC 4 in Oval Side Bars Texture Black, 2019-2023 Ranger SuperCrew","TAC","Check listing",{"cab":"SuperCrew"},"Oval tube alternative to the 4.25 in board."),
 ("B07TK4PW39","BETTER AUTOMOTIVE 4 in Oval Side Bars Texture Black, 2019-2023 Ranger SuperCrew","BETTER AUTOMOTIVE","Check listing",{"cab":"SuperCrew"},"Budget oval tube."),
 ("B0CW92SRD4","RHOBRA 4.5 in Drop Down Running Boards, 2019-2025 Ranger SuperCrew","RHOBRA","Check listing",{"cab":"SuperCrew"},"Budget drop step; title runs to 2025, confirm 2024+ with seller."),
 ("B0GFGHN3WN","Tyger Auto 3.5 in Rider Oval Tube Running Boards TG-SS2F64861, 2019-2023 Ford Ranger","Tyger Auto","Check listing",{},"Title names no cab; confirm SuperCrew or SuperCab with seller."),
]
