"""Long-form article — Best Roof Racks for 2021–2026 Ford Bronco (6th gen, U725).
Mirrors the approved pilot (ford_f150_2021_tonneau.py). No invented hands-on testing: every spec below comes
from the manufacturer/retailer pages listed in SOURCES (checked 2026-09-24).
"""

KEY = ("ford", "bronco", "2021-present", "roof-racks")

TITLE = "Best Roof Racks for 2021–2026 Ford Bronco: 7 Fit-Checked Racks for Hardtop and Soft Top"
META = ("Seven roof racks for the 2021–2026 Bronco, by 2-door or 4-door and hardtop or soft top, with load "
        "ratings, removable-panel notes and Ford's roof limits.")

FAQ = [
 ("What is the best roof rack for a 2021+ Ford Bronco?",
  "For a 4-door hardtop, the Rough Country 88202 full rack: 46.25 x 91 in of powder-coated aluminum with published 300 lb dynamic and 600 lb static ratings, listed for the 2021–2026 Bronco and the 2022–2026 Bronco Raptor. If you want a full-length rack for less, the Hooke Road Discovery is $499.99 at the maker. 2-door owners should look at the Hooke Road 2-door rack, and soft-top owners at the DV8 soft-top rack."),
 ("How much weight can the Bronco roof carry?",
  "Use the figures in your owner's manual or Ford's equipment installation guide. Owners on Bronco6G quote 110 lb dynamic (while driving) and 450 lb static (parked), citing Ford's documentation; some threads mention a 100 lb figure, so check your own truck's paperwork. The rack's weight counts against the dynamic limit, which means a 67 lb rack leaves only about 43 lb for cargo under 110 lb. A rack's own 300–800 lb rating doesn't change the vehicle's limit."),
 ("Do roof racks fit both the 2-door and 4-door Bronco?",
  "Mostly not. The 2-door and 4-door hardtops are different lengths, so full platforms are sold separately. Rough Country's 88202, the Hooke Road Discovery and both DV8 racks are 4-door only; Hooke Road makes a separate 2-door rack. Some crossbar kits, such as the Wonderdriver 5-piece set, are listed for both 2-door and 4-door hardtops. Check the door count in the listing title before you order."),
 ("Can I still remove the roof panels with a roof rack installed?",
  "With some racks, yes. Hooke Road says its 4-door Discovery rack lets you remove the front and middle roof panels, and its 2-door rack keeps the front top panels removable. Rough Country's half rack sits over the rear section and is listed as Freedom Top compatible. A full platform that bolts across the front panels will tie them down, so if taking the roof off is why you bought a Bronco, choose a half rack or one designed for panel removal."),
 ("Is there a roof rack for the Bronco soft top?",
  "Yes, but it's a different kind of rack. A soft top can't carry load, so soft-top racks bolt to the vehicle's factory attachment points and bridge over the fabric. DV8's RRBR-01 is built for 2021–2026 4-door Broncos with the factory soft top, is rated at 200 lb dynamic evenly distributed, and excludes the Raptor and Everglades. Crossbars sold for soft tops also exist, but check how and where they mount before you buy."),
 ("Do Bronco roof racks fit the Bronco Sport?",
  "No. The Bronco Sport is a different, smaller vehicle with a fixed roof and, on some trims, factory raised side rails. Every rack on this page is for the full-size Bronco, and most listings say \"exclude Bronco Sport\" in the title. Bronco Sport owners need crossbars made for that vehicle's rails. Search results mix the two constantly, so if a listing shows a crossover with raised side rails in the photos, or names Bronco Sport trims such as Base and Big Bend, it's for the Sport, not your Bronco."),
 ("Does the Sasquatch package or the Raptor change roof rack fit?",
  "The Sasquatch package adds 35 in tires and raises the truck, but it doesn't change the hardtop, so racks listed for your door count and roof type still fit. The added height matters for garages and parking structures once a rack is on. The Bronco Raptor is a 4-door hardtop; Rough Country and Hooke Road name it in their fitment, while DV8's soft-top rack excludes it. One budget crossbar listing also excludes the 4-door Badlands 2.7L, so read the exclusions."),
 ("Can a Bronco carry a rooftop tent?",
  "Yes, within limits. Parked, owners cite a 450 lb static limit, which covers the tent plus the people inside. On the road, the tent and rack together must stay under the dynamic limit, which owners cite as 110 lb. One Bronco6G owner notes a Yakima rooftop tent at 101.4 lb, which with a rack would exceed that figure. A lighter soft-shell tent and a light rack give you the most room, but confirm both limits in your manual first."),
 ("Do I need to drill the hardtop to fit a rack?",
  "No for every rack here. Hooke Road and DV8 describe their hardtop racks as bolt-on with no drilling, using the factory hardtop attachment points or rain gutters, and DV8's soft-top rack also bolts on with no drilling. Plan on 1 to 1.5 hours for hardtop racks and about 3 hours for DV8's soft-top rack, and have a helper for the heavier platforms."),
 ("Should I get crossbars or a full platform?",
  "Crossbars are enough for bikes, skis, a kayak or a cargo box, cost roughly $150–$240, weigh less and leave more of the Bronco's small dynamic limit for gear. A platform makes sense if you carry flat, bulky items such as recovery boards, cases or a tent, or want a light bar mount. Because the roof limit is low, lighter is almost always better on this truck."),
]

ARTICLE = {
 "dek": "Seven roof racks for the sixth-generation Bronco, from crossbar kits for the hardtop to full platforms and a rack that bridges the soft top. For each one we list door count, roof type, load rating, weight and whether you can still pull the roof panels.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these racks ourselves. We ranked them on published specs (load rating, size, weight, material, warranty), on the fitment each maker or seller lists for the 2021–2026 Bronco by door count and roof type, and on what Bronco owners report on the Bronco6G forum. Prices were checked at the manufacturer or a specialist retailer in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Match the rack to your roof and door count.** 2-door hardtop, 4-door hardtop and soft top each need a different rack. Almost every full platform here is 4-door only.",
  "**The Bronco's dynamic roof limit is small.** Owners cite 110 lb while driving and 450 lb parked, from Ford's documentation. The rack's own weight counts against the 110 lb.",
  "**Think about the removable panels.** Half racks and some full racks let you pull the front panels; a platform bolted across them doesn't.",
  "**Soft tops need a bridging rack.** DV8's soft-top rack bolts to the factory attachment points and is rated at 200 lb dynamic.",
  "**None of these fit the Bronco Sport.** It's a different vehicle with its own roof rails.",
 ],
 "top_picks": [
  {"asin": "B0FKC46Z7S", "role": "Best overall (4-door)", "why": "46.25 x 91 in aluminum, 300 lb dynamic / 600 lb static, fits the Raptor too"},
  {"asin": "B0D173XGG9", "role": "Best value full rack (4-door)", "why": "$499.99, 102.1 in long, keeps the front and middle panels removable"},
  {"asin": "B0FSTD2BN1", "role": "Best half rack", "why": "46.25 x 42 in over the rear section, Freedom Top compatible"},
  {"asin": "B0CR3MLR7Z", "role": "Best for 2-door", "why": "Made for the 2-door hardtop, 500 lb distributed, $449.99"},
  {"asin": "B0BJLCRG9K", "role": "Best for soft top", "why": "DV8 rack that bridges the factory soft top, about 31 lb, 200 lb dynamic"},
 ],
 "fit_table": {
  "caption": "2021–2026 Bronco roof setups (the rack must match the roof and door count)",
  "head": ["Roof", "Doors", "What fits", "Notes"],
  "rows": [
   ["Hardtop", "4-door (incl. Raptor)", "Full or half platforms, crossbar kits", "Most racks here. Check whether the front panels stay removable."],
   ["Hardtop", "2-door", "2-door platforms, crossbar kits listed for 2-door", "Shorter top; 4-door platforms won't fit."],
   ["Painted (body-color) hardtop", "2- or 4-door", "Racks that name the painted top", "Hooke Road says its 4-door Discovery works with it; ask others."],
   ["Soft top", "4-door", "Bridging racks such as DV8 RRBR-01", "Excludes Raptor and Everglades per DV8."],
   ["Any", "Bronco Sport", "None on this page", "Different vehicle; buy Bronco Sport crossbars."],
  ],
 },
 "look_for": [
  {"h": "Roof type and door count first",
   "body": "The Bronco came with a removable hardtop or a soft top, as a 2-door or a 4-door, and each combination has a different rack list. Full platforms are sized for one hardtop length: Rough Country's 88202, the Hooke Road Discovery and DV8's hardtop rack are 4-door only, while Hooke Road sells a separate 2-door rack. Soft tops need a rack that bridges the fabric. Crossbar kits are the most flexible, and some list both 2- and 4-door hardtops. Before comparing brands, note your doors, your roof and whether your hardtop is body-color painted."},
  {"h": "Ford's roof limit versus the rack's rating",
   "body": "Rack ratings on this page run from 200 lb to 800 lb, but the Bronco's own limit is much lower. Owners on Bronco6G quote Ford's figures as 110 lb dynamic and 450 lb static, citing the equipment installation guide. The rack's weight comes off the dynamic number while you drive. Hooke Road's 4-door Discovery weighs about 67 lb, which leaves roughly 43 lb for cargo. DV8's soft-top rack at about 31 lb leaves more. For light rack weight and a clear roof, crossbars or a half rack usually make the most sense on this truck."},
  {"h": "Keeping the roof panels removable",
   "body": "Taking the roof off is part of owning a Bronco, and a rack can end that. A platform bolted across the front panels ties them down. Rough Country's half rack covers the rear section only and is listed as Freedom Top compatible. Hooke Road says its 4-door Discovery lets you remove the front and middle panels, and its 2-door rack keeps the front top panels removable. Other makers don't always say, so ask the seller before ordering. A half rack plus open front panels is a common setup for summer driving."},
  {"h": "Rack weight and material",
   "body": "Because the dynamic limit is small, weight counts more on a Bronco than on most SUVs. Aluminum racks are lighter for their size, while steel adds strength and weight. DV8 builds both of its racks from steel plate and tubing: the hardtop version weighs about 53 lb and the soft-top version about 31 lb. Hooke Road combines aluminum crossbars with steel side panels, at about 67 lb for the 4-door and 62 lb for the 2-door. Rough Country uses powder-coated aluminum but doesn't publish a weight, so ask before you do the math."},
  {"h": "Light bars and wind noise",
   "body": "Many Bronco racks are sold with light bars in mind. DV8's hardtop and soft-top racks accept 40 in and 50 in light-bar mounts, and Hooke Road's 2-door rack takes up to a 36 in bar. Rough Country's configurator offers light-bar options. A front fairing cuts noise: Hooke Road fits one to both racks and says wind noise stays acceptable up to about 60 mph on the 4-door. Above that, expect more noise. A light bar adds weight too, so count it against the roof limit."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "Listing names 2021–2026 Bronco, your door count and roof type", "\"Bronco\" racks that don't say 2-door or 4-door, or Bronco Sport parts"],
   ["Mounting", "Bolt-on to factory hardtop points or rain gutters, no drilling", "Kits that need holes in the hardtop"],
   ["Load rating", "Published dynamic figure plus rack weight", "Only a static or \"evenly distributed\" figure with no weight"],
   ["Panels", "Front panels still removable, or a half rack", "Full racks that lock the front panels in place without saying so"],
   ["Painted top", "Listing that names the body-color hardtop", "Assuming a rack for the standard top fits a painted one"],
   ["Accessories", "T-slot crossbars, light-bar mounts", "Racks with no tie-down points"],
  ],
 },
 "types_table": {
  "caption": "Roof rack types compared on the 2021–2026 Bronco",
  "head": ["Type", "Price on this page", "Mounts to", "Rack weight", "Best for"],
  "rows": [
   ["Crossbar kit (side rails + bars)", "~$150–$240", "Hardtop attachment points", "Light", "Bikes, skis, kayaks, a cargo box"],
   ["Half rack", "From $499.95 (Rough Country)", "Rear hardtop section", "Not published", "Open-roof driving with gear on top"],
   ["Full aluminum platform", "$449.99–$499.99 (Hooke Road)", "Hardtop points or rain gutters", "~62–67 lb", "Tents, recovery gear, long loads"],
   ["Steel light-bar rack", "$999.99 (DV8 hardtop)", "Factory hardtop hardware", "~53 lb", "Light bars and tie-downs"],
   ["Soft-top bridging rack", "$1,199.99 (DV8 soft top)", "Factory attachment points", "~31 lb", "Soft-top trucks"],
  ],
 },
 "picks": [
  {"asin": "B0FKC46Z7S", "role": "Best overall (4-door)", "price": "$500–$900 (configurable)",
   "pros": ["Published 300 lb dynamic and 600 lb static ratings", "Full 46.25 x 91 in deck", "Powder-coated aluminum", "Listed for the 2021–2026 Bronco and 2022–2026 Bronco Raptor", "Configurable, including light-bar options"],
   "cons": ["4-door only", "Weight and warranty not on the product page", "A full rack covers the front panels"],
   "body": "Rough Country's 88202 is the Bronco platform with the clearest published numbers. The full version measures 46.25 in wide by 91 in long in powder-coated aluminum, and Rough Country rates it at 300 lb dynamic and 600 lb static, the same figures it uses on its 4Runner platforms. The fitment covers 4-door 2021–2026 Broncos and the 2022–2026 Bronco Raptor. The Amazon listing is titled for the 4-door with T-slot crossbars and a 600 lb load, and it gives the years as 2021–2025, so confirm 2026 fit with the seller if you have the newest truck.\n\nThe 88202 is sold through a configurator on Rough Country's site, starting at $499.95, with options such as light bars that change the price, so the full rack costs more than the base figure. Remember that the Bronco's dynamic roof limit, cited by owners at 110 lb, sits well below the rack's 300 lb, and the rack's weight counts against it. Rough Country doesn't publish that weight on the product page, so ask the seller before loading up. A full-length deck will cover the front panels; if you want them to come off, see the half rack below.",
   "who": "4-door hardtop owners, including Raptor owners, who want a full-length aluminum deck with published ratings.",
   "specs": [["Type", "Full-length platform"], ["Part #", "88202 (configurable)"], ["Fits", "2021–2026 Bronco 4-door; 2022–2026 Bronco Raptor"], ["Size", "46.25 x 91 in"], ["Dynamic load", "300 lb"], ["Static load", "600 lb"], ["Material", "Powder-coated aluminum"], ["Price", "From $499.95 (configurator)"]]},
  {"asin": "B0D173XGG9", "role": "Best value full rack (4-door)", "price": "$499.99",
   "pros": ["$499.99 at Hooke Road for a full-length rack", "Front and middle roof panels stay removable", "Seven T-slot aluminum crossbars take 8 mm nuts", "No drilling, factory hardtop attachment points", "Hooke Road says it works with the painted hardtop"],
   "cons": ["About 67 lb, heavy against a 110 lb dynamic limit", "800 lb is an evenly distributed figure, not a dynamic rating", "Adds about 4.5 in of height"],
   "body": "Hooke Road's Discovery rack is the cheapest full-length platform here and one of the few that keeps the Bronco's roof usable as a removable roof. Hooke Road lists it at $499.99 for 2021–2026 4-door hardtops. It's about 47.6 in wide and 102.1 in long, with seven extruded aluminum crossbars (3.2 x 0.8 in) whose T-slots take standard 8 mm nuts for lights, tents and recovery boards. The side, front and rear panels are 13-gauge steel with an E-coat and textured black powder coat. Hooke Road says you can still remove the front and middle roof panels, and that the rack works with the painted hardtop.\n\nThe trade-off is weight. Hooke Road quotes about 67 lb, and the 800 lb capacity is an evenly distributed figure, not a driving rating. Against the 110 lb dynamic limit owners cite, 67 lb leaves little for cargo while moving, so this rack suits bulky, light gear or a tent used parked. It bolts on with no drilling in about 1.5 hours, and Hooke Road suggests two or three people. The front fairing keeps wind noise acceptable up to about 60 mph, per the maker. The rack adds roughly 4.5 in of height.",
   "who": "4-door owners who want a full-length rack on a budget and still want to remove the front panels.",
   "specs": [["Type", "Full-length platform"], ["Fits", "2021–2026 Bronco 4-door hardtop, incl. Raptor (per listing)"], ["Size", "~47.6 x 102.1 in"], ["Weight", "~67 lb"], ["Capacity", "800 lb evenly distributed"], ["Crossbars", "7 aluminum, 8 mm T-slot"], ["Mounting", "Factory hardtop points, no drilling"], ["Install", "~1.5 hours, 2–3 people"], ["Price", "$499.99 (Hooke Road)"]]},
  {"asin": "B0FSTD2BN1", "role": "Best half rack", "price": "From $499.95",
   "pros": ["Covers only the rear section of the roof", "Listed as Freedom Top compatible", "Same 300 lb dynamic / 600 lb static ratings", "Powder-coated aluminum with T-slot crossbars", "Lighter load on the roof than a full rack"],
   "cons": ["4-door only", "42 in deck limits long items", "Weight not published"],
   "body": "For many Bronco owners, the half rack is the better Rough Country. It's the same 88202 family in a shorter 46.25 x 42 in size, placed over the rear section of the roof, and Rough Country lists it as Freedom Top compatible. That means the front panels stay removable, so you keep the open-air driving the Bronco was bought for while still carrying boards, a tent or a cargo case above the cargo area. The published ratings are the same 300 lb dynamic and 600 lb static.\n\nA shorter deck is also lighter, and that matters on a roof where owners cite a 110 lb dynamic limit. Rough Country doesn't list the weight, so ask before you plan a load. The fitment is 4-door only, including the 2022–2026 Bronco Raptor. The half rack is how Rough Country's configurator starts at $499.95, but options such as a light bar change the price. The Amazon listing is titled for the 2021–2026 Bronco 4-door with a 600 lb load and T-slot crossbars.",
   "who": "4-door owners who drive with the front panels off and want a deck over the rear of the roof.",
   "specs": [["Type", "Half platform"], ["Part #", "88202 (half configuration)"], ["Fits", "2021–2026 Bronco 4-door; 2022–2026 Raptor"], ["Size", "46.25 x 42 in"], ["Dynamic load", "300 lb"], ["Static load", "600 lb"], ["Panels", "Freedom Top compatible"], ["Material", "Powder-coated aluminum"]]},
  {"asin": "B0CR3MLR7Z", "role": "Best for 2-door", "price": "$449.99",
   "pros": ["Made for the 2021–2026 2-door hardtop", "Front top panels stay removable", "Seven aluminum T-slot crossbars", "Bolts to the factory rain gutters, no drilling", "Front fairing; takes up to a 36 in light bar"],
   "cons": ["About 62 lb against a small dynamic limit", "500 lb is evenly distributed, not dynamic", "2-door only"],
   "body": "Full platforms for the 2-door Bronco are harder to find because most makers start with the 4-door. Hooke Road's 2-door rack fills the gap. It's listed at $449.99 at the maker and 500 lb on Amazon for 2021–2026 2-door hardtops. It measures 47.6 in wide by 86.5 in long and adds about 3.8 in of height. It combines 13-gauge steel panels with seven extruded aluminum crossbars, each with dual T-slot channels on top that take standard 8 mm nuts. Hooke Road says the front top panels remain removable.\n\nInstallation is bolt-on to the factory rain gutters with the included brackets and hardware, and no drilling. The front fairing reduces wind noise, and there's room for a light bar up to 36 in. At about 62 lb, this rack uses much of the Bronco's cited 110 lb dynamic limit on its own, so it works best for light, bulky gear or a tent used while parked. The 500 lb figure is evenly distributed, not a driving rating. If you carry only bikes or skis, a crossbar kit listed for the 2-door is lighter.",
   "who": "2-door hardtop owners who want a full platform and still want to remove the front panels.",
   "specs": [["Type", "Full-length platform"], ["Fits", "2021–2026 Bronco 2-door hardtop"], ["Size", "47.6 x 86.5 in"], ["Weight", "~62 lb"], ["Capacity", "500 lb evenly distributed"], ["Crossbars", "7 aluminum, dual T-slot"], ["Mounting", "Factory rain gutters, no drilling"], ["Price", "$449.99 (Hooke Road)"]]},
  {"asin": "B0BKNJBSFZ", "role": "Best light-bar rack (hardtop)", "price": "$999.99",
   "pros": ["Published 200 lb dynamic rating", "Accepts 40 in and 50 in light-bar mounts", "Bolt-on with factory hardware, no drilling", "Arced crossbars and many tie-down points", "About 1 hour to install"],
   "cons": ["$999.99 for a steel rack", "About 53 lb", "One-year limited warranty"],
   "body": "DV8's hardtop rack stands out because DV8 publishes a dynamic rating. It's 200 lb evenly distributed while driving, which is more useful than a static-only figure when you're planning trail loads. ExtremeTerrain lists it at $999.99 for 2021–2026 4-door Broncos with the factory hardtop; the hardtop it's built around measures 90.5 by 44.5 in. It's made from steel plate and tubing with a micro-texture black powder coat, weighs about 53 lb, and bolts on in about an hour using factory hardware, with no drilling.\n\nThe arced crossbars add space for cargo, and the rack has multiple tie-down and accessory points plus mounts for 40 in and 50 in light bars, which is why it's popular with owners building a trail truck. Two cautions. First, the 200 lb rating belongs to the rack; the vehicle's own dynamic limit, cited by owners at 110 lb, still applies. Second, the retailer's fitment notes mention the OEM hardtop, so if yours is the body-color painted top, confirm fit with the seller. DV8 backs it with a one-year limited warranty.",
   "who": "4-door hardtop owners building a trail truck with a light bar who want a published dynamic rating.",
   "specs": [["Type", "Steel hardtop rack"], ["Part #", "RRBR-02"], ["Fits", "2021–2026 Bronco 4-door, OEM hardtop"], ["Dynamic load", "200 lb evenly distributed"], ["Weight", "~53 lb"], ["Material", "Steel plate and tubing, powder coat"], ["Light bar", "40 in and 50 in mounts"], ["Install", "~1 hour, no drilling"], ["Warranty", "1-year limited"]]},
  {"asin": "B0BJLCRG9K", "role": "Best for soft top", "price": "$1,199.99",
   "pros": ["Made for 4-door Broncos with the factory soft top", "About 31 lb, the lightest platform here", "200 lb dynamic rating", "No drilling; uses factory attachment points", "Takes 40 in and 50 in light bars on boxed rear mounts"],
   "cons": ["$1,199.99, the most expensive rack here", "About 3 hours with two people", "Excludes Raptor and Everglades"],
   "body": "A soft top can't carry weight, so a soft-top rack has to bridge the fabric and bolt to the vehicle instead. DV8's RRBR-01 does that. ExtremeTerrain lists it at $1,199.99 for 2021–2026 4-door Broncos with the factory soft top, excluding the Raptor and Everglades. It's made from 2 mm and 3.5 mm steel plate and 1.2 mm steel tubing with a black powder coat, weighs about 31 lb and is rated at 200 lb evenly distributed while driving. It mounts to factory attachment points and bolts on with no drilling.\n\nThe low weight is a real advantage on the Bronco: it leaves more of the cited 110 lb dynamic limit for gear than any hardtop platform here. The arced crossbars add cargo room, and the heavy boxed rear mounts take 40 in and 50 in light bars. Budget about three hours and a helper. DV8 only lists compatibility with the OEM soft top, so aftermarket tops aren't covered, and the product pages don't give clearance for folding the top, so ask the seller how the top operates with the rack fitted. The warranty is one year.",
   "who": "4-door soft-top owners who want a platform without buying a hardtop.",
   "specs": [["Type", "Soft-top bridging rack"], ["Part #", "RRBR-01"], ["Fits", "2021–2026 Bronco 4-door, factory soft top (not Raptor/Everglades)"], ["Dynamic load", "200 lb evenly distributed"], ["Weight", "~31 lb"], ["Material", "Steel plate and tubing, powder coat"], ["Install", "~3 hours, 2 people, no drilling"], ["Warranty", "1-year limited"]]},
  {"asin": "B0BW821W8X", "role": "Best budget crossbars", "price": "$150–$220",
   "pros": ["Listed for 2021–2026 Bronco hardtop, 2-door and 4-door", "5-piece kit: side rails plus crossbars", "Light compared with any platform", "Takes standard bike, ski, kayak and cargo-box mounts", "Least expensive way to use the roof"],
   "cons": ["Load rating not in the listing title; confirm", "Hardtop only", "No fairing"],
   "body": "If you carry bikes, skis, a kayak or a cargo box, a crossbar kit is the lightest and cheapest option, and on a Bronco with a small dynamic roof limit, light matters. The Wonderdriver kit is a 5-piece set of side rails and crossbars titled for 2021–2026 Bronco hardtops in both 2-door and 4-door form, and excludes the Bronco Sport. Because it works on both door counts, it's also one of the few options for 2-door owners who don't want a full platform.\n\nThe listing title doesn't give a load rating for this version. Wonderdriver sells a second listing, B0FXM1DYRK, titled with a 330 lb rating, if you want a published number. Either way, the vehicle's own limit is lower. Check on the listing whether the rails cover the front panels and whether you can still remove them with the kit in place, and ask the seller if it isn't stated. There's no fairing, so take the bars off between trips if the noise bothers you.",
   "who": "2- or 4-door hardtop owners who carry bikes, boards or a cargo box and want the lightest setup.",
   "specs": [["Type", "Crossbar kit (side rails + bars)"], ["Fits", "2021–2026 Bronco hardtop, 2-door and 4-door"], ["Pieces", "5"], ["Rating", "Confirm on listing (330 lb version: B0FXM1DYRK)"], ["Mounting", "Hardtop, no drilling per listing"], ["Excludes", "Bronco Sport"]]},
 ],
 "install": [
  "Identify your roof and door count: 2-door or 4-door, hardtop (standard or painted) or soft top. Order the rack listed for that exact combination.",
  "On a hardtop, clean the attachment points or rain gutters and fit the kit's brackets loosely on both sides before tightening anything.",
  "Lift the rack or crossbars onto the brackets with a helper; platforms weigh 50–70 lb and a hardtop scratches easily.",
  "Tighten the hardware evenly side to side to the kit's torque figure, then fit the fairing and any light-bar mounts.",
  "Test the roof: remove and refit the front panels (if the rack allows it), and open the doors and rear gate fully to check clearance.",
  "Re-check every bolt after the first few drives and after each rough trail, since vibration loosens roof-rack hardware.",
 ],
 "avoid": [
  {"h": "Buying for the wrong door count", "body": "Full platforms are sized for the 2-door or the 4-door hardtop, not both. Check the listing title before you order."},
  {"h": "Planning around the rack's rating", "body": "An 800 lb rack doesn't change the Bronco's cited 110 lb dynamic limit. Rack weight plus cargo has to fit under it."},
  {"h": "Loading the soft top", "body": "Crossbars or cargo resting on the fabric will damage it. Use a rack built to bridge the soft top."},
  {"h": "Bronco Sport parts", "body": "Bronco Sport racks and bars fit a different vehicle. The full-size Bronco needs its own."},
 ],
 "verdict": {
  "thesis": "Buy by roof and door count: Rough Country's full or half 88202 for most 4-door hardtops, Hooke Road for a full rack on a budget or on a 2-door, DV8 for soft tops, and a crossbar kit if you only carry bikes or boards.",
  "body": "The Bronco's small dynamic roof limit, cited by owners at 110 lb, is what makes this category different. Every pound of rack is a pound less of gear, so lighter racks and half racks make more sense here than on most SUVs. Rough Country publishes the clearest ratings, and its half rack keeps the front panels removable. Hooke Road offers full-length racks for less, including the rare 2-door option, but at 62–67 lb they suit bulky, light loads. DV8 is the answer for soft tops, and crossbars are enough for bikes and skis.\n\nIf you mainly need more storage, a cargo box on crossbars keeps gear dry and locked, and a trailer hitch with a cargo carrier takes weight off the roof altogether. Tailgate-mounted spares complicate hitch carriers, so check clearance first. Pair either with good floor liners if the gear you carry comes back muddy.",
 },
 "sources": [
  ["Rough Country Ford Bronco roof rack 88202 (configurable)", "https://www.roughcountry.com/product/configurable/ford-bronco-roof-rack-88202"],
  ["Hooke Road Discovery roof rack, 2021–2026 Bronco 4-door hardtop", "https://www.hookeroad.com/products/bronco-discovery-roof-rack-ford-21-23-4-door-hardtop-b8906s"],
  ["Hooke Road aluminum roof rack, 2021–2026 Bronco 2-door hardtop", "https://www.hookeroad.com/products/aluminum-ford-bronco-roof-rack-b8929s"],
  ["DV8 Offroad hard top roof rack RRBR-02 (ExtremeTerrain)", "https://www.extremeterrain.com/dv8-off-road-bronco-hard-top-roof-rack-rrbr-02.html"],
  ["DV8 Offroad soft top roof rack RRBR-01 (ExtremeTerrain)", "https://www.extremeterrain.com/dv8-offroad-bronco-soft-top-roof-rack-rrbr-01.html"],
  ["Dynamic roof load limit of 110 lbs (Bronco6G)", "https://www.bronco6g.com/forum/threads/dynamic-roof-load-limit-of-110-lbs.1840/"],
  ["Roof rack weight limit discussion (Bronco6G)", "https://www.bronco6g.com/forum/threads/roof-rack-100lbs-weight-limit.22665/"],
  ["Ford Bronco sixth generation (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_Bronco_(sixth_generation)"],
 ],
}

# Product list for this page (replaces the v1 generic list). (asin, name, brand, band, cond, note)
FITS = [
 ("B0FKC46Z7S","Rough Country Full Roof Rack, Ford Bronco 4-Door (2021-2025), aluminum, T-slot crossbars, 600 lb load","Rough Country","$500–$900",{"roof_type":"removable","doors":4},"4-door hardtop incl. Raptor; 300 lb dynamic / 600 lb static. Confirm 2026 fit and price."),
 ("B0D173XGG9","Hooke Road Full Roof Rack, 2021-2026 Ford Bronco & Raptor 4-Door Hardtop, aluminum T-slot crossbars, 800 lb load","Hooke Road","$450–$550",{"roof_type":"removable","doors":4},"~67 lb; front/middle panels stay removable; not Bronco Sport."),
 ("B0FSTD2BN1","Rough Country Half Roof Rack, Ford Bronco 4-Door (2021-2026), aluminum, T-slot crossbars, 600 lb load","Rough Country","$500–$650",{"roof_type":"removable","doors":4},"Rear section; Freedom Top compatible."),
 ("B0CR3MLR7Z","Hooke Road Bronco 2-Door Roof Rack, full length, 2021-2026 Ford Bronco 2-Door Hardtop, 500 lb","Hooke Road","$400–$500",{"roof_type":"removable","doors":2},"2-door hardtop only; ~62 lb."),
 ("B0BKNJBSFZ","DV8 Offroad Hard Top Roof Rack RRBR-02, 2021-2025 Ford Bronco 4-Door, 40/50 in light bar mounts, 200 lb","DV8 Offroad","$950–$1,050",{"roof_type":"removable","doors":4},"OEM hardtop; confirm painted-top fit with seller."),
 ("B0BJLCRG9K","DV8 Offroad Soft Top Roof Rack RRBR-01, 2021-2025 Ford Bronco 4-Door, 200 lb","DV8 Offroad","$1,100–$1,250",{"roof_type":"soft-top","doors":4},"Factory soft top only; not Raptor/Everglades."),
 ("B0BW821W8X","Wonderdriver 5-Piece Roof Rack Cross Bars, 2021-2026 Bronco hardtop 2-door & 4-door","Wonderdriver","$150–$220",{"roof_type":"removable"},"Hardtop only; not Bronco Sport. Confirm load rating on listing."),
 ("B0FXM1DYRK","Wonderdriver 330 lb 5-Piece Cross Bars, 2021-2026 Bronco hardtop 2-door & 4-door","Wonderdriver","$170–$240",{"roof_type":"removable"},"Higher-rated version of pick #7."),
 ("B0DP4MVP7Z","ANTS PART 5-Piece Extended Roof Rack Kit (2 rails + 3 bars), 2021-2026 Bronco 4-door hardtop","ANTS PART","$180–$260",{"roof_type":"removable","doors":4},"4-door only; no-drill."),
 ("B0C9CJK487","ROSY PIXEL Roof Rack Kit, side rails + cross bars, 2021-2026 Bronco hardtop","ROSY PIXEL","$150–$220",{"roof_type":"removable"},"Hardtop only."),
 ("B0D6QW62SB","Broaddict Half Roof Rack, 2021-2026 Bronco 4-door hardtop","Broaddict","$200–$300",{"roof_type":"removable","doors":4},"Rear-half platform; keeps front panels removable."),
 ("B0D179TWJ6","Extended Cross Bars + Side Ladder, 2021-2025 Bronco 4-door hardtop","Generic","$250–$350",{"roof_type":"removable","doors":4},"Includes side ladder."),
]
