"""Long-form article — Best Tonneau Covers for 2019–2023 Ford Ranger (US-market T6, 5 ft and 6 ft beds).
Mirrors the approved pilot ford_f150_2021_tonneau.py. No invented hands-on testing: every spec below comes
from the manufacturer/retailer pages listed in SOURCES (checked 2026-09-24).
"""

KEY = ("ford", "ranger", "2019-2023", "tonneau-covers")

TITLE = "Best Tonneau Covers for 2019–2023 Ford Ranger: 6 Fit-Checked Picks for 5 ft and 6 ft Beds"
META = ("Six tonneau covers matched to the 2019–2023 Ranger's 5 ft SuperCrew and 6 ft SuperCab beds, with load "
        "ratings, warranties, install notes and the 2024 part-number trap.")

FAQ = [
 ("What is the best tonneau cover for a 2019–2023 Ford Ranger?",
  "For most owners, the BAKFlip MX4 in part 448332 for the 5 ft (61 in) bed. It has aluminum panels with a polymer core, a 400 lb evenly distributed rating, auto-latching and a 5-year warranty, and RealTruck lists it at $1,099.99. If you want a lockable hard cover for half that, the Gator EFX (GC24022) is $549. If you open the bed all day, the RetraxPRO MX 80335 is the retractable to get."),
 ("Will a 2019–2023 Ranger tonneau cover fit a 2024 Ranger?",
  "Don't count on it. The 2024 Ranger is a new truck with a slightly shorter, wider bed, and BAK, Retrax, TruXedo and Tyger all sell separate 2024+ part numbers (the BAKFlip MX4 goes from 448332 to 448342). RealTruck lists the Gator EFX GC24022 for 2019–2023 only, even though one Amazon title reads 2019–2025. Buy the part your model year is listed for, and see the 2024–2026 Ranger guide for the new truck."),
 ("Is my Ranger bed 5 ft or 6 ft?",
  "In the US, the 2019–2023 Ranger SuperCrew (four full doors) has the 5 ft bed, which cover makers list as 5'1\" or 61 in. The SuperCab (small rear-hinged doors) has the 6 ft bed, listed as 6'1\" or 72.7 in. If you're unsure, measure inside the bed at the rail from the bulkhead to the inside of the closed tailgate."),
 ("Do these covers fit the Ranger Tremor?",
  "The covers here are listed by model year and bed length, not by trim, so a Tremor needs the same part as any other 2019–2023 Ranger with its bed length: 5'1\" on a SuperCrew. None of the makers we checked call the Tremor out by name, so if your truck has extra bed accessories, such as tie-down rails or a divider, confirm with the seller that the clamps clear them."),
 ("Why do some Ranger covers leak at the tailgate?",
  "Ranger5G owners have pointed to gaps around the ends of the Ranger's tailgate that let water past a cover's corner seals, and one owner there reported his older BAKFlip G2 leaking at those corners. Another poster's view was that folding hard covers will all let in a little water. Center the cover carefully, make sure the tailgate seal touches along its width, and consider a one-piece cover like the UnderCover SE if a dry bed is the priority."),
 ("How long does a BAKFlip MX4 take to install on a Ranger?",
  "BAK quotes 30 minutes or less for one person. Ranger owners on Ranger5G describe a slower job: one took about 3.5 hours and bought extra shims, and several said the paper instructions differed from BAK's video and the Ranger-specific brackets appear only in supplement sheets. On a spray-in liner, one owner advised cleaning the surface with an adhesive prep so the seals stick."),
 ("Hard or soft cover — which suits a Ranger better?",
  "Hard covers (MX4, EFX, RetraxPRO, UnderCover SE) lock under a locked tailgate and, except the SE, carry a published load. Soft covers (Lo Pro, Tyger T3) cost $223 to $540, open fast and weigh less, but vinyl won't stop a knife. On a midsize truck parked in town, where the bed is often the only lockable storage, hard usually makes more sense."),
 ("Can I put weight on top of the cover?",
  "Only on hard covers with a published rating, and only if the weight is spread flat: 500 lb for the RetraxPRO MX, 400 lb for the BAKFlip MX4 and 300 lb for the Gator EFX. The UnderCover SE doesn't list a load rating on RealTruck's page, and soft covers carry nothing. A point load such as a knee or a toolbox corner can dent panels that handle snow fine."),
 ("Is a retractable cover worth it on a 5 ft bed?",
  "It's a harder case than on a full-size truck. The RetraxPRO MX locks at any position and carries 500 lb, but Rack Attack puts the Retrax canister at roughly 10–11 in at the front of the bed, which is a bigger share of a 61 in box. RealTruck lists the 80335 at $1,949.99. Buy it only if full-bed access that locks in any position saves you time every day."),
 ("Can I run a bed rack with a tonneau cover on the Ranger?",
  "Most folding covers leave nowhere to mount a rack. Retrax sells an XR version of the PRO for this Ranger (T-80335) with T-slot rails for crossbars and racks over the cover. If you plan on a rooftop tent or bike rack over the bed, choose the rack system first and the cover second."),
]

ARTICLE = {
 "dek": "Six covers that fit the US-market 2019–2023 Ranger's 5 ft SuperCrew and 6 ft SuperCab beds, from a $223 soft tri-fold to a $1,950 retractable. Each pick lists load rating, warranty and install time, plus the tailgate-gap and 2024 part-number details owners run into.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these covers ourselves. We ranked them on published specs (load rating, materials, warranty, install time), on the fitment each maker lists for the 2019–2023 Ranger, and on what owners report on the Ranger5G forum. Prices were checked at RealTruck and Tyger Auto in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Two beds, tied to cab.** The SuperCrew has the 5 ft bed (61 in); the SuperCab has the 6 ft bed (72.7 in). Cover makers list them as 5'1\" and 6'1\".",
  "**2019–2023 covers are their own part numbers.** BAK, Retrax, TruXedo and Tyger all sell separate parts for the 2024+ Ranger. RealTruck lists the Gator EFX GC24022 for 2019–2023 only, even though one Amazon title says 2019–2025.",
  "**Load ratings separate the hard covers:** 500 lb for the RetraxPRO MX, 400 lb for the BAKFlip MX4, 300 lb for the Gator EFX. Soft covers have no rating.",
  "**The tailgate corners are where Rangers leak.** Ranger5G owners point to gaps at the ends of the tailgate; careful centering and seal setup matter more than brand.",
  "**Security comes from the tailgate.** A hard cover is only as secure as the locked tailgate below it.",
 ],
 "top_picks": [
  {"asin": "B07J5CVWGD", "role": "Best overall", "why": "400 lb rating, aluminum-and-polymer panels, auto-latching, 5-year warranty"},
  {"asin": "B07STF6BB9", "role": "Best value hard cover", "why": "All-aluminum tri-fold with dual slam-latches for $549"},
  {"asin": "B07NYT2TKW", "role": "Best retractable", "why": "500 lb rating, locks in any position, lifetime warranty"},
  {"asin": "B07N99DFT2", "role": "Best soft roll-up", "why": "Sits ¾ in above the rails with automatic tension control"},
  {"asin": "B0BHH638DY", "role": "Best budget", "why": "Aluminum-frame soft tri-fold with a 5-year warranty for $223"},
 ],
 "fit_table": {
  "caption": "2019–2023 Ranger beds (US market)",
  "head": ["Bed", "Inside length at rail", "Cab", "Notes"],
  "rows": [
   ["5 ft (sold as 5'1\")", "61 in", "SuperCrew", "The common bed. Order 448332, 80335, GC24022, 531001, TG-BC3F1066."],
   ["6 ft (sold as 6'1\")", "72.7 in", "SuperCab", "Fewer options. Order the 6 ft part (e.g. RetraxPRO MX 80336, Lo Pro 531101)."],
   ["2024+ Ranger 5 ft", "About 59.6 in", "SuperCrew", "New generation. 2019–2023 covers are listed separately; don't cross-shop."],
  ],
 },
 "look_for": [
  {"h": "Bed length follows the cab",
   "body": "On the US-market 2019–2023 Ranger, the bed is decided by the cab. Four full doors (SuperCrew) means the 5 ft bed that cover makers list as 5'1\" or 61 in. The SuperCab, with small rear-hinged doors, has the 6 ft bed, listed as 6'1\" or 72.7 in. Most covers are made for the 5 ft box first, and some 6 ft parts are harder to find. If the truck came secondhand with aftermarket parts, measure inside the bed at the rail from the bulkhead to the inside of the closed tailgate before ordering."},
  {"h": "2019–2023 and 2024+ are different trucks",
   "body": "Ford's 2024 Ranger is a new generation with a bed about 59.6 in long and wider between the wheel wells, and cover makers treat it as a new application. BAK sells the MX4 as 448332 for 2019–2023 and 448342 for 2024+. TruXedo's Lo Pro goes from 531001 to 531701, and Tyger's T3 from TG-BC3F1066 to TG-BC3F1205. Watch for cheap listings that claim one cover fits 2019–2026. The branded makers don't, and a cover that is off by an inch won't seal at the tailgate."},
  {"h": "Load rating and what 'hard' really means",
   "body": "For hard covers, the published distributed-load rating is the cleanest comparison. RetraxPRO MX aluminum slats are rated for 500 lb, BAKFlip MX4 aluminum/polymer panels for 400 lb and the Gator EFX for 300 lb. RealTruck doesn't list a load rating for the one-piece UnderCover SE. Soft vinyl covers carry no rating at all. They are weather covers. If you want to strap a cooler on top at a campsite or leave snow on the truck for a week, buy something with a number on it."},
  {"h": "Seals at the tailgate corners",
   "body": "The Ranger's tailgate leaves gaps at its ends, and Ranger5G owners describe water getting past cover seals there in the rain. That makes the rear seal and drainage more important than on some trucks. Look for a named tailgate seal and drain tubes: Retrax builds drain tubes into its water-management system, Gator uses drain rails, and the UnderCover SE uses a double-bulb EPDM seal around a one-piece lid. Folding covers have more joints, so expect to fine-tune the fit rather than bolt it on and forget it."},
  {"h": "How much of a short bed you give up",
   "body": "On a 61 in bed every inch counts. BAK says the MX4 folds flush against the cab for full bed access; Gator says the EFX leaves about two-thirds of the bed open when folded. A retractable's canister takes roughly 10–11 in at the front, a bigger share of a 5 ft box than of a full-size bed, though flat items can slide under it. A roll-up gives the whole bed back with a rolled bundle at the cab, and a one-piece lid gives full access only when propped open."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "Part number listed for the 2019–2023 Ranger and 5'1\" or 6'1\" bed", "\"Fits 2019–2026 Ranger\" on no-name listings"],
   ["Frame", "Aluminum frame or rails, no-drill clamps", "Plastic clamps or no frame material named"],
   ["Load rating", "A published distributed rating (300–500 lb) for hard covers", "\"Heavy duty\" with no number"],
   ["Seals / drainage", "Named tailgate seal and drain tubes or rails", "No mention of drainage"],
   ["Warranty", "2 years minimum; 5 years to lifetime is better", "90 days or nothing stated"],
   ["Bed space", "Folds flush to the cab or rolls up", "Bulky stacks that block a 5 ft bed"],
  ],
 },
 "types_table": {
  "caption": "Cover types compared on the 2019–2023 Ranger",
  "head": ["Type", "Price on this page", "Security", "Bed access", "Load on top", "Best for"],
  "rows": [
   ["Soft roll-up", "~$540 (Lo Pro)", "Low (vinyl)", "Full bed", "None", "Tall loads, bikes"],
   ["Soft tri-fold", "~$223 (T3)", "Low (vinyl)", "Folds to cab or comes off", "None", "Budget weather cover"],
   ["Hard tri-fold", "~$549 (EFX)", "High with tailgate locked", "About ⅔", "300 lb", "Security on a budget"],
   ["Hard fold (MX4)", "~$1,100", "High with tailgate locked", "Nearly full; folds against the cab", "400 lb", "Best all-round"],
   ["One-piece hinged", "~$1,300 (UnderCover SE)", "High; twist-lock", "Full when propped open", "Not published", "Driest bed, painted look"],
   ["Retractable", "~$1,950 (RetraxPRO MX)", "High; locks at any position", "Full, minus ~10–11 in canister", "500 lb", "Daily open/close"],
  ],
 },
 "picks": [
  {"asin": "B07J5CVWGD", "role": "Best overall", "price": "$1,100",
   "pros": ["400 lb distributed load rating", "Aluminum panels with high-density polymer core", "Patented auto-latching system", "Doesn't block the third brake light in any position", "5-year warranty; made in Missouri"],
   "cons": ["About 5× the price of the Tyger T3", "Ranger5G owners describe a fiddly install with extra shims", "Warranty is not transferable"],
   "body": "The MX4 is the benchmark folding hard cover, and for this Ranger it is part 448332 for the 5'1\" bed. BAK builds the panels from multi-layer aluminum with a high-density polymer core in a textured matte black finish and rates the cover for 400 lb evenly distributed. It latches itself when you close it, folds flush against the cab to give nearly the whole bed back, and BAK says it never blocks the third brake light. RealTruck lists it at $1,099.99 (list $1,249.99) with a 5-year warranty from the original purchase date.\n\nBAK quotes a one-person, no-drill install in 30 minutes or less. Ranger owners on Ranger5G tell a longer story: one took about 3.5 hours and bought twice the shims included, and several said the printed instructions differed from BAK's video, with the Ranger-specific brackets covered only in supplement sheets. On a spray-in liner, one owner advised using an adhesive prep so the seals stick. Owners who took the time to shim it properly reported no leaks, even after pressure washing. Budget an afternoon, not half an hour.",
   "who": "Owners who want a secure hard cover that stays on year-round and don't mind a careful install.",
   "specs": [["Type", "Hard folding (tri-fold)"], ["Part #", "448332 (5 ft)"], ["Fits", "2019–2023 Ranger, 5'1\" (61 in) bed"], ["Material", "Aluminum panels, polymer core"], ["Load rating", "400 lb distributed"], ["Latching", "Auto-latch, locks with tailgate"], ["Install", "≤30 min (BAK); owners report longer"], ["Warranty", "5 years (non-transferable)"], ["Made in", "USA (Missouri)"]]},
  {"asin": "B07STF6BB9", "role": "Best value hard cover", "price": "$549",
   "pros": ["Multi-layer aluminum construction", "Automatic dual slam-latches with twice the latch points", "Flush seals and drain rails", "Free cargo retriever tool (valued at $70)", "Stake pockets stay accessible"],
   "cons": ["300 lb rating versus 400 lb for the MX4", "2-year warranty only", "About ⅔ of the bed is open when folded"],
   "body": "The EFX is the cheapest cover here that locks, carries weight and is made by a brand with published specs. Gator builds it from multi-layer aluminum with a semi-gloss finish and uses automatic dual slam-latches, with what Gator describes as twice as many latch points as its earlier design. Flush-fitting seals and drain rails deal with water, and the stake pockets stay open for tie-downs. RealTruck lists part GC24022 at $549 (list $599), includes a cargo retriever tool it values at $70, and rates the install at under 30 minutes with no drilling.\n\nYou give up load rating and warranty against the MX4: 300 lb evenly distributed and a 2-year limited warranty with a 30-day exchange, compared with 400 lb and 5 years. Folded, it opens about two-thirds of the bed, so a dirt bike means taking it off. One fitment detail to watch: RealTruck lists GC24022 for the 2019–2023 Ranger 5'1\" bed and says it does not include 2024+, while the Amazon listing title reads 2019–2025. On a 2019–2023 truck either way it fits; on a 2024+ truck, confirm with the seller before buying.",
   "who": "Buyers who want a lockable hard cover under $600 and don't need a 400 lb rating or a long warranty.",
   "specs": [["Type", "Hard tri-fold"], ["Part #", "GC24022 (5 ft) · GC24023 (6 ft)"], ["Fits", "2019–2023 Ranger, 5'1\" bed (RealTruck)"], ["Material", "Multi-layer aluminum"], ["Load rating", "300 lb distributed"], ["Latching", "Automatic dual slam-latches"], ["Install", "<30 min, no drill"], ["Warranty", "2 years + 30-day exchange"]]},
  {"asin": "B07NYT2TKW", "role": "Best retractable", "price": "$1,950",
   "pros": ["500 lb rating, the highest here", "Locks at any position (TraxLatch)", "Opens independently of the tailgate", "Sealed drain tubes", "Limited lifetime warranty"],
   "cons": ["Most expensive cover here", "Canister takes about 10–11 in of a 61 in bed", "Roller repairs mean pulling the canister", "Not fully watertight at the tailgate in heavy rain"],
   "body": "A retractable is the only style here that opens the whole bed and still locks at any point, so you can keep the front of the bed covered while loading the back. The RetraxPRO MX uses double-wall aluminum slats rated for 500 lb, the highest on this page, with a key-lockable TraxLatch handle and an integrated water-management system with sealed drain tubes. It opens and closes with the tailgate up or down. RealTruck lists part 80335 for the 2019–2023 Ranger 5'1\" bed at $1,949.99 (list $2,249.99), with a limited lifetime warranty and a no-drill clamp-on install under 60 minutes. The 6'1\" SuperCab version is 80336.\n\nOn a 5 ft bed the canister matters more. Rack Attack's Retrax guide puts it at roughly 10–11 in at the front of the bed, though flat items slide underneath, and notes these covers aren't completely watertight at the tailgate gap in hard rain and that a roller failure means unbolting the canister. If you want crossbars or a rack over the cover, the XR version (T-80335) adds T-slot rails along the bed.",
   "who": "Owners who open the bed many times a day and want it fully open and locked in any position.",
   "specs": [["Type", "Retractable (manual)"], ["Part #", "80335 (5 ft) · 80336 (6 ft) · XR: T-80335"], ["Fits", "2019–2023 Ranger"], ["Material", "Double-wall aluminum slats"], ["Load rating", "500 lb distributed"], ["Lock", "Key-lockable TraxLatch, infinite positions"], ["Bed space lost", "~10–11 in (canister)"], ["Install", "<60 min, no drill"], ["Warranty", "Limited lifetime (original buyer)"]]},
  {"asin": "B07N99DFT2", "role": "Best soft roll-up", "price": "$540",
   "pros": ["Sits ¾ in above the rails", "Automatic tension control keeps the vinyl tight", "Quick-release; comes off without tools", "One-hand roll-up for nearly full bed access", "Limited lifetime warranty; assembled in South Dakota"],
   "cons": ["Vinyl gives little real security", "No load rating", "Costs about the same as the Gator EFX hard cover"],
   "body": "A roll-up is the right cover if you often carry tall loads, bikes or camping gear that won't fit under a lid. It rolls to the cab with one hand and gives nearly the whole bed back. The Lo Pro sits only ¾ in above the bed rails with internal mounting, so it looks close to flush, and TruXedo's automatic tension control keeps the vinyl taut through hot and cold seasons, which is the usual weak point of a roll-up. The industrial-grade, tear-resistant vinyl has a leather-grain finish.\n\nRealTruck lists part 531001 for the 2019–2023 Ranger 5'1\" bed at $539.99 (regular $569.99) with a limited lifetime warranty and a no-drill install under an hour; the 6'1\" SuperCab version is 531101. A quick-release system lets you take it off without tools. A Ranger5G poster suggested roll-ups like the Lo Pro among the options for a drier bed than folding hard covers. At this price it lines up against the Gator EFX. Pick the Lo Pro for full bed access and the EFX for security.",
   "who": "Owners who haul bikes, coolers and tall gear and care more about access than security.",
   "specs": [["Type", "Soft roll-up"], ["Part #", "531001 (5 ft) · 531101 (6 ft)"], ["Fits", "2019–2023 Ranger"], ["Material", "Industrial-grade vinyl, leather-grain finish"], ["Profile", "¾ in above rails"], ["Tension", "Automatic tension control"], ["Install", "<1 hr, no drill"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0BHH638DY", "role": "Best budget", "price": "$223",
   "pros": ["$223, the lowest price here", "24 oz marine-grade vinyl on aluminum frames", "Stainless steel clamps", "5–10 minute install (Tyger's figure)", "5-year warranty, longer than the Gator EFX's"],
   "cons": ["Vinyl gives little real security", "Over-rail bedliners need small holes cut", "5 ft bed only for this part"],
   "body": "The T3 is the cheapest way to cover a Ranger bed with a brand that publishes its specs. Tyger uses heavy-duty 24 oz marine-grade vinyl on aircraft-grade aluminum frames with stainless steel clamps, and the crossbars come pre-assembled and fold up with the cover. It weighs 27.56 lb, light enough to lift off and stash in a garage. Tyger lists part TG-BC3F1066 at $223 for the 2019–2023 Ranger 5 ft (61 in) bed, for any cab with that bed, backed by a 5-year warranty for US customers, longer than you get with the Gator EFX at more than twice the price.\n\nTyger's own fitment note is the thing to check: if your Ranger has a bedliner that wraps over the rails, you'll need to cut small holes in it for the clamps. Under-rail and spray-in liners need nothing. Tyger quotes a 5–10 minute install. A tri-fold can also flip up against the cab or come off completely, which suits owners who only want the cover on in bad weather.",
   "who": "First-time cover buyers and anyone who wants the bed covered for under $250.",
   "specs": [["Type", "Soft tri-fold"], ["Part #", "TG-BC3F1066 (5 ft)"], ["Fits", "2019–2023 Ranger, 5 ft (61 in), any cab"], ["Material", "24 oz marine vinyl, aluminum frames"], ["Clamps", "Stainless steel"], ["Weight", "27.56 lb"], ["Install", "5–10 min (maker's figure), no drill"], ["Warranty", "5 years (US)"]]},
  {"asin": "B088Q8YM6K", "role": "Best one-piece cover", "price": "$1,300",
   "pros": ["One-piece ABS lid has no fold joints to leak", "Double-bulb EPDM rubber seal", "Single center twist-lock operates dual latches", "Built-in removable LED light", "Textured black finish; assembled in Missouri"],
   "cons": ["About 58 lb, heavy to remove", "No load rating on RealTruck's page", "Full bed access only when propped open; tall loads need it off"],
   "body": "If a dry bed matters more than fast access, a one-piece lid is worth a look on the Ranger. Folding covers have joints and corner seals that can let water through the tailgate gaps Ranger5G owners describe, and one poster there suggested one-piece hard covers as the drier option. The UnderCover SE is a single ABS composite lid built on UnderCover's X-Effect structure, sealed with a double-bulb EPDM rubber gasket. A single low-profile twist-lock in the center works both latches, it comes with two keys, and a built-in LED light, removable via its hook, lights the bed at night.\n\nRealTruck lists part UC2186 for the 2019–2023 Ranger 5'1\" bed at $1,299.99 (list $1,399.99). RealTruck's page lists a 3-year limited warranty on the structure, with longer coverage on the ABS shell and paint; confirm the exact terms on the listing. It weighs about 58 lb and bolts on without drilling. The trade-offs: no published load rating, and anything taller than the bed sides means taking the lid off. The 6'1\" SuperCab version is UC2196.",
   "who": "Owners who want the driest, most car-like bed cover and rarely haul tall loads.",
   "specs": [["Type", "One-piece hinged (ABS)"], ["Part #", "UC2186 (5 ft) · UC2196 (6 ft)"], ["Fits", "2019–2023 Ranger, 5'1\" bed"], ["Material", "ABS composite, X-Effect structure"], ["Seal", "Double-bulb EPDM"], ["Lock", "Center twist-lock, dual latches"], ["Weight", "About 58 lb"], ["Warranty", "3-year limited structure (confirm terms)"]]},
 ],
 "install": [
  "Empty the bed and take out anything that sits where the clamps land: tie-down cleats, bed-divider brackets or the edge of an over-rail liner.",
  "If you have a spray-in liner, clean the rail area where seals will stick; a Ranger5G installer recommended an adhesive prep solution for better adhesion.",
  "Set the rails or frame inside the bed rails with the front seal tight against the bulkhead, and read the Ranger-specific supplement sheet if your kit includes one.",
  "Fit the clamps loosely, center the cover side to side, then close the tailgate and check that the rear seal touches along its whole width, including the ends.",
  "Shim where needed, then tighten the clamps evenly. Route any drain tubes (Retrax) through the corner drain holes.",
  "Recheck clamps after the first week of driving and after the first heavy rain. Retrax lists regular clamp checks as a warranty condition.",
 ],
 "avoid": [
  {"h": "2024+ covers on a 2019–2023 truck (and the reverse)", "body": "The 2024 Ranger's bed is a different size and every major maker lists separate parts. Buy the 2019–2023 part number unless the maker lists your year on it."},
  {"h": "\"Fits 2019–2026 Ranger\" no-name listings", "body": "Branded makers don't sell one cover for both generations. A listing that claims to fit both deserves a question to the seller before you buy."},
  {"h": "Expecting a folding cover to be bone-dry", "body": "Ranger owners report water at the tailgate corners with folding covers. If a dry bed is the goal, set the seals carefully or choose a one-piece lid."},
  {"h": "A folding cover when you want a bed rack", "body": "Most folding covers leave no mounting points. If a rack or rooftop tent is planned, look at the RetraxPRO XR (T-80335) or a rack designed to sit over a cover."},
 ],
 "verdict": {
  "thesis": "Match the bed to the cab, buy the 2019–2023 part number, then pick: the BAKFlip MX4 at $1,100, the Gator EFX at $549, or the RetraxPRO MX if you open the bed all day.",
  "body": "The best cover for a 2019–2023 Ranger is the one sold for your bed and model year, 5'1\" on the SuperCrew and 6'1\" on the SuperCab, and never a 2024+ part. From there it comes down to how you use the bed. The MX4 has the best mix of security, load rating and daily usability, if you're willing to spend time on the install. The EFX is the budget hard cover. The Retrax is worth its price only if locking the bed at any position saves you time every day. The UnderCover SE is the one to buy for the driest bed, and the Tyger T3's 5-year warranty makes it the sensible under-$250 choice.\n\nOnce the bed is covered, many Ranger owners add a bed rack for bikes and camping gear or a trailer hitch upgrade, and the cab benefits from laser-fit floor liners. If you drive the newer truck, see the 2024–2026 Ranger guide. The vehicle hub lists every fit-checked accessory for your Ranger.",
 },
 "sources": [
  ["BAKFlip MX4 448332 (RealTruck)", "https://realtruck.com/p/bakflip-mx4-tonneau-cover/bak-448332/"],
  ["RetraxPRO MX 80335 (RealTruck)", "https://realtruck.com/p/retraxpro-mx-tonneau-cover/rtx-80335/"],
  ["Gator EFX GC24022 (RealTruck)", "https://realtruck.com/p/gator-efx-hard-fold-tonneau-cover/guc-gc24022/"],
  ["TruXedo Lo Pro 531001 (RealTruck)", "https://realtruck.com/p/truxedo-lo-pro-tonneau-cover/trx-531001/"],
  ["UnderCover SE UC2186 (RealTruck)", "https://realtruck.com/p/undercover-se-tonneau-cover/udc-uc2186/"],
  ["Tyger T3 TG-BC3F1066 (Tyger Auto)", "https://www.tygerauto.com/tonneau-cover/tyger-t3-soft-trifold/tg-bc3f1066/tyger-t3-soft-tri-fold-fit-2019-2023-ford-ranger-5-bed.html"],
  ["Retrax ONE vs PRO, MX vs XR (Rack Attack)", "https://rackattack.com/retrax-tonneau-cover-review-one-pro-mx-xr-guide"],
  ["Ford Ranger (T6) — North American model (Wikipedia)", "https://en.wikipedia.org/wiki/Ford_Ranger_(T6)"],
  ["Non-leaking tonneau cover recommendations (Ranger5G)", "https://www.ranger5g.com/forum/threads/need-recommendations-for-non-leaking-tonneau-cover-avoid-bakflip-g2.3068/"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note)
FITS = [
 ("B07J5CVWGD","BAKFlip MX4 Hard Folding Tonneau Cover 448332, 2019-2023 Ranger 5' 1\" Bed (61 in)","BAK","$1,050–$1,250",{"bed_length_in":61},"5-year warranty; 400 lb rating."),
 ("B07STF6BB9","Gator EFX Hard Tri-Fold Tonneau Cover GC24022, Ford Ranger 5' Bed (61 in)","Gator","$520–$600",{"bed_length_in":61},"RealTruck lists 2019-2023 only; confirm year on listing."),
 ("B07NYT2TKW","RetraxPRO MX Retractable Tonneau Cover 80335, 2019-2023 Ranger 5' 1\" Bed (61 in)","Retrax","$1,900–$2,250",{"bed_length_in":61},"Canister uses ~10-11 in of bed."),
 ("B07N99DFT2","TruXedo Lo Pro Soft Roll-Up Tonneau Cover 531001, 2019-2023 Ranger 5' 1\" Bed (61 in)","TruXedo","$500–$570",{"bed_length_in":61},"Sits 3/4 in above rails."),
 ("B0BHH638DY","Tyger Auto T3 Soft Tri-Fold Tonneau Cover TG-BC3F1066, 2019-2023 Ranger 5' Bed","Tyger Auto","$210–$250",{"bed_length_in":61},"Over-rail bedliners need small holes cut."),
 ("B088Q8YM6K","UnderCover SE One-Piece Tonneau Cover UC2186, 2019-2023 Ranger 5' 1\" Bed (61 in)","UnderCover","$1,250–$1,400",{"bed_length_in":61},"No published load rating; about 58 lb."),
 ("B07NXVB15V","RetraxPRO XR Retractable Tonneau Cover T-80335 (T-slot rails), 2019-2023 Ranger 5' 1\" Bed","Retrax","$2,000–$2,400",{"bed_length_in":61},"Rack-ready rails; confirm price on listing."),
 ("B07NYS3MYK","RetraxPRO MX Retractable Tonneau Cover 80336, 2019-2023 Ranger 6' 1\" Bed (72.7 in)","Retrax","$1,950–$2,300",{"bed_length_in":72},"SuperCab 6 ft version; confirm price on listing."),
 ("B07N97MB8F","TruXedo Lo Pro Soft Roll-Up Tonneau Cover 531101, 2019-2023 Ranger 6' 1\" Bed (72.7 in)","TruXedo","$500–$600",{"bed_length_in":72},"SuperCab 6 ft version; confirm price on listing."),
 ("B07SSD1DGZ","Gator EFX Hard Tri-Fold Tonneau Cover GC24023, Ford Ranger 6' 1\" Bed (72.7 in)","Gator","$520–$650",{"bed_length_in":72},"SuperCab 6 ft version; confirm price on listing."),
 ("B088Q9NRFT","UnderCover SE One-Piece Tonneau Cover UC2196, 2019-2023 Ranger 6' 1\" Bed (72.7 in)","UnderCover","$1,250–$1,500",{"bed_length_in":72},"SuperCab 6 ft version; confirm price on listing."),
]
