"""Long-form article — Best Rooftop Cargo Boxes for 2023–2026 Honda Pilot (4th gen).
Mirrors the approved cargo-box pages (RAV4, Telluride). No invented hands-on testing: box specs come from Yakima,
Thule, Rhino-Rack, SportRack and etrailer pages fetched 2026-09-27; vehicle facts from db/migrations/003_vehicles.sql
plus Honda Info Center (rails by trim, 165 lb roof figure) and The Rack Shop. Boxes are universal; the Pilot-specific
part is which trims have rails (Sport, TrailSport, Touring, Elite) vs bare-roof LX/EX-L, the 165 lb roof figure,
crossbar spread and liftgate clearance. Note: 003_vehicles.sql says rails only on TrailSport/Elite; Honda lists four trims.
Source fixes 2026-10-04: box weight range corrected to 38.6–57.2 lb (no box here weighs 31 lb); the reference to a Pilot roof rack page that does not exist was replaced with what to buy for railed and bare-roof trims.
"""

KEY = ("honda", "pilot", "2023-present", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2023–2026 Honda Pilot: 7 Picks for Railed and Bare-Roof Trims"
META = ("Seven Yakima, Thule, Rhino-Rack, INNO and SportRack boxes for the 4th-gen Pilot: which trims have rails, "
        "the 165 lb roof figure, spread and liftgate checks.")

FAQ = [
 ("Which 2023–2026 Honda Pilot trims have roof rails?",
  "Honda's Info Center lists roof rails as standard on the Sport, TrailSport, Touring and Elite for both the 2023 and 2024 Pilot. The LX and EX-L come without rails, so they need a bare-roof crossbar kit that clamps into the door openings before any box can go on. If you have a Black Edition or a later model year, look at the roof: rails that run front to back mean a raised-rail kit, and a smooth roof means a clamp kit. Crossbar listings for this generation often split exactly this way."),
 ("What is the roof weight limit on a 2023–2026 Pilot?",
  "Honda says up to 165 lb of cargo can be carried on the roof rails using accessory crossbars. Treat that as the budget for everything above the rails: crossbars, the box itself and the gear inside. The boxes on this page weigh 38.6 to 57.2 lb, so after a set of bars you usually have roughly 90 to 120 lb for gear. Your owner's manual has the figure for your exact Pilot, and it wins over any crossbar listing that quotes a higher number."),
 ("What size cargo box fits a Honda Pilot?",
  "Most Pilot owners are best served by 15 to 16 cu ft. The Yakima GrandTour 16 (79 in long) and the Rhino-Rack MasterFit 440L (76 in, 15.5 cu ft) suit the roof and leave the liftgate room. A 21 cu ft box such as the Thule Motion 3 XXL fits physically but weighs 57.2 lb, so the 165 lb roof figure runs out before the box is full. The SportRack Vista XL gives 18 cu ft in a short 63 in shell for less money."),
 ("Will a roof box hit the Pilot's power liftgate?",
  "It can if the box is long and mounted too far back. Mount it as far forward as the windshield allows, open the liftgate slowly the first time, and watch the gap at the tail of the box. Thule publishes a front-clearance figure for each box, more than 54 13/16 in for the Motion 3 XXL, which you can measure against your Pilot. If your trim's power liftgate has an adjustable opening height, a lower setting adds margin."),
 ("Can I put a cargo box on a Pilot LX or EX-L?",
  "Yes, once crossbars are on. The LX and EX-L have no factory rails, so raised-rail bars (such as kits listed for the Sport, TrailSport, Touring and Elite) will not mount. You need a bare-roof kit whose feet clamp into the door openings and that is listed for the 2023–2026 Pilot without rails. Check that kit's weight rating and crossbar spread before choosing a box, because clamp kits often have limited spread."),
 ("Do I need Honda's own crossbars for a cargo box?",
  "No. Honda sells accessory crossbars for this Pilot (part 08L04-T90-100), and aftermarket kits from Yakima, Thule and budget brands fit the raised rails too. The Rack Shop lists a Yakima TimberLine kit for the railed 2023–2025 Pilot with a 165 lb rating. A box clamps to any of them, so pick bars on fit, rating, spread and noise. Our Pilot roof rack page lists fit-checked bars."),
 ("How far apart should the crossbars be for these boxes?",
  "Each box publishes its own range. Yakima lists 24–36 in for the GrandTour 16 and 24–35.5 in for the CBX 16. Rhino-Rack gives 620–930 mm (about 24.4–36.6 in) for the MasterFit 440L, etrailer gives 21-13/16 to 36-9/16 in for the Thule Motion 3, and the SportRack Vista XL mounts only at 25-7/8, 27-7/8 or 29-7/8 in. Set your bars inside the range before you lift the box on."),
 ("Can I carry a cargo box and bikes on a Pilot roof?",
  "Only if the box is narrow and the weight works. Full-width boxes such as the CBX 16 and SportRack Vista XL are 38 in wide and fill most of the bars. The Rhino-Rack MasterFit 440L (32 in) and INNO Wedge Plus (33 in) leave a little more room. Add the box, the bike mount, the bike and the cargo, and keep the total under the 165 lb roof figure. For bikes, a hitch rack is often the easier answer on a Pilot."),
 ("Will a roof box fit in my garage with a Pilot?",
  "Measure before the first trip home. The boxes on this page add 13-3/4 in (INNO Wedge Plus), 15 in (CBX 16), about 17 to 18 in (MasterFit 440L, GrandTour 16, Motion 3 XXL) or 19 in (SportRack Vista XL) on top of the crossbars. Measure the Pilot with bars fitted, add the box height, and compare it with your garage door opening. The TrailSport's lifted suspension adds a little height too."),
 ("Is a roof box or a hitch cargo carrier better on a Pilot?",
  "Our fitment data lists a 2 in receiver on the 4th-gen Pilot with a 5,000 lb tow rating on AWD models and 3,500 lb on FWD, so a hitch carrier is a real option for heavy items like coolers and bins. A roof box is better for soft, bulky gear, locks, keeps the rear camera clear and leaves the liftgate usable. Many three-row families use both: the box for bags, the hitch carrier for heavy things."),
]

ARTICLE = {
 "dek": "Seven picks for the fourth-generation Pilot: six rooftop boxes from Yakima, Thule, Rhino-Rack, INNO and SportRack, from a 13 cu ft low-profile box to a 21 cu ft Thule Motion 3 XXL, plus a set of crossbars for railed trims. For each one we list volume, length, weight and crossbar spread, and what those numbers mean for the Pilot's rails, its 165 lb roof figure and its liftgate.",
 "author": "jake-morrison",
 "reviewed": "2026-09-27",
 "method": "We did not mount these boxes ourselves. We ranked them on the makers' published specs (Yakima, Thule, Rhino-Rack and SportRack: volume, exterior dimensions, box weight, load rating, crossbar spread, ski length, warranty), on etrailer's figures for the Thule, INNO and SportRack boxes, on how those specs fit the Pilot's rails, roof figure and liftgate, and on Honda's own feature pages for which trims have rails. Prices were checked on the makers' stores and etrailer in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Check your trim first.** Honda lists roof rails as standard on the Sport, TrailSport, Touring and Elite. The LX and EX-L have a bare roof and need a clamp-style crossbar kit.",
  "**165 lb is the roof budget.** Honda quotes up to 165 lb on the rails with accessory crossbars. Bars, box and gear all count, so a 50 lb box leaves roughly 100 lb for cargo.",
  "**16 cu ft is the sweet spot.** The GrandTour 16 (79 in) and Rhino-Rack MasterFit 440L (76 in, 38.6 lb) hold a three-row family's soft bags without crowding the liftgate.",
  "**Big boxes run out of weight first.** The Thule Motion 3 XXL holds 21 cu ft but weighs 57.2 lb. Pack it with sleeping bags and jackets, not coolers.",
  "**Match spread to the bars.** Yakima's 16s and the MasterFit 440L start near 24 in, the Motion 3 at 21-13/16 in, and the SportRack Vista XL mounts only at three fixed positions.",
 ],
 "top_picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "why": "16 cu ft in 79 in, dual-side opening, 24–36 in spread, $709"},
  {"asin": "B07B4P7WYX", "role": "Lightest 15+ cu ft", "why": "Rhino-Rack MasterFit 440L: 15.5 cu ft, 38.6 lb, 165 lb rating, 5-year warranty"},
  {"asin": "B0F8PNL8H9", "role": "Biggest box", "why": "Thule Motion 3 XXL: 21 cu ft, 215 cm skis; pack it light"},
  {"asin": "B00BCLL8C0", "role": "Best budget", "why": "SportRack Vista XL: 18 cu ft in a 63 in shell for $449.95"},
  {"asin": "B0DNDPCG7W", "role": "Crossbars for railed trims", "why": "Listed for 2023–2026 Sport, TrailSport, Touring and Elite (not LX/EX-L)"},
 ],
 "fit_table": {
  "caption": "2023–2026 Pilot roof setups (what the box mounts to)",
  "head": ["Trim", "Roof", "Crossbars needed", "Box notes"],
  "rows": [
   ["Sport, TrailSport, Touring, Elite", "Raised side rails (standard, per Honda)", "Raised-rail bars listed for these trims (Honda 08L04-T90-100, Yakima TimberLine kit, budget bars)", "Every box here, once bars are set inside its spread range"],
   ["LX, EX-L", "Bare roof, no rails", "Bare-roof clamp kit listed for the Pilot without rails", "Check the clamp kit's spread and rating before choosing a box"],
   ["Black Edition and later years", "Check your roof", "Rails front to back = raised-rail kit; smooth roof = clamp kit", "Same boxes"],
   ["All 2023–2026", "Honda: up to 165 lb on the rails with accessory crossbars", "Weigh the bars", "Bars + box + gear under 165 lb or your manual's figure"],
  ],
 },
 "look_for": [
  {"h": "Rails by trim: Sport and up vs LX and EX-L",
   "body": "The first question on a Pilot is not which box but which roof. Honda's Info Center lists roof rails as standard on the Sport, TrailSport, Touring and Elite for 2023 and 2024, which leaves the LX and EX-L with a bare roof. Railed trims take a raised-rail kit such as Honda's accessory bars, the Yakima TimberLine setup The Rack Shop sells for the 2023–2025 Pilot, or budget bars whose listings name those trims and exclude the LX and EX-L. Bare-roof trims need a clamp kit that hooks into the door openings. Every box on this page mounts to either, once the bars are on."},
  {"h": "The 165 lb roof figure and what is left for gear",
   "body": "Honda says the Pilot can carry up to 165 lb on its rails with accessory crossbars, and The Rack Shop's Yakima kit for railed Pilots carries the same 165 lb rating. Some budget bar listings quote 300 lb, but the lower of the vehicle and bar figures is the one that applies. Everything counts: bars, box and contents. The boxes here weigh 38.6 lb (MasterFit 440L) up to 57.2 lb (Motion 3 XXL), so after a typical set of bars most Pilots have roughly 90 to 120 lb left for cargo. That suits duffels, sleeping bags and strollers; heavy coolers belong inside or on a hitch carrier."},
  {"h": "Box length vs the power liftgate",
   "body": "The Pilot's liftgate swings up toward the back of the roof, so length matters as much as volume. The boxes here run from 63 in (SportRack Vista XL) and 76 in (Rhino-Rack MasterFit 440L) to 79 in (GrandTour 16), 80 in (INNO Wedge Plus), 83 in (CBX 16) and 91.3 in (Thule Motion 3 XXL). Mount any box as far forward as the windshield allows, then open the liftgate slowly and check the gap. Thule lists a front-clearance figure of more than 54 13/16 in for the Motion 3 XXL; measure your Pilot against Thule's hatch-clearance guidance before ordering that one."},
  {"h": "Crossbar spread on the bars you fit",
   "body": "Each box needs its crossbars within a set distance. Yakima gives 24–36 in for the GrandTour 16 and 24–35.5 in for the CBX 16, Rhino-Rack gives 620–930 mm (about 24.4 to 36.6 in) for the MasterFit 440L, and etrailer gives 21-13/16 to 36-9/16 in for the Thule Motion 3. The SportRack Vista XL has three fixed positions, 25-7/8, 27-7/8 and 29-7/8 in. Raised-rail kits on a Pilot can usually be slid to suit, but bare-roof clamp kits on the LX and EX-L sit at fixed points on the door openings, so check that kit's spread first."},
  {"h": "Loading height and garage clearance",
   "body": "The Pilot is a tall midsize SUV, and the TrailSport rides higher still. Dual-side opening boxes let you load from the curb side without standing in the road, and a small step stool helps with the far side of a 38 in wide box. Height is the other check. The boxes here add 13-3/4 in (INNO Wedge Plus), 15 in (CBX 16), about 17 to 18 in (MasterFit 440L, GrandTour 16, Motion 3 XXL) or 19 in (Vista XL) above the bars. Measure the Pilot with bars fitted and add the box height before you pull into a garage or parking structure."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbars", "A kit listed for your trim: raised-rail for Sport and up, clamp kit for LX/EX-L", "Raised-rail bars on a bare-roof LX or EX-L"],
   ["Box weight", "Under 50 lb to save the 165 lb budget for gear (MasterFit 440L: 38.6 lb)", "Heavy boxes that leave little room for cargo"],
   ["Length", "Under about 80 in for the most liftgate room", "A 90 in+ box without measuring the hatch arc"],
   ["Crossbar spread", "A range your bars can meet (most boxes here start between about 22 and 24.4 in)", "Fixed-position boxes on bars that can't move"],
   ["Opening", "Dual-side, so you load from the curb", "Rear-only opening if you park on the street"],
   ["Warranty", "Limited lifetime (Yakima, Thule Motion 3, INNO) or 5 years (Rhino-Rack)", "No warranty stated; ask the seller"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Pilot (makers' published specs; Thule spread, INNO and SportRack figures per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Liftgate / fit guidance"],
  "rows": [
   ["Yakima GrandTour 16", "16 cu ft", "79 × 35 × 18 in", "51.5 lb", "24–36 in", "Mount forward; tallest 16 here"],
   ["Yakima CBX 16", "16 cu ft", "83 × 38 × 15 in", "57 lb", "24–35.5 in", "Low but long and heavy; test the liftgate"],
   ["Rhino-Rack MasterFit 440L", "15.5 cu ft", "76 × 32 × 17 in", "38.6 lb", "620–930 mm (about 24.4–36.6 in)", "Short and light; most weight left for gear"],
   ["INNO Wedge Plus", "13 cu ft", "80 × 33 × 13-3/4 in", "44 lb", "Not published; confirm", "Lowest profile; 110 lb cargo limit"],
   ["Thule Motion 3 XXL", "21 cu ft", "91.3 × 36.2 × 18.1 in", "57.2 lb", "21-13/16 to 36-9/16 in", "Front clearance over 54 13/16 in; pack light"],
   ["SportRack Vista XL", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed at 25-7/8, 27-7/8 or 29-7/8 in", "Shortest; rear-opening lid"],
  ],
 },
 "picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "price": "$709",
   "pros": ["16 cu ft in a 79 in shell that stays clear of the liftgate", "18 in deep for bulky family gear", "24–36 in spread suits raised-rail and clamp kits", "Dual-side opening and SKS locks", "Limited lifetime warranty; made in the USA"],
   "cons": ["51.5 lb takes almost a third of the 165 lb roof figure", "18 in tall, so measure your garage", "Costs more than the budget boxes here"],
   "body": "For a three-row Pilot, the GrandTour 16 is the box that holds the awkward family gear without fighting the liftgate. Yakima lists it at 79 x 35 x 18 in with 16 cu ft, and that deep 18 in shell swallows camp chairs, a folded stroller and soft duffels that won't fit behind the third row. It opens from both sides, so you load from the curb, takes skis and boards up to 185 cm, and comes with SKS locks, a removable torque-limiting knob and a limited lifetime warranty. Yakima builds it in the USA and lists it at $709.\n\nThe fit numbers work well on a Pilot. Its 24–36 in spread covers most raised-rail kits on the Sport, TrailSport, Touring and Elite, and gives a bare-roof clamp kit on an LX or EX-L a good chance of lining up. At 79 in it is shorter than most 16 cu ft boxes, which leaves more room between its tail and the open liftgate. The trade-off is weight: at 51.5 lb, plus the bars, it leaves roughly 100 lb of Honda's 165 lb roof figure for gear. Pack it soft and light, and measure garage clearance, because 18 in is the tallest 16 here.",
   "who": "Pilot families who want one deep, easy-loading 16 cu ft box for road trips.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "79 × 35 × 18 in"], ["Box weight", "51.5 lb"], ["Crossbar spread", "24–36 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS locks included"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B07B4P7WYX", "role": "Lightest 15+ cu ft", "price": "Confirm on listing",
   "pros": ["38.6 lb, the lightest box here with 15+ cu ft", "165 lb rated load, published by Rhino-Rack", "76 in long, clear of the liftgate", "32 in wide, leaving some bar room", "Dual-side opening, three locking points, 5-year warranty"],
   "cons": ["Rhino-Rack's page doesn't list a price", "Heavy Duty bars need the separate RUBK-MF fitting kit", "17 in tall; check your garage"],
   "body": "The Rhino-Rack MasterFit 440L is the box to pick if roof weight is your main worry. Rhino-Rack lists it at 440 L (15.5 cu ft), 76 x 32 x 17 in, and 38.6 lb, with a published 165 lb (75 kg) maximum load, dual-side opening with a key lock, three locking points and a 5-year warranty. That is nearly 13 lb lighter than the GrandTour 16 for only half a cubic foot less space, and on a Pilot those pounds go straight back into your 165 lb roof budget.\n\nThe shape suits the Pilot too. At 76 in it sits well forward of the liftgate, and at 32 in wide it leaves a little crossbar length beside it. Rhino-Rack gives a crossbar spacing of 620 to 930 mm, about 24.4 to 36.6 in, which raised-rail kits on the Sport and up can meet easily; on an LX or EX-L clamp kit, check the spread first. The page says it works directly with Rhino-Rack's Vortex and Euro bars and needs a separate RUBK-MF kit for their Heavy Duty bars, so confirm the mounting hardware suits your crossbar shape on the listing. Rhino-Rack's page doesn't show a price, so compare on the listing.",
   "who": "Pilot owners who want a full-size box and the most weight left for gear.",
   "specs": [["Volume", "440 L / 15.5 cu ft"], ["Exterior", "76 × 32 × 17 in"], ["Box weight", "38.6 lb"], ["Max load", "165 lb (75 kg)"], ["Crossbar spread", "620–930 mm (about 24.4–36.6 in)"], ["Opening", "Dual-side, key lock"], ["Locking points", "3"], ["Warranty", "5 years"]]},
  {"asin": "B0C41RZ4HM", "role": "Low-profile 16, made in USA", "price": "$699",
   "pros": ["16 cu ft at only 15 in tall", "24–35.5 in spread", "Integrated tie-down points inside", "Lid handle locks the box and the mounts; SKS locks", "Made in the USA; limited lifetime warranty"],
   "cons": ["57 lb, one of the heaviest boxes here", "83 in long, so test the liftgate", "Yakima listed it as out of stock when checked"],
   "body": "The Yakima CBX 16 trades weight for height. Yakima lists it at 83 x 38 x 15 in with 16 cu ft, 3 in lower than the GrandTour 16, which helps if your Pilot lives in a garage or you use a low parking structure. It opens from both sides, has integrated tie-down points, fits skis and boards up to 185 cm, and its lid handle locks the gear in and the box to the bars. Yakima says it installs in about 10 minutes, builds it in the USA and lists it at $699 with a limited lifetime warranty, though it showed as out of stock on Yakima's store when we checked.\n\nOn a Pilot, the catch is weight. At 57 lb, plus the bars, it uses a big share of Honda's 165 lb roof figure and leaves roughly 90 lb for gear. It is also 83 in long and 38 in wide, so it fills the bars and reaches further back toward the liftgate than the GrandTour. Mount it forward and open the liftgate slowly the first time. Its 24–35.5 in spread suits most raised-rail kits; on a bare-roof LX or EX-L, confirm the clamp kit's spread first.",
   "who": "Pilot owners who need a low 16 cu ft box for garage clearance and accept the extra weight.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "83 × 38 × 15 in"], ["Box weight", "57 lb"], ["Crossbar spread", "24–35.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Install", "About 10 min"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0B57PG4LR", "role": "Lowest profile", "price": "About $888",
   "pros": ["13-3/4 in tall, the lowest box here", "80 in long with dual-side opening", "Tool-free Memory Mount clamps fit round, square, aero and most factory bars", "44 lb box weight", "Limited lifetime warranty"],
   "cons": ["13 cu ft, the least volume here", "110 lb cargo limit (per etrailer)", "Pricey for its size"],
   "body": "The INNO Wedge Plus is the box for Pilot owners who care most about height. etrailer lists the Wedge Plus at 80 x 33 x 13-3/4 in with 13 cu ft, a 44 lb box weight and a 110 lb cargo capacity. Its Memory Mount clamps go on without tools and fit round, square, aero, elliptical and most factory crossbars, the lid opens from both sides with push-button handles, and the key can't be removed unless the lid is properly closed. INNO backs it with a limited lifetime warranty. etrailer's figures are for the BRM864 version, which the BRM865 in this listing replaces, and etrailer listed it at $888.11.\n\nOn a Pilot, 13-3/4 in of box is about 4 in less than the GrandTour 16, which can be the difference at a garage door, especially on a TrailSport. At 33 in wide it leaves a little room on the bars, and at 80 in it is still short enough to mount forward of the liftgate. The trade-off is space: 13 cu ft holds a family's soft bags for a weekend, not a week. Its 110 lb cargo limit sits comfortably inside the Pilot's 165 lb roof figure once the 44 lb box and bars are counted. Confirm the spread against your bars on the listing.",
   "who": "Pilot owners who park in a low garage and pack light.",
   "specs": [["Volume", "13 cu ft"], ["Exterior", "80 × 33 × 13-3/4 in (etrailer)"], ["Box weight", "44 lb"], ["Max load", "110 lb"], ["Mount", "Memory Mount, tool-free"], ["Opening", "Dual-side"], ["Crossbar spread", "Not published; confirm"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0F8PNL8H9", "role": "Biggest box", "price": "$1,249.95 (box alone)",
   "pros": ["21 cu ft, the most volume here", "Skis up to 215 cm, 5–7 pairs", "21-13/16 to 36-9/16 in spread (etrailer)", "Dual-side one-hand opening, PowerClick mounts, SlideLock", "Thule rates it for 165 lb; limited lifetime warranty per etrailer"],
   "cons": ["57.2 lb box weight", "91.3 in long; Thule lists front clearance over 54 13/16 in", "This Amazon listing bundles GoPack duffels, so it costs more than the box alone"],
   "body": "When a Pilot is carrying eight people for a week, the Thule Motion 3 XXL is the box that holds their gear. Thule lists it at 21 cu ft with exterior dimensions of 91.3 x 36.2 x 18.1 in, a 57.2 lb box weight and a 165 lb maximum load. It takes skis up to 215 cm, opens from both sides with one hand, locks with SlideLock and clamps on with PowerClick mounts that click at the right torque. etrailer lists a crossbar spread of 21-13/16 to 36-9/16 in and a limited lifetime warranty. Thule lists the box alone at $1,249.95; this Amazon listing bundles it with a GoPack duffel set, so compare it with the box-only price.\n\nThe Pilot's roof figure is the limit here, not the box. Honda quotes 165 lb, and the 57.2 lb box plus bars leaves roughly 90 lb for gear, so fill it with sleeping bags, jackets and soft duffels. Length is the second check. Thule gives a front-clearance figure of more than 54 13/16 in for this box, so measure your Pilot against Thule's hatch-clearance guidance, mount it well forward and open the liftgate slowly the first time.",
   "who": "Big families and ski crews who need the most volume and will pack it light.",
   "specs": [["Volume", "21 cu ft"], ["Exterior", "91.3 × 36.2 × 18.1 in"], ["Box weight", "57.2 lb"], ["Max load", "165 lb"], ["Crossbar spread", "21-13/16 to 36-9/16 in (etrailer)"], ["Ski length", "Up to 215 cm"], ["Front clearance", "Over 54 13/16 in (Thule)"], ["Warranty", "Limited lifetime (etrailer)"]]},
  {"asin": "B00BCLL8C0", "role": "Best budget", "price": "$449.95",
   "pros": ["18 cu ft for $449.95 at SportRack", "63 in long, the shortest box here", "Tool-free mounting hardware and a lock", "Fits square, round and most factory bars, per SportRack", "Rear opening keeps you out of traffic"],
   "cons": ["Fixed mounting positions only", "38 in wide and 19 in tall, the tallest box here", "Box weight, load rating and warranty terms not published; confirm"],
   "body": "The SportRack Vista XL is the budget way to add a lot of space to a Pilot. SportRack lists the SR7018 at 63 x 38 x 19 in with 18 cu ft, UV-resistant ABS, tool-free mounting hardware and a lock, for $449.95, and says it fits SportRack racks, square bars, round bars and most factory racks. Short and wide instead of long and narrow, it holds more than any 16 cu ft box here while sitting far forward of the liftgate.\n\nThree things need checking. First, etrailer gives three fixed mounting positions, 25-7/8, 27-7/8 and 29-7/8 in center to center, so your bars must sit on one of them; that is easy with sliding raised-rail bars on a Sport or TrailSport and less certain with a clamp kit on an LX or EX-L. Second, the lid opens at the rear, so you reach up and over the back of the roof to load it, and a step stool helps on a tall SUV. Third, SportRack doesn't publish a box weight, load rating or warranty terms, so confirm them on the listing before planning a load against the 165 lb roof figure. At 19 in tall, measure your garage too.",
   "who": "Budget buyers who want big, short, lockable space and don't mind loading from the rear.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "63 × 38 × 19 in"], ["Opening", "Rear"], ["Mounting positions", "25-7/8, 27-7/8 or 29-7/8 in (etrailer)"], ["Hardware", "Tool-free; lock included"], ["Material", "UV-resistant ABS"], ["Box weight / max load", "Not published; confirm"], ["Price", "$449.95 (SportRack)"]]},
  {"asin": "B0DNDPCG7W", "role": "Crossbars for railed trims", "price": "Confirm on listing",
   "pros": ["Listing names 2023–2026 Pilot Sport, TrailSport, Touring and Elite", "Explicitly excludes LX and EX-L, which lowers the risk of a wrong order", "Adjustable aluminum bars", "Anti-theft locks", "Much cheaper than a Yakima or Thule kit"],
   "cons": ["The 300 lb figure in the title is the bar claim; the Pilot's 165 lb roof figure still applies", "No maker spec sheet to check spread or bar weight; confirm", "Won't fit bare-roof LX or EX-L"],
   "body": "Every box on this page needs crossbars, and on a railed Pilot these budget bars are the cheapest route. The listing title names the 2023–2026 Pilot Sport, TrailSport, Touring and Elite and states that they are not for the LX and EX-L, which matches Honda's list of trims with standard rails. They are adjustable aluminum bars with anti-theft locks. For a brand-name kit, Honda sells accessory crossbars (08L04-T90-100) and The Rack Shop lists a Yakima TimberLine setup for the railed 2023–2025 Pilot at $503.90 on sale, with a 165 lb rating and a 40 in fairing size.\n\nTwo cautions. The title quotes a 300 lb load, but that is a bar claim; Honda's 165 lb figure for the roof rails is the number to plan around, and it covers bars, box and gear. There is also no maker spec sheet for these bars, so confirm the bar weight, the bar length and how far apart they can be set against your box's spread range before ordering. If you have an LX or EX-L, skip these and buy a bare-roof clamp kit listed for the Pilot without rails.",
   "who": "Sport, TrailSport, Touring and Elite owners who need bars before a box and want to spend less.",
   "specs": [["Fits (per listing)", "2023–2026 Pilot Sport, TrailSport, Touring, Elite"], ["Not for", "LX, EX-L"], ["Material", "Aluminum"], ["Lock", "Anti-theft"], ["Listed load", "300 lb (bar claim)"], ["Roof figure", "165 lb (Honda)"], ["Spread / bar weight", "Not published; confirm"]]},
 ],
 "install": [
  "Fit crossbars for your roof: raised-rail bars on the Sport, TrailSport, Touring or Elite, a bare-roof clamp kit on the LX or EX-L. Torque them to the maker's spec.",
  "Set the bar spread inside the box's range (24–36 in for the GrandTour 16, about 24.4–36.6 in for the MasterFit 440L, or one of the Vista XL's fixed positions).",
  "With a helper and a step stool, lift the box on, center it side to side and slide it forward, keeping it clear of the antenna and any sunroof opening.",
  "Fit the clamps loosely, open the liftgate slowly and check the gap at the tail of the box, then tighten the clamps to the box maker's instructions.",
  "Lock the box and mounts, rock it from each corner, and re-check the clamps after the first drive.",
  "Load heavy items low and between the bars, and keep bars + box + gear under Honda's 165 lb figure. With a 51.5 lb GrandTour 16 on the bars, that leaves roughly 100 lb for cargo.",
 ],
 "avoid": [
  {"h": "Raised-rail bars on an LX or EX-L", "body": "Those trims have no rails. Buy a clamp kit listed for the Pilot without rails; listings for railed trims say so."},
  {"h": "Planning around a bar's 300 lb claim", "body": "Honda quotes 165 lb for the roof rails with accessory crossbars. The lower figure applies to bars, box and gear together."},
  {"h": "A long box without checking the liftgate", "body": "Boxes over 80 in reach toward the liftgate's arc. Mount forward and open the liftgate slowly the first time."},
  {"h": "Filling a 21 cu ft box to the lid", "body": "The Motion 3 XXL holds far more than the roof figure allows once its 57.2 lb and the bars are counted. Pack it with light, bulky gear."},
 ],
 "verdict": {
  "thesis": "Get the right crossbars for your trim, then choose the Yakima GrandTour 16 for most Pilot families, the Rhino-Rack MasterFit 440L if weight matters most, or the SportRack Vista XL on a budget.",
  "body": "On the fourth-gen Pilot, the roof sets two rules: Sport and up have rails while the LX and EX-L don't, and Honda's 165 lb figure covers bars, box and gear together. The GrandTour 16 fits those rules best for most families, with 16 cu ft in a 79 in shell and a 24–36 in spread that suits most bar kits. The Rhino-Rack MasterFit 440L gives nearly the same space at 38.6 lb, leaving the most weight for gear. The CBX 16 and INNO Wedge Plus are the low-profile choices for tight garages, the Thule Motion 3 XXL is the big box for a full crew packed light, and the SportRack Vista XL gives 18 cu ft for $449.95 if rear loading is acceptable.\n\nStart with the bars: a raised-rail kit for the railed trims or a door-frame clamp kit for the bare-roof LX and EX-L, confirmed in the maker's fit guide. For heavy gear, the Pilot's 2 in trailer hitch takes a hitch cargo carrier, and a set of all-weather floor liners protects the cabin from the wet gear that comes out of the box. The vehicle hub lists every fit-checked accessory for your Pilot.",
 },
 "sources": [
  ["2023 Pilot roof rails, trims and 165 lb figure (Honda Info Center)", "https://www.hondainfocenter.com/2023/Pilot/Feature-Guide/Exterior-Features/Roof-Rails/"],
  ["2024 Pilot roof rails (Honda Info Center)", "https://www.hondainfocenter.com/2024/Pilot/Feature-Guide/Exterior-Features/Roof-Rails/"],
  ["Yakima TimberLine rack for 2023–2025 Pilot with raised rails (The Rack Shop)", "https://therackshop.com/2023-2025-honda-pilot-w-raised-rails-yakima-crossbar-complete-roof-rack/"],
  ["Honda Pilot cross bars 08L04-T90-100 (Honda Automotive Parts)", "https://www.hondaautomotiveparts.com/oem-parts/honda-cross-bars-8l04t90100"],
  ["Yakima GrandTour 16 (Yakima)", "https://yakima.com/products/grandtour-16"],
  ["Yakima CBX 16 (Yakima)", "https://yakima.com/products/cbx-16"],
  ["Rhino-Rack MasterFit Roof Box 440L (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-racks/roof-boxes/roof-boxes/masterfit-roof-box-440l-black-_rmft440"],
  ["INNO Wedge Plus 13 cu ft (etrailer)", "https://www.etrailer.com/Roof-Box/Inno/INBRM864MBK.html"],
  ["Thule Motion 3 XXL (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-motion-3-xxl-_-639950"],
  ["Thule Motion 3 spread and warranty (etrailer)", "https://www.etrailer.com/Roof-Box/Thule/TH59PN.html"],
  ["SportRack Vista XL (SportRack)", "https://www.sportrack.com/product/vista-xl-cargo-box/"],
  ["SportRack Vista XL mounting positions (etrailer)", "https://www.etrailer.com/question-156482.html"],
 ],
}

# Product list for this page (boxes + bars for railed trims). (asin, name, brand, band, cond, note)
FITS = [
 ("B083KP48XC","Yakima GrandTour 16 Premium Rooftop Cargo Box, 16 cu ft, dual-side opening (79 in long)","Yakima","$700–$900",{},"Universal box; needs crossbars (24-36 in spread). Confirm liftgate gap."),
 ("B07B4P7WYX","Rhino-Rack MasterFit Roof Box 440L (15.5 cu ft), Black","Rhino-Rack","See listing",{},"Universal box, 38.6 lb; confirm mounting kit suits your bars."),
 ("B0C41RZ4HM","Yakima CBX 16 Aerodynamic Rooftop Cargo Box for Cars, Wagons and SUVs","Yakima","$650–$800",{},"Universal box, 83 in long; confirm liftgate gap and spread."),
 ("B0B57PG4LR","INNO Wedge Plus 865 Cargo Box, 13 cu ft, Matte Black","INNO","$800–$950",{},"Universal low-profile box; confirm crossbar spread on the listing."),
 ("B0F8PNL8H9","Thule Motion 3 XXL 21 cu ft Rooftop Cargo Box with GoPack Duffel Set, 165 lb load capacity","Thule","$1,200–$1,500",{},"Bundle listing; 91.3 in long, confirm front clearance on your Pilot."),
 ("B00BCLL8C0","SportRack Vista XL Rear Opening Cargo Box, 18 cu ft, Black","SportRack","$400–$500",{},"Fixed mounting positions; confirm box weight and load rating on the listing."),
 ("B0DNDPCG7W","Roof Rack Cross Bars for Honda Pilot 2023-2026 Sport TrailSport Touring Elite (Not for LX & EX-L)","Generic","See listing",{"roof_type":"raised-rails"},"Railed trims only; confirm spread and bar weight."),
]
