"""Long-form article — Best Roof Racks / Crossbars for the 2023–2026 Honda Pilot (4th gen).
Mirrors the approved pilot (ford_f150_2021_tonneau.py) and the CR-V / Highlander / Tahoe roof-rack pages.
No invented hands-on testing: vehicle facts come from Honda Info Center's 2023 Pilot roof rails page ("Standard on
Sport, TrailSport, Touring and Elite"; "up to 165 pounds of cargo can be carried" with accessory crossbars), Honda's
Pilot page showing the 2026 trims (Roof Rails listed on Sport, TrailSport, Touring, Touring Blackout, Elite and Black
Edition as we read it, not on the EX-L), Wikipedia (2023 model year, LX dropped for 2025, 2026 refresh), etrailer's 2023
and 2024 Pilot roof pages ("Factory installed raised rails that run front to back"; the 2023 page also lists a "No
existing rails or crossbars" roof), The Rack Shop's 2023–2025 Pilot Yakima TimberLine kit (165 lb, 50 in max spread,
$503.90), Bernardi Parts' page for Honda crossbars 08L04-T90-100 (165 lb, $261 list, $221.85 sale) and ASG Auto
Sports' BRIGHTLINES Pilot page ($124.99, 154 lb, preset holes in the rails), all opened 2026-10-05. Amazon picks are
identified by listing titles read in amazon.com search results on 2026-10-05; amazon.com pages cannot be fetched, so
each pick says which facts come from the title only. No Thule, Yakima or Honda-genuine listing whose Amazon title
names the 2023+ Pilot was found, so those systems are described from etrailer, The Rack Shop and Bernardi Parts and
are not picks. No platform or basket listing titled for this Pilot was found. The crossbar listing B0DNDPCG7W already
belongs to the Pilot cargo box guide and is deliberately not used here.
Not verified, and worded as such: a Honda roof figure for the bare-roof LX and EX-L; bar ratings, locks, weights,
spread and warranty for any Amazon set beyond what its title or a retailer page says; 2027 fit of any part.
"""

KEY = ("honda", "pilot", "2023-present", "roof-racks")

TITLE = "Best Roof Racks & Crossbars for 2023–2026 Honda Pilot: 6 Picks for Raised Rails and Bare Roofs"
META = ("Six crossbar sets for the 4th-gen Pilot: bolt-on and clamp bars for the raised rails on Sport and up, "
        "a door-frame kit for the bare LX and EX-L, and the 165 lb rule.")

FAQ = [
 ("Which 2023–2026 Honda Pilot trims have roof rails?",
  "Honda's Info Center lists roof rails as standard on the Sport, TrailSport, Touring and Elite for the 2023 Pilot, which leaves the LX and EX-L with a bare roof. Honda's current Pilot page, showing the 2026 lineup, lists Roof Rails on the Sport, TrailSport, Touring, Touring Blackout, Elite and Black Edition as we read it, and not on the EX-L. Wikipedia notes that the LX was dropped for 2025 and the Black Edition added that year. So for every model year the rule is the same: the EX-L, and the LX through 2024, are bare; everything else has rails. Look at the roof before you shop. Rails that run front to back take rail-mounted bars, and a smooth roof takes a door-frame clamp kit."),
 ("Are the Pilot's roof rails raised or flush?",
  "Raised. etrailer's roof pages for the 2023 and 2024 Pilot describe the railed roof as \"Factory installed raised rails that run front to back\", and The Rack Shop sells its Yakima TimberLine kit for the \"2023-2025 Honda Pilot (w/raised rails)\". Honda's own Info Center calls them \"large, strengthened roof rails\". A raised rail has a gap underneath, so clamp-style towers such as Yakima's TimberLine wrap around it. Two Amazon titles here say so outright: the Wonderdriver railed set says \"with Raised Side Rails\" and a lockable set says the same. The rails also have preset holes, which is how BRIGHTLINES' replacement bars and Honda's own crossbars attach, according to ASG Auto Sports and Bernardi Parts."),
 ("What crossbars fit a Pilot LX or EX-L with no rails?",
  "A door-frame clamp kit, with feet that sit on the roof edge and hook into the door openings. On Amazon, the Wonderdriver set is titled for the Honda Pilot LX and EX-L, 2023–2026. For a brand-name kit, etrailer lists Yakima BaseLine systems for the 2023 Pilot with \"No existing rails or crossbars\" at $604.75 to $773.75, and a Yakima LockNLoad platform rack on the same feet at $1,243.85. The other route is Honda's own accessory crossbars, which Bernardi Parts says require roof rails, so they do not help a bare-roof trim. Whatever you buy, a clamp kit fixes the bar spread at the door openings, so check the spread range of your cargo box or tent first."),
 ("How much weight can the Pilot roof carry?",
  "Honda's Info Center says \"up to 165 pounds of cargo can be carried\" on the roof rails using accessory crossbars, and Bernardi Parts prints a 165-pound load capacity for Honda's crossbars 08L04-T90-100. The Rack Shop lists 165 lb for its Yakima TimberLine kit on the railed Pilot. Treat 165 lb as the budget for the bars, the carrier and the cargo together while driving. Amazon titles here print 220 lb, 300 lb and 330 lb; those are the sellers' bar claims and do not raise the roof's limit. We found no Honda figure for the bare-roof LX and EX-L, so read your owner's manual for that number, and use the lowest figure you can confirm."),
 ("Do 2016–2022 Pilot crossbars fit the 2023 Pilot?",
  "Don't count on it. The fourth-generation Pilot debuted on November 7, 2022 and went on sale that December as a 2023 model, on Honda's GLTP2 platform shared with the Passport, per Wikipedia. We found no maker fit list that carries a 2016–2022 rack over: The Rack Shop lists its Yakima kit for the 2023–2025 Pilot as its own setup, ASG Auto Sports sells separate BRIGHTLINES sets for the 2016–2022 and the 2023–2026 Pilot, and Bernardi Parts lists Honda's 08L04-T90-100 crossbars for 2023–2026 only. Our 2016–2022 Pilot guides cover the third generation. Buy a listing that names 2023 or later, and if a title spans both generations, ask the seller which fit kit ships."),
 ("Can I buy Honda's own crossbars for the Pilot?",
  "Yes, through a Honda dealer. Bernardi Parts lists Honda Crossbars, part 08L04-T90-100, for the 2023–2026 Pilot at $261.00 list and $221.85 on sale, made of extruded aluminum and Capron resin, with a 165-pound load capacity, and notes that roof rails are required. That is the same 165 lb figure Honda gives for the roof, so the bars and the roof are rated together. We could not find a listing on Amazon whose title names the 2023+ Pilot for the genuine crossbars, so they are not a pick here. If you want the factory look for less, the BRIGHTLINES replacement bars bolt to the same preset holes in the rails, per ASG Auto Sports."),
 ("Are Thule or Yakima racks sold for the 2023–2026 Pilot?",
  "Yes, through rack retailers rather than Amazon. etrailer lists Thule WingBar Evo systems with 53 in bars for the railed 2024 Pilot at $704.85, the SquareBar Evo at $604.85 and the WingBar Edge at $809.80, plus Yakima TimberLine systems from $454.85 (RoundBar) to $623.85 (HD bars) and Inno Aero systems from $596.47. The Rack Shop sells a Yakima TimberLine kit for the 2023–2025 Pilot with raised rails at $503.90 on sale, rated 165 lb, with 60 in bars and a 50 in maximum spread. We found no Thule or Yakima listing on Amazon whose title names this Pilot, so they appear here as retailer options, not picks. Buy them by fit guide, with the kit confirmed for your model year."),
 ("Which Pilot crossbars are lockable?",
  "By title, the Snailfly set (\"with Lock\") and the lockable raised-rail set in our extra listings. The KINGGERI title we read does not say lockable, although its Amazon address does, so check the listing. The BRIGHTLINES, SNIXWOO, PARTOL and Wonderdriver titles do not mention locks, and ASG Auto Sports' BRIGHTLINES page does not either. Honda's crossbars and the Thule and Yakima kits take lock cores sold separately or as options; ask the retailer. If the Pilot sits on the street or at trailheads with bars on, locks are worth the small difference, and lock the carrier too."),
 ("How far apart should Pilot crossbars be?",
  "Set them to what the carrier needs. The Rack Shop lists a 50 in maximum spread for its Yakima TimberLine kit on the railed Pilot, which is far more than a cargo box asks for; the boxes in our Pilot cargo box guide want roughly 24 to 37 in. Clamp-style bars slide along the raised rail, so you can set the spread yourself. Bolt-on bars, such as BRIGHTLINES' replacement set and Honda's own crossbars, go into preset holes, so the spread is fixed by the rail; check it against the box before buying either part. On a bare-roof LX or EX-L, a door-frame kit fixes the spread at the door openings. Keep the rear bar forward of the liftgate's swing."),
 ("Does a 2026 Pilot take the same crossbars as a 2023?",
  "Nothing we read says the roof changed. Wikipedia describes the 2026 refresh, unveiled November 18, 2025, as a new front fascia, a larger grille, a 10.2 in digital cluster and a 12.3 in touchscreen; Honda's 2026 page still lists Roof Rails on the railed trims. Bernardi Parts lists Honda's crossbars for 2023–2026 as one span, and five of the Amazon titles here run 2023–2026. The Rack Shop's Yakima kit and the Wonderdriver railed set stop at 2025, so a 2026 owner should pick a title that names 2026 or ask the seller. For a 2027 Pilot, confirm with the seller; no page we read covers it."),
]

ARTICLE = {
 "dek": "The fourth-generation Pilot has two roofs. Honda lists roof rails on the Sport, TrailSport, Touring and Elite, and on the 2026 Touring Blackout and Black Edition, and leaves the LX and EX-L bare. Here are six crossbar sets matched to each: a bolt-on factory-style set and clamp bars for the raised rails, and a door-frame kit for the bare roof, plus the Honda, Thule and Yakima options Bernardi Parts, etrailer and The Rack Shop list, with the 165 lb rule that decides how much any of them can carry.",
 "author": "jake-morrison",
 "reviewed": "2026-10-05",
 "method": "We did not install these crossbars ourselves. We matched each set to the Pilot roof named in its Amazon listing title (raised rails, or the LX and EX-L bare roof) and checked the vehicle facts against Honda's Info Center and Pilot pages, Wikipedia, etrailer's 2023 and 2024 Pilot roof pages, The Rack Shop's Pilot kit page and Bernardi Parts' page for Honda's crossbars. Amazon product pages cannot be opened by our tools, so where the only spec source is the listing title, we say so. BRIGHTLINES specs and price were read at ASG Auto Sports, and Thule and Yakima prices at etrailer and The Rack Shop, in October 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Roof type follows the trim.** Honda lists rails on the Sport, TrailSport, Touring and Elite (and the 2026 Touring Blackout and Black Edition). The LX and EX-L have a bare roof. Look before you buy.",
  "**The rails are raised, with preset holes.** etrailer calls them factory installed raised rails that run front to back. Clamp bars slide on them; BRIGHTLINES and Honda's own bars bolt into the preset holes.",
  "**165 lb is the roof budget.** Honda quotes up to 165 lb on the rails with accessory crossbars, and its own crossbars are rated 165 lb. Bars, carrier and cargo all count. A 300 lb bar claim changes nothing.",
  "**A bare roof needs a door-frame kit.** The Wonderdriver set is titled for the LX and EX-L; etrailer lists Yakima BaseLine kits for the railless 2023 Pilot from $604.75.",
  "**2016–2022 racks do not carry over.** No maker fit list we read carries them across. Buy a title that names 2023 or later, and confirm 2026 if the title stops at 2025.",
 ],
 "top_picks": [
  {"asin": "B0CM7JY653", "role": "Best overall (raised rails)", "why": "BRIGHTLINES factory-style bars that bolt to the rails' preset holes, with a 154 lb rating and a one-year warranty on a retailer page we could read"},
  {"asin": "B0C556DCZL", "role": "Best OE-style upgrade", "why": "SNIXWOO all-aluminum bars titled as an upgrade from the OE-style cross rails, 220 lb bar claim, 2023–2026"},
  {"asin": "B0FL27BZ6Y", "role": "Best lockable", "why": "Snailfly bars with a lock in the title, 2023–2026, not for the LX and EX-L"},
  {"asin": "B0CRR4KVS9", "role": "Best for the bare roof (LX, EX-L)", "why": "The one Amazon title here that names the Pilot LX and EX-L, the trims without rails"},
  {"asin": "B0CX1DS4K9", "role": "Best trim-named clamp set", "why": "KINGGERI title names the Sport, TrailSport, Touring and Elite for 2023–2026"},
 ],
 "fit_table": {
  "caption": "2023–2026 Pilot roofs (the crossbar must match the roof, not the model year)",
  "head": ["Roof", "Trims", "Crossbars on this page", "Notes"],
  "rows": [
   ["Raised roof rails, preset holes", "Sport, TrailSport, Touring, Elite (Honda Info Center, 2023); plus Touring Blackout and Black Edition on Honda's 2026 page", "BRIGHTLINES (bolt-on), SNIXWOO, KINGGERI, Snailfly, PARTOL", "etrailer: factory installed raised rails front to back. Honda: up to 165 lb with accessory crossbars"],
   ["Bare roof", "LX (2023–2024), EX-L (all years)", "Wonderdriver LX/EX-L door-frame kit", "Or Yakima BaseLine $604.75–$773.75, LockNLoad platform $1,243.85 at etrailer (2023 Pilot, no rails)"],
   ["Honda crossbars 08L04-T90-100", "Any 2023–2026 Pilot with rails", "Dealer part; not on Amazon under this Pilot's name", "Bernardi Parts: $261 list, $221.85 sale, 165 lb, rails required"],
   ["Thule / Yakima / Inno kits", "Railed trims", "Retailer kits, not picks", "etrailer $454.85–$809.80; The Rack Shop Yakima TimberLine $503.90, 165 lb, 50 in max spread"],
   ["2016–2022 Pilot", "Previous generation", "None", "Separate parts at every retailer we read; see our 2016–2022 Pilot guides"],
  ],
 },
 "look_for": [
  {"h": "Rails or bare roof: check the trim, then look up",
   "body": "Honda split this Pilot's roof by trim. The Info Center's 2023 page lists roof rails as standard on the Sport, TrailSport, Touring and Elite and calls them large, strengthened roof rails; the LX and EX-L are not on the list. Honda's current Pilot page, showing the 2026 lineup, lists Roof Rails on the Sport, TrailSport, Touring, Touring Blackout, Elite and Black Edition as we read it, and not on the EX-L. Wikipedia adds that the LX was dropped for 2025, so from that year the EX-L is the only bare-roof trim. The railed trims take any set on this page except the Wonderdriver LX/EX-L kit. The bare trims take only that kit or a retailer door-frame system. A used Pilot may have had dealer rails added, so look at the roof rather than trusting the badge alone."},
  {"h": "Raised rails with preset holes: two ways to mount",
   "body": "etrailer's 2023 and 2024 Pilot pages describe the railed roof as factory installed raised rails that run front to back, and The Rack Shop sells its Yakima kit for the Pilot with raised rails. A raised rail has a gap under it, so clamp-style bars and Yakima's TimberLine towers wrap around the rail and slide to any spread. The rails also carry preset holes. ASG Auto Sports says BRIGHTLINES' replacement bars bolt directly to pre-set holes in the roof side rails, and Honda's own 08L04-T90-100 crossbars require the rails. Bolt-on bars sit at fixed positions and look factory; clamp bars adjust. Either way, compare the foot in the listing photos with your rail before you order, since Amazon pages give us only the title."},
  {"h": "The 165 lb rule, and why a 330 lb bar does not change it",
   "body": "Honda's Info Center says up to 165 pounds of cargo can be carried on the roof rails using accessory crossbars, Bernardi Parts prints a 165-pound load capacity for Honda's crossbars, and The Rack Shop rates its Yakima kit for the railed Pilot at 165 lb. Those figures cover the bars, the carrier and the cargo together while driving. The Amazon titles here claim 220 lb (SNIXWOO, PARTOL), 300 lb (KINGGERI) and 330 lb (Snailfly). Those are bar strength claims. A stiffer bar flexes less under a loaded box; it does not let the Pilot carry more. BRIGHTLINES' 154 lb figure from ASG Auto Sports is the one rating here below Honda's. We found no Honda figure for the bare-roof LX and EX-L, so read the owner's manual and plan to the lowest number you can confirm."},
  {"h": "Spread: sliding clamps, fixed bolt-on bars, fixed door-frame kits",
   "body": "The three mounting styles behave differently once the bars are on. Clamp bars slide along the raised rail, so you set the spread to suit the carrier, up to the 50 in maximum The Rack Shop lists for its Yakima TimberLine kit. Bolt-on bars go into the rails' preset holes, so the spread is whatever the holes give; check that against your carrier before buying BRIGHTLINES or Honda's bars. A door-frame kit on an LX or EX-L puts its feet at the door openings, so the spread is set by the kit and the car. Our Pilot cargo box guide lists each box's range, roughly 24 to 37 in. On every roof the rear limit is the liftgate: keep the rear bar forward of its swing and open it slowly the first time with the carrier mounted."},
  {"h": "Name-brand kits and Honda's own parts",
   "body": "If you want a published fit guide and a lifetime warranty, etrailer lists complete systems for the railed 2024 Pilot: Thule WingBar Evo with 53 in bars at $704.85, SquareBar Evo at $604.85, WingBar Edge at $809.80, Yakima TimberLine from $454.85 with RoundBar to $623.85 with HD bars, and Inno Aero from $596.47. The Rack Shop sells a Yakima TimberLine kit for the 2023–2025 Pilot with raised rails at $503.90 on sale, with 60 in bars, a 165 lb rating and a 50 in maximum spread. For a bare roof, etrailer lists Yakima BaseLine systems for the 2023 Pilot at $604.75 to $773.75. Honda's route is crossbars 08L04-T90-100, $261 list and $221.85 on sale at Bernardi Parts, rated 165 lb. None of these has an Amazon listing titled for this Pilot, so they are options, not picks."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "Title naming the 2023+ Pilot and your roof: \"Sport TrailSport Touring Elite\" or \"Raised Side Rails\" for railed trims, \"LX EX-L\" for the bare roof", "\"Universal\" bars, or a title that doesn't say which roof"],
   ["Mount", "Clamp feet shaped for a raised rail, or bolt-on bars for the preset holes", "Flush-rail or fixed-point kits sold for another SUV"],
   ["Load", "A stated bar rating, and your total under Honda's 165 lb with the bars counted", "Loading to a 300 or 330 lb bar claim"],
   ["Security", "A lock named in the title or on the retailer page", "Hex-key-only feet if you park in public"],
   ["Profile", "Aero aluminum bars with short overhang", "Long square steel bars on a daily driver"],
   ["Year range", "2023–2026, or the year you own", "Assuming 2026 fit from a title that stops at 2025"],
  ],
 },
 "types_table": {
  "caption": "Roof-rack options on the 2023–2026 Pilot (retailer and dealer prices read October 2026)",
  "head": ["Option", "Price guide", "Roof", "Rating (per maker/listing)", "Mount", "Best for"],
  "rows": [
   ["BRIGHTLINES replacement bars (Amazon, ASG Auto Sports)", "$124.99 (ASG)", "Raised rails", "154 lb (ASG)", "Bolts to preset holes", "Factory look, fixed spread"],
   ["Budget clamp bars (Amazon: SNIXWOO, KINGGERI, Snailfly, PARTOL)", "Check listing", "Raised rails", "220–330 lb bar claims", "Clamp on the rail (per titles; confirm)", "Adjustable spread on a budget"],
   ["Budget door-frame kit (Amazon: Wonderdriver LX/EX-L)", "Check listing", "Bare roof", "Not in title", "Door-frame clamps", "LX and EX-L owners on a budget"],
   ["Honda crossbars 08L04-T90-100", "$261 list, $221.85 sale (Bernardi Parts)", "Raised rails", "165 lb", "Rails required (Bernardi)", "Dealer-backed factory part"],
   ["Yakima TimberLine kits", "$454.85–$623.85 (etrailer); $503.90 (The Rack Shop)", "Raised rails", "165 lb (The Rack Shop)", "Towers wrap the rail", "Fit guide, 50 in max spread"],
   ["Thule WingBar Evo / SquareBar Evo / WingBar Edge", "$604.85–$809.80 (etrailer)", "Raised rails", "Not shown on the etrailer roof page", "Thule raised-rail feet", "T-slot accessories, lifetime warranty"],
   ["Yakima BaseLine / LockNLoad platform", "$604.75–$1,243.85 (etrailer, 2023 Pilot)", "Bare roof", "Not shown on the etrailer roof page", "Door-frame clips", "LX and EX-L owners who want a fit guide"],
  ],
 },
 "picks": [
  {"asin": "B0CM7JY653", "role": "Best overall (raised rails)", "price": "$110–$140",
   "pros": ["Bolts directly to the preset holes in the Pilot's roof side rails, per ASG Auto Sports", "154 lb rating evenly distributed, published by ASG", "High-grade aluminum, aerodynamic shape to cut wind noise", "One-year manufacturer warranty with tech support", "Amazon title runs 2023–2026; ASG lists it at $124.99"],
   "cons": ["ASG's fitment text says 2023–2024 while its title and the Amazon title say 2023–2026; confirm a 2025 or 2026 with the seller", "No lock mentioned on the ASG page or in the title", "Fixed spread; check it against your box before buying"],
   "body": "BRIGHTLINES is the pick for owners who want bars that look and mount like Honda's own, for a price a retailer prints. ASG Auto Sports, which sells BRIGHTLINES racks, lists the Pilot 2023–2026 replacement crossbars at $124.99: a pair of high-grade aluminum bars with four mounting towers and hardware, an aerodynamic shape meant to keep wind noise down, a 154 lb rating when the load is evenly spread, and a one-year warranty with tech support. The bars bolt directly to the pre-set holes in the roof side rails, which is the same approach as Honda's 08L04-T90-100 crossbars at $221.85 on sale at Bernardi Parts. The Amazon title names the 2023–2026 Honda Pilot.\n\nTwo cautions from the pages we read. ASG's title says 2023–2026 but its fitment text says 2023–2024, so a 2025 or 2026 owner should get the seller's confirmation in writing; nothing we read suggests the rail changed, but the page is inconsistent. ASG also showed the set as sold out when we read it. Neither ASG nor the Amazon title mentions a lock. The 154 lb rating sits just under Honda's 165 lb roof figure, so plan the load to 154 lb with the bars counted. Because the bars sit in fixed holes, measure the installed spread before you buy a cargo box; our Pilot cargo box guide lists each box's range.",
   "who": "Sport, TrailSport, Touring and Elite owners who want a factory-style bolt-on bar with a rating and a warranty on record, for a fraction of the dealer price.",
   "specs": [["Type", "Bolt-on replacement crossbars, aero aluminum"], ["Fits (per Amazon title)", "2023–2026 Honda Pilot"], ["Fits (per ASG page)", "Title 2023–2026; text 2023–2024; confirm 2025+"], ["Not for", "Bare-roof LX, EX-L"], ["Mount", "Pre-set holes in the roof side rails (ASG)"], ["Load rating", "154 lb evenly distributed (ASG)"], ["Lock", "Not mentioned"], ["Price seen", "$124.99 (ASG Auto Sports)"], ["Warranty", "1 year (ASG)"]]},
  {"asin": "B0C556DCZL", "role": "Best OE-style upgrade", "price": "Check listing",
   "pros": ["Title names the 2023, 2024, 2025 and 2026 Honda Pilot", "All aluminum alloy bars, per the title", "Sold as an upgrade from the OE-style cross rails, so it targets the factory rail", "220 lb bar claim printed in the title, a figure close to the brand-name kits", "SNIXWOO sells a second Pilot listing that names the Elite, Sport, Touring and TrailSport"],
   "cons": ["220 lb is the seller's bar claim; Honda's 165 lb roof figure still applies", "No lock, weight or warranty in the title; no maker page we could open", "How the feet attach is not stated in the title; compare the photos with your rail"],
   "body": "SNIXWOO's set is the one for an owner who wants an all-aluminum bar with a stated number and a title that covers the whole generation. The title names the 2023, 2024, 2025 and 2026 Honda Pilot, calls the bars all aluminum alloy, and sells them as upgraded from the OE-style cross rails, which tells you the seller is targeting the factory raised rails rather than a universal fit. It prints 220 lb, the same figure PARTOL prints and a more modest claim than the 300 and 330 lb on the KINGGERI and Snailfly titles. SNIXWOO's second Pilot listing, in our extra rows, names the Elite, Sport, Touring and TrailSport, which matches Honda's railed trims.\n\nWhat the title does not say, the listing must. There is no lock, no bar weight, no bar length and no warranty in the title, and Amazon pages cannot be opened by our tools, so read those before ordering. The title does not say whether the bars clamp the rail or bolt into its preset holes, so look at the feet in the photos and compare them with your rail. Whatever rating the seller claims, Honda's 165 lb figure covers bars, carrier and cargo together, so a 220 lb bar earns you stiffness, not capacity. If you want a bolt-on bar with a retailer page behind it, BRIGHTLINES is the safer choice; if you want a lock in the title, Snailfly.",
   "who": "Railed-trim owners who want all-aluminum bars with a printed rating and a title that already names 2026.",
   "specs": [["Type", "Aluminum alloy crossbars"], ["Fits (per title)", "2023–2026 Honda Pilot"], ["Not for", "Bare-roof LX, EX-L"], ["Bar rating", "220 lb (per title)"], ["Vehicle limit", "165 lb with accessory crossbars (Honda)"], ["Mount", "Not in title; see listing photos"], ["Lock", "Not in title; see listing"], ["Warranty", "See listing"]]},
  {"asin": "B0CX1DS4K9", "role": "Best trim-named clamp set", "price": "Check listing",
   "pros": ["Title names the Sport, TrailSport, Touring and Elite, Honda's four railed trims for 2023–2024", "Covers 2023–2026 by title", "Aluminum bars, per the title", "300 lb bar claim printed in the title", "KINGGERI sells a second Pilot listing titled lockable, 260 lb, 2023–2025 with raised rails"],
   "cons": ["300 lb is the seller's bar claim, not the roof limit", "The title we read does not say lockable, though the listing's address does; confirm", "No maker page we could open; warranty from the listing only"],
   "body": "KINGGERI's title answers the first question on a Pilot, which trim, by naming the Sport, TrailSport, Touring and Elite for 2023–2026. That is Honda's list of trims with standard roof rails for 2023 and 2024, and it leaves out the LX and EX-L, which is correct. The title calls the bars aluminum roof rails crossbars and prints 300 lb. The 2025 Black Edition and 2026 Touring Blackout are not named, but Honda's 2026 page lists Roof Rails on both, so the rail is the same; ask the seller if you want it in writing.\n\nThe 300 lb needs context. Honda quotes 165 lb on the rails with accessory crossbars and rates its own bars at 165 lb, and The Rack Shop rates its Yakima kit for this roof at 165 lb. A 300 lb bar does not raise that; it only sags less under a loaded box. The title we read does not say lockable, although the listing's web address includes the word, so check the listing before you assume locks. KINGGERI also sells a second Pilot set, in our extra rows, titled lockable and 260 lb with raised rails for 2023–2025, which is the better choice if the bars stay on a car that parks in public. We could not open either Amazon page, so bar length, clamp design and warranty come from the listing; compare the clamp photos with your raised rail and recheck the clamps after the first week.",
   "who": "Railed-trim owners who want the trims named in the title and an adjustable clamp bar at a budget price.",
   "specs": [["Type", "Rail-mounted aluminum crossbars"], ["Fits (per title)", "2023–2026 Pilot Sport, TrailSport, Touring, Elite"], ["Not for", "Bare-roof LX, EX-L"], ["Bar rating", "300 lb (per title)"], ["Vehicle limit", "165 lb with accessory crossbars (Honda)"], ["Lock", "Not in title; address says lockable; confirm"], ["Mount", "Not in title; see listing photos"], ["Warranty", "See listing"]]},
  {"asin": "B0FL27BZ6Y", "role": "Best lockable", "price": "Check listing",
   "pros": ["Lock named in the title", "Title says not for LX and EX-L, matching Honda's bare-roof trims", "Covers 2023–2026 by title", "Aluminum bars; title claims anti-wobble and wind noise reduction", "Snailfly sells rail bars for many SUVs, so it is a known seller rather than an anonymous listing"],
   "cons": ["330 lb is the seller's bar claim, the highest on this page and double Honda's roof figure", "Anti-wobble and noise claims are the seller's, not measured by us", "No maker page we could open; warranty from the listing only"],
   "body": "If the bars will stay on the Pilot, locks matter more than the rating, and Snailfly's title is the one here that names a lock. It is titled for the 2023–2026 Honda Pilot, not for the LX and EX-L, which lines up with Honda's bare-roof trims, and it describes aluminum bars with anti-wobble and wind noise reduction. Snailfly sells similar bars for the CR-V, Highlander and Forester, which we cover in those guides, so you are buying from a seller with a track record rather than a one-off listing. A lock core keeps the bars, and whatever is mounted to them, from leaving with a hex key at a trailhead.\n\nThe 330 lb in the title is the seller's bar claim and the highest on this page. It is double Honda's 165 lb figure for the rails with accessory crossbars, and that lower number is the one that applies to bars, carrier and cargo together. The anti-wobble and noise claims are also the seller's; aero aluminum bars are generally quieter than square steel, but we could not open the Amazon page to read bar shape, weight or warranty, so take those from the listing. Compare the clamp in the photos with your raised rail, confirm the lock is a key core rather than a security screw, and recheck the clamps after the first drive and before every loaded trip.",
   "who": "Railed-trim owners who park on the street or at trailheads and want a lock named in the title.",
   "specs": [["Type", "Lockable rail-mounted aluminum crossbars"], ["Fits (per title)", "2023–2026 Honda Pilot (not LX, EX-L)"], ["Not for", "Bare-roof LX, EX-L"], ["Lock", "Yes (per title)"], ["Bar rating", "330 lb (per title)"], ["Vehicle limit", "165 lb with accessory crossbars (Honda)"], ["Mount", "Not in title; see listing photos"], ["Warranty", "See listing"]]},
  {"asin": "B0CRR4KVS9", "role": "Best for the bare roof (LX, EX-L)", "price": "Check listing",
   "pros": ["The only title here that names the Pilot LX and EX-L, the two trims without rails", "Covers 2023–2026 by title", "Far cheaper than a Yakima BaseLine kit at etrailer", "Wonderdriver also sells a railed-trim Pilot set, so it knows both roofs", "The bars an EX-L needs before any box, bag or bike mount"],
   "cons": ["Short title gives no rating, material, lock or warranty; read the listing", "Door-frame feet fix the spread; check your carrier's range first", "No Honda roof figure for the bare roof; owner's manual is the authority"],
   "body": "A Pilot LX or EX-L has nothing on the roof to clamp to, so it needs a kit whose feet sit on the roof edge and hook into the door openings. Wonderdriver's set is the budget version of that kit, and its title names the Honda Pilot LX and EX-L for 2023–2026, exactly the two trims Honda leaves without rails. Since Wikipedia records the LX as dropped for 2025, the 2025 and 2026 years in the title apply to the EX-L. For a brand-name alternative, etrailer lists Yakima BaseLine systems for the 2023 Pilot with no existing rails or crossbars at $604.75 to $773.75, and a LockNLoad platform rack on the same feet at $1,243.85.\n\nThe title we read is short, so the listing has to tell you the rest: bar material, rating, locks, weight and warranty. Amazon pages cannot be opened by our tools, so read all of them, and confirm you are ordering the LX/EX-L version and not Wonderdriver's railed-trim listing, which is titled for the Elite, Sport, Touring and TrailSport with raised side rails. Two practical points. A door-frame kit fixes the distance between the bars at the door openings, so measure the installed spread before you buy a cargo box, and choose a box with a wide range. And Honda's 165 lb figure is printed for the rails with accessory crossbars; we found no figure for the bare roof, so take the limit from your owner's manual and the kit's own rating, whichever is lower.",
   "who": "LX and EX-L owners who need bars for a bare roof and will not pay for a Yakima BaseLine kit.",
   "specs": [["Type", "Door-frame clamp crossbars"], ["Fits (per title)", "2023–2026 Honda Pilot LX, EX-L"], ["Not for", "Railed trims (Sport, TrailSport, Touring, Elite and up)"], ["Bar rating", "Not in title; see listing"], ["Vehicle limit", "Owner's manual (no Honda figure read for the bare roof)"], ["Spread", "Fixed by the feet; measure before buying a box"], ["Lock", "Not in title; see listing"], ["Warranty", "See listing"]]},
  {"asin": "B0CSK8CXLP", "role": "Best budget (raised rails)", "price": "Check listing",
   "pros": ["Title names the 2023–2026 Honda Pilot", "220 lb bar claim printed in the title", "PARTOL sells vehicle-specific bars for many SUVs", "Simple rail bar for cargo bags, skis and a bike tray", "Usually among the lowest price bands for a named-brand rail set"],
   "cons": ["Short title does not name trims or the rail; confirm it needs rails on the listing", "No lock in the title", "No maker page we could open; warranty from the listing only"],
   "body": "PARTOL's set is the plain rail bar for an owner who needs bars a few times a year and wants to spend as little as possible. The title names the 2023–2026 Honda Pilot and prints 220 lb, the same figure SNIXWOO prints and well under the 300 and 330 lb claims elsewhere on this page. PARTOL sells vehicle-specific crossbars for a long list of SUVs, so it is a known budget brand rather than an anonymous seller, and a 220 lb aluminum bar is plenty for a soft cargo bag, a pair of ski carriers or one bike tray.\n\nThe title is short, and that is the trade-off. It does not name the trims, and it does not say raised side rails the way the Wonderdriver and lockable sets do, so confirm on the listing that it mounts to the factory rails and is not for the bare-roof LX and EX-L. It does not mention a lock, bar length or warranty either; read the listing for all three. Honda's 165 lb figure for the rails with accessory crossbars is the number to plan around, bars included, whatever the title claims. For a loaded cargo box on long trips, BRIGHTLINES' bolt-on bars or a Yakima TimberLine kit from The Rack Shop at $503.90 is the stiffer, better-documented choice. For light loads a few times a year, this one does the job if you check the clamps after the first drive.",
   "who": "Budget buyers with a railed Pilot who carry light loads a few times a year and will read the listing for the details.",
   "specs": [["Type", "Rail-mounted crossbars"], ["Fits (per title)", "2023–2026 Honda Pilot"], ["Roof", "Rails assumed; confirm on listing"], ["Bar rating", "220 lb (per title)"], ["Vehicle limit", "165 lb with accessory crossbars (Honda)"], ["Lock", "Not in title; see listing"], ["Mount", "Not in title; see listing photos"], ["Warranty", "See listing"]]},
 ],
 "install": [
  "Identify your roof: raised rails that run front to back (Sport, TrailSport, Touring, Elite, Touring Blackout, Black Edition) or a smooth roof (LX, EX-L). Rails take rail-mounted bars; a bare roof takes a door-frame kit.",
  "Clean the rails or the roof edge where the feet will sit so they grip paint and rail, not grit, and remove any stickers or dealer rail caps that cover the preset holes.",
  "Bolt-on bars (BRIGHTLINES, Honda): line the towers up with the preset holes in the rails and fit the hardware loosely. Clamp bars: set both bars loosely on the rails. Door-frame kit: set each foot at the position the instructions give and hook the clamps into the door openings with the doors open.",
  "Space the bars to your carrier's range (clamp bars slide; bolt-on and door-frame feet do not), keeping the rear bar forward of the liftgate's swing.",
  "Center the bars so the overhang is equal on both sides, then tighten the feet evenly, alternating sides, to the torque the instructions give.",
  "Open the liftgate fully to check clearance, lock the feet if your set has locks, and drive a short loop.",
  "Re-tighten after the first drive, recheck after the first week, and check again before every loaded trip. Keep bars, carrier and cargo under Honda's 165 lb figure.",
 ],
 "avoid": [
  {"h": "Rail bars on an LX or EX-L", "body": "Those trims have nothing to clamp to. Buy a door-frame kit titled for the Pilot LX and EX-L, or a Yakima BaseLine system from a rack retailer."},
  {"h": "Flush-rail or fixed-point kits sold for another SUV", "body": "etrailer lists the Pilot's rails as raised. Feet shaped for a flush rail or a fixed point have no gap to wrap and no hole to use."},
  {"h": "Loading to the bar claim", "body": "220, 300 and 330 lb are sellers' bar ratings. Honda quotes 165 lb on the rails with accessory crossbars, and that covers bars, carrier and cargo."},
  {"h": "A 2016–2022 Pilot part, or a 2025 title on a 2026", "body": "The 2023 Pilot is a new generation, and every retailer we read sells it separate parts. If a title stops at 2025, ask the seller before buying for a 2026."},
 ],
 "verdict": {
  "thesis": "Match the roof: BRIGHTLINES' bolt-on bars or the KINGGERI, SNIXWOO and Snailfly clamp sets for the raised rails on Sport and up, the Wonderdriver LX/EX-L kit for a bare roof, and a Yakima or Thule kit from a rack retailer if you want a fit guide and a lifetime warranty on either.",
  "body": "The best Pilot crossbar is the one sold for your roof. Sport, TrailSport, Touring, Elite, Touring Blackout and Black Edition owners have raised rails with preset holes and should buy rail bars: BRIGHTLINES for a factory-style bolt-on set with a 154 lb rating and a price ASG Auto Sports prints, SNIXWOO for all-aluminum bars with a modest 220 lb claim, KINGGERI for the trims in the title, Snailfly for a lock, and PARTOL on a budget. LX and EX-L owners have a bare roof and need the Wonderdriver door-frame kit or a Yakima BaseLine system from etrailer. For a dealer part, Honda's 08L04-T90-100 crossbars are $221.85 on sale at Bernardi Parts and rated 165 lb. Whatever you buy, Honda's 165 lb figure includes the bars.\n\nWith bars on, a cargo box is the usual next step, and our Pilot cargo box guide lists box lengths and spread ranges for this roof and its liftgate. If the roof is full, or you'd rather keep the bikes low, a trailer hitch with a bike carrier does the job: Honda fits one to the TrailSport at the factory, and the other trims need a dealer or aftermarket receiver first. The vehicle hub lists every fit-checked accessory for the 2023–2026 Pilot.",
 },
 "sources": [
  ["2023 Pilot roof rails: \"Standard on Sport, TrailSport, Touring and Elite\", up to 165 lb with accessory crossbars (Honda Info Center)", "https://www.hondainfocenter.com/2023/Pilot/Feature-Guide/Exterior-Features/Roof-Rails/"],
  ["Honda Pilot, 2026 lineup: Roof Rails by trim, TrailSport towing (Honda)", "https://automobiles.honda.com/pilot"],
  ["Honda Pilot fourth generation: November 2022 debut, 2023 model year, GLTP2 platform, LX dropped for 2025, 2026 refresh (Wikipedia)", "https://en.wikipedia.org/wiki/Honda_Pilot"],
  ["2024 Honda Pilot roof rack systems: \"Factory installed raised rails that run front to back\", Thule, Yakima and Inno prices (etrailer)", "https://www.etrailer.com/roof-2024_Honda_Pilot.htm"],
  ["2023 Honda Pilot roof rack systems: raised rails and \"No existing rails or crossbars\", Yakima BaseLine and LockNLoad prices (etrailer)", "https://www.etrailer.com/roof-2023_Honda_Pilot.htm"],
  ["Yakima TimberLine rack for 2023–2025 Honda Pilot w/raised rails, 165 lb, 50 in max spread, $503.90 (The Rack Shop)", "https://therackshop.com/2023-2025-honda-pilot-w-raised-rails-yakima-crossbar-complete-roof-rack/"],
  ["Honda Crossbars 08L04-T90-100, 2023–2026 Pilot, 165 lb, extruded aluminum and Capron resin, $261 list, $221.85 sale, roof rails required (Bernardi Parts)", "https://www.bernardiparts.com/Products/Honda-Crossbars-(Pilot-2023-2026)__08L04-T90-100.aspx"],
  ["BRIGHTLINES roof rack crossbars replacement for Honda Pilot 2023–2026, $124.99, 154 lb, pre-set holes in the rails, 1-year warranty (ASG Auto Sports)", "https://www.asgautosports.com/products/brightlines-roof-rack-crossbars-replacement-for-honda-pilot-2023-2025"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note) — picks first, then extra verified listings.
# roof_type follows the vehicle row and the Pilot cargo box guide: raised-rails (etrailer: "Factory installed raised
# rails that run front to back") for rail-mounted sets, bare for the LX/EX-L door-frame kit. Titles were read in
# amazon.com search results on 2026-10-05; amazon.com pages cannot be fetched.
FITS = [
 ("B0CM7JY653","BRIGHTLINES Roof Racks Cross Bars Replacement for 2023-2026 Honda Pilot","BRIGHTLINES","$110–$140",{"roof_type":"raised-rails"},"Bolts to preset holes in the rails; ASG Auto Sports $124.99, 154 lb. Confirm 2025-2026 with seller."),
 ("B0C556DCZL","SNIXWOO Enhanced 220 LBS Roof Racks for 2023 2024 2025 2026 Honda Pilot, All Aluminum Alloy Cross Bars, Upgraded from the OE-Style Cross Rails","SNIXWOO","Check listing",{"roof_type":"raised-rails"},"220 lb is the bar claim; load to Honda's 165 lb. Confirm mount and locks on listing."),
 ("B0CX1DS4K9","KINGGERI 300lbs Roof Rack Cross Bars for Honda Pilot 2023-2026 Sport TrailSport Touring Elite, Aluminum","KINGGERI","Check listing",{"roof_type":"raised-rails"},"Railed trims only; 300 lb is the bar claim. Confirm locks on listing."),
 ("B0FL27BZ6Y","Snailfly Aluminum Roof Rack Cross Bars with Lock for 2023-2026 Honda Pilot (Not for LX, EX-L), 330lbs","Snailfly","Check listing",{"roof_type":"raised-rails"},"Lock in title; 330 lb is the bar claim. Confirm clamp against your rail."),
 ("B0CRR4KVS9","Wonderdriver Roof Rack Cross Bars for Honda Pilot LX EX-L 2023-2026","Wonderdriver","Check listing",{"roof_type":"bare"},"Door-frame kit for bare-roof LX/EX-L; confirm rating, spread and locks on listing."),
 ("B0CSK8CXLP","PARTOL 220lbs Roof Rack Cross Bars for 2023-2026 Honda Pilot","PARTOL","Check listing",{"roof_type":"raised-rails"},"Short title; confirm it needs rails and check locks on listing."),
 ("B0CWL6QRZB","Wonderdriver Roof Rack Cross Bars for 2023 2024 2025 Honda Pilot Elite Sport Touring Trailsport (Except LX and EX-L) with Raised Side Rails","Wonderdriver","Check listing",{"roof_type":"raised-rails"},"Title names raised side rails; stops at 2025, confirm 2026 with seller."),
 ("B0FBWRS2FJ","Lockable Roof Rack Cross Bars for Honda Pilot 2023-2026 (with Raised Side Rails), Heavy Duty Aluminum","Generic","Check listing",{"roof_type":"raised-rails"},"Unnamed seller; lockable per title. Confirm rating and warranty on listing."),
 ("B0CT2DT57Z","KINGGERI Lockable 260lbs Roof Rack Cross Bars for Honda Pilot 2023 2024 2025 Sport TrailSport Touring Elite with Raised Rails (Not for LX & EX-L)","KINGGERI","Check listing",{"roof_type":"raised-rails"},"Lockable per title; stops at 2025, confirm 2026 with seller."),
 ("B0CDPSRH9D","SNIXWOO Real All Aluminum Roof Racks for 2023 2024 2025 2026 Honda Pilot, 220LBS, for Pilot Elite Sport Touring Trailsport","SNIXWOO","Check listing",{"roof_type":"raised-rails"},"Second SNIXWOO listing naming the railed trims; confirm differences from #2 on listing."),
 ("B0FHJMGG63","HmmtyRack 300lbs Roof Rack Cross Bars for Honda Pilot 2023-2026 Sport TrailSport Touring Elite (Not for LX & EX-L), Aluminum","HmmtyRack","Check listing",{"roof_type":"raised-rails"},"300 lb is the bar claim; confirm locks and warranty on listing."),
 ("B0D6GSP93H","ERKUL Roof Rack Cross Bars for Honda Pilot 2023-2026","ERKUL","Check listing",{"roof_type":"raised-rails"},"Short title; confirm rails, rating and locks on listing."),
]
