"""Long-form article — Best Floor Mats & Liners for 2023–2026 Honda CR-V (6th gen).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("honda", "cr-v", "2023-present", "floor-mats")

TITLE = "Best Floor Liners for 2023–2026 Honda CR-V: 7 Picks for Gas and Hybrid, With Cargo Deck Notes"
META = ("Seven 6th-gen CR-V floor and cargo liner picks from Husky, HAFIDI, Weize, TTX and budget TPE, with gas vs "
        "hybrid and the upper vs lower cargo deck explained.")

FAQ = [
 ("Do CR-V Hybrid and gas models take the same floor liners?",
  "For the cabin, usually yes. Most cabin sets on this page list both gas and hybrid, including Husky's 99411 and HAFIDI. Cargo liners are where differences show up, because the cargo floor and adjustable deck can differ. Autocessking's cargo kit is listed for the hybrid specifically."),
 ("What does 'upper deck position' mean on a CR-V cargo liner?",
  "Many CR-Vs have an adjustable cargo floor board that sits in an upper or lower position. A cargo liner cut for the upper position lies on the raised floor; one for the lower position sits deeper. Weize, TTX and Husky's 24411 cargo liner are listed for the upper position. Check where your cargo floor sits before ordering."),
 ("Do 2017–2022 CR-V liners fit the 2023+?",
  "No. The 2023 CR-V is a new generation with a new floor. Husky's catalog shows the split: 99401 for 2017–2022 and 99411 for the new car. Buy 2023+ listings."),
 ("Why does Husky's 99411 list 2024–2026?",
  "The listing we found for Husky's WeatherBeater 99411 front and second-row set names 2024–2026, while its front pair (17281) and second-row piece (11491) list 2023 onward, and its 4-piece bundle with cargo lists 2023–2024. The 6th gen started with the 2023 model year. For a 2023, the separate front and second-row pieces or the bundle are the safer Husky orders."),
 ("Do these liners fit the CR-V Sport Touring and TrailSport?",
  "Trim changes powertrain, wheels and trim, not the floor. The Sport and Sport Touring trims are hybrids; the TrailSport (2026) is a trim that also shares the cabin floor. Match gas or hybrid for cargo liners."),
 ("Do CR-V liners fit the Acura RDX or Honda HR-V?",
  "No. Buy liners that name the CR-V and your years. Platform-sharing doesn't mean floor-sharing."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto Honda's retention posts and clear of the pedals at full travel. Remove the factory mat first and heel-test the liner toward the pedals."),
 ("How do I clean them?",
  "Pull them, rinse and scrub with mild soap, and dry before reinstalling. Skip silicone protectants."),
 ("Should I get backrest mats?",
  "If you fold the rear seats to carry bikes or boxes, yes. TTX's set includes backrest mats that protect the carpeted seatbacks when folded."),
 ("How much do CR-V liners cost?",
  "On this page, cabin-only TPE sets run about $80–$120, full sets with cargo about $100–$160, and Husky's WeatherBeater sets about $130–$220. Amazon prices move daily."),
 ("Is WeatherBeater worth it on a CR-V?",
  "In snow country, yes. Husky says WeatherBeater is laser-measured, made in the USA and backed by a lifetime warranty against cracks and breaks, with tall walls that hold snowmelt. In a mild climate, a TPE set with a cargo liner is often the better value."),
 ("Can I buy Husky's CR-V pieces separately?",
  "Yes. Husky lists a WeatherBeater front pair (17281) and second-row piece (11491) for 2023–2026 CR-V including hybrid, and a 24411 cargo liner for the upper cargo position on 2023–2025 models including hybrid. Buying pieces lets you cover a 2023, skip the rear if you rarely carry passengers, or replace one worn piece."),
]

ARTICLE = {
 "dek": "Seven floor and cargo liner picks for the 6th-generation CR-V, from Husky's made-in-USA WeatherBeater to $80 TPE. The cabin fits gas and hybrid alike on most sets; the cargo area is where you need to check powertrain and the upper or lower deck position.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2023–2026 CR-V (gas, hybrid, cargo deck position), on published maker specs (material, origin, warranty) and on coverage in listing photos. Husky claims come from its own site, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Cabin liners usually cover gas and hybrid.** Check the title anyway.",
  "**Cargo is the tricky part.** Upper or lower deck, gas or hybrid.",
  "**2023 was a new generation.** 2017–2022 liners don't fit.",
  "**Husky's year ranges vary by part.** 99411 lists 2024–2026; separate pieces list 2023+.",
  "**Full sets with cargo are strong value.** Weize, TTX and the generic TPE kit.",
 ],
 "top_picks": [
  {"asin": "B0C3XBN5BV", "role": "Best overall", "why": "Husky WeatherBeater 99411, 2024–2026 incl. hybrid, made in USA"},
  {"asin": "B0D43X3Q5G", "role": "Best Husky with cargo", "why": "Husky 4-piece front, 2nd row and cargo, 2023–2024 incl. hybrid"},
  {"asin": "B0BVLYJV8X", "role": "Best cabin TPE", "why": "HAFIDI 1st and 2nd row, CR-V and CR-V Hybrid"},
  {"asin": "B0CWRYCGGY", "role": "Best full set", "why": "Weize floor mats plus upper-position cargo liner"},
  {"asin": "B0DZNG9CHB", "role": "Best with backrest mats", "why": "TTX floor, cargo and backrest mats, gas and hybrid"},
 ],
 "fit_table": {
  "caption": "2023–2026 CR-V: cabin and cargo fit",
  "head": ["Area", "Variable", "Note"],
  "rows": [
   ["Cabin", "Gas or hybrid", "Most sets list both; check title"],
   ["Cargo", "Upper or lower deck position", "Weize, TTX, Husky 24411: upper position"],
   ["Cargo", "Gas or hybrid", "Autocessking cargo kit: hybrid"],
   ["Generation", "2017–2022 vs 2023+", "Not compatible"],
  ],
 },
 "look_for": [
  {"h": "Cabin: gas and hybrid",
   "body": "The 6th-gen CR-V is sold with a 1.5-liter turbo gas engine and as a hybrid. For the cabin floor, most listings on this page cover both: Husky's 99411 and 4-piece bundle include hybrid models, HAFIDI and Sunsdrew name the CR-V and CR-V Hybrid, and the generic TPE and TTX kits list gas and hybrid. Always read the title, but the cabin is rarely the problem on this vehicle."},
  {"h": "Cargo: upper or lower deck",
   "body": "The CR-V's cargo area has an adjustable floor board on many trims, which can sit in an upper or lower position. Cargo liners are cut for one. Weize's and TTX's sets and Husky's 24411 cargo liner are listed for the upper position. Autocessking's kit is listed for the CR-V Hybrid's upper deck. Open the liftgate and check where your floor board sits before ordering. The hybrid's cargo floor can differ from the gas car's, so match powertrain for cargo liners especially."},
  {"h": "Generation and Husky's year ranges",
   "body": "The 2023 CR-V is a new generation, so 2017–2022 liners don't fit. Within the generation, Husky's listings vary: the 99411 front and second-row set lists 2024–2026, its 17281 front and 11491 second-row pieces list 2023 onward, and its 4-piece bundle with cargo lists 2023–2024. For a 2023, choose the pieces or the bundle."},
  {"h": "Warranty and material",
   "body": "Husky says WeatherBeater is laser-measured, designed and made in the USA from ProGard, anchored by StayPut nibs and covered by a lifetime warranty against cracks and breaks. HAFIDI, Sunsdrew, Weize, TTX and the generic kits sell TPE liners and don't publish comparable warranty terms we could check. For a CR-V kept many years in a snowy climate, the warranty is a reasonable tiebreaker."},
  {"h": "Retention and pedal clearance",
   "body": "Honda uses retention posts in the driver footwell. A CR-V-specific liner lines up with them. Seat the driver liner, heel-test it toward the pedals and press the brake and accelerator to the floor. Never stack a liner on the factory mat."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2023+ in the title", "2017–2022 listings"],
   ["Cabin", "Gas and hybrid named", "Titles that don't say"],
   ["Cargo deck", "Upper or lower position named", "Cargo liners that don't say"],
   ["Cargo powertrain", "Hybrid named for hybrids", "Gas cargo liners on a hybrid"],
   ["Retention", "Hook holes for Honda's posts", "Loose mats"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor and cargo protection for the 2023–2026 CR-V",
  "head": ["Type", "Example", "Coverage", "Walls", "Price band", "Best for"],
  "rows": [
   ["USA-made molded liner", "Husky 99411", "Front + 2nd", "High", "$130–$180", "Snow country"],
   ["USA-made bundle", "Husky 4-piece", "Front, 2nd, cargo", "High", "$180–$240", "2023–2024 owners"],
   ["Cabin TPE", "HAFIDI, Sunsdrew", "Front + 2nd", "Medium", "$80–$120", "Value"],
   ["Full TPE set", "Weize, generic, TTX", "Cabin + cargo (+ backrest)", "Medium", "$110–$160", "Families"],
   ["Hybrid cargo kit", "Autocessking", "Cabin + cargo", "Medium", "$100–$140", "Hybrids"],
  ],
 },
 "picks": [
  {"asin": "B0C3XBN5BV", "role": "Best overall", "price": "$130–$180",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs", "Includes hybrid models", "Lists 2024–2026"],
   "cons": ["Title starts at 2024", "Cargo sold separately", "Firm feel"],
   "body": "Husky's WeatherBeater 99411 is a three-piece front and second-row set listed for 2024–2026 CR-V, including hybrid models. Husky says WeatherBeater is laser-measured using vehicle-specific data, designed and made in the USA from ProGard and anchored by StayPut nibs, with a lifetime warranty against cracks and breaks.\n\nFor a CR-V in snow country, the tall, firm walls hold snowmelt that would soak the carpet, and the crack warranty covers the usual cold-weather failure. The hybrid coverage in the title removes a common question.\n\nThe title starts at 2024. For a 2023, Husky's 17281 front and 11491 second-row pieces (both listed from 2023) or the 4-piece bundle are the safer orders. Add Husky's 24411 cargo liner if your cargo floor sits in the upper position.",
   "who": "2024–2026 owners who want the best-documented cabin liners.",
   "specs": [["Part #", "Husky 99411"], ["Pieces", "3"], ["Fits", "2024–2026 CR-V incl. hybrid"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B0D43X3Q5G", "role": "Best Husky with cargo", "price": "$180–$240",
   "pros": ["Front, 2nd row and cargo in one bundle", "Includes hybrid models", "Covers the 2023 launch year", "Made in the USA", "Lifetime warranty against cracks and breaks"],
   "cons": ["Title covers 2023–2024; confirm later years", "Cargo piece is for the adjustable cargo floor; check position", "Most expensive here"],
   "body": "Husky's WeatherBeater 4-piece bundle covers the front and second row plus the cargo area of 2023–2024 CR-V, including hybrid models, with the cargo liner cut for the adjustable cargo floor. It's the Husky option that covers the 2023 launch year and the cargo area in one order.\n\nIt shares WeatherBeater's credentials: laser-measured, made in the USA and a lifetime warranty against cracks and breaks. For a family CR-V that hauls, having the cargo floor covered by the same brand keeps fit and wall height consistent.\n\nFor 2025 and 2026, use the 99411 cabin set plus the 24411 cargo liner, and check your cargo floor position.",
   "who": "2023–2024 owners who want Husky cabin and cargo coverage.",
   "specs": [["Pieces", "4"], ["Covers", "Front, 2nd row, cargo"], ["Fits", "2023–2024 CR-V incl. hybrid"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B0BVLYJV8X", "role": "Best cabin TPE", "price": "$80–$120",
   "pros": ["1st and 2nd row", "Lists CR-V and CR-V Hybrid 2023–2026", "TPE with raised edges", "Low price", "Covers the full generation to date"],
   "cons": ["Cabin only", "No published warranty", "Walls lower than Husky's"],
   "body": "HAFIDI's TPE liners cover the first and second rows of the 2023–2026 CR-V and CR-V Hybrid. The full year range and both powertrains in the title make it an easy budget order.\n\nHAFIDI doesn't publish warranty or material specs we could check. For a CR-V that commutes in a mild climate, it keeps the carpet clean for well under Husky's price. Sunsdrew's cabin set, listed 2023–2025, is a close alternative in our product list.\n\nAdd a cargo liner for your deck position if you haul. Check the listing photos for the driver-side retention holes and a one-piece rear across the hump. On the CR-V's rear floor, a single piece is easier to pull and clean, and it covers the middle where a third passenger's feet land.",
   "who": "Budget buyers who want the cabin covered.",
   "specs": [["Rows", "1st + 2nd"], ["Fits", "2023–2026 CR-V & CR-V Hybrid"], ["Material", "TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$80–$120"]]},
  {"asin": "B0CWRYCGGY", "role": "Best full set", "price": "$110–$150",
   "pros": ["Floor mats plus cargo liner", "Cargo cut for the upper deck position", "Lists 2023–2026 incl. Hybrid", "One order for cabin and cargo", "Raised edges"],
   "cons": ["Upper deck position only", "No published warranty", "Little maker documentation"],
   "body": "Weize's set covers the cabin floor plus a cargo liner for the upper deck position, listed for 2023–2026 CR-V including the Hybrid. For families who haul, getting the cargo liner in the same order is the value.\n\nThe upper-position cut is the thing to check: open the liftgate and see where your cargo floor board sits. If it's in the lower position, this cargo piece won't sit right.\n\nWeize doesn't publish warranty terms we could check. The generic TPE floor-and-cargo kit in our product list, also listing gas and hybrid, is an alternative.",
   "who": "Families with the cargo floor in the upper position.",
   "specs": [["Includes", "Floor mats + cargo liner (upper deck)"], ["Fits", "2023–2026 CR-V incl. Hybrid"], ["Material", "TPE (per listing)"], ["Warranty", "Confirm with seller"], ["Price band", "$110–$150"]]},
  {"asin": "B0DZNG9CHB", "role": "Best with backrest mats", "price": "$120–$160",
   "pros": ["Floor liners, cargo liner and backrest mats", "Lists gas and hybrid", "Upper deck cargo cut", "Protects folded seatbacks", "Lists 2023–2026"],
   "cons": ["Upper deck position only", "No published warranty", "More pieces than some owners need"],
   "body": "TTX Lighting's set covers the cabin floor, the cargo area in the upper deck position and the backs of the rear seats, for 2023–2026 CR-V gas and hybrid. The backrest mats are the difference: if you fold the rear seats for bikes, boxes or a dog crate, they protect the carpeted seatbacks.\n\nLike Weize, the cargo piece is for the upper deck position. TTX doesn't publish warranty terms we could check.\n\nFor owners who use the CR-V as a cargo hauler, it's the most complete kit here.",
   "who": "Owners who fold the rear seats often.",
   "specs": [["Includes", "Floor, cargo (upper deck), backrest"], ["Fits", "2023–2026 CR-V gas & hybrid"], ["Material", "TPE (per listing)"], ["Warranty", "Confirm with seller"], ["Price band", "$120–$160"]]},
  {"asin": "B0CSKR1WZ6", "role": "Budget full set", "price": "$110–$150",
   "pros": ["Floor mats plus cargo liner", "Lists 2023–2026 gas and hybrid", "TPE", "One order", "Raised edges"],
   "cons": ["Generic brand", "Confirm cargo deck position", "No published warranty"],
   "body": "This generic TPE set covers the floor and cargo area of the 2023–2026 CR-V, gas and hybrid. It's a straightforward full-coverage kit.\n\nThe short title doesn't state the cargo deck position, so check the listing photos or ask the seller before ordering. Documentation is thin.\n\nFor a family that wants cabin and cargo covered at a low price, it's a reasonable choice. Before ordering, ask the seller to confirm the cargo deck position and send them a photo if the listing is unclear; it's the one detail on this kit most likely to cause a return.",
   "who": "Budget buyers who want cabin and cargo covered.",
   "specs": [["Includes", "Floor mats + cargo liner"], ["Fits", "2023–2026 CR-V gas & hybrid"], ["Material", "TPE"], ["Cargo deck", "Confirm position"], ["Price band", "$110–$150"]]},
  {"asin": "B0D5QNN1BD", "role": "Best for hybrid cargo", "price": "$100–$140",
   "pros": ["4 pieces including cargo liner", "Cut for the CR-V Hybrid upper deck", "Lists 2023–2025", "Clear hybrid fit", "Budget price"],
   "cons": ["Hybrid only", "Confirm 2026", "No published warranty"],
   "body": "Autocessking's 4-piece set covers the cabin floor and the cargo area of the 2023–2025 CR-V Hybrid, with the cargo liner cut for the upper deck. For hybrid owners, a cargo liner that names the hybrid is the safest cargo purchase.\n\nIt's a budget brand with little documentation. For a 2026, confirm with the seller.\n\nGas owners should pick Weize, TTX or the generic kit instead. If you'd rather have Husky's walls in the cabin, pair Husky's 17281 front and 11491 second-row pieces, which list the hybrid, with this kit's cargo liner.",
   "who": "Hybrid owners who want the cargo area covered.",
   "specs": [["Pieces", "4"], ["Includes", "Floor mats + cargo liner (upper deck)"], ["Fits", "2023–2025 CR-V Hybrid"], ["Material", "All-weather (per listing)"], ["Price band", "$100–$140"]]},
 ],
 "install": [
  "Confirm your CR-V is a 2023+ model and note gas or hybrid.",
  "Open the liftgate and note whether the cargo floor board is in the upper or lower position.",
  "Remove the factory mats and vacuum.",
  "Hook the driver liner onto the retention posts and heel-test it toward the pedals.",
  "Fit the passenger, rear and cargo liners; fold the rear seats and close the liftgate to check clearance.",
  "Press the pedals to the floor before driving.",
 ],
 "avoid": [
  {"h": "2017–2022 liners", "body": "The 2023 CR-V has a new floor."},
  {"h": "Wrong cargo deck position", "body": "Upper and lower positions take different cargo liners."},
  {"h": "Gas cargo liners on a hybrid", "body": "Check powertrain for cargo pieces."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy Husky's WeatherBeater 99411 for a 2024–2026 CR-V, Husky's 4-piece bundle for a 2023–2024 with cargo, and HAFIDI or Weize for TPE on a budget.",
  "body": "The 6th-gen CR-V's cabin is easy to fit; the cargo area takes a second look. Husky has the strongest warranty and walls, with year ranges that vary by part. HAFIDI covers the cabin for little money, Weize and the generic kit add cargo, TTX adds backrest mats and Autocessking is the hybrid cargo pick.\n\nAfter the floors, most CR-V owners add a trailer hitch for a bike rack and crossbars for the roof rails."},
 "sources": [
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners 99411 CR-V listing", "https://www.amazon.com/dp/B0C3XBN5BV"],
  ["Husky Liners CR-V 4-piece bundle listing", "https://www.amazon.com/dp/B0D43X3Q5G"],
  ["Husky Liners 24411 cargo liner listing", "https://www.amazon.com/dp/B0C3X9L4JD"],
  ["Husky Liners 99401 (2017–2022) listing", "https://www.amazon.com/dp/B06XPBJD8D"],
  ["Honda CR-V, sixth generation (Wikipedia)", "https://en.wikipedia.org/wiki/Honda_CR-V"],
 ],
}

FITS = [
 ("B0C3XBN5BV","Husky Liners WeatherBeater 99411, 2024-2026 Honda CR-V (incl. hybrid), front & 2nd row","Husky Liners","$130–$180",{},"2024+; for 2023 use 17281 + 11491."),
 ("B0D43X3Q5G","Husky Liners WeatherBeater 4-pc front, 2nd row + cargo, 2023-2024 CR-V (incl. hybrid), adjustable cargo upper level","Husky Liners","$180–$240",{},"Confirm 2025+ and cargo position."),
 ("B0BVLYJV8X","HAFIDI TPE Floor Liners 1st & 2nd row, 2023-2026 CR-V & CR-V Hybrid","HAFIDI","$80–$120",{},"Cabin set only."),
 ("B0CWRYCGGY","Weize Floor Mats + Cargo Liner (upper position), 2023-2026 CR-V incl. Hybrid","Weize","$110–$150",{},"Cargo liner for upper deck position."),
 ("B0DZNG9CHB","TTX Lighting Floor Liners + Cargo Liner + Backrest Mats, 2023-2026 CR-V gas & hybrid (upper deck)","TTX Lighting","$120–$160",{},"Full set."),
 ("B0CSKR1WZ6","TPE All-Weather Floor Mats + Cargo Liner, 2023-2026 CR-V gas & hybrid","Generic","$110–$150",{},"Full set incl. cargo; confirm deck position."),
 ("B0D5QNN1BD","Autocessking 4-Piece Floor Mats + Cargo Liner, 2023-2025 CR-V Hybrid (upper deck)","Autocessking","$100–$140",{"hybrid":True},"Hybrid cargo deck."),
 ("B0CZ364XXB","Sunsdrew TPE Floor Liners 1st & 2nd row, 2023-2025 CR-V & Hybrid","Sunsdrew","$80–$120",{},"Cabin set only."),
 ("B0FN4LV9RG","Husky Liners WeatherBeater 17281 Front Row, 2023-2026 Honda CR-V incl. Hybrid","Husky Liners","$70–$110",{},"Front row only."),
 ("B0FN4M6NKL","Husky Liners WeatherBeater 11491 2nd Row, 2023-2026 Honda CR-V incl. Hybrid","Husky Liners","$60–$100",{},"2nd row only."),
 ("B0C3X9L4JD","Husky Liners WeatherBeater 24411 Cargo Liner, 2023-2025 CR-V incl. Hybrid (upper cargo position)","Husky Liners","$90–$140",{},"Upper cargo position."),
]
