"""Long-form article — Best Floor Mats & Liners for 2020–2025 Hyundai Palisade (1st gen, LX2).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("hyundai", "palisade", "2020-2025", "floor-mats")

TITLE = "Best Floor Liners for 2020–2025 Hyundai Palisade: 6 Three-Row Picks, and Why 2026 Is Different"
META = ("Six 1st-gen Palisade floor liner options from WeatherTech, Husky, Smartliner, TOUGHPRO, RILLEC and "
        "Megiteller, sorted by 7- vs 8-seat, with the 2026 redesign cutoff.")

FAQ = [
 ("Do 2020–2025 Palisade liners fit a 2026 Palisade?",
  "No. The 2026 Palisade is a new generation. Husky sells a separate 96381 set for it, distinct from the 95711 for 2020–2024. Buy liners that name your generation."),
 ("What's the difference between 7-seat and 8-seat Palisade liners?",
  "The second row. Seven-seat Palisades have two captain's chairs; eight-seat Palisades have a bench. TOUGHPRO's set is for buckets. RILLEC lists both 7 and 8 seat, and Megiteller lists bench and bucket layouts. Check the second-row piece against your vehicle."),
 ("Do Telluride liners fit the Palisade?",
  "Don't assume so. The two share a platform, but most makers sell separate sets because the cabins differ. Buy liners that name the Palisade."),
 ("Did the 2023 facelift change the floor?",
  "The 2023 refresh changed styling and interior details, but most listings here run 2020–2025, which indicates the floor carried over. Husky's 95711 title stops at 2024, so confirm a 2025 with Husky."),
 ("Is Husky's cargo liner worth adding?",
  "If you haul gear with the third row folded, yes. Husky's 22711 cargo liner is listed for 2020–2025 Palisade and runs to the back of the second row over the folded third row, covering the whole load floor."),
 ("What is Megiteller?",
  "A budget brand selling heavy-duty rubber liners. Its Palisade listing covers three rows in bench and bucket layouts. We couldn't find published warranty terms, so we rank it on fit and price."),
 ("Is WeatherTech's full set worth the price?",
  "It covers all three rows with WeatherTech's laser-measured fit and lifetime limited warranty. It's the most expensive option here. Families who use every row get the most out of it."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto Hyundai's retention posts and clear of the pedals at full travel. Remove the factory mat first and heel-test the liner toward the pedals."),
 ("Do Calligraphy trims need different liners?",
  "No. Trims change seats and finishes, not the floor. Seating layout matters; trim doesn't."),
 ("How do I clean three-row liners?",
  "Pull each row, shake out crumbs, rinse and scrub with mild soap, and dry before reinstalling. Skip silicone protectants."),
 ("How much do Palisade liners cost?",
  "On this page, rubber sets run about $100–$150, Husky's front and second row about $130–$170, RILLEC's three rows plus cargo and Smartliner's three rows about $150–$200, and WeatherTech's full set about $280–$360. Amazon prices move daily."),
 ("Can I mix liner brands row by row in a Palisade?",
  "Yes. Each row is a separate piece. A common approach is Husky's front and second-row liners for their walls and warranty, a budget third-row piece and Husky's cargo liner. Make sure every piece names the 2020–2025 Palisade and your second-row layout."),
]

ARTICLE = {
 "dek": "Six three-row liner options for the first-generation Palisade, from WeatherTech's full set to $100 heavy rubber. The second row decides fit, and 2026 is a hard cutoff: the redesigned Palisade takes different liners.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2020–2025 Palisade (seating, rows covered, years), on published maker specs (material, origin, warranty) and on coverage in listing photos. WeatherTech, Husky and Smartliner claims come from their own sites, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**2026 is a new Palisade.** Husky sells 96381 for it; nothing here fits.",
  "**7-seat or 8-seat.** Captain's chairs and bench take different second-row pieces.",
  "**WeatherTech and Smartliner cover three rows.** RILLEC adds cargo liners.",
  "**Husky covers front, second and cargo.** 95711 plus 22711.",
  "**Telluride liners aren't a safe substitute.** Buy Palisade-named listings.",
 ],
 "top_picks": [
  {"asin": "B0821S9J83", "role": "Best overall", "why": "WeatherTech FloorLiners full set, three rows"},
  {"asin": "B0855BJL1M", "role": "Best made in USA", "why": "Husky WeatherBeater 95711, front and 2nd row, 2020–2024"},
  {"asin": "B081TP8BD4", "role": "Best one-piece TPE", "why": "Smartliner 3-row set, 2020–2025"},
  {"asin": "B0D22HJYD7", "role": "Best with cargo", "why": "RILLEC 3-row plus cargo liners, 7 and 8 seat"},
  {"asin": "B07WHP4DY5", "role": "Best rubber", "why": "TOUGHPRO plus 3rd row, 2nd-row buckets, listed as made in USA"},
 ],
 "fit_table": {
  "caption": "Palisade liners by generation and seating",
  "head": ["Variable", "Versions", "What to buy"],
  "rows": [
   ["Generation", "2020–2025 vs 2026+", "Picks here are 2020–2025; 2026 needs new-gen liners (e.g., Husky 96381)"],
   ["Second row", "Captain's chairs (7) or bench (8)", "TOUGHPRO: buckets; RILLEC and Megiteller: both"],
   ["Facelift", "2023+", "Floor carried over; confirm titles that stop at 2024"],
  ],
 },
 "look_for": [
  {"h": "The 2026 cutoff",
   "body": "The Palisade was redesigned for 2026, and the floor changed with it. Husky makes the split clear with separate WeatherBeater sets: 95711 for 2020–2024 and 96381 for 2026, plus separate 2026 front and second-row pieces. Every set on this page is for the first generation. If you're shopping for a 2026, skip this page's picks and buy liners that name the new model. If you're buying a used first-gen Palisade, the picks here fit 2020–2025, with a couple that stop at 2024."},
  {"h": "Captain's chairs or bench",
   "body": "The first-gen Palisade offers a second-row bench for eight seats or captain's chairs for seven. The second-row liner and sometimes the third-row liner are shaped for one layout. TOUGHPRO's set is for bucket seats. RILLEC lists 7- and 8-seat. Megiteller lists bench and bucket. WeatherTech splits parts by layout in its fit program. Count your second-row seats before shopping."},
  {"h": "How many rows to cover",
   "body": "WeatherTech and Smartliner cover three rows. RILLEC covers three rows plus cargo liners. Husky's 95711 covers the front and second row; its 22711 cargo liner covers the load floor to the back of the second row over the folded third row. Families that use the third row daily should cover it; families that mostly fold it flat should prioritize the cargo liner."},
  {"h": "Warranty and origin",
   "body": "WeatherTech says its liners are laser-measured and backed by a lifetime limited warranty. Husky says WeatherBeater is laser-measured, made in the USA and covered by a lifetime warranty against cracks and breaks. Smartliner says its liners are one-piece, 100% recyclable TPE designed in the US, with a limited lifetime warranty. TOUGHPRO's listings say made in USA. RILLEC and Megiteller don't publish comparable terms we could check."},
  {"h": "Retention and pedal clearance",
   "body": "Hyundai uses retention posts in the driver footwell. A Palisade-specific liner lines up with them. Seat the driver liner, heel-test it toward the pedals and press the brake and accelerator to the floor. Never stack a liner on the factory mat."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2020–2025 named", "2026+ listings on a 1st-gen"],
   ["Vehicle", "Palisade named", "Telluride listings"],
   ["Second row", "Bench or buckets named", "Kits that don't state seating"],
   ["Rows", "The zones you use", "Paying for rows you don't need"],
   ["Retention", "Hook holes for Hyundai's posts", "Loose mats"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2020–2025 Palisade",
  "head": ["Type", "Example", "Coverage", "Walls", "Price band", "Best for"],
  "rows": [
   ["Laser-measured full set", "WeatherTech", "3 rows", "High", "$280–$360", "One brand throughout"],
   ["USA-made molded liner", "Husky 95711", "Front + 2nd", "High", "$130–$170", "Snow country"],
   ["One-piece TPE", "Smartliner", "3 rows", "Medium-high", "$150–$200", "Warranty on a budget"],
   ["TPE + cargo", "RILLEC", "3 rows + cargo", "Medium", "$150–$200", "Families who haul"],
   ["Rubber", "TOUGHPRO, Megiteller", "3 rows", "Low-medium", "$100–$150", "Budget, grip"],
  ],
 },
 "picks": [
  {"asin": "B0821S9J83", "role": "Best overall", "price": "$280–$360",
   "pros": ["All three rows in one set", "Laser-measured fit", "Lifetime limited warranty", "High walls", "WeatherTech fit program by layout"],
   "cons": ["Most expensive here", "Grey color in this listing; check others", "Confirm seating layout"],
   "body": "WeatherTech's FloorLiners full set covers the first, second and third rows of the Palisade. WeatherTech says its liners are laser-measured for a custom fit and backed by a lifetime limited warranty; its HP line uses injection-molded TPE with beveled high walls, made in America.\n\nOne brand across three rows keeps fit and wall height consistent through the cabin. The listing here is the grey color; WeatherTech sells black and tan versions too, which matters for matching a Calligraphy interior. Confirm your seating layout with WeatherTech's fit checker, because the second-row piece differs between captain's chairs and bench.\n\nIt's the most expensive option. For a family that uses every row and keeps the car for years, it's the most complete single purchase. Add Husky's 22711 cargo liner if you haul gear.",
   "who": "Families who use all three rows and want one brand throughout.",
   "specs": [["Brand", "WeatherTech"], ["Rows", "1st–3rd"], ["Fits", "Hyundai Palisade 1st gen (confirm seating)"], ["Fit method", "Laser-measured"], ["Warranty", "Lifetime limited"], ["Color", "Grey (other colors sold separately)"]]},
  {"asin": "B0855BJL1M", "role": "Best made in USA", "price": "$130–$170",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs", "Front and 2nd row, 3 pieces", "Pairs with Husky's 22711 cargo liner"],
   "cons": ["Title covers 2020–2024; confirm 2025", "No third row", "Firm feel"],
   "body": "Husky's WeatherBeater 95711 covers the front and second row of the 2020–2024 Palisade. Husky says WeatherBeater is laser-measured using vehicle-specific data, designed and made in the USA from ProGard and anchored by StayPut nibs, with a lifetime warranty against cracks and breaks.\n\nThe front and second row take most of the traffic in a family Palisade, so this set protects the busiest zones for less than half of WeatherTech's price. The firm walls hold snowmelt. Husky also sells separate front (15261) and second-row (12731) pieces listed for 2020–2025, which covers a 2025.\n\nPair it with the 22711 cargo liner for the load floor. For the third row, add a third-row liner from another brand or check Husky's catalog. The one-piece second-row liner matters on an eight-seat Palisade, where three passengers share the rear floor and a middle passenger stands on the hump. On a seven-seat vehicle, check how the second-row piece handles the space between the captain's chairs.",
   "who": "Owners who want US-made liners in the busiest rows.",
   "specs": [["Part #", "Husky 95711"], ["Pieces", "3"], ["Fits", "2020–2024 Palisade, front + 2nd row"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B081TP8BD4", "role": "Best one-piece TPE", "price": "$150–$200",
   "pros": ["Three rows", "One-piece, 100% recyclable TPE", "Limited lifetime warranty", "No PVC, latex or BPA", "Lists 2020–2025"],
   "cons": ["Walls lower than Husky's", "Confirm seating layout", "Cargo sold separately"],
   "body": "Smartliner's 3-row set covers the 2020–2025 Palisade. Smartliner says its liners are molded from a single piece of heavy-duty, 100% recyclable TPE, free of PVC, latex and BPA, covering wall to wall including the transmission tunnel and under-seat areas, with a limited lifetime warranty. The company is based in Apopka, Florida.\n\nThree rows with a written lifetime warranty for about half of WeatherTech's price is the value case. The full 2020–2025 range also covers the facelifted cars without a separate part.\n\nConfirm your second-row layout with the seller. Add a cargo liner if you haul gear. Smartliner's one-piece construction also helps with cleaning: each row comes out as a single tray rather than several small mats, which is easier with a car full of kids' gear. The TPE is flexible enough to fold for carrying without cracking in cold weather.",
   "who": "Families who want three rows with a warranty on a budget.",
   "specs": [["Rows", "3"], ["Fits", "2020–2025 Palisade"], ["Material", "One-piece TPE"], ["Warranty", "Limited lifetime"], ["Company", "Apopka, Florida"]]},
  {"asin": "B0D22HJYD7", "role": "Best with cargo", "price": "$150–$200",
   "pros": ["Three rows plus cargo liners", "Lists 7- and 8-seat", "Full 2020–2025 range", "One order for the whole interior", "Raised edges"],
   "cons": ["No published warranty", "Little maker documentation", "Walls lower than molded premium liners"],
   "body": "RILLEC's set covers three rows plus cargo liners for 2020–2025 Palisade, 7- and 8-seat. It's the most complete coverage here for the money.\n\nThe cargo liners are what set it apart: families who haul sports gear or a stroller get the load floor covered in the same order. RILLEC doesn't publish warranty terms we could check.\n\nBecause it lists both seating layouts, confirm which second-row piece ships for your vehicle before ordering. If the cargo liner is the main reason you're buying, compare it with Husky's 22711 WeatherBeater cargo liner, which has taller walls and a lifetime crack warranty. RILLEC's advantage is the price of the whole kit; Husky's is durability in the one area that takes the heaviest loads.",
   "who": "Families who want every zone covered in one order.",
   "specs": [["Covers", "3 rows + cargo"], ["Fits", "2020–2025 Palisade, 7 & 8 seat"], ["Material", "TPE (per listing)"], ["Warranty", "Confirm with seller"], ["Price band", "$150–$200"]]},
  {"asin": "B07WHP4DY5", "role": "Best rubber", "price": "$110–$150",
   "pros": ["Front, 2nd and 3rd row", "Heavy-duty rubber listed as made in USA", "For 2nd-row buckets", "Grips and stays flexible in the cold", "Budget price for three rows"],
   "cons": ["Buckets only", "Lower edges than molded liners", "No cargo mat"],
   "body": "TOUGHPRO's set covers the front, second and third rows of the 2020–2025 Palisade with second-row buckets. Its listing describes heavy-duty rubber mats made in USA.\n\nRubber suits family use: it grips small shoes, stays flexible in the cold and doesn't slide. The edges are lower than a molded liner's, so empty the front mats after heavy snow.\n\nFor a seven-seat Palisade on a budget, it's the pick. Megiteller's heavy-duty rubber set, which lists bench and bucket layouts, is the alternative for eight-seat vehicles and is in our product list. Check the listing photos for the driver-side retention holes; heavy rubber mats rely on their weight and the posts rather than nibs, so seating them on the posts is important.",
   "who": "Seven-seat owners who want three rows of rubber.",
   "specs": [["Rows", "3"], ["Fits", "2020–2025 Palisade, 2nd-row buckets"], ["Material", "Heavy-duty rubber"], ["Made in", "USA (per listing)"], ["Price band", "$110–$150"]]},
  {"asin": "B084DW5PBH", "role": "Best cargo liner", "price": "$100–$150",
   "pros": ["Covers the load floor over the folded 3rd row", "Lists 2020–2025", "Made in the USA", "Lifetime warranty against cracks and breaks", "Tall walls contain spills"],
   "cons": ["Cargo only", "Firm material", "Adds cost on top of a floor set"],
   "body": "Husky's WeatherBeater 22711 cargo liner is listed for 2020–2025 Palisade and runs to the back of the second row over the folded third row. With the third row down, the Palisade's load floor is long and flat, and this liner covers all of it.\n\nIt carries the WeatherBeater credentials: laser-measured, made in the USA and a lifetime warranty against cracks and breaks. For families who haul luggage, sports gear or a dog, the cargo area takes as much abuse as the footwells.\n\nPair it with any floor set on this page. If your family uses the third row most of the time, the liner still protects the cargo floor behind it, and it folds out of the way when you raise the seats. A washable blanket on top helps if a dog rides back there, since a smooth liner can be slippery for paws under braking.",
   "who": "Owners who haul gear with the third row folded.",
   "specs": [["Part #", "Husky 22711"], ["Fits", "2020–2025 Palisade"], ["Coverage", "Cargo to back of 2nd row over folded 3rd row"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B08YJF62K1", "role": "Best rubber for 8-seat", "price": "$100–$140", "pros": ["Three rows of heavy-duty rubber", "Lists bench and bucket layouts", "Covers 2020–2025", "Lowest price for three rows", "Grips and stays flexible in the cold"], "cons": ["No published warranty", "Lower edges than molded liners", "Confirm which second-row piece ships"], "body": "Megiteller's heavy-duty rubber liners cover three rows of the 2020–2025 Palisade and list both bench and bucket layouts. That makes it the rubber option for eight-seat Palisades, which TOUGHPRO's bucket-only set doesn't cover.\n\nRubber suits family use: it's heavy enough to stay put, grips wet shoes and stays flexible in freezing weather. The edges are lower than a molded liner's, so empty the front mats after a snowy day. Megiteller doesn't publish warranty terms we could check.\n\nBecause the listing covers two layouts, confirm with the seller which second-row piece ships for your vehicle. For the lowest-cost three-row coverage on an eight-seat Palisade, it's the pick.", "who": "Eight-seat owners who want three rows of rubber for the least money.", "specs": [["Rows", "3"], ["Fits", "2020–2025 Palisade, bench & bucket"], ["Material", "Heavy-duty rubber"], ["Warranty", "Confirm with seller"], ["Price band", "$100–$140"]]}
 ],
 "install": [
  "Confirm your Palisade is a 2020–2025 model and check the second row (bench or captain's chairs).",
  "Remove the factory mats from every row and vacuum.",
  "Hook the driver liner onto the retention posts and heel-test it toward the pedals.",
  "Fit the passenger and second-row liners; slide and fold the second row to check clearance.",
  "Fit the third-row and cargo liners; fold the third row up and down.",
  "Press the pedals to the floor before driving.",
 ],
 "avoid": [
  {"h": "2026 liners on a 1st-gen", "body": "The redesigned Palisade has a different floor."},
  {"h": "Wrong second-row layout", "body": "Captain's chairs and bench take different pieces."},
  {"h": "Telluride listings", "body": "Shared platform, different cabin."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy WeatherTech's full set for three rows from one brand, Husky's 95711 plus 22711 for US-made front, second-row and cargo coverage, and Smartliner for three rows with a warranty on a budget.",
  "body": "The first-gen Palisade is fit by its second row and its generation. WeatherTech covers three rows with a lifetime limited warranty, Husky is the US-made choice for the busiest rows and the cargo floor, Smartliner and RILLEC give full coverage for less, and TOUGHPRO is the rubber budget pick for seven-seat vehicles.\n\nAfter the floors, many Palisade owners add a trailer hitch for a bike rack and a roof rack on the factory rails. Owners of a 2026 Palisade should look for new-generation parts."},
 "sources": [
  ["WeatherTech FloorLiner HP buying guide (WeatherTech)", "https://www.weathertech.com/blog/product-spotlight/new-weathertech-floorliner-hp.html"],
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners 95711 Palisade listing", "https://www.amazon.com/dp/B0855BJL1M"],
  ["Husky Liners 96381 2026 Palisade listing", "https://www.amazon.com/dp/B0GSSJD3YB"],
  ["Husky Liners 22711 cargo liner listing", "https://www.amazon.com/dp/B084DW5PBH"],
  ["SMARTLINER home page (SMARTLINER)", "https://www.smartliner-usa.com/"],
  ["Hyundai Palisade (Wikipedia)", "https://en.wikipedia.org/wiki/Hyundai_Palisade"],
 ],
}

FITS = [
 ("B0821S9J83","WeatherTech FloorLiners Full Set (461578-1-2-3), Hyundai Palisade, Grey","WeatherTech","$280–$360",{"rows":3},"Confirm seating layout with WeatherTech."),
 ("B0855BJL1M","Husky Liners WeatherBeater 95711, 2020-2024 Hyundai Palisade, front & 2nd row","Husky Liners","$130–$170",{"rows":2},"Confirm 2025."),
 ("B081TP8BD4","SMARTLINER 3-Row Floor Liner Set, 2020-2025 Palisade","SMARTLINER","$150–$200",{"rows":3},"Full 3-row set."),
 ("B0D22HJYD7","RILLEC 3-Row Liners + Cargo Liners, 2020-2025 Palisade 7 & 8 seat","RILLEC","$150–$200",{"rows":3},"7- and 8-seat."),
 ("B07WHP4DY5","TOUGHPRO Floor Mat Set + 3rd Row (made in USA), 2020-2025 Palisade with 2nd-row buckets","TOUGHPRO","$110–$150",{"rows":3,"second_row":"bucket"},"2nd-row bucket seats."),
 ("B084DW5PBH","Husky Liners WeatherBeater 22711 Cargo Liner, 2020-2025 Palisade (over folded 3rd row)","Husky Liners","$100–$150",{"rows":3},"Cargo only."),
 ("B08YJF62K1","Megiteller Heavy-Duty Rubber 3-Row Floor Liners, 2020-2025 Palisade bench & bucket","Megiteller","$100–$140",{"rows":3},"Bench and bucket layouts."),
]
