"""Long-form article — Best Rooftop Cargo Boxes for 2020–2025 Hyundai Palisade (1st gen, LX2).
Mirrors the approved F-150 tonneau pilot. No invented hands-on testing: box specs come from Yakima, Thule,
Rhino-Rack, INNO (via etrailer) and Rightline Gear (via RealTruck) pages fetched 2026-09-27; vehicle facts from
db/migrations/003_vehicles.sql and the Palisade roof-rack article (flush rails, Thule kit 6008, 50 in bars, 165 lb,
~32 in spread). Hyundai accessory crossbar 220 lb figure is from the Hyundai installation guide as quoted by owners on
palisadeforums.org; hatch clearance (about 71 in) from an etrailer expert answer.
Source fixes 2026-10-04 (round 2): roof figure now cites Hyundai's 2020, 2023 and 2024 specification sheets (roof rails load capacity 220 lb; sheets do not say whether it is for driving only) alongside the forum-quoted 220 lb accessory crossbar figure, with "the lowest number applies"; the 163 lb Motion 3 XXL remainder restated as crossbars plus gear under the roof figure; factory receiver wording removed (the sheets list no tow hitch); rails worded as the trims the listings name; etrailer hatch clearance worded as "gives" not "measured"; Telluride line reduced to "related" (Wikipedia).
"""

KEY = ("hyundai", "palisade", "2020-2025", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2020–2025 Hyundai Palisade: 7 Picks for Its Flush Rails"
META = ("Seven Yakima, Thule, Rhino-Rack, INNO and Rightline cargo boxes for the 1st-gen Palisade: flush-rail bars, "
        "32 in spread, 165 vs 220 lb bar math, hatch clearance.")

FAQ = [
 ("What size cargo box fits a 2020–2025 Hyundai Palisade?",
  "The Palisade's roof and hatch leave room for almost any size. An etrailer expert puts its rear hatch clearance at about 71 in, well past the 55 in a Thule Motion XT needs, so even the 91.3 in Thule Motion 3 XXL (21 cu ft) is a realistic choice. For most families a 16 cu ft box like the Yakima SkyBox 16 is the sweet spot: enough for third-row luggage while leaving weight for gear under a 165 lb bar rating."),
 ("How much weight can the Palisade's roof crossbars hold?",
  "It depends on the bars, and the roof has its own figure. Hyundai's 2020, 2023 and 2024 Palisade specification sheets print a roof rails load capacity of 220 lb. The sheets do not say whether that is for driving only. Thule rates its Evo Flush Rail system for the Palisade at 165 lb, which is the system's rating. Palisade owners also quote Hyundai's accessory crossbar installation guide: 220 lb (100 kg), evenly distributed, for the set. The lowest number applies. The bars, the box and everything in it count toward the roof figure."),
 ("What crossbar spread does the Palisade allow for a cargo box?",
  "In an etrailer answer about a Thule Motion XT, the expert gives the Palisade's crossbar spread as about 32 in. That sits inside the range of every box here with a published spread: 24 to 34.5 in for the SkyBox 16, 21-13/16 to 36-9/16 in for the Thule Motion 3, 24 to 39 in for the INNO Wedge 660 and 620 to 930 mm (about 24.4 to 36.6 in) for the Rhino-Rack MasterFit 440. The DeepSpace 10 needs 32 to 46 in, so 32 in is right at its minimum."),
 ("Will a roof box hit the Palisade's liftgate?",
  "Rarely, if it is mounted forward. The etrailer expert gives about 71 in of rear hatch clearance on the Palisade against 55 in needed for a Thule Motion XT. Thule lists more than 54 13/16 in of front clearance for the Motion 3 XXL, the longest box here. Measure your own Palisade from the front crossbar to the line where the roof meets the hatch, and open the power liftgate slowly the first time."),
 ("Do I need Thule or Hyundai crossbars for a cargo box?",
  "No particular brand, but they must be flush-rail bars that name the 2020–2025 Palisade. Hyundai sells accessory crossbars (220 lb per its install guide, as owners quote it), Thule fits it with Evo Flush Rail feet, kit 6008 and 50 in WingBar Evo bars (165 lb), and Amazon sets clamp to the same rails. A box clamps to any of them. Raised-rail towers won't grip the Palisade's flush rails. See our Palisade roof rack page for fit-checked bars."),
 ("Will a 2020–2025 Palisade cargo box fit the 2026 Palisade?",
  "The box will, because boxes clamp to crossbars, not the car. The 2026 Palisade is a new generation with a different body, so buy crossbars listed for 2026 and re-check the spread, hatch clearance and roof figure in its manual. Your 2020–2025 bars shouldn't be assumed to fit."),
 ("Can I carry a cargo box and bikes on a Palisade?",
  "Yes, with a narrow box. Thule's Palisade bars are 50 in long. A full-width box like the 36 in SkyBox 16 leaves about 14 in, which is tight for a bike mount; the 26.5 in Yakima SkyBox NX Skinny leaves about 23.5 in. Add up the box, the bike mount, the bike and the cargo, and keep it under your bar rating, 165 lb on the Thule system, and never above the 220 lb roof rails figure on Hyundai's spec sheets."),
 ("Can I open the Palisade's sunroof with a cargo box on?",
  "Check it parked before you rely on it. Flush-rail feet hold the bars a few inches above the roof, and a box's front edge can sit close to the sunroof opening. For other SUVs, etrailer's experts advise against opening a sunroof or panoramic roof while a box is installed, because the glass can make contact with the rack or box. Keep it closed on the road."),
 ("Will a cargo box fit in my garage on a Palisade?",
  "Measure first. The boxes here add 11 in (INNO Wedge 660), 15 in (SkyBox 16), 16 in (NX Skinny, DeepSpace 10), 17 in (Rhino-Rack MasterFit 440), about 18 in (Motion 3 XXL, Rightline Sport 3) on top of the crossbars, which already sit above the flush rails. Measure the Palisade with bars fitted, add the box height, and compare it with the garage door opening."),
 ("Is a roof box or a hitch cargo carrier better on a Palisade?",
  "Hyundai's 2020, 2023 and 2024 specification sheets rate the Palisade at 5,000 lb with trailer brakes and list no tow hitch as equipment, so a receiver is something a dealer or an owner adds. Look under the rear bumper. With a receiver fitted, a hitch carrier suits heavy items like coolers and water jugs without touching the roof figure. A roof box is better for soft, bulky luggage, keeps the liftgate and camera clear, and locks. For an eight-seat Palisade that is full to the third row, many families use both."),
]

ARTICLE = {
 "dek": "Seven rooftop boxes from Yakima, Thule, Rhino-Rack, INNO and Rightline Gear matched to the first-generation Palisade's flush rails, from a 30.2 lb 10 cu ft box to the 21 cu ft Thule Motion 3 XXL and a $140 soft bag. For each we list volume, size, box weight and crossbar spread, and what those numbers mean for the Palisade's roughly 32 in bar spread, its 165 lb or 220 lb bars, Hyundai's 220 lb roof rails figure and a hatch with about 71 in of clearance.",
 "author": "jake-morrison",
 "reviewed": "2026-10-04",
 "method": "We did not mount these boxes ourselves. We ranked them on published specs from Yakima, Thule and Rhino-Rack, etrailer's figures for the INNO Wedge 660 and the Thule Motion 3 spread, and RealTruck's Rightline Gear listing: volume, exterior size, box weight, cargo rating, crossbar spread, ski length and warranty. We checked those numbers against the Palisade's flush rails, the 165 lb Thule system, the 220 lb roof rails load capacity on Hyundai's 2020, 2023 and 2024 specification sheets, the 220 lb figure owners quote from Hyundai's accessory crossbar guide, and etrailer's Palisade answer on crossbar spread (about 32 in) and hatch clearance (about 71 in). Prices were checked in September 2026; Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Flush-rail crossbars first.** The Palisade's rails are flush, so buy bars made for them (Thule kit 6008, Hyundai accessory bars or a flush-rail Amazon set). Every box here clamps to any of them.",
  "**Know your bar rating and the roof figure.** Thule's Palisade system is rated at 165 lb. Hyundai's 2020, 2023 and 2024 spec sheets print a 220 lb roof rails load capacity, and owners quote the same 220 lb (100 kg) from Hyundai's accessory crossbar guide. The lowest number applies.",
  "**About 32 in of spread.** etrailer gives that figure for the Palisade. It suits every box here, though it is right at the DeepSpace 10's 32 in minimum.",
  "**The hatch is generous.** etrailer gives about 71 in of hatch clearance, so even a 91.3 in Motion 3 XXL can fit if mounted forward.",
  "**2026 is a new generation.** Boxes carry over; bars for 2020–2025 shouldn't be assumed to fit.",
 ],
 "top_picks": [
  {"asin": "B001PUZXGK", "role": "Best overall", "why": "16 cu ft, 15 in tall, 47 lb, 24–34.5 in spread covers the 32 in Palisade spread"},
  {"asin": "B0F8PNL8H9", "role": "Biggest box", "why": "Thule Motion 3 XXL: 21 cu ft, 215 cm skis; the Palisade's 71 in hatch clearance has room"},
  {"asin": "B07B4P7WYX", "role": "Best mid-size", "why": "Rhino-Rack MasterFit 440: 15.5 cu ft, 38.6 lb, 165 lb cargo rating, 5-year warranty"},
  {"asin": "B0DYWCZSD8", "role": "Best box plus bike", "why": "26.5 in wide, leaving about 23.5 in on 50 in Thule bars; 195 cm skis"},
  {"asin": "B0012INT98", "role": "Best budget", "why": "Rightline Gear Sport 3: 18 cu ft waterproof soft carrier, $139.99"},
 ],
 "fit_table": {
  "caption": "2020–2025 Palisade roof setups (what the box mounts to)",
  "head": ["Item", "Palisade (1st gen)", "What it means for a box"],
  "rows": [
   ["Rails", "Flush side rails on the trims crossbar listings name (SE, SEL, XRT, Limited, Calligraphy)", "Flush-rail bars only; raised-rail towers won't grip"],
   ["Roof rails load capacity", "220 lb (Hyundai 2020, 2023 and 2024 spec sheets)", "Covers bars, box and cargo; the sheets do not say if it is for driving only"],
   ["Thule system", "Evo Flush Rail 710601 + kit 6008 + 50 in WingBar Evo, 165 lb", "Box + cargo under 165 lb; 50 in bars"],
   ["Hyundai accessory bars", "220 lb (100 kg) evenly distributed, per Hyundai install guide quoted by owners", "More headroom, up to the roof rails figure"],
   ["Crossbar spread", "About 32 in (etrailer expert)", "Fits boxes whose range includes 32 in"],
   ["Hatch clearance", "About 71 in (etrailer expert)", "Room for long boxes mounted forward"],
   ["2026+", "New generation", "Boxes carry over; buy new bars"],
  ],
 },
 "look_for": [
  {"h": "Flush-rail bars, then the box",
   "body": "A cargo box clamps to crossbars, and on the Palisade the crossbars are where the fit lives. Its side rails are flush, attached to the roof along their whole length with no gap underneath, so the bars need feet that grip the rail from the side. Thule's answer is its Evo Flush Rail foot with fit kit 6008 and 50 in WingBar Evo bars; Hyundai sells accessory crossbars; and Amazon has flush-rail sets that name 2020–2025. Raised-rail towers that wrap under a rail won't hold. Once the bars are on, every box on this page clamps to them. Our Palisade roof rack page lists the fit-checked sets."},
  {"h": "165 lb or 220 lb: the rating on your bars",
   "body": "The Palisade has two common bar ratings. Thule rates its Evo Flush Rail system for the Palisade at 165 lb. Palisade owners quote Hyundai's accessory crossbar installation guide at 220 lb (100 kg), evenly distributed. The roof has its own figure: Hyundai's 2020, 2023 and 2024 specification sheets print a roof rails load capacity of 220 lb, without saying whether it is for driving only. Plan around the lowest of those numbers that applies. The hard boxes here weigh 30.2 lb (DeepSpace 10) to 57.2 lb (Motion 3 XXL), so on 165 lb bars you have roughly 108 to 135 lb for gear. Some boxes have their own lower cargo limits: 100 lb for the DeepSpace 10 and 110 lb for the INNO Wedge 660."},
  {"h": "The 32 in spread",
   "body": "Every box has a minimum and maximum crossbar spread, and an etrailer expert gives the Palisade's as about 32 in. That is comfortably inside the SkyBox 16 (24 to 34.5 in), the Thule Motion 3 (21-13/16 to 36-9/16 in, per etrailer), the INNO Wedge 660 (24 to 39 in) and the Rhino-Rack MasterFit 440 (620 to 930 mm, about 24.4 to 36.6 in). The Yakima DeepSpace 10 needs 32 to 46 in, so a Palisade at 32 in is right at its minimum; measure your own bars first. Yakima doesn't publish a spread for the SkyBox NX Skinny, so confirm it."},
  {"h": "Hatch clearance and box length",
   "body": "The Palisade's long, flat roof is friendly to long boxes. In the same etrailer answer, the expert gives about 71 in of rear hatch clearance on the Palisade, against 55 in needed for a Thule Motion XT. Thule lists more than 54 13/16 in of front clearance for the 91.3 in Motion 3 XXL, the longest box here, so the numbers work if the box is mounted forward. Measure your own Palisade from the front crossbar to the line where the roof meets the hatch, then open the power liftgate slowly the first time with the box on."},
  {"h": "Width on 50 in bars",
   "body": "Thule's Palisade system uses 50 in (127 cm) bars, shorter than the long bars on some raised-rail SUVs. A full-width 36 in box such as the SkyBox 16 leaves about 14 in, enough for a slim accessory but tight for a bike mount. If bikes or a kayak share the roof, a narrow box helps: the SkyBox NX Skinny is 26.5 in wide and the DeepSpace 10 is 23 in, which leave about 23.5 in and 27 in. A second carrier also adds weight against the same bar rating, so add it all up before you load."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbars", "Flush-rail bars that name the 2020–2025 Palisade", "Raised-rail towers or 2026 Palisade bars"],
   ["Crossbar spread", "A range that includes about 32 in", "Boxes whose minimum is above your measured spread"],
   ["Box weight", "Under about 50 lb on 165 lb bars", "Filling a 21 cu ft box with heavy gear"],
   ["Width", "26–27 in if bikes share the 50 in bars", "Full-width box plus bikes over the rating"],
   ["Height", "11–16 in if you park in a garage", "Guessing clearance with an 18 in box"],
   ["Warranty", "Limited lifetime (Yakima, Thule Motion 3, INNO) or 5 years (Rhino-Rack)", "No stated warranty"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Palisade (makers' specs; INNO and Motion 3 spread per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Palisade notes"],
  "rows": [
   ["Yakima SkyBox 16 Carbonite", "16 cu ft", "81 × 36 × 15 in", "47 lb", "24–34.5 in", "Covers 32 in; low"],
   ["Thule Motion 3 XXL", "21 cu ft", "91.3 × 36.2 × 18.1 in", "57.2 lb", "21-13/16 to 36-9/16 in", "Biggest; 71 in hatch helps"],
   ["Rhino-Rack MasterFit 440", "15.5 cu ft", "76 × 32 × 17 in", "38.6 lb", "620–930 mm (about 24.4–36.6 in)", "165 lb cargo rating; 5-year warranty"],
   ["Yakima SkyBox NX Skinny", "12 cu ft", "84 × 26.5 × 16 in", "43 lb", "Not published; confirm", "Room for a bike on 50 in bars"],
   ["Yakima DeepSpace 10", "10 cu ft", "60 × 23 × 16 in", "30.2 lb", "32–46 in", "At its minimum on a 32 in spread"],
   ["INNO Wedge 660", "11 cu ft", "80 × 33 × 11 in", "42 lb", "24–39 in", "Lowest; 110 lb cargo"],
   ["Rightline Gear Sport 3", "18 cu ft", "48 × 36 × 18 in", "Soft bag", "Straps; rack optional", "No lock; folds away"],
  ],
 },
 "picks": [
  {"asin": "B001PUZXGK", "role": "Best overall", "price": "$599",
   "pros": ["16 cu ft, the right size for third-row luggage", "24–34.5 in spread covers the Palisade's 32 in", "15 in tall, low on a tall SUV", "47 lb, leaving 118 lb of a 165 lb rating for gear", "$599 on sale at Yakima (regular $749); limited lifetime warranty"],
   "cons": ["36 in wide, leaving about 14 in on 50 in bars", "Skis up to 185 cm only", "81 in long; check the hatch once"],
   "body": "For most Palisade owners, the problem a box solves is simple: with all three rows in use, the luggage doesn't fit. The SkyBox 16 Carbonite handles that at a fair price. Yakima lists it at 16 cu ft and 81 x 36 x 15 in, with a 47 lb box weight, dual-side opening, SuperLatch security and SKS locks, and says it installs with no assembly on Yakima StreamLine bars and most factory or aerodynamic crossbars. It takes skis and boards up to 185 cm and carries a limited lifetime warranty. It was $599 on sale on Yakima's store when we checked, down from $749.\n\nIt matches the Palisade's numbers well. The 24 to 34.5 in spread range includes the roughly 32 in spread etrailer gives for the Palisade, and 47 lb of box on 165 lb Thule bars leaves 118 lb for bags; on Hyundai's 220 lb accessory bars there is more headroom, up to the 220 lb roof rails figure on Hyundai's spec sheets, which also has to cover the bars. At 15 in tall it is one of the lower boxes here, which helps on an SUV this tall. The catch is width: at 36 in it fills most of 50 in Thule bars, so choose the NX Skinny if bikes ride up there too.",
   "who": "Palisade families who want a full-size 16 cu ft box at a good price and a low height.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "81 × 36 × 15 in"], ["Box weight", "47 lb"], ["Crossbar spread", "24–34.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS, SuperLatch"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0F8PNL8H9", "role": "Biggest box", "price": "$1,249.95 (box alone)",
   "pros": ["21 cu ft, the most volume here", "Skis up to 215 cm", "21-13/16 to 36-9/16 in spread (etrailer) covers 32 in", "Thule rates it for 165 lb of cargo", "One-handed dual-side opening, PowerClick mounts, SlideLock"],
   "cons": ["57.2 lb, the heaviest here", "91.3 in long; mount it forward", "This Amazon listing bundles GoPack duffels, so it costs more than the box alone"],
   "body": "An eight-seat Palisade on a week-long trip can fill any box, and the Thule Motion 3 XXL is the biggest on this page. Thule lists it at 21 cu ft and 91.3 x 36.2 x 18.1 in, with a 57.2 lb box weight, a 165 lb maximum load and room for skis up to 215 cm. It opens from either side with one hand, locks with SlideLock and clamps on with PowerClick mounts. etrailer lists a 21-13/16 to 36-9/16 in spread and a limited lifetime warranty for the Motion 3 line. Thule lists the box alone at $1,249.95; this Amazon listing bundles it with a GoPack duffel set, so compare prices.\n\nThe Palisade suits it better than most SUVs. Thule lists more than 54 13/16 in of front clearance, and the etrailer expert gives about 71 in of hatch clearance on the Palisade, so a forward-mounted XXL should leave the liftgate free; measure yours to be sure. The limit is weight. On 165 lb Thule bars, 57.2 lb of box leaves about 108 lb for gear. Against Hyundai's 220 lb roof rails figure, the same box leaves about 163 lb for the crossbars and the gear together, and Thule's 165 lb load limit for the box still applies. Fill it with sleeping bags, jackets and soft duffels, not coolers.",
   "who": "Big families and ski groups who want the most volume and pack it light.",
   "specs": [["Volume", "21 cu ft"], ["Exterior", "91.3 × 36.2 × 18.1 in"], ["Box weight", "57.2 lb"], ["Max load", "165 lb"], ["Crossbar spread", "21-13/16 to 36-9/16 in (etrailer)"], ["Ski length", "Up to 215 cm"], ["Front clearance", "More than 54 13/16 in (Thule)"], ["Mount / lock", "PowerClick / SlideLock"]]},
  {"asin": "B07B4P7WYX", "role": "Best mid-size", "price": "Not listed on Rhino-Rack's page; check listing",
   "pros": ["15.5 cu ft (440 L) at 38.6 lb", "Rated for 75 kg (about 165 lb) of cargo", "620–930 mm spread covers the Palisade's 32 in", "Dual-side opening with three locking points", "5-year warranty"],
   "cons": ["Rhino-Rack lists direct fit on its own Vortex and Euro bars; confirm the clamp on yours", "Rhino-Rack doesn't list a price on its page", "No ski length published"],
   "body": "The Rhino-Rack MasterFit 440 is Rhino-Rack's light, mid-size hard box. Rhino-Rack lists it at 440 L (15.5 cu ft), with exterior dimensions of 76 x 32 x 17 in, an interior of 74 x 30 x 15 in, a 38.6 lb box weight and a 75 kg maximum load. It opens from both sides, locks at three points with the included key, and uses a twist-to-tighten, press-to-lock clamp. Rhino-Rack covers it with a 5-year warranty. Its page doesn't list a price, so check the live listing.\n\nOn a Palisade, the numbers line up. Rhino-Rack's required crossbar spacing of 620 to 930 mm (about 24.4 to 36.6 in) includes the roughly 32 in etrailer gives, and at 38.6 lb it leaves about 126 lb of a 165 lb Thule rating for gear. At 76 in long and 32 in wide it leaves room for the liftgate and a little room on 50 in bars. The one fit question is the clamp: Rhino-Rack says it works directly with its Vortex and Euro bars and needs the RUBK-MF kit for its Heavy Duty bars, so confirm it clamps to your Thule, Hyundai or Amazon bars before you order.",
   "who": "Palisade owners who want a light, mid-size box with a real cargo rating and a 5-year warranty.",
   "specs": [["Volume", "15.5 cu ft (440 L)"], ["Exterior", "76 × 32 × 17 in"], ["Interior", "74 × 30 × 15 in"], ["Box weight", "38.6 lb"], ["Max load", "75 kg (about 165 lb)"], ["Crossbar spacing", "620–930 mm (about 24.4–36.6 in)"], ["Opening / locks", "Dual-side; 3 locking points"], ["Warranty", "5 years"]]},
  {"asin": "B0DYWCZSD8", "role": "Best box plus bike", "price": "$799",
   "pros": ["26.5 in wide, leaving about 23.5 in on 50 in bars", "Skis and boards up to 195 cm", "Dual-side opening", "Full metal locking handles lock the lid and mounts", "Limited lifetime warranty"],
   "cons": ["12 cu ft for $799", "Crossbar spread not published; confirm against 32 in", "84 in long; check the hatch once"],
   "body": "A full-width box on 50 in Palisade bars leaves little room for anything else. The SkyBox NX Skinny is Yakima's answer: 84 x 26.5 x 16 in and 12 cu ft, narrow enough to leave roughly 23.5 in of bar for a bike or ski mount beside it. It takes skis and boards up to 195 cm, opens from both sides, and its full metal handles lock both the lid and the mounts. Yakima lists it at $799 (regular $949.99) with SKS locks and a limited lifetime warranty, and says it fits StreamLine and most factory or aerodynamic crossbars.\n\nWeight is the thing to watch, because the bike mount and bike share the same bar rating as the box. At 43 lb, the box plus a roof bike mount and a bike can take a large share of a 165 lb Thule rating before any cargo goes in; Hyundai's 220 lb accessory bars leave more room, up to the 220 lb roof rails figure. Yakima's page doesn't list a crossbar spread for this model, so confirm it against the Palisade's roughly 32 in spread on the listing or with Yakima. The 84 in length suits the Palisade's roughly 71 in hatch clearance if mounted forward.",
   "who": "Palisade owners who want locked storage and a bike or skis on the roof at the same time.",
   "specs": [["Volume", "12 cu ft"], ["Exterior", "84 × 26.5 × 16 in"], ["Box weight", "43 lb"], ["Ski length", "Up to 195 cm"], ["Opening", "Dual-side"], ["Lock", "SKS; locks lid and mounts"], ["Crossbar spread", "Not published; confirm"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B09HC2LWX8", "role": "Lightest box", "price": "$649",
   "pros": ["30.2 lb, the lightest hard box here", "Published 100 lb max load", "60 in long, far from the hatch", "23 in wide, leaving about 27 in of bar", "Made in the USA; limited lifetime warranty"],
   "cons": ["Needs a 32–46 in spread; 32 in is its minimum", "10 cu ft; no skis", "100 lb cargo cap"],
   "body": "The DeepSpace 10 is the lightest hard box here and one of the few with a published cargo rating. Yakima lists it at 10 cu ft, 60 x 23 x 16 in and 30.2 lb, with a 100 lb maximum load, integrated tie-down points, a wide opening, an SKS lock and a textured ABS shell. It is made in the USA with a limited lifetime warranty, and Yakima lists it at $649 (regular $869.99). Yakima says it installs in about 10 minutes on existing crossbars.\n\nOn a Palisade, its narrow 23 in shell leaves about 27 in of a 50 in Thule bar free for bikes or a kayak, and at 60 in it sits nowhere near the hatch. The fit question is spread. Yakima requires 32 to 46 in between the bars, and etrailer gives the Palisade's spread as about 32 in, which is exactly its minimum. Measure your own bars center to center; if they sit a little closer, slide clamp-on bars apart if your kit allows. At 10 cu ft it is a weekend-bag box, not a ski box.",
   "who": "Palisade owners who want a light, narrow box and room for a second carrier.",
   "specs": [["Volume", "10 cu ft"], ["Exterior", "60 × 23 × 16 in"], ["Box weight", "30.2 lb"], ["Max load", "100 lb"], ["Crossbar spread", "32–46 in"], ["Material", "Textured ABS"], ["Made in", "USA"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "price": "$864.97 (etrailer)",
   "pros": ["11 in tall, the lowest box here", "24–39 in spread covers 32 in", "Tool-free Memory Mount hardware for round, square, aero and factory bars", "Dual-side opening; key only comes out when the lid is closed", "Limited lifetime warranty"],
   "cons": ["11 cu ft", "110 lb cargo rating", "More per cubic foot than the 16s"],
   "body": "If your Palisade parks in a garage, the INNO Wedge 660 is the box most likely to clear the door. etrailer lists it at 80 x 33 x 11 in with 11 cu ft, an interior of 72 x 25-5/8 x 8-1/2 in, a 42 lb box weight and a 110 lb maximum load. It fits spreads from 24 to 39 in with tool-free Memory Mount hardware, opens from both sides, and its key can't be removed unless the lid is closed properly. etrailer lists a limited lifetime warranty and a price of $864.97; the Amazon listing says it is made in Japan.\n\nThe Palisade's roughly 32 in spread sits near the middle of the INNO's range, so bar position is easy. At 11 in tall it is 4 to 7 in lower than the other hard boxes here, which matters on a tall three-row SUV. The trade-off is volume: 11 cu ft holds 6 to 8 pairs of skis or 4 to 6 snowboards, per etrailer, or a few soft duffels, not a family's bulky camping gear. Its own 110 lb cargo rating sits below either bar rating, so it is the number to pack to.",
   "who": "Palisade owners with a low garage who carry skis or a few soft bags.",
   "specs": [["Volume", "11 cu ft"], ["Exterior", "80 × 33 × 11 in"], ["Interior", "72 × 25-5/8 × 8-1/2 in"], ["Box weight", "42 lb"], ["Max load", "110 lb"], ["Crossbar spread", "24–39 in"], ["Mount", "Memory Mount, tool-free"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0012INT98", "role": "Best budget", "price": "$139.99 (RealTruck)",
   "pros": ["18 cu ft for $139.99", "Welded seams and a waterproof zipper, per RealTruck", "Works with or without a roof rack", "Folds into a stuff sack", "Straps and car clips included"],
   "cons": ["No lock", "Soft sides; no skis", "1-year warranty"],
   "body": "For one or two road trips a year, a soft carrier gets the third-row luggage out of the cabin for a fraction of a hard box's price. RealTruck lists the Rightline Gear Sport 3 at 18 cu ft and 48 x 36 x 18 in, with welded seams and an SZIP waterproof zipper that Rightline calls 100 percent waterproof with no zipper flap needed. It is made for SUVs and minivans with or without a roof rack, and includes four attachment straps, four car clips and a stuff sack. RealTruck lists it at $139.99 with a one-year warranty, and showed it as temporarily unavailable when we checked.\n\nOn a Palisade, crossbars give the straps the best anchor; the flush rails leave no gap to loop a strap under, so without bars the kit's car clips at the door openings do the work. At 48 in long it stays well clear of the liftgate. There is no lock, so empty it overnight, and pack it full so the sides don't flap. Its contents count against the same bar rating and roof limit as any box. When the trip is over, it folds away and the drag goes with it.",
   "who": "Occasional travelers who want 18 cu ft of dry roof space for under $150.",
   "specs": [["Volume", "18 cu ft"], ["Size", "48 × 36 × 18 in"], ["Type", "Soft carrier"], ["Weatherproofing", "Welded seams, SZIP waterproof zipper"], ["Mounting", "With or without roof rack; 4 straps, 4 car clips"], ["Lock", "None"], ["Warranty", "1 year"], ["Price", "$139.99 (RealTruck)"]]},
 ],
 "install": [
  "Fit flush-rail crossbars that name the 2020–2025 Palisade (Thule kit 6008, Hyundai accessory bars or a flush-rail set) and torque them to spec.",
  "Note your bar rating (165 lb Thule, 220 lb Hyundai accessory per its guide) and the 220 lb roof rails figure on Hyundai's spec sheets, and plan the load under the lowest one.",
  "Measure the bar spread center to center (about 32 in per etrailer) and confirm it sits inside the box's range, especially for the DeepSpace 10 (32 in minimum).",
  "With a helper and a step stool, set the box on the bars, center it, and slide it forward toward the windshield, clear of the sunroof opening if you have one.",
  "Snug the clamps, open the liftgate slowly to check the gap, then tighten to the box maker's spec and lock the box and mounts.",
  "Load heavy items low and centered between the bars, keep the sunroof closed while driving, and recheck the clamps after the first drive.",
 ],
 "avoid": [
  {"h": "Raised-rail towers on flush rails", "body": "The Palisade's rails have no gap underneath. Towers made to wrap a raised rail won't clamp securely."},
  {"h": "Assuming 220 lb on every bar", "body": "Hyundai's spec sheets print 220 lb for the roof rails, and owners quote the same figure from Hyundai's accessory crossbar guide. Thule's Palisade system is rated at 165 lb. The lowest number applies."},
  {"h": "Ignoring the DeepSpace 10's 32 in minimum", "body": "The Palisade's spread is about 32 in, exactly the DeepSpace 10's minimum. Measure your bars before ordering it."},
  {"h": "Buying 2026 Palisade bars for a 2020–2025", "body": "The 2026 is a new generation. The box carries over; the bars should name your years."},
 ],
 "verdict": {
  "thesis": "Fit flush-rail crossbars that name the 2020–2025 Palisade, then choose the Yakima SkyBox 16 for most families, the Thule Motion 3 XXL for the most volume, or the Rightline Sport 3 on a budget.",
  "body": "The first-gen Palisade makes a cargo box easy once the right bars are on: about 32 in of spread fits every box here with a published range, and about 71 in of hatch clearance means even long boxes can go on if mounted forward. The SkyBox 16 is the balanced pick at $599, the Motion 3 XXL is for full-crew trips packed light, and the Rhino-Rack MasterFit 440 is a light mid-size box with a 5-year warranty if its clamp suits your bars. The NX Skinny leaves room for bikes, the DeepSpace 10 is the lightest hard box if your spread reaches 32 in, the INNO Wedge 660 is for low garages, and the Rightline Sport 3 is the budget soft option. Your bars' rating and Hyundai's 220 lb roof rails figure decide how full any of them gets, and the lowest number applies.\n\nStart with the bars: our Palisade roof rack page lists flush-rail crossbars that name 2020–2025. For heavy gear, a hitch cargo carrier takes weight off the roof. Hyundai's spec sheets list no tow hitch as equipment, so look under the rear bumper and add a trailer hitch if there is none. Floor liners protect all three rows on muddy trips. The Kia Telluride is a related SUV, but check each vehicle's own fit.",
 },
 "sources": [
  ["Yakima SkyBox 16 Carbonite (Yakima)", "https://yakima.com/collections/roof-boxes/products/skybox-16-carbonite-2014-2023"],
  ["Yakima SkyBox NX Skinny (Yakima)", "https://yakima.com/products/skybox-nx-skinny"],
  ["Yakima DeepSpace 10 (Yakima)", "https://yakima.com/collections/roof-boxes/products/deepspace-10"],
  ["Thule Motion 3 XXL (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-motion-3-xxl-_-639950"],
  ["Thule Motion 3 spread and warranty (etrailer)", "https://www.etrailer.com/Roof-Box/Thule/TH59PN.html"],
  ["Rhino-Rack MasterFit Roof Box 440L RMFT440 (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-racks/roof-boxes/roof-boxes/masterfit-roof-box-440l-black-_rmft440"],
  ["INNO Wedge 660 (etrailer)", "https://www.etrailer.com/Roof-Box/Inno/INBRM660BK.html"],
  ["Rightline Gear Sport 3 (RealTruck)", "https://realtruck.com/p/rightline-gear-cargo-bags/rlg-100s30/"],
  ["Palisade crossbar spread and hatch clearance for a Thule box (etrailer)", "https://www.etrailer.com/answers.aspx?AnswerModel=Palisade&Manufacturer=Thule&Filter=fit&AnswerMake=Hyundai"],
  ["Hyundai accessory crossbar 220 lb limit, owner thread (Palisade Forums)", "https://palisadeforums.org/threads/cross-bars.912/"],
  ["2020–2025 Palisade Thule complete rack, kit 6008 (The Rack Shop)", "https://therackshop.com/2020-2025-hyundai-palisade-w-flush-rails-thule-crossbar-complete-roof-rack/"],
  ["2020 Palisade specifications: roof rails load capacity, trailer weight (Hyundai)", "https://www.hyundainews.com/assets/documents/original/40272-2020PalisadeSpecifications.pdf"],
  ["2023 Palisade specifications: roof rails load capacity, trailer weight (Hyundai)", "https://www.hyundainews.com/assets/documents/original/50303-2023PalisadeProductSpecs20220630.pdf"],
  ["2024 Palisade specifications: roof rails load capacity, trailer weight (Hyundai)", "https://www.hyundainews.com/assets/documents/original/56241-2024PalisadeSpecs020323.pdf"],
  ["Hyundai Palisade: related models (Wikipedia)", "https://en.wikipedia.org/wiki/Hyundai_Palisade"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Palisade roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B001PUZXGK","Yakima SkyBox 16 Carbonite Rooftop Cargo Box, 16 cu ft (15 in tall)","Yakima","$550–$750",{},"Universal box; 24-34.5 in spread covers ~32 in. Confirm spread and hatch clearance."),
 ("B0F8PNL8H9","Thule Motion 3 XXL 21 cu ft Rooftop Cargo Box with GoPack Duffel Set, 165 lb load capacity","Thule","$1,200–$1,500",{},"Bundle listing; universal box, 57.2 lb. Confirm spread and hatch clearance."),
 ("B07B4P7WYX","Rhino-Rack MasterFit Roof Box 440L (Black)","Rhino-Rack","See listing",{},"Universal box; 620-930 mm spread. Confirm the clamp fits your crossbars."),
 ("B0DYWCZSD8","Yakima SkyBox NX Skinny 12 cu ft Cargo Box (26.5 in wide)","Yakima","$700–$850",{},"Universal narrow box; spread not published, confirm against ~32 in."),
 ("B09HC2LWX8","Yakima DeepSpace 10 Hard Shell Cargo Box, 10 cu ft (100 lb max)","Yakima","$550–$700",{},"Needs 32-46 in spread; Palisade ~32 in is the minimum, confirm your bars."),
 ("B06VX9L59C","INNO BRM660BK Wedge Cargo Box, 11 cu ft, Gloss Black","INNO","$850–$1,000",{},"Universal low box (11 in tall); 24-39 in spread. Confirm spread on your bars."),
 ("B0012INT98","Rightline Gear Sport 3 Waterproof Rooftop Cargo Carrier, 18 cu ft, Black","Rightline Gear","$120–$160",{},"Universal soft carrier, no lock; confirm strap routing on flush rails or bars."),
]
