"""Long-form article — Best Running Boards, Side Steps & Rock Sliders for 2020–2026 Jeep Gladiator (JT).
No invented hands-on testing: fit facts come from the Amazon listing titles recorded in FITS (found 2026-10-05 through
amazon.com-restricted searches); specs and prices come from the maker and retailer pages in sources (read 2026-10-05):
Quadratec (Rough Country 90762, Go Rhino 684451687T, AMP Research 75135-01A), Fat Bob's Garage (Rough Country ESR610530
power boards and 90802 rock sliders) and Westin's Outlaw Drop page. Vehicle facts: Wikipedia's JT page (137.3 in
wheelbase, 218.0 in length, model years, Willys rock rails, Texas Trail side steps), Wikipedia's JL page (118.4 in
4-door wheelbase) and Jeep's 2025 Gladiator press kit (steel rock rails listed under Willys, Rubicon, Mojave, Mojave X
and Rubicon X).
Not read, and worded as such in the text: any TAC, Hooke Road or Rock Slide Engineering page (title-only details);
whether any kit other than Rough Country's 90762 needs factory rock rails removed; factory rock rails by trim for model
years before 2025; EcoDiesel fit; the part number behind the Rough Country power board listing (the Amazon title has
none). The AMP Research ASIN was recorded from a result titled "AMP Research 75135-01A PowerStep Electric Running Boards
for 2020-2021 Jeep Gladiator, Black"; the same ASIN also appears under a general RealTruck title with no vehicle in it,
and the text says so.
"""

KEY = ("jeep", "gladiator", "2020-present", "running-boards")

TITLE = "Best Running Boards & Rock Sliders for 2020–2026 Jeep Gladiator JT: 7 Picks, Steps to Sliders"
META = ("Seven Jeep Gladiator JT side steps, from TAC tube bars to AMP Research power steps and Rough Country rock "
        "sliders, with factory rock rail notes by trim.")

FAQ = [
 ("Do Wrangler JL Unlimited running boards fit the Gladiator?",
  "Do not assume so. The Gladiator is based on the Wrangler JL, but Wikipedia lists a 137.3 in wheelbase for the JT against 118.4 in for the 4-door Wrangler Unlimited, a gap of 18.9 in. The makers we read sell the two as separate parts. Westin's Outlaw Drop is 20-14165 for the 2020–2026 Gladiator and 20-14065 for the 2018–2026 Wrangler 4-door, and Quadratec lists Rough Country's 90762, Go Rhino's 684451687T and AMP Research's 75135-01A for the Gladiator JT by name. Buy a step whose title or fit list names the Gladiator JT and your model year."),
 ("Does my Gladiator already have factory rock rails?",
  "Look under the doors, because it depends on trim and year. Jeep's 2025 Gladiator press kit lists steel rock rails for the cab and bed corners on the Willys and the Rubicon, and steel rock rails for the cab on the Mojave. The Mojave X and Rubicon X add steel rock rails for the bed corners. In the kit we read, rock rails are named only under those trims. Wikipedia also notes standard rock rails on the Willys and black side steps on the Texas Trail edition. We did not read a Jeep release for every earlier model year, so treat this as a guide and check your own truck or its window sticker."),
 ("Do I have to remove the factory rock rails to fit side steps?",
  "For one pick, yes. For the rest, we could not confirm. Quadratec's page for Rough Country's 90762 Contoured Drop Steps says that if the Jeep has factory Rubicon rock rails, they have to be removed before the steps go on. The Quadratec pages for Go Rhino's OE Xtreme and AMP Research's PowerStep, Westin's Outlaw Drop page and the Fat Bob's Garage pages for Rough Country's power boards and rock sliders say nothing about factory rails either way. Westin lists its Gladiator part as a body mount. If you own a Willys, Rubicon or Mojave, ask the seller in writing whether the kit replaces the rails or bolts beside them."),
 ("Are power running boards worth it on a Gladiator?",
  "They are the only type that gives a low step without a permanent clearance cost. A fixed step hangs under the rocker all the time, and on a truck with a 137.3 in wheelbase the middle of the truck is what meets a ledge first. A power step drops when a door opens and folds up when it closes. The price is real: Quadratec lists AMP Research's PowerStep 75135-01A at $2,099.99, and Fat Bob's Garage lists Rough Country's power boards at $1,099.95. The retailers estimate 3 to 5 hours of installation. If the truck stays on pavement, a fixed drop step does the same job for a fraction of that."),
 ("What is the difference between a tube step, a drop step and a rock slider?",
  "A tube step, or nerf bar, is a tube along the rocker with a pad at each door. Go Rhino's 4 in OE Xtreme and TAC's 3 in side bars are that type. A drop step puts the pad below the bar for a lower first step: Westin's Outlaw Drop has a 4 in drop plate, and Rough Country's Contoured Drop Steps tuck a flush rail against the body with a step under each door. A rock slider is armor first. Rough Country's 90802 is 1/8 in steel, bolts to the frame and has a top you can stand on. Sliders give the highest step and the most protection. Drop steps give the lowest step and the least clearance."),
 ("How much weight can Gladiator side steps hold?",
  "It depends on the product, and only three of the seven picks publish a figure on the pages we read. Fat Bob's Garage lists Rough Country's power boards at up to 660 lb on each side. Quadratec lists AMP Research's PowerStep at 600 lb per side and Rough Country's Contoured Drop Steps as capable of handling up to 465 lb, without saying whether that is per side. The Go Rhino, Westin and rock slider pages give no rating, and TAC's listing title gives none. Ask the seller for a figure if a heavy rider will use the step, and never use a step as a jacking point unless the maker says it is built for that."),
 ("Do I need to drill to install Gladiator side steps?",
  "Not for the picks whose pages address it. Westin lists the Outlaw Drop as a bolt-on installation with no drilling required and with brackets included. Quadratec describes Go Rhino's OE Xtreme as a channel-mount, non-drill installation. Fat Bob's Garage lists Rough Country's power boards as a no-drill install on factory mounting points, and its 90802 rock sliders as a 100 percent bolt-on frame mount. Quadratec's pages for the 90762 drop steps and the AMP PowerStep list brackets and install times but do not use the words no drilling, and TAC's listing title does not say. Power steps add a wiring job on top of the brackets."),
 ("Will a listing that stops at 2023 or 2025 fit a 2026 Gladiator?",
  "Often, but confirm it. The JT has been one generation since the 2020 model year, and retailers list longer ranges than some Amazon titles do. Quadratec lists Go Rhino's 684451687T for 2020–2027 while the Amazon title says 20-23, and Westin lists its Outlaw Drop 20-14165 for 2020–2026. AMP Research's Amazon title names only 2020–2021, and Rough Country's rock slider title stops at 2022. Send the seller your model year and the part number and ask for a yes in writing. Some listings say 2019. Wikipedia gives April 2019 as the start of production and 2020 as the first model year, so that is the same truck."),
 ("Do these steps fit the Rubicon, the Mojave and the EcoDiesel?",
  "None of the listing titles on this page is limited to a trim, and the retailer pages we read list the Gladiator JT without excluding one. Rough Country's pages say 4WD. What changes by trim is what is already bolted on. Jeep's 2025 press kit lists steel rock rails on the Willys, Rubicon and Mojave, and Rough Country's drop steps need factory Rubicon rails removed. Rough Country's power boards are also listed as not fitting trucks with Mopar's Tire Deflector Bracket, parts 68637397AB and 68640856AB. None of the pages names or excludes the 3.0L EcoDiesel offered in select years, so diesel owners should ask the seller before ordering."),
 ("Will side steps hurt my Gladiator's off-road clearance?",
  "Yes, by however far they hang below the rocker. Approach and departure angles are set by the bumpers, so steps do not change them, but breakover and side clearance drop. That matters more on a Gladiator than on a Wrangler, because the wheelbase is 18.9 in longer than the 4-door Wrangler's by Wikipedia's figures. A drop step such as Westin's Outlaw Drop, with its 4 in drop plate, sits lowest. A straight tube or a slider keeps more, and a power step keeps all of it when the doors are closed. For rocks, pick a frame-mounted slider or keep the factory rock rails your trim came with."),
]

ARTICLE = {
 "dek": "Seven side steps and rock sliders listed for the Gladiator JT, from TAC's 3 in tube bars to AMP Research's PowerStep, with Rough Country drop steps, power boards and frame-mounted sliders in between. One body makes length easy. The traps are Wrangler parts that never name the JT and the factory rock rails that some trims already carry.",
 "author": "jake-morrison",
 "reviewed": "2026-10-05",
 "method": "We did not install these parts ourselves. We chose them from Amazon listings whose titles name the 2020–2026 Jeep Gladiator JT, then ranked them on the specs published by Westin on its own site and by Quadratec and Fat Bob's Garage on their product pages, read in October 2026: material, load rating, mounting, install time, warranty and price. Vehicle facts come from Wikipedia's JT and JL pages and from Jeep's 2025 Gladiator press kit. We could not open a maker or retailer page for TAC or Hooke Road, so those details come from the listing titles only and are marked that way. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Buy Gladiator parts, not Wrangler parts.** Wikipedia lists a 137.3 in wheelbase for the JT and 118.4 in for the 4-door Wrangler, and Westin sells a separate part number for each.",
  "**Look under the doors first.** Jeep's 2025 press kit lists steel rock rails on the Willys, Rubicon and Mojave.",
  "**One pick needs the factory rails off.** Quadratec says Rough Country's 90762 drop steps require removing factory Rubicon rock rails. The other pages do not say.",
  "**Power steps keep clearance.** AMP Research is rated 600 lb per side and Rough Country 660 lb per side, per their retailers.",
  "**Titles lag the fit lists.** Amazon titles here stop at 2021, 2022, 2023 and 2025 while retailers list later years. Confirm your year.",
 ],
 "top_picks": [
  {"asin": "B081569DCW", "role": "Best overall", "why": "Rough Country 90762 drop steps, 465 lb rating, 3-year warranty, 1 to 2 hour install"},
  {"asin": "B0BWSH5DLW", "role": "Best power steps", "why": "Rough Country power boards, 660 lb per side, LED lights, no-drill mount"},
  {"asin": "B08CMXHNGT", "role": "Best tube step", "why": "Go Rhino 4 in OE Xtreme, 87 in long, non-drill channel mount, 5-year warranty on black"},
  {"asin": "B09XN9F4VT", "role": "Best for trails", "why": "Rough Country 90802, 1/8 in steel, frame-mounted bolt-on slider with a step top"},
  {"asin": "B07YXB1MN6", "role": "Best budget", "why": "TAC 3 in black side bars listed for the 2020–2025 Gladiator JT"},
 ],
 "fit_table": {
  "caption": "2020–2026 Gladiator JT: what decides step fit",
  "head": ["Variable", "Versions", "What to do"],
  "rows": [
   ["Body", "One: four-door cab and 5 ft bed", "No cab or bed choice; a Gladiator-specific step is the right length"],
   ["Wrangler parts", "Wrangler 4-door: 118.4 in wheelbase; Gladiator: 137.3 in (Wikipedia)", "Buy only parts whose title or fit list names the Gladiator JT"],
   ["Factory rock rails", "Willys, Rubicon: cab and bed corners; Mojave: cab (Jeep 2025 press kit)", "Look under the doors; ask whether the kit replaces the rails"],
   ["Model year", "2020–2026; listing titles stop at 2021 to 2025", "Confirm your year and the part number with the seller"],
   ["Mopar Tire Deflector Bracket", "Parts 68637397AB and 68640856AB", "Rough Country's power boards are listed as not fitting"],
   ["Step type", "Tube, drop step, slider, power step", "Slider or power step for trails; drop step for easy entry"],
  ],
 },
 "look_for": [
  {"h": "The Gladiator is not a long Wrangler",
   "body": "The Gladiator is based on the Wrangler JL, and from the front seats forward the two share a great deal. For side steps, treat them as different vehicles. Wikipedia lists the JT at a 137.3 in wheelbase and 218.0 in overall, against 118.4 in and 188.4 in for the 4-door Wrangler Unlimited. Makers sell them as separate applications. Westin's Outlaw Drop table gives 20-14165 for the 2020–2026 Gladiator and 20-14065 for the 2018–2026 Wrangler 4-door, and Quadratec lists Rough Country's 90762, Go Rhino's 684451687T and AMP Research's 75135-01A for the Gladiator JT by name. We found no maker page that lists one step for both. A listing that says only Wrangler JL, or names the JL and JT together, needs the Gladiator part number confirmed before you pay."},
  {"h": "Factory rock rails by trim",
   "body": "Many Gladiators leave the factory with something already bolted under the doors. Jeep's 2025 press kit lists steel rock rails for the cab and bed corners on the Willys and the Rubicon and steel rock rails for the cab on the Mojave, and it adds bed-corner rails to the Mojave X and Rubicon X. Wikipedia notes black side steps on the Texas Trail edition. We did not read a Jeep release for each earlier year, so check your own truck. This matters because a step and a rail compete for the same space. Quadratec says Rough Country's 90762 drop steps need factory Rubicon rock rails removed first. The other pages we read are silent, so ask each seller whether the kit replaces the rails or mounts beside them."},
  {"h": "Breakover on a 137.3 in wheelbase",
   "body": "A long wheelbase helps on the highway and hurts breakover. The middle of the truck is what meets a ledge or a rut crest first, and side steps hang exactly there. So step type matters more on this truck than on a short Wrangler. A drop step is lowest: Westin's Outlaw Drop puts its step plate 4 in below the bar. A straight tube such as Go Rhino's OE Xtreme or TAC's 3 in bar tucks closer to the body. A slider like Rough Country's 90802 is built to be landed on, with 1/8 in steel and a frame mount. A power step folds away. Decide how often the truck leaves pavement before you choose how low the step should hang, and remember that the bed corners sit behind any cab-length step."},
  {"h": "Fixed or power, and what power costs",
   "body": "Two picks retract. AMP Research's PowerStep 75135-01A is the premium one. Quadratec lists an 85 in board of black-anodized, Teflon-coated aluminum, 7 in wide, rated 600 lb per side, with LED courtesy lights, a 5-year/60,000-mile warranty and a $2,099.99 price. Rough Country's power running boards cost roughly half that. Fat Bob's Garage lists them at $1,099.95 with a 6 in aluminum board, up to 660 lb on each side and LED courtesy lights, on factory mounting points with no drilling. Both deploy when a door opens. Both are a half-day job, 3 to 4 hours for AMP Research and 3 to 5 for Rough Country by the retailers' estimates, and both need wiring that the pages we read do not describe in detail. Read the instructions before you order."},
  {"h": "Ratings, finish and warranty",
   "body": "Published numbers separate the documented steps from the rest. Load ratings on the pages we read: up to 660 lb on each side for Rough Country's power boards, 600 lb per side for AMP Research, and up to 465 lb for Rough Country's 90762. Warranties: AMP Research 5 years or 60,000 miles, Go Rhino 5 years on textured black and limited lifetime on polished stainless, Westin 3 years, and Rough Country 3 years on the drop steps. Finish matters where roads are salted. Westin puts an E-coat under its textured black powder coat, Go Rhino offers stainless, and AMP Research's boards are anodized aluminum. The TAC and Hooke Road listing titles give none of this, so read those listings for material, rating and warranty before you buy on price."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Vehicle", "Gladiator JT named in the title or fit list", "Wrangler JL parts with no JT part number"],
   ["Model year", "Your year in the range, or the seller's confirmation", "Titles that stop early with no answer from the seller"],
   ["Factory rails", "Seller says whether the kit replaces or clears them", "Assuming the mounting points are free on a Willys, Rubicon or Mojave"],
   ["Load rating", "A published figure (465 to 660 lb on this page)", "\"Heavy duty\" with no number"],
   ["Mounting", "Bolt-on, no drilling, brackets included", "Kits that need drilling to fit"],
   ["Warranty", "Written terms of 3 to 5 years", "No terms stated"],
  ],
 },
 "types_table": {
  "caption": "Side step types for the 2020–2026 Gladiator JT",
  "head": ["Type", "Example", "First step", "Clearance when driving", "Price band", "Best for"],
  "rows": [
   ["Power step (premium)", "AMP Research PowerStep 75135-01A", "Low when deployed", "Full (folds up)", "$2,000–$2,200", "Daily drivers that also see trails"],
   ["Power step (value)", "Rough Country power running boards", "Low when deployed", "Full (folds up)", "$1,050–$1,150", "Power steps for about half the price"],
   ["Contoured drop step", "Rough Country 90762", "Low at each door", "Low to medium", "$380–$420", "Most trucks without factory rails"],
   ["Drop nerf bar", "Westin Outlaw Drop 20-14165", "Lowest (4 in drop plate)", "Low", "$490–$530", "Lifted trucks, shorter riders"],
   ["Tube step", "Go Rhino 4 in OE Xtreme; TAC 3 in", "Medium", "Medium", "$320–$430 (Go Rhino)", "A simple step close to the body"],
   ["Rock slider", "Rough Country 90802", "High", "Best of the fixed types; built for impacts", "$480–$520", "Rock trails"],
   ["Slider with power step", "Rock Slide Engineering BD-SS-301-JT4 (product list)", "Confirm on listing", "Confirm on listing", "Check listing", "2024–2025 trucks, per the listing title"],
   ["Flat running board", "No pick", "Low and wide", "Low", "Check listing", "Family trucks; we found no brand-name board whose Amazon title names the JT"],
  ],
 },
 "picks": [
  {"asin": "B081569DCW", "role": "Best overall", "price": "$380–$420",
   "pros": ["Rated for up to 465 lb (Quadratec)", "All-steel construction with a textured black powder coat", "Laser-cut tread under each door", "1 to 2 hour install with brackets and hardware included", "3-year limited warranty"],
   "cons": ["Factory Rubicon rock rails must come off first", "Fixed step, so it costs some clearance", "Amazon title stops at 2025; confirm 2026"],
   "body": "Rough Country's Contoured Drop Steps, part 90762, are the fixed step with the best mix of documentation and price on this page. The Amazon title lists them for the Jeep Gladiator JT, 2020–2025, as flush-fit rails with side steps, and Quadratec lists the same part number for the 2020–2027 Gladiator JT. The design is a rail that follows the body with a formed step under each door, so it looks closer to a factory part than a round tube does. Quadratec describes all-steel construction, a textured black powder coat and laser-cut tread, and says the steps are capable of handling up to 465 lb. The page gives a total length of 64 in and does not say whether the rating is per side.\n\nQuadratec lists them at $399.95 plus a $75 shipping surcharge, with a 3-year limited warranty and an install time of 1 to 2 hours using the included brackets and hardware. One fit note decides whether this is your step: Quadratec says that if the Jeep has factory Rubicon rock rails, they have to be removed before the Contoured Drop Steps go on. Jeep's 2025 press kit also lists steel rock rails on the Willys and Mojave, so owners of those trims should ask the same question. The Amazon title stops at 2025, so a 2026 owner should confirm the part number with the seller.",
   "who": "Owners of trucks without factory rock rails who want a low step at each door with a published rating and warranty.",
   "specs": [["Part #", "Rough Country 90762"], ["Type", "Contoured drop step, fixed"], ["Fits", "Gladiator JT 2020–2025 (listing title); 2020–2027 (Quadratec)"], ["Material", "Steel, textured black powder coat"], ["Load rating", "Up to 465 lb (Quadratec)"], ["Length", "64 in (Quadratec)"], ["Install", "1–2 hr, brackets and hardware included"], ["Factory rails", "Rubicon rock rails must be removed (Quadratec)"], ["Warranty", "3-year limited"]]},
  {"asin": "B07XBWD6WM", "role": "Best premium power step", "price": "$2,000–$2,200",
   "pros": ["Folds up when the doors close, so nothing hangs below the rocker", "Rated 600 lb per side (Quadratec)", "85 in black-anodized, Teflon-coated aluminum boards", "Built-in LED courtesy lights", "5-year/60,000-mile warranty; built in the USA per Quadratec"],
   "cons": ["The most expensive pick on this page", "Amazon listing title names only 2020–2021", "3 to 4 hour install with wiring"],
   "body": "AMP Research's PowerStep is the reference power step, and part 75135-01A is the Gladiator version. Quadratec lists it for the 2020–2027 Gladiator JT and describes boards that deploy automatically when a door opens and retract when it closes. The board is 85 in of extruded aluminum, black-anodized and Teflon coated, 7 in wide with a 7 in drop, and rated at 600 lb per side, with built-in LED courtesy lights. Quadratec says AMP Research engineers and builds its PowerSteps in the USA and backs them with a 5-year/60,000-mile warranty.\n\nThe cost is the obstacle. Quadratec lists the 75135-01A at $2,099.99 plus a $75 shipping surcharge and rates the install at 3 to 4 hours, intermediate difficulty. The page does not mention factory rock rails, so Willys, Rubicon and Mojave owners should ask whether the linkage brackets clear the rails or replace them. Read the Amazon listing with care. The title we recorded for this ASIN names the 75135-01A for the 2020–2021 Jeep Gladiator, and the same ASIN also appears under a general RealTruck AMP Research title that says Plug-N-Play and names no vehicle. Before ordering, check the part number and the vehicle shown on the listing, and ask the seller to confirm your model year.",
   "who": "Owners who use the truck daily and off-road and will pay for a step that disappears when the doors close.",
   "specs": [["Part #", "AMP Research 75135-01A"], ["Type", "Power-retractable step"], ["Fits", "2020–2021 Gladiator (listing title); 2020–2027 JT (Quadratec)"], ["Board", "85 in extruded aluminum, 7 in wide"], ["Finish", "Black anodized, Teflon coated"], ["Load rating", "600 lb per side"], ["Lights", "Built-in LED courtesy lights"], ["Install", "3–4 hr, intermediate (Quadratec)"], ["Warranty", "5 years / 60,000 miles"]]},
  {"asin": "B0BWSH5DLW", "role": "Best value power step", "price": "$1,050–$1,150",
   "pros": ["Up to 660 lb on each side (Fat Bob's Garage)", "Deploys when a door opens and folds away when it closes", "Integrated LED courtesy lights", "No-drill install on factory mounting points", "Roughly half the price Quadratec lists for AMP Research"],
   "cons": ["Not for trucks with Mopar's Tire Deflector Bracket", "3 to 5 hour install", "Amazon title gives no part number; match it on the listing"],
   "body": "Rough Country's power running boards put a retracting step on a Gladiator for about half of what AMP Research costs. The Amazon title lists them for the Jeep Gladiator JT, 2020–2025, as retractable electric side steps with dual motors, LED lights and a textured anti-slip surface. The retailer Fat Bob's Garage lists Rough Country's Gladiator power boards as part ESR610530 for the 2020–2026 JT 4WD at $1,099.95. Its page describes lightweight aluminum boards 6 in wide with a textured anti-slip coating, a high-torque motor system that deploys the board when a door opens, and integrated LED courtesy lights that light the board when it is down. Each side is listed as supporting up to 660 lb, the highest rating on this page.\n\nThe retailer lists a no-drill installation on factory mounting points and estimates 3 to 5 hours. It words the warranty as a \"5-Year limited lifetime replacement warranty\" against structural and workmanship defects, so confirm the term on the listing. One exclusion is specific to this truck: the boards do not fit models equipped with Mopar's Tire Deflector Bracket, the frame support sold as 68637397AB and 68640856AB. The Amazon title carries no part number and stops at 2025, so match the part number on the listing to ESR610530 before you rely on these specs, and ask about 2026. The page says nothing about factory rock rails.",
   "who": "Owners who want power steps and would rather keep about $1,000 for tires or a lift.",
   "specs": [["Part #", "ESR610530 (Fat Bob's Garage); not in the Amazon title"], ["Type", "Power-retractable step"], ["Fits", "Gladiator JT 2020–2025 (listing title); 2020–2026 4WD (retailer)"], ["Board", "Aluminum, 6 in wide, anti-slip coating"], ["Load rating", "Up to 660 lb each side"], ["Lights", "Integrated LED courtesy lights"], ["Install", "3–5 hr, no drilling"], ["Exclusion", "Mopar Tire Deflector Bracket 68637397AB / 68640856AB"], ["Warranty", "5-year limited (retailer wording); confirm on listing"]]},
  {"asin": "B08CMXHNGT", "role": "Best tube step", "price": "$320–$430",
   "pros": ["87 in long with a flat non-slip pad at each door opening", "Channel-mount, non-drill installation (Quadratec)", "Welded-in end caps", "5-year limited warranty on textured black; limited lifetime on stainless", "Polished stainless version, 684451687PS, also listed"],
   "cons": ["No published load rating", "Amazon title says 20-23; confirm later years", "Higher first step than a drop step"],
   "body": "Go Rhino's 4 in OE Xtreme is the plain tube step from a known maker. The Amazon title names part 684451687T, 4 in OE Xtreme side steps with a mounting bracket kit, for the Jeep 20-23 Gladiator. Quadratec lists the same part number in textured black for the 2020–2027 Gladiator JT, alongside a polished stainless version, 684451687PS. Quadratec's page describes an 87 in step with welded-in end caps in the matching finish, a large flat non-slip pad at each door opening, and channel-mount construction that allows a non-drill installation in an estimated 1 to 2 hours.\n\nQuadratec shows the textured black version at $324.99 against a $422.49 list price, which puts it below the other brand-name fixed steps we could price. The warranty is 5 years limited on black and limited lifetime on stainless. A straight bar sits closer to the rocker than a drop step, so it costs less clearance and gives a higher first step. That is the right trade for a stock-height truck and the wrong one for a lifted truck with short passengers. The page gives no load rating and no note about factory rock rails, so ask the seller both questions. The Amazon title stops at 2023 while Quadratec lists the part through 2027. Confirm the part number against your model year before ordering.",
   "who": "Stock-height trucks that need a simple bolt-on step with a 5-year warranty.",
   "specs": [["Part #", "Go Rhino 684451687T (black) · 684451687PS (stainless)"], ["Type", "4 in tube side step"], ["Fits", "Jeep 20-23 Gladiator (listing title); 2020–2027 JT (Quadratec)"], ["Length", "87 in"], ["Step", "Flat non-slip pad at each door"], ["Mounting", "Channel mount, no drilling"], ["Install", "1–2 hr"], ["Warranty", "5-year limited (black); limited lifetime (stainless)"]]},
  {"asin": "B0B32PLL4B", "role": "Best drop nerf bar", "price": "$490–$530",
   "pros": ["4 in drop die-stamped step plate", "10-gauge steel with a fully welded cab-length top plate", "E-coat under a textured black powder coat", "Bolt-on, no drilling, brackets and hardware included", "Westin's fit table lists the Gladiator through 2026"],
   "cons": ["The drop plate hangs lowest of the fixed steps here", "3-year warranty, shorter than Go Rhino's", "Amazon title carries no part number"],
   "body": "Westin's Outlaw Drop is the step for a Gladiator that sits high. The Amazon title reads Westin Outlaw Drop Nerf StepBar, 20- Jeep Gladiator, and Westin's own application table lists part 20-14165 for the 2020–2026 Gladiator as a body-mount fit. The same table gives 20-14065 for the 2018–2026 Wrangler 4-door, so Westin treats the two as separate applications. Westin describes a 1.5 in mandrel-bent steel tube, 10-gauge steel and a fully welded cab-length top plate, with a 4 in drop die-stamped step plate that gives traction and lets dirt and mud fall through.\n\nThe finish is a textured black powder coat over an E-coat base, which Westin says gives long-lasting corrosion protection. Installation is bolt-on with no drilling required, and hardware and mounting brackets are included. Westin covers the bars for 3 years and lists the Outlaw Drop line from $493.99 to $528.99. The drop plate is both the benefit and the cost. It puts the first step 4 in below the bar, and it is the lowest fixed point on this page, so keep it off rock trails. Westin's page does not say how the brackets deal with factory rock rails, so Willys, Rubicon and Mojave owners should ask. The Amazon title has no part number, so check that the listing shows 20-14165 before you buy.",
   "who": "Lifted or tall-tired road trucks, and shorter passengers who need the lowest first step.",
   "specs": [["Part #", "Westin 20-14165 (Westin fit table)"], ["Type", "Drop nerf bar"], ["Fits", "20- Jeep Gladiator (listing title); 2020–2026 (Westin)"], ["Construction", "1.5 in mandrel-bent steel tube, 10-gauge steel, welded top plate"], ["Step", "4 in drop die-stamped plate"], ["Finish", "Textured black powder coat over E-coat"], ["Mounting", "Body mount, bolt-on, no drilling"], ["Warranty", "3 years"], ["Line price", "$493.99–$528.99 (Westin)"]]},
  {"asin": "B09XN9F4VT", "role": "Best rock slider", "price": "$480–$520",
   "pros": ["Solid one-piece, 1/8 in thick all-steel construction", "Frame mount, 100 percent bolt-on, no drilling (retailer page)", "Top of the slider can be used as a step", "Flat black powder coat", "Hardware included"],
   "cons": ["Amazon title stops at 2022; the retailer lists 2020–2023", "No published load rating", "Retailer page gives two install times and two warranty wordings"],
   "body": "A Gladiator that crawls needs armor under the cab, and Rough Country's 90802 is the slider here with a product page behind it. The Amazon title lists Rough Country Rock Sliders for the 2020–2022 Jeep Gladiator JT 4WD, part 90802. Fat Bob's Garage lists the same part as heavy-duty rock sliders for the 2020–2023 Gladiator JT 4WD at $499.95. Its page describes solid one-piece, 1/8 in thick all-steel construction in a flat black powder coat, a bolt-on frame mount that requires no drilling, and a top that can be used as a step.\n\nThe frame mount is the point. A step bar hangs from its brackets and is built for feet. A slider is tied to the frame so the rocker can come down on a rock. The retailer page is not tidy: it quotes 3 to 4 hours in the description and 1 to 2 hours in the feature list, and it describes the warranty both as a 3-year limited warranty and as a limited lifetime replacement warranty, so confirm both on the listing. It gives no load rating and does not say whether factory rock rails must come off. The Amazon title stops at 2022 and the retailer at 2023, so owners of 2024 and later trucks should get the seller's confirmation first. Willys, Rubicon and Mojave trucks with factory steel rails may not need this part at all.",
   "who": "Owners without factory rock rails who run rocky trails and want protection first and a step second.",
   "specs": [["Part #", "Rough Country 90802"], ["Type", "Rock slider with step top"], ["Fits", "2020–2022 Gladiator JT 4WD (listing title); 2020–2023 (retailer)"], ["Material", "One-piece 1/8 in steel"], ["Finish", "Flat black powder coat"], ["Mounting", "Frame mount, bolt-on, no drilling"], ["Install", "1–2 hr or 3–4 hr (retailer page gives both)"], ["Warranty", "Confirm on listing (retailer page gives two terms)"]]},
  {"asin": "B07YXB1MN6", "role": "Best budget", "price": "Check listing",
   "pros": ["Listed for the 2020–2025 Gladiator JT by name", "3 in black side bars, sold as a pair", "Straight bar stays close to the rocker", "Fixed, so no wiring", "Simple design with little to go wrong"],
   "cons": ["No maker page read; details come from the listing title only", "Material, load rating and warranty not confirmed", "Title stops at 2025; confirm 2026"],
   "body": "TAC's 3 in side bars are the budget pick, and they are here on fit, not on documentation. The Amazon title lists TAC side steps for the 2020–2025 Jeep Gladiator JT truck: 3 in black side bars, two pieces. That is everything we can state about the part. We did not open a TAC page for it, so the tube material, the coating under the black finish, the step pad design, the bracket type, the load rating and the warranty are all things to read on the listing before you order.\n\nWhat the type tells you is simpler. A 3 in bar is the slimmest step on this page. It tucks close to the rocker, so it takes little clearance, and it gives a narrow foothold instead of a platform, which suits adults more than small children. Compare it with Go Rhino's 4 in OE Xtreme, which Quadratec shows at $324.99 with a 5-year warranty on black. If TAC's live price is not well below that, the Go Rhino is the better-documented buy. Ask the seller three things: whether the brackets bolt on without drilling, whether the kit clears or replaces factory rock rails on a Willys, Rubicon or Mojave, and whether it fits a 2026. Hooke Road's rock-slider-style nerf bars in our product list are the other budget route, with the same need to read the listing.",
   "who": "Budget buyers who want a basic step on a Gladiator and will read the listing closely.",
   "specs": [["Brand", "TAC"], ["Type", "3 in tube side bar"], ["Fits", "2020–2025 Gladiator JT (listing title)"], ["Finish", "Black (listing title)"], ["Pieces", "2 (listing title)"], ["Load rating", "Not read; confirm on listing"], ["Warranty", "Not read; confirm on listing"]]},
 ],
 "install": [
  "Confirm the part number against your model year, and look under the doors for factory rock rails or side steps before you open the box.",
  "If the kit replaces factory rails, remove them first. Quadratec says Rough Country's 90762 needs factory Rubicon rock rails off.",
  "Bolt the brackets to the body or frame points hand-tight, following the maker's order for front, middle and rear brackets.",
  "With a helper, lift the bar, board or slider onto the brackets and start every bolt before tightening any.",
  "For power steps, mount the linkages and motors, route the harness away from heat and moving parts, connect it per the instructions, then open and close each door to check deploy and retract.",
  "Level each side, torque every bolt to the values in the instructions, and recheck them at the end of the first week and again when you come home from the first trail day.",
 ],
 "avoid": [
  {"h": "Wrangler JL steps with no Gladiator part number", "body": "Wikipedia lists the JT's wheelbase at 137.3 in against 118.4 in for the 4-door Wrangler, and Westin sells a separate part for each. Buy the part whose fit list names the Gladiator."},
  {"h": "Ordering before looking under the doors", "body": "Jeep's 2025 press kit lists steel rock rails on the Willys, Rubicon and Mojave. A rocker-mounted step may need them removed, as Rough Country's 90762 does."},
  {"h": "Drop steps on a trail truck", "body": "A 4 in drop plate under a 137.3 in wheelbase is the first thing to touch. Use a frame-mounted slider or a power step."},
  {"h": "Trusting a year range you have not confirmed", "body": "Titles here stop at 2021, 2022, 2023 and 2025. Retailers often list later years for the same part number, but get the seller's answer for your year."},
 ],
 "verdict": {
  "thesis": "Look under the doors, then buy Rough Country's 90762 drop steps for a bare-rocker truck, a power step from Rough Country or AMP Research if the Gladiator leaves pavement, and Rough Country's 90802 sliders if it meets rocks.",
  "body": "The Gladiator is easy to fit in one way and easy to get wrong in two. One cab and one bed mean there is no length to choose. The mistakes are buying a Wrangler part that never names the JT, and ordering before checking for the factory rock rails that Jeep's 2025 press kit lists on the Willys, Rubicon and Mojave. Past those checks, the choice follows use. Rough Country's 90762, which Quadratec lists at $399.95, gives most owners a rated step with a written warranty. Go Rhino's OE Xtreme is the simple tube, Westin's Outlaw Drop is the lowest step, and TAC is the budget bar. For trails, Rough Country's power boards and AMP Research's PowerStep keep the clearance, and the 90802 sliders protect the rocker.\n\nSteps keep mud off the sill, which is where floor liners start their work on a truck with removable doors. The bed is the usual next project: a tonneau cover to keep the 5 ft box dry, or a bed rack if you camp from the truck, since the roof comes off and cannot carry a tent. LED light bars come next for owners who drive unlit trails. Wrangler owners need their own steps, sold by door count.",
 },
 "sources": [
  ["Rough Country 90762 Contoured Drop Steps, Gladiator JT (Quadratec)", "https://quadratec.com/p/rough-country/contoured-drop-steps-gladiator-jt-90762"],
  ["AMP Research PowerStep 75135-01A, Gladiator JT (Quadratec)", "https://www.quadratec.com/p/amp-research/powerstep-jeep-gladiator-jt"],
  ["Rough Country Power Running Boards ESR610530, Gladiator JT 2020–2026 (Fat Bob's Garage)", "https://fatbobsgarage.com/products/rough-country-power-running-boards-for-jeep-gladiator-jt-4wd-2020-2026-esr610530"],
  ["Go Rhino 684451687T 4 in OE Xtreme Side Steps, Gladiator JT (Quadratec)", "https://www.quadratec.com/p/go-rhino/4-inch-oe-xtreme-side-steps-jeep-gladiator-jt/textured-black"],
  ["Westin Outlaw Drop Nerf Step Bars: specs and application table (Westin Automotive)", "https://www.westinautomotive.com/outlaw-drop-nerf-step-bars"],
  ["Rough Country Rock Sliders 90802, Gladiator JT 2020–2023 (Fat Bob's Garage)", "https://fatbobsgarage.com/products/rough-country-rock-sliders-heavy-duty-for-jeep-gladiator-jt-4wd-2020-2023-90802"],
  ["Press Kit: 2025 Jeep Gladiator, rock rails by trim (Stellantis Media)", "https://media.stellantisnorthamerica.com/newsrelease.do?id=26089"],
  ["Jeep Gladiator (JT): wheelbase, length, model years, trims (Wikipedia)", "https://en.wikipedia.org/wiki/Jeep_Gladiator_(JT)"],
  ["Jeep Wrangler (JL): 2-door and 4-door wheelbases (Wikipedia)", "https://en.wikipedia.org/wiki/Jeep_Wrangler_(JL)"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note). One body, so cond is {} unless a title limits years.
FITS = [
 ("B081569DCW","Rough Country Contoured Drop Steps 90762, Flush Fit Rails with Side Steps, Jeep Gladiator JT (2020-2025)","Rough Country","$380–$420",{},"465 lb rating; factory Rubicon rock rails must be removed (Quadratec); confirm 2026."),
 ("B07XBWD6WM","AMP Research 75135-01A PowerStep Electric Running Boards, 2020-2021 Jeep Gladiator, Black","AMP Research","$2,000–$2,200",{},"Power-retractable; title names 2020-2021 only; confirm part number and your year on the listing."),
 ("B0BWSH5DLW","Rough Country Power Running Boards, Retractable Electric Side Steps w/ Dual Motors, LED Lights, Jeep Gladiator JT (2020-2025)","Rough Country","$1,050–$1,150",{},"Not for trucks with Mopar Tire Deflector Bracket; confirm part number and 2026 on listing."),
 ("B08CMXHNGT","Go Rhino 684451687T 4 in OE Xtreme Side Steps with Mounting Brackets Kit, Jeep 20-23 Gladiator","Go Rhino","$320–$430",{},"Quadratec lists the part for 2020-2027; confirm 2024 and later with seller."),
 ("B0B32PLL4B","Westin Outlaw Drop Nerf Step Bars, 20- Jeep Gladiator","Westin","$490–$530",{},"Title has no part number; confirm the listing shows 20-14165."),
 ("B09XN9F4VT","Rough Country Rock Sliders 90802, 2020-2022 Jeep Gladiator JT 4WD","Rough Country","$480–$520",{},"Frame-mount slider; title stops at 2022; confirm 2023 and later with seller."),
 ("B07YXB1MN6","TAC Side Steps 3 in Black Side Bars (2 pcs), 2020-2025 Jeep Gladiator JT","TAC","Check listing",{},"Details from title only; confirm material, rating and 2026 on listing."),
 ("B0BLC7F3PT","Hooke Road Nerf Bar Rock Sliders Side Rail Rocker Guards, 2020-2025 Jeep Gladiator JT","Hooke Road","Check listing",{},"Budget slider-style bars; confirm mounting, rating and 2026 on listing."),
 ("B0DMSNTST5","Hooke Road Cab Length Side Step Nerf Bars, Tube Rock Slider Rails, 2020-2026 Jeep Gladiator JT","Hooke Road","Check listing",{},"Title names 2026; confirm mounting and rating on listing."),
 ("B0DPNHMNRZ","Rock Slide Engineering Step Slider w/ Power Step BD-SS-301-JT4, Jeep Gladiator JT 2024-2025 (4 Door)","Rock Slide Engineering","Check listing",{"year_from":2024},"Title names 2024-2025 only; confirm 2026 and specs on listing."),
]
