"""Long-form article — Best Roof Racks for 2018–2026 Jeep Wrangler JL (2-door and 4-door Unlimited).
Mirrors the approved pilot (ford_f150_2021_tonneau.py) and the roof-rack guides (4Runner, Bronco, Tahoe).
No invented hands-on testing. Vehicle facts come from Jeep's 2018 Wrangler launch release on Stellantis Media
(Sky One-Touch powertop, Sunrider soft top, body-color and black three-piece hardtops, "Lighter Freedom panels",
trim list by door count, "a roof rack for mounting Mopar carriers" as a Mopar accessory) and Wikipedia's JL page
(96.8 / 118.4 in wheelbases, 166.8 / 188.4 in lengths, production from November 2017, JK built until April 27, 2018,
2024 refresh), both opened 2026-10-05. Product specs come from the maker or retailer pages in SOURCES (Rough Country
configurator and ExtremeTerrain for 10612, Dometic for the Front Runner 1/2 kit, CB Adventure Supply for the Front
Runner Extreme kit, Rhino-Rack for RJLB1 and ExtremeTerrain for JB0880, Hooke Road for HE.3057-S, TrailFX and The
Engine Block for JL012T). Amazon picks are identified by listing title read in amazon.com search results; amazon.com
pages cannot be fetched, so where a spec comes only from a title the page says so. No Jeep roof load figure was read;
the page says so and sends readers to the owner's manual. No pick on this page is listed by its maker for a soft top;
the page says so.
"""

KEY = ("jeep", "wrangler", "2018-present", "roof-racks")

TITLE = "Best Roof Racks for 2018–2026 Jeep Wrangler JL: 7 Picks for Hardtops, Soft Tops and 2 vs 4 Doors"
META = ("Seven roof racks for the 2018–2026 Wrangler JL by mount type: hardtop Backbone, gutter tray, bolt-on steel, "
        "2-door rack, crossbars and basket, with soft-top limits.")

FAQ = [
 ("What is the best roof rack for a 2018–2026 Jeep Wrangler JL?",
  "For most 4-door owners, the Rough Country 10612. Rough Country lists it at $729.95 for the 2018–2026 JL, rates it at 225 lb dynamic and 450 lb static evenly distributed, and calls it Freedom Panel compatible on 4-door models with a 100% bolt-on install and no drilling. It is excluded on Jeeps with the Sky One-Touch power top. If you want a flat aluminum tray with no drilling, the Front Runner Slimline II 1/2 kit mounts to the hardtop gutters. If you have a 2-door hardtop, the Hooke Road rack at $299.99 is the one made for your roof. If you only carry a kayak or a cargo box, a crossbar set is enough."),
 ("Does the Wrangler JL have factory roof rails?",
  "No. Jeep's 2018 launch release lists three roofs, the Sky One-Touch powertop, the Sunrider soft top and the three-piece hardtop with Freedom panels, and never mentions roof rails. The only factory mention of a rack is that Mopar introduced \"a roof rack for mounting Mopar carriers\" as an accessory; we did not find a current Mopar page or an Amazon listing for it, so ask a dealer. Everything on this page therefore attaches to the hardtop itself, to its drip gutters, or to the Jeep's body. That is the opposite of a 4Runner or a Tahoe, where the rails do the work and the bars just clamp on."),
 ("Can I put a roof rack on a Wrangler soft top?",
  "Not with any pick on this page. The Sunrider soft top is fabric over bows and cannot carry a load, and none of the makers here list their rack for a soft top. Rough Country's page addresses the hardtop and Freedom panels and excludes the Sky One-Touch; TrailFX's page says only that its rack bolts to factory mounting points. If you run a soft top, ask Rough Country or TrailFX in writing whether the rack can be used with the top up and down before you buy, or plan on a hitch cargo carrier instead. Our 2018–2026 Wrangler hitch guide covers the receiver you would need."),
 ("Which racks fit the 2-door Wrangler JL?",
  "Fewer than fit the Unlimited, because the 2-door hardtop is much shorter. Wikipedia's JL page lists a 96.8 in wheelbase and 166.8 in length for the 2-door against 118.4 in and 188.4 in for the 4-door. Hooke Road's HE.3057-S is built for the 2018–2026 2-door hardtop. Front Runner sells a 2-door Slimline II 1/2 kit on Amazon. Rough Country lists the 10612 for both bodies but warns that it will hinder removing the Freedom panels on 2-door models. The 200 lb crossbar set here names 2-door and 4-door Jeeps. Every other pick is 4-door only."),
 ("Can I still take the Freedom panels off with a rack installed?",
  "It depends on the rack. Rough Country calls the 10612 Freedom Panel compatible on 4-door models and says it hinders panel removal on 2-doors. Hooke Road says the front top panels \"can be easily removed and installed\" once its 2-door rack is on, because the rack covers the rear of the top. Front Runner's 1/2 kit sits over the rear half of the hardtop on gutter legs, which is why it is sold as a half rack, but Dometic's page does not state panel removal, so ask. A full-length tray or a crossbar set with a bar over the front panels will tie them down."),
 ("How much weight can a Wrangler JL hardtop carry?",
  "We could not confirm a Jeep roof load figure from any Jeep page, so the owner's manual is the authority. What we can give you is the rack makers' numbers. Rhino-Rack rates its RJLB1 Backbone at 264 lb, and ExtremeTerrain lists the JB0880 Backbone kit at 176 lb dynamic. Rough Country rates the 10612 at 225 lb dynamic and 450 lb static. Hooke Road rates its 2-door rack at 160 lb evenly distributed, and TrailFX rates the JL012T at 300 lb. The rack's own weight counts against any dynamic figure, so an 86 lb Front Runner Extreme kit uses far more of your budget than a 25 lb Backbone. Use the lowest number you can find."),
 ("Do roof racks from the 2007–2018 Wrangler JK fit the JL?",
  "Only when the maker says so. The JL went into production in November 2017 and the JK was built until April 27, 2018, so both were sold as 2018 models, and a listing that says only \"2018 Wrangler\" can be for either body. Rhino-Rack sells a separate Backbone for the JL (RJLB1) and the JK (RJKB1), and Front Runner sells separate JK and JL kits. Some crossbar sets are the exception: the 200 lb set and the Grandroad set on this page name the JK, the JL and the Gladiator JT in one title. Look for the letters JL or a year of 2019 or later before you buy."),
 ("What is the difference between a Backbone rack and a gutter-mount rack?",
  "Where the load goes. Rhino-Rack's Backbone is an interior structure, three plates on each side joined by a frame inside the hardtop, and the legs and bars attach through it, which ExtremeTerrain says requires drilling holes through the roof. The rack then carries up to 264 lb by Rhino-Rack's figure because the hardtop shell is reinforced. A gutter-mount kit, such as Front Runner's 1/2 kit with eight gutter-mount legs or Hooke Road's rain-gutter rack, clamps to the hardtop's drip rail with no drilling, which is reversible but limited by the hardtop skin. Pick the Backbone for a tent or heavy gear, and a gutter kit if you want the hardtop unmarked."),
 ("Will a roof rack work with the Wrangler 4xe or the Rubicon 392?",
  "Check each listing. Rough Country's configurator lists the 10612 as compatible with the 4xe. Dometic says the Front Runner Slimline II 1/2 kit is \"Not suitable for 4xe models\". The other makers here do not mention the 4xe or the 392 on the pages we read, so ask before ordering. Both the 4xe and the 392 are 4-door only, which rules out the 2-door picks anyway. Owners of a 2024 or later Jeep should also look at the years in the title: the Rhino-Rack listing stops at 2022 and the crossbar titles at 2024, so later-year owners should confirm with the seller."),
 ("Are the Amazon crossbars and baskets as good as Rhino-Rack or Front Runner?",
  "They publish far less. The 200 lb crossbar set, the Grandroad bars and the SUPAREE basket are described here from their Amazon listing titles only, because amazon.com pages cannot be opened by us and no maker page was found. Rhino-Rack, Dometic, Rough Country and Hooke Road publish a rating, materials, mounting and, for most, a warranty. For a kayak in summer or a cargo box on a trip, a budget set that names your door count and hardtop is a sensible buy if you check the clamps often. For a rooftop tent or gear left on all year, buy a rack with a published rating and a warranty."),
]

ARTICLE = {
 "dek": "The Wrangler JL has no roof rails, a hardtop that comes off and a soft top that cannot carry anything, so a roof rack here is a different purchase than on most SUVs. Here are seven racks whose Amazon listings name the 2018+ JL, sorted by how they mount: Rhino-Rack's internal Backbone, Front Runner's gutter-mount tray, Rough Country's and TrailFX's bolt-on racks, Hooke Road's 2-door rack, a crossbar set and a basket, with the soft-top and Sky One-Touch limits spelled out.",
 "author": "jake-morrison",
 "reviewed": "2026-10-05",
 "method": "We did not install these racks ourselves. Picks were chosen on the fitment each maker or seller states for the 2018–2026 Wrangler JL by door count and roof type in its Amazon listing title, on the mounting method, rating, weight, materials and warranty published by Rhino-Rack, Dometic (Front Runner), Rough Country, Hooke Road and TrailFX, and on prices read at those makers or at ExtremeTerrain and CB Adventure Supply in October 2026. Amazon product pages cannot be opened by us, so where a spec comes only from a listing title we say so. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**There are no roof rails.** Jeep's 2018 launch release lists a Sky One-Touch powertop, a Sunrider soft top and a three-piece hardtop with Freedom panels, and never mentions roof rails. Every rack here mounts to the hardtop shell, its gutters or the body.",
  "**Soft-top Jeeps are not covered.** No maker on this page lists its rack for the soft top, and Rough Country excludes the Sky One-Touch. Soft-top owners should ask the maker in writing or use a hitch carrier.",
  "**Count the doors.** The 2-door hardtop is 21.6 in shorter in wheelbase (96.8 vs 118.4 in, Wikipedia). Hooke Road's rack and Front Runner's 2-door kit are the 2-door parts; most others are 4-door only.",
  "**Decide about the Freedom panels first.** Rough Country's 10612 is Freedom Panel compatible on 4-doors, Hooke Road's 2-door rack leaves the front panels removable, and a full-length tray does not.",
  "**No Jeep roof figure was found.** Rack ratings run from 160 lb (Hooke Road) to 300 lb (TrailFX); the owner's manual sets the real limit, and the rack's own weight counts against it.",
 ],
 "top_picks": [
  {"asin": "B082TQ6KNJ", "role": "Best overall (4-door)", "why": "Rough Country's bolt-on steel rack, 225 lb dynamic and 450 lb static, Freedom Panel compatible on 4-doors, no drilling, 4xe listed"},
  {"asin": "B09NP3RLSL", "role": "Best no-drill tray", "why": "Front Runner Slimline II 1/2 kit on eight gutter-mount legs, 53.5 in tray, 5-year warranty"},
  {"asin": "B07W7TMYDK", "role": "Best for heavy loads", "why": "Rhino-Rack Backbone reinforces the hardtop from inside; Rhino-Rack rates the RJLB1 structure at 264 lb"},
  {"asin": "B0CR3K92TG", "role": "Best for 2-door", "why": "Hooke Road rack made for the 2-door hardtop, rain-gutter mount, front panels stay removable"},
  {"asin": "B0C857BR82", "role": "Best budget crossbars", "why": "200 lb lockable bars whose title names 2-door and 4-door JK, JL and JT hardtops"},
 ],
 "fit_table": {
  "caption": "2018–2026 Wrangler JL roofs and bodies (match the rack to the roof and the door count, not the trim)",
  "head": ["Roof or body", "What Jeep says", "What fits from this page", "Notes"],
  "rows": [
   ["Three-piece hardtop, 4-door", "Body-color or black, with Freedom panels (2018 launch release)", "All 4-door picks: Rough Country, Front Runner, Rhino-Rack, TrailFX, crossbars, basket", "Rough Country and Front Runner's 1/2 kit keep the front panels in play; a full tray does not."],
   ["Three-piece hardtop, 2-door", "Same roof on a 96.8 in wheelbase (Wikipedia)", "Hooke Road HE.3057-S, Front Runner 2-door 1/2 kit, the 200 lb crossbars, Rough Country (panel removal hindered)", "4-door trays and Backbones are too long."],
   ["Sunrider soft top", "Fabric top on bows (2018 launch release)", "Nothing verified on this page", "Ask Rough Country or TrailFX in writing; otherwise use a hitch carrier."],
   ["Sky One-Touch powertop", "Full-length canvas roof that retracts at a button (2018 launch release)", "Nothing verified; Rough Country excludes it", "The retracting canvas is where a rack would sit."],
   ["4xe or Rubicon 392", "4-door only", "Rough Country lists the 4xe; Dometic excludes the 4xe from the Front Runner 1/2 kit", "Ask the other makers."],
  ],
 },
 "look_for": [
  {"h": "Mount type: hardtop shell, gutter or body",
   "body": "With no rails, a JL rack has to make its own foundation, and the three ways to do that behave very differently. Rhino-Rack's Backbone builds an interior frame inside the hardtop, three plates per side by Rhino-Rack's description, and ExtremeTerrain says the JB0880 kit's castings connect through the roof, so holes are drilled. It is the strongest hardtop mount and the least reversible. Gutter-mount kits from Front Runner and Hooke Road clamp legs to the hardtop's drip rail with no drilling, which keeps the top unmarked but relies on the hardtop skin. Rough Country and TrailFX describe bolt-on racks to factory mounting points with no drilling; neither page says exactly where the brackets land, so ask before you buy if you need the whole hardtop to come off."},
  {"h": "Two doors or four",
   "body": "The 2-door and 4-door hardtops are different lengths. Wikipedia's JL page gives a 96.8 in wheelbase and 166.8 in overall length for the 2-door against 118.4 in and 188.4 in for the Unlimited, so a 4-door tray overhangs a 2-door roof by well over a foot. Hooke Road sells HE.3057-S only for the 2018–2026 2-door hardtop, Front Runner sells separate 2-door and 4-door Slimline II kits, and the Rhino-Rack and TrailFX listings here are 4-door only. Rough Country lists the 10612 for both bodies but says it hinders Freedom panel removal on 2-doors. The 4xe and the 392 are 4-door only, so their owners skip the 2-door parts."},
  {"h": "Freedom panels and the whole top coming off",
   "body": "Jeep's 2018 release makes a point of the \"Lighter Freedom panels and improved latches\" for quicker removal, and a rack can end that. A half-length rack over the rear of the hardtop is the usual answer. Hooke Road says the front top panels can be removed and installed with its 2-door rack on, and Rough Country lists the 10612 as Freedom Panel compatible on 4-doors. Front Runner's 1/2 kit covers the rear 53.5 in of the roof, though Dometic's page does not state panel removal. A full-length tray like the Front Runner Extreme or a crossbar set with a bar over the front panels ties them down. Taking the whole hardtop off with any rack fitted means removing or unbolting the rack first, so decide how often you do that."},
  {"h": "Rating, rack weight and the missing Jeep number",
   "body": "We could not read a roof load limit from a Jeep page, so your owner's manual is the authority and the lowest figure wins. The racks here publish a wide range: 160 lb evenly distributed for Hooke Road's 2-door rack, 176 lb dynamic for the Rhino-Rack JB0880 kit at ExtremeTerrain, 225 lb dynamic and 450 lb static for Rough Country, 264 lb for the Rhino-Rack RJLB1 structure, and 300 lb for TrailFX. Rack weight comes out of any dynamic figure. Rhino-Rack lists the RJLB1 structure at 25.1 lb, Hooke Road quotes about 48 lb, and CB Adventure Supply lists the Front Runner Extreme kit at 86 lb installed. A rooftop tent plus a heavy rack can use the whole budget before any gear goes on."},
  {"h": "Powertrain, year and the JK trap",
   "body": "Three checks keep you out of the wrong part. First, the 4xe: Dometic marks the Front Runner 1/2 kit \"Not suitable for 4xe models\" while Rough Country lists the 4xe for the 10612. Second, the model year: the Rhino-Rack Amazon title stops at 2022 and the crossbar and basket titles at 2024, so a 2025 or 2026 owner should confirm with the seller, even though the maker pages run to 2026. Third, the JK. Both the JK and the JL were sold as 2018 models, and Rhino-Rack and Front Runner sell separate JK and JL kits, so a \"2018 Wrangler\" title alone is not enough. Only the crossbar sets here list the JK, the JL and the Gladiator together."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "Title names the JL or JLU, your door count, the hardtop and a year in 2018–2026", "\"Jeep Wrangler\" with no generation, or JK-only part numbers"],
   ["Mount", "A stated method: interior Backbone, gutter legs or bolt-on to factory points", "Clamps that grip the hardtop edge with no stated mount"],
   ["Freedom panels", "A maker statement that the front panels still come off", "Full-length trays if you open the roof often"],
   ["Rating", "A published dynamic figure plus the rack's weight", "\"Heavy duty\" with no number"],
   ["Soft top", "A maker statement that covers the soft top", "Any rack on this page, none is listed for it"],
   ["Warranty", "5 years (Front Runner, Rhino-Rack bars) or limited lifetime (Rough Country at ExtremeTerrain)", "No warranty stated on a title-only listing"],
  ],
 },
 "types_table": {
  "caption": "Roof rack types compared on the 2018–2026 Wrangler JL",
  "head": ["Type", "Price on this page", "Mounts to", "Drilling", "Doors", "Best for"],
  "rows": [
   ["Internal hardtop Backbone + bars", "Not read at a retailer (Rhino-Rack JB0880)", "Frame inside the hardtop, through the roof", "Yes (ExtremeTerrain)", "4-door", "Tents and heavy gear on a hardtop"],
   ["Gutter-mount aluminum tray", "$1,499 (Front Runner 1/2 kit, Dometic)", "Hardtop drip gutters, 8 legs", "No", "4-door (2-door kit sold separately)", "Flat deck with no holes in the top"],
   ["Bolt-on steel rack", "$729.95 (Rough Country) to $799 (TrailFX)", "Factory mounting points (location not stated)", "No", "Both (Rough Country) or 4-door (TrailFX)", "Light bars, 4-door Freedom panel use"],
   ["2-door gutter rack", "$299.99 (Hooke Road)", "Factory rain gutters", "No", "2-door", "2-door hardtops that keep the front panels off"],
   ["Crossbar set", "Check the listing", "Hardtop (per title)", "Per listing", "2-door and 4-door", "Kayak, bikes, a cargo box"],
   ["Basket", "Check the listing", "Hardtop (per title)", "Per listing", "Per listing", "Bulky soft loads"],
  ],
 },
 "picks": [
  {"asin": "B082TQ6KNJ", "role": "Best overall (4-door)", "price": "$700–$760",
   "pros": ["Rough Country rates it at 225 lb dynamic and 450 lb static", "Freedom Panel compatible on 4-door models", "100% bolt-on with no cutting or drilling", "Listed for the 4xe in Rough Country's configurator", "Optional 50 in and dual 2 in LED lights from the same configurator"],
   "cons": ["Excluded on the Sky One-Touch powertop", "Hinders Freedom panel removal on 2-door models", "Rack weight is not published"],
   "body": "Rough Country's 10612 is the rack with the clearest fit statement for a JL. Rough Country's configurator lists it at $729.95 for 2018–2026 JL and JLU models, calls it Freedom Panel compatible on the 4-door, lists the 4xe, and excludes Jeeps with the Sky One-Touch powertop. The rating is 225 lb dynamic and 450 lb static, evenly distributed, in all-steel construction. The outer size is 70 in long, 54 in wide and 6 in tall, with an interior cargo area of 61 by 50.75 by 3 in. ExtremeTerrain lists the same part at $729.95 with a limited lifetime warranty, a 2 to 3 hour install and a heavy-duty, all-steel, black powder-coated build, and quotes a 250 lb rating, so we use the maker's lower figure.\n\nThe Amazon title names the Unlimited for 2018–2025 and the 2-door for 2021–2024, which is narrower than Rough Country's own 2018–2026 span, so owners outside those years should confirm with the seller. Two gaps remain. Rough Country does not publish the rack's weight, so ask before you subtract it from the manual's limit. And neither page says where the brackets bolt to, which matters if you take the whole hardtop off; Rough Country's note that the rack hinders panel removal on 2-doors suggests the front mounts sit near the panels on the shorter roof. The configurator's optional 50 in bar and dual 2 in pods, 27,840 lumens combined, make this the obvious base for a light-bar build.",
   "who": "4-door hardtop owners, including 4xe owners, who want a bolt-on steel rack with published ratings and still want the Freedom panels off in summer.",
   "specs": [["Type", "Bolt-on steel rack"], ["Part #", "10612"], ["Fits", "2018–2026 JL and JLU (Rough Country); title: Unlimited 2018–2025, 2-door 2021–2024"], ["Dynamic load", "225 lb"], ["Static load", "450 lb"], ["Size", "70 x 54 x 6 in; cargo area 61 x 50.75 x 3 in"], ["Drilling", "None"], ["Excludes", "Sky One-Touch powertop"], ["Price", "$729.95 (Rough Country, ExtremeTerrain)"]]},
  {"asin": "B09NP3RLSL", "role": "Best no-drill tray (4-door)", "price": "$1,400–$1,550",
   "pros": ["Eight gutter-mount legs, no drilling", "53.5 in Slimline II tray over the rear half of the roof", "5-year warranty on all Dometic Front Runner Series racks", "Slimline II accessory range: tables, boxes, awning and light mounts", "2-door version sold as a separate Amazon listing"],
   "cons": ["$1,499 for a half-length rack", "Not suitable for 4xe models per Dometic", "Load capacity, weight and panel removal not stated on Dometic's page"],
   "body": "Front Runner, sold under Dometic in the US, is the brand to buy if you want a flat aluminum tray without drilling the hardtop. The Slimline II 1/2 Roof Rack Kit, part KRJW027T, is listed by Dometic at $1,499 for the 2018-current JL 4 Door. The kit includes eight gutter-mount legs that clamp the tray to the hardtop's drip rail, and Dometic states no drilling is required. The tray is the half-size configuration at 1358 mm, or 53.5 in, long. Every Dometic Front Runner Series rack carries a 5-year warranty, and the Slimline II slot system takes the brand's tables, water tanks, awning brackets and light mounts.\n\nThe half length is the point. It leaves the front of the hardtop free, which is where the Freedom panels live, although Dometic's page does not say in words that the panels still come off, so ask. Dometic also marks the kit \"Not suitable for 4xe models\". The page does not list a capacity or the tray's weight, so plan the load from your owner's manual rather than from a Front Runner figure. One customer review on the Dometic page mentions drilling holes in the hardtop, which contradicts the no-drill description; read the instructions before install day. If you want the whole roof covered, Front Runner's Extreme Slimline II kit for the 4-door is listed by CB Adventure Supply at $2,699 with an 86 lb installed weight and drilling required, and it is in the fit list below.",
   "who": "4-door hardtop owners who want a flat accessory tray with no holes in the top and plan to buy into one accessory system.",
   "specs": [["Type", "Gutter-mount aluminum tray (half length)"], ["Part #", "KRJW027T"], ["Fits", "2018-current JL 4 Door (Dometic); not 4xe"], ["Tray length", "53.5 in (1358 mm)"], ["Mounting", "8 gutter-mount legs, no drilling"], ["Capacity", "Not stated on Dometic's page"], ["Warranty", "5 years"], ["Price", "$1,499 (Dometic)"]]},
  {"asin": "B07W7TMYDK", "role": "Best for heavy loads (4-door hardtop)", "price": "Check listing",
   "pros": ["Backbone reinforces the hardtop from the inside", "Rhino-Rack rates the RJLB1 structure at 120 kg / 264 lb", "Structure weighs 25.1 lb per Rhino-Rack", "Takes 2 or 3 Vortex bars or the Pioneer Platform", "Limited lifetime warranty on the Backbone, 5 years on the bars (ExtremeTerrain)"],
   "cons": ["ExtremeTerrain says the kit mounts through the roof, so holes are drilled", "ExtremeTerrain now lists the JB0880 kit as discontinued; confirm stock on the listing", "Amazon title stops at 2022; about 2 hours to install"],
   "body": "Rhino-Rack's Backbone is the engineering answer to a hardtop with no rails. Rhino-Rack describes the RJLB1 as an interior structure set up on the inside of the JL hardtop, three plates on each side connected with an interior frame, so the load path goes into a frame rather than the fiberglass skin. Rhino-Rack rates the mounting system at 120 kg or 264 lb, lists its weight at 25.1 lb, gives it a 5-year warranty and says you can attach a 2 or 3 bar system or the Pioneer Platform. The Amazon listing here is the JB0880 kit, a heavy-duty RCL 2-bar Backbone package titled for the 2018–2022 JL 4-door hardtop.\n\nExtremeTerrain's page for the JB0880 fills in what Rhino-Rack's RJLB1 page leaves out. It lists the kit for 2018–2026 4-door hardtops, describes internal brackets and external castings that connect through the roof, so drilling is required, puts the dynamic rating at 176 lb, quotes about 2 hours of light to moderate work, and gives a limited lifetime warranty on the Backbone and 5 years on the crossbars in aluminum alloy with a black powder coat. The same page shows the kit as discontinued with no price, so confirm the Amazon listing is in stock and ships the whole kit before you order. Freedom panel removal is not addressed by either page, so ask the seller. For a rooftop tent on a hardtop, this is still the mount with the strongest published foundation.",
   "who": "4-door hardtop owners who want a permanent, reinforced mount for a tent or heavy gear and accept drilled holes.",
   "specs": [["Type", "Internal hardtop Backbone + 2 bars"], ["Part #", "JB0880 (kit); RJLB1 (Backbone structure)"], ["Fits", "2018–2022 JL 4-door hardtop (title); 2018–2026 (ExtremeTerrain)"], ["Capacity", "264 lb (Rhino-Rack, RJLB1); 176 lb dynamic (ExtremeTerrain, JB0880)"], ["Structure weight", "25.1 lb (RJLB1)"], ["Drilling", "Yes, through the roof (ExtremeTerrain)"], ["Install", "~2 hours"], ["Warranty", "Limited lifetime Backbone, 5-year bars"], ["Availability", "Listed as discontinued at ExtremeTerrain; confirm on listing"]]},
  {"asin": "B08JV2JQRC", "role": "Best steel tube rack (4-door)", "price": "$750–$850",
   "pros": ["300 lb capacity per TrailFX", "Bolt-on to factory mounting points, about one hour", "E-coat plus textured powder coat over steel tube", "Four-bar round-tube design", "Amazon title runs 2018–2025"],
   "cons": ["TrailFX does not say whether the hardtop or panels stay removable", "No weight, dimensions or warranty on the maker page", "Soft top not addressed"],
   "body": "TrailFX's JL012T is the simplest rack here: four round steel bars on robust bracketry that, in the maker's words, bolts to factory mounting points in about an hour. TrailFX lists it at $799 for the JL 4-door and rates it at 300 lb, the highest figure on this page, with e-coat and textured black powder coat over steel. The Engine Block's launch story quotes TrailFX's product manager on the factory-point install, and says the design is more supportive than others and produces less wind noise, which is a maker claim we pass on rather than a measurement.\n\nWhat TrailFX does not publish is as important as what it does. The product page gives no rack weight, no outer dimensions, no warranty terms and no statement on the Freedom panels, the full hardtop or the soft top, and it does not say where the factory mounting points are. So before you order, ask TrailFX or the seller three things: how much the rack weighs, whether the front panels come off with it fitted, and whether the whole hardtop can be removed without unbolting the rack. The Amazon title names the 2018–2025 JL 4-door with direct-fit bolt-on mounting and the 300 lb capacity. A 2026 owner should confirm fit with the seller.",
   "who": "4-door owners who want the highest published rating in a plain steel rack and will ask the maker about the panels first.",
   "specs": [["Type", "Bolt-on steel tube rack"], ["Part #", "JL012T (T83JL012T)"], ["Fits", "JL 4-door (TrailFX); 2018–2025 (title)"], ["Capacity", "300 lb"], ["Mounting", "Factory mounting points, bolt-on"], ["Finish", "E-coat and textured powder coat"], ["Install", "About 1 hour (TrailFX)"], ["Price", "$799 (TrailFX)"]]},
  {"asin": "B0CR3K92TG", "role": "Best for 2-door", "price": "$280–$330",
   "pros": ["Made for the 2018–2026 JL 2-door hardtop", "Mounts to the factory rain gutters, no drilling", "Front top panels can be removed with the rack installed", "Three aluminum crossbars with two T-slot channels for 8 mm nuts", "$299.99 at Hooke Road"],
   "cons": ["160 lb evenly distributed is the lowest rating here", "About 48 lb for a 41.4 in rack", "Adds about 4.3 in of height"],
   "body": "Two-door owners have the shortest list, and Hooke Road's HE.3057-S is the one with a maker page behind it. Hooke Road lists it at $299.99 for the 2018–2026 JL 2-door hardtop. It mounts to the factory rain gutters with no drilling or modification, and Hooke Road says the front top panels can be easily removed and installed once the rack is on, because the rack sits over the rear of the short top. It is 52.6 in wide and 41.4 in long, adds about 4.3 in of height, and weighs about 48 lb. The side, front and rear panels are 13-gauge steel with a textured black powder coat over E-coat, and the three crossbars are 3.2 by 0.8 in aluminum extrusions with two top-facing T-slot channels for standard 8 mm nuts.\n\nThe rating is 160 lb evenly distributed, the lowest on this page, and the rack's own 48 lb makes it a basket for light, bulky gear rather than a tent platform. Hooke Road quotes up to 1.5 hours to install and does not state a warranty on the product page, so ask. The Amazon title matches the maker: a cross bar and cargo basket for the 2018–2026 2-door hardtop with no drilling and easy front panel removal. It is sold for the hardtop only, which rules out the soft top. If you want a tray instead of a basket on a 2-door, Front Runner's 2-door Slimline II 1/2 kit is in the fit list below.",
   "who": "2-door hardtop owners who want a no-drill rack that still lets the front panels come off.",
   "specs": [["Type", "2-door gutter-mount rack"], ["Part #", "HE.3057-S"], ["Fits", "2018–2026 JL 2-door hardtop"], ["Capacity", "160 lb evenly distributed"], ["Size", "52.6 x 41.4 in, ~4.3 in tall"], ["Weight", "~48 lb"], ["Crossbars", "3 aluminum, dual 8 mm T-slot"], ["Mounting", "Factory rain gutters, no drilling"], ["Price", "$299.99 (Hooke Road)"]]},
  {"asin": "B0C857BR82", "role": "Best budget crossbars", "price": "Check listing",
   "pros": ["Title names 2-door and 4-door JK, JL and Gladiator JT, 2007–2024", "200 lb figure printed in the title", "Anti-theft metal lock in the title", "Two bars are enough for a kayak, bikes or a cargo box", "Light compared with any rack above"],
   "cons": ["Specs come from the listing title only", "Mounting method is not stated in the title; confirm hardtop and drilling", "Title stops at 2024"],
   "body": "If all you carry is a kayak, a pair of bikes or a cargo box, two bars are enough, and this set is the one whose title covers the most Jeeps: heavy-duty crossbars rated at 200 lb, compatible with the JK, JL and Gladiator JT from 2007 to 2024, 2-door and 4-door, with an anti-theft metal lock. We could not open the Amazon page or find a maker site, so everything here is from the title, and the 200 lb figure is the seller's. Being listed for the JK and the JL together suggests the bars grip the hardtop rather than a generation-specific structure, but the title does not say how they mount or whether drilling is involved, so confirm both on the listing before you order.\n\nTreat the bars like any hardtop accessory: check that the feet sit on the hardtop and not across the Freedom panel seams if you plan to pull the panels, lock them, and recheck the clamps after the first drive and after rough roads. A 2025 or 2026 owner should ask the seller about fit, because the title stops at 2024. Grandroad's 4-door hardtop set, also listed for the JK, JL and JT, is in the fit list below as an alternative. None of these bars is listed for the soft top.",
   "who": "Hardtop owners with either door count who carry a kayak, bikes or a box a few times a year and want to spend the least.",
   "specs": [["Type", "Crossbar set"], ["Fits", "2007–2024 JK, JL, JT hardtop, 2-door and 4-door (title)"], ["Rating", "200 lb (title)"], ["Lock", "Anti-theft metal lock (title)"], ["Mounting", "Confirm on listing"], ["Alternative", "Grandroad 4-door set B0BPRRCVXD"]]},
  {"asin": "B0D949VKQ5", "role": "Best basket (hardtop)", "price": "Check listing",
   "pros": ["Title names the JL and Gladiator JT, 2018–2024, hard top only", "Aluminum basket with crossbars in one kit", "Sides keep soft bags and bins from sliding", "A basket is the cheapest way to carry bulky, light loads", "Lighter than a steel rack"],
   "cons": ["Specs come from the listing title only", "Hard top only; door count not in the title", "Title stops at 2024"],
   "body": "A basket suits the gear most Wrangler owners put on the roof: duffels, a cooler, recovery boards, firewood. The SUPAREE listing is titled as an aluminum roof rack cargo basket crossbar for the Jeep Wrangler JL and Gladiator JT, 2018–2024, hard top only. That is the whole of what we can state, because the Amazon page cannot be opened by us and we found no SUPAREE spec page for this rack. The title does not give a rating, a weight, the basket's size or whether the mounts need drilling, and it does not say 2-door or 4-door, so a 2-door owner should ask the seller for the basket's length against the 2-door roof before ordering.\n\nUse it for what the title supports. Keep the load light and low, strap everything in two directions, and remember that a basket's sides catch wind, so expect more noise than bare bars. The hard-top-only note rules out the soft top and the Sky One-Touch. Owners of a 2025 or 2026 Jeep should confirm fit, since the title stops at 2024. If you want a basket with a maker page and a rating, Hooke Road's 2-door rack above is one on a 2-door, and Rough Country's 10612 is a basket-style rack with published numbers on a 4-door.",
   "who": "Hardtop owners who carry soft, bulky loads and want the simplest kit, and will confirm size and rating with the seller.",
   "specs": [["Type", "Aluminum basket with crossbars"], ["Fits", "2018–2024 JL and Gladiator JT, hard top only (title)"], ["Rating", "Not in title; confirm"], ["Doors", "Not in title; confirm"], ["Mounting", "Confirm on listing"], ["Alternative", "JROAD full-length 4-door platform B0FKB34XXL"]]},
 ],
 "install": [
  "Identify your roof and body: three-piece hardtop, Sunrider soft top or Sky One-Touch, and 2-door or 4-door. Only hardtops are covered by the racks on this page, and 2-door racks differ from 4-door racks.",
  "Decide about the Freedom panels. If you take them off often, choose a rack that leaves the front of the roof clear (Rough Country on a 4-door, Hooke Road on a 2-door, a half-length tray) and skip full-length trays and bars over the front panels.",
  "For a gutter-mount kit, clean the drip rails, fit the legs loosely and evenly on both sides, set the tray or bars square to the roof, then tighten in sequence to the kit's torque figure.",
  "For a Backbone, follow Rhino-Rack's instructions for the interior plates before drilling anything, and seal every through-roof fastener as the instructions direct. This step is not reversible, so measure twice.",
  "For a bolt-on rack, locate the factory mounting points the instructions name, fit the brackets with a helper holding the rack, and tighten evenly side to side before fitting any light bar.",
  "Open the rear glass, swing the tailgate and remove and refit the front panels (if the rack allows it) to check clearance, then drive a short loop and listen for wind noise.",
  "Recheck every fastener after the first week and after any trail day, and keep the load under the lowest of the manual's figure, the rack's rating and the hardtop's own condition.",
 ],
 "avoid": [
  {"h": "A hardtop rack on a soft top or Sky One-Touch", "body": "Fabric cannot carry a rack, and Rough Country excludes the Sky One-Touch outright. Nothing on this page is verified for either roof."},
  {"h": "A 4-door tray on a 2-door Jeep", "body": "The 2-door hardtop sits on a wheelbase 21.6 in shorter. Buy the 2-door part from Hooke Road or Front Runner, or a crossbar set that names both bodies."},
  {"h": "Planning around the rack's rating", "body": "A 300 lb rack does not raise the Jeep's limit, which we could not read from Jeep. Use the owner's manual and subtract the rack's own weight."},
  {"h": "A JK rack with a '2018' label", "body": "Both generations were sold as 2018s. Rhino-Rack and Front Runner sell separate JK and JL kits, so look for JL in the title or a year of 2019 or later."},
 ],
 "verdict": {
  "thesis": "On a Wrangler JL, buy by roof and door count before brand: Rough Country's 10612 for most 4-door hardtops, Front Runner's 1/2 kit if you refuse to drill, Rhino-Rack's Backbone for heavy loads, Hooke Road for a 2-door, and crossbars if a kayak is the only cargo.",
  "body": "The JL's missing roof rails turn a roof rack into a structural decision. The Backbone makes the hardtop a load-bearing shell and asks for drilled holes in return; the gutter kits leave the top untouched but publish fewer numbers; the bolt-on steel racks from Rough Country and TrailFX give the best ratings per dollar but do not say where they bolt, so ask about the panels. Soft-top and Sky One-Touch owners have no verified pick here, and no maker page we read offers one. Whichever rack you choose, a half-length design keeps the Freedom panels in play, and the owner's manual, not the rack box, sets the weight you can carry.\n\nMost owners fit the rack alongside two other mods. A roof rack on a Jeep this tall is easier to load with running boards or side steps on the rockers, and a bolt-on rack with light mounts is the usual place for an LED light bar, which is why Rough Country sells the 10612 with one in the configurator. If a rack is really about storage, a hitch cargo carrier moves the weight off the roof, keeps the top removable and clears the tailgate spare, and our hitch guide covers the receiver. Floor liners finish the job for a Jeep that spends the summer with the panels off.",
 },
 "sources": [
  ["All-new 2018 Jeep Wrangler launch release: Sky One-Touch powertop, Sunrider soft top, Freedom panels, trims by door count, Mopar roof rack (Stellantis Media)", "https://media.stellantisnorthamerica.com/newsrelease.do?id=18667&mid="],
  ["Jeep Wrangler (JL): wheelbases, lengths, production from November 2017, JK built until April 27, 2018, 2024 refresh (Wikipedia)", "https://en.wikipedia.org/wiki/Jeep_Wrangler_(JL)"],
  ["Rough Country JL roof rack 10612 configurator: $729.95, 225 lb dynamic / 450 lb static, Freedom Panel compatible, Sky One-Touch excluded, 4xe (Rough Country)", "https://www.roughcountry.com/product/configurable/jl-roof-rack-10612c"],
  ["Rough Country roof rack system 10612: $729.95, limited lifetime warranty, 2 to 3 hour install, 250 lb (ExtremeTerrain)", "https://www.extremeterrain.com/rough-country-jeep-wrangler-roof-rack-system-10612.html"],
  ["Front Runner Jeep Wrangler JL 4 Door (2018-Current) Slimline II 1/2 Roof Rack Kit KRJW027T: $1,499, 8 gutter-mount legs, 53.5 in, not 4xe, 5-year warranty (Dometic)", "https://www.dometic.com/en-us/product/jeep-wrangler-jl-4-door-18-curr-sl-ii-1-2-rack"],
  ["Front Runner Jeep Wrangler JL 4 Door Extreme Roof Rack Kit: $2,699, 86 lb installed, drilling required (CB Adventure Supply)", "https://www.cbadventuresupply.com/products/front-runner-jeep-wrangler-jl-4-door-2017-current-extreme-roof-rack-kit"],
  ["Rhino-Rack Backbone Mounting System RJLB1: interior structure, 264 lb, 25.1 lb, 5 years (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-rack-extras/roof-rack-parts/rhino-rack-backbone/rhino-rack-backbone-mounting-system_rjlb1"],
  ["Rhino-Rack Heavy Duty RCL 2-Bar Backbone Roof Rack JB0880: 176 lb dynamic, through-roof mounting, ~2 hours, warranty, discontinued (ExtremeTerrain)", "https://www.extremeterrain.com/rhino-rack-jeep-wrangler-heavy-duty-rcl-2-bar-backbone-roof-rack-black-jb0880.html"],
  ["Hooke Road aluminum roof rack HE.3057-S, 2018–2026 JL 2-door hardtop: $299.99, rain-gutter mount, 160 lb, ~48 lb (Hooke Road)", "https://www.hookeroad.com/products/roof-rack-for-jeep-wrangler-jl-2-door-b3057s"],
  ["TrailFX roof rack for Jeep Wrangler JL 4 Door JL012T: $799, 300 lb, bolt-on, about one hour (TrailFX)", "https://www.trailfx.com/products/trailfx-jl012t-roof-rack"],
  ["New TrailFX JL roof rack: factory mounting points, 300 lb, steel tube (The Engine Block)", "https://theengineblock.com/new-trailfx-jl-roof-rack-helps-wrangler-maintain-heavyweight-status/"],
 ],
}

# Product list for this page (replaces the v1 generic list). (asin, name, brand, band, cond, note)
FITS = [
 ("B082TQ6KNJ","Rough Country Roof Rack for Jeep Wrangler JL (2021-2024) & Unlimited (2018-2025), heavy-duty cargo rack, Freedom Top compatible, low-profile","Rough Country","$700–$760",{},"225 lb dynamic / 450 lb static; not Sky One-Touch; hinders panel removal on 2-door. Confirm years outside the title with seller."),
 ("B09NP3RLSL","Front Runner Slimline II 1/2 Roof Rack Kit, Jeep Wrangler JL 4 Door (2018-Current), KRJW027T","Front Runner","$1,400–$1,550",{"doors":"4-door"},"Gutter mount, no drilling; not 4xe per Dometic; capacity not stated, confirm."),
 ("B07W7TMYDK","Rhino Rack 2018-2022 Jeep Wrangler JL 4dr Hard Top Heavy Duty RCL Black 2 Bar Backbone Roof Rack JB0880","Rhino-Rack","Check listing",{"doors":"4-door","top":"hardtop"},"Internal Backbone, drilling through roof; ExtremeTerrain lists JB0880 as discontinued, confirm stock and later years."),
 ("B08JV2JQRC","TrailFX JL012T Roof Rack, Jeep Wrangler JL 4 Door 2018-2025, direct-fit bolt-on, 300 lb, textured black steel","TrailFX","$750–$850",{"doors":"4-door"},"Bolt-on to factory points; panel removability and weight not published, confirm with maker."),
 ("B0CR3K92TG","Hooke Road JL 2 Doors Roof Rack Cross Bar Aluminum Cargo Basket, 2018-2026 Jeep Wrangler JL 2-Door Hard Top, no drill, front panels removable","Hooke Road","$280–$330",{"doors":"2-door","top":"hardtop"},"Rain-gutter mount; 160 lb evenly distributed; ~48 lb."),
 ("B0C857BR82","Heavy Duty Roof Rack Cross Bars 200 lb, Jeep Wrangler JK JL Gladiator JT 2007-2024, anti-theft lock, 2 & 4 door","Generic","Check listing",{"top":"hardtop"},"Title-only specs; confirm mounting and drilling on listing; title stops at 2024."),
 ("B0D949VKQ5","SUPAREE Aluminum Roof Rack Cargo Basket Crossbar, Jeep Wrangler JL and Gladiator JT 2018-2024, hard top only","SUPAREE","Check listing",{"top":"hardtop"},"Title-only specs; door count, rating and mounting not in title, confirm with seller."),
 ("B09NP2LWG9","Front Runner Slimline II 1/2 Roof Rack Kit / Tall, Jeep Wrangler JL 2 Door (2018-Current)","Front Runner","Check listing",{"doors":"2-door"},"2-door version of the 1/2 kit; confirm price, 4xe note does not apply (4xe is 4-door)."),
 ("B0CLDFRYLC","Front Runner Extreme Slimline II Roof Rack, Jeep Wrangler JL 4 Door (2018-Current), full length","Front Runner","$2,500–$2,800",{"doors":"4-door"},"CB Adventure Supply: $2,699, 86 lb installed, drilling required; covers the Freedom panels."),
 ("B0BPRRCVXD","Grandroad Roof Rack Cross Bars, 2007-2024 Jeep Wrangler JK JL Gladiator JT, 4 door hard top, aluminum","Grandroad","Check listing",{"doors":"4-door","top":"hardtop"},"Alternative to the 200 lb set; title-only specs; title stops at 2024."),
 ("B0FKB34XXL","JROAD Wrangler JL Hard Top Platform Roof Rack, full length cargo basket, 2018-2025 Jeep Wrangler JL 4 Door Hardtop","JROAD","Check listing",{"doors":"4-door","top":"hardtop"},"Full-length platform covers the Freedom panels; title-only specs; confirm rating and mounting."),
]
