"""Long-form article — Best Rooftop Cargo Boxes for 2022–2026 Jeep Grand Cherokee (WL) and 2021–2026 Grand Cherokee L.
Mirrors the approved F-150 tonneau pilot. No invented hands-on testing: box specs come from Yakima, Thule,
Rhino-Rack, SportRack and Rightline Gear (via RealTruck) pages fetched 2026-09-27; vehicle facts from
db/migrations/003_vehicles.sql and the Grand Cherokee roof-rack article (flush rails, fixed mounting points,
~24.5 in Rhino-Rack Vortex spread, 47 in Thule bars, 165 lb brand-name ratings, 2021 two-row = WK2).
"""

KEY = ("jeep", "grand-cherokee", "2022-present", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2022–2026 Jeep Grand Cherokee & L: 7 Picks for Flush Rails"
META = ("Seven Yakima, Thule, Rhino-Rack, SportRack and Rightline cargo boxes for the WL Grand Cherokee and L: "
        "fixed-point 24.5 in spread, 165 lb bars, hatch checks.")

FAQ = [
 ("What size cargo box fits a 2022–2026 Grand Cherokee?",
  "A 16 cu ft box suits most two-row Grand Cherokees, and the three-row L's longer roof gives more room for an 18 cu ft box. Just as important as volume is crossbar spread: several flush-rail systems mount at fixed points, and etrailer lists the Rhino-Rack Vortex at about 24.5 in. The Yakima SkyBox 16 and CBX 16 (24 in minimum), the Thule Motion 3 XL (21-13/16 in minimum) and the Rhino-Rack MasterFit 440 (620 mm, about 24.4 in) all start below that."),
 ("Why does crossbar spread matter so much on a Grand Cherokee?",
  "Because many of its racks can't be moved. The Yakima SkyLine and Rhino-Rack Vortex systems for the WL mount at fixed points in the flush rails, and etrailer lists the Vortex at about 24.5 in, not adjustable. A box whose minimum spread is above that number won't mount. The SportRack Vista XL, for example, uses fixed positions starting at 25-7/8 in, so it needs clamp-on bars you can slide apart."),
 ("How much weight can I put in a cargo box on a Grand Cherokee?",
  "Start with the bars. The brand-name systems on etrailer's 2023 Grand Cherokee list (Thule WingBar Evo, Yakima SkyLine, Rhino-Rack Vortex) are rated at 165 lb, and the Grand Cherokee's own roof limit is in the owner's manual; we could not confirm that figure from Jeep for this page. The box and its contents count against the bar rating. A 47 lb SkyBox 16 on 165 lb bars leaves 118 lb for gear at most."),
 ("Do cargo boxes fit the Grand Cherokee L and the 4xe?",
  "Yes. Boxes clamp to crossbars, so the question is the bars. The Amazon bars on our roof rack page name both the two-row Grand Cherokee and the three-row L, and none exclude the 4xe. Brand-name kits may use different parts or positions on the L's longer roof, so look it up separately. The L's extra roof length also gives a long box more room ahead of the liftgate."),
 ("I have a 2021 Grand Cherokee. Does this guide apply?",
  "Only if it is a 2021 Grand Cherokee L. The WL generation launched with the three-row L for 2021; the two-row didn't switch until 2022. A 2021 two-row Grand Cherokee is the previous WK2, which uses different rack parts. The boxes themselves carry over, but the crossbars and spread must match your body."),
 ("Will a roof box hit the Grand Cherokee's liftgate?",
  "It can if it is mounted too far back. etrailer's experts measure from the front crossbar to the line where the roof and hatch meet, then compare that with the box maker's figure. Thule lists more than 50 5/8 in of front clearance for the Force 3 L and more than 52 3/32 in for the Motion 3 XL. On fixed-point racks you can't move the bars, so slide the box forward on them and open the power liftgate slowly the first time."),
 ("Can I open the sunroof with a cargo box on a Grand Cherokee?",
  "Test it parked, and expect to keep it closed. etrailer's Thule WingBar Evo page for the 2023 Grand Cherokee says the bars don't interfere with the factory sunroof, but its Rhino-Rack Vortex page warns that opening a sunroof with cargo on the rack could cause contact. A box's front edge often sits near the glass, so keep the roof shut while the box is on."),
 ("Does the rail finish change the crossbars for a box?",
  "For some kits it does. etrailer lists Inno's Aero and Aero Flush systems for the 2023 Grand Cherokee twice: once for a black-and-chrome track and once for a matte-black-and-gloss-black track. Check your rail before ordering those bars. The box itself doesn't care, but the bars have to be right first."),
 ("Will a cargo box fit in my garage on a Grand Cherokee?",
  "Measure it. The boxes here add 15 in (Yakima SkyBox 16, CBX 16), 16.8 in (Thule Force 3 L), 17 in (Thule Motion 3 XL, Rhino-Rack MasterFit 440), 18 in (Rightline Sport 3) or 19 in (SportRack Vista XL) on top of the crossbars. Measure the Grand Cherokee with bars fitted, add the box height, and compare it with the door opening before you drive in."),
 ("Should I use a roof box or a hitch cargo carrier on a Grand Cherokee?",
  "The WL has a Class IV receiver and tows up to 6,200 lb with the V6 (7,200 lb with the 2022–2024 V8), so a hitch carrier handles heavy coolers and bins easily and keeps weight off the 165 lb bars. A roof box locks, keeps soft bags dry and leaves the liftgate free. For family trips many owners use both: bulky, light gear up top and the heavy items on the hitch."),
]

ARTICLE = {
 "dek": "Seven rooftop boxes from Yakima, Thule, Rhino-Rack, SportRack and Rightline Gear matched to the WL Grand Cherokee and Grand Cherokee L, from a 38.6 lb Rhino-Rack MasterFit to the 18 cu ft Thule Motion 3 XL and a $140 soft bag. For each we list volume, size, box weight and crossbar spread, and what those numbers mean for flush rails with fixed mounting points, a 24.5 in spread on some systems and 165 lb bars.",
 "author": "jake-morrison",
 "reviewed": "2026-09-27",
 "method": "We did not mount these boxes ourselves. We ranked them on published specs from Yakima, Thule, Rhino-Rack and SportRack, etrailer's figures for the Thule Motion 3 spread and the SportRack Vista XL mounting positions, and RealTruck's Rightline Gear listing: volume, exterior size, box weight, cargo rating, crossbar spread, ski length and warranty. We checked those numbers against the WL Grand Cherokee's flush rails, the fixed 24.5 in spread etrailer lists for the Rhino-Rack Vortex, the 165 lb rating of brand-name Grand Cherokee systems and 47 in Thule bars, plus etrailer's sunroof and hatch-clearance guidance. Prices were checked in September 2026; Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Flush rails, often fixed points.** The Yakima SkyLine and Rhino-Rack Vortex mount at fixed points in the WL's rails, so the bar spread isn't yours to choose.",
  "**Check the 24.5 in spread.** etrailer lists the Vortex at about 24.5 in. Boxes with a 24 in or lower minimum fit it; the SportRack Vista XL (25-7/8 in minimum) needs clamp-on bars.",
  "**165 lb bars.** Brand-name systems for the 2023 Grand Cherokee are rated at 165 lb, and the roof limit is in your manual. Box plus cargo stays under both.",
  "**Match the body.** 2022+ two-row and 2021+ L are WL; a 2021 two-row is the old WK2 with different rack parts.",
  "**The L has more roof.** Its longer roof gives long boxes more room ahead of the liftgate.",
 ],
 "top_picks": [
  {"asin": "B001PUZXGK", "role": "Best overall", "why": "16 cu ft, 15 in tall, 47 lb; 24 in minimum spread fits a fixed 24.5 in rack"},
  {"asin": "B0HGC24R2P", "role": "Best for skis", "why": "Thule Motion 3 XL: 18 cu ft, 200 cm skis, 21-13/16 in minimum spread"},
  {"asin": "B07B4P7WYX", "role": "Best with Rhino-Rack bars", "why": "MasterFit 440: fits Vortex bars directly, 38.6 lb, 165 lb cargo rating, 5-year warranty"},
  {"asin": "B0DYQ4T5ZZ", "role": "Shortest 16 cu ft", "why": "Thule Force 3 L: 76.8 in long for the two-row's shorter roof; 43 lb"},
  {"asin": "B0012INT98", "role": "Best budget", "why": "Rightline Gear Sport 3: 18 cu ft waterproof soft carrier, $139.99"},
 ],
 "fit_table": {
  "caption": "WL Grand Cherokee family: what the box mounts to",
  "head": ["Model / years", "Roof", "Crossbar notes", "Box notes"],
  "rows": [
   ["Grand Cherokee (WL), 2022–2026, incl. 4xe", "Flush side rails on railed trims", "Thule 47 in bars; Yakima SkyLine and Rhino-Rack Vortex at fixed points (~24.5 in Vortex)", "Box minimum spread at or below your bars' spread"],
   ["Grand Cherokee L (WL), 2021–2026", "Flush side rails; longer roof", "Amazon bars name the L; check brand kits separately", "More room ahead of the liftgate"],
   ["Grand Cherokee (WK2), 2021 two-row", "Previous generation", "Different parts (Thule Podium, kit THKIT3142)", "Not covered here"],
   ["Any WL with no rails", "No rails", "Rhino-Rack lists naked-roof systems", "Soft bag can strap on without a rack"],
  ],
 },
 "look_for": [
  {"h": "Crossbars for the WL's flush rails",
   "body": "A cargo box clamps to crossbars, and on the Grand Cherokee the bars carry all the fit. The WL's rails are flush to the roof, so raised-rail towers that wrap under a rail won't work. etrailer's 2023 Grand Cherokee list is almost all flush-rail systems: Thule uses Evo Flush Rail feet with a custom fit kit and 47 in bars, while the Yakima SkyLine and Rhino-Rack Vortex bolt to fixed mounting points in the rails. Clamp-on Amazon bars grip the rail and slide. Buy bars that name your body, two-row 2022+ or L 2021+, then pick the box. Our Grand Cherokee roof rack page lists fit-checked sets."},
  {"h": "Fixed points and the 24.5 in spread",
   "body": "Fixed mounting points are strong and repeatable, but they set the bar spread for you. etrailer lists the Rhino-Rack Vortex on the 2023 Grand Cherokee at about 24.5 in, not adjustable. Boxes with a lower minimum fit it: the Yakima SkyBox 16 and CBX 16 start at 24 in, Thule lists 21-13/16 in for the Motion 3 (per etrailer), and Rhino-Rack's MasterFit 440 starts at 620 mm, about 24.4 in. The SportRack Vista XL's first position is 25-7/8 in and Thule doesn't publish a spread for the Force 3 L, so confirm those against your bars. Clamp-on bars let you choose."},
  {"h": "165 lb bars and box weight",
   "body": "The brand-name systems on etrailer's Grand Cherokee list, Thule WingBar Evo, Yakima SkyLine and Rhino-Rack Vortex, are rated at 165 lb. Some Amazon bars print 220 to 300 lb, but the roof limit in your owner's manual still caps the total. The hard boxes here weigh 38.6 lb (Rhino-Rack MasterFit 440) to 57 lb (Yakima CBX 16), which leaves roughly 108 to 126 lb for gear on 165 lb bars. Boxes with their own cargo rating, like the 165 lb Thule Motion 3 XL and Force 3 L and the 75 kg MasterFit, don't raise that ceiling."},
  {"h": "Two-row vs L: roof length and the liftgate",
   "body": "The three-row L has a longer roof than the two-row Grand Cherokee, which gives a long box more room ahead of the liftgate's arc. On the two-row, a shorter box is the safer bet: the Thule Force 3 L packs 16 cu ft into 76.8 in, and the SportRack Vista XL fits 18 cu ft into 63 in. etrailer's experts measure from the front crossbar to the line where the roof and hatch meet, then compare that with the box maker's figure; Thule lists more than 50 5/8 in for the Force 3 L. Because fixed-point bars can't move, slide the box forward on them instead."},
  {"h": "Width on 47 in bars and the sunroof",
   "body": "Thule's Grand Cherokee system uses 47 in bars, so a wide box fills most of them. The 38 in CBX 16 and Vista XL leave about 9 in, the 36 in SkyBox 16 leaves about 11 in and the 32 in MasterFit 440 about 15 in, which is the most room here for a slim mount beside the box. The sunroof is the other front-of-roof check. etrailer says the Thule WingBar Evo doesn't interfere with the 2023 Grand Cherokee's factory sunroof, but its Rhino-Rack Vortex page warns that opening a sunroof with cargo on the rack could cause contact. Keep it closed with a box on."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbars", "Flush-rail bars that name the WL two-row or L", "WK2 bars or raised-rail towers"],
   ["Crossbar spread", "A minimum of 24.5 in or less for fixed-point Vortex bars", "Boxes that start above your fixed spread"],
   ["Box weight", "Under about 50 lb on 165 lb bars", "Heavy boxes packed to their volume"],
   ["Length", "Under about 80 in on the two-row; longer on the L", "Long boxes pushed back over the hatch line"],
   ["Width", "32–36 in on 47 in bars if you want room beside it", "Assuming room for a bike beside a 38 in box"],
   ["Opening", "Dual-side for curbside loading", "Rear-opening lids if you can't reach behind a tall SUV"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Grand Cherokee (makers' specs; Motion 3 spread and Vista XL positions per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Fixed 24.5 in (Vortex)?"],
  "rows": [
   ["Yakima SkyBox 16 Carbonite", "16 cu ft", "81 × 36 × 15 in", "47 lb", "24–34.5 in", "Yes"],
   ["Thule Motion 3 XL", "18 cu ft", "84.7 × 35 × 17 in", "51 lb", "21-13/16 to 36-9/16 in", "Yes"],
   ["Rhino-Rack MasterFit 440", "15.5 cu ft", "76 × 32 × 17 in", "38.6 lb", "620–930 mm (about 24.4–36.6 in)", "Yes; fits Vortex bars directly"],
   ["Yakima CBX 16", "16 cu ft", "83 × 38 × 15 in", "57 lb", "24–35.5 in", "Yes"],
   ["Thule Force 3 L", "16 cu ft", "76.8 × 33.3 × 16.8 in", "43 lb", "Not published; confirm", "Confirm"],
   ["SportRack Vista XL", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed at 25-7/8, 27-7/8 or 29-7/8 in", "No; needs clamp-on bars"],
   ["Rightline Gear Sport 3", "18 cu ft", "48 × 36 × 18 in", "Soft bag", "Straps; rack optional", "Straps to bars"],
  ],
 },
 "picks": [
  {"asin": "B001PUZXGK", "role": "Best overall", "price": "$599",
   "pros": ["24 in minimum spread fits a fixed 24.5 in rack", "15 in tall, one of the lowest here", "47 lb, leaving 118 lb of a 165 lb rating", "Dual-side opening, SKS locks, SuperLatch", "$599 on sale at Yakima (regular $749); limited lifetime warranty"],
   "cons": ["36 in wide, leaving about 11 in on 47 in bars", "81 in long; check the two-row's liftgate", "Skis only up to 185 cm"],
   "body": "The SkyBox 16 Carbonite is the safest all-round choice for a Grand Cherokee because its spread range starts low enough for the fixed-point racks. Yakima lists it at 16 cu ft and 81 x 36 x 15 in, with a 47 lb box weight, dual-side opening, SuperLatch security and SKS locks, and a 24 to 34.5 in crossbar spread. It installs with no assembly on Yakima StreamLine bars and most factory or aerodynamic crossbars, takes skis and boards up to 185 cm, and carries a limited lifetime warranty. It was $599 on sale at Yakima when we checked, down from $749.\n\nOn a WL, that 24 in minimum is the key number: it sits just under the roughly 24.5 in fixed spread etrailer lists for the Rhino-Rack Vortex, and well inside any clamp-on bar setting. The 47 lb box leaves 118 lb for gear on 165 lb bars, before the manual's roof figure, and its 15 in height helps at garage doors. On the two-row, 81 in is long enough to check the liftgate once; on the L's longer roof there is more room. At 36 in wide it fills most of a 47 in Thule bar.",
   "who": "Grand Cherokee and L owners who want a proven 16 cu ft box that fits fixed-point racks.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "81 × 36 × 15 in"], ["Box weight", "47 lb"], ["Crossbar spread", "24–34.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS, SuperLatch"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0HGC24R2P", "role": "Best for skis", "price": "$1,149.95 (Thule)",
   "pros": ["18 cu ft with skis up to 200 cm", "21-13/16 in minimum spread (etrailer), the lowest here", "Thule rates it for 165 lb of cargo", "One-handed dual-side opening, PowerClick, SlideLock", "Limited lifetime warranty per etrailer"],
   "cons": ["$1,149.95, the priciest box here", "84.7 in long; best suited to the L's roof", "This Amazon listing is a Limited Edition finish; confirm the color"],
   "body": "For a Grand Cherokee that heads to the ski hill, the Thule Motion 3 XL takes the longest skis on this page. Thule lists it at 18 cu ft, 84.7 x 35 x 17 in and 51 lb, with a 165 lb maximum load and room for 5 to 7 pairs of skis up to 200 cm. The lid opens from either side with one hand, SlideLock separates locking from opening, and PowerClick mounts show when the clamps are tight. etrailer lists a 21-13/16 to 36-9/16 in spread and a limited lifetime warranty for the Motion 3 line. Thule lists it at $1,149.95; this Amazon listing is a Limited Edition version, so check the finish.\n\nIts wide spread range is the Grand Cherokee advantage: 21-13/16 in is comfortably below a fixed 24.5 in Vortex setting, so it mounts on any bar setup here. Length is the question. At 84.7 in, it suits the L's longer roof best; on the two-row, measure from the front bar to the roof-hatch line against Thule's figure of more than 52 3/32 in before you buy. On 165 lb bars, the 51 lb box leaves about 114 lb for skis, boots and bags.",
   "who": "Skiers, especially with an L, who want 18 cu ft and 200 cm ski length.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "84.7 × 35 × 17 in"], ["Box weight", "51 lb"], ["Max load", "165 lb"], ["Crossbar spread", "21-13/16 to 36-9/16 in (etrailer)"], ["Ski length", "Up to 200 cm"], ["Front clearance", "More than 52 3/32 in (Thule)"], ["Mount / lock", "PowerClick / SlideLock"]]},
  {"asin": "B07B4P7WYX", "role": "Best with Rhino-Rack bars", "price": "Not listed on Rhino-Rack's page; check listing",
   "pros": ["Works directly with Rhino-Rack Vortex bars, per Rhino-Rack", "620 mm (about 24.4 in) minimum spacing", "38.6 lb, the lightest hard box here", "Rated for 75 kg (about 165 lb) of cargo", "Dual-side opening, three locking points, 5-year warranty"],
   "cons": ["24.4 in minimum is only just under a 24.5 in fixed spread; confirm", "Rhino-Rack doesn't list a price on its page", "No ski length published"],
   "body": "If your Grand Cherokee wears the Rhino-Rack Vortex system etrailer lists for the 2023 model, the MasterFit 440 is the box built to match. Rhino-Rack lists it at 440 L (15.5 cu ft), 76 x 32 x 17 in outside and 74 x 30 x 15 in inside, with a 38.6 lb box weight, a 75 kg maximum load, dual-side opening, three locking points and a twist-to-tighten, press-to-lock clamp. It works directly with Vortex and Euro bars and needs the RUBK-MF kit for Rhino-Rack's Heavy Duty bars. Rhino-Rack covers it for 5 years; its page doesn't list a price.\n\nThe spread is close. Rhino-Rack requires 620 to 930 mm between the bars, about 24.4 to 36.6 in, and etrailer lists the Vortex's fixed spread at about 24.5 in, so it should sit at the bottom of the range; measure your bars before ordering. The rest suits the WL well. At 38.6 lb it leaves about 126 lb of a 165 lb rating for gear, at 76 in it gives the two-row's liftgate room, and at 32 in wide it leaves about 15 in on 47 in bars. On Thule or Amazon bars, confirm the clamp fits.",
   "who": "Grand Cherokee owners on Rhino-Rack Vortex bars who want a light, matched box.",
   "specs": [["Volume", "15.5 cu ft (440 L)"], ["Exterior", "76 × 32 × 17 in"], ["Interior", "74 × 30 × 15 in"], ["Box weight", "38.6 lb"], ["Max load", "75 kg (about 165 lb)"], ["Crossbar spacing", "620–930 mm (about 24.4–36.6 in)"], ["Fit", "Vortex and Euro bars direct; RUBK-MF kit for Heavy Duty"], ["Warranty", "5 years"]]},
  {"asin": "B0C41RZ4HM", "role": "Most usable space", "price": "$699",
   "pros": ["Flat floor that Yakima says maximizes usable space", "24–35.5 in spread fits a 24.5 in fixed rack", "15 in tall", "Made in the USA; about 10-minute install", "Dual-side opening, SKS locks, limited lifetime warranty"],
   "cons": ["57 lb, the heaviest here", "38 in wide, leaving about 9 in on 47 in bars", "83 in long; measure the two-row's liftgate"],
   "body": "The Yakima CBX 16 is the box for bins and carry-ons. Yakima lists it at 16 cu ft and 83 x 38 x 15 in, and says its flattened floor gives market-leading usable space. It opens from both sides, takes skis and boards up to 185 cm, and comes with SKS locks and a limited lifetime warranty. Yakima says it installs in about 10 minutes, builds it in the USA and prices it at $699. Its 24 to 35.5 in spread range starts below the roughly 24.5 in fixed spread etrailer lists for the Rhino-Rack Vortex, so it mounts on fixed-point racks as well as clamp-on bars.\n\nThe trade-offs on a Grand Cherokee are weight, width and length. At 57 lb it is the heaviest box here, which leaves 108 lb for cargo on 165 lb bars, so pack it with bulky, light gear. At 38 in wide it leaves only about 9 in of a 47 in Thule bar. And at 83 in it is long for the two-row's roof, so measure from the front bar to the roof-hatch line before buying; on the L there is more room. Its 15 in height is a plus at the garage door.",
   "who": "Owners, especially of the L, who pack square loads and want a low 16 cu ft box.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "83 × 38 × 15 in"], ["Box weight", "57 lb"], ["Crossbar spread", "24–35.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Install", "About 10 min"], ["Made in", "USA"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0DYQ4T5ZZ", "role": "Shortest 16 cu ft", "price": "$879.95 (Thule)",
   "pros": ["16 cu ft in 76.8 in, the shortest 16 here", "43 lb", "Thule rates it for 165 lb of cargo", "Thule lists front clearance of more than 50 5/8 in", "Dual-side opening, PowerClick, SlideLock; made in the USA"],
   "cons": ["Thule doesn't publish a crossbar spread; confirm against 24.5 in", "Skis only up to 175 cm", "$879.95 and listed as temporarily out of stock at Thule"],
   "body": "On the two-row Grand Cherokee's shorter roof, a short box gives the liftgate the most room, and the Thule Force 3 L is the shortest 16 cu ft box here. Thule lists it at 76.8 x 33.3 x 16.8 in with a 43 lb box weight, a 165 lb maximum load and room for 5 to 7 pairs of skis up to 175 cm or 3 to 5 snowboards. It opens from both sides, locks with SlideLock, clamps with PowerClick, and Thule lists it as made in the USA at $879.95, temporarily out of stock on its own store when we checked.\n\nThule gives a front clearance figure of more than 50 5/8 in, the smallest of the Thule boxes here, which you can compare with the distance from your front bar to the roof-hatch line. At 43 lb it leaves about 122 lb for gear on 165 lb bars. The open question is spread: Thule's page doesn't list one, and on a fixed-point rack with about 24.5 in between the bars that matters, so confirm it on the listing or with Thule before ordering. On clamp-on bars you can set whatever it needs.",
   "who": "Two-row Grand Cherokee owners who want 16 cu ft with the most liftgate room.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "76.8 × 33.3 × 16.8 in"], ["Box weight", "43 lb"], ["Max load", "165 lb"], ["Ski length", "Up to 175 cm"], ["Front clearance", "More than 50 5/8 in (Thule)"], ["Mount / lock", "PowerClick / SlideLock"], ["Crossbar spread", "Not published; confirm"]]},
  {"asin": "B00BCLL8C0", "role": "Budget hard box", "price": "$449.95",
   "pros": ["18 cu ft for $449.95", "63 in long, the shortest hard box here", "Tool-free hardware and a lock", "Fits square, round and most factory bars, per SportRack", "UV-resistant ABS"],
   "cons": ["First mounting position is 25-7/8 in, too wide for a fixed 24.5 in rack", "Rear-opening lid; 19 in tall", "Box weight, load rating and warranty not published; confirm"],
   "body": "The SportRack Vista XL is the cheapest way to lock 18 cu ft on a Grand Cherokee, as long as your bars can move. SportRack lists it at 63 x 38 x 19 in with 18 cu ft, a UV-resistant ABS shell, tool-free mounting hardware and a lock, for $449.95. At 63 in it is the shortest hard box here, which suits the two-row's roof and leaves the liftgate plenty of room. etrailer's expert gives three fixed mounting positions: 25-7/8, 27-7/8 and 29-7/8 in center to center.\n\nThat is the Grand Cherokee catch. A Rhino-Rack Vortex set at a fixed 24.5 in spread is narrower than the Vista XL's first position, so this box needs clamp-on bars you can slide to one of its three settings, like the adjustable Amazon sets on our roof rack page. The rear-opening lid means reaching up from behind the SUV, and at 19 in tall it adds the most height here. SportRack doesn't publish a box weight, load rating or warranty, so confirm all three on the listing before loading it against 165 lb bars.",
   "who": "Budget buyers with adjustable clamp-on bars who want a big, short box.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "63 × 38 × 19 in"], ["Opening", "Rear"], ["Mounting positions", "25-7/8, 27-7/8 or 29-7/8 in (etrailer)"], ["Hardware", "Tool-free; lock included"], ["Material", "UV-resistant ABS"], ["Box weight / max load", "Not published; confirm"], ["Price", "$449.95 (SportRack)"]]},
  {"asin": "B0012INT98", "role": "Best budget", "price": "$139.99 (RealTruck)",
   "pros": ["18 cu ft for $139.99", "Welded seams and a waterproof zipper, per RealTruck", "Straps to bars at any spread", "Works with or without a roof rack", "Folds into a stuff sack"],
   "cons": ["No lock", "Soft sides; no skis", "1-year warranty"],
   "body": "A soft carrier sidesteps the Grand Cherokee's spread question entirely, because it straps to the bars wherever they are. RealTruck lists the Rightline Gear Sport 3 at 18 cu ft and 48 x 36 x 18 in, with welded seams and an SZIP waterproof zipper that Rightline calls 100 percent waterproof, no flap required. It is made for SUVs and minivans with or without a roof rack, and comes with four attachment straps, four car clips and a stuff sack. RealTruck lists it at $139.99 with a one-year warranty, and showed it as temporarily unavailable when we checked.\n\nOn fixed-point bars at about 24.5 in, the straps simply wrap both bars. Without bars, the flush rails leave no gap for a strap, so the kit's car clips at the door openings take over. At 48 in long it is clear of the liftgate on both the two-row and the L. There is no lock, so empty it overnight, and pack it full so the sides don't flap at highway speed. Its contents still count against the 165 lb bar rating and the manual's roof limit.",
   "who": "Occasional travelers who want 18 cu ft of dry roof space for under $150.",
   "specs": [["Volume", "18 cu ft"], ["Size", "48 × 36 × 18 in"], ["Type", "Soft carrier"], ["Weatherproofing", "Welded seams, SZIP waterproof zipper"], ["Mounting", "With or without roof rack; 4 straps, 4 car clips"], ["Lock", "None"], ["Warranty", "1 year"], ["Price", "$139.99 (RealTruck)"]]},
 ],
 "install": [
  "Confirm your body (2022+ two-row or 2021+ L), then fit flush-rail crossbars that name it; torque fixed-point feet or rail clamps to spec.",
  "Measure the bar spread center to center (about 24.5 in on a Rhino-Rack Vortex) and check that it sits inside the box's range.",
  "Note the bar rating (165 lb on brand-name systems) and your owner's manual roof figure, and plan box plus cargo under the lower one.",
  "With a helper, set the box on the bars, center it, and slide it forward. Measure from the front bar to the roof-hatch line against the box maker's clearance figure.",
  "Snug the clamps, open the power liftgate slowly to check the gap, then tighten to spec, lock the box and mounts, and rock it from each corner.",
  "Keep the sunroof closed while the box is on, load heavy items low and centered, and recheck the clamps after the first drive.",
 ],
 "avoid": [
  {"h": "A box that needs more spread than your rack gives", "body": "Fixed-point Vortex bars sit at about 24.5 in. The SportRack Vista XL starts at 25-7/8 in and needs adjustable bars."},
  {"h": "WK2 bars on a WL", "body": "A 2021 two-row is WK2; a 2021 L is WL. Match the body before buying bars for a box."},
  {"h": "Loading to the box's volume", "body": "16–18 cu ft holds more than 165 lb bars allow once the box weight is counted. Pack light, bulky gear up top."},
  {"h": "Opening the sunroof with a box on", "body": "etrailer warns that opening a sunroof with cargo on a Vortex rack could cause contact. Keep it shut."},
 ],
 "verdict": {
  "thesis": "Get flush-rail bars for your WL body, check the spread, then choose the Yakima SkyBox 16 for most owners, the Thule Motion 3 XL for skis, the Rhino-Rack MasterFit 440 on Vortex bars, or the Rightline Sport 3 on a budget.",
  "body": "The WL Grand Cherokee's flush rails and fixed mounting points make spread the first cargo box question. The SkyBox 16, CBX 16, Motion 3 XL and MasterFit 440 all start at or below the roughly 24.5 in fixed spread etrailer lists for the Rhino-Rack Vortex, so they work on fixed-point and clamp-on bars alike. The SkyBox 16 is the balanced pick, the CBX 16 suits square loads, the Motion 3 XL is for skiers and fits best on the L's longer roof, and the MasterFit 440 is the light match for Vortex bars. The Force 3 L is the shortest 16 for the two-row if you confirm its spread, the SportRack Vista XL needs adjustable bars, and the Rightline Sport 3 is the budget soft option. Whichever you choose, 165 lb bars and your manual's roof figure decide how full it gets.\n\nStart with the bars; our Grand Cherokee roof rack page lists flush-rail crossbars for the two-row and the L. For heavy gear, the Grand Cherokee's Class IV trailer hitch takes a hitch cargo carrier easily, and floor liners for the WL protect the cabin on wet trips. The vehicle hub lists every fit-checked accessory for your Grand Cherokee.",
 },
 "sources": [
  ["Yakima SkyBox 16 Carbonite (Yakima)", "https://yakima.com/collections/roof-boxes/products/skybox-16-carbonite-2014-2023"],
  ["Yakima CBX 16 (Yakima)", "https://yakima.com/products/cbx-16"],
  ["Thule Motion 3 XL (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-motion-3-xl-_-639850"],
  ["Thule Force 3 L (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-force-3-l-_-645750"],
  ["Thule Motion 3 spread and warranty (etrailer)", "https://www.etrailer.com/Roof-Box/Thule/TH59PN.html"],
  ["Rhino-Rack MasterFit Roof Box 440L RMFT440 (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-racks/roof-boxes/roof-boxes/masterfit-roof-box-440l-black-_rmft440"],
  ["SportRack Vista XL (SportRack)", "https://www.sportrack.com/product/vista-xl-cargo-box/"],
  ["SportRack Vista XL mounting positions (etrailer)", "https://www.etrailer.com/question-156482.html"],
  ["Rightline Gear Sport 3 (RealTruck)", "https://realtruck.com/p/rightline-gear-cargo-bags/rlg-100s30/"],
  ["Rhino-Rack Vortex, 2023 Grand Cherokee, fixed spread and sunroof note (etrailer)", "https://www.etrailer.com/Roof-Rack/Jeep/Grand%20Cherokee/2023/RR34FR66GR.html"],
  ["Grand Cherokee Thule fit answers incl. hatch clearance method (etrailer)", "https://www.etrailer.com/answers.aspx?AnswerModel=Grand+Cherokee&Manufacturer=Thule&Filter=fit&AnswerMake=Jeep"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Grand Cherokee roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B001PUZXGK","Yakima SkyBox 16 Carbonite Rooftop Cargo Box, 16 cu ft (15 in tall)","Yakima","$550–$750",{},"Universal box; 24 in minimum fits ~24.5 in fixed racks. Confirm spread and hatch clearance."),
 ("B0HGC24R2P","Thule Motion 3 XL Rooftop Cargo Box, 18 cu ft, Limited Edition","Thule","$1,100–$1,250",{},"Universal box; 21-13/16 in minimum spread. Confirm finish and liftgate clearance (84.7 in)."),
 ("B07B4P7WYX","Rhino-Rack MasterFit Roof Box 440L (Black)","Rhino-Rack","See listing",{},"Fits Vortex bars directly; 620 mm minimum, confirm against your fixed spread."),
 ("B0C41RZ4HM","Yakima CBX 16 Aerodynamic Rooftop Cargo Box for Cars, Wagons and SUVs","Yakima","$650–$800",{},"Universal box; 24-35.5 in spread, 57 lb. Confirm hatch clearance (83 in long)."),
 ("B0DYQ4T5ZZ","Thule Force 3 L Rooftop Cargo Box, 16 cu ft (76.8 in long)","Thule","$800–$950",{},"Universal box; spread not published, confirm against your bars."),
 ("B00BCLL8C0","SportRack Vista XL Rear Opening Cargo Box, 18 cu ft, Black","SportRack","$400–$500",{},"Starts at 25-7/8 in; needs adjustable bars. Confirm box weight and load rating."),
 ("B0012INT98","Rightline Gear Sport 3 Waterproof Rooftop Cargo Carrier, 18 cu ft, Black","Rightline Gear","$120–$160",{},"Universal soft carrier, no lock; confirm strap routing on your bars."),
]
