"""Long-form article — Best Floor Mats & Liners for 2020–2026 Kia Telluride (1st gen, ON).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("kia", "telluride", "2020-present", "floor-mats")

TITLE = "Best Floor Liners for 2020–2026 Kia Telluride: 5 Three-Row Picks From WeatherTech to TOUGHPRO"
META = ("Five Telluride floor liner sets from WeatherTech, Husky, Smartliner, TOUGHPRO and SUPER LINER, matched to "
        "7- vs 8-seat layouts and the second-row console.")

FAQ = [
 ("Do 7-seat and 8-seat Tellurides take the same liners?",
  "The front row does, the second row may not. Seven-seat Tellurides have two captain's chairs, with or without a center console between them; eight-seat Tellurides have a bench. SUPER LINER's set is for buckets without a center console. WeatherTech asks you to confirm seating layout. Husky's 95691 front and second-row set and Smartliner's 3-row set are listed broadly for the Telluride; check the second-row piece against your layout."),
 ("Do Palisade liners fit the Telluride?",
  "Don't assume so. The Telluride and Palisade share a platform, and some front-row parts overlap, but most makers sell separate sets because the cabins differ. Buy liners that name the Telluride."),
 ("Did the 2023 facelift change the Telluride's floor?",
  "The 2023 refresh changed styling, the dash screens and added the X-Pro trims, but the listings here span 2020 to 2025 or 2026, which indicates the floor carried over. A few stop at 2024 or 2025; confirm later years with the seller."),
 ("Is WeatherTech's full set worth the price?",
  "It covers all three rows in one order with WeatherTech's laser-measured fit and lifetime limited warranty, according to WeatherTech. It's the most expensive option here. If the third row rarely gets used, Husky's front and second-row set plus a third-row add-on can cost less."),
 ("What about the Telluride's second-row console?",
  "Some seven-seat Tellurides have a console between the captain's chairs, others an open walkway. The second-row liner either wraps around the console or bridges the walkway. SUPER LINER is for buckets without a console. Look at your second row and compare with listing photos."),
 ("Does Smartliner's set include a cargo liner?",
  "Yes. Smartliner's Telluride set covers three rows plus a cargo liner behind the third row. Smartliner says its liners are one-piece, 100% recyclable TPE with a limited lifetime warranty."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto Kia's retention posts and clear of the pedals at full travel. Remove the factory mat first and heel-test the liner toward the pedals."),
 ("Do X-Line and X-Pro trims need different liners?",
  "No. X-Line and X-Pro change ground clearance, tires and styling, not the cabin floor. Seating layout is what matters."),
 ("How do I clean three-row liners?",
  "Pull each row, shake them out, rinse and scrub with mild soap, and dry before reinstalling. Skip silicone protectants."),
 ("Will these fit a next-generation Telluride?",
  "Liners on this page are for the first-generation Telluride. If Kia releases a redesigned Telluride, buy liners that name that generation; a new platform or cabin usually means new liners."),
 ("Can I mix liner brands row by row?",
  "Yes. Each row is a separate piece, and nothing requires them to match. A common approach is Husky's front and second-row liners for their walls and warranty, plus a cheaper third-row piece and a cargo liner from another brand. Make sure every piece names the Telluride and your second-row layout, and check that the edges don't overlap awkwardly at the seat rails."),
 ("How much do Telluride floor liners cost?",
  "On this page, TOUGHPRO's three rows run about $110–$150, SUPER LINER about $130–$170, Husky's front and second row about $130–$170, Smartliner's three rows plus cargo about $180–$230 and WeatherTech's full set about $280–$360. Prices on Amazon change daily, so check the live price before ordering."),
 ("Do I need a cargo liner if I have floor liners?",
  "They protect different things. Floor liners cover the footwells where shoes land; the cargo area takes strollers, groceries, sports bags and dogs. The Telluride's cargo area behind the third row is carpeted, and spills there soak in quickly. If you carry anything wet or dirty back there, a cargo liner is worth adding. Smartliner's set includes one, and several brands sell Telluride cargo liners separately."),
 ("Are liners safe with the Telluride's driver-side retention posts?",
  "Yes, when the liner is cut for the Telluride and seated properly. The retention posts hold the driver liner back from the pedals. Every liner on this page claims a Telluride-specific cut. After installing, push the driver liner toward the pedals with your heel and press the brake and accelerator to the floor. If anything touches, reseat the liner on the posts before driving."),
]

ARTICLE = {
 "dek": "Five three-row liner options for the first-generation Telluride, from WeatherTech's full set to TOUGHPRO's made-in-USA rubber. The second row decides fit: captain's chairs with a console, captain's chairs without one, or a bench.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2020–2026 Telluride (seating, console, rows covered), on published maker specs (material, origin, warranty) and on coverage in listing photos. WeatherTech, Husky and Smartliner claims come from their own sites, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Second row decides fit.** Captain's chairs with or without a console, or a bench.",
  "**WeatherTech covers all three rows.** Laser-measured, lifetime limited warranty.",
  "**Husky covers front and second row.** Add a third-row piece.",
  "**Smartliner adds a cargo liner.** Three rows plus cargo in one set.",
  "**Palisade liners aren't a safe substitute.** Buy Telluride-named listings.",
 ],
 "top_picks": [
  {"asin": "B08T6P8XG8", "role": "Best overall", "why": "WeatherTech FloorLiners full set, 1st–3rd row"},
  {"asin": "B081W2SH36", "role": "Best made in USA", "why": "Husky WeatherBeater 95691 front and 2nd row, 2020–2025"},
  {"asin": "B08258HJGQ", "role": "Best with cargo", "why": "Smartliner 3-row plus cargo liner, 2020–2025"},
  {"asin": "B07RN1362T", "role": "Best rubber", "why": "TOUGHPRO floor set plus 3rd row, listed as made in USA"},
  {"asin": "B0B1ZLL74S", "role": "Best for no-console buckets", "why": "SUPER LINER 3-row for captain's chairs without console"},
 ],
 "fit_table": {
  "caption": "2020–2026 Telluride: second-row layouts",
  "head": ["Layout", "Seats", "Liner note"],
  "rows": [
   ["Captain's chairs, open walkway", "7", "SUPER LINER (no console); confirm others"],
   ["Captain's chairs with console", "7", "Confirm with seller; WeatherTech fit tool"],
   ["Second-row bench", "8", "Confirm second-row piece"],
   ["Facelift", "2023+", "Floor carried over; check year ranges"],
  ],
 },
 "look_for": [
  {"h": "Your second-row layout",
   "body": "The Telluride's second row comes three ways: a bench for eight seats, captain's chairs with an open walkway for seven, or captain's chairs with a center console. The second-row liner is shaped for one of those. SUPER LINER's set says buckets without a center console. WeatherTech asks buyers to confirm seating. Husky's 95691 and Smartliner's set list the Telluride broadly, so check listing photos of the second-row piece against your vehicle. It's the single detail most likely to cause a return on this SUV."},
  {"h": "Three rows and cargo",
   "body": "A Telluride has four zones: front, second row, third row and cargo. WeatherTech's full set covers all three rows. Smartliner adds a cargo liner behind the third row. TOUGHPRO's set includes the third row. Husky's 95691 covers the front and second row only, so add a third-row piece. Families that use the third row daily should buy full coverage; families that rarely fold it up can save money with a two-row set and a cargo liner."},
  {"h": "Liner or rubber mat",
   "body": "WeatherTech, Husky and Smartliner sell molded liners with raised walls. TOUGHPRO sells heavy-duty rubber mats that its listings describe as made in USA; rubber is heavier, grippier and stays flexible in the cold, but its edges are lower. SUPER LINER sells TPE liners. In snow country, the walls of a molded liner hold more melt; in a mild climate, rubber mats are easier to live with."},
  {"h": "Warranty and origin",
   "body": "WeatherTech says its liners are laser-measured and backed by a lifetime limited warranty. Husky says WeatherBeater is laser-measured, made in the USA and covered by a lifetime warranty against cracks and breaks. Smartliner says its liners are one-piece, 100% recyclable TPE designed in the US, with a limited lifetime warranty. TOUGHPRO's listings say made in USA. SUPER LINER doesn't publish comparable terms we could check."},
  {"h": "Retention and pedal clearance",
   "body": "Kia uses retention posts in the driver footwell. A Telluride-specific liner lines up with them. Seat the driver liner, heel-test it toward the pedals and press the brake and accelerator to the floor. Never stack a liner on the factory mat."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Vehicle", "Telluride named", "Palisade listings"],
   ["Second row", "Bench, buckets, console named", "Kits that don't state seating"],
   ["Rows", "The zones you use", "Paying for rows you don't need"],
   ["Walls", "Raised lip for snowmelt", "Flat mats in snow country"],
   ["Retention", "Hook holes for Kia's posts", "Loose mats"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2020–2026 Telluride",
  "head": ["Type", "Example", "Coverage", "Walls", "Price band", "Best for"],
  "rows": [
   ["Laser-measured full set", "WeatherTech", "3 rows", "High", "$280–$360", "Full coverage, one brand"],
   ["USA-made molded liner", "Husky 95691", "Front + 2nd", "High", "$130–$170", "Snow country"],
   ["One-piece TPE + cargo", "Smartliner", "3 rows + cargo", "Medium-high", "$180–$230", "Families who haul"],
   ["USA-made rubber", "TOUGHPRO", "3 rows", "Low-medium", "$110–$150", "Budget, grip"],
   ["TPE 3-row", "SUPER LINER", "3 rows", "Medium", "$130–$170", "No-console buckets"],
  ],
 },
 "picks": [
  {"asin": "B08T6P8XG8", "role": "Best overall", "price": "$280–$360",
   "pros": ["All three rows in one set", "Laser-measured fit", "Lifetime limited warranty", "High walls", "Big-brand fit program"],
   "cons": ["Most expensive here", "Confirm seating layout", "Cargo liner sold separately"],
   "body": "WeatherTech's FloorLiners full set covers the first, second and third rows of the Telluride. WeatherTech says its liners are laser-measured for a custom fit and backed by a lifetime limited warranty; its FloorLiner HP line uses injection-molded TPE with beveled high walls and an anti-skid underside, made in America.\n\nOne brand across three rows means consistent fit and wall height through the cabin, and WeatherTech's fit program splits parts by seating layout. That's why the listing asks you to confirm your layout: run your VIN or trim through WeatherTech's fit checker to get the right second-row piece for a bench, captain's chairs, or chairs with a console.\n\nIt's the priciest option here. For families who use all three rows and plan to keep the Telluride, it's the most complete single purchase. Add a cargo liner if you haul gear. WeatherTech's laser-measured pattern also tends to run higher up the footwell sides than budget sets, which protects the carpet where kids kick the seat bases. If you keep the Telluride for the long haul, the lifetime limited warranty and the ability to buy a single replacement row later make the higher price easier to justify.",
   "who": "Families who use all three rows and want one brand throughout.",
   "specs": [["Brand", "WeatherTech"], ["Rows", "1st–3rd"], ["Fits", "Kia Telluride (confirm seating)"], ["Fit method", "Laser-measured"], ["Warranty", "Lifetime limited"], ["Price band", "$280–$360"]]},
  {"asin": "B081W2SH36", "role": "Best made in USA", "price": "$130–$170",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs", "Front and 2nd row, 3 pieces", "Lists 2020–2025"],
   "cons": ["No third row or cargo", "Title stops at 2025; confirm 2026", "Confirm second-row layout"],
   "body": "Husky's WeatherBeater 95691 covers the front and second row of the 2020–2025 Telluride. Husky says WeatherBeater is laser-measured using vehicle-specific data, designed and made in the USA from ProGard and anchored by StayPut nibs, with a lifetime warranty against cracks and breaks.\n\nThe front and second row get the most traffic in a family SUV, so this set protects the zones that matter most for less than half of WeatherTech's full set. The firm walls hold snowmelt well.\n\nAdd a third-row liner (Smartliner and TOUGHPRO both include one in their sets, and Husky sells separate third-row parts). Confirm your second-row layout and a 2026 model year with Husky's fit tool before ordering. Husky's StayPut nibs grip the Telluride's carpet firmly, and the one-piece second-row liner covers the whole rear floor on bench-seat vehicles. On captain's-chair vehicles, check how Husky's second-row piece treats the walkway or console area, because that's where the layouts differ.",
   "who": "Owners who want US-made liners where the mud lands.",
   "specs": [["Part #", "Husky 95691"], ["Pieces", "3"], ["Fits", "2020–2025 Telluride, front + 2nd row"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B08258HJGQ", "role": "Best with cargo", "price": "$180–$230",
   "pros": ["Three rows plus cargo liner", "One-piece, 100% recyclable TPE", "Limited lifetime warranty", "No PVC, latex or BPA", "Covers transmission tunnel and under-seat areas, per Smartliner"],
   "cons": ["Title stops at 2025", "Confirm second-row layout", "Walls lower than Husky's"],
   "body": "Smartliner's Telluride set covers all three rows plus a cargo liner behind the third row, for 2020–2025. Smartliner says its liners are molded from one piece of heavy-duty, 100% recyclable TPE, free of PVC, latex and BPA, and covered by a limited lifetime warranty; the company is based in Apopka, Florida.\n\nFor families who haul sports gear or groceries, the cargo liner is what sets it apart from WeatherTech's set at a lower price. You get four zones covered with a written lifetime warranty.\n\nConfirm your second-row layout and a 2026 model year with the seller before ordering. The cargo liner sits behind the upright third row. If you often fold the third row flat for luggage, remember that the folded seatbacks aren't covered; a separate seatback cover or a blanket protects them.",
   "who": "Families who want every zone covered with a warranty.",
   "specs": [["Covers", "3 rows + cargo"], ["Fits", "2020–2025 Telluride"], ["Material", "One-piece TPE"], ["Warranty", "Limited lifetime"], ["Company", "Apopka, Florida"]]},
  {"asin": "B07RN1362T", "role": "Best rubber", "price": "$110–$150",
   "pros": ["Front, 2nd and 3rd row", "Heavy-duty rubber listed as made in USA", "Grips and stays flexible in the cold", "Lower price for three rows", "Heavy enough to stay put"],
   "cons": ["Lower edges than molded liners", "Heavy to carry", "Confirm seating layout"],
   "body": "TOUGHPRO's set covers the front, second and third rows of the 2020–2025 Telluride. Its listing describes heavy-duty rubber mats made in USA.\n\nRubber is a practical family choice: it grips kids' shoes, stays flexible in freezing weather and doesn't slide. The trade-off is containment; the edges are lower than a molded liner's, so empty the front mats after heavy snow.\n\nFor three rows under $150, it's the budget pick. Confirm the second-row piece against your layout. Rubber mats also shrug off the kind of wear that comes with car seats: a heavy child seat base and repeated scuffing from little shoes. If you want taller walls up front but rubber in the back, you can mix TOUGHPRO's rear rows with Husky's front pair.",
   "who": "Families who want three rows of rubber on a budget.",
   "specs": [["Rows", "3"], ["Fits", "2020–2025 Telluride"], ["Material", "Heavy-duty rubber"], ["Made in", "USA (per listing)"], ["Price band", "$110–$150"]]},
  {"asin": "B0B1ZLL74S", "role": "Best for no-console buckets", "price": "$130–$170",
   "pros": ["Cut for captain's chairs without a console", "3-row liner set", "TPE with raised edges", "Covers the walkway to the third row", "Mid-range price"],
   "cons": ["Only for no-console buckets", "Title stops at 2024", "No published warranty"],
   "body": "SUPER LINER's 3-row set is listed for 2020–2024 Telluride with second-row buckets and no center console. That's a narrow fit, and if it's yours, the second-row piece bridges the walkway where third-row passengers step through.\n\nIt's a TPE liner with raised edges. SUPER LINER doesn't publish warranty terms we could check, and the title stops at 2024, so confirm a 2025 or 2026 with the seller.\n\nFor a seven-seat Telluride with the open walkway, it's a precise fit at a fair price. Look at the listing photos of the second-row piece and compare them with your walkway before ordering. If your Telluride has a console between the chairs, this isn't the set; ask WeatherTech or Husky for a console-specific piece.",
   "who": "Seven-seat owners with an open walkway between the captain's chairs.",
   "specs": [["Rows", "3"], ["Fits", "2020–2024 Telluride, 2nd-row buckets without console"], ["Material", "TPE"], ["2025+", "Confirm with seller"], ["Price band", "$130–$170"]]},
 ],
 "install": [
  "Check your second row: bench, captain's chairs with console, or without.",
  "Remove the factory mats from every row and vacuum.",
  "Hook the driver liner onto the retention posts and heel-test it toward the pedals.",
  "Fit the passenger and second-row liners; slide and fold the second row to check clearance.",
  "Fit the third-row and cargo liners; fold the third row up and down.",
  "Press the pedals to the floor before driving.",
 ],
 "avoid": [
  {"h": "Wrong second-row layout", "body": "Console, walkway and bench each need a different second-row piece."},
  {"h": "Palisade listings", "body": "Shared platform, different cabin."},
  {"h": "Ignoring the third row", "body": "Kids track mud there; cover it if it's used."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy WeatherTech's full set for three rows from one brand, Husky's 95691 for US-made front and second-row liners, and Smartliner if you want the cargo area covered too.",
  "body": "The Telluride is fit by its second row. Once you know bench, captain's chairs with a console, or without, the choice is straightforward. WeatherTech covers three rows with a lifetime limited warranty, Husky is the US-made choice for the busiest rows, Smartliner adds a cargo liner, TOUGHPRO is the rubber budget pick and SUPER LINER fits the no-console layout precisely.\n\nAfter the floors, most Telluride owners add a trailer hitch for a bike rack or small trailer, and a roof rack on the factory rails."},
 "sources": [
  ["WeatherTech FloorLiner HP buying guide (WeatherTech)", "https://www.weathertech.com/blog/product-spotlight/new-weathertech-floorliner-hp.html"],
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners 95691 Telluride listing", "https://www.amazon.com/dp/B081W2SH36"],
  ["SMARTLINER home page (SMARTLINER)", "https://www.smartliner-usa.com/"],
  ["TOUGHPRO Telluride listing", "https://www.amazon.com/dp/B07RN1362T"],
  ["Kia Telluride (Wikipedia)", "https://en.wikipedia.org/wiki/Kia_Telluride"],
 ],
}

FITS = [
 ("B08T6P8XG8","WeatherTech FloorLiners full set (1st-3rd row), Telluride","WeatherTech","$280–$360",{"rows":3},"Brand-name full 3-row set; confirm seating layout."),
 ("B081W2SH36","Husky Liners Weatherbeater 3-piece front & 2nd row, 2020-2025 Telluride (95691)","Husky Liners","$130–$170",{"rows":2},"Front + 2nd row; add a 3rd-row liner."),
 ("B08258HJGQ","SMARTLINER 3-Row + Cargo Liner set, 2020-2025 Telluride","SMARTLINER","$180–$230",{"rows":3},"Includes cargo liner behind 3rd row."),
 ("B07RN1362T","TOUGHPRO Floor Mat Set + 3rd Row (made in USA), 2020-2025 Telluride","TOUGHPRO","$110–$150",{"rows":3},"Full 3-row set."),
 ("B0B1ZLL74S","SUPER LINER 3-Row Liner Set, 2020-2024 Telluride with 2nd-row buckets, no center console","SUPER LINER","$130–$170",{"rows":3,"second_row":"bucket"},"Bucket seats without console only; confirm 2025."),
]
