"""Long-form article — Best Tonneau Covers for 2019–2026 Ram 1500 (5th gen, DT).
Mirrors the approved pilot (ford_f150_2021_tonneau.py). No invented hands-on testing: every spec below comes
from the manufacturer/retailer pages listed in SOURCES (checked 2026-09-24). ASINs from Amazon listing titles
that name the 2019+ Ram 1500 (new body), bed length and RamBox / multifunction-tailgate status.
"""

KEY = ("ram", "1500", "2019-present", "tonneau-covers")

TITLE = "Best Tonneau Covers for 2019–2026 Ram 1500: 6 Picks Matched to Bed, RamBox and Tailgate"
META = ("Six tonneau covers for the DT Ram 1500's 5'7\" and 6'4\" beds, with the RamBox, multifunction "
        "tailgate, TRX bed bar and Ram Classic part-number traps spelled out.")

FAQ = [
 ("What is the best tonneau cover for a 2019+ Ram 1500?",
  "For most non-RamBox trucks, the BAKFlip MX4 448227 on the 5'7\" bed. It has aluminum panels with polymer cores, a 400 lb evenly distributed rating, auto-latches, a 5-year warranty and a clamp-on install BAK puts at 30 minutes or less. RealTruck lists it at $1,049.99. If that is more than you want to spend, the Gator EFX GC34008 gives you a lockable aluminum tri-fold for $599. If you open the bed all day, the RetraxPRO MX is the one to look at."),
 ("Do Ram 1500 Classic tonneau covers fit the new-body 2019+ Ram 1500?",
  "No. Ram sold the older DS truck as the Ram 1500 Classic next to the new DT from 2019 through 2024, and the two use different bed rails. Covers are listed separately: the Tyger T3 for the DT is TG-BC3D1044 and says \"Not Fit 19-24 Classic\", while the Classic version is TG-BC3D1015. BAK, Retrax and TruXedo do the same. If a listing says \"2009–2018, 2019–2024 Classic\", it is for the old truck. Look for \"new body style\" or a 2019–2026 range with no Classic mention."),
 ("Do I need a RamBox-specific tonneau cover?",
  "Yes. The RamBox bins are built into the bed sides, and every maker we checked sells a separate RamBox part: BAKFlip MX4 448227RB, RetraxPRO MX 80244 and TruXedo Lo Pro 584901. A standard cover such as the MX4 448227 is listed without RamBox. The bed is still 5'7\" long, so measuring won't tell you which one you need. Look at the bed sides. If there are lidded storage bins over the wheel wells, buy the RamBox SKU."),
 ("Will a tonneau cover work with the Ram multifunction tailgate?",
  "Only if the part number says so. The 60/40 split tailgate, a $995 option Ram added during the 2019 model year, changes the top edge the cover seals against. Many standard covers, including the MX4 448227, Gator EFX GC34008, RetraxPRO MX 80243 and Tyger T3, are listed as not compatible. BAK sells 448226 for the split gate, and the RamBox versions of the MX4, RetraxPRO and Lo Pro are listed as working with or without it."),
 ("How do I tell if my Ram 1500 has the 5'7\" or 6'4\" bed?",
  "Measure inside the bed at the rail, from the front bulkhead to the inside of the closed tailgate. About 67 in (listings print 67.4\") is the 5'7\" box, and about 76 in (76.3\") is the 6'4\" box. Crew Cab trucks come with either length. Quad Cab trucks have the 6'4\" bed. Every TRX has the 5'7\" bed."),
 ("Does a tonneau cover fit the Ram TRX?",
  "Usually, but not with the TRX bed bar in place. RealTruck's fitment notes for the MX4, Gator EFX, RetraxPRO MX, UnderCover Flex and TruXedo Lo Pro all say the same thing: \"Will NOT Work w/ Ram TRX Bed Bar\" and the bar must be removed before installation. The TRX uses the 5'7\" bed, so buy the 5'7\" part that matches your RamBox and tailgate setup, then decide whether you would rather have the cover or the bar."),
 ("Why does water get in at the back of the bed on a 2019+ Ram?",
  "Owners on 5thGenRams trace most leaks to the tailgate, not the cover. The DT has a wide gap, around an inch according to one thread, between the tailgate ends and the bed caps, and RamBox trucks have a similar gap beside the bins. The fixes owners report are foam weatherstrip, the strip TruXedo includes, and dedicated tailgate gap seals. Even with those, owners say to expect some water in a hard downpour or at a car wash."),
 ("Hard or soft cover — which is better on a Ram 1500?",
  "Buy a hard cover if you leave gear in the bed. The MX4, Gator EFX, UnderCover Flex and RetraxPRO lock under a locked tailgate and carry 300 to 500 lb spread evenly. Soft covers such as the Tyger T3 ($237) and TruXedo Lo Pro ($489.99) weigh less and open fast, but vinyl gives little security and has no load rating. They keep weather and road dirt out and are easy to remove."),
 ("Can I stand on or put cargo on top of a Ram 1500 tonneau cover?",
  "Only on hard covers and only up to the maker's evenly distributed rating: 500 lb for the RetraxPRO MX, 400 lb for the BAKFlip MX4 and UnderCover Flex, and 300 lb for the Gator EFX. Those numbers assume a flat load spread across the panels. A knee, a boot heel or the corner of a toolbox concentrates the weight and can dent a panel well below the rating. Soft covers are not rated to carry anything."),
 ("Is a retractable cover worth it on a Ram 1500?",
  "Only if you open the bed many times a day. The RetraxPRO MX locks at any position, doesn't depend on the tailgate, and has the highest rating here at 500 lb. It is also the most expensive: RealTruck lists the 80243 at $2,149.99 and the RamBox 80244 at $1,949.99. The canister also takes space at the front of the bed. For weekend and commuter use, a folding cover is the better value."),
]

ARTICLE = {
 "dek": "Six covers that fit the fifth-generation Ram 1500's 5'7\" and 6'4\" beds, from a $237 soft tri-fold to a $2,150 retractable. For each one we give the load rating, warranty and install time, and the exact part number for RamBox, the multifunction tailgate and the TRX.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these covers ourselves. We ranked them on published specs (load rating, materials, warranty, install time), on the fitment each maker lists for the 2019–2026 Ram 1500, and on what owners report on the 5thGenRams forum. Prices were checked at RealTruck or the manufacturer in September 2026. Amazon prices change daily, so the button shows the live price.",
 "takeaways": [
  "**The 2019+ Ram 1500 has four fitment types, not two:** 5'7\" or 6'4\" bed, each with or without RamBox. The multifunction (split) tailgate is a fifth variable. The cover has to match all of them.",
  "**The Ram 1500 Classic is a different truck.** It was sold next to the new body from 2019 to 2024 and needs different covers. If a listing names \"Classic\" or \"2009–2018\", it isn't for the DT.",
  "**RamBox trucks need RamBox part numbers:** MX4 448227RB, RetraxPRO MX 80244, Lo Pro 584901. The bed length is the same, but the cover isn't.",
  "**Load ratings differ a lot:** 500 lb for the RetraxPRO MX, 400 lb for the BAKFlip MX4 and UnderCover Flex, 300 lb for the Gator EFX. Soft covers have no rating.",
  "**On a TRX, the bed bar has to come off.** Every hard and soft cover from RealTruck's brands here lists it as incompatible.",
 ],
 "top_picks": [
  {"asin": "B07BSCQYB2", "role": "Best overall", "why": "400 lb rating, auto-latches, 5-year warranty, installs in 30 minutes or less"},
  {"asin": "B07XLV7BB2", "role": "Best value hard cover", "why": "Lockable aluminum tri-fold for $599 that keeps full stake-pocket access"},
  {"asin": "B07C9YSJP1", "role": "Best retractable", "why": "500 lb rating and locks at any position; RamBox version 80244 available"},
  {"asin": "B07B4962C5", "role": "Best for RamBox + split tailgate", "why": "Soft roll-up listed for RamBox trucks with or without the multifunction tailgate"},
  {"asin": "B07H8LBLG3", "role": "Best budget", "why": "$237 soft tri-fold with a 5-year warranty, built for the new body only"},
 ],
 "fit_table": {
  "caption": "2019–2026 Ram 1500 (DT) beds and the options that change the part number",
  "head": ["Bed", "Inside length at rail", "Cabs", "Notes"],
  "rows": [
   ["5'7\"", "67.4 in", "Crew Cab (incl. TRX)", "The most common bed and the one with the most cover choices."],
   ["5'7\" with RamBox", "67.4 in", "Crew Cab", "Needs RamBox SKUs (MX4 448227RB, RetraxPRO 80244, Lo Pro 584901)."],
   ["6'4\"", "76.3 in", "Quad Cab, Crew Cab", "Order the 6'4\" SKU (MX4 448223, Gator EFX GC34009, Tyger TG-BC3D1045)."],
   ["Multifunction tailgate", "Either bed", "Optional from 2019", "Many standard covers are listed as not compatible. Buy a split-gate SKU (MX4 448226)."],
   ["Ram 1500 Classic (DS)", "67.4 / 76.3 in", "Sold 2019–2024", "Different truck and different rails. DT covers don't fit it."],
  ],
 },
 "look_for": [
  {"h": "Bed length, then RamBox, then tailgate",
   "body": "Start with the tape measure. At the rail, the 5'7\" bed is about 67 in and the 6'4\" bed about 76 in. Next, check the bed sides. RamBox bins over the wheel wells mean you need a RamBox-specific cover, and measuring won't show that. Last, check the tailgate. A 60/40 split gate that swings open like barn doors is the multifunction tailgate, and many standard covers are listed as not compatible with it. Amazon titles from BAK, Retrax, Gator and TruXedo name all three, for example \"w/RamBox, w/ or w/o Multifunction TG 5' 7\". If a listing leaves any of them out, ask the seller before you buy."},
  {"h": "New body vs Ram 1500 Classic",
   "body": "From 2019 to 2024, Ram sold two different trucks as the \"Ram 1500\": the new DT and the older DS, badged Classic. Their bed rails differ, so the covers do too. Tyger's DT cover says \"Not Fit 19-24 Classic\" in the title, and BAK's older 448207 is listed for \"2009–2023 Dodge Ram\", which means the Classic body. The Classic has a traditional grille and interior. The DT has the RAM-lettered tailgate and a newer interior. If a used-parts ad just says \"fits 2019 Ram\", find out which body it came from. Tyger's Classic cover, TG-BC3D1015, is the one to buy if you have the old body."},
  {"h": "Load rating and what \"hard\" means",
   "body": "The published distributed-load rating is the fairest way to compare hard covers. On this page: RetraxPRO MX 500 lb, BAKFlip MX4 400 lb, UnderCover Flex 400 lb, Gator EFX 300 lb. Soft covers, including the TruXedo Lo Pro and Tyger T3, carry no rating. They keep weather out but aren't made to hold anything. If your truck sits under snow for days or you want to strap light gear on top, buy a rated cover and keep point loads off the panel centers. A soft cover sags and pools water under snow, while a rated panel stays flat and sheds it over the sides."},
  {"h": "The TRX bed bar and other bed accessories",
   "body": "RealTruck's fitment notes for every cover on this page from BAK, Gator, Retrax, UnderCover and TruXedo say they won't work with the Ram TRX bed bar, which has to be removed before installation. The TRX shares the 5'7\" bed, so the cover itself fits, but you have to choose between the cover and the bar. The same logic applies to aftermarket bed-rail caps and over-rail bedliners. Tyger says over-rail liners need small holes cut for its clamps. Anything that sits where the clamps land has to come off or be trimmed. RealTruck's notes don't mention the 2025+ RHO, so RHO owners should ask the seller about any bed hardware."},
  {"h": "Sealing the Ram's tailgate gap",
   "body": "Most Ram leak complaints come from the truck, not the cover. On 5thGenRams, owners describe gaps of about an inch at the tailgate corners of 2019+ trucks, and a similar gap beside the RamBox bins. The fixes they report are foam weatherstrip, the strip TruXedo includes, and dedicated tailgate gap seals. Budget for a seal kit whatever cover you buy, and keep electronics off the rear corners of the bed. RamBox trucks add a second gap between the bins and the tailgate, and owners there recommend dedicated RamBox gap seals. Even with seals, one owner sums it up: casual rain stays mostly out, but a pressure washer or a torrential downpour still gets in. Treat any cover as weather-resistant, not waterproof."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "\"2019–2026 Ram 1500\" plus bed length, RamBox status and tailgate type in the title", "Listings that say \"Classic\" or \"2009–2018\", or leave out RamBox"],
   ["Frame", "Aluminum rails, no-drill clamps inside the bed rail", "Unspecified frame material or plastic clamps"],
   ["Load rating", "A published distributed rating (300–500 lb) if you need a hard cover", "\"Heavy duty\" with no number"],
   ["Tailgate", "An explicit \"works with multifunction tailgate\" line if you have the split gate", "No mention of the split gate on a truck that has one"],
   ["Seals", "Tailgate seal named; plan on a gap seal for DT corners", "Assuming the cover alone keeps the rear corners dry"],
   ["Warranty", "3 years minimum; 5 years to lifetime is better", "90 days or nothing stated"],
  ],
 },
 "types_table": {
  "caption": "Cover types compared on the Ram 1500",
  "head": ["Type", "Price on this page", "Security", "Bed access", "Load on top", "Best for"],
  "rows": [
   ["Soft tri-fold", "~$237 (Tyger T3)", "Low (vinyl)", "About ⅔; can be removed", "None", "Budget weather cover"],
   ["Soft roll-up", "~$490 (Lo Pro)", "Low (vinyl)", "Full bed", "None", "RamBox trucks, tall loads"],
   ["Hard tri-fold", "~$599 (Gator EFX)", "High with tailgate locked", "About ⅔", "300 lb", "Security on a budget"],
   ["Hard fold, flips to cab", "~$1,050–$1,100 (MX4, Flex)", "High with tailgate locked", "Up to 100% folded against the cab", "400 lb", "Best all-round"],
   ["Retractable", "~$1,950–$2,150 (RetraxPRO)", "High; locks at any position", "Full, minus the canister", "500 lb", "Daily open/close, contractors"],
  ],
 },
 "picks": [
  {"asin": "B07BSCQYB2", "role": "Best overall", "price": "$1,050",
   "pros": ["400 lb distributed load rating", "Polymer-reinforced aluminum panels", "Patented auto-latching", "Third brake light stays visible in every position", "5-year warranty; assembled in Missouri"],
   "cons": ["Not for the multifunction tailgate (use 448226) or RamBox (use 448227RB)", "TRX bed bar must come off", "More than 4× the price of the Tyger T3"],
   "body": "The MX4 is the benchmark folding cover, and the 448227 is the version most DT owners need: 2019–2026 Ram 1500, 5'7\" bed, no RamBox, standard tailgate. BAK uses aluminum panels reinforced with high-density polymer and rates the cover at 400 lb evenly distributed, enough for a snow load or a sheet of plywood laid flat. The latches close automatically, the cover sits flush with the bed rails, and BAK says the third brake light stays visible in every fold position. RealTruck lists it at $1,049.99 (list $1,199.99).\n\nThe MX4 lineup has a matching part for nearly every DT configuration. The 448227RB for RamBox trucks works with or without the multifunction tailgate and costs $1,099.99. The 448226 for non-RamBox trucks with the split gate costs $1,249.99 at RealTruck. Its Amazon title reads 2020–2026, so 2019 owners should ask the seller. The 448223 covers the 6'4\" bed. BAK puts install at 30 minutes or less with no drilling, and the warranty is five years. The cover clamps inside the rails, so the stake pockets stay free for tie-downs.",
   "who": "Owners who want a secure hard cover that stays on year-round and a part number for every RamBox and tailgate combination.",
   "specs": [["Type", "Hard folding"], ["Part #", "448227 (5'7\") · 448227RB (RamBox) · 448226 (split gate) · 448223 (6'4\")"], ["Fits", "2019–2026 Ram 1500 (new body); not Classic"], ["Material", "Polymer-reinforced aluminum panels, aluminum rails"], ["Load rating", "400 lb distributed"], ["Latching", "Auto-latch, locks with tailgate"], ["Install", "30 min or less, no drill"], ["Warranty", "5 years"], ["Made in", "USA (Missouri)"]]},
  {"asin": "B07XLV7BB2", "role": "Best value hard cover", "price": "$599",
   "pros": ["Multi-layer aircraft-grade aluminum panels", "About half the MX4's price", "Keeps full stake-pocket access", "No-drill install in 30 minutes or less", "6'4\" version (GC34009) listed"],
   "cons": ["300 lb rating (MX4 and Flex: 400 lb)", "2-year warranty", "No RamBox or split-tailgate version on this SKU"],
   "body": "The Gator EFX gives you a lockable aluminum hard cover for about half what the BAK costs. The GC34008 is listed for the 2019–2026 Ram 1500 5'7\" bed without RamBox and without the multifunction tailgate, and RealTruck prices it at $599. The panels are multi-layer aircraft-grade aluminum and are rated for 300 lb evenly distributed. That is less than the MX4, but enough for snow and light gear laid flat.\n\nFolded, Gator says the EFX leaves about two-thirds of the bed open for tall cargo, and the stake pockets stay usable, which matters if you run a rack or tie-downs there. It clamps on in 30 minutes or less with no drilling. As with the others, the TRX bed bar has to come off. The main trade-off is the warranty: two years against five for BAK and three for UnderCover. On Jeep Gladiator forums, EFX owners report two-plus years of dry beds, which is a fair indication the design seals well when installed carefully. The GC34009 covers the 6'4\" bed with the same RamBox and tailgate restrictions.",
   "who": "Buyers who want a hard, lockable cover under $600 on a non-RamBox truck with the standard tailgate.",
   "specs": [["Type", "Hard tri-fold"], ["Part #", "GC34008 (5'7\") · GC34009 (6'4\")"], ["Fits", "2019–2026 Ram 1500, w/o RamBox, w/o multifunction TG"], ["Material", "Multi-layer aircraft-grade aluminum"], ["Load rating", "300 lb distributed"], ["Bed access folded", "About ⅔"], ["Install", "30 min or less, no drill"], ["Warranty", "2 years"]]},
  {"asin": "B07BV1YBGN", "role": "Best full-access folding cover", "price": "$1,100",
   "pros": ["400 lb rating", "Folds flush against the rear window for 100% bed access", "Can also lock at the ⅔-open position", "Aluminum-skinned panels", "No-drill install under an hour"],
   "cons": ["Same price as the MX4 with a shorter (3-year) warranty", "Not for the multifunction tailgate", "TRX bed bar must come off"],
   "body": "The UnderCover Flex matches the MX4's 400 lb rating and adds one thing the others don't have: it folds all the way up flush against the rear window, held by built-in prop rods, so you get 100% of the bed. Or you can strap it at the two-thirds position for everyday runs. That helps on a 5'7\" bed, where a few inches of folded stack decides whether a dirt bike or an appliance box fits. The panels are aluminum-skinned with a gloss black finish.\n\nThe FX31008 is listed for the 2019–2026 Ram 1500 5'7\" bed, not with the multifunction tailgate, and RealTruck prices it at $1,099.99. It installs in under an hour without drilling. The drawback is the warranty: three years, against five for the MX4 at nearly the same price. UnderCover lists a RamBox version, FX31011, but its Amazon title covers only 2019–2022 and says it won't work with the black track system, so newer RamBox owners should confirm fit before ordering. For the 6'4\" bed, check UnderCover's listings for the matching part number.",
   "who": "Owners who haul tall loads and want a hard, lockable cover that can give back the entire bed.",
   "specs": [["Type", "Hard folding (flips to cab)"], ["Part #", "FX31008 (5'7\")"], ["Fits", "2019–2026 Ram 1500, w/o multifunction TG"], ["Material", "Aluminum-skinned panels, gloss black"], ["Load rating", "400 lb distributed"], ["Bed access", "100% folded to the window, or ⅔"], ["Install", "<1 hr, no drill"], ["Warranty", "3 years limited"]]},
  {"asin": "B07C9YSJP1", "role": "Best retractable", "price": "$2,150",
   "pros": ["500 lb rating, the highest here", "Locks at any position", "Works independently of the tailgate", "Double-wall aluminum slats", "Limited lifetime warranty"],
   "cons": ["Most expensive cover on this page", "Canister takes space at the front of the bed", "Standard 80243 isn't for the multifunction tailgate"],
   "body": "A retractable is the only style here that opens the whole bed and still locks at any point. You can keep the front third covered for tools and leave the back open for a load. The RetraxPRO MX uses double-wall aluminum slats rated for 500 lb, and it opens and closes independently of the tailgate. RealTruck lists the 80243 (2019–2026 Ram 1500, 5'7\", not for the multifunction tailgate) at $2,149.99, with a limited lifetime warranty that isn't transferable.\n\nFor RamBox trucks, Retrax sells the 80244, which RealTruck lists at $1,949.99. Its Amazon title says it fits with or without the multifunction tailgate, which makes it the easiest premium option for a truck that has both RamBox and the split gate. Install is under an hour with clamps and no drilling. The canister costs some bed length at the bulkhead, though flat sheet goods can slide under it. If you plan to add crossbars later, the XR version (T-80243) adds T-slot rails, which is the usual way to fit a bed rack over a cover.",
   "who": "Contractors and daily users who open the bed many times a day, and RamBox owners who want the most secure cover available.",
   "specs": [["Type", "Retractable (manual)"], ["Part #", "80243 (5'7\") · 80244 (RamBox) · XR: T-80243"], ["Fits", "2019–2026 Ram 1500 (new body)"], ["Material", "Double-wall aluminum slats, matte black"], ["Load rating", "500 lb distributed"], ["Lock", "Locks at any position"], ["Install", "<1 hr, clamp-on"], ["Warranty", "Limited lifetime (non-transferable)"]]},
  {"asin": "B07B4962C5", "role": "Best for RamBox + split tailgate", "price": "$490",
   "pros": ["Listed for RamBox trucks with or without the multifunction tailgate", "Sits ¾ in above the rails", "Tear-resistant vinyl, leather-grain finish", "Quick-release; comes off without tools", "Limited lifetime warranty; assembled in South Dakota"],
   "cons": ["Vinyl gives little security", "No load rating", "Amazon title stops at 2024; confirm 2025–2026 with the seller"],
   "body": "RamBox trucks with the split tailgate have the fewest cover options, and the TruXedo Lo Pro 584901 is one of the few built for exactly that combination. Its Amazon title lists the 2019+ Ram 1500 with RamBox, with or without the multifunction tailgate, on the 5'7\" bed. RealTruck lists it at $489.99 (list $519.99). The vinyl sits only ¾ in above the rails, so from the side the truck looks almost uncovered, and the roll-up gives back the full bed in seconds.\n\nThe Lo Pro clamps inside the bed with no drilling, and a quick-release system lets you take it off without tools. TruXedo backs it with a limited lifetime warranty. It is still vinyl, so it keeps rain and prying eyes out but won't stop a knife, and it carries nothing on top. For non-RamBox trucks with the split gate, TruXedo lists the 585801, and 5thGenRams owners report that TruXedo's included weatherstrip helps with the DT's tailgate-corner gaps. If you sell the truck, the quick-release makes it easy to move the cover to another RamBox Ram of the same years.",
   "who": "RamBox owners, especially with the split tailgate, who want full bed access and a low-profile look for under $500.",
   "specs": [["Type", "Soft roll-up"], ["Part #", "584901 (RamBox) · 585801 (split gate, no RamBox)"], ["Fits", "2019–2024 Ram 1500 w/RamBox, w/ or w/o multifunction TG (per listing)"], ["Material", "Industrial-grade tear-resistant vinyl"], ["Profile", "¾ in above rails"], ["Install", "<1 hr, no drill"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B07H8LBLG3", "role": "Best budget", "price": "$237",
   "pros": ["$237, the lowest price here", "24 oz marine-grade vinyl on aluminum frames", "Stainless steel clamps", "5–10 minute install (maker's figure)", "5-year warranty"],
   "cons": ["Not for RamBox, the multifunction tailgate or the Classic", "Vinyl offers little security", "Over-rail bedliners need small holes cut"],
   "body": "The Tyger T3 is the cheapest cover here that is built specifically for the new-body Ram rather than sold as a one-size-fits-many listing. Tyger lists TG-BC3D1044 for the 2019–2026 Ram 1500 5'7\" bed at $237, and the title says \"Not Fit 19-24 Classic\". It uses dual-coated 24 oz marine-grade vinyl over aircraft-grade aluminum frames with stainless clamps, weighs 33.7 lb, and has a 5-year warranty, which is longer than the Gator EFX at more than twice the price.\n\nTyger's fitment notes are specific. The T3 isn't compatible with RamBox or the multifunction tailgate, and trucks with an over-the-rail bedliner need small holes cut for the clamps. Under-rail and spray-in liners need nothing. Tyger quotes a 5–10 minute install, and the tri-fold can flip up against the cab or come off entirely. The 6'4\" bed has its own part, TG-BC3D1045. For RamBox trucks or the split gate, look at the TruXedo Lo Pro above instead. At 33.7 lb, one person can lift the T3 off in a minute.",
   "who": "First-time cover buyers, lease trucks and anyone with a plain 5'7\" or 6'4\" bed who wants weather protection for under $250.",
   "specs": [["Type", "Soft tri-fold"], ["Part #", "TG-BC3D1044 (5'7\") · TG-BC3D1045 (6'4\")"], ["Fits", "2019–2026 Ram 1500; not Classic, RamBox or split gate"], ["Material", "24 oz marine vinyl, aluminum frames"], ["Clamps", "Stainless steel"], ["Weight", "33.7 lb"], ["Install", "5–10 min (maker's figure), no drill"], ["Warranty", "5 years (US)"]]},
 ],
 "install": [
  "Empty the bed. Remove the TRX bed bar if you have one, plus any rail caps or cargo cleats where the clamps will sit.",
  "Confirm the part number against the truck: bed length, RamBox or not, multifunction tailgate or not, and new body rather than Classic.",
  "Set the rails or frame inside the bed rails with the front seal tight against the bulkhead, then fit the clamps loosely.",
  "Center the cover side to side, close the tailgate, and check that the rear seal meets it along its full width.",
  "Tighten the clamps evenly side to side. Overtightening one side twists the frame and leaves a gap.",
  "Fit a tailgate gap seal or the supplied foam at the rear corners, where DT owners report most of their leaks.",
  "Route any drain tubes the cover includes, and re-check the clamps after the first week of driving.",
 ],
 "avoid": [
  {"h": "Ram 1500 Classic parts on a new-body truck", "body": "\"Fits 2019 Ram 1500\" can mean the Classic. If the title names the Classic or 2009–2018, it's the wrong truck."},
  {"h": "Standard covers on a RamBox bed", "body": "The bed length is the same, but the bins change the fit. Buy the RamBox SKU, such as 448227RB, 80244 or 584901."},
  {"h": "Ignoring the split tailgate", "body": "Many standard covers are listed as not compatible with the multifunction tailgate. If your tailgate opens like barn doors, only buy listings that say they work with it."},
  {"h": "Expecting a dry bed without sealing the tailgate", "body": "The DT's tailgate-corner gaps let water past any cover. Plan on a gap seal and keep valuables away from the rear corners."},
 ],
 "verdict": {
  "thesis": "Match bed, RamBox and tailgate first, then pick: the BAKFlip MX4 for most trucks, the Gator EFX to save money, and the RetraxPRO MX if you open the bed all day.",
  "body": "The best cover for a 2019–2026 Ram 1500 is the one whose part number matches all three: bed length, RamBox and tailgate. After that, the MX4 has the best mix of load rating, warranty and part-number coverage. The Gator EFX is a lockable hard cover for $599. The UnderCover Flex is for owners who need the whole bed back. The RetraxPRO MX is worth $2,000 only if a cover that locks in any position saves you time every day. RamBox trucks with the split gate have the fewest options, and the TruXedo Lo Pro is one of them.\n\nIf you plan to add a bed rack later, choose the cover with that in mind, because the Retrax XR rails are the easiest way to mount one. Most owners then move on to floor liners for the DT cab and a trailer hitch upgrade. The vehicle hub lists every fit-checked accessory for your Ram.",
 },
 "sources": [
  ["BAKFlip MX4 448227 (RealTruck)", "https://realtruck.com/p/bakflip-mx4-tonneau-cover/bak-448227/"],
  ["BAKFlip MX4 448227RB RamBox (RealTruck)", "https://realtruck.com/p/bakflip-mx4-tonneau-cover/bak-448227rb/"],
  ["BAKFlip MX4 448226 multifunction tailgate (RealTruck)", "https://realtruck.com/p/bakflip-mx4-tonneau-cover/bak-448226/"],
  ["Gator EFX GC34008 (RealTruck)", "https://realtruck.com/p/gator-efx-hard-fold-tonneau-cover/guc-gc34008/"],
  ["UnderCover Flex FX31008 (RealTruck)", "https://realtruck.com/p/undercover-flex-tonneau-cover/udc-fx31008/"],
  ["RetraxPRO MX 80243 and 80244 (RealTruck)", "https://realtruck.com/p/retraxpro-mx-tonneau-cover/rtx-80243/"],
  ["TruXedo Lo Pro 584901 (RealTruck)", "https://realtruck.com/p/truxedo-lo-pro-tonneau-cover/trx-584901/"],
  ["Tyger T3 TG-BC3D1044 (Tyger Auto)", "https://www.tygerauto.com/tg-bc3d1044/tyger-t3-soft-tri-fold-fit-2019-2026-ram-1500-not-fit-19-24-classic-57-bed.html"],
  ["Ram adds multifunction tailgate to 2019 Ram 1500 (Stellantis Media)", "https://media.stellantisnorthamerica.com/newsrelease.do?id=20594&mid="],
  ["Tonneau cover leaks on 2019 Rams (5thGenRams)", "https://5thgenrams.com/community/threads/tonneau-cover-leaks-on-2019-rams.5981/"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note)
FITS = [
 ("B07BSCQYB2","BAKFlip MX4 Hard Folding Tonneau Cover 448227, 2019-2026 Ram 1500, not w/ Multi-Function Tailgate, 5'7\" Bed (67.4\")","BAK","$1,000–$1,200",{"bed_length_in":67,"rambox":False,"multifunction_tailgate":False},"5-year warranty; 400 lb rating. Not for RamBox or split tailgate."),
 ("B07XLV7BB2","Gator EFX Hard Tri-Fold Tonneau Cover GC34008, 2019-2025 Ram 1500 w/o RamBox, not w/ Multi-Function Tailgate, 5'7\" Bed","Gator","$550–$650",{"bed_length_in":67,"rambox":False,"multifunction_tailgate":False},"300 lb rating; 2-year warranty."),
 ("B07BV1YBGN","UnderCover Flex Hard Folding Tonneau Cover FX31008, 2019-2025 Ram 1500, not w/ Multi-Function Tailgate, 5'7\" Bed","UnderCover","$1,000–$1,150",{"bed_length_in":67,"multifunction_tailgate":False},"Folds flush to the rear window; 3-year warranty."),
 ("B07C9YSJP1","RetraxPRO MX Retractable Tonneau Cover 80243, 2019-2025 Ram 1500, not w/ Multi-Function Tailgate, 5'7\" Bed","Retrax","$1,950–$2,200",{"bed_length_in":67,"rambox":False,"multifunction_tailgate":False},"500 lb rating; canister uses front-of-bed space."),
 ("B07B4962C5","TruXedo Lo Pro Soft Roll-Up Tonneau Cover 584901, 2019-2024 Ram 1500 w/RamBox, w/ or w/o Multi-Function Tailgate, 5'7\" Bed","TruXedo","$470–$530",{"bed_length_in":67,"rambox":True},"RamBox trucks only; confirm 2025-2026 fit on the listing."),
 ("B07H8LBLG3","Tyger Auto T3 Soft Tri-Fold Tonneau Cover TG-BC3D1044, 2019-2026 Ram 1500 (not 19-24 Classic), 5'7\" Bed","Tyger Auto","$220–$260",{"bed_length_in":67,"rambox":False,"multifunction_tailgate":False},"Not for RamBox or split tailgate."),
 ("B07BSJRTNY","BAKFlip MX4 Hard Folding Tonneau Cover 448227RB, 2019-2026 Ram 1500 w/RamBox, w/ or w/o Multifunction TG, 5'7\" Bed","BAK","$1,050–$1,250",{"bed_length_in":67,"rambox":True},"RamBox version of #1."),
 ("B0BJ4CQM33","BAKFlip MX4 Hard Folding Tonneau Cover 448226, 2020-2026 Ram 1500 w/ Multi-Function (Splitgate) Tailgate, 5'7\" Bed","BAK","$1,150–$1,300",{"bed_length_in":67,"rambox":False,"multifunction_tailgate":True},"Split-tailgate version of #1; confirm 2019 fit with the seller."),
 ("B07DDSFPQL","RetraxPRO MX Retractable Tonneau Cover 80244, 2019-2025 Ram 1500 w/ RamBox, w/ and w/o Multi-Function Tailgate, 5'7\" Bed","Retrax","$1,900–$2,250",{"bed_length_in":67,"rambox":True},"RamBox version of #4."),
 ("B08V54F2GK","TruXedo Lo Pro Soft Roll-Up Tonneau Cover 585801, 2019-2024 Ram 1500 w/ Multi-Function Tailgate, 5'7\" Bed","TruXedo","$470–$530",{"bed_length_in":67,"rambox":False,"multifunction_tailgate":True},"Split-gate, non-RamBox version of #5; confirm 2025-2026 on listing."),
 ("B07BSK4TZC","BAKFlip MX4 Hard Folding Tonneau Cover 448223, 2019-2026 Ram 1500, not w/ Multi-Function Tailgate, 6'4\" Bed (76.3\")","BAK","$1,050–$1,250",{"bed_length_in":76,"multifunction_tailgate":False},"6'4\" version of #1."),
 ("B07XVRMC9S","Gator EFX Hard Tri-Fold Tonneau Cover GC34009, 2019-2025 Ram 1500 w/o RamBox, not w/ Multi-Function Tailgate, 6'4\" Bed","Gator","$550–$650",{"bed_length_in":76,"rambox":False,"multifunction_tailgate":False},"6'4\" version of #2."),
 ("B07M7L8X91","Tyger Auto T3 Soft Tri-Fold Tonneau Cover TG-BC3D1045, 2019-2025 Ram 1500 New Body (not Classic), 6'4\" Bed","Tyger Auto","$220–$270",{"bed_length_in":76,"rambox":False},"6'4\" version of #6."),
]
