"""Long-form article — Best Floor Mats & Liners for 2020–2025 Subaru Outback (6th gen, BT).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("subaru", "outback", "2020-present", "floor-mats")

TITLE = "Best Floor Liners for 2020–2025 Subaru Outback: 6 Picks That Also Fit the Legacy"
META = ("Six 6th-gen Outback floor liner sets from Husky, Subaru, OEDRO, YITAMOTOR, Auxko and budget TPE, with "
        "Legacy cross-fit, Wilderness notes and the 2026 cutoff.")

FAQ = [
 ("Do Outback liners fit the 2020–2025 Legacy?",
  "Usually, yes. The 6th-gen Outback and 7th-gen Legacy share a platform and cabin floor, and most listings on this page name both: Husky's 95541, Subaru's J501SAN100, YITAMOTOR, OEDRO, the generic 3D set and Auxko. Cargo liners are different, since the Legacy is a sedan with a trunk."),
 ("Does the Outback Wilderness take different liners?",
  "The Wilderness (2022–2025) shares the Outback cabin floor, so liners listed for the 2020–2025 Outback fit unless the listing excludes it. The Wilderness adds water-repellent upholstery and different trim, not a different floor."),
 ("Will 2020–2025 Outback liners fit a 2026 Outback?",
  "Treat the 2026 Outback as a new generation and buy liners that name it. Subaru redesigned the Outback for 2026, and floor liners are generation-specific."),
 ("Do 2015–2019 Outback liners fit a 2020?",
  "No. The 2020 Outback moved to the Subaru Global Platform with a new cabin floor. Husky's catalog shows the split: 99671 for 2015–2019 and 95541 for 2020–2025. Buy 2020+ listings."),
 ("Are Subaru's own heavy-gauge mats worth it?",
  "Subaru's J501SAN100 all-weather mats are a dealer part, sold as a set of four for the 2020–2025 Outback and Legacy. They fit the retention hooks exactly and cost less than Husky. They're mats with a heavy gauge rather than deep-walled liners, so they hold less standing water."),
 ("Is Husky's WeatherBeater worth it for an Outback?",
  "In snow country, yes. Husky says WeatherBeater is laser-measured, made in the USA and backed by a lifetime warranty against cracks and breaks, and its tall walls hold snowmelt. It costs more than Subaru's mats and the budget TPE sets."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto Subaru's retention hooks and clear of the pedals at full travel. Remove the factory mat first and heel-test the liner toward the pedals."),
 ("Should I add a cargo liner?",
  "If you carry a dog, skis or camping gear, yes. The Outback's cargo area is carpeted and it's one of the car's main uses. Choose one listed for the 6th-gen Outback wagon."),
 ("How do I clean liners after a ski trip?",
  "Pull them, knock off the snow, rinse and scrub with mild soap, and dry before reinstalling. Skip silicone protectants. Empty the driver liner often in winter."),
 ("Do XT turbo Outbacks need different liners?",
  "No. The 2.4-liter turbo XT trims share the cabin floor with the 2.5-liter cars. Engine choice affects towing, not floor liners."),
 ("How much do Outback liners cost?",
  "On this page, budget TPE sets run about $80–$130, Subaru's mats about $90–$130 and Husky's WeatherBeater about $130–$180. Amazon prices move daily."),
 ("Is there a Husky cargo liner for the 2020–2025 Outback?",
  "In the Amazon listings we found, Husky's Outback cargo liner (28801) is listed for 2015–2019, not the 6th gen. Subaru sells a cargo tray for the 2020–2025 Outback through dealers, and several aftermarket brands sell 6th-gen cargo liners. Make sure any cargo liner names the 2020–2025 Outback wagon, since the older generation's cargo floor is different."),
 ("Can I use Outback liners in a Subaru Ascent or Crosstrek?",
  "No. The Ascent is a three-row SUV with its own floor, and the Crosstrek is a smaller car. Both use the Subaru Global Platform, but liners are cut to the cabin, not the platform. Buy sets that name your model and years."),
 ("How long do Outback liners last?",
  "Several years for most TPE and WeatherBeater liners. The driver's heel area wears first. Husky's lifetime warranty covers cracks and breaks, which is the common failure for firm liners in cold climates. Budget TPE sets are usually replaceable after a few winters for less than the price of one premium set."),
]

ARTICLE = {
 "dek": "Six floor liner sets listed for the 6th-generation Outback, from Husky's made-in-USA WeatherBeater and Subaru's heavy-gauge mats to $80 TPE. Most also fit the 2020–2025 Legacy, and every trim including the Wilderness shares one floor.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2020–2025 Outback (and Legacy), on published maker specs (material, origin, warranty) and on coverage in listing photos. Husky claims come from its own site, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**One floor for 2020–2025.** Every Outback trim, Wilderness and XT included.",
  "**The Legacy shares it.** Most listings here name both cars.",
  "**2026 is a new generation.** Buy liners that name it.",
  "**Husky is the documented pick.** Made in the USA with a lifetime crack warranty.",
  "**Subaru's mats are the value OEM choice.** Heavy-gauge set of four.",
 ],
 "top_picks": [
  {"asin": "B08697PNQH", "role": "Best overall", "why": "Husky WeatherBeater 95541, 2020–2025 Outback and Legacy, made in USA"},
  {"asin": "B07WRSDBSS", "role": "Best factory option", "why": "Subaru heavy-gauge all-weather mats J501SAN100, set of 4"},
  {"asin": "B093L62R7H", "role": "Best TPE value", "why": "OEDRO TPE 1st and 2nd row, Outback and Legacy"},
  {"asin": "B09R1BJW74", "role": "Best 3D budget", "why": "3D custom-fit liners, all Outback and Legacy models"},
  {"asin": "B0948LXFWJ", "role": "Best budget", "why": "YITAMOTOR TPE, Outback and Legacy"},
 ],
 "fit_table": {
  "caption": "Outback floor liners by generation",
  "head": ["Car", "Years", "Liner note"],
  "rows": [
   ["Outback 6th gen (incl. Wilderness, XT)", "2020–2025", "All picks on this page"],
   ["Legacy 7th gen", "2020–2025", "Most picks list it; cargo liners differ"],
   ["Outback 5th gen", "2015–2019", "Not compatible (Husky 99671)"],
   ["Outback next gen", "2026+", "Buy liners that name it"],
  ],
 },
 "look_for": [
  {"h": "Generation and the Legacy",
   "body": "The 6th-gen Outback shares its platform and cabin floor with the 2020–2025 Legacy sedan, and nearly every listing on this page names both. That's handy for households with one of each. What doesn't carry over is the cargo area: the Outback is a wagon with a cargo floor, the Legacy a sedan with a trunk. On the generation boundaries, the 2020 Outback moved to the Subaru Global Platform, so 2015–2019 liners don't fit, and the 2026 Outback is a redesign that needs its own liners."},
  {"h": "Walls for snow and trailheads",
   "body": "The Outback is a snow-country and trailhead car, and snowmelt and mud are what liners are for. Husky's WeatherBeater uses a firm ProGard material with tall walls that hold slush. Subaru's heavy-gauge mats are thick and durable but flatter. The TPE sets (OEDRO, YITAMOTOR, Auxko, the generic 3D set) sit between them with raised edges. For a car that lives in the mountains, walls matter more than price."},
  {"h": "Wilderness and XT",
   "body": "The Wilderness adds water-repellent upholstery, more ground clearance and a ladder-style roof rack, but the cabin floor is the same as other 6th-gen Outbacks. The XT trims add the 2.4-liter turbo. Neither changes floor liners. Buy by generation, not trim."},
  {"h": "Warranty and material",
   "body": "Husky says WeatherBeater is laser-measured, designed and made in the USA from ProGard, anchored by StayPut nibs and covered by a lifetime warranty against cracks and breaks. Subaru's mats are genuine dealer parts. OEDRO, YITAMOTOR, Auxko and the generic 3D liners are TPE sets that don't publish comparable warranty terms we could check. In a car owners keep for a decade, the warranty is a fair tiebreaker."},
  {"h": "Retention and pedal clearance",
   "body": "Subaru uses retention hooks in the driver footwell. An Outback-specific liner lines up with them. Seat the driver liner, heel-test it toward the pedals and press the brake and accelerator to the floor. Never stack a liner on the factory mat."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2020–2025 in the title", "2015–2019 or 2026+ listings"],
   ["Legacy", "Named if you want cross-fit", "Legacy cargo liners in an Outback"],
   ["Walls", "Raised lip for snowmelt", "Flat mats in snow country"],
   ["Retention", "Hook holes for Subaru's posts", "Loose mats"],
   ["Cargo", "Wagon cargo liner", "Bare carpet with a dog"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2020–2025 Outback",
  "head": ["Type", "Example", "Coverage", "Walls", "Price band", "Best for"],
  "rows": [
   ["USA-made molded liner", "Husky 95541", "Front + 2nd", "High", "$130–$180", "Snow and trailheads"],
   ["OEM heavy-gauge mat", "Subaru J501SAN100", "Set of 4", "Low-medium", "$90–$130", "Factory fit"],
   ["TPE liner", "OEDRO, YITAMOTOR, Auxko", "Front + 2nd", "Medium", "$80–$130", "Value"],
   ["3D TPE", "Generic 3D", "Front + 2nd", "Medium-high", "$90–$130", "All models"],
  ],
 },
 "picks": [
  {"asin": "B08697PNQH", "role": "Best overall", "price": "$130–$180",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs", "Lists 2020–2025 Outback and Legacy", "Three pieces with one-piece rear"],
   "cons": ["Firm feel", "Cargo liner sold separately", "Costs more than Subaru's mats"],
   "body": "Husky's WeatherBeater 95541 is the three-piece front and second-row set for the 2020–2025 Outback and Legacy. Husky says WeatherBeater is laser-measured using vehicle-specific data, designed and made in the USA from ProGard and anchored by StayPut nibs, with a lifetime warranty against cracks and breaks.\n\nFor an Outback that lives in snow country or at trailheads, the tall, firm walls hold snowmelt and mud that would otherwise soak the carpet. The lifetime crack warranty matters most in the cold, where rigid liners are most likely to fail. The firm material takes a warm day to relax after shipping.\n\nHusky also sells the front (15951) and second-row (16891) pieces separately for 2020–2025, useful if you need to replace one. Add a cargo liner for the wagon if you haul.",
   "who": "Owners in snow country or who drive to trailheads.",
   "specs": [["Part #", "Husky 95541"], ["Pieces", "3"], ["Fits", "2020–2025 Outback and Legacy"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B07WRSDBSS", "role": "Best factory option", "price": "$90–$130",
   "pros": ["Genuine Subaru part J501SAN100", "Heavy-gauge all-weather mats", "Set of 4", "Lists 2020–2025 Outback and Legacy", "Dealer-supported"],
   "cons": ["Flatter than deep-walled liners", "Holds less standing water", "Cargo sold separately"],
   "body": "Subaru's heavy-gauge all-weather floor mats, J501SAN100, are sold as a set of four for the 2020–2025 Outback and Legacy. They're designed with the car, so fit at the retention hooks is dependable, and they cost less than Husky.\n\nThe design is a thick, heavy mat rather than a deep tray. That makes them durable and easy to lift out, but they hold less standing water than a WeatherBeater, so empty them often in snow.\n\nA Subaru dealer can confirm the part for your VIN and sells a matching cargo tray. For owners who want a factory-look interior at a fair price, they're the default.",
   "who": "Owners who want factory-fit mats at a fair price.",
   "specs": [["Part #", "Subaru J501SAN100"], ["Pieces", "4"], ["Fits", "2020–2025 Outback and Legacy"], ["Type", "Heavy-gauge all-weather mat"], ["Price band", "$90–$130"]]},
  {"asin": "B093L62R7H", "role": "Best TPE value", "price": "$90–$130",
   "pros": ["TPE liner with raised edges", "1st and 2nd row", "Lists Outback and Legacy", "Cheaper than Husky", "Flexible for cleaning"],
   "cons": ["No published warranty", "Walls lower than Husky's", "Cargo not included"],
   "body": "OEDRO's TPE liners cover the first and second rows of the 2020–2025 Outback and Legacy. It's a proper liner with raised edges at a mid-budget price.\n\nTPE is light, flexible for cleaning and stays soft in cold weather better than rigid plastic. OEDRO doesn't publish warranty terms we could check, so aging is harder to predict than with Husky.\n\nFor an Outback that sees normal commuting and occasional snow, it's a good balance of containment and price. Check listing photos for driver-side hook holes. OEDRO's cut includes the Legacy, so a household with both cars can standardize on one set design. Look at the listing photos for a one-piece rear liner across the hump; on the Outback's rear floor, a single piece is easier to pull and doesn't leave a strip of carpet in the middle.",
   "who": "Commuters who want a raised-edge liner for less.",
   "specs": [["Rows", "1st + 2nd"], ["Fits", "2020–2025 Outback / Legacy"], ["Material", "TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$90–$130"]]},
  {"asin": "B09R1BJW74", "role": "Best 3D budget", "price": "$90–$130",
   "pros": ["3D molded shape", "Lists all Outback and Legacy models", "Front and 2nd row", "Raised edges", "Budget price"],
   "cons": ["Generic brand", "No published warranty", "Cargo not included"],
   "body": "These 3D custom-fit liners are listed for 2020–2025 Outback and Legacy, all models, front and second row. The 3D molding follows the footwell shape, and the raised edges keep water in the tray.\n\nIt's a generic brand with little documentation. The 'all models' note is reassuring for Wilderness and XT owners.\n\nFor the price, it's a practical everyday liner. Compare the live price with OEDRO before ordering. The 3D molding is the practical difference from flat budget mats: each liner is shaped to the footwell contours, so water stays in the tray instead of running to the edges. That matters in an Outback that sees slushy trailhead parking lots.",
   "who": "Budget buyers with any trim.",
   "specs": [["Rows", "Front + 2nd"], ["Fits", "2020–2025 Outback / Legacy, all models"], ["Material", "3D TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$90–$130"]]},
  {"asin": "B0948LXFWJ", "role": "Best budget", "price": "$80–$120",
   "pros": ["Low price", "1st and 2nd row", "Lists Outback and Legacy", "TPE with raised edges", "Easy to replace"],
   "cons": ["No published warranty", "Little maker documentation", "Walls lower than premium liners"],
   "body": "YITAMOTOR's TPE liners cover the first and second rows of the 2020–2025 Outback and Legacy. It's one of the cheapest raised-edge options here.\n\nAt this price, you're buying the cut and the edges. YITAMOTOR doesn't publish warranty terms we could check.\n\nFor a commuter Outback in a mild climate, it keeps the carpet clean. In snow country, Husky's walls are worth the difference. A tip for dog owners: the rear floor liner catches water off a wet dog's paws if the dog rides on the back seat, so don't skip the second-row piece even if you rarely carry people.",
   "who": "Commuters on a tight budget.",
   "specs": [["Rows", "1st + 2nd"], ["Fits", "2020–2025 Outback / Legacy"], ["Material", "TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$80–$120"]]},
  {"asin": "B0DRYQ1QMC", "role": "Budget alternative", "price": "$80–$120",
   "pros": ["All-weather TPE", "Lists Outback and Legacy", "Front and rear", "Low price", "Raised edges"],
   "cons": ["No published warranty", "Little maker documentation", "Cargo not included"],
   "body": "Auxko's all-weather TPE mats are listed for 2020–2025 Outback and Legacy. It's a close alternative to YITAMOTOR at a similar price.\n\nCompare the listing photos of both: look for driver-side hook holes and a one-piece rear across the hump. Whichever shows a cleaner cut for your car is the better buy.\n\nLike other budget sets, it's a price-driven choice with little documentation. If you're choosing among the budget sets, the retention hook holes on the driver side are the one detail that matters most for safety. Pick the set whose photos show them clearly.",
   "who": "Budget buyers comparing TPE sets.",
   "specs": [["Rows", "Front + rear"], ["Fits", "2020–2025 Outback / Legacy"], ["Material", "TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$80–$120"]]},
  {"asin": "B0FHMJYDYX", "role": "Best front-only", "price": "$70–$110", "pros": ["Husky WeatherBeater front piece", "Lists 2020–2025 Outback and Legacy", "Made in the USA", "Lifetime warranty against cracks and breaks", "Covers the footwells that get dirtiest"], "cons": ["Front row only", "Firm feel", "Rear sold separately (16891)"], "body": "Husky's WeatherBeater 15951 is the front-row piece for the 2020–2025 Outback and Legacy, sold on its own. It's the answer for solo commuters whose back seat rarely sees passengers, or for owners replacing a worn front liner from the 95541 set.\n\nThe front footwells take nearly all the snowmelt and mud in daily driving, so a front-only purchase protects most of the carpet for the least money. It carries WeatherBeater's credentials: laser-measured, made in the USA from ProGard, StayPut nibs and a lifetime warranty against cracks and breaks.\n\nAdd Husky's 16891 second-row piece later if you start carrying passengers or a dog on the rear seat. Buying the two separately costs a little more than the 95541 set, but spreads the cost.", "who": "Solo commuters and owners replacing one worn piece.", "specs": [["Part #", "Husky 15951"], ["Row", "Front"], ["Fits", "2020–2025 Outback and Legacy"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"], ["Rear", "Husky 16891"]]}
 ],
 "install": [
  "Confirm your Outback is a 2020–2025 model (or Legacy of the same years).",
  "Remove the factory mats and vacuum, including the cargo area if you bought a cargo liner.",
  "Hook the driver liner onto Subaru's retention hooks and heel-test it toward the pedals.",
  "Fit the passenger and rear liners; fold the rear seats to check clearance.",
  "Lay the cargo liner and close the liftgate.",
  "Press the pedals to the floor before driving.",
 ],
 "avoid": [
  {"h": "2015–2019 or 2026+ liners", "body": "Different floors."},
  {"h": "Legacy cargo liners", "body": "The sedan's trunk is a different shape."},
  {"h": "Flat mats in snow country", "body": "Snowmelt needs walls."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy Husky's WeatherBeater 95541 for a snow-country Outback, Subaru's J501SAN100 for a factory fit at a fair price, and OEDRO or the generic 3D set for a TPE liner on a budget.",
  "body": "The 6th-gen Outback is simple to fit: one floor across every trim, shared with the Legacy. Husky has the strongest warranty and walls, Subaru's heavy-gauge mats are the value OEM pick, and OEDRO, the generic 3D set, YITAMOTOR and Auxko cover the budget range.\n\nAfter the floors, most Outback owners add crossbars for the integrated roof rails or a cargo box, and a trailer hitch for a bike rack."},
 "sources": [
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners 95541 Outback/Legacy listing", "https://www.amazon.com/dp/B08697PNQH"],
  ["Husky Liners 99671 (2015–2019) listing", "https://www.amazon.com/dp/B00P8DF6G2"],
  ["Subaru J501SAN100 heavy-gauge mats listing", "https://www.amazon.com/dp/B07WRSDBSS"],
  ["OEDRO Outback/Legacy liners listing", "https://www.amazon.com/dp/B093L62R7H"],
  ["Subaru Outback, sixth generation (Wikipedia)", "https://en.wikipedia.org/wiki/Subaru_Outback"],
 ],
}

FITS = [
 ("B08697PNQH","Husky Liners WeatherBeater 95541, 2020-2025 Subaru Legacy & Outback, front & 2nd row","Husky Liners","$130–$180",{},"Made in USA."),
 ("B07WRSDBSS","Subaru Genuine Heavy-Gauge All-Weather Floor Mats J501SAN100 (set of 4), 2020-2025 Outback & Legacy","Subaru","$90–$130",{},"OEM."),
 ("B093L62R7H","OEDRO TPE Floor Liners 1st & 2nd row, 2020-2025 Outback / Legacy","OEDRO","$90–$130",{},"Also fits Legacy."),
 ("B09R1BJW74","3D Custom-Fit Liners front & 2nd row, 2020-2025 Outback / Legacy (all models)","Generic","$90–$130",{},"All models."),
 ("B0948LXFWJ","YITAMOTOR TPE Floor Liners 1st & 2nd row, 2020-2025 Outback / Legacy","YITAMOTOR","$80–$120",{},"Also fits Legacy."),
 ("B0DRYQ1QMC","Auxko All-Weather TPE Floor Mats, 2020-2025 Outback / Legacy","Auxko","$80–$120",{},"Also fits Legacy."),
 ("B0FHMJYDYX","Husky Liners WeatherBeater 15951 Front Row, 2020-2025 Subaru Legacy & Outback","Husky Liners","$70–$110",{},"Front row only."),
 ("B0FHMHRRCB","Husky Liners WeatherBeater 16891 2nd Row, 2020-2025 Subaru Legacy & Outback","Husky Liners","$60–$100",{},"2nd row only."),
]
