"""Long-form article — Best Rooftop Cargo Boxes for 2020–2025 Subaru Outback (6th gen, BT).
Mirrors the approved F-150 tonneau pilot. No invented hands-on testing: box specs come from Yakima's own
product pages plus Thule, SportRack and etrailer; vehicle facts from db/migrations/003_vehicles.sql plus the references in SOURCES
(checked 2026-09-24). Boxes are universal; the Outback-specific part is swing-out bars vs Wilderness rails,
roof load, crossbar spread and hatch clearance.
"""

KEY = ("subaru", "outback", "2020-present", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2020–2025 Subaru Outback: 7 Picks for Swing-Out Bars and Wilderness"
META = ("Seven Yakima, Thule and SportRack cargo boxes for the 6th-gen Outback: swing-out crossbar spread, Wilderness "
        "rail notes, roof load math and rear gate clearance.")

FAQ = [
 ("Can I mount a cargo box on the Outback's factory swing-out crossbars?",
  "Usually, yes. Most 2020–2025 Outbacks have raised rails with crossbars that stow inside the rails and swing out when you need them. A box clamps to them like any other bar, as long as the distance between the deployed bars falls inside the box's spread range, such as 24–34.5 in for the Yakima SkyBox 16. Deploy the bars, measure center to center, and compare before you buy."),
 ("How much weight can a 2020–2025 Outback roof carry with a box?",
  "Check the owner's manual for your model year, because published figures differ. Our fitment data lists 176 lb for the standard Outback, and one reference quotes 150 lb for 2020–2022 models. Plan around the lower number until you've read your manual. Then subtract the bars and the box: a 47 lb SkyBox 16 on 150 lb leaves about 100 lb for gear."),
 ("Is the Outback Wilderness roof different for a cargo box?",
  "Yes. The Wilderness uses its own heavier-duty roof rails, rated for up to 700 lb static, which is the parked load that matters for rooftop tents. Driving loads are much lower, and the box and its contents count against the driving figure in your manual, not the 700 lb number. Wilderness owners also typically fit aftermarket bars (The Rack Shop lists 50 in bars) rather than using the standard trims' swing-out bars."),
 ("Will a roof box hit the Outback's rear gate?",
  "The Outback is a long wagon, so it has more room at the back of the roof than a compact SUV, but a long box can still reach the rear gate's path. Mount the box forward, then open the gate slowly the first time. If your Outback has a power rear gate with an adjustable opening height, you can lower that setting as a backup."),
 ("What size roof box is best for an Outback?",
  "A 16 cu ft box such as the Yakima SkyBox 16 or GrandTour 16 suits most families, and it leaves room under a roof limit of roughly 150–176 lb. Skiers should look at length rather than volume: the SkyBox NX Skinny takes skis up to 195 cm while leaving bar space, and the 18 cu ft Thule Motion 3 XL takes 200 cm skis. On a budget, the SportRack Vista XL fits 18 cu ft into 63 in for $449.95. If you want the lightest box, the 30.2 lb DeepSpace 10 has a 100 lb cargo limit."),
 ("Do I need aftermarket crossbars for a roof box on an Outback?",
  "Not always. The swing-out bars work for occasional trips if their spread fits the box; the Thule Motion 3 boxes have the widest range here (21-13/16 to 36-9/16 in, per etrailer). Aftermarket bars make sense when you want a spread the factory bars can't reach (the DeepSpace 10 needs 32–46 in), a quieter aero bar, or a Wilderness setup. Buy bars listed for your Outback's rail type. Integrated-rail and Wilderness kits are different, and our Outback roof rack page lists both."),
 ("Can I carry skis and a cargo box on an Outback at the same time?",
  "Yes, with a narrow box. A full-width 16 cu ft box takes most of the crossbar length. The SkyBox NX Skinny is 26.5 in wide, and Yakima says it leaves crossbar space for other gear, so a ski or bike mount can go next to it. Add up the weight of the box, the second mount and the gear, and keep the total under the roof limit."),
 ("Do 2020–2025 Outback roof box setups carry over to the 2026 Outback?",
  "The box does; boxes clamp to crossbars, not to the car. The 2026 Outback is a new seventh generation, so the crossbars may not. Buy bars listed for the 2026 model and use its manual's roof figures. Reports on the 2026 Outback quote a 220 lb dynamic rating, which differs from the 6th-gen figures above."),
 ("Will a roof box block the Outback's sunroof?",
  "It shouldn't if you place the front crossbar thoughtfully. Keep the front bar and the front of the box clear of the glass panel's tilt and slide path, and open the sunroof once after mounting to confirm. The box's spread range usually leaves room to shift the bars a few inches."),
 ("Does a roof box hurt the Outback's fuel economy?",
  "Yes, any roof box adds drag, and the effect grows with speed. Yakima's boxes here have tapered noses, and a box mounted level and centered is quieter and more efficient than one that sits nose-up. The most effective step is taking the box off between trips; the SkyBox and GrandTour use quick-release mounts and Yakima quotes about 10 minutes to install."),
]

ARTICLE = {
 "dek": "Seven rooftop boxes from Yakima, Thule and SportRack matched to the 6th-generation Outback's long roof, from the 30 lb DeepSpace 10 to the 18 cu ft Thule Motion 3 XL. For each one we list volume, length, weight and crossbar spread, and what those numbers mean for the swing-out factory bars, the Wilderness rails and the roof load limit.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not mount these boxes ourselves. We ranked them on the makers' published specs (Yakima, Thule and SportRack: volume, exterior dimensions, box weight, crossbar spread, ski length, warranty), on etrailer's spread figures for the Thule and SportRack boxes, on how those specs fit the Outback's swing-out bars, Wilderness rails and rear gate, and on the roof load figures in our fitment data and the references below. Prices were checked on the makers' stores in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Know your rails.** Most 2020–2025 Outbacks have raised rails with swing-out crossbars; the Wilderness has its own heavier-duty rails and usually takes aftermarket bars.",
  "**Measure the swing-out bar spread.** A box needs the bars inside its range: 24–34.5 in for the SkyBox 16, 24–36 in for the GrandTour 16, 21-13/16 to 36-9/16 in for the Thule Motion 3 XL, 32–46 in for the DeepSpace 10.",
  "**Driving load is the number that counts.** Published figures for the standard Outback range from 150 to 176 lb. The Wilderness's 700 lb figure is static (parked), not for a box on the move.",
  "**The long roof helps.** The Outback has more roof behind the rear bar than a compact SUV, but test the rear gate with any box over 80 in.",
  "**Skiers: think length and width.** The Thule Motion 3 XL takes 200 cm skis; the SkyBox NX Skinny takes 195 cm and leaves bar space for a second carrier.",
 ],
 "top_picks": [
  {"asin": "B001PUZXGK", "role": "Best overall", "why": "16 cu ft, 15 in tall, 47 lb, 24–34.5 in spread; $599 on sale"},
  {"asin": "B0DYWCZSD8", "role": "Best for skiers", "why": "195 cm skis, 26.5 in wide, leaves room on the bars for a ski or bike mount"},
  {"asin": "B083KP48XC", "role": "Best premium", "why": "Tallest 16 cu ft box here, 24–36 in spread, dual-side opening"},
  {"asin": "B0HGC24R2P", "role": "Best 18 cu ft", "why": "Thule Motion 3 XL: 200 cm skis, widest spread range here (21-13/16 to 36-9/16 in)"},
  {"asin": "B00BCLL8C0", "role": "Best budget", "why": "SportRack Vista XL: 18 cu ft in a 63 in shell for $449.95; check its fixed mounting positions"},
 ],
 "fit_table": {
  "caption": "2020–2025 Outback roof setups (what the box mounts to)",
  "head": ["Trim", "Roof hardware", "Driving roof load", "Box notes"],
  "rows": [
   ["Non-Wilderness trims", "Raised rails with integrated swing-out crossbars (most trims)", "176 lb in our data; 150 lb quoted for 2020–2022 (check manual)", "Boxes clamp to the deployed bars if the spread fits"],
   ["Wilderness", "Heavier-duty rails, rated 700 lb static", "Lower than 700 lb; use the manual's driving figure", "Aftermarket bars (about 50 in) are the usual base"],
   ["Any trim with aftermarket bars", "Bars clamped to the raised rails", "Lowest of the bar rating and the roof rating", "Lets you set a wider spread, e.g. 32 in+ for the DeepSpace 10"],
  ],
 },
 "look_for": [
  {"h": "Swing-out bar spread vs the box's range",
   "body": "The Outback's party trick is crossbars that stow inside the rails and swing out when you need them. Before you buy a box, check whether your deployed bars can slide along the rails or sit at one position, then measure center to center and compare with the box. Yakima lists 24–34.5 in for the SkyBox 16 and 24–36 in for the GrandTour 16, so check that the factory spread falls inside those. The DeepSpace 10 needs 32–46 in, and the SportRack Vista XL mounts at fixed 25-7/8, 27-7/8 or 29-7/8 in positions per etrailer. The Thule Motion 3 XL's 21-13/16 to 36-9/16 in range is the most forgiving. If the factory bars can't hit a box's range, aftermarket bars on the rails can."},
  {"h": "Driving load, not the Wilderness's 700 lb",
   "body": "The 700 lb Wilderness figure is a static rating: the weight the roof holds while parked, which is why it gets quoted for rooftop tents. A box counts against the driving load, which is much lower. For the standard 6th-gen Outback, our fitment data lists 176 lb and one reference quotes 150 lb for 2020–2022, so read the manual for your year. The boxes here weigh 30.2 to 51.5 lb (SportRack doesn't publish the Vista XL's weight). Add your bars, and a standard Outback usually has about 100 lb left for gear."},
  {"h": "Rear gate clearance on the long roof",
   "body": "The Outback is a wagon, so there is more roof behind the rear crossbar than on a compact crossover. That means long boxes are more workable here, but not automatic. The rear gate swings up toward the back of the roof, and the 92 in RocketBox 16, the 84.7 in Thule Motion 3 XL and the 84 in SkyBox NX Skinny are the boxes to test; the 63 in SportRack Vista XL is the easiest. Mount the box forward on the bars, open the gate slowly the first time, and check the gap. If your Outback has a power rear gate with an adjustable height, a lower setting adds margin."},
  {"h": "Width for skis, bikes and boats",
   "body": "Outbacks tend to carry more than one kind of gear. A full-width 16 cu ft box is 35–36 in wide and fills most of the crossbar length. The SkyBox NX Skinny, at 26.5 in wide, is the one Yakima says leaves bar space for other gear, so a ski rack, bike mount or kayak carrier can go beside it. Its 195 cm ski length is also the longest here. Just remember that everything on the bars shares the same driving roof limit."},
  {"h": "Height and garage clearance",
   "body": "A box adds its height on top of the rails and bars, and the Wilderness sits higher still. The boxes here are 15 in tall (SkyBox 16, RocketBox 16), 16 in (SkyBox NX Skinny, DeepSpace 10), 17 in (Thule Motion 3 XL), 18 in (GrandTour 16) and 19 in (SportRack Vista XL). If you park in a garage or use a parking structure, measure the car with bars fitted and add the box height before you choose. A 3 in difference between the SkyBox and GrandTour can decide whether it fits."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbar spread", "A range that includes your deployed swing-out bar spread", "Boxes with no published spread, unless you confirm with the maker"],
   ["Box weight", "Under 50 lb to save the 150–176 lb driving limit for gear", "Heavy boxes on the factory bars with a full load"],
   ["Length", "Under 85 in for easy rear gate clearance; test anything longer", "Assuming a wagon clears any box"],
   ["Width", "26–27 in if you want a second carrier on the bars", "A full-width box plus bikes that overloads the roof"],
   ["Opening", "Dual-side, so you load from the curb", "Single-side boxes"],
   ["Warranty", "Limited lifetime (Yakima boxes and, per etrailer, the Thule Motion 3)", "No warranty stated; ask the seller"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Outback (makers' published specs; Thule and SportRack spread per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Rear gate guidance"],
  "rows": [
   ["SkyBox 16 Carbonite", "16 cu ft", "81 × 36 × 15 in", "47 lb", "24–34.5 in", "Mount forward; usually room to spare"],
   ["SkyBox NX Skinny", "12 cu ft", "84 × 26.5 × 16 in", "43 lb", "Not published; confirm", "Mount forward, test the gate"],
   ["GrandTour 16", "16 cu ft", "79 × 35 × 18 in", "51.5 lb", "24–36 in", "Shortest 16 here; check garage height"],
   ["RocketBox 16", "16 cu ft", "92 × 26 × 15 in", "42 lb", "Not published; confirm", "Longest; measure before buying"],
   ["DeepSpace 10", "10 cu ft", "60 × 23 × 16 in", "30.2 lb", "32–46 in", "No gate issues; needs wide bar spread"],
   ["Thule Motion 3 XL", "18 cu ft", "84.7 × 35 × 17 in", "51 lb", "21-13/16 to 36-9/16 in", "Mount forward, test the gate"],
   ["SportRack Vista XL", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed at 25-7/8, 27-7/8 or 29-7/8 in", "No gate issues; rear-opening lid"],
  ],
 },
 "picks": [
  {"asin": "B001PUZXGK", "role": "Best overall", "price": "$599",
   "pros": ["16 cu ft in a 15 in tall shell, the lowest 16 here", "47 lb, lighter than the GrandTour", "Dual-side opening with SuperLatch security", "24–34.5 in spread and quick-release mounts that fit most crossbars", "$599 on sale at Yakima (regular $749)"],
   "cons": ["36 in wide, so little bar space is left", "81 in long; mount it forward", "Spread range tops out at 34.5 in"],
   "body": "For most Outback owners, the SkyBox 16 Carbonite is the box to start with. Yakima lists it at 81 x 36 x 15 in and 47 lb, with 16 cu ft, dual-side opening, SKS locks and SuperLatch security, and quick-release hardware that fits most crossbars, including factory bars. Yakima says it installs in about 10 minutes with no assembly, and it takes skis and boards up to 185 cm. It was $599 on sale (regular $749) on Yakima's store when we checked, with a limited lifetime warranty.\n\nThe 15 in height matters on an Outback because it keeps the overall height down for garages, and the Wilderness sits taller to begin with. The 47 lb weight leaves roughly 100 lb for gear under a 150–176 lb driving limit once bars are counted. The fit check is the spread. Deploy the swing-out bars, measure between them, and confirm it falls within 24–34.5 in. The 81 in length works on the long roof, but slide the box forward and open the rear gate slowly the first time.",
   "who": "Outback families who want a low, full-size box that works on the factory swing-out bars.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "81 × 36 × 15 in"], ["Box weight", "47 lb"], ["Crossbar spread", "24–34.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Install", "About 10 min, no assembly"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0DYWCZSD8", "role": "Best for skiers", "price": "$799",
   "pros": ["Skis and boards up to 195 cm, the longest here", "26.5 in wide, leaving bar space for a ski or bike mount", "Dual-side opening", "Full metal handle locks the lid and the mounts", "Limited lifetime warranty"],
   "cons": ["12 cu ft for $799", "Crossbar spread not published on Yakima's page", "84 in long; test the rear gate"],
   "body": "Outbacks spend a lot of winters at ski areas, and the SkyBox NX Skinny is shaped for that. Yakima lists it at 84 x 26.5 x 16 in and 12 cu ft, with room for skis and boards up to 195 cm, 10 cm more than the 16 cu ft boxes here. Being narrow is the other half of the case: Yakima says it leaves crossbar space for other gear, so on an Outback a second ski carrier, a bike mount or a kayak saddle can ride beside it. It opens from both sides, and the full metal handle locks both the lid and the box to the bars. Yakima lists it at $799 with SKS locks and a limited lifetime warranty.\n\nThe downsides are price per cubic foot and a missing spec. At $799 for 12 cu ft it costs more than the SkyBox 16, and Yakima's page doesn't publish a crossbar spread for it, so confirm that it suits your deployed swing-out bars before ordering. At 43 lb plus a second carrier plus gear, the combined load can reach the Outback's driving limit quickly, so weigh the full setup.",
   "who": "Skiers and multi-sport Outback owners who want a locking box with room on the bars for another carrier.",
   "specs": [["Volume", "12 cu ft"], ["Exterior", "84 × 26.5 × 16 in"], ["Box weight", "43 lb"], ["Ski length", "Up to 195 cm"], ["Opening", "Dual-side"], ["Lock", "SKS; locks lid and mounts"], ["Crossbar spread", "Not published; confirm"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B083KP48XC", "role": "Best premium", "price": "$709",
   "pros": ["18 in tall, the deepest 16 cu ft shell here, for bulky items", "79 in long, the shortest 16 cu ft box here", "24–36 in spread, the widest range of the 16s", "Dual-side opening and SKS locks", "Limited lifetime warranty"],
   "cons": ["51.5 lb, the heaviest here", "18 in height can matter in garages, especially on a Wilderness", "About $110 more than the SkyBox 16"],
   "body": "The GrandTour 16 is the box for bulky gear: coolers without ice, camp chairs, a folded stroller. Yakima lists it at 79 x 35 x 18 in, so it is 3 in taller than the SkyBox 16 and 2 in shorter. The extra depth makes it easier to fit tall, awkward items, and the shorter length leaves a little more room over the rear gate. It opens from both sides, takes skis and boards up to 185 cm, and comes with SKS locks and a limited lifetime warranty. Yakima lists it at $709.\n\nIts 24–36 in spread range is the widest of the 16 cu ft boxes here, which gives the best chance of matching the Outback's swing-out bar spread. The costs are weight and height. At 51.5 lb it takes the largest share of the driving roof limit, leaving roughly 100 lb or less for gear on a standard Outback once bars are counted. At 18 in tall, check garage clearance before buying, especially on a Wilderness with its taller ride height.",
   "who": "Outback owners who carry bulky gear and want the widest spread range for the factory bars.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "79 × 35 × 18 in"], ["Box weight", "51.5 lb"], ["Crossbar spread", "24–36 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS locks included"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B001PUZ24I", "role": "Budget long box", "price": "$350",
   "pros": ["16 cu ft for a $350 Yakima list price", "42 lb, lighter than the other 16s", "26 in wide, leaving bar space beside it", "Long shape suits long skis", "Limited lifetime warranty"],
   "cons": ["92 in long, so measure the rear gate first", "Yakima lists it as archived and out of stock", "Spread and opening details not published"],
   "body": "The RocketBox 16 is the cheapest Yakima 16 here: $350 on Yakima's page, with a limited lifetime warranty. It weighs 42 lb, less than the SkyBox 16 or GrandTour 16, and its long, narrow shape (92 x 26 x 15 in) leaves room on the crossbars for a bike or ski mount beside it. That lower weight is useful against a standard Outback's 150–176 lb driving limit.\n\nThe Outback's long wagon roof handles a 92 in box better than a compact SUV, but length is still the thing to check. Measure from the front crossbar to where the open rear gate reaches, and make sure the box's tail stays clear with the box mounted forward. Yakima lists the RocketBox 16 as archived and out of stock, and its page doesn't give a crossbar spread or opening details. Confirm the spread on the listing and compare it with your swing-out bars before ordering.",
   "who": "Budget buyers with long skis or narrow gear who have room behind the rear bar for a 92 in box.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "92 × 26 × 15 in"], ["Box weight", "42 lb"], ["Price", "$350 (Yakima list, archived)"], ["Crossbar spread", "Not published; confirm"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B09HC2LWX8", "role": "Lightest load", "price": "$649",
   "pros": ["30.2 lb, the lightest box here", "Published 100 lb max load", "60 in long, no rear gate concerns", "Integrated tie-down points", "Made in the USA; limited lifetime warranty"],
   "cons": ["Needs a 32–46 in crossbar spread", "10 cu ft; no room for skis", "Priced close to the SkyBox 16"],
   "body": "The DeepSpace 10 does the most with the Outback's driving roof limit. Yakima lists it at 60 x 23 x 16 in and 30.2 lb, and it is the only box on this page with a published cargo rating: 100 lb. On a standard Outback at 150–176 lb, that 30 lb shell leaves room for a real load once bars are counted. It has tie-down points inside, a wide-angle lid, and a limited lifetime warranty, and Yakima lists it at $649, made in the USA.\n\nThe spread is the catch. The DeepSpace needs 32–46 in between the bars, wider than the 16 cu ft boxes need. Measure your deployed swing-out bars; if they sit closer than 32 in, you'll need aftermarket bars on the rails that can be spaced wider. Wilderness owners who have already moved to aftermarket bars may find it easiest to fit. At 60 in long it is nowhere near the rear gate, but at 10 cu ft it isn't a ski box.",
   "who": "Outback owners who want the lightest locking box and have, or will fit, bars that can be spread 32 in or more.",
   "specs": [["Volume", "10 cu ft"], ["Exterior", "60 × 23 × 16 in"], ["Box weight", "30.2 lb"], ["Max load", "100 lb"], ["Crossbar spread", "32–46 in"], ["Material", "Textured ABS"], ["Made in", "USA"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0HGC24R2P", "role": "Best 18 cu ft", "price": "$1,149.95",
   "pros": ["18 cu ft, 2 cu ft more than the 16s", "Skis up to 200 cm, the longest here", "21-13/16 to 36-9/16 in spread (etrailer), the widest range on this page", "One-handed dual-side opening, PowerClick mounts, SlideLock", "Thule rates it for 165 lb of cargo; limited lifetime warranty per etrailer"],
   "cons": ["$1,149.95 at Thule, the priciest box here", "51 lb, so it takes a big share of a 150–176 lb driving limit", "84.7 in long; this listing is a Limited Edition finish, so confirm the color"],
   "body": "The Thule Motion 3 XL is the step up for Outback owners who want more room than a 16 cu ft box and longer skis than the Yakimas take. Thule lists it at 18 cu ft with exterior dimensions of 84.7 x 35 x 17 in, a 51 lb box weight and a 165 lb maximum load. It takes skis up to 200 cm, 5 cm more than the SkyBox NX Skinny, opens from either side with one hand, locks with SlideLock, and clamps on with PowerClick mounts. Thule lists it at $1,149.95. This Amazon listing is a Limited Edition version, so check the finish on the listing.\n\nFor the Outback, the spread range is the big advantage. etrailer lists 21-13/16 to 36-9/16 in for the Motion 3 boxes, the widest range on this page, which gives the best chance of matching the swing-out bars wherever they deploy, and etrailer lists a limited lifetime warranty for the line. The costs are weight and length. At 51 lb it leaves roughly 100 lb or less for gear under a 150–176 lb driving limit once the bars are counted, so pack skis, boots and soft bags, not a cooler. At 84.7 in it is about as long as the SkyBox NX Skinny, so mount it forward and open the rear gate slowly the first time.",
   "who": "Skiers and road-trippers who want 18 cu ft and 200 cm skis and the widest spread range for the swing-out bars.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "84.7 × 35 × 17 in"], ["Box weight", "51 lb"], ["Max load", "165 lb"], ["Crossbar spread", "21-13/16 to 36-9/16 in (etrailer)"], ["Ski length", "Up to 200 cm"], ["Mount / lock", "PowerClick / SlideLock"], ["Warranty", "Limited lifetime (etrailer)"]]},
  {"asin": "B00BCLL8C0", "role": "Best budget", "price": "$449.95",
   "pros": ["18 cu ft for $449.95 at SportRack", "63 in long, nowhere near the rear gate", "Tool-free mounting hardware and a lock", "Fits square, round and most factory bars, per SportRack", "Rear opening lets you load away from traffic"],
   "cons": ["Fixed mounting positions (25-7/8, 27-7/8 or 29-7/8 in per etrailer) must match your bars", "38 in wide and 19 in tall, the widest and tallest box here", "Box weight, load rating and warranty not published; confirm"],
   "body": "The SportRack Vista XL gives an Outback 18 cu ft for $449.95, less than half the price of the Thule Motion 3 XL. SportRack lists it at 63 x 38 x 19 in in UV-resistant ABS, with tool-free mounting hardware and a lock, and says it fits square bars, round bars and most factory racks. Its short, wide shape suits the wagon: at 63 in it sits well forward of the rear gate and still holds more than any 16 cu ft box here. etrailer lists it under the Outback Wagon among its fits.\n\nThe mount is the thing to check on the swing-out bars. etrailer's expert gives three fixed mounting positions, 25-7/8, 27-7/8 and 29-7/8 in center to center, so deploy your factory bars and measure: if they don't land on one of those, you'll need aftermarket bars you can position. The lid opens at the rear, so you load from behind the car, which is handy at a trailhead but means reaching over the roof's tail. At 38 in wide it fills the bars, and at 19 in tall it is the tallest box here, which matters for garages and on a Wilderness. SportRack's page doesn't list box weight, load rating or warranty terms, so confirm them on the listing before loading up.",
   "who": "Budget buyers who want a short, big box and have bars that match its mounting positions.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "63 × 38 × 19 in"], ["Opening", "Rear"], ["Mounting positions", "25-7/8, 27-7/8 or 29-7/8 in (etrailer)"], ["Hardware", "Tool-free; lock included"], ["Material", "UV-resistant ABS"], ["Box weight / max load", "Not published; confirm"], ["Price", "$449.95 (SportRack)"]]},
 ],
 "install": [
  "On standard trims, swing the factory crossbars out and lock them in position; on a Wilderness or with aftermarket bars, fit and torque the bars to the maker's spec.",
  "Measure the spread between the bars center to center and confirm it is inside the box's range (24–34.5 in SkyBox 16, 24–36 in GrandTour 16, 21-13/16 to 36-9/16 in Motion 3 XL, 32–46 in DeepSpace 10) or on one of the Vista XL's fixed positions.",
  "With a helper, set the box on the bars, center it side to side, and slide it forward, keeping the front clear of the sunroof path.",
  "Fit the clamps loosely, open the rear gate slowly and check the gap at the tail of the box, then tighten the clamps to the box maker's instructions.",
  "Lock the box and mounts, rock it from each corner, and re-check the clamps after the first drive.",
  "Load heavy items low and centered between the bars, and keep bars + box + gear under the driving limit in your manual.",
 ],
 "avoid": [
  {"h": "Treating the Wilderness 700 lb figure as a driving limit", "body": "700 lb is the static (parked) rating. A box on the move counts against the much lower driving figure in the manual."},
  {"h": "Buying a box without measuring the swing-out bars", "body": "The factory bars have limited adjustment. If their spread isn't inside the box's range, the box won't mount correctly."},
  {"h": "Crossbar kits for the wrong rail type", "body": "Integrated-rail and Wilderness Outbacks take different aftermarket bars. The box doesn't care, but the bars must match your rails."},
  {"h": "Stacking a box, bikes and skis past the limit", "body": "A narrow box leaves room for other carriers, but everything shares one driving roof limit. Weigh the full setup."},
 ],
 "verdict": {
  "thesis": "Measure your swing-out bars, then choose the Yakima SkyBox 16 for most Outbacks, the Thule Motion 3 XL for 18 cu ft and long skis, or the SportRack Vista XL on a budget.",
  "body": "On the 6th-gen Outback, the box matters less than the bars and the driving load. The SkyBox 16 is low, relatively light and fits the widest range of factory setups, which makes it the default pick. The SkyBox NX Skinny is the ski box that leaves room for a second carrier, the GrandTour 16 is for bulky gear and the widest spread range, and the DeepSpace 10 gives the most cargo headroom if your bars can spread 32 in or more. The Thule Motion 3 XL costs the most but has the widest spread range and takes 200 cm skis, and the SportRack Vista XL is the budget 18 cu ft box if its fixed mounting positions match your bars. The RocketBox 16 is only a bargain once you've measured for its 92 in length.\n\nIf the swing-out bars don't fit your box, see our Outback roof rack page for crossbars matched to integrated rails and to the Wilderness. For heavy items like coolers, a trailer hitch and hitch carrier keep the weight low. The vehicle hub lists every fit-checked accessory for your Outback.",
 },
 "sources": [
  ["Yakima SkyBox 16 Carbonite (Yakima)", "https://yakima.com/collections/roof-boxes/products/skybox-16-carbonite-2014-2023"],
  ["Yakima SkyBox NX Skinny (Yakima)", "https://yakima.com/products/skybox-nx-skinny"],
  ["Yakima GrandTour 16 (Yakima)", "https://yakima.com/products/grandtour-16"],
  ["Yakima RocketBox 16 (Yakima)", "https://yakima.com/products/rocketbox-16"],
  ["Yakima DeepSpace 10 (Yakima)", "https://yakima.com/collections/roof-boxes/products/deepspace-10"],
  ["Subaru Outback — 6th gen retractable roof rack, Wilderness 700 lb rating, 2026 7th gen", "https://en.wikipedia.org/wiki/Subaru_Outback"],
  ["Subaru roof load figures, Wilderness vs standard (AHG Auto Service)", "https://www.ahgautoservice.com/how-much-can-the-subaru-wilderness-roof-hold/"],
  ["Outback Wilderness rack options (The Rack Shop)", "https://therackshop.com/subaru-outback-wilderness-rack-options/"],
  ["Thule Motion 3 XL (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-motion-3-xl-_-639850"],
  ["Thule Motion 3 spread and warranty (etrailer)", "https://www.etrailer.com/Roof-Box/Thule/TH59PN.html"],
  ["SportRack Vista XL (SportRack)", "https://www.sportrack.com/product/vista-xl-cargo-box/"],
  ["SportRack Vista XL mounting positions (etrailer)", "https://www.etrailer.com/question-156482.html"],
  ["2026 Outback roof rack ratings (The Drive)", "https://www.thedrive.com/news/why-the-2026-subaru-outbacks-roof-rack-has-three-different-weight-ratings"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Outback roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B001PUZXGK","Yakima SkyBox 16 Carbonite Rooftop Cargo Box, 16 cu ft (81 in long)","Yakima","$550–$750",{},"24-34.5 in spread; measure deployed swing-out bars."),
 ("B0DYWCZSD8","Yakima SkyBox NX Skinny 12 cu ft Cargo Box (26.5 in wide, 195 cm skis)","Yakima","$700–$850",{},"Leaves bar room for skis/bike; confirm spread on listing."),
 ("B083KP48XC","Yakima GrandTour 16 Premium Rooftop Cargo Box, 16 cu ft, dual-side opening","Yakima","$700–$900",{},"24-36 in spread; 18 in tall, check garage height."),
 ("B001PUZ24I","Yakima RocketBox 16 Cargo Box, 16 cu ft (92 in long)","Yakima","$350–$600",{},"Long box: measure rear gate clearance; confirm spread."),
 ("B09HC2LWX8","Yakima DeepSpace 10 Hard Shell Cargo Box, 10 cu ft (100 lb max)","Yakima","$550–$700",{},"Needs 32-46 in spread; factory bars may be too close, confirm."),
 ("B0HGC24R2P","Thule Motion 3 XL Rooftop Cargo Box, 18 cu ft, Limited Edition","Thule","$1,100–$1,250",{},"21-13/16 to 36-9/16 in spread; 84.7 in long, test rear gate. Confirm finish."),
 ("B00BCLL8C0","SportRack Vista XL Rear Opening Cargo Box, 18 cu ft, Black","SportRack","$400–$500",{},"Fixed mounting positions; confirm they match your bars and the load rating."),
]
