"""Long-form article — Best Rooftop Cargo Boxes for 2019–2024 Subaru Forester (5th gen, SK).
Mirrors the approved RAV4 / Outback cargo-box pages. No invented hands-on testing: box specs come from the Yakima,
Thule, Rhino-Rack and SportRack product pages and etrailer (INNO) listed in sources; vehicle facts come from
db/migrations/003_vehicles.sql and the Forester roof-rack page's references (checked 2026-09-27).
Boxes are universal; the Forester-specific part is raised rails vs Wilderness rails, the 176 lb driving
limit, crossbar spread and liftgate clearance.
Text fixes 2026-10-04: Base trim rails are optional per Subaru's 2019, 2022 and 2024 trim sheets (bare-roof check added); "ladder-type" no longer described as Wilderness-only (Subaru's 2 Sept 2021 release uses it for the refreshed 2022 rails too); 176 lb / 700 lb attributed to Subaru's 2022 and 2024 sheets and 2022 release, with 2019-2021 owners sent to the owner's manual; hitch FAQ reworded (no factory receiver confirmed; Subaru accessory hitch L101SSJ001 / L101SSJ005) and "in our data" removed; 2025 Wilderness note per Wikipedia.
"""

KEY = ("subaru", "forester", "2019-2024", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2019–2024 Subaru Forester: 7 Boxes for Raised Rails and Wilderness"
META = ("Seven Yakima, Thule, INNO, Rhino-Rack and SportRack boxes for the SK Forester: 176 lb roof load math, "
        "Wilderness rails, spread and liftgate clearance.")

FAQ = [
 ("What size cargo box fits a 2019–2024 Subaru Forester?",
  "Most Forester owners are best served by 11 to 16 cu ft. The Forester is a compact SUV, so length matters as much as volume. The Thule Pulse 2 M is 68.9 in long, the SportRack Vista XL 63 in, the Rhino-Rack MasterFit 440 76 in and the Thule Force 3 L 76.8 in. The Yakima GrandTour 16 is 79 in and the CBX 16 is 83 in. Shorter boxes leave more room for the open liftgate, so start from length and then pick the volume you need."),
 ("How much weight can I carry in a roof box on a Forester?",
  "Subaru's 2022 and 2024 trim comparison sheets print a 176 lb maximum capacity for the standard roof rails, and Subaru's release on the refreshed 2022 Forester calls it the dynamic (driving) capacity. That figure covers the crossbars, the box and the cargo together. A 31 lb Thule Pulse 2 M on bars that weigh around 15 lb leaves roughly 130 lb for gear; a 57 lb Yakima CBX 16 leaves about 100 lb. The 2019 sheet prints no capacity, so 2019–2021 owners should take the figure from the owner's manual."),
 ("Is the Forester Wilderness roof better for a cargo box?",
  "It has more margin. Subaru rates the 2022–2024 Wilderness rails at 220 lb dynamic and 800 lb static, against the 176 lb and 700 lb its 2022 release gives the standard rails. The box itself fits either way, because boxes clamp to crossbars. The difference is the bars: standard-rail crossbars are often titled \"not Wilderness,\" so buy bars listed for the Wilderness rail first and then choose the box."),
 ("Will a roof box hit the Forester's liftgate?",
  "A long box can. The liftgate swings up toward the rear of the roof, and a box that hangs past the rear crossbar sits in its path. Slide the box as far forward as the windshield and antenna allow, then open the liftgate slowly the first time and watch the gap. Thule publishes a front-clearance figure for its boxes (more than 44 13/16 in for the Pulse 2 M and more than 50 5/8 in for the Force 3 L) to use with its hatch clearance guidance."),
 ("Do I need crossbars before I buy a cargo box for my Forester?",
  "Yes. A box clamps to crossbars, and clamp-on crossbars need rails. Subaru lists raised side rails as standard on Premium, Sport, Limited and Touring and optional on the Base, so look at a Base roof first: with no rails, you need a door-jamb clamp system from Thule or Yakima instead. Otherwise buy a set titled for the Forester's raised rails, or a Wilderness-specific set on that trim, and check the bars' spread range against the box. Our 2019–2024 Forester roof rack page lists fit-checked bars, including Subaru's own aero set and lockable aftermarket sets."),
 ("How far apart should the crossbars be for a roof box?",
  "Inside the box's published range. Yakima lists 24–36 in for the GrandTour 16 and 24–35.5 in for the CBX 16. etrailer lists 24–39 in for the INNO Wedge 660, and Rhino-Rack gives 620–930 mm (about 24.4–36.6 in) for the MasterFit 440. Because Forester bars clamp to the raised rails, you set the spread yourself; just keep the rear bar ahead of where the rail curves down toward the liftgate."),
 ("Can I open the moonroof with a cargo box on the Forester?",
  "Don't count on it. etrailer attaches a note to the Thule systems it fits to the Forester saying it is not recommended to open, vent or retract the sun, moon or glass roof while the product is installed. A box sits even closer to the glass than bare bars. Keep the front of the box clear of the panel's path and leave the moonroof closed while the box is on."),
 ("Can I fit a cargo box and a bike on a Forester at the same time?",
  "Only with a narrow box and careful weight math. Most full-width boxes here are 32–38 in wide and take most of the crossbar length. Even when a bike mount fits beside the box, the bike, the mount, the box and the bars all count against the 176 lb driving limit. If you carry bikes often, a hitch-mounted bike rack keeps that weight off the roof. We could not confirm that any Forester leaves the factory with a receiver, so look under the rear bumper. Subaru's accessory hitch is 1-1/4 in for 2019–2021 (L101SSJ001) and 2 in for 2022–2024 (L101SSJ005), and Subaru rates the standard Forester at 1,500 lb of towing."),
 ("Will a Forester roof box fit in my garage?",
  "Measure your door opening and add the height of the bars and box. The INNO Wedge 660 is only 11 in tall, the lowest box here, and the Yakima CBX 16 is 15 in. The Thule Force 3 L is 16.8 in, the Rhino-Rack MasterFit 440 17 in, the GrandTour 16 18 in and the SportRack Vista XL 19 in. Put a note on the dash or garage remote the first few weeks, because forgetting the box is the most common way to damage one."),
 ("Does a roof box hurt the Forester's fuel economy?",
  "Yes. fueleconomy.gov says a large, blunt rooftop cargo box can reduce fuel economy by about 2–8% in the city, 6–17% on the highway and 10–25% at 65–75 mph, while rear-mounted cargo boxes cost 1–5% on the highway. A low, tapered box such as the 11 in tall INNO Wedge 660 is the better shape, and taking the box off between trips is the cheapest fix."),
]

ARTICLE = {
 "dek": "Seven rooftop boxes from Yakima, Thule, INNO, Rhino-Rack and SportRack matched to the 5th-generation Forester's raised rails, from the 31 lb Thule Pulse 2 M to the rugged Yakima CBX 16. For each one we list volume, length, height, weight and crossbar spread, and what those numbers mean for the Forester's 176 lb driving limit, the Wilderness rails and the liftgate.",
 "author": "jake-morrison",
 "reviewed": "2026-10-04",
 "method": "We did not mount these boxes ourselves. We ranked them on the makers' published specs (Yakima, Thule, Rhino-Rack and SportRack product pages, and etrailer's listing for the INNO box): volume, exterior dimensions, box weight, load rating, crossbar spread, ski length and warranty. We then matched those numbers to the Forester's raised rails, the 176 lb dynamic roof rating Subaru publishes for the standard 2022–2024 rails (220 lb on the Wilderness), the liftgate and garage clearance. Vehicle facts come from Subaru's 2019, 2022 and 2024 trim comparison sheets, Subaru's release on the refreshed 2022 Forester and the references on our Forester roof rack page. Prices were checked on the makers' and retailers' pages in September 2026; Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Crossbars come first.** The box clamps to crossbars, and those need rails. Subaru lists raised rails as standard on Premium, Sport, Limited and Touring and optional on the Base, so check a Base for a bare roof. The 2022–2024 Wilderness has its own rails, and many standard bars are titled \"not Wilderness.\"",
  "**Do the 176 lb math.** Subaru's 2022 and 2024 sheets rate the standard rails at 176 lb; bars, box and gear all count. A 31 lb Pulse 2 M leaves far more for gear than a 57 lb CBX 16. For 2019–2021, confirm the figure in the owner's manual.",
  "**Shorter is safer at the liftgate.** The boxes here run from 63 in (Vista XL) and 68.9 in (Pulse 2 M) to 83 in (CBX 16). Mount forward and open the liftgate slowly the first time.",
  "**Match the spread.** You set the spread on clamp-on raised-rail bars, but it must sit inside the box's range, such as 24–36 in for the GrandTour 16 or 24–39 in for the INNO Wedge 660.",
  "**Leave the moonroof shut.** etrailer notes it is not recommended to open the sun or moon roof with a Thule rack installed on the Forester, and a box sits closer still.",
 ],
 "top_picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "why": "16 cu ft in 79 in, dual-side opening, 24–36 in spread, limited lifetime warranty"},
  {"asin": "B0G8C5LHQ5", "role": "Lightest box", "why": "Thule Pulse 2 M: 14 cu ft, 31 lb, 68.9 in long, 165 lb max load"},
  {"asin": "B0DYQ4T5ZZ", "role": "Best premium 16 cu ft", "why": "Thule Force 3 L: 76.8 in long, 43 lb, 165 lb load rating"},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "why": "INNO Wedge 660: only 11 in tall, 24–39 in spread, 110 lb capacity"},
  {"asin": "B00BCLL8C0", "role": "Best budget", "why": "SportRack Vista XL: 18 cu ft in 63 in for $449.95; rear-opening lid"},
 ],
 "fit_table": {
  "caption": "2019–2024 Forester roof setups (what you need before any box goes on)",
  "head": ["Roof", "Trims / years", "Driving / parked limit", "Box notes"],
  "rows": [
   ["Raised side rails", "Standard on Premium, Sport, Limited, Touring, 2019–2024; optional on Base (Subaru)", "176 lb / 700 lb (Subaru: 2022 and 2024 sheets, 2022 release); 2019–2021: see owner's manual", "Clamp-on bars titled for Forester raised rails; set spread to the box's range"],
   ["No rails", "Base without the optional rails", "See owner's manual", "Clamp-on bars won't mount; fit a door-jamb clamp system from Thule or Yakima first"],
   ["Wilderness rails", "Wilderness, 2022–2024", "220 lb / 800 lb (Subaru)", "Bars listed for the Wilderness; more load margin for heavier boxes"],
   ["Moonroof cars", "Trims with the sunroof option", "Same as above", "Keep the box clear of the glass path; leave it closed while the box is on"],
   ["6th-gen Forester", "2025+ (new generation; the 2025 Wilderness is the older body per Wikipedia)", "See the owner's manual", "Same boxes, but buy bars listed for your year and trim"],
  ],
 },
 "look_for": [
  {"h": "Box length vs the Forester liftgate",
   "body": "The Forester has a compact SUV roof and a liftgate that swings up toward its back edge, so length is the first number to check. The boxes here run from 63 in (SportRack Vista XL) and 68.9 in (Thule Pulse 2 M) through 76 in (Rhino-Rack MasterFit 440), 76.8 in (Thule Force 3 L) and 79 in (GrandTour 16) to 80 in (INNO Wedge 660) and 83 in (Yakima CBX 16). Mount any of them as far forward as the windshield allows, then open the liftgate slowly and watch the gap. Thule's front-clearance figures (more than 44 13/16 in for the Pulse 2 M) are a useful cross-check against its hatch guidance."},
  {"h": "Roof load after crossbars: 176 lb, or 220 lb on the Wilderness",
   "body": "Subaru's 2022 and 2024 sheets rate the standard rails at 176 lb and the 2022–2024 Wilderness rails at 220 lb while driving. The 2019 sheet prints no figure, so 2019–2021 owners should confirm it in the owner's manual. Those figures cover everything above the rails. The boxes here weigh 31 lb (Pulse 2 M) to 57 lb (CBX 16); SportRack doesn't publish the Vista XL's weight. Add your crossbars' listed weight and a standard Forester usually has about 100–130 lb left for gear. That suits sleeping bags, duffels and skis. A box's own rating, such as 165 lb for the Thule boxes, doesn't raise the car's limit, so load to the lower figure."},
  {"h": "Crossbar spread on clamp-on raised-rail bars",
   "body": "Forester crossbars clamp to the raised rails and slide along them, so you choose the spread. It still has to fall inside the box's range: 24–36 in for the GrandTour 16, 24–35.5 in for the CBX 16, 24–39 in for the INNO Wedge 660 (per etrailer) and about 24.4–36.6 in for the MasterFit 440 (Rhino-Rack's 620–930 mm). The SportRack Vista XL mounts at fixed positions of 25-7/8, 27-7/8 or 29-7/8 in, per etrailer. Keep the rear bar ahead of the point where the rail curves down, and mark the rail with tape once you find the right spacing."},
  {"h": "Height, garages and the moonroof",
   "body": "Box height ranges from 11 in (INNO Wedge 660) to 19 in (SportRack Vista XL), on top of the bars. If you park in a garage or use a parking structure, measure the opening and add the box and bar height before choosing. The moonroof is the other constraint. etrailer notes that it is not recommended to open, vent or retract the sun or moon roof while a Thule system is installed on the Forester, and a loaded box sits closer to the glass than bare bars. Keep the front of the box clear of the panel's path and leave it closed while driving."},
  {"h": "Opening side, locks and warranty",
   "body": "Dual-side opening lets you load from the curb on either side, and most boxes here have it: the Yakima, Thule, Rhino-Rack and INNO boxes all open from both sides. The SportRack Vista XL opens at the rear, which on a Forester means reaching over the back of the roof, so shorter owners will want a step. Every box here locks. Warranty terms differ: Yakima lists a limited lifetime warranty, etrailer lists one for the INNO, and Rhino-Rack lists 5 years for the MasterFit. Thule's pages send you to its warranty page, so confirm the terms there."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Length", "Under about 80 in for liftgate room (Pulse 2 M 68.9 in, Force 3 L 76.8 in)", "Long ski boxes without testing the liftgate"],
   ["Box weight", "Under 45 lb to save the 176 lb limit for gear", "Heavy boxes on a standard-rail car if you pack dense gear"],
   ["Crossbar spread", "A published min/max range your bars can meet", "Listings with no spread figure (confirm first)"],
   ["Height", "Low profile if you garage the car (INNO Wedge 660: 11 in)", "19 in tall boxes in a low garage"],
   ["Opening", "Dual-side, so you load from the curb", "Single-side boxes that open toward traffic"],
   ["Warranty", "Published terms (Yakima lifetime, Rhino-Rack 5 years)", "No terms stated; ask the seller"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Forester (makers' published specs; INNO and SportRack mounting per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Liftgate guidance"],
  "rows": [
   ["SportRack Vista XL", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed at 25-7/8, 27-7/8 or 29-7/8 in", "Shortest here; rear-opening lid"],
   ["Thule Pulse 2 M", "14 cu ft", "68.9 × 32.1 × 16.6 in", "31 lb", "Not published; confirm", "Front clearance >44 13/16 in"],
   ["Rhino-Rack MasterFit 440", "15.5 cu ft", "76 × 32 × 17 in", "38.6 lb", "620–930 mm (about 24.4–36.6 in)", "Mount forward, test the liftgate"],
   ["Thule Force 3 L", "16 cu ft", "76.8 × 33.3 × 16.8 in", "43 lb", "Not published; confirm", "Front clearance >50 5/8 in"],
   ["Yakima GrandTour 16", "16 cu ft", "79 × 35 × 18 in", "51.5 lb", "24–36 in", "Mount forward, test the liftgate"],
   ["INNO Wedge 660", "11 cu ft", "80 × 33 × 11 in", "42 lb", "24–39 in", "Long but very low"],
   ["Yakima CBX 16", "16 cu ft", "83 × 38 × 15 in", "57 lb", "24–35.5 in", "Longest here; test the liftgate"],
  ],
 },
 "picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "price": "$709",
   "pros": ["16 cu ft in 79 in, shorter than the CBX 16 and INNO Wedge 660", "Dual-side opening", "24–36 in crossbar spread, easy to meet on clamp-on rail bars", "Takes skis and boards up to 185 cm", "Limited lifetime warranty"],
   "cons": ["51.5 lb, second-heaviest box here", "18 in tall, so check the garage", "Pricier than the Rhino-Rack and SportRack boxes"],
   "body": "The GrandTour 16 is the box that fits the most Forester owners' needs without asking for compromises. Yakima lists it at 79 x 35 x 18 in and 16 cu ft, with dual-side opening, room for skis and boards up to 185 cm, and a limited lifetime warranty, for $709. Its 24–36 in crossbar spread is wide enough that clamp-on raised-rail bars can almost always be set inside it, and because Forester bars slide along the rails, you can choose a spread near the front of the range to keep the box forward of the liftgate. At 79 in it is 4 in shorter than the CBX 16 and 1 in shorter than the INNO Wedge 660.\n\nThe trade-off is weight and height. At 51.5 lb it takes a real share of the standard Forester's 176 lb driving limit. Add bars of around 15 lb and you have a little over 100 lb for gear, which is plenty for bags, jackets and skis but not for a loaded cooler. Wilderness owners, with 220 lb to work with, have more margin. It is also 18 in tall, so measure a low garage before you buy. Mount it forward, then open the liftgate slowly the first time to confirm the tail clears.",
   "who": "Forester owners who want a full 16 cu ft box with a wide spread range and a lifetime warranty.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "79 × 35 × 18 in"], ["Box weight", "51.5 lb"], ["Crossbar spread", "24–36 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Warranty", "Limited lifetime"], ["Price", "$709 (Yakima)"]]},
  {"asin": "B0G8C5LHQ5", "role": "Lightest box", "price": "$699.95",
   "pros": ["31 lb, the lightest box here", "68.9 in long, easy to keep clear of the liftgate", "165 lb (75 kg) maximum load", "DualSide opening and PowerClick tool-free mounts with a torque indicator", "Thule publishes a front-clearance figure (>44 13/16 in)"],
   "cons": ["14 cu ft, less than the 16 cu ft boxes", "Skis only up to 155 cm", "Crossbar spread not published; confirm with Thule's fit guide"],
   "body": "On a standard Forester, weight is the limit you hit first, and the Thule Pulse 2 M is the answer to that. Thule lists it at 68.9 x 32.1 x 16.6 in with 14 cu ft (400 L) inside, a 31 lb box weight and a 165 lb (75 kg) maximum load. It opens from both sides, locks centrally and clamps on with PowerClick mounts that have a torque indicator, so you know when the clamps are tight. Thule lists it at $699.95, and REI sells it at the same price. Its short length also helps at the back of the roof: Thule gives a front-clearance figure of more than 44 13/16 in to check against its hatch clearance guidance.\n\nAgainst a 176 lb driving limit, 31 lb of box and roughly 15 lb of bars leave about 130 lb for gear, more than any other box here. The trade-offs are capacity and ski length. At 14 cu ft it holds less than the 16s, and at 155 cm it won't take most adult skis. It's a box for camping gear, strollers and luggage. Thule's product page doesn't list a crossbar spread, so confirm it against your raised-rail or Wilderness bars before ordering.",
   "who": "Standard-rail Forester owners who want the most payload left for gear and the least liftgate worry.",
   "specs": [["Volume", "14 cu ft (400 L)"], ["Exterior", "68.9 × 32.1 × 16.6 in"], ["Box weight", "31 lb"], ["Max load", "165 lb (75 kg)"], ["Ski length", "Up to 155 cm"], ["Mount / lock", "PowerClick / central locking"], ["Front clearance", ">44 13/16 in (Thule)"], ["Crossbar spread", "Not published; confirm"]]},
  {"asin": "B0DYQ4T5ZZ", "role": "Best premium 16 cu ft", "price": "$879.95",
   "pros": ["16 cu ft in 76.8 in, the shortest 16 cu ft box here", "43 lb, lighter than both Yakima 16s", "165 lb maximum load", "DualSide opening and PowerClick mounts", "Thule publishes a front-clearance figure (>50 5/8 in)"],
   "cons": ["$879.95, the priciest box here", "Skis only up to 175 cm", "Crossbar spread and warranty terms not on the product page; confirm"],
   "body": "If you want a full 16 cu ft on the Forester with the least length at the back, the Thule Force 3 L is the premium pick. Thule lists it at 76.8 x 33.3 x 16.8 in, 16 cu ft (450 L), 43 lb and a 165 lb maximum load, with DualSide opening and PowerClick quick-mount clamps that include a torque indicator. That makes it 2.2 in shorter than the GrandTour 16 and 6.2 in shorter than the CBX 16, while weighing 8.5 lb less than the GrandTour and 14 lb less than the CBX. Thule's page says that if your vehicle's hatch clearance exceeds the listed front-clearance figure, more than 50 5/8 in for this box, it will fit without contacting the hatch.\n\nOn a 176 lb standard Forester roof, the lighter shell leaves roughly 115 lb for gear after typical bars, which is the best of any 16 cu ft box here. The costs are price and ski length. At $879.95 it is $170 more than the GrandTour 16, and it takes skis only to 175 cm, so longer skis need a longer box. Thule's page doesn't list a crossbar spread or warranty terms, so confirm both before you buy.",
   "who": "Forester owners who want the full 16 cu ft in the shortest, lightest shell and will pay for it.",
   "specs": [["Volume", "16 cu ft (450 L)"], ["Exterior", "76.8 × 33.3 × 16.8 in"], ["Box weight", "43 lb"], ["Max load", "165 lb"], ["Ski length", "Up to 175 cm"], ["Mount", "PowerClick with torque indicator"], ["Front clearance", ">50 5/8 in (Thule)"], ["Crossbar spread / warranty", "Not published; confirm"]]},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "price": "$864.97",
   "pros": ["Only 11 in tall, the lowest box here", "24–39 in crossbar spread, the widest range here", "110 lb weight capacity", "Memory Mount hardware for repeat installs", "Limited lifetime warranty, per etrailer"],
   "cons": ["11 cu ft for the price", "80 in long, so test the liftgate", "Skis only up to 182 cm, loaded diagonally"],
   "body": "The INNO Wedge 660 is the box for Forester owners who park in a garage or care about wind. etrailer lists it at 80 x 33 x 11 in with 11 cu ft, a 42 lb box weight, a 110 lb weight capacity and a 24–39 in crossbar spread, the widest range on this page. At 11 in tall it is 4 in lower than the next-lowest box here and 8 in lower than the SportRack Vista XL. The dual-side lid opens with push buttons, keyed locks on each side secure both the cargo and the mounting hardware, and INNO's Memory Mount hardware needs a one-time setup so repeat installs go quickly. It fits round, square, aero, elliptical and most factory crossbars, per etrailer, which lists it at $864.97 with a limited lifetime warranty.\n\nThe low shape costs capacity: 11 cu ft is a flat, long space suited to skis, soft bags and camping pads rather than tall items. Skis up to 182 cm fit diagonally. At 80 in it also sits long on a compact roof, so mount it forward and open the liftgate slowly the first time. Its 42 lb weight leaves roughly 120 lb for gear under the standard 176 lb limit.",
   "who": "Garage parkers and highway drivers who want the lowest box and the widest spread range.",
   "specs": [["Volume", "11 cu ft"], ["Exterior", "80 × 33 × 11 in"], ["Box weight", "42 lb"], ["Weight capacity", "110 lb"], ["Crossbar spread", "24–39 in"], ["Ski length", "Up to 182 cm (diagonal)"], ["Opening", "Dual-side, push-button"], ["Warranty", "Limited lifetime (etrailer)"]]},
  {"asin": "B07B4P7WYX", "role": "Best mid-weight value", "price": "Not listed by Rhino-Rack; see listing",
   "pros": ["15.5 cu ft (440 L) in 76 in", "38.6 lb, lighter than every 16 cu ft box here", "Dual-side opening with keyed locks on both sides and 3 locking points", "Spread of 620–930 mm (about 24.4–36.6 in)", "5-year warranty"],
   "cons": ["Rhino-Rack's page lists no US price; confirm on the listing", "Maximum speed of 130 km/h (about 80 mph) with the box fitted, per the instructions", "75 kg (165 lb) max load, like most boxes here"],
   "body": "The Rhino-Rack MasterFit 440 fills the gap between the light Thule Pulse 2 M and the 16 cu ft boxes. Rhino-Rack lists it at 76 x 32 x 17 in with 440 L (15.5 cu ft) inside, a 38.6 lb box weight and a 75 kg maximum load. It opens from both sides, has keyed locks on both sides and three locking points, comes with two load straps, and carries a 5-year warranty. Rhino-Rack's instructions give a crossbar spacing of 620 mm minimum and 930 mm maximum for this size, about 24.4 to 36.6 in, which clamp-on Forester bars can meet easily.\n\nFor the Forester, the numbers line up well. At 76 in it is 3 in shorter than the GrandTour 16, and at 38.6 lb it is almost 13 lb lighter, leaving roughly 120 lb for gear under a 176 lb driving limit. The instructions also set a maximum speed of 130 km/h with the box fitted, which is fine for US highways but worth knowing. Rhino-Rack's US page doesn't show a price, so check the listing, and confirm that the mounting hardware suits your bar profile.",
   "who": "Buyers who want close to 16 cu ft at under 40 lb and a published warranty.",
   "specs": [["Volume", "15.5 cu ft (440 L)"], ["Exterior", "76 × 32 × 17 in"], ["Box weight", "38.6 lb"], ["Max load", "75 kg (165 lb)"], ["Crossbar spread", "620–930 mm (about 24.4–36.6 in)"], ["Opening / locks", "Dual-side; 3 locking points"], ["Max speed", "130 km/h (instructions)"], ["Warranty", "5 years"]]},
  {"asin": "B0C41RZ4HM", "role": "Most rugged", "price": "$699",
   "pros": ["16 cu ft in a rugged, textured shell", "Only 15 in tall despite 16 cu ft", "Dual-side opening with SKS locks", "24–35.5 in crossbar spread", "Limited lifetime warranty"],
   "cons": ["57 lb, the heaviest box here", "83 in long and 38 in wide, the longest box here", "Yakima's page notes owner reports of fitment trouble on some factory bars"],
   "body": "The Yakima CBX 16 is the box to pick if you want something that looks and wears like adventure gear. Yakima lists it at 83 x 38 x 15 in and 16 cu ft, with a dual-sided hatch, SKS locks, an easy-grab lid handle, room for skis and boards up to 185 cm, a 24–35.5 in crossbar spread and a limited lifetime warranty, for $699. Yakima says it mounts to its own StreamLine crossbars and to factory or aero bars. Its 15 in height is low for a 16 cu ft box, which helps in garages.\n\nOn a Forester, the numbers ask for care. At 57 lb it is the heaviest box here, and on a standard car's 176 lb limit it leaves roughly 100 lb for gear once bars are counted. Wilderness owners, at 220 lb, get more room. It is also 83 in long and 38 in wide, the largest footprint here, so it needs to sit well forward and will fill the crossbars. The product page's customer reviews mention fitment trouble on some factory crossbars, and Yakima's support suggests checking bar compatibility, so confirm your bars' profile before you order.",
   "who": "Wilderness owners and anyone who wants a tough-looking 16 cu ft box and has the load margin for it.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "83 × 38 × 15 in"], ["Box weight", "57 lb"], ["Crossbar spread", "24–35.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS locks included"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B00BCLL8C0", "role": "Best budget", "price": "$449.95",
   "pros": ["18 cu ft for $449.95, the most volume and lowest price here", "63 in long, the shortest box here", "Tool-free mounting with a lock included", "Fits square, round and most factory bars, per SportRack", "UV-resistant ABS shell"],
   "cons": ["Rear-opening lid means loading over the back of the roof", "Fixed mounting positions (25-7/8, 27-7/8 or 29-7/8 in per etrailer)", "Box weight and load rating not published; confirm"],
   "body": "The SportRack Vista XL is the budget box that suits a compact roof. SportRack lists it at 63 x 38 x 19 in with 18 cu ft of space, UV-resistant ABS, tool-free mounting hardware and a lock, for $449.95. The shape is what matters on a Forester: short and wide instead of long and narrow, so it holds more than any 16 cu ft box here while sitting well forward of the liftgate. It is 5.9 in shorter than the Thule Pulse 2 M and 20 in shorter than the CBX 16.\n\nThere are three checks. First, etrailer's expert lists three fixed mounting positions, 25-7/8, 27-7/8 and 29-7/8 in center to center, so set your clamp-on bars to one of them. On the Forester's raised rails, that is easy to do. Second, the lid opens at the rear, so you load it from behind the car, reaching over the back of the roof; SportRack pitches that as loading away from traffic, but a step helps. Third, SportRack doesn't publish a box weight or load rating, so confirm them on the listing and pack light, bulky gear to stay inside 176 lb. At 19 in it is the tallest box here, which matters in low garages.",
   "who": "Budget buyers who want the most space for the least money and the shortest box on the roof.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "63 × 38 × 19 in"], ["Opening", "Rear"], ["Mounting positions", "25-7/8, 27-7/8 or 29-7/8 in (etrailer)"], ["Hardware", "Tool-free; lock included"], ["Material", "UV-resistant ABS"], ["Box weight / max load", "Not published; confirm"], ["Price", "$449.95 (SportRack)"]]},
 ],
 "install": [
  "Check the roof first, because a Base may have no rails. Then fit crossbars listed for your roof: raised-rail bars on cars with raised rails, or a Wilderness-listed set on the 2022–2024 Wilderness. Torque them to the maker's spec.",
  "Set the spread inside the box's range (24–36 in GrandTour 16, 24–35.5 in CBX 16, 24–39 in Wedge 660, about 24.4–36.6 in MasterFit 440) or on one of the Vista XL's fixed positions, keeping the rear bar ahead of the rail's downward curve.",
  "With a helper, set the box on the bars, center it side to side and slide it as far forward as the windshield and antenna allow, keeping it clear of the moonroof's path.",
  "Fit the clamps loosely, open the liftgate slowly and check the gap at the tail, then tighten the clamps to the box maker's spec (Thule's PowerClick clamps show a torque indicator).",
  "Lock the box, pull on each corner to check the mounts, and re-check the clamps after the first drive.",
  "Load heavy items low and between the bars, keep bars + box + gear under 176 lb (220 lb Wilderness), and leave the moonroof closed.",
 ],
 "avoid": [
  {"h": "Standard-rail bars on a Wilderness", "body": "Many Forester crossbars are titled \"not Wilderness\" because the 2022–2024 Wilderness has its own rails. Buy bars for your rail first; the box clamps to those."},
  {"h": "Loading to the box's rating", "body": "The Thule boxes are rated at 165 lb, but the standard Forester roof carries 176 lb including bars and box. After a 40–57 lb box and the bars, about 100–130 lb is left for gear."},
  {"h": "A long box without testing the liftgate", "body": "The CBX 16 is 83 in long and the Wedge 660 80 in. Mount them forward and open the liftgate slowly once, or pick the 63 in Vista XL or 68.9 in Pulse 2 M."},
  {"h": "Opening the moonroof under a box", "body": "etrailer notes it is not recommended to open, vent or retract the sun or moon roof with a Thule system installed on the Forester. Keep it closed while the box is on."},
 ],
 "verdict": {
  "thesis": "Fit bars for your rail, then choose the Yakima GrandTour 16 for an all-round 16 cu ft box, the Thule Pulse 2 M to save roof load, or the SportRack Vista XL on a budget.",
  "body": "On the SK Forester, the best box balances length and weight against a 176 lb driving limit. The GrandTour 16 is the all-rounder: 16 cu ft in 79 in, a 24–36 in spread and a lifetime warranty. The Thule Pulse 2 M is the smart choice when payload matters, at 31 lb and 68.9 in, and the Force 3 L gives the full 16 cu ft in a shorter, lighter shell for more money. The INNO Wedge 660 is the low-profile box for garages, the Rhino-Rack MasterFit 440 is the light 15.5 cu ft option with a 5-year warranty, and the CBX 16 suits Wilderness owners with 220 lb to spend. The SportRack Vista XL is the budget pick, as long as you're fine loading from the rear.\n\nBefore any box, you need crossbars: see the 2019–2024 Forester roof rack page for bars fit-checked by rail type. If bikes are part of the trip, a trailer hitch with a hitch bike rack keeps that weight off the roof, and all-weather floor liners protect the cabin on ski and camping weekends. The vehicle hub lists every fit-checked accessory for your Forester.",
 },
 "sources": [
  ["Yakima GrandTour 16 (Yakima)", "https://yakima.com/products/grandtour-16"],
  ["Yakima CBX 16 (Yakima)", "https://yakima.com/products/cbx-16"],
  ["Thule Pulse 2 M (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-pulse-2-m-_-610250"],
  ["Thule Force 3 L (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-force-3-l-_-645750"],
  ["INNO Wedge 660 specs (etrailer)", "https://www.etrailer.com/Roof-Box/Inno/INBRM660BK.html"],
  ["Rhino-Rack MasterFit Roof Box 440L (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-racks/roof-boxes/roof-boxes/masterfit-roof-box-440l-black-_rmft440"],
  ["Rhino-Rack MasterFit instructions: load, spacing, speed (Rhino-Rack)", "https://assets.rhinorack.com/Instructions/Accessories/RMFT-Masterfit.pdf"],
  ["SportRack Vista XL (SportRack)", "https://www.sportrack.com/product/vista-xl-cargo-box/"],
  ["SportRack Vista XL mounting positions (etrailer)", "https://www.etrailer.com/question-156482.html"],
  ["2022 Forester roof rack systems and moonroof note (etrailer)", "https://www.etrailer.com/roof-2022_Subaru_Forester.htm"],
  ["2022 Forester Wilderness first look: roof ratings (Our Auto Expert)", "https://www.ourautoexpert.com/2022-subaru-forester-wilderness-first-look/"],
  ["2019 Forester trim comparison: roof rails by trim (Subaru)", "https://www.subaru.com/services/vehicles/pdf/trimComparison/2019/FOR"],
  ["2022 Forester trim comparison: roof rails and capacity, towing by trim (Subaru)", "https://www.subaru.com/services/vehicles/pdf/trimComparison/2022/FOR"],
  ["2024 Forester trim comparison: roof rails and capacity, towing by trim (Subaru)", "https://www.subaru.com/services/vehicles/pdf/trimComparison/2024/FOR"],
  ["Subaru announces pricing on refreshed 2022 Forester: roof rail design and load limits (Subaru U.S. Media Center)", "https://media.subaru.com/pressrelease/1789/1/subaru-announces-pricing-refreshed-2022-forester-suv"],
  ["Subaru L101SSJ005 trailer hitch, 2022–2024 (Subaru Parts Pros)", "https://www.subarupartspros.com/sku/l101ssj005.html"],
  ["Subaru L101SSJ001 trailer hitch, 2019–2021 (Subaru Parts Pros)", "https://www.subarupartspros.com/sku/l101ssj001.html"],
  ["Subaru Forester generations (Wikipedia)", "https://en.wikipedia.org/wiki/Subaru_Forester"],
  ["Cargo box fuel economy impact (fueleconomy.gov)", "https://www.fueleconomy.gov/feg/driveHabits.jsp"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Forester roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B083KP48XC","Yakima GrandTour 16 Premium Rooftop Cargo Box, 16 cu ft, dual-side opening (79 in long)","Yakima","$700–$900",{},"Universal box; needs crossbars (24-36 in spread). Confirm liftgate gap."),
 ("B0G8C5LHQ5","Thule Pulse 2 M Roof-Mounted Box, 14 Cubic Ft, Dual-Side Opening","Thule","$650–$750",{},"31 lb, 68.9 in long; confirm crossbar spread with Thule's fit guide."),
 ("B0DYQ4T5ZZ","Thule Force 3 L Rooftop Cargo Box, 16 cu ft (76.8 in long)","Thule","$800–$950",{},"Shortest 16 cu ft here; confirm crossbar spread with Thule."),
 ("B06VX9L59C","INNO BRM660BK Wedge Cargo Box - 11 Cubic FT (Gloss Black)","INNO","$800–$900",{},"11 in tall, 24-39 in spread; confirm bar profile and liftgate gap."),
 ("B07B4P7WYX","Rhino-Rack MasterFit Roof Box 440L (Black)","Rhino-Rack","See listing",{},"38.6 lb, about 24.4-36.6 in spread; confirm price and bar fit."),
 ("B0C41RZ4HM","Yakima CBX 16 Aerodynamic Rooftop Cargo Box for Cars, Wagons and SUVs","Yakima","$650–$750",{},"57 lb and 83 in long; confirm load math and factory-bar fit."),
 ("B00BCLL8C0","SportRack Vista XL Rear Opening Cargo Box, 18 cu ft, Black","SportRack","$400–$500",{},"Fixed mounting positions; confirm box weight and load rating on the listing."),
]
