"""Long-form article — Best Trailer Hitches for 2017–2026 Tesla Model 3 (pre-Highland and 2024+ Highland).
Mirrors the approved pilot (ford_f150_2021_tonneau.py), adapted to hitch logic: Highland vs pre-Highland replaces
bed length, and Tesla's US rating (Tesla Shop + owner's manual) caps every hitch rating. No invented hands-on
testing: specs come from the Tesla Shop, Tesla owner's manual, CURT, Stealth Hitches and etrailer pages in
sources (checked 2026-09-24).
Source fixes 2026-10-04: added what Tesla's owner's manual says about accessory carriers, towing and warranty (new FAQ, plus FAQ, takeaways, fit_table, look_for, look_table, types_table, picks, install, new avoid item, verdict); stated that Tesla's 2,200/1,650 lb, 200 lb tongue and 121 lb carrier figures are for a car with Tesla's own Tow Package (2024+ Rear-Wheel Drive and All-Wheel Drive, not the Performance) and that Tesla gives no figure for an aftermarket hitch; added "we could not confirm" on how Tesla service treats an aftermarket hitch and on Trailer Mode with an aftermarket harness; removed wording that presented an aftermarket hitch as the default or a sensible choice for bikes or towing; attributed the Highland date and the European tow bar to Wikipedia and pointed readers to the door-jamb build date; attributed the 4-pin connector to the Tesla Shop.
Text fixes 2026-10-04 (round 2): TITLE and META no longer promise hitches "for bike racks": they now say the six picks are aftermarket receivers, that Tesla's manual says not to fit a carrier without its Tow Package, and that 121 lb is the carrier limit of that package (Tesla's Towing and Accessories page, reopened); dek now says "aftermarket hitches"; reviewed date updated.
"""

KEY = ("tesla", "model-3", "2017-present", "hitches")

TITLE = "Best Hitches for 2017–2026 Tesla Model 3: 6 Aftermarket Receiver Picks, Highland vs Pre-Highland"
META = ("Six aftermarket Model 3 receivers for 2017–2023 and 2024+ Highland cars. Tesla's manual says not to "
        "fit a carrier without its Tow Package (121 lb carrier limit).")

FAQ = [
 ("Can a Tesla Model 3 tow in the US?",
  "Going by Tesla's own pages, only a car fitted with Tesla's Tow Package. The Tesla Shop sells the Model 3 Tow Package at $1,300 for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later, rated up to 2,200 lb, and says it is not compatible with the Model 3 Performance. For a car with that package, Tesla's current owner's manual gives 1,650 lb without trailer brakes, 2,200 lb with them and 200 lb tongue weight, and says: 'Trailer Mode must always be active when towing a trailer.' The Vehicle Loading page in both the 2017–2023 manual and the current one says: 'Do not use Model 3 for towing purposes. Model 3 does not currently support towing.' Tesla gives no towing figure for an aftermarket hitch. Wikipedia says Tesla offered a tow bar on European Model 3s from May 2019. The Tesla Shop lists no tow package for 2017–2023 US cars."),
 ("Does Tesla allow a bike rack on an aftermarket Model 3 hitch?",
  "Tesla's Model 3 owner's manual ties carriers to its own tow package. The Towing and Accessories page says the package 'allows you to tow a trailer or carry an accessory (bicycles, skis, snowboards, etc.) with your Model 3'. The same page carries this caution: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package. Doing so can cause significant damage.' It adds: 'Damage caused by non-Tesla approved accessories is not covered by the warranty.' Nothing we read from Tesla approves an aftermarket hitch for a carrier or a trailer. Aftermarket makers such as CURT and Stealth Hitches sell hitches for the Model 3 anyway, and the six on this page are examples. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla before you buy, and decide with the answer in hand."),
 ("What is the best hitch for a Model 3 bike rack?",
  "Going by Tesla's manual, the only hitch Tesla provides for carrying bikes is its own Tow Package, which the Tesla Shop lists for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later. The manual says not to install an accessory carrier on a Model 3 that is not equipped with the towing package, so read the answer above and ask Tesla first. If you still choose an aftermarket hitch, the Stealth Hitches rack package is the first aftermarket pick here: Stealth lists it for the 2017–2025 Model 3, the 2 in rack receiver detaches, and nothing shows under the bumper when it's off. CURT's 13431 is the brand-name bolt-on for 2017–2023 cars, with a receiver that stays visible. etrailer lists it at $335.78, with 2,000 lb GTW and 300 lb tongue weight. Those are the makers' ratings for the hitch, not figures from Tesla."),
 ("How much weight can a bike rack put on a Model 3?",
  "Tesla's figure is for its own package. The current Model 3 owner's manual says the tow package's 2 in hitch receiver can support an accessory carrier and is 'designed to support vertical loads of up to 121 lbs (55 kg)'. That covers the rack and the bikes together. The manual's own example is a 40 lb carrier with two items of about 40 lb each. A 45–50 lb two-bike platform rack leaves about 70 lb for bikes, which is too little for most pairs of e-bikes. Tesla gives no figure for an aftermarket hitch, and its manual says not to install an accessory carrier on a Model 3 that is not equipped with the towing package. Stealth rates its 2 in rack receiver at 350 lb, but that is Stealth's rating for its own part. We could not confirm whether Tesla's 121 lb figure can be applied to a receiver Tesla did not fit, so ask Tesla."),
 ("Do 2017–2023 Model 3 hitches fit the 2024 Highland?",
  "Mostly no. CURT lists 13431, 13449 and 11581 for the 2017–2023 Model 3 only, and the maXpeedingrods listing stops at 2023. The Highland refresh reshaped the rear, including taillights that no longer break between trunk and side. Stealth Hitches is the exception: it lists its SHR09001 for 2017–2025. For a 2024 or later Rear-Wheel Drive or All-Wheel Drive car, Tesla's own package is the route its manual provides for. An aftermarket listing has to name Highland or 2024+, as the TIOYAR does."),
 ("Is a 1-1/4 in or 2 in receiver better on a Model 3?",
  "Two inch, for most people. More bike racks come in 2 in, and the rack stays steadier in the larger receiver. Tesla's own tow package and the Stealth hitch both use 2 in. The 1-1/4 in CURT 11581 is listed for 2017–2023 cars and takes a rack with a 1-1/4 in shank. CURT gives it the same 2,000 lb GTW as its 2 in part and a lower 200 lb tongue weight. Receiver size changes nothing in Tesla's manual, which says not to install an accessory carrier on a car without its towing package."),
 ("What does 'hidden hitch' mean on a Model 3?",
  "The visible parts come off when you're not using them. Stealth Hitches bolts a hitch beam and a stainless latch block behind the bumper. The 2 in rack receiver and the ball mount lock into the latch block and detach, so the car looks stock when they're out. Stealth says installation needs no welding or drilling and quotes about four hours. CURT's 13431 has a concealed cross tube, but the receiver stays under the bumper."),
 ("Can I add towing to a Stealth rack package later?",
  "Stealth sells one. Its towing conversion kit, SHT25048, is $269 on Stealth's own store. It adds safety-chain anchors, harness and controller kits, a magnetic clip, a zero-play ball mount and a 2 in ball, and uses the same latch block as the rack receiver. Tesla's position is separate from Stealth's. The Vehicle Loading page in both versions of Tesla's manual says: 'Do not use Model 3 for towing purposes. Model 3 does not currently support towing.' It adds: 'Using Model 3 for towing without Tesla-approved towing components and accessories may void the warranty.' Tesla's towing figures are for a car fitted with its own Tow Package, and its manual says Trailer Mode must always be active when towing a trailer. We could not confirm whether Trailer Mode works with an aftermarket harness, so ask Tesla before you tow."),
 ("Do I need to remove the bumper to install a Model 3 hitch?",
  "Yes, on every hitch here. etrailer notes that CURT's 13431 needs the rear bumper fascia and an undercarriage trim panel removed, and reviewers there report tight tolerances and some trimming when the fascia goes back on. CURT rates its Model 3 hitches as a professional-level install. Stealth quotes about four hours with no welding or drilling. Tesla installs its own package at a Service Center, included in the $1,300."),
 ("Will a hitch bike rack block the Model 3's lights or trunk?",
  "A loaded rack usually covers part of the lower rear and can hide the plate. Most platform racks tilt down so the trunk opens, but check the tilt clearance on a Model 3 before you buy. The Tesla Shop lists a trailer harness and a North America 4-pin connector with Tesla's package. With an aftermarket hitch, add a light board for the rack if your state requires visible lights and plate."),
 ("Can I use a vertical-hanging bike rack on a Model 3 hitch?",
  "Not on the CURT hitches: CURT says its Model 3 hitches are not compatible with racks that hang bikes vertically. Those racks put the most leverage on the receiver, and the 121 lb that Tesla gives for its own tow-package receiver would rule out most of them once four or five bikes are loaded. Use a platform rack sized to your bikes."),
]

ARTICLE = {
 "dek": "Six aftermarket hitches for the 2017–2026 Model 3, hidden and bolt-on, sorted by pre-Highland (2017–2023) and Highland (2024+) fit, with Tesla's $1,300 US tow package, its 2,200 lb rating, the 121 lb carrier figure that goes with it, and what Tesla's manual says about fitting a carrier to a car without that package.",
 "author": "jake-morrison",
 "reviewed": "2026-10-04",
 "method": "We did not install these hitches ourselves. We ranked them on published ratings (class, receiver, gross trailer weight, tongue weight), on the Model 3 years each maker or listing names, and on install details from CURT, Stealth Hitches and etrailer. Tesla's US tow status and limits come from the Tesla Shop and Tesla's Model 3 owner's manuals. We reopened those pages on October 4, 2026 for the wording on accessory carriers, towing and warranty, and we report that wording without having confirmed how Tesla service applies it. Prices were checked at Tesla, Stealth and etrailer in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Tesla sells a Tow Package only for 2024+ Rear-Wheel Drive and All-Wheel Drive cars:** $1,300, rated up to 2,200 lb, not compatible with the Performance. The Vehicle Loading page in both the 2017–2023 manual and the current one says: 'Do not use Model 3 for towing purposes.'",
  "**Tesla's manual ties carriers to that package.** It says: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package', and that damage caused by non-Tesla approved accessories is not covered by the warranty. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla before you buy.",
  "**121 lb is Tesla's figure for its own receiver.** With the Tow Package, rack plus bikes must fit inside it. Tesla gives no figure for an aftermarket hitch, whatever the hitch maker's rating says.",
  "**Aftermarket makers sell hitches anyway, and most are pre-Highland only.** CURT 13431, 13449 and 11581 list 2017–2023. Stealth lists 2017–2025.",
  "**Hidden or visible, the rear fascia comes off.** Stealth's receiver detaches; CURT's stays under the bumper. CURT calls its Model 3 hitches a professional-level install.",
 ],
 "top_picks": [
  {"asin": "B09DGB75RL", "role": "Best hidden aftermarket hitch", "why": "Detachable 2 in rack receiver; nothing shows when off; listed for 2017–2025"},
  {"asin": "B09DG9SX4S", "role": "Hidden hitch with towing parts", "why": "Same hidden hitch plus ball mount, 4-way wiring and chain anchors"},
  {"asin": "B07YXHNHHW", "role": "Best brand-name bolt-on (2017–2023)", "why": "CURT 13431: 2 in, 2,000 lb GTW, 300 lb TW, limited lifetime warranty"},
  {"asin": "B086RQQGF2", "role": "Best 1-1/4 in", "why": "CURT 11581 for small racks; 2,000 lb GTW, 36 lb hitch"},
  {"asin": "B0FY6GS5L5", "role": "Budget pick for Highland", "why": "Listed for 2024–2026 Model 3 with a 2 in receiver"},
 ],
 "fit_table": {
  "caption": "Model 3 years and hitch options (Highland changed the rear; match the listing to your car; the third column lists aftermarket hitches, which are not Tesla's tow package)",
  "head": ["Years", "Tesla US tow option", "Aftermarket hitches that list it", "Notes"],
  "rows": [
   ["2017–2023 (pre-Highland)", "None", "CURT 13431, 13449, 11581; Stealth SHR09001; maXpeedingrods", "Tesla lists no tow package. Both manuals: 'Do not use Model 3 for towing purposes.' Manual: no accessory carrier without the towing package. Ask Tesla first."],
   ["2024–2025 Highland RWD / AWD", "Tow Package, $1,300, up to 2,200 lb", "Stealth SHR09001 (to 2025), TIOYAR", "With Tesla's package, the manual gives 200 lb tongue weight and 121 lb for carriers. Tesla gives no figure for an aftermarket hitch."],
   ["2024+ Highland Performance", "Not compatible (Tesla Shop)", "Confirm with the seller", "No Tesla tow package, so the manual's caution on accessory carriers applies. Ask Tesla first."],
   ["2026", "Tow Package (2024+ RWD/AWD)", "TIOYAR (2024–2026)", "Stealth lists to 2025; confirm 2026."],
  ],
 },
 "look_for": [
  {"h": "Pre-Highland or Highland",
   "body": "Wikipedia says the refreshed Model 3, known as Highland, was made available for order in North America on January 10, 2024. Its redesigned taillights no longer break between the trunk and the sides, and the rear changed enough that most hitches were not carried over. CURT lists its 13431, 13449 and 11581 for 2017–2023 only, and the maXpeedingrods listing stops at 2023. Stealth Hitches lists its SHR09001 for 2017–2025, and the TIOYAR is sold for 2024–2026. Go by the build date on the door-jamb label and the listing's fit notes, and ask the seller if those two don't settle it."},
  {"h": "Tesla's US tow status",
   "body": "In the US, Tesla's tow option starts with cars produced in 2024. The Tesla Shop lists a $1,300 Model 3 Tow Package for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later, rated up to 2,200 lb, with a 2 in receiver, 4-pin connector, harness and tow mode software, installed at a Service Center. It is not compatible with the Performance. The manual's figures (2,200 lb with trailer brakes, 1,650 lb without, 200 lb tongue weight) are for a car fitted with that package, and Tesla gives no figure for an aftermarket hitch. For every other Model 3, the Vehicle Loading page in both the 2017–2023 manual and the current one says: 'Do not use Model 3 for towing purposes. Model 3 does not currently support towing.' Wikipedia says Tesla offered a tow bar on European Model 3s from May 2019. Aftermarket makers sell hitches for 2017–2023 cars anyway. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla before you buy."},
  {"h": "Carriers: Tesla's caution and its 121 lb figure",
   "body": "Tesla's current owner's manual says the tow package includes a 2 in hitch receiver that can support an accessory carrier, 'designed to support vertical loads of up to 121 lbs (55 kg)'. As we read the manual's table, the figure is the same with five occupants or with two or fewer in the rear. The same page carries this caution: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package. Doing so can cause significant damage.' It adds: 'Damage caused by non-Tesla approved accessories is not covered by the warranty.' Stealth rates its 2 in rack receiver at 350 lb and CURT's 13431 carries 300 lb tongue weight, but those are the makers' ratings, and Tesla gives no figure for an aftermarket hitch. With Tesla's package, a 45–50 lb two-bike platform rack leaves about 70 lb for bikes. Two e-bikes usually weigh more than that, so plan around the rack's weight first."},
  {"h": "Hidden vs visible receiver",
   "body": "The Model 3 sits low, and a receiver under the bumper is what most owners notice. Stealth's hitch beam and stainless latch block stay behind the bumper, and the rack receiver and ball mount detach, so the car looks stock when they're off. Stealth says the design doesn't scrape and doesn't cost ground clearance. CURT's 13431 has a concealed cross tube, but the receiver stays visible below the bumper. It costs less and there's nothing to take on and off."},
  {"h": "Receiver size and rack choice",
   "body": "Two inch receivers take the widest choice of platform racks and hold them more firmly. Tesla's package and Stealth's hitch are 2 in, and so is the CURT 13431. CURT's 11581 is 1-1/4 in, sized for a rack with a 1-1/4 in shank, with 2,000 lb GTW and 200 lb tongue weight. CURT says none of its Model 3 hitches take vertical-hanging bike racks, and the 121 lb Tesla gives for its own receiver would rule out most of those anyway."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "Listing names 2017–2023 or 2024+ Highland, and your drivetrain", "\"Fits Model 3\" with no years"],
   ["Receiver", "2 in for platform racks", "1-1/4 in if you plan a heavier rack later"],
   ["Ratings", "Published GTW and tongue weight, read as the maker's rating for the hitch; Tesla's 121 lb is for its own tow-package receiver", "Treating a hitch rating as Tesla's approval to tow or to carry a rack"],
   ["Look", "Detachable receiver if you care about the rear view", "Low-hanging receivers on a lowered car"],
   ["Install", "Maker's instructions and hardware list; professional install if unsure", "Listings with no instructions"],
   ["Lights", "Harness or light board when a rack hides the lights", "Racks that cover the plate with no board"],
  ],
 },
 "types_table": {
  "caption": "Hitch types on the Model 3 (Tesla's manual says not to install an accessory carrier on a car without its towing package; ratings in the aftermarket rows are the makers', and Tesla gives none for them)",
  "head": ["Type", "Price on this page", "Visible when not in use", "Towing", "Years", "Best for"],
  "rows": [
   ["Tesla Tow Package", "$1,300 installed", "Receiver visible", "Up to 2,200 lb", "2024+ RWD/AWD", "2024+ RWD/AWD owners who tow or carry bikes"],
   ["Hidden (Stealth)", "$568 on Stealth's store", "No", "Stealth's tow package or $269 kit; no Tesla figure", "2017–2025", "Clean look; ask Tesla first"],
   ["Brand-name bolt-on 2 in (CURT 13431)", "$335.78 (etrailer)", "Receiver only", "Hitch 2,000 lb (CURT); Tesla's manual says not to tow", "2017–2023", "Brand-name 2 in receiver; ask Tesla first"],
   ["Brand-name 1-1/4 in (CURT 11581)", "About $180–$260", "Receiver only", "Hitch 2,000 lb (CURT); Tesla's manual says not to tow", "2017–2023", "1-1/4 in racks; ask Tesla first"],
   ["Budget 2 in", "About $120–$200", "Receiver visible", "Confirm; no Tesla figure", "By listing", "Lowest cost; ask Tesla first"],
  ],
 },
 "picks": [
  {"asin": "B09DGB75RL", "role": "Best hidden aftermarket hitch", "price": "$450–$600",
   "pros": ["Nothing visible under the bumper when the receiver is off", "Detachable 2 in rack receiver on a stainless latch block with integral lock", "Listed for 2017–2025, covering both pre-Highland and Highland", "No welding or drilling, about 4 hours (Stealth)", "Lifetime guarantee for as long as you own the car; made in the USA"],
   "cons": ["Costs more than a CURT bolt-on", "Rack only; towing needs the $269 conversion kit", "2026 cars not listed; confirm"],
   "body": "The Model 3's low, clean rear is the case for a hidden hitch. The SHR09001 bolts a hitch beam behind the bumper with a stainless steel latch block and an integral lock. The 2 in rack receiver slides into the latch block and comes out when you're done, so the car looks stock between trips and there's nothing to scrape on driveways. Stealth rates the 2 in rack receiver at 350 lb and the 1-1/4 in adapter at 300 lb, says the install needs no welding or drilling, and quotes about four hours. It is finished in stainless and powder coat, made in the USA, and guaranteed for as long as you own the car.\n\nStealth lists it for the 2017–2025 Model 3, which makes it one of the few hitches that spans pre-Highland and Highland cars. Its store shows $568 for the SHR09001; this Amazon listing is the rack package, so compare what's in the box before you buy. Stealth's ratings are for its own part. Tesla's manual says not to install an accessory carrier on a Model 3 that is not equipped with the towing package, and the 121 lb vertical load it prints is for Tesla's own receiver. Tesla gives no figure for this hitch, so ask Tesla before you buy. Stealth also sells its SHT25048 kit, which adds a ball mount and wiring for $269.",
   "who": "Owners who carry bikes a few times a month, want the car to look untouched the rest of the time, and have asked Tesla about an aftermarket hitch first.",
   "specs": [["Type", "Hidden, detachable 2 in rack receiver"], ["Part #", "Stealth SHR09001"], ["Fits", "2017–2025 Model 3"], ["Rack receiver rating", "350 lb (2 in) / 300 lb (1-1/4 in adapter)"], ["Tesla's figure", "121 lb carriers, for Tesla's own receiver only (manual)"], ["Install", "About 4 hr, no welding or drilling"], ["Lock", "Integral lock in latch block"], ["Warranty", "Lifetime, while you own the car"], ["Made in", "USA"]]},
  {"asin": "B09DG9SX4S", "role": "Hidden hitch with towing parts", "price": "$550–$700",
   "pros": ["Rack receiver and ball mount on the same latch block", "Includes 4-way connector with magnetic clip and harness", "Chain anchors and 2 in ball included", "Stealth rates it 3,500 lb GTW and 350 lb tongue weight", "Same hidden look as the rack package"],
   "cons": ["Stealth's rating is far above the 2,200 lb Tesla gives for its own package, and Tesla gives no figure for an aftermarket hitch", "Most expensive aftermarket pick", "Doesn't include Tesla's Trailer Mode software"],
   "body": "This is the same Stealth hitch with the towing parts added. Stealth's combo package for the SHR09001 lists the bolt-up hitch beam, stainless latch with integral lock, detachable 2 in rack receiver, detachable ball mount at an 18 in standard height, 2 in ball, chain anchors, and a wiring harness with a 4-way connector on a magnetic clip. Stealth rates the hitch at 3,500 lb gross trailer weight and 350 lb tongue weight. etrailer lists a Stealth hidden hitch with towing kit at 3,500 lb and 350 lb as well.\n\nThose are Stealth's ratings, not Tesla's. Tesla's figures of 2,200 lb with trailer brakes, 1,650 lb without and 200 lb tongue weight are for a 2024 or later Rear-Wheel Drive or All-Wheel Drive car fitted with Tesla's own Tow Package, and Tesla gives no figure for an aftermarket hitch. The Vehicle Loading page in both versions of the manual says: 'Do not use Model 3 for towing purposes. Model 3 does not currently support towing.' It adds that towing without Tesla-approved towing components and accessories may void the warranty. The manual also says Trailer Mode must always be active when towing a trailer, and this package does not come with Tesla's tow mode software. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla before you buy this package for a trailer.",
   "who": "Owners who want Stealth's hidden hitch with the towing parts in one box, and who have asked Tesla how it treats aftermarket towing equipment.",
   "specs": [["Type", "Hidden, detachable rack receiver + ball mount"], ["Fits", "2017–2025 Model 3 (per listing)"], ["Hitch rating", "3,500 lb GTW / 350 lb TW (Stealth)"], ["Tesla's figures", "2,200 lb braked / 1,650 lb unbraked / 200 lb TW, with Tesla's Tow Package only"], ["Wiring", "4-way connector, magnetic clip, harness"], ["Ball mount", "Detachable, 18 in to top of ball"], ["Install", "About 4 hr, no welding or drilling"], ["Warranty", "Lifetime, while you own the car"]]},
  {"asin": "B07YXHNHHW", "role": "Best brand-name bolt-on (2017–2023)", "price": "$300–$360",
   "pros": ["Class 3, 2 in receiver for platform racks", "2,000 lb GTW and 300 lb tongue weight", "Concealed cross tube, gloss black powder coat", "Made in the USA; limited lifetime warranty", "etrailer lists it at $335.78, down from $608.95"],
   "cons": ["2017–2023 only; not for Highland", "Rear fascia and undertray come off; owners report tight refit", "Not for vertical-hanging bike racks"],
   "body": "CURT's 13431 is the brand-name bolt-on for a pre-Highland Model 3: a fully welded Class 3 hitch with a 2 in receiver, 2,000 lb gross trailer weight and 300 lb tongue weight. The cross tube is concealed behind the bumper, the finish is gloss black powder coat, and it's made in the USA with a limited lifetime warranty. etrailer lists it at $335.78 against a regular $608.95 and fits it to the 2017–2023 Model 3 only.\n\netrailer notes the install means removing the rear bumper fascia and an undercarriage trim panel. Several reviewers there describe tight tolerances when the bumper goes back on, including trimming plastic and filing holes to line things up. Budget time or a shop. CURT says its Model 3 hitches don't take vertical-hanging bike racks. The 300 lb tongue rating is CURT's figure for the hitch. Tesla gives no figure for an aftermarket hitch, and its manual says not to install an accessory carrier on a Model 3 without the towing package, which the Tesla Shop lists only for cars produced in 2024 or later. Ask Tesla before you buy. CURT's 13449 is a similar Class 3 hitch for 2017–2023 with the same 2,000 lb and 300 lb ratings.",
   "who": "2017–2023 owners who want a brand-name 2 in receiver at a mid-range price and have asked Tesla about an aftermarket hitch first.",
   "specs": [["Class / receiver", "Class 3, 2 in"], ["Part #", "CURT 13431"], ["Fits", "2017–2023 Model 3 (etrailer)"], ["Hitch rating", "2,000 lb GTW / 300 lb TW"], ["Tesla's position", "No tow package for 2017–2023; manual says no carrier without it"], ["Install", "Fascia and undertray removal"], ["Warranty", "Limited lifetime"], ["Made in", "USA"]]},
  {"asin": "B086RQQGF2", "role": "Best 1-1/4 in", "price": "$180–$260",
   "pros": ["1-1/4 in receiver takes racks with a 1-1/4 in shank", "2,000 lb GTW, 200 lb tongue weight", "36 lb hitch weight", "Concealed main body, gloss black powder coat with Bonderite rust coating", "Made in Wisconsin; limited lifetime warranty"],
   "cons": ["Fewer racks come in 1-1/4 in", "2017–2023 only", "Sold here by a reseller; confirm it's CURT 11581 in the box"],
   "body": "CURT's 11581 takes a rack with a 1-1/4 in shank without an adapter. It is a Class 1 hitch with a 1-1/4 in receiver, 2,000 lb gross trailer weight and 200 lb tongue weight, weighing 36 lb. The main body is concealed for a factory look, the finish is gloss black powder coat over a rust-resistant Bonderite coat, and CURT makes it in Wisconsin with a limited lifetime warranty (one year on finish and parts).\n\nCURT lists it for the 2017–2023 Model 3 and rates the install as professional. Like its other Model 3 hitches, it's not for vertical-hanging bike racks. The 200 lb tongue rating is CURT's figure for the hitch. Tesla gives no figure for an aftermarket hitch, and its manual says not to install an accessory carrier on a Model 3 without the towing package, so ask Tesla first. This Amazon listing is from a reseller, so check the part number when it arrives. For a new rack purchase, a 2 in hitch gives you more choice.",
   "who": "Pre-Highland owners with a light 1-1/4 in rack who don't want an adapter and have asked Tesla first.",
   "specs": [["Class / receiver", "Class 1, 1-1/4 in"], ["Part #", "CURT 11581"], ["Fits", "2017–2023 Model 3"], ["Hitch rating", "2,000 lb GTW / 200 lb TW"], ["Hitch weight", "36 lb"], ["Install", "Professional (CURT)"], ["Warranty", "Limited lifetime (1-yr finish, 1-yr parts)"]]},
  {"asin": "B0FY6GS5L5", "role": "Budget pick for Highland", "price": "$120–$200",
   "pros": ["Listing names the 2024, 2025 and 2026 Model 3", "2 in receiver for platform racks", "Black steel construction", "A fraction of Tesla's $1,300 package", "Covers 2026, which Stealth's listing doesn't"],
   "cons": ["Thin published specs; confirm ratings with the seller", "No wiring and no Trailer Mode", "Confirm Performance fit"],
   "body": "Highland owners have fewer choices, because most brand-name hitches stop at 2023. The TIOYAR listing is written for the 2024–2026 Model 3 and has a 2 in receiver in black steel. That makes it the lowest-priced Highland listing on this page, and one of the few that names 2026.\n\nIt doesn't publish the detail CURT and Stealth do, so ask the seller for the tongue-weight rating, what hardware comes in the box and whether the install needs trimming. Tesla's 121 lb carrier figure is for its own tow-package receiver, and Tesla gives no figure for this hitch. A Highland Rear-Wheel Drive or All-Wheel Drive owner has the route Tesla's manual provides for: the $1,300 Tow Package, rated to 2,200 lb, with wiring and the tow mode software. The manual says not to install an accessory carrier on a Model 3 without that package, so ask Tesla before buying this hitch instead. Tesla says its package is not compatible with the Performance, so Performance owners should confirm fit for this hitch with the seller too.",
   "who": "2024–2026 owners who want the lowest-priced receiver and have asked Tesla about an aftermarket hitch first.",
   "specs": [["Receiver", "2 in"], ["Fits", "2024–2026 Model 3 (per listing)"], ["Material", "Black steel"], ["Ratings", "Confirm with seller"], ["Tesla's figures", "121 lb carriers and 2,200 lb, with Tesla's package only"], ["Wiring", "Not included"]]},
  {"asin": "B0FXGN3CF9", "role": "Budget pick for 2017–2023", "price": "$120–$180",
   "pros": ["Lowest price for a pre-Highland 2 in receiver", "Listing names 2017–2023 Model 3", "Class II, 2 in receiver per the listing", "Takes 2 in platform racks", "Leaves budget for a better rack"],
   "cons": ["Pre-Highland only", "Less install documentation than CURT", "No wiring"],
   "body": "The maXpeedingrods Class II hitch is the low-cost alternative to CURT's 13431 for a pre-Highland car. The listing names the 2017–2023 Model 3 and uses a 2 in receiver, so standard platform racks fit without an adapter. Class II is the listing's label, and Tesla gives no figure for this hitch. Tesla's manual says not to install an accessory carrier on a Model 3 that is not equipped with the towing package, and the Vehicle Loading page in both versions of the manual says not to use the Model 3 for towing. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla before you buy.\n\nThe savings over CURT come from what you don't get: CURT's published ratings detail, made-in-USA welding and the lifetime warranty. Ask the seller for the instruction sheet and the hardware list, and expect the same fascia and undertray removal as any Model 3 hitch. The money saved can go toward a better rack or a light board.",
   "who": "2017–2023 owners who want the cheapest receiver, accept thinner specs and have asked Tesla first.",
   "specs": [["Class / receiver", "Class II, 2 in"], ["Fits", "2017–2023 Model 3 (per listing)"], ["Ratings", "Confirm on listing"], ["Tesla's position", "No tow package for 2017–2023; manual says no carrier without it"], ["Install", "Fascia removal expected"], ["Wiring", "Not included"]]},
 ],
 "install": [
  "Read Tesla's manual first. It says not to install an accessory carrier on a Model 3 without the towing package, so ask Tesla how it treats an aftermarket hitch before you start. Then confirm your build date and drivetrain: 2017–2023 and 2024+ Highland cars take different hitches, and Tesla's tow package excludes the Performance.",
  "For Tesla's package, book it through the Tesla Shop. Installation at a Service Center is included in the $1,300. The steps below are for aftermarket hitches.",
  "Remove the rear bumper fascia and undercarriage trim panel as the maker's sheet describes. Have a second person hold the fascia; it's wide and the clips are easy to break.",
  "Bolt the hitch beam to the mounting points and torque to the maker's figures. Stealth's latch block mounts at this stage.",
  "Refit the fascia, trimming only where the instructions say. etrailer reviewers report tight tolerances on the Model 3, so dry-fit before trimming.",
  "Weigh the rack and bikes together. Tesla's 121 lb figure is for its own tow-package receiver, and Tesla gives no figure for an aftermarket hitch, so follow the hitch and rack makers' limits and whatever Tesla told you. Re-torque the hitch bolts after the first few hundred miles.",
 ],
 "avoid": [
  {"h": "Fitting a carrier before asking Tesla", "body": "The Model 3 manual's caution reads: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package. Doing so can cause significant damage.' Its warranty note says damage caused by non-Tesla approved accessories is not covered. We could not confirm how Tesla service treats a car with an aftermarket hitch, so get Tesla's answer before you order."},
  {"h": "Towing on a 2017–2023 US car as if it were rated", "body": "The Vehicle Loading page in both versions of Tesla's manual says: 'Do not use Model 3 for towing purposes.' The Tesla Shop lists no tow package for those years, and a hitch rated 2,000 or 3,500 lb doesn't change that."},
  {"h": "Pre-Highland hitches on a 2024+ car", "body": "CURT's Model 3 hitches list 2017–2023. On a Highland Rear-Wheel Drive or All-Wheel Drive car, Tesla's package is the route its manual provides for, and an aftermarket listing has to name 2024+."},
  {"h": "Overloading the rack", "body": "Tesla's 121 lb figure is for its tow-package receiver and includes the rack. Two e-bikes on a 50 lb rack is usually over it. Tesla gives no figure for an aftermarket hitch."},
  {"h": "Vertical-hanging racks", "body": "CURT rules them out on its Model 3 hitches, and they put the most leverage on a low, short-overhang car."},
 ],
 "verdict": {
  "thesis": "Tesla's $1,300 Tow Package, for 2024+ Rear-Wheel Drive and All-Wheel Drive cars, is the only hitch Tesla's manual provides for, whether for a trailer or a bike rack. If you still go aftermarket after asking Tesla, Stealth's rack package lists 2017–2025 and CURT's 13431 lists 2017–2023.",
  "body": "Start with what Tesla says. Its Tow Package is sold for 2024 and later Rear-Wheel Drive and All-Wheel Drive cars, not the Performance, and the manual's figures (2,200 lb with trailer brakes, 1,650 lb without, 200 lb tongue weight, 121 lb for a carrier) are for a car fitted with it. For every other Model 3, the manual says: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package.' It adds that damage caused by non-Tesla approved accessories is not covered by the warranty, and the Vehicle Loading page in both versions of the manual says not to use the Model 3 for towing. Aftermarket makers sell hitches for the car anyway. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla before you buy, and decide with the answer in hand. Among the aftermarket hitches, Stealth's hidden hitch lists 2017–2025 and shows nothing when the receiver is off, CURT's 13431 gives a brand-name 2 in receiver for less on 2017–2023 cars, and TIOYAR is the budget listing for 2024–2026. Tesla gives no figure for any of them.\n\nA hitch bike rack keeps bikes off the glass roof and out of the airflow over it, which is the case for it over a roof rack. Once the hitch is sorted, all-weather floor mats are the other common add-on. The vehicle hub lists every fit-checked accessory for your Model 3.",
 },
 "sources": [
  ["Model 3 Tow Package (Tesla Shop)", "https://shop.tesla.com/product/model-3-tow-package"],
  ["Model 3 Owner's Manual: Towing and Accessories (Tesla)", "https://www.tesla.com/ownersmanual/model3/en_us/GUID-BD9A38D5-4410-45A3-8337-BDF7342750F3.html"],
  ["Model 3 Owner's Manual: Vehicle Loading, towing warning (Tesla)", "https://www.tesla.com/ownersmanual/model3/en_us/GUID-877ACE2D-B62F-4596-A6AD-A74F7905741C.html"],
  ["2017–2023 Model 3 Owner's Manual: Vehicle Loading (Tesla)", "https://www.tesla.com/ownersmanual/2017_2023_model3/en_us/GUID-877ACE2D-B62F-4596-A6AD-A74F7905741C.html"],
  ["Stealth Hitches SHR09001, 2017–2025 Model 3 (Stealth Hitches)", "https://stealthhitches.com/products/tesla-hitch-shr09001"],
  ["Stealth towing conversion kit SHT25048 (Stealth Hitches)", "https://stealthhitches.com/products/towing-conversion-kit-sht25048"],
  ["CURT 13431 Model 3 hitch (etrailer)", "https://www.etrailer.com/Trailer-Hitch/CURT/C13431.html"],
  ["CURT 13449 Class 3 hitch, Model 3 (CURT)", "https://www.curtmfg.com/part/13449"],
  ["CURT 11581 Class 1 hitch, Model 3 (CURT)", "https://www.curtmfg.com/part/11581"],
  ["2021 Tesla Model Y hitches incl. Stealth with towing kit (etrailer)", "https://www.etrailer.com/Trailer-Hitch/Tesla/Model+Y/2021/DT58MR.html?vehicleid=202120216003159"],
  ["Tesla Model 3 (Highland refresh dates, European tow bar)", "https://en.wikipedia.org/wiki/Tesla_Model_3"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note)
FITS = [
 ("B09DGB75RL","Stealth Hitches Receiver Hitch Rack Package, 2017-2025 Tesla Model 3, hidden 2 in receiver","Stealth Hitches","$450–$600",{"year_to":2025},"Hidden receiver; Tesla manual says no carrier without its tow package, ask Tesla."),
 ("B09DG9SX4S","Stealth Hitches Receiver Hitch Rack & Tow Package, 2017-2025 Tesla Model 3","Stealth Hitches","$550–$700",{"year_to":2025},"Adds ball mount + 4-way wiring; Tesla tow figures apply only with its own Tow Package."),
 ("B07YXHNHHW","CURT 13431 Class 3 Trailer Hitch 2 in, 2017-2023 Tesla Model 3","CURT","$300–$360",{"year_to":2023},"Pre-Highland only; 2,000 lb GTW / 300 lb TW."),
 ("B086RQQGF2","CURT 11581 Class 1 Trailer Hitch 1-1/4 in, 2017-2023 Tesla Model 3","CURT","$180–$260",{"year_to":2023},"Reseller listing; confirm part 11581 on arrival."),
 ("B0FY6GS5L5","TIOYAR Trailer Hitch 2 in Receiver, 2024-2026 Tesla Model 3 (Highland)","TIOYAR","$120–$200",{"year_from":2024},"Confirm ratings and Performance fit with seller."),
 ("B0FXGN3CF9","maXpeedingrods Class II Hitch 2 in, 2017-2023 Model 3","maXpeedingrods","$120–$180",{"year_to":2023},"Pre-Highland only."),
]
