"""Long-form article — Best Rooftop Cargo Boxes for 2017–2026 Tesla Model 3 (incl. 2024 Highland refresh).
Mirrors the approved RAV4 / Outback cargo-box pages. No invented hands-on testing: box specs come from the Thule,
Yakima, Rhino-Rack and SportRack product pages and etrailer (INNO) listed in sources; vehicle facts from
db/migrations/003_vehicles.sql, the Tesla Shop and the Model 3 roof-rack page's references (checked 2026-09-27).
Boxes are universal; the Model 3-specific part is the glass roof with fixed points, Tesla's 150 lb rating,
the short 28 in crossbar spread, trunk-lid clearance and range.
Source fixes 2026-10-04: reworded 150 lb as the Tesla Shop's load rating for Tesla's own rack (495 lb static load limit) and stated that the owner's manual prints no roof load (TITLE "150 lb Roof" became "150 lb Rack", FAQ, method, takeaways, fit_table, look_for, verdict); added the manual's wording on Tesla-approved roof racks with "we could not confirm whether Tesla approves any aftermarket bars" (FAQ, takeaways, install, verdict); replaced the hitch-carrier FAQ and the verdict's hitch sentence with Tesla's manual caution on accessory carriers and removed "1.25 in" (most hitches in the hitch guide are 2 in); attributed the Highland dates (Tesstudio and TESEVO build splits, Wikipedia order date) and pointed readers to the door-jamb build date.
Text fixes 2026-10-04 (round 2): fit_table cell "Fixed points only" became "Fixed mounting points", so it no longer rules out the door-frame clip system the roof rack guide documents from etrailer's listing; reviewed date updated.
"""

KEY = ("tesla", "model-3", "2017-present", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2017–2026 Tesla Model 3: 6 Boxes for a 28 in Spread and 150 lb Rack"
META = ("Six Thule, Yakima, INNO, Rhino-Rack and SportRack boxes for the Model 3's glass roof: 150 lb load math, "
        "28 in bar spread, trunk clearance and range.")

FAQ = [
 ("What is the best cargo box for a 2017–2026 Tesla Model 3?",
  "The Thule Pulse 2 M is the best overall cargo box for the 2017–2026 Tesla Model 3. At 31 lb and 68.9 in long with 14 cu ft, it leaves the most of the 150 lb rating Tesla gives its own rack and suits the car's 28 in crossbar spread. The INNO Wedge 660 is the lowest profile at 11 in tall, with a 24–39 in spread range that covers 28 in. If you need 16 cu ft, the Yakima SkyBox 16 fits a 24–34.5 in spread. The SportRack Vista XL is the budget pick, with 18 cu ft in 63 in. Fit crossbars for your build first, since original and Highland cars take different aftermarket bars, and Tesla's manual says to use only roof rack systems approved by Tesla."),
 ("Can you put a cargo box on a Tesla Model 3?",
  "Yes, once crossbars are fitted. The Model 3 has a glass roof with no rails, so the bars bolt into fixed mounting points under the roof trim; Tesla's own Model 3 Roof Rack has T-slots meant for cargo boxes, bike racks and ski racks. Any universal box then clamps to the bars, as long as its crossbar spread range covers the car's short spread and the total load stays under the 150 lb Tesla gives its own rack. Tesla's owner's manual says you must use 'only roof rack systems that have been approved by Tesla'. We could not confirm whether Tesla approves any aftermarket bars, so ask Tesla."),
 ("How much weight can a Model 3 roof carry with a cargo box?",
  "The Tesla Shop gives Tesla's own Model 3 Roof Rack a 150 lb load rating and a 495 lb static load limit. Tesla's owner's manual prints no roof load, so 150 lb is the rack's rating, not a separate figure for the roof. Plan the bars, the box and the cargo inside it. A 31 lb Thule Pulse 2 M leaves roughly 119 lb minus the weight of your bars; a 47 lb Yakima SkyBox 16 leaves about 103 lb minus the bars. Some boxes carry their own 165 lb rating, but 150 lb is the figure to plan around."),
 ("What crossbar spread do cargo boxes need on a Model 3?",
  "etrailer's product experts give the factory Model 3 roof rack a crossbar spread of 28 inches. Choose a box whose range includes 28 in: the Yakima SkyBox 16 (24–34.5 in), the INNO Wedge 660 (24–39 in, per etrailer) and the Rhino-Rack MasterFit 440 (about 24.4–36.6 in) all do. The Yakima DeepSpace 10 does not, because its minimum is 32 in. The SportRack Vista XL's 27-7/8 in position is the closest of its fixed positions."),
 ("Will a roof box hit the Model 3's trunk lid?",
  "It can if the box hangs too far back. The Model 3 is a sedan, and its trunk lid rises behind the rear glass. With a 28 in spread and a long box, the tail can overhang the back of the roof. Center the box on the bars so the overhang is split front and rear, keep the front clear of the windshield, and open the trunk slowly the first time. Short boxes such as the 68.9 in Pulse 2 M or 63 in Vista XL leave the most margin."),
 ("Does a 2017–2023 Model 3 box setup fit the 2024 Highland?",
  "The box does, because it clamps to crossbars rather than the car. The bars are the question. Tesstudio sells separate racks for 2017–2023.10 builds and the Highland from 2023.11 builds, and TESEVO lists them separately too. Those build splits are the sellers' own, and Wikipedia says the refreshed car was made available for order in North America on January 10, 2024. Tesla says its own Model 3 rack fits all Model 3 vehicles. Go by the build date on the door-jamb label and the listing's fit notes, buy bars listed for your build, then re-check the spread before mounting the box."),
 ("How much range does a cargo box cost on a Model 3?",
  "Tesla doesn't publish a figure. The best public data comes from fueleconomy.gov, which says a large, blunt rooftop cargo box can reduce fuel economy by around 2–8% in city driving, 6–17% on the highway and 10–25% at 65–75 mph. An EV loses energy to drag the same way, and a Model 3 is a low, slippery sedan, so a box adds a large share of its total drag. Plan highway charging stops conservatively and take the box off between trips."),
 ("Which cargo box is most aerodynamic for a Model 3?",
  "No maker here publishes a drag figure, so the best guide is shape. A low, tapered box presents less frontal area: the INNO Wedge 660 is only 11 in tall and the Yakima SkyBox 16 is 15 in. The Thule Pulse 2 M is 16.6 in tall but short and light. Mount the box level and centered, not nose-up, because a tilted box adds drag and wind noise."),
 ("Can I use a hitch cargo carrier instead of a roof box on a Model 3?",
  "Tesla's manual restricts it. It says: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package. Doing so can cause significant damage.' The Tesla Shop lists that package for Rear-Wheel Drive and All-Wheel Drive cars produced in 2024 or later, not the Performance. With it, the manual gives 121 lb of vertical load for the carrier and its contents together. Aftermarket makers sell receivers for other Model 3s, most of them 2 in. We could not confirm how Tesla service treats a car with an aftermarket hitch, so ask Tesla first. fueleconomy.gov, writing about gas vehicles, puts rear-mounted carriers at 1–5% worse on the highway against 6–17% for a rooftop box. For luggage and skis, a roof box remains the practical choice."),
 ("Will Thule and Yakima boxes clamp to Tesla's T-slot crossbars?",
  "Generally yes, but check the clamp's bar-size limit. Tesla says its Model 3 rack's T-slots take cargo boxes. etrailer notes Yakima GrandTour boxes fit Tesla bars up to 3-1/2 in wide and 1-11/16 in tall on the Model Y, and it recommends Yakima's 23H adapters over the 39H on Tesla's aero bars for other carriers. Aftermarket bars vary in profile, so compare them with the box's clamp limits before buying."),
 ("Can I open the glass roof area or use the car normally with a box on?",
  "The Model 3's glass roof doesn't open, so there is no sunroof path to worry about. What changes is height and noise. Add the bars and box height to the car before entering a garage or parking structure, and expect more wind noise in a quiet EV cabin. Fixed-point bars and quick-release box mounts come off in minutes, which is the best fix for both noise and range."),
]

ARTICLE = {
 "dek": "Six rooftop boxes from Thule, Yakima, INNO, Rhino-Rack and SportRack matched to the Model 3's glass roof, fixed mounting points and short 28 in crossbar spread. For each one we list volume, length, height, weight and spread range, and what those numbers mean for Tesla's 150 lb rating, trunk-lid clearance and range, on 2017–2023 cars and the 2024 Highland.",
 "author": "jake-morrison",
 "reviewed": "2026-10-04",
 "method": "We did not mount these boxes ourselves. We ranked them on the makers' published specs (Thule, Yakima, Rhino-Rack and SportRack product pages, and etrailer's listing for the INNO box): volume, exterior dimensions, box weight, load rating, crossbar spread and warranty. We then matched those numbers to the 150 lb load rating the Tesla Shop gives Tesla's own Model 3 Roof Rack, the 28 in factory crossbar spread cited by etrailer's experts, the sedan's trunk lid and the range cost published by fueleconomy.gov. We reopened Tesla's Model 3 owner's manual and the Tesla Shop on October 4, 2026 for the wording on roof racks, roof load and accessory carriers. Prices were checked in September 2026; Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Bars first, on fixed points.** The Model 3 has a glass roof and no rails. Bars bolt into fixed points under the trim; Tesla's rack fits all Model 3, and aftermarket bars split 2017–2023 and Highland. Tesla's manual says to use 'only roof rack systems that have been approved by Tesla'. We could not confirm whether Tesla approves any aftermarket bars, so ask Tesla.",
  "**150 lb is the figure to plan around.** It is the Tesla Shop's load rating for Tesla's own Model 3 rack, with a 495 lb static load limit. The owner's manual prints no roof load. Bars, box and gear all count, so a light box matters more here than on an SUV.",
  "**The spread is short: 28 in.** etrailer cites 28 in for the factory rack. The SkyBox 16, Wedge 660 and MasterFit 440 ranges include it; the DeepSpace 10 (32 in minimum) does not.",
  "**Short boxes suit a sedan roof.** With bars only 28 in apart, a long box overhangs front and rear. The 68.9 in Pulse 2 M and 63 in Vista XL leave the most trunk-lid margin.",
  "**Range is the running cost.** fueleconomy.gov puts rooftop boxes at 6–17% worse on the highway and 10–25% at 65–75 mph. Take the box off between trips.",
 ],
 "top_picks": [
  {"asin": "B0G8C5LHQ5", "role": "Best overall", "why": "Thule Pulse 2 M: 31 lb, 68.9 in long, 14 cu ft; leaves the most of Tesla's 150 lb"},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "why": "INNO Wedge 660: 11 in tall, 24–39 in spread covers 28 in"},
  {"asin": "B001PUZXGK", "role": "Best 16 cu ft", "why": "Yakima SkyBox 16: 15 in tall, 24–34.5 in spread, $599 on sale"},
  {"asin": "B07B4P7WYX", "role": "Best mid-weight", "why": "Rhino-Rack MasterFit 440: 15.5 cu ft at 38.6 lb, 5-year warranty"},
  {"asin": "B00BCLL8C0", "role": "Best budget", "why": "SportRack Vista XL: 18 cu ft in 63 in for $449.95; 27-7/8 in position"},
 ],
 "fit_table": {
  "caption": "Model 3 roof setups (what you need before any box goes on)",
  "head": ["Body", "Build", "Crossbars", "Box notes"],
  "rows": [
   ["Original Model 3", "Builds to Oct 2023 (2023.10), per Tesstudio and TESEVO", "Tesla rack, or aftermarket bars listed 2017–2023", "Spread about 28 in (etrailer, factory rack); 150 lb rack rating (Tesla Shop)"],
   ["Highland refresh", "Builds from Nov 2023 (2023.11), per Tesstudio; North American orders from January 10, 2024, per Wikipedia", "Tesla rack, or bars listed for Highland / 2024+", "Same boxes; confirm the bars' spread and check the door-jamb build date"],
   ["All Model 3, Tesla rack", "2017–2026", "Tesla Model 3 Roof Rack ($400, 150 lb load rating, 495 lb static load limit)", "T-slots for cargo box hardware"],
   ["All Model 3", "Glass roof, no opening panel", "Fixed mounting points; no rail or gutter clamps", "No sunroof path; watch garage height and trunk lid"],
  ],
 },
 "look_for": [
  {"h": "Crossbar spread: the 28 in number",
   "body": "etrailer's product experts give the factory Model 3 roof rack a crossbar spread of 28 in. That is short, and it rules some boxes in and others out. The Yakima SkyBox 16 (24–34.5 in), the INNO Wedge 660 (24–39 in, per etrailer), the Rhino-Rack MasterFit 440 (620–930 mm, about 24.4–36.6 in) and the Yakima GrandTour 16 (24–36 in) all cover it. The SportRack Vista XL mounts at 25-7/8, 27-7/8 or 29-7/8 in, so its middle position is closest. The Yakima DeepSpace 10 needs at least 32 in and won't work. Thule doesn't publish a spread for the Pulse 2 M or Force 3 L, so confirm with its fit guide."},
  {"h": "Tesla's 150 lb rating after bars and box",
   "body": "The Tesla Shop gives Tesla's own Model 3 rack a 150 lb load rating and a 495 lb static load limit. The owner's manual prints no roof load, so that rack rating is the figure to plan around. Everything above the roof counts against the 150 lb: the bars, the box and what you pack. The boxes here weigh 31 lb (Pulse 2 M) to 47 lb (SkyBox 16); SportRack doesn't publish the Vista XL's weight. After a set of bars, that leaves about 90–115 lb for gear, less than on most SUVs. Pack sleeping bags, jackets and soft duffels up top and keep dense items in the trunk and frunk. A box rated at 165 lb doesn't change that."},
  {"h": "Box length vs the sedan roof and trunk lid",
   "body": "With the bars only 28 in apart, most of any box hangs past them. A 68.9 in Pulse 2 M overhangs about 41 in in total, and an 81 in SkyBox 16 about 53 in, split between the front and the rear. Too far forward and the nose sits over the windshield; too far back and the tail overhangs the rear glass, where the open trunk lid rises. Center the box, check the gap at both ends, and open the trunk slowly the first time. The 63 in Vista XL and 68.9 in Pulse 2 M are the easiest to place on this roof."},
  {"h": "Range, shape and wind noise",
   "body": "Tesla publishes no range figure for a roof box. fueleconomy.gov says a large, blunt rooftop cargo box can cut fuel economy about 2–8% in the city, 6–17% on the highway and 10–25% at 65–75 mph, and an EV pays for drag the same way. Shape is the part you control. The INNO Wedge 660 is 11 in tall and the SkyBox 16 is 15 in, both low for their volume. The Model 3's cabin is quiet, so wind noise is easy to hear. Mount the box level and centered, and remove it between trips."},
  {"h": "Clamp fit on Tesla-style T-slot bars",
   "body": "Tesla's Model 3 rack uses T-slot aluminum bars and says the slots take cargo boxes. Most boxes here clamp around the bar instead, so the bar's width and height matter. etrailer notes Yakima GrandTour boxes fit Tesla bars up to 3-1/2 in wide and 1-11/16 in tall on the Model Y, and INNO's Wedge 660 fits round, square, aero, elliptical and most factory crossbars, per etrailer. Aftermarket Model 3 bars come in several profiles, so measure yours and check the box's clamp range before you order."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbar spread", "A range that includes 28 in (SkyBox 16, Wedge 660, MasterFit 440)", "Boxes with a 32 in+ minimum, such as the DeepSpace 10"],
   ["Box weight", "Under 40 lb to save Tesla's 150 lb for gear (Pulse 2 M 31 lb, MasterFit 38.6 lb)", "Heavy boxes that leave under 100 lb for cargo"],
   ["Length", "Under about 77 in on a 28 in spread", "Long ski boxes that overhang the windshield or trunk lid"],
   ["Height / shape", "Low, tapered boxes (Wedge 660 11 in, SkyBox 16 15 in)", "Tall, blunt boxes left on all year"],
   ["Clamp fit", "Clamps rated for your bar's width and height", "Assuming a clamp fits an aero T-slot bar without checking"],
   ["Opening", "Dual-side, so you load from the curb", "Single-side boxes that open toward traffic"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Model 3 (makers' published specs; INNO and SportRack mounting per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Works at 28 in?"],
  "rows": [
   ["SportRack Vista XL", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed at 25-7/8, 27-7/8 or 29-7/8 in", "27-7/8 in is closest; confirm"],
   ["Thule Pulse 2 M", "14 cu ft", "68.9 × 32.1 × 16.6 in", "31 lb", "Not published", "Confirm with Thule"],
   ["Rhino-Rack MasterFit 440", "15.5 cu ft", "76 × 32 × 17 in", "38.6 lb", "About 24.4–36.6 in", "Yes"],
   ["Thule Force 3 L", "16 cu ft", "76.8 × 33.3 × 16.8 in", "43 lb", "Not published", "Confirm with Thule"],
   ["INNO Wedge 660", "11 cu ft", "80 × 33 × 11 in", "42 lb", "24–39 in", "Yes"],
   ["Yakima SkyBox 16", "16 cu ft", "81 × 36 × 15 in", "47 lb", "24–34.5 in", "Yes; long overhang"],
   ["Yakima DeepSpace 10 (not a pick)", "10 cu ft", "60 × 23 × 16 in", "30.2 lb", "32–46 in", "No"],
  ],
 },
 "picks": [
  {"asin": "B0G8C5LHQ5", "role": "Best overall", "price": "$699.95",
   "pros": ["31 lb, leaving the most of Tesla's 150 lb for gear", "68.9 in long, easy to center on a 28 in spread", "165 lb (75 kg) box rating", "DualSide opening; PowerClick mounts with a torque indicator", "14 cu ft covers a weekend's luggage"],
   "cons": ["Skis only up to 155 cm", "16.6 in tall, taller than the INNO or SkyBox", "Crossbar spread not published; confirm with Thule"],
   "body": "On a Model 3, the two numbers that decide a box are 150 lb and 28 in, and the Thule Pulse 2 M handles both better than anything else here. Thule lists it at 68.9 x 32.1 x 16.6 in with 14 cu ft (400 L), a 31 lb box weight and a 165 lb (75 kg) maximum load. It opens from both sides, locks centrally and clamps on with PowerClick mounts whose torque indicator shows when each clamp is tight. Thule and REI both list it at $699.95.\n\nAgainst Tesla's 150 lb rating, 31 lb of box leaves about 119 lb before you subtract your bars, roughly 16 lb more than the SkyBox 16 allows. Its length matters just as much: on bars 28 in apart, a 68.9 in box overhangs about 41 in in total, so it can sit centered without crowding the windshield or the trunk lid. The limits are ski length, just 155 cm, and height, 16.6 in, which adds more frontal area than the INNO Wedge 660. Thule's page doesn't list a crossbar spread, so confirm the Pulse 2 M against a 28 in spread in Thule's fit guide before ordering.",
   "who": "Model 3 owners who want the lightest, shortest locking box for road-trip luggage.",
   "specs": [["Volume", "14 cu ft (400 L)"], ["Exterior", "68.9 × 32.1 × 16.6 in"], ["Box weight", "31 lb"], ["Max load", "165 lb (75 kg)"], ["Ski length", "Up to 155 cm"], ["Mount / lock", "PowerClick / central locking"], ["Crossbar spread", "Not published; confirm"], ["Price", "$699.95 (Thule, REI)"]]},
  {"asin": "B06VX9L59C", "role": "Lowest profile", "price": "$864.97",
   "pros": ["Only 11 in tall, the lowest box here", "24–39 in spread comfortably covers 28 in", "110 lb weight capacity", "Fits round, square, aero, elliptical and most factory bars, per etrailer", "Limited lifetime warranty, per etrailer"],
   "cons": ["11 cu ft for $864.97", "80 in long, so it overhangs a 28 in spread by about 52 in", "42 lb, heavier than the Pulse 2 M"],
   "body": "If range and wind noise worry you more than capacity, the INNO Wedge 660 is the box to look at. etrailer lists it at 80 x 33 x 11 in with 11 cu ft, a 42 lb box weight, a 110 lb weight capacity and a 24–39 in crossbar spread. At 11 in tall it is 4 in lower than the SkyBox 16 and 5.6 in lower than the Pulse 2 M, so it adds the least frontal area of any box here. The dual-side lid opens with push buttons, keyed locks on each side secure both cargo and mounts, and INNO's Memory Mount hardware needs a one-time setup for quick repeat installs. etrailer lists it at $864.97 with a limited lifetime warranty.\n\nThe 28 in spread sits comfortably inside its range, and etrailer says it fits aero and most factory crossbars, but check the clamp against your bar's profile. The catch is length. At 80 in, it overhangs 28 in bars by about 52 in in total, so center it carefully and check the windshield and the trunk lid. Skis up to 182 cm fit diagonally. At 42 lb it leaves about 108 lb of Tesla's 150 lb before bars.",
   "who": "Highway-heavy Model 3 drivers who want the lowest, quietest-looking box and mostly carry skis and soft bags.",
   "specs": [["Volume", "11 cu ft"], ["Exterior", "80 × 33 × 11 in"], ["Box weight", "42 lb"], ["Weight capacity", "110 lb"], ["Crossbar spread", "24–39 in"], ["Ski length", "Up to 182 cm (diagonal)"], ["Opening", "Dual-side, push-button"], ["Warranty", "Limited lifetime (etrailer)"]]},
  {"asin": "B001PUZXGK", "role": "Best 16 cu ft", "price": "$599",
   "pros": ["$599 on sale at Yakima (regular $749)", "16 cu ft at only 15 in tall", "24–34.5 in spread covers 28 in", "Dual-side opening; skis up to 185 cm", "Limited lifetime warranty"],
   "cons": ["47 lb, the heaviest pick here", "81 in long: about 53 in of overhang on 28 in bars", "36 in wide, filling most of the bar"],
   "body": "The Yakima SkyBox 16 Carbonite is the full-size option that still makes sense on a Model 3. Yakima lists it at 81 x 36 x 15 in, 16 cu ft and 47 lb, with dual-sided opening, room for skis and boards up to 185 cm and a limited lifetime warranty. Its 24–34.5 in crossbar spread includes the Model 3's 28 in with room to spare, and at 15 in it is low for a 16 cu ft box, which helps with drag and garage clearance. It was on sale for $599, down from $749, on Yakima's page when we checked.\n\nThe costs are weight and length. At 47 lb it leaves about 103 lb of Tesla's 150 lb before your bars, so pack light and bulky rather than dense. At 81 in it overhangs 28 in bars by about 53 in in total, the most of any pick here, so it needs careful centering: keep the nose off the windshield and check the trunk lid's clearance at the back. For family trips with skis or a lot of soft luggage, it is the best value 16 cu ft box for this car.",
   "who": "Model 3 owners who need a full 16 cu ft for skis or family luggage and will pack light.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "81 × 36 × 15 in"], ["Box weight", "47 lb"], ["Crossbar spread", "24–34.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Warranty", "Limited lifetime"], ["Price", "$599 sale (Yakima)"]]},
  {"asin": "B07B4P7WYX", "role": "Best mid-weight", "price": "Not listed by Rhino-Rack; see listing",
   "pros": ["15.5 cu ft (440 L) at 38.6 lb", "76 in long, 5 in shorter than the SkyBox 16", "620–930 mm spread (about 24.4–36.6 in) covers 28 in", "Dual-side opening, 3 locking points", "5-year warranty"],
   "cons": ["No US price on Rhino-Rack's page; confirm on the listing", "130 km/h (about 80 mph) maximum speed with the box, per the instructions", "17 in tall"],
   "body": "The Rhino-Rack MasterFit 440 sits between the light Pulse 2 M and the full-size SkyBox 16. Rhino-Rack lists it at 76 x 32 x 17 in with 440 L (15.5 cu ft), a 38.6 lb box weight, a 75 kg maximum load, dual-side opening with keyed locks on both sides, three locking points, two load straps and a 5-year warranty. Its instructions give a crossbar spacing of 620 mm minimum to 930 mm maximum for this size, about 24.4 to 36.6 in, which includes the Model 3's 28 in.\n\nOn Tesla's 150 lb rating, 38.6 lb of box leaves about 111 lb before bars, nearly as much as the Pulse 2 M while holding 1.5 cu ft more. At 76 in it overhangs 28 in bars by about 48 in, so center it and check the trunk lid. The instructions also set a maximum speed of 130 km/h with the box fitted. Rhino-Rack's US page shows no price, so check the listing, and confirm its mounting hardware suits your bars' profile, especially Tesla-style aero T-slot bars.",
   "who": "Buyers who want close to 16 cu ft without going over 40 lb, and a published warranty.",
   "specs": [["Volume", "15.5 cu ft (440 L)"], ["Exterior", "76 × 32 × 17 in"], ["Box weight", "38.6 lb"], ["Max load", "75 kg (165 lb)"], ["Crossbar spread", "620–930 mm (about 24.4–36.6 in)"], ["Opening / locks", "Dual-side; 3 locking points"], ["Max speed", "130 km/h (instructions)"], ["Warranty", "5 years"]]},
  {"asin": "B0DYQ4T5ZZ", "role": "Best premium", "price": "$879.95",
   "pros": ["16 cu ft in 76.8 in", "43 lb, 4 lb lighter than the SkyBox 16", "165 lb box rating", "DualSide opening and PowerClick mounts", "Thule publishes a front-clearance figure (>50 5/8 in)"],
   "cons": ["$879.95, the priciest box here", "Skis only up to 175 cm", "Crossbar spread and warranty not on the product page; confirm"],
   "body": "The Thule Force 3 L is the premium way to get a full 16 cu ft onto a Model 3 without the SkyBox's length. Thule lists it at 76.8 x 33.3 x 16.8 in, 16 cu ft (450 L), 43 lb and a 165 lb maximum load, with DualSide opening and PowerClick quick-mount clamps that include a torque indicator, for $879.95. That makes it 4.2 in shorter and 4 lb lighter than the SkyBox 16 for the same volume. On bars 28 in apart it overhangs about 49 in in total, which is easier to center without reaching over the windshield or the trunk lid.\n\nThe trade-offs are price, ski length and a missing number. It costs $280.95 more than the SkyBox 16 on sale, takes skis only to 175 cm, and Thule's page doesn't list a crossbar spread or warranty terms. Confirm the spread against the Model 3's 28 in in Thule's fit guide before you buy. Against Tesla's 150 lb rating it leaves about 107 lb before bars.",
   "who": "Model 3 owners who want the full 16 cu ft in a shorter, lighter shell and will pay for it.",
   "specs": [["Volume", "16 cu ft (450 L)"], ["Exterior", "76.8 × 33.3 × 16.8 in"], ["Box weight", "43 lb"], ["Max load", "165 lb"], ["Ski length", "Up to 175 cm"], ["Mount", "PowerClick with torque indicator"], ["Crossbar spread / warranty", "Not published; confirm"], ["Price", "$879.95 (Thule)"]]},
  {"asin": "B00BCLL8C0", "role": "Best budget", "price": "$449.95",
   "pros": ["18 cu ft for $449.95, the most volume and lowest price here", "63 in long, the shortest box here", "27-7/8 in mounting position is close to the 28 in spread", "Tool-free mounting with a lock", "Fits square, round and most factory bars, per SportRack"],
   "cons": ["Rear-opening lid: load from behind the car", "19 in tall and 38 in wide, the most frontal area here", "Box weight and load rating not published; confirm"],
   "body": "The SportRack Vista XL is the budget choice, and on a Model 3 its short shape is a real advantage. SportRack lists it at 63 x 38 x 19 in with 18 cu ft, UV-resistant ABS, tool-free mounting hardware and a lock, for $449.95. etrailer's expert gives three fixed mounting positions, 25-7/8, 27-7/8 and 29-7/8 in center to center, and the middle one sits within an eighth of an inch of the Model 3's 28 in spread. At 63 in, it overhangs 28 in bars by only about 35 in, the least of any box here.\n\nThe drawbacks are shape and missing numbers. At 19 in tall and 38 in wide it is the bluntest box on this page, and fueleconomy.gov's figures for large, blunt boxes are the ones that apply, so expect a bigger range hit at highway speed. The rear-opening lid means loading from behind the car, over the rear glass. SportRack doesn't publish a box weight or a load rating, so confirm both on the listing and check whether its clamps fit your bar profile before you mount it.",
   "who": "Budget buyers who want the most space for the money and mostly drive short trips.",
   "specs": [["Volume", "18 cu ft"], ["Exterior", "63 × 38 × 19 in"], ["Opening", "Rear"], ["Mounting positions", "25-7/8, 27-7/8 or 29-7/8 in (etrailer)"], ["Hardware", "Tool-free; lock included"], ["Material", "UV-resistant ABS"], ["Box weight / max load", "Not published; confirm"], ["Price", "$449.95 (SportRack)"]]},
 ],
 "install": [
  "Fit bars listed for your build (Tesla's rack for all Model 3, or aftermarket bars for 2017–2023.10 or Highland) into the fixed points under the roof trim, and torque them to spec. Tesla's manual says to use only roof rack systems approved by Tesla, so ask Tesla about aftermarket bars first.",
  "Measure the spread center to center (about 28 in on the factory rack) and confirm it sits inside the box's range, or on the Vista XL's 27-7/8 in position.",
  "Check that the box clamps fit your bar's width and height, since Tesla-style bars are aero T-slot profiles.",
  "With a helper, set the box on the bars and center it front to back and side to side, keeping the nose clear of the windshield.",
  "Tighten the clamps to the box maker's spec, lock the box, pull on each corner, then open the trunk slowly and check the gap at the tail.",
  "Load light, bulky gear, keep bars + box + gear under 150 lb, and re-check the clamps after the first drive.",
 ],
 "avoid": [
  {"h": "A box that can't reach 28 in", "body": "The Yakima DeepSpace 10 needs at least 32 in between bars. Check every box's minimum spread against the Model 3's 28 in before ordering."},
  {"h": "Loading to the box's 165 lb rating", "body": "Tesla's Model 3 rack is rated at 150 lb, and that includes bars and box. After a 31–47 lb box and the bars, only about 90–115 lb is left for gear."},
  {"h": "Long boxes pushed back to clear the windshield", "body": "On a 28 in spread, an 80 in box overhangs about 52 in. Pushing it back to clear the windshield moves the tail over the rear glass, toward the trunk lid."},
  {"h": "Leaving the box on between trips", "body": "fueleconomy.gov puts rooftop boxes at 10–25% worse efficiency at 65–75 mph. On an EV that is range, so take the box off when you don't need it."},
 ],
 "verdict": {
  "thesis": "Fit bars for your build, then choose the Thule Pulse 2 M for the best balance of weight and length, the INNO Wedge 660 for the lowest profile, or the Yakima SkyBox 16 if you need 16 cu ft.",
  "body": "On the Model 3, a cargo box has to work within three limits: the 150 lb rating Tesla gives its own rack, a 28 in crossbar spread and a sedan roof with a trunk lid behind it. The Thule Pulse 2 M fits all three best, at 31 lb and 68.9 in. The INNO Wedge 660 is the low, 11 in tall option for highway drivers, the Rhino-Rack MasterFit 440 carries 15.5 cu ft at 38.6 lb, and the SkyBox 16 and Force 3 L give the full 16 cu ft if you pack light. The SportRack Vista XL is the budget pick, and its 27-7/8 in position lines up with the car's spread.\n\nBefore any box, you need crossbars for your build: see the Model 3 roof rack page for fixed-point bars, including Highland-specific sets. Tesla's manual says you must use 'only roof rack systems that have been approved by Tesla'. We could not confirm whether Tesla approves any aftermarket bars, so ask Tesla. For bikes, a trailer hitch with a bike rack costs less efficiency than the roof on fueleconomy.gov's figures for gas vehicles, but Tesla's manual says: 'Do not attempt to install an accessory carrier on Model 3 that is not equipped with the towing package.' Ask Tesla before fitting an aftermarket one. All-weather floor mats protect the cabin on ski trips. Owners of the 2020–2026 Model Y have a taller roof, a 165 lb rating and a wider spread. The vehicle hub lists every fit-checked accessory for the Model 3.",
 },
 "sources": [
  ["Tesla Model 3 Roof Rack: 150 lb / 495 lb ratings (Tesla Shop)", "https://shop.tesla.com/product/model-3-roof-rack"],
  ["Model 3 Owner's Manual: Vehicle Loading, roof racks (Tesla)", "https://www.tesla.com/ownersmanual/model3/en_us/GUID-877ACE2D-B62F-4596-A6AD-A74F7905741C.html"],
  ["2017–2023 Model 3 Owner's Manual: Vehicle Loading (Tesla)", "https://www.tesla.com/ownersmanual/2017_2023_model3/en_us/GUID-877ACE2D-B62F-4596-A6AD-A74F7905741C.html"],
  ["Model 3 Owner's Manual: Towing and Accessories (Tesla)", "https://www.tesla.com/ownersmanual/model3/en_us/GUID-BD9A38D5-4410-45A3-8337-BDF7342750F3.html"],
  ["Model 3 Tow Package (Tesla Shop)", "https://shop.tesla.com/product/model-3-tow-package"],
  ["Tesla Model 3 (Highland refresh dates)", "https://en.wikipedia.org/wiki/Tesla_Model_3"],
  ["Model 3 28 in crossbar spread and Yakima box fit (etrailer expert answers)", "https://www.etrailer.com/answers.aspx?AnswerMake=Tesla&Manufacturer=Yakima&Filter=fit"],
  ["Tesstudio roof rack variants, Model 3 and Highland (Tesstudio)", "https://www.tesstudio.com/products/tesstudio-roof-rack-for-tesla-model-3-highland-model-y-model-y-juniper-set-of-2"],
  ["Thule Pulse 2 M (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-pulse-2-m-_-610250"],
  ["Thule Pulse 2 M price and weight (REI)", "https://www.rei.com/product/C07625/thule-pulse-2-m-roof-box"],
  ["Thule Force 3 L (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-force-3-l-_-645750"],
  ["Yakima SkyBox 16 Carbonite (Yakima)", "https://yakima.com/collections/roof-boxes/products/skybox-16-carbonite-2014-2023"],
  ["INNO Wedge 660 specs (etrailer)", "https://www.etrailer.com/Roof-Box/Inno/INBRM660BK.html"],
  ["Rhino-Rack MasterFit Roof Box 440L (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-racks/roof-boxes/roof-boxes/masterfit-roof-box-440l-black-_rmft440"],
  ["Rhino-Rack MasterFit instructions: load, spacing, speed (Rhino-Rack)", "https://assets.rhinorack.com/Instructions/Accessories/RMFT-Masterfit.pdf"],
  ["SportRack Vista XL (SportRack) and mounting positions (etrailer)", "https://www.sportrack.com/product/vista-xl-cargo-box/"],
  ["Yakima DeepSpace 10 spread range (Yakima)", "https://yakima.com/collections/roof-boxes/products/deepspace-10"],
  ["Cargo box and rear carrier fuel economy impact (fueleconomy.gov)", "https://www.fueleconomy.gov/feg/driveHabits.jsp"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Model 3 roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B0G8C5LHQ5","Thule Pulse 2 M Roof-Mounted Box, 14 Cubic Ft, Dual-Side Opening","Thule","$650–$750",{},"31 lb, 68.9 in; confirm spread covers the Model 3's 28 in."),
 ("B06VX9L59C","INNO BRM660BK Wedge Cargo Box - 11 Cubic FT (Gloss Black)","INNO","$800–$900",{},"11 in tall, 24-39 in spread; confirm clamp fit on T-slot bars."),
 ("B001PUZXGK","Yakima SkyBox 16 Carbonite Rooftop Cargo Box, 16 cu ft (81 in long)","Yakima","$550–$750",{},"24-34.5 in spread; long overhang, confirm trunk-lid gap."),
 ("B07B4P7WYX","Rhino-Rack MasterFit Roof Box 440L (Black)","Rhino-Rack","See listing",{},"38.6 lb, about 24.4-36.6 in spread; confirm price and bar fit."),
 ("B0DYQ4T5ZZ","Thule Force 3 L Rooftop Cargo Box, 16 cu ft (76.8 in long)","Thule","$800–$950",{},"43 lb; confirm spread covers 28 in with Thule."),
 ("B00BCLL8C0","SportRack Vista XL Rear Opening Cargo Box, 18 cu ft, Black","SportRack","$400–$500",{},"27-7/8 in position near 28 in; confirm weight, rating and clamp fit."),
]
