"""Long-form article — Best Floor Mats & Liners for 2020–2026 Tesla Model Y (pre-refresh and Juniper).
No invented hands-on testing: fit facts from listing titles in FITS, specs from retailer pages in sources (checked 2026-09-24).
"""

KEY = ("tesla", "model-y", "2020-present", "floor-mats")

TITLE = "Best Floor Mats for 2020–2026 Tesla Model Y: 6 Sets Split by Pre-Refresh vs Juniper"
META = ("Six Model Y all-weather mat sets from 3D MAXpider, TripleAliners, 3W, Foronetry and Autocessking, split by "
        "2020–2024 vs Juniper, 5-seat vs 7-seat and Standard trim.")

FAQ = [
 ("How do I know if my Model Y is a Juniper?",
  "The refreshed Model Y, nicknamed Juniper, has a full-width light bar across the front and rear, a rear-seat touchscreen and ambient lighting. Listings on this page call it the 2025–2026 Model Y Juniper. If your car has the older front with separate headlights and no light bar, it's a pre-refresh car and needs a 2020–2024 set."),
 ("Do pre-refresh Model Y mats fit a Juniper?",
  "Don't assume so. Mat makers sell separate sets, and several listings on this page say 'not Juniper' or 'Juniper only'. The trunk and interior trim changed with the refresh. 3D MAXpider, for example, sells a Kagu set for the 2021–2025 Model Y and a separate one for the 2026 Juniper. Match the listing to your car's generation."),
 ("What about the 7-seat Model Y?",
  "Tesla offered a seven-seat option on the pre-refresh Model Y. Its second-row floor and cargo area differ from the five-seat car, and most sets on this page are listed for five seats only. 3D MAXpider sells a separate third-row mat for the 7-seat 2021–2025 Model Y. If you have seven seats, look for a set that names it."),
 ("What is the Model Y 'Standard' trim and does it matter?",
  "Tesla added a lower-priced Standard version of the refreshed Model Y. Some Juniper listings, including Foronetry's and TripleAliners', say not for the Standard trim, which suggests its interior or trunk differs. If you have the Standard, ask the seller before ordering."),
 ("Why do Model Y kits have so many pieces?",
  "The Model Y has a lot of zones to protect: front footwells, a large rear floor, the frunk, the main trunk floor, the lower trunk well, the seatbacks when folded and the rear bumper sill. Kits range from six to eleven pieces depending on how many of those they include. Autocessking's 11-piece and TripleAliners' 10-piece are the most complete here."),
 ("Is 3D MAXpider worth paying more for?",
  "Retailer descriptions of 3D MAXpider's Kagu line describe a three-layer construction with a carbon-fiber-textured surface and a patented grip underside. It also separates its pre-refresh and Juniper sets clearly, which reduces the risk of a wrong fit. Budget kits cover more zones for less money but publish fewer specs."),
 ("Will mats slide on the Model Y's flat floor?",
  "A mat with a grippy backing or retention points shouldn't. The flat floor gives a mat nothing to wedge into, so grip matters. Seat the driver mat carefully and check brake and accelerator travel after installing."),
 ("Do I need a bumper guard piece?",
  "If you load heavy gear or a dog over the rear sill, a bumper guard protects the paint and trim. TripleAliners' Juniper kit includes one. Otherwise, it's optional."),
 ("How do I clean the mats?",
  "Pull them out, rinse and scrub with mild soap, and dry before reinstalling. The lower trunk well liner collects water, so empty and dry it after wet trips. Skip silicone protectants."),
 ("Do Model 3 mats fit the Model Y?",
  "No. The Model Y is taller with a different floor, trunk and frunk. Buy a set that names the Model Y and your generation."),
 ("Does Tesla sell its own Model Y all-weather liners?",
  "Tesla sells all-weather interior liners for the Model Y through its own shop, typically split by generation like the aftermarket sets. They're designed for the car and fit well, but they aren't sold through the Amazon listings this page covers. If you prefer factory parts, check Tesla's shop for your generation and compare the pieces included with the kits here."),
]

ARTICLE = {
 "dek": "Six all-weather mat sets for the Model Y, from 3D MAXpider's Kagu to 11-piece kits that cover every surface. The fit decision is generational: pre-refresh 2020–2024 cars and the 2025+ Juniper take different sets, and the 7-seat and Standard versions add their own exclusions.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these mats ourselves. We ranked them on the fit each listing states for the Model Y (generation, seating, trim), on the pieces included, on published maker or retailer specs and on coverage in listing photos. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Pre-refresh or Juniper first.** Sets are split, and several listings exclude one or the other.",
  "**5-seat is the default.** 7-seat pre-refresh cars need a set that names them.",
  "**Standard trim can differ.** Some Juniper listings exclude it.",
  "**Piece counts vary from 6 to 11.** Frunk, trunk well, seatbacks and bumper guard are the variables.",
  "**3D MAXpider separates generations clearly.** Different Kagu sets for 2021–2025 and 2026 Juniper.",
 ],
 "top_picks": [
  {"asin": "B0936RH9SH", "role": "Best pre-refresh", "why": "3D MAXpider Kagu full set, Model Y 2021–2025 (pre-Juniper)"},
  {"asin": "B0F8PPNW49", "role": "Best Juniper", "why": "3D MAXpider Kagu full set for the Juniper"},
  {"asin": "B0DZGGYTBC", "role": "Most complete Juniper kit", "why": "TripleAliners 10-piece incl. frunk, trunk, backrest and bumper guard"},
  {"asin": "B0BRJQ2C7V", "role": "Best pre-refresh value", "why": "3W 6-piece TPE with cargo and frunk liners, 2020–2024 5-seat"},
  {"asin": "B0H251XWBW", "role": "Best 11-piece", "why": "Autocessking 11-piece all-weather kit, Juniper (not Standard)"},
 ],
 "fit_table": {
  "caption": "Model Y mats by generation and version",
  "head": ["Version", "How to tell", "What to buy"],
  "rows": [
   ["Pre-refresh 5-seat (2020–2024)", "Separate headlights, no light bar", "3D MAXpider 2021–2025, 3W, Foronetry 2021–2024, WEIZE"],
   ["Pre-refresh 7-seat", "Third-row seat", "Sets naming 7-seat; 3D MAXpider third-row mat"],
   ["Juniper (2025–2026)", "Full-width light bar, rear screen", "3D MAXpider Juniper, TripleAliners, Foronetry, Autocessking"],
   ["Juniper Standard", "Lower-priced trim", "Several Juniper kits exclude it; confirm"],
  ],
 },
 "look_for": [
  {"h": "Pre-refresh or Juniper",
   "body": "The refreshed Model Y, which listings call Juniper, changed the interior and trunk trim enough that mat makers sell separate sets. The listings on this page are explicit: 3W, Foronetry's 9-piece and WEIZE are for 2020–2024 pre-refresh cars; Foronetry's 8-piece, TripleAliners, Autocessking and 3D MAXpider's Juniper set are for the Juniper. The quickest way to tell is the light bar: a full-width light strip across the front and rear means Juniper. Don't rely on the model year alone around the changeover, because some 2025 cars were built before and after it."},
  {"h": "Five seats, seven seats or Standard",
   "body": "Tesla offered a seven-seat option on the pre-refresh Model Y, and its second-row floor and cargo area differ. Most sets here are listed for five seats. 3D MAXpider sells a separate third-row mat for the 7-seat 2021–2025 car. On the Juniper side, some listings exclude the lower-priced Standard version, which suggests its interior or trunk differs. If you have either of these, confirm with the seller before ordering."},
  {"h": "Which zones to cover",
   "body": "The Model Y has an unusually large cargo area, a deep lower trunk well, a frunk, and a rear sill that takes scrapes when loading. Kits vary accordingly: 3W's 6-piece covers the floor, cargo and frunk; TripleAliners' 10-piece adds the rear lower well, backrest and a bumper guard; Autocessking's 11-piece covers even more. If you fold the rear seats for bikes or a dog crate, backrest pieces protect the carpeted seatbacks. Decide what you actually use before paying for eleven pieces."},
  {"h": "Grip and edges",
   "body": "The Model Y's floor is flat, so a mat has nothing to wedge into. Grip comes from the underside and any retention points. Retailer descriptions of 3D MAXpider's Kagu line mention a patented underside that grabs the carpet. Edges matter in wet climates: a raised lip at each footwell keeps water on the mat. Seat the driver mat carefully and check pedal travel before driving."},
  {"h": "Documentation",
   "body": "3D MAXpider is the best-documented brand here, with retailer descriptions of three-layer construction and a carbon-fiber-textured surface, plus separate part numbers by generation and row. 3W's maker is a TPE mat specialist in Taizhou, China. The other Tesla-focused brands (TripleAliners, Foronetry, Autocessking, WEIZE, TAPTES) publish few specs and no warranty terms we could check. They win on piece count and price."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "Pre-refresh or Juniper named", "Listings that don't say"],
   ["Seating", "5-seat or 7-seat named", "5-seat sets in a 7-seat car"],
   ["Trim", "Standard included or excluded", "Assuming Standard fits"],
   ["Coverage", "Zones you use", "Paying for pieces you won't use"],
   ["Grip", "Grippy backing or retention points", "Slick-backed mats"],
   ["Trunk well", "Liner with an edge", "Leaving the well bare"],
  ],
 },
 "types_table": {
  "caption": "Mat options for the Model Y",
  "head": ["Type", "Example", "Generation", "Pieces", "Price band"],
  "rows": [
   ["Premium 3-layer mats", "3D MAXpider Kagu", "Both (separate sets)", "Cabin", "$150–$230"],
   ["10–11 piece kits", "TripleAliners, Autocessking", "Juniper", "Cabin, frunk, trunk, backrest, bumper", "$150–$200"],
   ["8–9 piece kits", "Foronetry", "Both (separate sets)", "Cabin, frunk, trunk", "$130–$190"],
   ["6-piece TPE", "3W, WEIZE", "Pre-refresh", "Cabin, cargo, frunk", "$100–$160"],
  ],
 },
 "picks": [
  {"asin": "B0936RH9SH", "role": "Best pre-refresh", "price": "$150–$230",
   "pros": ["Full cabin set for the 2021–2025 Model Y", "Three-layer construction per retailer descriptions", "Carbon-fiber-textured surface", "Patented grip underside", "Separate third-row mat for 7-seat cars"],
   "cons": ["Frunk and trunk sold separately", "Costs more than multi-piece kits", "Confirm 2025 build (pre-refresh vs Juniper)"],
   "body": "3D MAXpider's Kagu full set is listed for the 2021–2025 Model Y, the pre-refresh car. Retailer descriptions of the Kagu line describe a three-layer construction, a carbon-fiber-textured surface with a soft, rubber-like finish and a patented underside that grips the carpet, which matters on the Model Y's flat floor.\n\nThe brand's catalog is its strength: it sells a separate Kagu set for the 2026 Juniper, separate front-row pieces and a third-row mat for the 7-seat pre-refresh car. That clarity reduces the risk of ordering the wrong generation. The texture also suits the Tesla cabin better than a ribbed mat.\n\nThe trade-off is coverage per dollar: the full set covers the cabin, not the frunk and trunk, which you buy separately. If your car is a 2025, check for the light bar before ordering; a 2025 Juniper needs the Juniper set. For a 2020 car, 3D MAXpider lists a separate 2020 set.",
   "who": "Pre-refresh owners who want the best-documented cabin mats.",
   "specs": [["Line", "3D MAXpider Kagu"], ["Fits", "2021–2025 Model Y (pre-refresh)"], ["Pieces", "Full cabin set"], ["Construction", "3-layer (retailer)"], ["7-seat", "Separate third-row mat"], ["2020 cars", "Separate 2020 set"]]},
  {"asin": "B0F8PPNW49", "role": "Best Juniper", "price": "$150–$230",
   "pros": ["Juniper-specific full cabin set", "Same Kagu construction and texture", "Patented grip underside", "Clear generation split", "Cabin-matching look"],
   "cons": ["Title names 2026 Juniper; confirm a 2025 Juniper", "Frunk and trunk sold separately", "Most expensive per piece"],
   "body": "3D MAXpider's Kagu full set for the Juniper is the refreshed-car counterpart to its pre-refresh set. It carries the same three-layer construction, carbon-fiber texture and grip underside described by retailers for the Kagu line.\n\nThe title names the 2026 Model Y Juniper. If your Juniper is registered as a 2025, confirm with the seller, since the refresh straddled model years. As with the pre-refresh set, the frunk and trunk liners are separate purchases.\n\nFor a new Juniper where you want the cabin to look finished and the fit to be well documented, it's the pick. If you want every surface covered for less money, TripleAliners' or Autocessking's kits cover more pieces.",
   "who": "Juniper owners who want the best-documented cabin mats.",
   "specs": [["Line", "3D MAXpider Kagu"], ["Fits", "Model Y Juniper (listed 2026; confirm 2025)"], ["Pieces", "Full cabin set"], ["Construction", "3-layer (retailer)"], ["Price band", "$150–$230"]]},
  {"asin": "B0DZGGYTBC", "role": "Most complete Juniper kit", "price": "$150–$200",
   "pros": ["10 pieces: floor, frunk, trunk, rear lower well, backrest, bumper guard", "Juniper-specific", "Bumper guard protects the rear sill", "Backrest pieces for folded seats", "One order for the whole car"],
   "cons": ["Not for the Standard trim", "Little maker documentation", "No published warranty"],
   "body": "TripleAliners' 10-piece kit is listed for the 2025–2026 Model Y Juniper, not the Standard trim. It covers the floor, frunk, trunk, rear lower well, backrest and a bumper guard, which is close to every surface in the car.\n\nThe bumper guard and backrest pieces are what set it apart. If you load bikes, a dog crate or heavy gear over the rear sill, the guard protects the paint and trim, and the backrests protect the carpeted seatbacks when the rear seats are folded.\n\nTripleAliners doesn't publish warranty terms we could check, so it competes on coverage and price. For a Juniper that hauls gear, it's the most complete single order here.",
   "who": "Juniper owners who haul gear and fold the rear seats.",
   "specs": [["Pieces", "10"], ["Covers", "Floor, frunk, trunk, rear lower, backrest, bumper guard"], ["Fits", "2025–2026 Model Y Juniper (not Standard)"], ["Material", "All-weather (per listing)"], ["Price band", "$150–$200"]]},
  {"asin": "B0BRJQ2C7V", "role": "Best pre-refresh value", "price": "$120–$160",
   "pros": ["6 pieces: floor, cargo and frunk liners", "TPE from a TPE-mat specialist", "Lists 2020–2024 5-seat", "Clear 'not Juniper' fit", "Covers the frunk"],
   "cons": ["5-seat only", "No backrest pieces", "No published warranty"],
   "body": "3W's 6-piece TPE set covers the floor, cargo area and frunk of 2020–2024 Model Y 5-seat cars, pre-Juniper. 3W's maker, Zhejiang Zhenya in Taizhou, China, specializes in TPE car and trunk mats.\n\nIt covers the zones most owners need, footwells, trunk and frunk, for noticeably less than 3D MAXpider's cabin set plus separate cargo pieces. It doesn't include backrest pieces, so if you fold the rear seats often, add seatback covers.\n\nThe clear 5-seat, pre-refresh fit makes it a safe order for a 2020–2024 car. Foronetry's 9-piece and WEIZE's 6-piece sets for the same cars are alternatives in our product list.",
   "who": "Pre-refresh 5-seat owners who want cabin, trunk and frunk covered.",
   "specs": [["Pieces", "6"], ["Covers", "Floor, cargo, frunk"], ["Fits", "2020–2024 Model Y 5-seat (not Juniper)"], ["Material", "TPE"], ["Price band", "$120–$160"]]},
  {"asin": "B0H251XWBW", "role": "Best 11-piece", "price": "$150–$200",
   "pros": ["11 pieces, the most here", "Juniper-specific", "Covers cabin and cargo zones", "All-weather material", "Good for heavy users"],
   "cons": ["Not for the Standard trim", "Little maker documentation", "More pieces than many owners need"],
   "body": "Autocessking's 11-piece kit is listed for the 2025–2026 Model Y Juniper, not the Standard trim. It has the highest piece count here, covering the cabin and cargo zones in detail.\n\nFor an owner who uses every part of the car, eleven pieces means fewer bare spots. For an owner who mostly drives solo, it's more than needed; a cabin set plus a trunk liner does the job for less.\n\nAutocessking publishes little beyond the listing. Compare its diagram with TripleAliners' 10-piece to see which zones each covers, and pick the one that matches how you use the car.",
   "who": "Juniper owners who want every zone covered.",
   "specs": [["Pieces", "11"], ["Covers", "Cabin + cargo zones"], ["Fits", "2025–2026 Model Y Juniper (not Standard)"], ["Material", "All-weather (per listing)"], ["Price band", "$150–$200"]]},
  {"asin": "B0GTS6R1N6", "role": "Best Juniper 8-piece", "price": "$140–$190",
   "pros": ["8 pieces: frunk, trunk, cargo and rear mats", "Juniper 5-seat", "Middle ground between cabin sets and 11-piece kits", "All-weather material", "Covers the frunk"],
   "cons": ["Not for Standard or 7-seat", "Little maker documentation", "No published warranty"],
   "body": "Foronetry's 8-piece set is listed for the 2025–2026 Model Y Juniper 5-seat, not the Standard trim or 7-seat. It covers the frunk, trunk, cargo area and rear mats.\n\nIt sits between 3D MAXpider's cabin-only set and the 10- and 11-piece kits. If you want the frunk and trunk covered but don't need backrest pieces or a bumper guard, it's a sensible choice.\n\nFor pre-refresh cars, Foronetry sells a separate 9-piece set for 2021–2024 5-seat Model Y, which is in our product list. Match the generation before ordering. Check the listing diagram for whether the rear lower trunk well is included; on the Model Y it's deep and collects water from wet gear.",
   "who": "Juniper 5-seat owners who want the essentials covered.",
   "specs": [["Pieces", "8"], ["Covers", "Frunk, trunk, cargo, rear mats"], ["Fits", "2025–2026 Model Y Juniper 5-seat (not Standard)"], ["Material", "All-weather (per listing)"], ["Price band", "$140–$190"]]},
 ],
 "install": [
  "Confirm your generation (light bar = Juniper), seating and trim.",
  "Remove any old mats and vacuum the cabin, frunk and trunk.",
  "Seat the driver mat, using retention points if present, and heel-test it toward the pedals.",
  "Fit the passenger and rear mats across the flat rear floor.",
  "Fit frunk, trunk, lower well, backrest and bumper pieces; close the frunk and liftgate.",
  "Press the brake and accelerator to the floor before driving.",
 ],
 "avoid": [
  {"h": "Wrong generation", "body": "Pre-refresh and Juniper sets aren't interchangeable."},
  {"h": "5-seat sets in a 7-seat car", "body": "The second row and cargo differ."},
  {"h": "Assuming Standard fits", "body": "Several Juniper kits exclude it."},
  {"h": "Slick-backed mats", "body": "On a flat floor, grip matters."},
 ],
 "verdict": {
  "thesis": "Match the generation first, then buy 3D MAXpider for the best-documented cabin fit, TripleAliners or Autocessking for full Juniper coverage, and 3W for a pre-refresh value set.",
  "body": "Model Y mats are about generation and scope. Pre-refresh and Juniper cars take different sets, and 7-seat and Standard versions add exclusions. 3D MAXpider has the clearest catalog and best construction details; the Tesla-focused kits cover more zones for less money.\n\nAfter the mats, many Model Y owners add a roof rack or a trailer hitch for a bike rack, both of which also differ by generation on some parts."},
 "sources": [
  ["3D Maxpider Kagu floor liners (AutoAccessoriesGarage)", "https://www.autoaccessoriesgarage.com/Floor-Mats-Liners/3D-Maxpider-Kagu-Floor-Liners"],
  ["3D MAXpider Kagu Model Y 2021–2025 listing", "https://www.amazon.com/dp/B0936RH9SH"],
  ["3D MAXpider Kagu Model Y Juniper listing", "https://www.amazon.com/dp/B0F8PPNW49"],
  ["3D MAXpider Model Y 7-seat third row listing", "https://www.amazon.com/dp/B098W37G9X"],
  ["TripleAliners Model Y Juniper 10-piece listing", "https://www.amazon.com/dp/B0DZGGYTBC"],
  ["Tesla Model Y (Wikipedia)", "https://en.wikipedia.org/wiki/Tesla_Model_Y"],
 ],
}

FITS = [
 ("B0936RH9SH","3D MAXpider Kagu Floor Mats Full Set, Tesla Model Y 2021-2025 (pre-refresh)","3D MAXpider","$150–$230",{"year_to":2024,"rows":2},"Pre-refresh; confirm 2025 build."),
 ("B0F8PPNW49","3D MAXpider Kagu Floor Mats Full Set, Tesla Model Y Juniper 2026","3D MAXpider","$150–$230",{"year_from":2025},"Juniper; confirm 2025 Juniper."),
 ("B0DZGGYTBC","TripleAliners 10-Piece Set, 2025-2026 Model Y Juniper (floor, frunk, trunk, rear lower, backrest, bumper guard)","TripleAliners","$150–$200",{"year_from":2025},"Juniper only; not Standard."),
 ("B0BRJQ2C7V","3W 6-Piece TPE Floor Mats + Cargo + Frunk Liners, 2020-2024 Model Y 5-seat (not Juniper)","3W","$120–$160",{"year_to":2024,"rows":2},"Pre-Juniper only."),
 ("B0H251XWBW","Autocessking 11-Piece All-Weather Mats + Cargo Liners, 2025-2026 Model Y Juniper (not Standard)","Autocessking","$150–$200",{"year_from":2025},"Juniper only."),
 ("B0GTS6R1N6","Foronetry 8-Piece All-Weather Set, 2025-2026 Model Y Juniper 5-seat (frunk, trunk, cargo, rear mats)","Foronetry","$140–$190",{"year_from":2025,"rows":2},"Juniper only; not Standard trim or 7-seat."),
 ("B0CBWNQYW5","Foronetry 9-Piece All-Weather Set, 2021-2024 Model Y 5-seat (not 7-seat / not Juniper)","Foronetry","$130–$180",{"year_to":2024,"rows":2},"Pre-Juniper only."),
 ("B0CPXZKX62","WEIZE 6-Piece All-Weather Mats + Trunk + Cargo Liners, 2020-2024 Model Y 5-seat","WEIZE","$100–$140",{"year_to":2024,"rows":2},"Pre-Juniper only."),
 ("B0H6QQJ7GT","Front (frunk) + Rear Trunk Mats, 2025-2026 Model Y Juniper 5-seat Premium/Performance","Generic","$60–$90",{"year_from":2025},"Trunk/frunk only; Juniper."),
 ("B098W37G9X","3D MAXpider Kagu Third Row Mat, Tesla Model Y 7-Seat 2021-2025","3D MAXpider","$50–$80",{"rows":3},"7-seat third row only."),
]
