"""Long-form article — Best Rooftop Cargo Boxes for 2020–2026 Tesla Model Y (incl. 2025 Juniper refresh).
Mirrors the approved RAV4 / Outback cargo-box pages. No invented hands-on testing: box specs come from the Yakima,
Thule, Rhino-Rack and SportRack product pages and etrailer (INNO) listed in sources; vehicle facts from
db/migrations/003_vehicles.sql, the Tesla Shop, the Model Y owner's manual and the Model Y roof-rack page's
references (checked 2026-09-27). Boxes are universal; the Model Y-specific part is the glass roof with fixed points,
the 165 lb rating, the ~35.5 in factory spread, power liftgate clearance and range.
Source fixes 2026-10-04: removed the unsourced claim that the 7-seat Model Y "has the same roof as the 5-seat" (now: Tesla's rack listing excludes only the Model Y L, we could not confirm a seven-seat roof fit, and Wikipedia says the US seven-seat option ended at the 2025 refresh); dated the Model Y Standard (October 2025) and Model Y L (US launch July 2026) per Wikipedia; the hitch-carrier FAQ now carries Tesla's manual wording on accessory carriers and the tow package.
"""

KEY = ("tesla", "model-y", "2020-present", "cargo-boxes")

TITLE = "Best Rooftop Cargo Boxes for 2020–2026 Tesla Model Y: 7 Boxes for Its Spread, Liftgate and Range"
META = ("Seven Yakima, Thule, INNO, Rhino-Rack and SportRack boxes for the Model Y: 165 lb load math, 35.5 in "
        "bar spread, power liftgate height and range cost.")

FAQ = [
 ("What is the best cargo box for a Tesla Model Y?",
  "For most owners, the Yakima GrandTour 16. It holds 16 cu ft in a 79 in shell, its 24–36 in crossbar spread covers the Model Y's roughly 35.5 in factory spread, and etrailer confirms GrandTour boxes fit Tesla's Model Y bars as long as the bars are no wider than 3-1/2 in and no taller than 1-11/16 in. If roof load matters more than volume, the 30.2 lb Yakima DeepSpace 10 or 31 lb Thule Pulse 2 M leave more of Tesla's 165 lb for gear."),
 ("How much weight can I put in a roof box on a Model Y?",
  "Tesla rates its Model Y Roof Rack at 165 lb, and that figure covers the bars, the box and the cargo together. A 51.5 lb GrandTour 16 leaves about 113 lb before you subtract the bars; a 30.2 lb DeepSpace 10 leaves about 135 lb, though that box has its own 100 lb cargo limit. The TESEVO bars on our roof rack page weigh 12.4 lb, which gives a sense of what bars take off the total."),
 ("What crossbar spread do cargo boxes need on a Model Y?",
  "An owner on etrailer measured the Tesla crossbars on a 2021 Model Y at about 35.5 in center to center. That is wide enough to rule some boxes out. The GrandTour 16 (24–36 in), DeepSpace 10 (32–46 in), INNO Wedge 660 (24–39 in, per etrailer) and Rhino-Rack MasterFit 440 (about 24.4–36.6 in) cover it. The Yakima SkyBox 16 tops out at 34.5 in and the SportRack Vista XL's widest position is 29-7/8 in, so neither suits factory bars."),
 ("Will a cargo box hit the Model Y's power liftgate?",
  "It can if the tail of the box reaches past the back of the roof. Tesla's manual says the liftgate can open up to about 7.5 ft high. Mount the box forward, open the liftgate slowly the first time and watch the gap. If it's tight, lower the opening height: stop the liftgate at the height you want (or move it by hand), then press and hold the button on its underside until you hear a chime to save it."),
 ("How much range does a roof box cost on a Model Y?",
  "Tesla doesn't publish a figure for a box. The best public data is from fueleconomy.gov, which says a large, blunt rooftop cargo box can reduce fuel economy by around 2–8% in city driving, 6–17% on the highway and 10–25% at 65–75 mph, while rear-mounted cargo boxes cost 1–5% on the highway. An EV loses energy to drag the same way, so plan road-trip charging around the high end and take the box off between trips."),
 ("Is a hitch cargo carrier better than a roof box on a Model Y?",
  "For range, usually yes, but read Tesla's manual first. It says not to install an accessory carrier on a Model Y that is not equipped with the tow package, and that the tow package receiver is designed for vertical loads up to 160 lb. A Model Y with the Tow Package has a 2 in receiver, per our vehicle data, and fueleconomy.gov puts rear-mounted carriers at 1–5% worse on the highway against 6–17% for a rooftop box. The trade-offs are that a hitch carrier blocks or loads the liftgate unless it swings or tilts, and it isn't sealed unless you buy a hitch box. For skis and soft luggage on long trips, the roof box still wins on convenience."),
 ("Does the 2025 Juniper change which cargo box fits?",
  "The box doesn't care, because it clamps to crossbars. What changes is the bars. Tesstudio and EVBASE sell separate racks for the 2020–2024 Model Y and the Juniper, while Tesla says its own rack fits every Model Y except the Model Y L. Buy bars for your body, measure the new spread, and check it against the box's range before mounting."),
 ("Will Thule and Yakima box clamps fit Tesla's Model Y crossbars?",
  "Usually, within limits. Tesla's bars are aluminum T-slot bars, and Tesla says the slots take cargo boxes. etrailer confirms the Yakima GrandTour 16 and 18 fit Model Y bars no wider than 3-1/2 in and no taller than 1-11/16 in. For other boxes, measure your bar and compare it with the clamp's range; aftermarket bars vary in profile."),
 ("Can I put a cargo box on a Model Y with a 7-seat or Model Y L?",
  "Wikipedia says the US seven-seat option ended at the 2025 refresh, so a seven-seat car is a pre-refresh Model Y. Tesla says its rack fits all Model Y vehicles except the Model Y L, which leaves the seven-seat car included. We could not confirm from a maker's page that the seven-seat roof matches the five-seat, so check the bar listing for your car. The Model Y L, the six-seat version that Wikipedia says launched in the US in July 2026, is different: Tesla excludes it from its Model Y rack, and we found no confirmed rack for it on our roof rack page. Until a rack listed for the Model Y L exists, there is no safe base for a box on that car."),
 ("Will a roof box make the Model Y too tall for my garage?",
  "Measure the garage door opening and add the height of the bars and box. The INNO Wedge 660 is only 11 in tall, the Yakima CBX 16 15 in, the Thule Pulse 2 M 16.6 in, the SportRack Horizon 2 L 16 in, the DeepSpace 10 16 in, the Rhino-Rack MasterFit 440 17 in and the GrandTour 16 18 in. Also set the liftgate height for the garage ceiling, since Tesla warns that it opens up to about 7.5 ft."),
]

ARTICLE = {
 "dek": "Seven rooftop boxes from Yakima, Thule, INNO, Rhino-Rack and SportRack matched to the Model Y's glass roof, fixed-point bars and wide 35.5 in factory spread. For each one we list volume, length, height, weight and spread range, and what those numbers mean for Tesla's 165 lb rating, the power liftgate and range, on 2020–2024 cars and the 2025 Juniper.",
 "author": "jake-morrison",
 "reviewed": "2026-10-04",
 "method": "We did not mount these boxes ourselves. We ranked them on the makers' published specs (Yakima, Thule, Rhino-Rack and SportRack product pages, and etrailer's listing for the INNO box): volume, exterior dimensions, box weight, load rating, crossbar spread and warranty. We then matched them to the Model Y's 165 lb rack rating from the Tesla Shop, the roughly 35.5 in factory spread from an etrailer Q&A, etrailer's clamp-fit answer for Tesla bars, the liftgate guidance in Tesla's owner's manual and the range data on fueleconomy.gov. Prices were checked in September 2026; Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Bars first, on fixed points.** The Model Y has a glass roof with four hidden mounting points. Tesla's rack fits all Model Y except the Model Y L; aftermarket bars split 2020–2024 and Juniper.",
  "**165 lb covers everything.** Tesla rates its Model Y rack at 165 lb, bars and box included. A 30–57 lb box leaves roughly 95–120 lb for gear once bars are counted.",
  "**The factory spread is wide: about 35.5 in.** The GrandTour 16, DeepSpace 10, Wedge 660 and MasterFit 440 cover it; the SkyBox 16 (34.5 in max) and Vista XL (29-7/8 in max) don't.",
  "**Set the liftgate height.** Tesla says the liftgate opens up to about 7.5 ft. Mount the box forward, and save a lower opening height if the gap is tight.",
  "**Range is the running cost.** fueleconomy.gov puts rooftop boxes at 10–25% worse efficiency at 65–75 mph. Remove the box between trips.",
 ],
 "top_picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "why": "16 cu ft in 79 in; 24–36 in spread covers 35.5 in; etrailer confirms fit on Model Y bars"},
  {"asin": "B09HC2LWX8", "role": "Lightest box", "why": "Yakima DeepSpace 10: 30.2 lb, 60 in long, 32–46 in spread made for wide bars"},
  {"asin": "B0G8C5LHQ5", "role": "Best light 14 cu ft", "why": "Thule Pulse 2 M: 31 lb, 68.9 in, 165 lb box rating"},
  {"asin": "B06VX9L59C", "role": "Best for range", "why": "INNO Wedge 660: only 11 in tall, 24–39 in spread"},
  {"asin": "B0GH4XR3D9", "role": "Best budget", "why": "SportRack Horizon 2 L: 16 cu ft, 37 lb, $549.95; passenger-side opening"},
 ],
 "fit_table": {
  "caption": "Model Y roof setups (what you need before any box goes on)",
  "head": ["Body", "Build", "Crossbars", "Box notes"],
  "rows": [
   ["Original Model Y (5- or 7-seat)", "2020 to early 2025", "Tesla rack, or aftermarket bars listed 2020–2024 (confirm 7-seat fit on aftermarket bars)", "Factory spread about 35.5 in (etrailer Q&A); 165 lb limit"],
   ["Juniper refresh", "Early 2025 onward", "Tesla rack, or bars that name Juniper", "Same boxes; measure the spread on your bars"],
   ["Model Y Standard", "October 2025 onward (Wikipedia)", "Check the bar listing; some makers list separate parts", "Confirm bars before choosing a box"],
   ["Model Y L (6-seat)", "US launch July 2026 (Wikipedia)", "Excluded from Tesla's rack; no confirmed rack", "No box until a rack is listed"],
  ],
 },
 "look_for": [
  {"h": "Crossbar spread: why 35.5 in rules boxes out",
   "body": "An owner on etrailer measured the Tesla crossbars on a 2021 Model Y at about 35.5 in center to center, and etrailer's expert used that figure to confirm a carrier's fit. That is wider than many boxes allow. The GrandTour 16 (24–36 in), DeepSpace 10 (32–46 in), INNO Wedge 660 (24–39 in, per etrailer) and Rhino-Rack MasterFit 440 (620–930 mm, about 24.4–36.6 in) cover it. The Yakima CBX 16 tops out at exactly 35.5 in, so measure first. The SkyBox 16 (34.5 in max) and the SportRack Vista XL (29-7/8 in widest position) won't reach factory bars."},
  {"h": "Tesla's 165 lb rating after bars and box",
   "body": "Tesla rates its Model Y Roof Rack at 165 lb, and the aftermarket bars on our roof rack page list the same 75 kg. That is the total for the bars, the box and the cargo. The boxes here weigh 30.2 lb (DeepSpace 10) to 57 lb (CBX 16). With bars around 12 lb, like TESEVO's 12.4 lb set, you have roughly 95–120 lb for gear. Pack jackets, sleeping bags and duffels up top and keep dense items in the frunk and trunk. A box's own 165 lb rating doesn't add to the car's limit."},
  {"h": "Power liftgate clearance and opening height",
   "body": "The Model Y's liftgate hinges at the back of the roof, and Tesla's manual says it can open up to about 7.5 ft high. A box whose tail reaches past the rear crossbar can sit in the liftgate's path. The wide 35.5 in spread helps, because less of the box overhangs the bars: a 79 in GrandTour overhangs about 43.5 in in total, split front and rear. Mount it forward, open the liftgate slowly the first time, and if it's close, save a lower opening height by stopping the liftgate where you want it and holding the button on its underside until it chimes."},
  {"h": "Range, shape and wind noise",
   "body": "Tesla publishes no range figure for a roof box. fueleconomy.gov says a large, blunt rooftop cargo box can reduce fuel economy by around 2–8% in the city, 6–17% on the highway and 10–25% at 65–75 mph, and rear-mounted carriers 1–5% on the highway. Those figures are for gas cars, but an EV pays for drag the same way. Shape is what you control: the INNO Wedge 660 is 11 in tall and the CBX 16 15 in, against 18 in for the GrandTour 16. In a quiet EV cabin, wind noise also stands out, so mount the box level and remove it between trips."},
  {"h": "Clamp fit on Tesla's T-slot bars",
   "body": "Tesla's Model Y bars are powder-coated aluminum with T-slots, and Tesla says they take cargo boxes. Most boxes here clamp around the bar, so the bar's size matters. etrailer confirms the Yakima GrandTour 16 and 18 fit Model Y bars no wider than 3-1/2 in and no taller than 1-11/16 in. etrailer says the INNO Wedge 660 fits round, square, aero, elliptical and most factory bars. SportRack's Horizon 2 uses a U-bolt kit, which is simple on round and square bars but worth checking on an aero profile. Measure your bars before you order."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Crossbar spread", "A range that reaches about 35.5 in (GrandTour 16, DeepSpace 10, Wedge 660, MasterFit 440)", "SkyBox 16 (34.5 in max) or Vista XL (29-7/8 in max) on factory bars"],
   ["Box weight", "Under 45 lb to save Tesla's 165 lb for gear", "57 lb boxes if you pack dense gear"],
   ["Length", "Mounted forward so the tail clears the liftgate", "Long boxes pushed back to clear the glass roof's front edge"],
   ["Height / shape", "Low, tapered boxes for range (Wedge 660 11 in)", "Tall, blunt boxes left on all year"],
   ["Clamp fit", "Clamps rated for your bar (GrandTour: up to 3-1/2 × 1-11/16 in)", "Assuming any clamp fits an aero T-slot bar"],
   ["Opening", "Dual-side, or passenger side, so you load from the curb", "Driver-side-only access on busy streets"],
  ],
 },
 "types_table": {
  "caption": "Box sizing for the Model Y (makers' published specs; INNO and SportRack Vista XL per etrailer)",
  "head": ["Box", "Volume", "L × W × H", "Box weight", "Crossbar spread", "Works at 35.5 in?"],
  "rows": [
   ["Yakima DeepSpace 10", "10 cu ft", "60 × 23 × 16 in", "30.2 lb", "32–46 in", "Yes"],
   ["Thule Pulse 2 M", "14 cu ft", "68.9 × 32.1 × 16.6 in", "31 lb", "Not published", "Confirm with Thule"],
   ["SportRack Horizon 2 L", "16 cu ft", "75.6 × 33 × 16 in", "37 lb", "Not published", "Confirm"],
   ["Rhino-Rack MasterFit 440", "15.5 cu ft", "76 × 32 × 17 in", "38.6 lb", "About 24.4–36.6 in", "Yes"],
   ["Yakima GrandTour 16", "16 cu ft", "79 × 35 × 18 in", "51.5 lb", "24–36 in", "Yes (etrailer confirms fit)"],
   ["INNO Wedge 660", "11 cu ft", "80 × 33 × 11 in", "42 lb", "24–39 in", "Yes"],
   ["Yakima CBX 16", "16 cu ft", "83 × 38 × 15 in", "57 lb", "24–35.5 in", "At the limit; measure"],
   ["Yakima SkyBox 16 (not a pick)", "16 cu ft", "81 × 36 × 15 in", "47 lb", "24–34.5 in", "No"],
   ["SportRack Vista XL (not a pick)", "18 cu ft", "63 × 38 × 19 in", "Not published", "Fixed, 29-7/8 in max", "No"],
  ],
 },
 "picks": [
  {"asin": "B083KP48XC", "role": "Best overall", "price": "$709",
   "pros": ["16 cu ft in 79 in", "24–36 in spread covers the 35.5 in factory spread", "etrailer confirms fit on Model Y bars up to 3-1/2 × 1-11/16 in", "Dual-side opening; skis up to 185 cm", "Limited lifetime warranty"],
   "cons": ["51.5 lb, second-heaviest box here", "18 in tall, the tallest pick, so more drag and garage height", "35.5 in sits near the top of its range"],
   "body": "The GrandTour 16 is the one box here with a direct Model Y fit answer behind it. etrailer's expert says the Yakima GrandTour 16 and GrandTour 18 fit the Model Y's roof as long as the crossbars are no wider than 3-1/2 in and no taller than 1-11/16 in, and its 24–36 in spread covers the roughly 35.5 in that owners measure on Tesla's bars. Yakima lists it at 79 x 35 x 18 in, 16 cu ft and 51.5 lb, with dual-sided opening, room for skis and boards up to 185 cm and a limited lifetime warranty, for $709.\n\nOn the wide factory spread it overhangs the bars by only about 43.5 in in total, so it is easy to set forward of the liftgate's path. The costs are weight and height. At 51.5 lb it leaves about 113 lb of Tesla's 165 lb before bars, closer to 100 lb once they're counted, so pack light and bulky gear. At 18 in tall it is the tallest box here, which means more frontal area on the highway and less garage clearance. Because 35.5 in sits near the top of its range, measure your bars center to center before mounting.",
   "who": "Model Y owners who want a full 16 cu ft box with a confirmed fit on Tesla's bars.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "79 × 35 × 18 in"], ["Box weight", "51.5 lb"], ["Crossbar spread", "24–36 in"], ["Bar limit (etrailer)", "Up to 3-1/2 in wide, 1-11/16 in tall"], ["Ski length", "Up to 185 cm"], ["Opening", "Dual-side"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B09HC2LWX8", "role": "Lightest box", "price": "$649",
   "pros": ["30.2 lb, the lightest box here", "32–46 in spread suits the Model Y's wide bars", "60 in long, the shortest box here", "Published 100 lb load rating and interior tie-down points", "SKS lock; limited lifetime warranty"],
   "cons": ["10 cu ft, and too short for skis", "23 in wide but 16 in tall", "$649 for 10 cu ft"],
   "body": "The Yakima DeepSpace 10 is the box whose spread range most boxes' ranges miss: 32–46 in. On a compact SUV or a Model 3 that minimum is a problem, but the Model Y's roughly 35.5 in factory spread sits comfortably inside it. Yakima lists it at 60 x 23 x 16 in, 10 cu ft and 30.2 lb, with a 100 lb load rating, a wide-angle opening, integrated interior tie-down points, an SKS lock and a limited lifetime warranty. It was $649 on Yakima's page, down from $869.99.\n\nFor a Model Y, the numbers are hard to beat. At 30.2 lb it leaves about 135 lb of Tesla's 165 lb before bars, and its own 100 lb cargo limit becomes the figure to respect. At 60 in long, it overhangs the bars by only about 24.5 in, so it sits well clear of the liftgate. It is also only 23 in wide, leaving bar space for a bike or ski mount alongside, as long as the total stays under 165 lb. The trade-off is volume: 10 cu ft won't take skis, so it suits camping gear, strollers and duffels.",
   "who": "Model Y owners who want the lightest, shortest box and room on the bars for another carrier.",
   "specs": [["Volume", "10 cu ft"], ["Exterior", "60 × 23 × 16 in"], ["Box weight", "30.2 lb"], ["Max load", "100 lb"], ["Crossbar spread", "32–46 in"], ["Lock", "SKS"], ["Price", "$649 (Yakima, regular $869.99)"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0G8C5LHQ5", "role": "Best light 14 cu ft", "price": "$699.95",
   "pros": ["31 lb with 14 cu ft inside", "68.9 in long, well clear of the liftgate", "165 lb (75 kg) box rating", "DualSide opening; PowerClick mounts with a torque indicator", "Thule publishes a front-clearance figure (>44 13/16 in)"],
   "cons": ["Skis only up to 155 cm", "Crossbar spread not published; confirm 35.5 in with Thule", "16.6 in tall"],
   "body": "The Thule Pulse 2 M gives you 40% more volume than the DeepSpace 10 for less than a pound of extra weight. Thule lists it at 68.9 x 32.1 x 16.6 in with 14 cu ft (400 L), a 31 lb box weight and a 165 lb (75 kg) maximum load. It opens from both sides, locks centrally and mounts with PowerClick clamps that have a torque indicator, and Thule and REI both list it at $699.95. Thule gives a front-clearance figure of more than 44 13/16 in to check against its hatch clearance guidance.\n\nOn Tesla's 165 lb rating, 31 lb of box leaves about 134 lb before bars, the best payload of any box that holds more than 10 cu ft here. At 68.9 in it overhangs the factory bars by only about 33 in in total, which keeps its tail well away from the liftgate. The limits are ski length, just 155 cm, and a missing spread figure: Thule's page doesn't publish one, so confirm in Thule's fit guide that the box's clamps reach bars about 35.5 in apart.",
   "who": "Model Y owners who want a light, short box for luggage and camping gear rather than skis.",
   "specs": [["Volume", "14 cu ft (400 L)"], ["Exterior", "68.9 × 32.1 × 16.6 in"], ["Box weight", "31 lb"], ["Max load", "165 lb (75 kg)"], ["Ski length", "Up to 155 cm"], ["Mount / lock", "PowerClick / central locking"], ["Crossbar spread", "Not published; confirm"], ["Price", "$699.95 (Thule, REI)"]]},
  {"asin": "B06VX9L59C", "role": "Best for range", "price": "$864.97",
   "pros": ["Only 11 in tall, the least frontal area here", "24–39 in spread covers 35.5 in with room to spare", "110 lb weight capacity", "Fits aero and most factory bars, per etrailer", "Limited lifetime warranty, per etrailer"],
   "cons": ["11 cu ft for $864.97", "80 in long", "Skis only up to 182 cm, loaded diagonally"],
   "body": "Range-conscious Model Y owners should start with the INNO Wedge 660. etrailer lists it at 80 x 33 x 11 in with 11 cu ft, a 42 lb box weight, a 110 lb weight capacity and a 24–39 in crossbar spread. At 11 in tall it is 7 in lower than the GrandTour 16, and a smaller frontal area is the part of drag an owner can control. No maker publishes a range figure for its box, but fueleconomy.gov's worst figures are for large, blunt boxes, and this is the opposite shape. The dual-side lid opens with push buttons, keyed locks on each side secure the cargo and mounts, and Memory Mount hardware makes repeat installs quick. etrailer lists it at $864.97 with a limited lifetime warranty.\n\nThe 35.5 in factory spread sits well inside its range, and etrailer says it fits round, square, aero, elliptical and most factory bars, though you should check the clamp against Tesla's T-slot profile. At 42 lb it leaves about 123 lb of Tesla's 165 lb before bars. The trade-off is space: 11 cu ft is long and flat, best for skis up to 182 cm, soft bags and camping pads. At 80 in, mount it forward and check the liftgate.",
   "who": "Highway road-trippers who want the lowest box and accept less volume to save range.",
   "specs": [["Volume", "11 cu ft"], ["Exterior", "80 × 33 × 11 in"], ["Box weight", "42 lb"], ["Weight capacity", "110 lb"], ["Crossbar spread", "24–39 in"], ["Ski length", "Up to 182 cm (diagonal)"], ["Opening", "Dual-side, push-button"], ["Warranty", "Limited lifetime (etrailer)"]]},
  {"asin": "B07B4P7WYX", "role": "Best mid-weight", "price": "Not listed by Rhino-Rack; see listing",
   "pros": ["15.5 cu ft (440 L) at 38.6 lb", "620–930 mm spread (about 24.4–36.6 in) covers 35.5 in", "76 in long", "Dual-side opening, 3 locking points", "5-year warranty"],
   "cons": ["No US price on Rhino-Rack's page; confirm on the listing", "130 km/h (about 80 mph) maximum speed with the box, per the instructions", "17 in tall"],
   "body": "The Rhino-Rack MasterFit 440 is a near-16 cu ft box at well under 40 lb. Rhino-Rack lists it at 76 x 32 x 17 in with 440 L (15.5 cu ft), a 38.6 lb box weight, a 75 kg maximum load, dual-side opening with keyed locks on both sides, three locking points, two load straps and a 5-year warranty. Its instructions give a crossbar spacing of 620–930 mm for this size, about 24.4 to 36.6 in, which includes the Model Y's roughly 35.5 in with an inch to spare.\n\nAgainst Tesla's 165 lb rating, 38.6 lb of box leaves about 126 lb before bars, nearly 13 lb more than the GrandTour 16 while holding almost as much. At 76 in it overhangs the factory bars by about 40.5 in, easy to keep forward of the liftgate. The instructions set a 130 km/h maximum speed with the box fitted. Rhino-Rack's US page lists no price, so check the listing, and confirm its mounting hardware suits Tesla's aero T-slot bars.",
   "who": "Buyers who want close to 16 cu ft, a light shell and a published warranty.",
   "specs": [["Volume", "15.5 cu ft (440 L)"], ["Exterior", "76 × 32 × 17 in"], ["Box weight", "38.6 lb"], ["Max load", "75 kg (165 lb)"], ["Crossbar spread", "620–930 mm (about 24.4–36.6 in)"], ["Opening / locks", "Dual-side; 3 locking points"], ["Max speed", "130 km/h (instructions)"], ["Warranty", "5 years"]]},
  {"asin": "B0C41RZ4HM", "role": "Most rugged", "price": "$699",
   "pros": ["16 cu ft at only 15 in tall", "Rugged textured shell", "Dual-side opening with SKS locks", "Skis and boards up to 185 cm", "Limited lifetime warranty"],
   "cons": ["57 lb, the heaviest box here", "24–35.5 in spread tops out right at the factory spread", "83 in long and 38 in wide"],
   "body": "The Yakima CBX 16 is the rugged-looking option, and on a Model Y it comes with two numbers to check. Yakima lists it at 83 x 38 x 15 in, 16 cu ft and 57 lb, with a dual-sided hatch, SKS locks, an easy-grab lid handle, room for skis and boards up to 185 cm, a 24–35.5 in crossbar spread and a limited lifetime warranty, for $699. Yakima says it mounts to its StreamLine bars and to factory or aero crossbars. At 15 in it is 3 in lower than the GrandTour 16, which helps drag and garage clearance.\n\nThe first check is the spread. Its 35.5 in maximum matches the owner-measured factory spread almost exactly, so measure your bars center to center; if they come out even slightly wider, this box isn't the right fit. The second is weight. At 57 lb it leaves about 108 lb of Tesla's 165 lb before bars, the least of any box here. Customer reviews on Yakima's page mention fitment trouble on some factory crossbars, so confirm the clamp suits Tesla's bars before you order.",
   "who": "Owners who want a tough 16 cu ft box, pack light, and have measured a spread of 35.5 in or less.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "83 × 38 × 15 in"], ["Box weight", "57 lb"], ["Crossbar spread", "24–35.5 in"], ["Opening", "Dual-side"], ["Ski length", "Up to 185 cm"], ["Lock", "SKS locks included"], ["Warranty", "Limited lifetime"]]},
  {"asin": "B0GH4XR3D9", "role": "Best budget", "price": "$549.95",
   "pros": ["16 cu ft for $549.95", "37 lb, lighter than every Yakima 16 here", "110 lb load capacity", "Passenger-side opening for loading away from traffic", "75.6 in long"],
   "cons": ["Single-side (passenger) opening only", "U-bolt mounting kit; confirm fit on Tesla's aero T-slot bars", "Crossbar spread and warranty terms not published; confirm"],
   "body": "The SportRack Horizon 2 L is the budget 16 cu ft box that suits the Model Y's wide bars better than SportRack's own Vista XL, whose widest mounting position is 29-7/8 in. SportRack lists the Horizon 2 at 75.6 x 33 x 16 in, 16 cu ft, 37 lb and a 110 lb load capacity, with room for four to six pairs of skis up to 181 cm, an impact-resistant ABS shell and passenger-side opening for loading away from traffic, for $549.95. That is 14.5 lb lighter than the GrandTour 16 and $159.05 cheaper.\n\nOn Tesla's 165 lb rating, 37 lb of box leaves about 128 lb before bars, though the box's own 110 lb load capacity is the tighter limit. At 75.6 in it overhangs the factory bars by about 40 in, so it can sit forward of the liftgate. Two things need checking. It mounts with a U-bolt kit that SportRack says suits square, round and factory bars, so confirm it clamps securely around Tesla's aero T-slot profile. SportRack also doesn't publish a crossbar spread or warranty terms, so confirm both on the listing.",
   "who": "Budget buyers who want 16 cu ft on a Model Y and don't mind single-side access.",
   "specs": [["Volume", "16 cu ft"], ["Exterior", "75.6 × 33 × 16 in"], ["Box weight", "37 lb"], ["Load capacity", "110 lb"], ["Ski length", "Up to 181 cm"], ["Opening", "Passenger side"], ["Mounting", "U-bolt kit"], ["Crossbar spread / warranty", "Not published; confirm"]]},
 ],
 "install": [
  "Fit bars for your body (Tesla's rack for any Model Y except the L, or aftermarket bars for 2020–2024 or Juniper) into the four fixed points under the roof trim, and torque them to spec.",
  "Measure the spread center to center (about 35.5 in on factory bars) and the bar's width and height, and compare both with the box's spread range and clamp limits.",
  "With a helper, set the box on the bars, center it side to side and slide it forward, keeping the nose off the windshield.",
  "Tighten the clamps loosely, open the liftgate slowly and check the gap at the tail; if it's tight, move the box forward or save a lower liftgate height.",
  "Tighten the clamps to the box maker's spec, lock the box and pull on each corner to check the mounts.",
  "Load light, bulky gear, keep bars + box + gear under 165 lb, and re-check the clamps after the first drive.",
 ],
 "avoid": [
  {"h": "Boxes that can't reach 35.5 in", "body": "The Yakima SkyBox 16 tops out at 34.5 in and the SportRack Vista XL at 29-7/8 in. On the Model Y's factory bars, neither can be clamped at its proper spacing."},
  {"h": "Loading to the box's rating", "body": "Tesla's 165 lb rating covers the bars and box too. After a 30–57 lb box and around 12 lb of bars, the gear allowance is roughly 95–120 lb, and some boxes have their own 100–110 lb cargo limit."},
  {"h": "Opening the liftgate at full height under a box", "body": "Tesla says the liftgate opens up to about 7.5 ft. Check the gap once, and save a lower height if the tail of the box is close."},
  {"h": "Leaving the box on all year", "body": "fueleconomy.gov puts rooftop boxes at 10–25% worse efficiency at 65–75 mph. On an EV that comes straight out of range, so take the box off between trips."},
 ],
 "verdict": {
  "thesis": "Fit Tesla-spec bars for your body, then choose the Yakima GrandTour 16 for a confirmed 16 cu ft fit, the DeepSpace 10 or Thule Pulse 2 M to save roof load, or the INNO Wedge 660 to save range.",
  "body": "On the Model Y, the factory spread of about 35.5 in decides more than it does on most cars. The GrandTour 16 fits it, and etrailer confirms it clamps to Model Y bars, which makes it the best all-round box. The DeepSpace 10's wide 32–46 in range, which rules it out on many cars, suits the Model Y well, and at 30.2 lb it is the lightest box here. The Thule Pulse 2 M is the light 14 cu ft option, the INNO Wedge 660 is the 11 in tall box for range, the Rhino-Rack MasterFit 440 carries 15.5 cu ft at 38.6 lb, and the SportRack Horizon 2 L is the budget 16. The CBX 16 works only if your spread measures 35.5 in or less.\n\nBefore any box, you need bars: see the Model Y roof rack page for fixed-point sets split by 2020–2024 and Juniper. If range matters more than a sealed box, a trailer hitch with a hitch cargo carrier costs far less efficiency on the highway, and all-weather floor mats keep the cabin clean on ski trips. Owners of the 2017–2026 Model 3 face a tighter 28 in spread and a 150 lb rating. The vehicle hub lists every fit-checked accessory for the Model Y.",
 },
 "sources": [
  ["Tesla Model Y Roof Rack: 165 lb rating, fitment (Tesla Shop)", "https://shop.tesla.com/product/model-y-roof-rack"],
  ["Model Y owner's manual: liftgate opening height (Tesla)", "https://www.tesla.com/ownersmanual/modely/en_us/GUID-3667D28B-5B3B-49CE-A1C1-3D70AC60D9F6.html"],
  ["Model Y factory rack crossbar spread (etrailer Q&A)", "https://www.etrailer.com/question-591977.html"],
  ["GrandTour fit on Model Y bars (etrailer expert answers)", "https://www.etrailer.com/answers.aspx?AnswerMake=Tesla&Manufacturer=Yakima&Filter=fit"],
  ["Yakima GrandTour 16 (Yakima)", "https://yakima.com/products/grandtour-16"],
  ["Yakima DeepSpace 10 (Yakima)", "https://yakima.com/collections/roof-boxes/products/deepspace-10"],
  ["Yakima CBX 16 (Yakima)", "https://yakima.com/products/cbx-16"],
  ["Thule Pulse 2 M (Thule)", "https://www.thule.com/en-us/cargo-carrier/car-top-carrier/thule-pulse-2-m-_-610250"],
  ["INNO Wedge 660 specs (etrailer)", "https://www.etrailer.com/Roof-Box/Inno/INBRM660BK.html"],
  ["Rhino-Rack MasterFit Roof Box 440L (Rhino-Rack)", "https://www.rhinorack.com/en-us/products/roof-racks/roof-boxes/roof-boxes/masterfit-roof-box-440l-black-_rmft440"],
  ["Rhino-Rack MasterFit instructions: load, spacing, speed (Rhino-Rack)", "https://assets.rhinorack.com/Instructions/Accessories/RMFT-Masterfit.pdf"],
  ["SportRack Horizon 2 (SportRack)", "https://www.sportrack.com/product/horizon2/"],
  ["Tesstudio roof rack variants, Model Y and Juniper (Tesstudio)", "https://www.tesstudio.com/products/tesstudio-roof-rack-for-tesla-model-3-highland-model-y-model-y-juniper-set-of-2"],
  ["Cargo box and rear carrier fuel economy impact (fueleconomy.gov)", "https://www.fueleconomy.gov/feg/driveHabits.jsp"],
  ["Model Y Owner's Manual: Towing and Accessories (Tesla)", "https://www.tesla.com/ownersmanual/modely/en_us/GUID-F5C80FF5-8DE3-4750-8BAF-0DCC0CFA0C5C.html"],
  ["Tesla Model Y: seven-seat option, Model Y Standard and Model Y L dates (Wikipedia)", "https://en.wikipedia.org/wiki/Tesla_Model_Y"],
 ],
}

# Product list for this page (boxes only; crossbars live on the Model Y roof-racks page). (asin, name, brand, band, cond, note)
FITS = [
 ("B083KP48XC","Yakima GrandTour 16 Premium Rooftop Cargo Box, 16 cu ft, dual-side opening (79 in long)","Yakima","$700–$900",{},"24-36 in spread; etrailer confirms Model Y bar fit. Confirm liftgate gap."),
 ("B09HC2LWX8","Yakima DeepSpace 10 Hard Shell Cargo Box, 10 cu ft (60 in long)","Yakima","$550–$700",{},"32-46 in spread suits ~35.5 in factory bars; confirm your spread."),
 ("B0G8C5LHQ5","Thule Pulse 2 M Roof-Mounted Box, 14 Cubic Ft, Dual-Side Opening","Thule","$650–$750",{},"31 lb; confirm spread reaches 35.5 in with Thule's fit guide."),
 ("B06VX9L59C","INNO BRM660BK Wedge Cargo Box - 11 Cubic FT (Gloss Black)","INNO","$800–$900",{},"11 in tall, 24-39 in spread; confirm clamp fit on T-slot bars."),
 ("B07B4P7WYX","Rhino-Rack MasterFit Roof Box 440L (Black)","Rhino-Rack","See listing",{},"About 24.4-36.6 in spread; confirm price and bar fit."),
 ("B0C41RZ4HM","Yakima CBX 16 Aerodynamic Rooftop Cargo Box for Cars, Wagons and SUVs","Yakima","$650–$750",{},"35.5 in max spread; confirm your bars measure 35.5 in or less."),
 ("B0GH4XR3D9","Sportrack Horizon 2 Cargo Box L, 16 Cubic Feet, Single Side Access","SportRack","$500–$600",{},"U-bolt mounts; confirm fit on aero T-slot bars and spread."),
]
