"""Long-form article — Best Floor Mats & Liners for 2022–2026 Toyota Tundra (3rd gen, XK70).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("toyota", "tundra", "2022-present", "floor-mats")

TITLE = "Best Floor Liners for 2022–2026 Toyota Tundra: 6 CrewMax & Double Cab Sets, Gas and i-FORCE MAX"
META = ("Six 3rd-gen Tundra floor liner sets from Husky, LASFIT and budget TPE, split by CrewMax vs Double Cab and "
        "checked for the i-FORCE MAX hybrid.")

FAQ = [
 ("Do 2014–2021 Tundra liners fit a 2022+ Tundra?",
  "No. The 2022 Tundra moved to the TNGA-F platform with a new cab. Husky's catalog makes the break clear: the 99581 set is for 2014–2021 CrewMax and the 99481 set is for 2022–2026 CrewMax. Buy a set listed for 2022 or later."),
 ("How do I tell a CrewMax from a Double Cab?",
  "Look at the rear doors. The CrewMax has full-size rear doors and a long rear floor with a sliding, reclining rear seat on some trims. The Double Cab has shorter rear doors and a smaller rear floor. The CrewMax usually carries the 5.5 ft or 6.5 ft bed, the Double Cab the 6.5 ft or 8.1 ft bed. The rear liners are not interchangeable, although Husky's 18571 front pair is listed for both cabs."),
 ("Do these liners fit the i-FORCE MAX hybrid Tundra?",
  "Some list it, some don't. LNZMPART's set names the hybrid. The AOMSAZTO bundle names the Tundra and Tundra Hybrid CrewMax. Husky's 99481 and LASFIT's set name the CrewMax without a hybrid note, so confirm with the seller or maker for a hybrid. The front floor is the same; the question is the rear piece, because the hybrid battery sits under the rear seat."),
 ("Will Tundra front liners fit a Sequoia?",
  "Husky lists its 18571 front pair for 2022–2026 Tundra CrewMax and Double Cab and for 2024–2026 Sequoia, which shows the two share a front floor. The rear floors are completely different, since the Sequoia has second and third rows. Don't use Tundra rear liners in a Sequoia."),
 ("Does the sliding rear seat affect the rear liner?",
  "On CrewMax trucks with the sliding rear bench, the rear floor has to accommodate seat tracks. CrewMax-specific liners are cut around them. Slide the seat through its range after installing to make sure the liner doesn't catch in the track."),
 ("What does the AOMSAZTO bundle include?",
  "Floor liners for the CrewMax plus a bed mat sized for the 5.5 ft bed, according to its title, which also lists the Tundra Hybrid. It's a convenient way to cover both at once if you have the short bed. If your CrewMax has the 6.5 ft bed, the bed mat won't fit."),
 ("Are Husky liners made in the USA?",
  "Husky says its WeatherBeater liners are designed, tested and manufactured in the USA, laser-measured using vehicle-specific data and covered by a lifetime warranty against cracks and breaks. That's more documentation than most budget brands offer."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto the retention posts and clear of the pedals at full travel. Remove the factory carpet mat first. After fitting, push the liner toward the pedals with your heel; it shouldn't move."),
 ("How do I clean them after mud or snow?",
  "Pull them out, hose them off and scrub with mild soap. Let them dry before reinstalling. Skip silicone protectants. In salt season, empty them every few days so melt doesn't spill over onto the carpet."),
 ("Do I need a cargo liner too?",
  "The Tundra is a pickup, so there's no interior cargo area. The next item for most owners is a bed mat or bed liner sized for the 5.5, 6.5 or 8.1 ft bed, and a tonneau cover if the bed carries gear that should stay dry."),
 ("Do Tundra liners fit the Capstone and 1794 Edition?",
  "Yes, if the cab and powertrain match. The Capstone is a hybrid CrewMax, and the 1794 Edition is a CrewMax offered with either powertrain depending on year. Trims change leather, trim and seats, not the floor pan. Buy by cab and hybrid status and confirm the rear piece on hybrid trucks."),
]

ARTICLE = {
 "dek": "Six liner sets listed for the 3rd-generation Tundra, from made-in-USA Husky WeatherBeater to an $80 TPE set. Cab length decides the rear liner, and the i-FORCE MAX hybrid's battery under the rear seat is the second thing to check.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2022–2026 Tundra (cab, hybrid, years), on published maker specs (material, origin, warranty) and on coverage in listing photos. Husky and LASFIT claims come from their own sites, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**New platform, new liners.** 2014–2021 Tundra liners don't fit the 2022+ truck.",
  "**CrewMax or Double Cab.** Husky sells 99481 for CrewMax and 99471 for Double Cab; rears don't swap.",
  "**Check the hybrid.** LNZMPART and AOMSAZTO name the i-FORCE MAX; others need confirming.",
  "**Front pairs are shared.** Husky's 18571 fits both cabs and the 2024–2026 Sequoia.",
  "**Husky is the documented pick.** Made in the USA with a lifetime crack warranty.",
 ],
 "top_picks": [
  {"asin": "B0BLQN9M6W", "role": "Best overall", "why": "Husky WeatherBeater 99481, 2022–2026 CrewMax, made in USA"},
  {"asin": "B0BLR5SB3K", "role": "Best for Double Cab", "why": "Husky WeatherBeater 99471, 2022–2026 Double Cab only"},
  {"asin": "B0BRCVGXCX", "role": "Best TPE", "why": "LASFIT recycled TPE, 2022–2026 CrewMax"},
  {"asin": "B0DYP2F168", "role": "Best for hybrid", "why": "LNZMPART full set that names the i-FORCE MAX hybrid"},
  {"asin": "B0F7G535N3", "role": "Best bundle", "why": "AOMSAZTO liners plus a 5.5 ft bed mat, gas and hybrid CrewMax"},
 ],
 "fit_table": {
  "caption": "2022–2026 Tundra: cab and powertrain decide the liner",
  "head": ["Variable", "Versions", "Liner note"],
  "rows": [
   ["Cab", "Double Cab, CrewMax", "Husky 99471 (Double Cab) vs 99481 (CrewMax); front 18571 shared"],
   ["Powertrain", "i-FORCE V6 or i-FORCE MAX hybrid", "Hybrid battery under rear seat; LNZMPART and AOMSAZTO list hybrid"],
   ["Rear seat (CrewMax)", "Fixed or sliding bench, by trim", "Slide the seat after install to check the track"],
   ["Generation", "2014–2021 vs 2022+", "Not compatible"],
  ],
 },
 "look_for": [
  {"h": "CrewMax or Double Cab",
   "body": "The 3rd-gen Tundra comes in two cabs, and the rear floors differ a lot. The CrewMax has full-size rear doors and one of the longest rear floors in the segment; the Double Cab's rear floor is shorter. Husky makes the split clean, with the 99481 set for CrewMax and the 99471 for Double Cab, while its 18571 front pair covers both. Most budget listings on this page are CrewMax only. If you have a Double Cab, the Husky 99471 is the one set here cut for it, so check the listing title twice before you order a cheaper CrewMax set by mistake."},
  {"h": "The i-FORCE MAX hybrid",
   "body": "Toyota's hybrid Tundra puts its battery under the rear seat, which changes the rear floor area of the CrewMax. That's why some listings name the hybrid and others stay silent. LNZMPART says its full set covers the CrewMax including the hybrid, and the AOMSAZTO bundle names the Tundra and Tundra Hybrid CrewMax. Husky and LASFIT list the CrewMax without a hybrid note. The front floor isn't affected, so a hybrid owner can buy a Husky front pair and confirm the rear separately. TRD Pro and Capstone trucks are hybrids, so this applies to them."},
  {"h": "Wall height and sill coverage",
   "body": "The Tundra's tall step-in means boots scrape the front liner edge on every entry. A liner with high walls that run up the sill keeps slush off the carpet. Husky's WeatherBeater uses a firm ProGard material that holds its wall shape; LASFIT's TPE is softer and grips boots better but has a lower lip. For a truck that sees snow, mud or job sites, prioritize walls. For a highway truck, softer TPE is more comfortable and easier to clean."},
  {"h": "Warranty and material",
   "body": "Husky says WeatherBeater is laser-measured, designed and made in the USA, and backed by a lifetime warranty against cracks and breaks, with StayPut nibs underneath. LASFIT uses GRS-certified recycled TPE rated from −13°F to 167°F. The budget brands (LNZMPART, Falafa, Priprilod, AOMSAZTO) sell TPE with raised edges and don't publish comparable terms. On a truck many owners keep for a decade, a written warranty is the easiest way to tell how a maker expects its liner to age."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2022+ in the title", "2014–2021 listings"],
   ["Cab", "CrewMax or Double Cab named", "No cab"],
   ["Hybrid", "i-FORCE MAX named or confirmed", "Assuming gas-truck rears fit"],
   ["Retention", "Hooks for Toyota's posts", "Loose mats"],
   ["Walls", "Raised lip up the sill", "Flat mats"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2022–2026 Tundra",
  "head": ["Type", "Example", "Coverage", "Walls", "Price band", "Best for"],
  "rows": [
   ["USA-made molded liner", "Husky WeatherBeater", "Front + rear", "High", "$160–$230", "Work, snow, mud"],
   ["Recycled TPE liner", "LASFIT", "Front + rear", "Medium-high", "$130–$170", "Daily drivers"],
   ["Budget TPE", "LNZMPART, Falafa, Priprilod", "Front + rear", "Medium", "$80–$130", "Value"],
   ["Liner + bed mat bundle", "AOMSAZTO", "Cab + 5.5 ft bed", "Medium", "$150–$200", "Short-bed CrewMax owners"],
  ],
 },
 "picks": [
  {"asin": "B0BLQN9M6W", "role": "Best overall", "price": "$160–$230",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs grip carpet", "Listing covers 2022–2026 CrewMax", "One-piece rear"],
   "cons": ["No hybrid note in the title", "Firm feel", "CrewMax only"],
   "body": "Husky's WeatherBeater 99481 is the most documented liner for the 3rd-gen CrewMax. The listing covers 2022–2026 Tundra CrewMax only, and Husky sells a separate set for the Double Cab and a different one for 2014–2021 trucks, which shows the maker tracks the floor changes precisely.\n\nHusky says WeatherBeater liners are laser-measured with vehicle-specific data, designed, tested and made in the USA from its ProGard formula, and anchored by StayPut nibs. The lifetime warranty covers cracks and breaks. For a Tundra that tows, works or sees snow, the firm walls are the reason to pay more: they hold slush and mud in the tray instead of letting it roll onto the carpet. The trade-off is feel, and the title doesn't mention the i-FORCE MAX. Hybrid owners should confirm the rear piece with Husky or the seller before ordering, or pair Husky's 18571 front liners with a hybrid-listed rear.",
   "who": "CrewMax owners who want the strongest warranty and highest walls.",
   "specs": [["Part #", "Husky 99481"], ["Pieces", "3"], ["Fits", "2022–2026 Tundra CrewMax only"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"], ["Hybrid", "Confirm with Husky"]]},
  {"asin": "B0BLR5SB3K", "role": "Best for Double Cab", "price": "$150–$220",
   "pros": ["Cut for the Double Cab's shorter rear floor", "Same WeatherBeater material and warranty", "Made in the USA", "Covers 2022–2026", "Few alternatives exist for this cab"],
   "cons": ["Double Cab only", "Priced close to the CrewMax set", "Firm feel"],
   "body": "Double Cab Tundras get overlooked by budget liner brands, which mostly cut CrewMax sets. Husky's WeatherBeater 99471 is listed for 2022–2026 Tundra Double Cab only, front and second row, and it's the one set on this page shaped for that shorter rear floor.\n\nIt shares the 99481's strengths: laser-measured fit, US manufacturing, ProGard material, StayPut nibs and a lifetime warranty against cracks and breaks. Double Cabs are often work trucks with long beds, and the rear floor tends to carry tools, so a firm tray with walls earns its keep. If you only want the fronts, Husky's 18571 pair covers both cabs and costs less. Otherwise, this is the set to buy for a Double Cab rather than trimming a CrewMax liner to fit.",
   "who": "Double Cab owners, especially work trucks.",
   "specs": [["Part #", "Husky 99471"], ["Pieces", "3"], ["Fits", "2022–2026 Tundra Double Cab only"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B0BRCVGXCX", "role": "Best TPE", "price": "$130–$170",
   "pros": ["GRS-certified recycled TPE", "Rated −13°F to 167°F", "3D laser-scanned", "Front and rear", "45-day returns on LASFIT's store"],
   "cons": ["CrewMax only", "No hybrid note", "Lower walls than Husky"],
   "body": "LASFIT's set is listed for 2022–2026 Tundra CrewMax, front and rear. LASFIT says it's 3D laser-scanned and made from GRS-certified recycled TPE free of PVC and phthalates, with a rated range of −13°F to 167°F.\n\nThe softer TPE surface grips a wet boot and folds for cleaning without stress marks, which makes it nicer day to day than a firm liner. What you give up is wall height: the lip is lower than Husky's, so empty it after a heavy snow day. The title doesn't mention the hybrid, so confirm the rear piece if your truck has the i-FORCE MAX. For a gas CrewMax used as a daily driver, it's the best balance of fit, comfort and price here.",
   "who": "Gas CrewMax owners who want soft, grippy TPE.",
   "specs": [["Rows", "Front + rear"], ["Fits", "2022–2026 Tundra CrewMax"], ["Material", "Recycled TPE (GRS)"], ["Temp range", "−13°F to 167°F"], ["Hybrid", "Confirm with seller"], ["Returns", "45 days (LASFIT store)"]]},
  {"asin": "B0DYP2F168", "role": "Best for hybrid", "price": "$90–$130",
   "pros": ["Title names the i-FORCE MAX hybrid", "Full set for the CrewMax", "Low price", "TPE with raised edges", "Covers 2022–2025"],
   "cons": ["No maker documentation", "2026 not listed", "CrewMax only"],
   "body": "LNZMPART's full set is one of the few budget listings that names the i-FORCE MAX hybrid, covering 2022–2025 Tundra CrewMax. For a TRD Pro, Capstone or any hybrid CrewMax, that's the detail that matters most in the rear piece.\n\nIt's a generic TPE liner with raised edges and little maker documentation, so warranty and material grade are unknowns. The value is simple: a hybrid-specific cut at a budget price. If you want Husky's walls and warranty on a hybrid, one option is Husky's 18571 front pair plus this set's rear, or ask Husky to confirm its rear piece for your truck. For a 2026, confirm fit with the seller. That makes LNZMPART the simplest route for a hybrid owner who doesn't want to piece together brands.",
   "who": "Hybrid CrewMax owners on a budget.",
   "specs": [["Rows", "Full set"], ["Fits", "2022–2025 Tundra CrewMax incl. i-FORCE MAX hybrid"], ["Material", "TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$90–$130"]]},
  {"asin": "B0F7G535N3", "role": "Best bundle", "price": "$150–$200",
   "pros": ["Floor liners plus a 5.5 ft bed mat", "Names Tundra and Tundra Hybrid CrewMax", "One order covers cab and bed", "Lower cost than buying separately", "TPE liners with raised edges"],
   "cons": ["Bed mat only fits the 5.5 ft bed", "No maker documentation", "Confirm 2026"],
   "body": "AOMSAZTO's bundle pairs CrewMax floor liners with a bed mat for the 5.5 ft bed, and its title lists both the Tundra and Tundra Hybrid for 2022–2025. That makes it a neat one-order fix for a short-bed CrewMax, gas or hybrid.\n\nThe catch is the bed length: a 6.5 ft CrewMax needs a different bed mat, so check the tape measure before ordering. Like other budget brands, AOMSAZTO doesn't publish warranty or material specs we could check. If you already have a spray-in bed liner, you don't need the mat, and a standalone liner set will cost less.",
   "who": "Short-bed CrewMax owners who want cab and bed covered in one order.",
   "specs": [["Includes", "Front + rear liners, 5.5 ft bed mat"], ["Fits", "2022–2025 Tundra & Tundra Hybrid CrewMax"], ["Bed", "5.5 ft only"], ["Material", "TPE"], ["Price band", "$150–$200"]]},
  {"asin": "B0FXM1998S", "role": "Budget alternative", "price": "$80–$120",
   "pros": ["Lowest price here", "3-piece CrewMax set", "Lists 2022–2025", "TPE with raised edges", "Easy to replace"],
   "cons": ["No hybrid note", "No maker documentation", "Walls shallower than premium sets"],
   "body": "Priprilod's three-piece TPE set is listed for 2022–2025 Tundra CrewMax and is the cheapest full set here. Falafa's CrewMax set, listed for 2022–2024, is a similar alternative in our product list.\n\nBoth are sensible for a gas CrewMax in a mild climate. Neither mentions the hybrid in its title, so confirm the rear piece if you have the i-FORCE MAX. Documentation is thin, so treat them as a replaceable, price-driven buy. If you're in snow country, the extra spent on Husky buys taller walls and a crack warranty, which matter more there than anywhere else. Check the listing photos for the retention post holes on the driver liner before you order.",
   "who": "Gas CrewMax owners on the tightest budget.",
   "specs": [["Pieces", "3"], ["Fits", "2022–2025 Tundra CrewMax"], ["Material", "TPE"], ["Hybrid", "Confirm with seller"], ["Price band", "$80–$120"]]},
 ],
 "install": [
  "Confirm cab (CrewMax or Double Cab) and powertrain before ordering.",
  "Remove the factory carpet mats and vacuum the floor.",
  "Hook the driver liner onto the retention posts and heel-test it toward the pedals.",
  "Fit the passenger liner against the sill and console.",
  "Lay the rear liner, then slide and recline the rear seat (if equipped) through its range to check the track.",
  "Press the pedals to the floor to confirm clearance before driving.",
 ],
 "avoid": [
  {"h": "2014–2021 liners", "body": "The 3rd-gen floor is new. Buy 2022+ listings."},
  {"h": "CrewMax rears in a Double Cab", "body": "The rear floors differ. Only front pairs are shared."},
  {"h": "Ignoring the hybrid", "body": "The battery under the rear seat can affect the rear piece."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy Husky's WeatherBeater 99481 for a CrewMax and 99471 for a Double Cab; hybrid owners should pick a set that names the i-FORCE MAX or confirm the rear.",
  "body": "The 3rd-gen Tundra is simple once you know your cab and powertrain. Husky's WeatherBeater sets are the best documented and the only ones here cut for both cabs. LASFIT is the soft TPE choice for gas CrewMax trucks, LNZMPART and AOMSAZTO name the hybrid, and Priprilod covers the budget end.\n\nWith the cab protected, most Tundra owners turn to running boards, which help with the tall step-in and keep mud off the sill, and a tonneau cover for the bed. Sequoia owners can share Husky's front pair but need a three-row set for the rest."},
 "sources": [
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners 99481 CrewMax listing", "https://www.amazon.com/dp/B0BLQN9M6W"],
  ["Husky Liners 99471 Double Cab listing", "https://www.amazon.com/dp/B0BLR5SB3K"],
  ["Husky Liners 18571 front row (Tundra & Sequoia) listing", "https://www.amazon.com/dp/B0BLQRB44X"],
  ["LASFIT floor mats (LASFIT)", "https://www.lasfit.com/collections/floor-mats"],
  ["Toyota Tundra, third generation (Wikipedia)", "https://en.wikipedia.org/wiki/Toyota_Tundra"],
 ],
}

FITS = [
 ("B0BLQN9M6W","Husky Liners WeatherBeater 99481, 2022-2026 Tundra CrewMax only","Husky Liners","$160–$230",{"cab":"CrewMax"},"Made in USA; confirm hybrid rear."),
 ("B0BLR5SB3K","Husky Liners WeatherBeater 99471, 2022-2026 Tundra Double Cab only","Husky Liners","$150–$220",{"cab":"Double Cab"},"Double Cab only."),
 ("B0BRCVGXCX","LASFIT TPE Floor Liners front & rear, 2022-2026 Tundra CrewMax","LASFIT","$130–$170",{"cab":"CrewMax"},"CrewMax only; confirm hybrid."),
 ("B0DYP2F168","LNZMPART All-Weather Floor Liners full set, 2022-2025 Tundra CrewMax incl. hybrid","LNZMPART","$90–$130",{"cab":"CrewMax"},"Lists i-FORCE MAX hybrid."),
 ("B0F7G535N3","AOMSAZTO Floor Liners + 5.5 ft Bed Mat set, 2022-2025 Tundra / Tundra Hybrid CrewMax","AOMSAZTO","$150–$200",{"cab":"CrewMax","bed_length_in":66},"Includes a bed mat for the 5.5 ft bed."),
 ("B0FXM1998S","Priprilod TPE Floor Liners 3-piece, 2022-2025 Tundra CrewMax","Priprilod","$80–$120",{"cab":"CrewMax"},"CrewMax only."),
 ("B0DKF8HCQR","Falafa TPE Floor Liners front & rear, 2022-2024 Tundra CrewMax","Falafa","$90–$130",{"cab":"CrewMax"},"Listed to 2024; confirm 2025 with seller."),
 ("B0BLQRB44X","Husky Liners WeatherBeater 18571 Front Row, 2022-2026 Tundra CrewMax & Double Cab, 2024-2026 Sequoia","Husky Liners","$90–$130",{},"Front row only."),
]
