"""Long-form article — Best Roof Racks & Crossbars for 2023–2026 Toyota Sequoia (3rd gen, XK80, hybrid only).
Mirrors the approved pilot (ford_f150_2021_tonneau.py) and the roof-rack guides (4Runner 2025, Tahoe 2021, Highlander
2020). No invented hands-on testing. Vehicle facts: db/migrations/003_vehicles.sql; etrailer's 2023 and 2024 Sequoia
roof pages (two roof types, "Factory installed raised rails that run front to back" and "Flush mounted rails that run
front to back", no grades named, only Front Runner platforms shown, "Factory roof rails will be removed prior to
installation"); Rack Warehouse (Thule Evo Raised Rail rack for the 2001–2025 Sequoia, 165 lb, $444.90; Yakima
TimberLine FX for the 2001–2025 Sequoia, $599.90; Sequoia category page with raised-rail systems and Prinsu platforms
for 2023–2026, no flush-rail system); Rave Offroad (TRD Pro factory roof rack, 132 lb evenly distributed, 67.5 in
long, $989 sale / $1,350 regular); Toyota Newsroom releases for the 2023 reveal (five grades, 9,000 lb) and the 2025
model year (six grades, 9,520 lb; neither describes the roof rails); Wikipedia (GA-F platform, XK80, i-FORCE MAX);
Dometic (Front Runner Slimsport KSTS003T: $1,249, 105 x 54.4 in load area, 5-year warranty) and OK4WD (same kit,
103.6 lb, 2023–2024). All opened 2026-10-05. Amazon picks are identified by listing title read in amazon.com search
results; amazon.com pages cannot be fetched, so each pick says which specs come from the title only. No Toyota roof
load figure was read; the page says so and sends readers to the owner's manual. No Thule, Yakima or Rhino-Rack
listing naming the 2023+ Sequoia was found on amazon.com, so those systems are described from Rack Warehouse and are
not picks. Toyota's PT767-0C660 bars (B0C26KKRF3) and the ROSY PIXEL bars (B0DJZZLPPT) already belong to the cargo
box guide's FITS and are not repeated here.
"""

KEY = ("toyota", "sequoia", "2023-present", "roof-racks")

TITLE = "Best Roof Racks & Crossbars for 2023–2026 Toyota Sequoia: 7 Picks for Raised and Flush Rails"
META = ("Seven roof racks and crossbars listed for the 3rd-gen Sequoia, lockable bars to the Front Runner Slimsport, "
        "with the raised vs flush rail check and TRD Pro notes.")

FAQ = [
 ("What is the best roof rack for a 2023–2026 Toyota Sequoia?",
  "The Tuyoung 260 lb lockable crossbars are the best overall pick. The title names the 2023–2026 Sequoia, prints a 260 lb rating and says lockable, the only set here with both. The ANTS PART bars are the budget pick and run 2023 through 2026 by title. The Front Runner Slimsport KSTS003T is the premium platform for an overland build, with a 105 x 54.4 in deck, though OK4WD lists it at 103.6 lb before cargo. If you want a 165 lb rating in writing, Rack Warehouse sells a Thule or Yakima raised-rail kit through a dealer. Look under the rail first: etrailer lists both raised and flush rails for this Sequoia and names no grades, and the clamp has to match your rail."),
 ("Does the 2023–2026 Toyota Sequoia have raised or flush roof rails?",
  "Both exist, and we could not confirm which grades get which. etrailer lists two roof types for the 2023 and 2024 Sequoia: \"Factory installed raised rails that run front to back\" and \"Flush mounted rails that run front to back\". It names no grades, and Toyota's releases for the 2023 reveal and the 2025 model year do not describe the roof rails at all. So check your own roof. Slide your fingers under the side rail between its end mounts. A gap you can pass a strap through means raised rails. A rail that sits tight to the roof along its whole length means flush rails. Raised-rail clamps and flush-rail feet are different parts, so settle this before you order anything."),
 ("What is the roof load limit on a 2023–2026 Sequoia?",
  "We could not confirm a Toyota roof figure from any page we could open, so the owner's manual is the authority. Read its roof-load section before you load bars or a platform. The numbers we did read are modest for a full-size SUV. Rave Offroad lists the TRD Pro factory roof rack at 132 lb when the weight is evenly distributed. Rack Warehouse rates the Thule Evo Raised Rail rack for the Sequoia at 165 lb. The Tuyoung bars on this page print 260 lb in their title, which is the seller's bar figure. Use the lowest of the manual, the rack and the bars, and count the rack's own weight against it."),
 ("Do the TRD Pro's factory roof rack and the other grades' rails take the same crossbars?",
  "No. Rave Offroad describes the TRD Pro rack as a factory option on the Sequoia TRD Pro that secures into the factory roof rails, 67.5 in long, 48 in wide at the back and 51 in at the front, with a 132 lb evenly distributed limit. It is a basket, not a pair of rails, so rail-clamp crossbars have nothing to grip once it is fitted. Toyota's releases we read do not describe this rack, so we could not confirm whether every TRD Pro carries it. If your TRD Pro has the basket, use its tie-down points or ask the seller whether a carrier clamps to its tubes. If it has plain rails, the bars on this page apply like any other grade."),
 ("Will Thule or Yakima crossbars fit the 2023–2026 Sequoia?",
  "On raised rails, yes, by Rack Warehouse's fit data. It sells the Thule Evo Raised Rail rack for the 2001–2025 Sequoia at $444.90 with a 165 lb rating, and Yakima's TimberLine FX for the same years at $599.90, both for factory raised side rails and both without splitting the generations. We found no Thule or Yakima kit for a flush-rail Sequoia at Rack Warehouse or on etrailer, whose 2023 and 2024 pages show only Front Runner platforms. We also found no Thule or Yakima Amazon listing that names the 2023 or later Sequoia, so neither is a pick here. If your rails are raised, order through a rack dealer and have them confirm the bar length for your model year."),
 ("Do 2008–2022 Sequoia roof racks fit the 2023–2026 Sequoia?",
  "Do not assume so. The third-generation Sequoia moved to the GA-F platform shared with the Tundra, with a new body and roof, and the Amazon listings on this page all name 2023 or later. Rack Warehouse's Thule and Yakima raised-rail pages cover 2001 through 2025 as one span, which says the clamps adapt to a range of rail shapes, not that the two roofs are the same. Rack Warehouse also lists separate Prinsu platforms for the 2008–2022 and the 2023–2026 Sequoia. Buy bars whose title names your year, and keep any used 2008–2022 rack out of the cart unless the seller confirms it by model year."),
 ("Are Sequoia crossbars the same as Tundra crossbars?",
  "No. The Sequoia and Tundra share the GA-F platform, and our fitment notes flag a different roof. A pickup cab has no long roof with side rails front to back, so Tundra listings are for a different part. The Front Runner Slimsport on this page is sold under its own Sequoia part number, KSTS003T, and every crossbar title here names the Sequoia. Buy by the Sequoia name and the year, not by the shared platform."),
 ("Which crossbars cover the 2025 and 2026 Sequoia?",
  "By title, the Tuyoung 260 lb bars, the ANTS PART bars, the Heavy-Duty bars, the cargo basket and crossbar kit and the rooftop platform all run 2023 through 2026. The Front Runner Slimsport is listed on Amazon as 2023-Current, though OK4WD lists the same kit for 2023–2024. The ALLMyHomy OE-style bars stop at 2024 in the title we read. Toyota's 2025 release added the 1794 grade and its 2026 release made power folding third-row seats standard; neither describes a roof change, but we could not confirm the rails are unchanged either. If your Sequoia is newer than the listing's last year, choose a listing that names your year or get the seller's answer in writing."),
 ("Do crossbars work with the Sequoia's panoramic moonroof?",
  "Toyota's 2025 release lists a standard panoramic moonroof on the Platinum and a panoramic roof on the 1794 grade. Crossbars sit on the side rails above the glass line, so the bars themselves are not the issue. What to check is the load: a cargo box's front edge, a basket's fairing or a bike's front wheel can sit over the glass. Front Runner says the Slimsport's fairing cutout keeps moonroof functionality on the Sequoia kit. For any set here, load the rack, then open the moonroof once while parked and watch what moves before you drive."),
 ("Should I buy crossbars, a basket or a full platform for a Sequoia?",
  "Buy for what you carry. Two bars take a cargo box, skis, a kayak or bikes and weigh the least, which matters on a roof whose published figures run 132 to 165 lb. A basket adds walls for loose gear and a place to strap a cooler, at the cost of noise and weight. A platform like the Front Runner Slimsport gives a flat 105 x 54.4 in deck with T-slots for light bars, tents and cases, but OK4WD lists it at 103.6 lb before you add anything, and etrailer says the factory rails come off to fit Front Runner's Sequoia platforms. For most families, bars first, then a cargo box; a platform suits owners building an overland rig."),
 ("Are the budget Amazon crossbars safe for a cargo box or kayak?",
  "They are sold for it, and every title here names the Sequoia and its years, but the proof is thinner than with Thule or Yakima. Only the Tuyoung title prints a rating, 260 lb, and says lockable. The ANTS PART, Heavy-Duty and ALLMyHomy titles print no rating. We could not open an amazon.com page to read clamp details or warranty terms, so compare the clamp in the listing photos with your rail, keep the total under the figure in your owner's manual, and recheck the clamps after the first week and after any long trip with a box on. For a box left on all year, the Thule or Yakima raised-rail kits from a rack dealer are the safer money."),
]

ARTICLE = {
 "dek": "The third-generation Sequoia is a hybrid-only, three-row SUV whose side rails come raised on some vehicles and flush on others, and whose roof figure Toyota does not publish where we could find it. Here are seven roof racks and crossbars whose Amazon listings name the 2023 or later Sequoia, from lockable 260 lb bars to a basket kit and the Front Runner Slimsport platform, plus the Thule and Yakima raised-rail kits Rack Warehouse sells and the TRD Pro factory rack, with the rail check that comes before any of them.",
 "author": "jake-morrison",
 "reviewed": "2026-10-05",
 "method": "We did not install these racks ourselves. Picks were chosen on the fitment each seller states for the 2023–2026 Sequoia in its Amazon listing title, on the years named, on printed load ratings and locks, and by comparison with the Thule and Yakima raised-rail systems Rack Warehouse lists for the Sequoia, the Front Runner platforms etrailer lists, and the TRD Pro factory rack Rave Offroad lists. Front Runner specs were read at Dometic and OK4WD in October 2026. Amazon product pages cannot be opened by us, so where a spec comes only from a listing title we say so. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Check the rails before anything else.** etrailer lists both \"Factory installed raised rails\" and \"Flush mounted rails\" for the 2023 and 2024 Sequoia and names no grades. A gap under the rail means raised; no gap means flush.",
  "**No Toyota roof figure where we could find one.** Rave Offroad lists the TRD Pro factory rack at 132 lb evenly distributed, and Rack Warehouse rates the Thule raised-rail kit at 165 lb. Your owner's manual is the authority.",
  "**Thule and Yakima fit raised rails only, through a dealer.** Rack Warehouse sells both for the 2001–2025 Sequoia without splitting generations. No flush-rail kit and no Amazon listing naming this Sequoia turned up.",
  "**The TRD Pro's factory rack is a basket, not rails.** Rave Offroad says it secures into the roof rails, 67.5 in long, 132 lb. Rail-clamp bars have nothing to grip on it.",
  "**Platforms replace the rails and weigh a lot.** etrailer says the factory rails come off for Front Runner's Sequoia platforms, and OK4WD lists the Slimsport at 103.6 lb before cargo.",
 ],
 "top_picks": [
  {"asin": "B0DNF26C5V", "role": "Best overall crossbars", "why": "Tuyoung title names the 2023–2026 Sequoia, prints 260 lb and says lockable, the only set here with both"},
  {"asin": "B0DCBLSSQS", "role": "Best budget crossbars", "why": "ANTS PART title runs 2023–2026, covering the whole generation by year"},
  {"asin": "B0CLDF4H9K", "role": "Best premium platform", "why": "Front Runner Slimsport KSTS003T: 105 x 54.4 in T-slot deck, light bar cutout, specs on the maker's page"},
  {"asin": "B0DK8HSMFL", "role": "Best basket kit", "why": "Basket and crossbars in one listing titled for the 2023–2026 Sequoia"},
  {"asin": "B0DFPJPJYX", "role": "Best factory-style bars", "why": "ALLMyHomy bars sold as a PT767-0C660 OE-style replacement for the 2023–2024 Sequoia"},
 ],
 "fit_table": {
  "caption": "2023–2026 Sequoia roofs: what the rack has to match",
  "head": ["Roof as delivered", "How to tell", "What fits", "Source"],
  "rows": [
   ["Factory raised side rails", "A gap under the rail between its end mounts", "Rail-clamp crossbars; Thule Evo Raised Rail or Yakima TimberLine FX through a dealer; Front Runner Slimsport with rails removed", "etrailer 2023 and 2024 roof pages; Rack Warehouse"],
   ["Flush side rails", "Rail sits tight to the roof, no gap", "Side-clamp bars shown gripping a flush rail in the listing photos; Front Runner Slimline II with rails removed", "etrailer 2023 and 2024 roof pages"],
   ["TRD Pro factory roof rack", "A 67.5 in basket in the rails", "Use its tie-down points; rail clamps have nothing to grip", "Rave Offroad"],
   ["Grades: SR5, Limited, Platinum, 1794 (2025+), TRD Pro, Capstone", "Rail type not stated by grade", "Look at the roof, not the badge", "Toyota 2023 reveal and 2025 release; etrailer names no grades"],
   ["Panoramic moonroof (Platinum, 1794 per Toyota)", "Glass between the rails", "Bars clear it; watch what the load sits over", "Toyota 2025 release; Dometic (Slimsport cutout)"],
   ["Roof load", "Not confirmed from Toyota", "Owner's manual; TRD Pro rack 132 lb, Thule kit 165 lb", "Rave Offroad; Rack Warehouse"],
  ],
 },
 "look_for": [
  {"h": "Raised or flush: the first thing to settle",
   "body": "This Sequoia is unusual because the rail type is not fixed across the lineup. etrailer's roof pages for the 2023 and the 2024 Sequoia each list two roof types, \"Factory installed raised rails that run front to back\" and \"Flush mounted rails that run front to back\", and neither page says which grades get which. Toyota's 2023 reveal and its 2025 release say nothing about the rails. So the roof decides, not the brochure. Slide your fingers under the side rail between its end mounts. A gap means raised rails, and clamp-style bars or the Thule and Yakima raised-rail kits fit. No gap means flush rails, and you need clamps built to grip a flush rail from the side. None of the Amazon titles here says raised or flush, so compare the clamp in each listing's photos with your rail before ordering."},
  {"h": "A roof figure Toyota keeps in the manual",
   "body": "We could not open a Toyota page that states the Sequoia's roof load, and our vehicle data holds no figure, so the owner's manual is the authority. What we could read is lower than most owners expect for a vehicle this size. Rave Offroad lists the TRD Pro factory roof rack at 132 lb when the weight is evenly distributed. Rack Warehouse rates its Thule Evo Raised Rail rack for the Sequoia at 165 lb. The Tuyoung bars print 260 lb, which is the seller's figure for the bars, not the roof. The rack's own weight counts against the limit while driving: OK4WD lists the Front Runner Slimsport at 103.6 lb, which under a figure like 132 lb leaves under 30 lb for cargo. Use the lowest number you find, and add bars, carrier and gear together."},
  {"h": "Years in the title, and the 2025 and 2026 changes",
   "body": "The third generation started with the 2023 model year. Toyota's 2025 release added the 1794 grade and made the 2025 lineup six grades, and its 2026 release made power folding third-row seats standard on all grades. Neither release describes a roof change, but neither describes the roof at all, so we could not confirm the rails are unchanged. The safe rule is the title. The Tuyoung, ANTS PART, Heavy-Duty, basket kit and platform titles run 2023 through 2026. The Front Runner Slimsport is listed on Amazon as 2023-Current, while OK4WD lists it for 2023–2024. The ALLMyHomy OE-style bars stop at 2024. If your Sequoia is newer than a listing's last year, pick another set or ask the seller."},
  {"h": "Bars, basket or platform on a long roof",
   "body": "etrailer lists Front Runner's Sequoia platforms at 103-13/16 and 105 in long by 54-7/16 in wide, which tells you how much roof there is to use. Two crossbars use a fraction of it and weigh the least, and they take a cargo box, skis, a kayak or bike mounts. A basket adds rails to strap loose gear against, plus wind noise and weight. A platform gives a flat deck with T-slots for a light bar, a tent or cases, and Front Runner's Sequoia kit includes a fairing with a 40 in cutout for its slim light bar. The cost is weight and the rails: etrailer says the factory roof rails will be removed before a Front Runner platform goes on. For a family carrying a box a few times a year, bars are enough. A platform is an overland build."},
  {"h": "Ratings, locks and the proof behind them",
   "body": "Only one Amazon title here prints a load rating, the Tuyoung at 260 lb, and only the Tuyoung title says lockable. The ANTS PART, Heavy-Duty and ALLMyHomy titles print neither, and the basket kit and platform titles give size words rather than numbers. We could not open an amazon.com page to read clamp material, bar length or warranty terms, so those are the listing's to tell you. The brand-name systems publish more: Rack Warehouse rates the Thule Evo Raised Rail rack at 165 lb, says it needs no drilling, and lists Thule One-Key lock cores as a separate buy. Dometic gives the Slimsport's deck size and a 5-year warranty. If bars stay on a Sequoia that parks outside, locks are worth the small extra cost, and taking the bars off between trips saves fuel and theft worry at once."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Fitment", "2023 or later Sequoia named in the title, with your model year", "\"Fits most SUVs\", Tundra bars, or 2008–2022 Sequoia bars"],
   ["Rail match", "A clamp in the photos that matches your raised or flush rail", "Ordering before you have looked under the rail"],
   ["Load rating", "A printed number, read beside the owner's manual figure", "Loading to the bar rating"],
   ["Rack weight", "A published weight you can subtract from the roof figure", "A 100 lb platform on a roof figure near 132 lb"],
   ["Security", "Lockable in the title, or lock cores sold for the system", "Unlocked bars left on in public lots"],
   ["Warranty", "Terms you can read (Dometic 5 years; Thule and Yakima limited lifetime)", "Nothing stated on the listing"],
  ],
 },
 "types_table": {
  "caption": "Roof rack options for the 2023–2026 Sequoia (brand-name prices as read in October 2026)",
  "head": ["Option", "Mounts to", "Price seen", "Rating", "Weight", "Notes"],
  "rows": [
   ["Amazon crossbars (four picks)", "Side rails; clamp per listing photos", "Check listing", "260 lb printed (Tuyoung); others not in title", "Not in title", "Cheapest route; specs from titles"],
   ["Amazon basket and crossbar kit", "Side rails via the bars", "Check listing", "Not in title", "Not in title", "Walls for loose gear; more noise"],
   ["Amazon rooftop platform", "Per listing", "Check listing", "Not in title", "Not in title", "Confirm mounting and rail removal with seller"],
   ["Front Runner Slimsport KSTS003T", "Integrated feet and brace brackets; rails removed per etrailer", "$1,249 (Dometic, OK4WD)", "Not published", "103.6 lb (OK4WD)", "105 x 54.4 in deck, light bar cutout, 5-year warranty (Dometic)"],
   ["Front Runner Slimline II (flush rails)", "Fixed mount, rails removed", "$2,299 (etrailer, FR65PF)", "Not published", "Not published", "The one flush-rail system etrailer lists"],
   ["Thule Evo Raised Rail rack", "Factory raised rails, no drilling", "$444.90 (Rack Warehouse)", "165 lb", "Not published", "2001–2025 Sequoia as one span; dealer order"],
   ["Yakima TimberLine FX", "Factory raised rails", "$599.90 (Rack Warehouse)", "Not on the page", "Not published", "2001–2025 Sequoia as one span; dealer order"],
   ["TRD Pro factory roof rack", "Secures into the factory roof rails", "$989 sale, $1,350 regular (Rave Offroad)", "132 lb evenly distributed", "80 lb shipping", "67.5 in long; TRD Pro factory option"],
  ],
 },
 "picks": [
  {"asin": "B0DNF26C5V", "role": "Best overall crossbars", "price": "Check listing",
   "pros": ["Title names the Toyota Sequoia 2023–2026, the full generation", "260 lb printed rating, the only rating on this page's bar titles", "Lockable, per the title", "Aluminum bars, per the listing", "Tuyoung sells vehicle-specific sets for many SUVs, so the clamp is a known design"],
   "cons": ["260 lb is the seller's bar figure, far above the 132 to 165 lb figures we read for this roof", "Title does not say raised or flush; check the clamp photos", "No maker page we could open; warranty from the listing only"],
   "body": "Tuyoung's set is the pick for most Sequoia owners because its title does the most work. It names the Toyota Sequoia 2023–2026, so a 2025 or 2026 owner is covered by the title rather than by a seller's reply. It prints 260 lb, the only rating on any crossbar title here. And it says lockable, which matters on a tall SUV that parks outside, since an unlocked bar lifts off in a minute. The listing describes aluminum bars. Tuyoung sells near-identical sets for other three-row SUVs on our pages, so the clamp design is a known quantity even though we could not open this listing.\n\nTreat the 260 lb as what it is. Rave Offroad lists the TRD Pro factory rack at 132 lb and Rack Warehouse rates the Thule raised-rail kit at 165 lb, and Toyota's roof figure is in the owner's manual, not on any page we could read. The bar rating tells you the bar will not be the weak point under a loaded cargo box; it does not raise the roof's limit. The title does not say whether the clamp is made for a raised rail or a flush rail, and etrailer lists both for this Sequoia, so look at the clamp in the photos against your own rail before ordering. Bar length, clamp material and warranty come from the listing page. Recheck the clamps after the first week and after any long trip with a box on.",
   "who": "Owners who leave bars on year-round, park in public, and want a rating and a lock in the title.",
   "specs": [["Type", "Side-rail crossbars, lockable"], ["Fits", "2023–2026 Toyota Sequoia (per title)"], ["Rail type", "Not in title; match the clamp photos to your rail"], ["Material", "Aluminum (per listing)"], ["Load rating", "260 lb (printed by seller)"], ["Locks", "Yes (per title)"], ["Warranty", "See listing"]]},
  {"asin": "B0DCBLSSQS", "role": "Best budget crossbars", "price": "Check listing",
   "pros": ["Title names the 2023–2026 Toyota Sequoia", "Covers the 2025 and 2026 model years by title", "Aluminum crossbars sold for skis and snowboards as well as luggage, per the listing", "Simple two-bar set with the least to go wrong", "Lowest price class on this page"],
   "cons": ["No load rating in the title", "No lock in the title; check the listing", "Clamp design and rail type only from the listing photos"],
   "body": "ANTS PART's bars are the plain budget choice. The title names the 2023–2026 Toyota Sequoia and nothing else, which is the first filter and the one that matters most: every model year of the generation so far is in it. The listing describes black aluminum crossbars sold for luggage, skis and snowboards. There is no rating and no lock in the title, so read the listing page for both before you decide, and plan the load around the owner's manual figure rather than anything the seller prints.\n\nWhat you give up against the Tuyoung set is the rating and the lock in writing. What you give up against the Thule and Yakima raised-rail kits at Rack Warehouse, $444.90 and $599.90, is a published 165 lb figure, a named clamp for a named rail type, and a dealer who checks the bar length for your year. For a family that carries a cargo box or skis a few times a season and takes the bars off in between, that trade is reasonable. As with every Amazon set here, we could not open the page, so compare the clamp in the photos with your raised or flush rail, confirm the bar length clears the rails' spacing, and tighten in steps side to side.",
   "who": "Budget buyers with a Sequoia of any model year who will read the listing for the rating and lock details.",
   "specs": [["Type", "Side-rail crossbars"], ["Fits", "2023–2026 Toyota Sequoia (per title)"], ["Rail type", "Not in title; match the clamp photos to your rail"], ["Material", "Aluminum (per listing)"], ["Load rating", "Not in title; check listing"], ["Locks", "Not in title; check listing"], ["Warranty", "See listing"]]},
  {"asin": "B0D59LFNMR", "role": "Best heavy-duty bars for 2023–2026", "price": "Check listing",
   "pros": ["Title names the 2023–2026 Toyota Sequoia", "Sold as heavy-duty aluminum bars, per the title", "Full generation by year", "Listed for luggage carriers and cargo, per the listing", "A second full-span set if the Tuyoung or ANTS PART bars are out of stock"],
   "cons": ["\"Heavy-duty\" with no number in the title", "No lock in the title", "No maker page we could open"],
   "body": "This set is the second full-span alternative on the page. Its title names the 2023–2026 Toyota Sequoia and calls the bars heavy-duty aluminum, which is the kind of wording our look table warns about: a strength claim without a number. Read the listing page for the figure, and if there is none, plan around the owner's manual and the 165 lb Thule kit rating as your working number. The title does not mention a lock either, so a set that stays on a Sequoia in a public lot needs the Tuyoung instead.\n\nWhy list it at all? Stock. Budget crossbar listings come and go, and the Sequoia is a low-volume vehicle next to a RAV4 or Highlander, so having a second and third title that names the whole generation gives you a fallback that still passes the year test. The same cautions apply: we could not open the amazon.com page, so the clamp style, bar length and warranty are the listing's to tell you. Hold the clamp photos against your rail, raised or flush, and if the photos do not make the clamp clear, send the seller a photo of your rail before you buy. Set the bars at the spread your box or carrier asks for, and recheck them after the first drive.",
   "who": "Owners who want a full-span fallback when the other 2023–2026 sets are unavailable.",
   "specs": [["Type", "Side-rail crossbars"], ["Fits", "2023–2026 Toyota Sequoia (per title)"], ["Rail type", "Not in title; match the clamp photos to your rail"], ["Material", "Aluminum, sold as heavy-duty (per title)"], ["Load rating", "Not in title; check listing"], ["Locks", "Not in title; check listing"], ["Warranty", "See listing"]]},
  {"asin": "B0DFPJPJYX", "role": "Best factory-style bars", "price": "Check listing",
   "pros": ["Title names the 2023 and 2024 Toyota Sequoia and cites OE part PT767-0C660", "Sold as an all-metal, heavy-duty replacement for Toyota's own bars", "Factory look on a low-profile bar", "Listed for kayak, luggage, ski and bike carriers", "An alternative to dealer pricing on the genuine bars"],
   "cons": ["Title stops at 2024; 2025 and 2026 owners should confirm or choose another set", "No load rating or lock in the title", "OE reference is the seller's claim; Toyota's rating for the genuine bars is not published where we looked"],
   "body": "ALLMyHomy sells these as an OE-style set and prints Toyota's part number, PT767-0C660, in the title. That is the genuine Toyota crossbar sold for the 2023 and later Sequoia, which our cargo box guide covers, and owners there describe a low-profile bar with caps over the mounting screws. An OE-style replacement is the choice if you want that factory look without dealer pricing, and if you already know your rails suit Toyota's own bars. The title names the 2023 and 2024 Sequoia, describes all-metal, heavy-duty crossbars, and lists kayak, luggage, ski and bike carriers as uses.\n\nTwo things to confirm. First, the years: the title stops at 2024. Toyota's 2025 and 2026 releases describe no roof change, but they describe nothing about the roof, so a 2025 or 2026 owner should get the seller's answer in writing or buy a 2023–2026 title instead. Second, the mount: Toyota's bars attach to the factory rails, and we could not confirm from any page whether the genuine part suits both the raised and the flush rails etrailer lists, let alone this copy of it. Compare the mounting feet in the photos with your rail. There is no rating or lock in the title, and the OE reference is the seller's claim, so the owner's manual still sets your load.",
   "who": "2023–2024 owners who want a factory-look bar and will match the feet to their rails first.",
   "specs": [["Type", "OE-style crossbars (seller references PT767-0C660)"], ["Fits", "2023–2024 Toyota Sequoia (per title)"], ["Rail type", "Not in title; match the feet in the photos to your rail"], ["Material", "All metal, sold as heavy-duty (per title)"], ["Load rating", "Not in title; check listing"], ["Locks", "Not in title; check listing"], ["2025–2026", "Not named; confirm with seller"], ["Warranty", "See listing"]]},
  {"asin": "B0DK8HSMFL", "role": "Best basket kit", "price": "Check listing",
   "pros": ["Basket and crossbars in one listing titled for the 2023–2026 Sequoia", "Aluminum, per the title", "Walls to strap coolers, bins and loose gear against", "Full generation by year", "Cheaper than a platform and keeps the factory rails"],
   "cons": ["No basket size, rating or weight in the title", "More wind noise than bars alone", "Basket weight comes out of a roof figure we could not confirm"],
   "body": "If what you carry is loose, a cooler, bins, firewood, a spare tire, a basket beats a pair of bare bars because it gives you walls to strap against. This kit bundles the basket and the crossbars it sits on, and the title names the Toyota Sequoia 2023, 2024, 2025 and 2026 and calls it aluminum. Buying the two together removes the usual question of whether a universal basket's clamps match the bars, and the bars keep the factory rails in place, unlike a Front Runner platform.\n\nThe title gives no basket dimensions, load rating or weight, and we could not open the page, so all three come from the listing. Weight is the one to read first. Rave Offroad lists the TRD Pro factory basket at 132 lb evenly distributed and Rack Warehouse rates the Thule kit at 165 lb; an aluminum basket plus bars takes a real share of a figure like that before the first cooler goes in. A basket also adds wind noise on a highway drive, so look for a fairing in the listing or budget for one. Match the bar clamps in the photos to your raised or flush rail, set the bars at the spread the basket's feet need, and strap the load to the basket rails, not just the floor.",
   "who": "Owners who haul loose gear, coolers and bins and want a basket matched to its own bars.",
   "specs": [["Type", "Cargo basket plus crossbars"], ["Fits", "2023–2026 Toyota Sequoia (per title)"], ["Rail type", "Not in title; match the clamp photos to your rail"], ["Material", "Aluminum (per title)"], ["Basket size", "Not in title; check listing"], ["Load rating", "Not in title; check listing"], ["Fairing", "Not in title; check listing"], ["Warranty", "See listing"]]},
  {"asin": "B0DK6SJ6Z5", "role": "Best budget platform", "price": "Check listing",
   "pros": ["Flat rooftop platform titled for the 2023–2026 Toyota Sequoia", "Aluminum, per the title", "A deck for cases, boards and a tent at a fraction of the Front Runner price", "Full generation by year", "Sold with the Sequoia name, not as a universal cut-to-fit deck"],
   "cons": ["No deck size, rating or weight in the title", "Mounting method not in the title; confirm whether the rails come off", "A platform's weight counts against a roof figure as low as 132 lb"],
   "body": "This is the low-cost route to a flat deck. The title names the 2023–2026 Toyota Sequoia and describes an aluminum rooftop platform cargo carrier, which is the same idea as the Front Runner Slimsport, a flat surface for recovery boards, cases and a rooftop tent, at a much lower price class. For an owner who wants the overland look and a place to mount a light bar without spending four figures, it is the listing to read first.\n\nRead it closely. The title gives no deck size, no load rating and no weight, and it does not say how the platform mounts. etrailer says Front Runner's Sequoia platforms go on with the factory roof rails removed, and this listing may or may not work the same way, so ask the seller whether it sits on the rails, clamps to them or replaces them, and whether it suits raised rails, flush rails or both. Weight is the other number to get before you buy: OK4WD lists the Front Runner at 103.6 lb, and any aluminum deck this size will be heavy next to the 132 lb TRD Pro rack figure and the 165 lb Thule kit rating. If the seller cannot give you a weight and a rating, that is your answer. If they can, a platform at this price is a sensible way to try the format.",
   "who": "Owners who want a flat deck for overland gear on a budget and will get the mounting and weight answers first.",
   "specs": [["Type", "Rooftop platform"], ["Fits", "2023–2026 Toyota Sequoia (per title)"], ["Mounting", "Not in title; ask whether the rails stay"], ["Material", "Aluminum (per title)"], ["Deck size", "Not in title; check listing"], ["Load rating", "Not in title; check listing"], ["Weight", "Not in title; ask the seller"], ["Warranty", "See listing"]]},
  {"asin": "B0CLDF4H9K", "role": "Best premium platform", "price": "$1,200–$1,300",
   "pros": ["Sequoia-specific kit KSTS003T, listed on Amazon as 2023-Current", "105 x 54.4 in load area in T-slot aluminum slats (Dometic)", "Wind fairing with a 40 in cutout for Front Runner's slim light bar; keeps the moonroof usable (Dometic)", "5-year warranty on Dometic's page", "Integrated mounting feet with brace brackets, hardware and fitment guide included"],
   "cons": ["$1,249 at Dometic and OK4WD, the most expensive rack here", "103.6 lb per OK4WD, before any cargo", "etrailer says the factory rails come off for Front Runner's Sequoia platforms"],
   "body": "Front Runner's Slimsport is the platform with specs you can read. Dometic, which now sells Front Runner, lists the Sequoia kit KSTS003T at $1,249 with a 2666 by 1383 mm load area, 105 by 54.4 in, built from high-strength aluminum slats with T-slots for Front Runner's top-mount accessories. The kit includes a wind fairing with a 40 in cutout for Front Runner's slim LED light bar, which Dometic says keeps the moonroof usable, plus integrated mounting feet, brace brackets, hardware and a fitment guide, and a 5-year warranty. OK4WD lists the same kit at $1,249, 103.6 lb, for the 2023–2024 Sequoia, and notes it needs Front Runner's RRAC213 for installation and does not take under-rack tables or some side-mount brackets. The Amazon title is the Lightbar Ready kit for the Sequoia 2023-Current.\n\nThe weight is the decision. At 103.6 lb the rack alone exceeds half of the 165 lb Thule kit rating and sits under the 132 lb TRD Pro rack figure by less than 30 lb, and Toyota's own roof figure is in the manual. Neither Dometic nor OK4WD publishes a load rating for the kit, so ask before you plan a tent. The other cost is the rails: etrailer lists Front Runner's 105 in Slimsport for the raised-rail Sequoia and says the factory roof rails will be removed before installation, and it lists a Slimline II at $2,299 for the flush-rail roof with the same note. Keep every rail bolt in case you go back to stock.",
   "who": "Overland builders who want a documented full-length deck with a light bar slot and accept the weight and the rail removal.",
   "specs": [["Type", "Full-length aluminum platform"], ["Part #", "KSTS003T (Lightbar Ready)"], ["Fits", "Sequoia 2023-Current (Amazon title); 2023–2024 (OK4WD)"], ["Load area", "105 x 54.4 in (Dometic)"], ["Weight", "103.6 lb (OK4WD)"], ["Load rating", "Not published; ask Front Runner"], ["Mounting", "Integrated feet and brace brackets; rails removed per etrailer"], ["Fairing", "Included, 40 in light bar cutout"], ["Warranty", "5 years (Dometic)"]]},
 ],
 "install": [
  "Identify the roof: raised rails with a gap underneath, flush rails with no gap, or the TRD Pro factory basket. Crossbars need rails; a basket kit sits on its own bars; Front Runner's platforms go on with the rails removed, per etrailer.",
  "Read the roof-load section of the owner's manual and write the figure down. Subtract the rack's weight, 103.6 lb for the Slimsport per OK4WD, before you plan cargo.",
  "Clean the rails where the clamps or feet will sit. Grit under a pad scratches the finish and lets a clamp creep.",
  "For crossbars, set the spread your box, basket or carrier asks for, center the bars side to side, and tighten the clamps in steps, left and right, to the listing's torque. Lock them if the set has locks.",
  "For a platform that replaces the rails, unbolt the rails, keep every bolt and seal, fit the feet and brace brackets with the hardware supplied, and torque to the kit's figures with a second person holding a deck this size.",
  "Open the moonroof and the power liftgate while parked with the rack and any load fitted, and watch for contact.",
  "Recheck every clamp or bolt after the first week and after any long trip, and take bars off between trips to save fuel and theft risk.",
 ],
 "avoid": [
  {"h": "Buying clamps before looking under the rail", "body": "etrailer lists both raised and flush rails for this Sequoia and names no grades. Raised-rail clamps have nothing to grip on a flush rail. Look first."},
  {"h": "Rail-clamp bars on a TRD Pro with the factory basket", "body": "Rave Offroad says the factory rack secures into the rails and spans 67.5 in. Bars have nowhere to clamp once it is on."},
  {"h": "Loading to the bar rating", "body": "A 260 lb bar does not change the roof figure in the manual, the 132 lb TRD Pro rack figure or the 165 lb Thule kit rating. Add rack, carrier and cargo."},
  {"h": "Tundra or 2008–2022 Sequoia racks", "body": "Different roof. Every listing here names 2023 or later, and Rack Warehouse sells separate Prinsu platforms for 2008–2022 and 2023–2026."},
 ],
 "verdict": {
  "thesis": "Look under the rail first, then buy the Tuyoung 260 lb lockable bars for most Sequoias, the ANTS PART set on a budget, the Front Runner Slimsport if you are building an overland rig, or a Thule or Yakima raised-rail kit through a dealer if you want a 165 lb rating in writing.",
  "body": "The third-gen Sequoia is an easy roof once three things are settled: whether your rails are raised or flush, what the owner's manual allows, and whether a TRD Pro basket is already up there. After that, the Tuyoung set is the only crossbar title here with a rating and a lock, ANTS PART and the Heavy-Duty bars cover the whole generation for less, and ALLMyHomy gives 2023–2024 owners a factory look. The basket kit suits loose gear, the budget platform is worth a look if the seller can give you a weight and a rating, and the Front Runner Slimsport is the documented choice at $1,249 and 103.6 lb. If you want proof rather than titles on raised rails, Rack Warehouse's Thule Evo Raised Rail rack is $444.90 at 165 lb and Yakima's TimberLine FX is $599.90, both covering the 2001–2025 Sequoia as one span.\n\nWith bars on, a rooftop cargo box is the usual next step, and our Sequoia cargo box guide covers the boxes and Toyota's own PT767-0C660 bars. On a 75 in tall SUV, running boards make the reach to the roof easier and give you a place to stand while you strap a load, and our running boards guide covers Go Rhino and the power steps. For heavy gear, the Class IV trailer hitch our data lists takes a hitch cargo carrier that keeps the weight off the roof entirely.",
 },
 "sources": [
  ["2023 Toyota Sequoia roof rack systems: \"Factory installed raised rails\" and \"Flush mounted rails\", Front Runner platforms, rails removed (etrailer)", "https://www.etrailer.com/roof-2023_toyota_sequoia.htm"],
  ["2024 Toyota Sequoia roof rack systems: same two roof types, Front Runner FR56FB, FR36FB and FR65PF (etrailer)", "https://www.etrailer.com/roof-2024_toyota_sequoia.htm"],
  ["Thule Evo Raised Rail rack for the 2001–2025 Toyota Sequoia, 165 lb, $444.90 (Rack Warehouse)", "https://www.rackwarehouse.com/products/thule-evo-raised-rail-rack/vehicle/toyota/sequoia/"],
  ["Yakima TimberLine FX for the 2001–2025 Toyota Sequoia, raised rails, $599.90 (Rack Warehouse)", "https://www.rackwarehouse.com/products/yakima-timberline-fx-complete-rack/vehicle/toyota/sequoia/"],
  ["Toyota Sequoia roof racks: raised-rail systems and Prinsu platforms for 2008–2022 and 2023–2026 (Rack Warehouse)", "https://www.rackwarehouse.com/categories/roof-racks/vehicle/toyota/sequoia/"],
  ["TRD Pro roof rack for 2023+ Sequoia: 132 lb evenly distributed, 67.5 in long, $989 sale (Rave Offroad)", "https://raveoffroad.com/products/trd-pro-roof-rack-for-2023-sequoia"],
  ["Front Runner Slimsport Roof Rack Kit / Light Bar Ready KSTS003T: $1,249, 105 x 54.4 in, 5-year warranty (Dometic)", "https://www.dometic.com/en-us/product/toyota-sequoia-roofrack-slimsport-kit-lightbar-ready-ksts003t"],
  ["Front Runner Slimsport KSTS003T: $1,249, 103.6 lb, 2023–2024 Sequoia (OK4WD)", "https://ok4wd.com/toyota-sequoia-2023-current-slimsport-roof-rack-kit-lightbar-ready-ksts003t/"],
  ["Standing Tall: All-New 2023 Sequoia, January 2022 reveal: five grades, 9,000 lb towing, no roof rail details (Toyota Newsroom)", "https://pressroom.toyota.com/standing-tall-all-new-2023-sequoia-full-size-suv-is-ready-to-make-its-mark/"],
  ["2025 Sequoia Adds 1794 Grade and More: six grades, panoramic moonroof on Platinum and 1794, 9,520 lb, no roof rail details (Toyota Newsroom)", "https://pressroom.toyota.com/2025-sequoia-adds-1794-grade-and-more/"],
  ["Toyota Sequoia third generation: GA-F platform, XK80, i-FORCE MAX, grades (Wikipedia)", "https://en.wikipedia.org/wiki/Toyota_Sequoia"],
 ],
}

# Product list for this page. (asin, name, brand, band, cond, note) — picks first, then extra verified listings.
# No title on this page says raised or flush, and etrailer lists both rail types for this Sequoia without naming grades,
# so roof_type is left out of cond; every note sends the buyer to the clamp photos.
# Titles were read in amazon.com search results on 2026-10-05; amazon.com pages cannot be fetched.
FITS = [
 ("B0DNF26C5V","Tuyoung 260lbs Lockable Roof Rack Cross Bars for Toyota Sequoia 2023-2026, aluminum","Tuyoung","Check listing",{},"Seller-printed 260 lb; roof figure still applies. Match the clamp photos to your raised or flush rail."),
 ("B0DCBLSSQS","ANTS PART Roof Rack Cross Bars for 2023-2026 Toyota Sequoia, aluminum, black","ANTS PART","Check listing",{},"Rating and locks not in title; confirm on listing and match the clamp to your rail."),
 ("B0D59LFNMR","Heavy-Duty Roof Rack Cross Bars for 2023-2026 Toyota Sequoia, aluminum luggage carrier","Generic","Check listing",{},"No rating in title; confirm on listing and match the clamp to your rail."),
 ("B0DFPJPJYX","ALLMyHomy Roof Rack Cross Bars for Toyota Sequoia 2023-2024, heavy duty all metal, OE PT767-0C660 style","ALLMyHomy","Check listing",{},"Title stops at 2024; confirm 2025-2026 and the rail match with the seller."),
 ("B0DK8HSMFL","Roof Rack Cargo Basket & Cross Bars Kit for Toyota Sequoia 2023-2026, aluminum, black","Generic","Check listing",{},"Basket size, rating and weight not in title; confirm on listing."),
 ("B0DK6SJ6Z5","Roof Rack Cargo Carrier Rooftop Platform for 2023-2026 Toyota Sequoia, aluminum, black","Generic","Check listing",{},"Mounting, deck size, rating and weight not in title; confirm whether the rails stay."),
 ("B0CLDF4H9K","Front Runner Slimsport Roof Rack Kit / Lightbar Ready, Toyota Sequoia (2023-Current), KSTS003T","Front Runner","$1,200–$1,300",{},"$1,249 at Dometic and OK4WD; 103.6 lb; rails removed per etrailer; no published load rating."),
 ("B0CX5FLJYT","Cross Bar for Toyota Sequoia 2023-2025, crossbars luggage cargo carrier roof rack, black, 2 pcs","Generic","Check listing",{},"Listed to 2025; confirm 2026 and the rail match with the seller."),
 ("B0CX86XK2Q","AITONOBLE Crossbar for 2023-2025 Toyota Sequoia, aluminum rack bars, black, 2 pcs","AITONOBLE","Check listing",{},"Listed to 2025; confirm 2026 and the rail match with the seller."),
 ("B0CYGBYXSL","VERBANA Roof Rack Cross Bars for Sequoia 2023-2024, aluminum crossbars, black","VERBANA","Check listing",{},"Listed to 2024; confirm 2025-2026 and the rail match with the seller."),
 ("B0DK7BDB9V","Roof Rack Cargo Basket for Toyota Sequoia 2023-2026, aluminum, black (basket only)","Generic","Check listing",{},"Basket without bars; confirm it clamps to your crossbars and read the weight on the listing."),
]
