"""Long-form article — Best Floor Mats & Liners for 2020–2026 Toyota Highlander (4th gen, XU70).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("toyota", "highlander", "2020-present", "floor-mats")

TITLE = "Best Floor Liners for 2020–2026 Toyota Highlander: 6 Three-Row Sets for 7-Seat, 8-Seat and Hybrid"
META = ("Six 4th-gen Highlander floor liner sets from Husky, TGBROS, MAXPRO, LASFIT and Smartliner, sorted by "
        "captain's chairs vs bench and gas vs hybrid.")

FAQ = [
 ("Why do some Highlander liners exclude the hybrid?",
  "The Highlander Hybrid places its battery under the second-row seat, which changes the second-row floor and under-seat area. MAXPRO and LASFIT list their sets as not for the hybrid. The generic 7-seat set on this page names the hybrid, and Husky's WeatherBeater pieces are listed for the Highlander without a hybrid exclusion in their titles. Look for 'Hybrid' on the tailgate badge and buy accordingly."),
 ("What's the difference between 7-seat and 8-seat Highlander liners?",
  "The second row. Seven-seat Highlanders have two captain's chairs with a walkway between them; eight-seat trucks have a three-person bench. The second-row liner is shaped differently. LASFIT's set is for 8-seat (bench) gas models; the budget carpet-style set is for 7-seat captain's chairs; TGBROS lists both bench and buckets with a console."),
 ("Do Highlander liners fit the Grand Highlander?",
  "No. The Grand Highlander (2024+) is a larger, separate model with its own floor. Buy liners that name it specifically."),
 ("Do I need a third-row liner?",
  "If anyone rides back there, yes. Kids climbing into the third row track mud across it, and the third row floor is carpet. Smartliner sells a third-row-only liner for the 2020–2026 Highlander that pairs with any front and second-row set. TGBROS and MAXPRO include the third row."),
 ("What does Husky's Highlander cargo liner cover?",
  "Husky's 25791 cargo liner is listed for 2020–2026 Highlander, running to the back of the second row and folding up and down with the third row. That means it protects the cargo floor and the back of the folded third row in one piece."),
 ("Are 2014–2019 Highlander liners compatible?",
  "No. The 2020 Highlander moved to the TNGA-K platform with a new floor. Husky's 99601 set, for example, is for 2014–2019 and excludes the hybrid. Buy 2020+ listings."),
 ("Will liners fit around the second-row captain's chair console?",
  "Some 7-seat Highlanders have a second-row center console between the captain's chairs, others have an open walkway. TGBROS lists buckets with a console. If your truck has an open walkway, a liner that bridges it covers more carpet. Check listing photos against your layout."),
 ("How should the driver liner sit?",
  "Flat on the carpet, hooked onto Toyota's retention posts and clear of the pedals at full travel. Remove the factory mat first and heel-test it toward the pedals."),
 ("How do I clean three-row liners?",
  "Pull each row, shake out crumbs and grit, rinse and scrub with mild soap. Dry before reinstalling. Skip silicone protectants. The third-row liner is usually the easiest to forget; check it monthly."),
 ("Is Husky X-act Contour better than WeatherBeater for a family SUV?",
  "Husky says X-act Contour is 22% more flexible and 10% softer than WeatherBeater, with a DuraGrip surface. In a family SUV, that softer feel is pleasant underfoot and easy to fold for cleaning. WeatherBeater is firmer and holds its walls more rigidly. Both are made in the USA with the same lifetime warranty."),
 ("Can I use Husky's separate WeatherBeater pieces instead of the X-act Contour kit?",
  "Yes. Husky lists a WeatherBeater front piece (15321) and second-row piece (12791) for 2020–2026 Highlander, plus the 25791 cargo liner. Buying pieces lets you cover a 2025 or 2026 and skip rows you don't need. WeatherBeater is firmer than X-act Contour, with the same US manufacturing and lifetime crack warranty. Confirm the second-row piece for your seating layout."),
]

ARTICLE = {
 "dek": "Six three-row liner options for the 4th-generation Highlander, from Husky's made-in-USA liners to a $50 third-row add-on. Two layout questions decide fit: captain's chairs or bench in the second row, and gas or hybrid.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2020–2026 Highlander (seating, hybrid, rows covered), on published maker specs (material, origin, warranty) and on coverage in listing photos. Husky, LASFIT and Smartliner claims come from their own sites, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Hybrid changes the second row.** MAXPRO and LASFIT exclude the Highlander Hybrid.",
  "**7-seat or 8-seat.** Captain's chairs and bench take different second-row liners.",
  "**Grand Highlander is different.** Nothing here fits it.",
  "**Husky covers every row separately.** Front, second row, cargo; X-act Contour adds a 3-row kit.",
  "**Smartliner's third-row piece** adds coverage to any two-row set.",
 ],
 "top_picks": [
  {"asin": "B0D45ZF7JF", "role": "Best overall", "why": "Husky X-act Contour 4-piece, front, 2nd and 3rd row, 2020–2024, made in USA"},
  {"asin": "B08PPJB31Z", "role": "Best 3-row value", "why": "TGBROS full 3-row set for bench or buckets with console"},
  {"asin": "B0DM89BCFG", "role": "Best TPE (gas)", "why": "MAXPRO 3-row liners, 2020–2026, not hybrid"},
  {"asin": "B0BXLGWKGW", "role": "Best for 8-seat", "why": "LASFIT recycled TPE for bench-seat gas models"},
  {"asin": "B088C2THJV", "role": "Best third-row add-on", "why": "Smartliner third-row liner, 2020–2026"},
 ],
 "fit_table": {
  "caption": "2020–2026 Highlander: seating and powertrain decide fit",
  "head": ["Variable", "Versions", "Liner note"],
  "rows": [
   ["Second row", "Captain's chairs (7-seat) or bench (8-seat)", "LASFIT: 8-seat; budget carpet set: 7-seat; TGBROS: both"],
   ["Powertrain", "Gas or Hybrid", "MAXPRO and LASFIT exclude hybrid; budget 7-seat set lists it"],
   ["Rows covered", "Front, 2nd, 3rd, cargo", "Mix sets or buy a 3-row kit"],
   ["Previous gen", "2014–2019", "Not compatible"],
   ["Grand Highlander", "Separate model (2024+)", "Not compatible"],
  ],
 },
 "look_for": [
  {"h": "Captain's chairs or bench",
   "body": "The 4th-gen Highlander comes with a second-row bench for eight seats or two captain's chairs for seven. The second-row floor liner has to match, because captain's chairs leave a walkway to the third row that a bench doesn't, and some 7-seat trucks put a small console between the chairs. LASFIT lists its set for 8-seat trucks; the budget carpet-style set is for 7-seat captain's chairs; TGBROS says its 3-row set covers the bench or buckets with a console. Count your second-row seats before you shop."},
  {"h": "Gas or Hybrid",
   "body": "The Highlander Hybrid puts its battery under the second-row seat, and that affects the second-row floor area. MAXPRO and LASFIT exclude the hybrid in their titles. The budget 7-seat set names it. Husky's pieces don't carry a hybrid exclusion in the titles we found, but confirm with Husky's fit tool. If there's a Hybrid badge on the liftgate, filter every listing for it before comparing prices."},
  {"h": "How many rows to cover",
   "body": "A three-row SUV has four floor zones: front, second row, third row and cargo. Kits vary widely in how many they include. Husky's X-act Contour 4-piece covers front, second and third rows. TGBROS and MAXPRO sell 3-row sets. LASFIT's set covers front and second row. Smartliner sells a third-row-only liner, and Husky's 25791 cargo liner covers the cargo floor and folds with the third row. Decide which zones actually get dirty in your family before paying for all four."},
  {"h": "Material, feel and warranty",
   "body": "Husky says both its WeatherBeater and X-act Contour lines are laser-measured, made in the USA and backed by a lifetime warranty against cracks and breaks; X-act Contour is 22% more flexible and 10% softer, with a DuraGrip surface. LASFIT uses GRS-certified recycled TPE rated from −13°F to 167°F. Smartliner uses one-piece, 100% recyclable TPE with a limited lifetime warranty. TGBROS and MAXPRO don't publish comparable terms. In a family SUV, a softer liner is nicer underfoot and folds easily for cleaning."},
  {"h": "Retention and pedal clearance",
   "body": "Toyota puts retention posts in the driver footwell. A Highlander-specific liner has holes for them. After installing, heel-test the driver liner toward the pedals and press the brake and accelerator to the floor. Never lay a liner over the factory carpet mat. It sounds obvious, but in a family car with several drivers, it's worth checking after anyone else cleans the car."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2020+ in the title", "2014–2019 listings"],
   ["Second row", "Captain's chairs or bench named", "Kits that don't state seating"],
   ["Powertrain", "Gas or hybrid named", "Gas-only sets in a hybrid"],
   ["Rows", "The zones you need", "Paying for rows you don't use"],
   ["Retention", "Hook holes for Toyota's posts", "Loose mats"],
   ["Warranty", "Written terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2020–2026 Highlander",
  "head": ["Type", "Example", "Coverage", "Feel", "Price band", "Best for"],
  "rows": [
   ["USA-made 3-row kit", "Husky X-act Contour 4-pc", "Front, 2nd, 3rd", "Soft", "$220–$300", "Families keeping the car"],
   ["Budget 3-row set", "TGBROS, MAXPRO", "Front, 2nd, 3rd", "Medium", "$120–$160", "Value"],
   ["Recycled TPE 2-row", "LASFIT", "Front + 2nd", "Medium", "$110–$150", "8-seat gas"],
   ["Third-row add-on", "Smartliner", "3rd row", "Medium", "$40–$70", "Completing a 2-row set"],
   ["Cargo liner", "Husky 25791", "Cargo + folded 3rd row", "Firm", "$100–$150", "Strollers, sports gear"],
  ],
 },
 "picks": [
  {"asin": "B0D45ZF7JF", "role": "Best overall", "price": "$220–$300",
   "pros": ["Front, second and third row in one kit", "Made in the USA", "Lifetime warranty against cracks and breaks", "Softer, more flexible X-act Contour material", "DuraGrip surface"],
   "cons": ["Title covers 2020–2024; confirm 2025–2026", "Most expensive here", "Confirm seating layout and hybrid with Husky"],
   "body": "Husky's X-act Contour 4-piece kit covers the front, second and third rows of the 2020–2024 Highlander. X-act Contour is Husky's softer line: Husky says it's 22% more flexible and 10% softer than WeatherBeater, with a DuraGrip surface, and like all Husky liners it's laser-measured, made in the USA and covered by a lifetime warranty against cracks and breaks.\n\nIn a family SUV, the softer material is the right call. It's more comfortable underfoot, easier to fold and carry to the hose, and grips kids' shoes. Covering all three rows in one order also means one maker's fit and warranty across the whole cabin. It's the most expensive option here.\n\nThe title stops at 2024 and doesn't specify seating or hybrid in its short form, so run your trim through Husky's fit tool before ordering. For a 2025 or 2026, Husky's WeatherBeater front (15321) and second-row (12791) pieces are listed for 2020–2026.",
   "who": "Families who want all three rows covered by one US-made brand.",
   "specs": [["Line", "Husky X-act Contour"], ["Pieces", "4 (front pair, 2nd, 3rd)"], ["Fits", "2020–2024 Highlander"], ["Flexibility", "22% more flexible than WeatherBeater (Husky)"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B08PPJB31Z", "role": "Best 3-row value", "price": "$120–$160",
   "pros": ["Full 3-row set", "Listed for bench or buckets with console", "Covers 2020–2025", "Far cheaper than a Husky 3-row kit", "Raised edges"],
   "cons": ["No hybrid note; confirm", "No published warranty", "Open-walkway captain's chair layouts: confirm"],
   "body": "TGBROS' 3-row liner set is listed for the 2020–2025 Highlander with a second-row bench or buckets with a console. Covering all three rows for around $140 makes it the value pick for families.\n\nTGBROS doesn't publish warranty or material details we could check. The bigger question is layout: if your captain's chairs have an open walkway rather than a console, ask the seller whether the second-row piece covers it. The title also doesn't mention the hybrid, so confirm that too. If both check out, it's an efficient way to protect the whole cabin of a family Highlander.\n\nAt this price, it's also a sensible set for a lease, where you want the carpet clean at turn-in without paying for a premium brand.",
   "who": "Families who want all three rows covered on a budget.",
   "specs": [["Rows", "Front, 2nd, 3rd"], ["Fits", "2020–2025 Highlander, 2nd-row bench or buckets with console"], ["Material", "TPE (per listing)"], ["Hybrid", "Confirm with seller"], ["Price band", "$120–$160"]]},
  {"asin": "B0DM89BCFG", "role": "Best TPE (gas)", "price": "$120–$160",
   "pros": ["3-row liner set", "Lists 2020–2026", "Clear 'not hybrid' note", "TPE with raised edges", "Covers the newest model year"],
   "cons": ["Not for the Highlander Hybrid", "Confirm seating layout", "No published warranty"],
   "body": "MAXPRO's 3-row liners are listed for 2020–2026 Highlander, not hybrid. The clear hybrid exclusion and the 2026 coverage are its strengths.\n\nFor a gas Highlander, it covers all three rows for less than half of Husky's kit. MAXPRO publishes little beyond the listing, so warranty is an unknown. Confirm your second-row layout with the seller before ordering, since the title doesn't say captain's chairs or bench.\n\nIf you drive a Highlander Hybrid, skip this set and look at the budget 7-seat carpet-style set, which names the hybrid, or confirm a Husky kit.",
   "who": "Gas Highlander owners who want three rows covered, including 2026.",
   "specs": [["Rows", "3"], ["Fits", "2020–2026 Highlander (not hybrid)"], ["Material", "TPE"], ["Seating", "Confirm with seller"], ["Price band", "$120–$160"]]},
  {"asin": "B0BXLGWKGW", "role": "Best for 8-seat", "price": "$110–$150",
   "pros": ["GRS-certified recycled TPE", "Rated −13°F to 167°F", "Cut for the 8-seat bench layout", "3D laser-scanned", "Lists 2020–2026"],
   "cons": ["Not for hybrid", "Front and second row only", "8-seat only"],
   "body": "LASFIT's liners are listed for 2020–2026 Highlander 8-seat models with the second-row bench, gas only. LASFIT says they're 3D laser-scanned and made from GRS-certified recycled TPE, rated from −13°F to 167°F.\n\nIt covers the front and second rows, which is where most of the mud lands. Pair it with Smartliner's third-row liner if the third row sees regular use. The narrow fit description (8-seat, gas) is a strength: if it matches your truck, the fit is well defined. LASFIT's 45-day return window on its own store gives you time to check. Before ordering, check the liftgate badge for Hybrid and count the second-row seats; if you have captain's chairs, this is the wrong set.",
   "who": "8-seat gas Highlander owners.",
   "specs": [["Rows", "Front + 2nd"], ["Fits", "2020–2026 Highlander 8-seat (bench), not hybrid"], ["Material", "Recycled TPE (GRS)"], ["Temp range", "−13°F to 167°F"], ["Add", "Smartliner 3rd row"]]},
  {"asin": "B088C2THJV", "role": "Best third-row add-on", "price": "$40–$70",
   "pros": ["Covers the third row that 2-row sets skip", "One-piece TPE", "Limited lifetime warranty (Smartliner)", "Lists 2020–2026", "Pairs with any front/2nd-row set"],
   "cons": ["Third row only", "Doesn't cover cargo", "Walls lower than a molded front liner"],
   "body": "Smartliner's third-row liner is listed for the 2020–2026 Highlander. It exists because most two-row sets stop at the second row, leaving the third-row carpet exposed to kids' shoes.\n\nSmartliner says its liners are molded from a single piece of heavy-duty, 100% recyclable TPE, free of PVC, latex and BPA, and backed by a limited lifetime warranty. The company is based in Apopka, Florida. At $40–$70, it's the cheapest way to finish off LASFIT's or Husky's two-row pieces.\n\nFor the cargo floor behind the third row, Husky's 25791 cargo liner is the matching piece.",
   "who": "Owners completing a two-row liner set.",
   "specs": [["Rows", "3rd only"], ["Fits", "2020–2026 Highlander"], ["Material", "One-piece TPE"], ["Warranty", "Limited lifetime"], ["Company", "Apopka, Florida"]]},
  {"asin": "B092546NV6", "role": "Best cargo liner", "price": "$100–$150",
   "pros": ["Covers cargo floor to the back of the 2nd row", "Folds up and down with the 3rd row", "Made in the USA", "Lifetime warranty against cracks and breaks", "Lists 2020–2026"],
   "cons": ["Cargo only", "Firm WeatherBeater material", "Adds cost on top of a floor set"],
   "body": "Husky's WeatherBeater 25791 is a cargo liner listed for the 2020–2026 Highlander. It runs to the back of the second row and folds up and down with the third row, so it protects both the cargo floor and the back of the folded third-row seats.\n\nThat's where strollers, sports bags and grocery spills land in a family Highlander. It carries the WeatherBeater credentials: laser-measured, made in the USA and covered by a lifetime warranty against cracks and breaks. Pair it with any floor set. If your family carries a dog, the cargo liner is the piece that saves the most carpet; claws and wet fur do more damage back there than boots do up front. Check that the liner clears any aftermarket cargo organizer before ordering.",
   "who": "Families who use the cargo area hard.",
   "specs": [["Part #", "Husky 25791"], ["Fits", "2020–2026 Highlander"], ["Coverage", "Cargo to back of 2nd row, folds with 3rd row"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
 ],
 "install": [
  "Confirm second-row seating (captain's chairs or bench) and powertrain (gas or hybrid).",
  "Remove the factory mats from every row and vacuum.",
  "Hook the driver liner onto the retention posts and heel-test it toward the pedals.",
  "Fit the passenger and second-row liners; slide and fold the second row to check clearance.",
  "Fit the third-row liner and, if bought, the cargo liner; fold the third row up and down.",
  "Press the pedals to the floor before driving.",
 ],
 "avoid": [
  {"h": "Gas-only sets in a hybrid", "body": "The hybrid battery sits under the second row."},
  {"h": "Wrong second-row layout", "body": "Captain's chairs and bench take different liners."},
  {"h": "Grand Highlander or 2014–2019 listings", "body": "Different floors."},
  {"h": "Stacking mats", "body": "Remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy Husky's X-act Contour 4-piece for a US-made three-row kit, TGBROS or MAXPRO for three rows on a budget, and add Smartliner's third-row piece to any two-row set.",
  "body": "The 4th-gen Highlander needs two answers before any liner purchase: captain's chairs or bench, and gas or hybrid. Husky's X-act Contour kit is the best-documented three-row option, TGBROS and MAXPRO cover three rows for much less, LASFIT is the 8-seat TPE pick, and Smartliner and Husky's cargo liner fill in the back.\n\nWith the floors covered, many Highlander owners add a roof rack for bikes or a cargo box, and a trailer hitch for a bike rack. The Highlander's raised rails make crossbars straightforward."},
 "sources": [
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky X-act Contour Highlander 4-pc listing", "https://www.amazon.com/dp/B0D45ZF7JF"],
  ["Husky Liners 25791 cargo liner listing", "https://www.amazon.com/dp/B092546NV6"],
  ["SMARTLINER home page (SMARTLINER)", "https://www.smartliner-usa.com/"],
  ["LASFIT floor mats (LASFIT)", "https://www.lasfit.com/collections/floor-mats"],
  ["Toyota Highlander, fourth generation (Wikipedia)", "https://en.wikipedia.org/wiki/Toyota_Highlander"],
 ],
}

FITS = [
 ("B0D45ZF7JF","Husky Liners X-act Contour 4-pc Front, 2nd & 3rd Row, 2020-2024 Toyota Highlander","Husky Liners","$220–$300",{"rows":3},"Confirm seating, hybrid and 2025+."),
 ("B08PPJB31Z","TGBROS 3-Row Floor Liner Set, 2020-2025 Highlander (2nd-row bench or buckets with console)","TGBROS","$120–$160",{"rows":3},"Full 3-row set; confirm hybrid."),
 ("B0DM89BCFG","MAXPRO 3-Row Floor Liners, 2020-2026 Highlander (not hybrid)","MAXPRO","$120–$160",{"rows":3,"hybrid":False},"Not for Highlander Hybrid."),
 ("B0BXLGWKGW","LASFIT TPE Floor Liners front & 2nd row, 2020-2026 Highlander 8-seat (not hybrid)","LASFIT","$110–$150",{"seats":8,"hybrid":False},"8-seat (2nd-row bench), gas only."),
 ("B088C2THJV","SMARTLINER 3rd-Row Floor Liner, 2020-2026 Highlander","SMARTLINER","$40–$70",{"rows":3},"Third row only — pair with a front/2nd-row set."),
 ("B092546NV6","Husky Liners WeatherBeater 25791 Cargo Liner, 2020-2026 Highlander (to back of 2nd row, folds with 3rd row)","Husky Liners","$100–$150",{"rows":3},"Cargo only."),
 ("B0DQ8J5FT9","Carpet-Style All-Weather Floor Mats 4-piece, 2020-2025 Highlander 7-seat incl. hybrid","Generic","$70–$110",{"seats":7},"7-seat captain's chairs; lists hybrid."),
 ("B0FHMM2SWB","Husky Liners WeatherBeater 15321 Front Row, 2020-2026 Toyota Highlander","Husky Liners","$80–$120",{},"Front row only."),
 ("B0FHMM2SVF","Husky Liners WeatherBeater 12791 2nd Row, 2020-2026 Toyota Highlander","Husky Liners","$70–$110",{},"2nd row only; confirm seating."),
]
