"""Long-form article — Best Floor Mats & Liners for 2016–2023 Toyota Tacoma (3rd gen).
No invented hands-on testing: fit facts from listing titles in FITS, specs from maker pages in sources (checked 2026-09-24).
"""

KEY = ("toyota", "tacoma", "2016-2023", "floor-mats")

TITLE = "Best Floor Liners for 2016–2023 Toyota Tacoma Double Cab: 6 Picks by Transmission and Model Year"
META = ("Six 3rd-gen Tacoma Double Cab liner sets, from Husky WeatherBeater and Toyota TRD Pro to $70 TPE, with "
        "the automatic vs manual and 2016–2017 vs 2018+ front-row split.")

FAQ = [
 ("Why do Tacoma liners care about automatic vs manual?",
  "The manual Tacoma has a different floor shape around the shifter and clutch pedal. Liners cut for the automatic leave the clutch area wrong and may interfere with the pedal. Husky sells separate front pairs: 13981 for 2018–2024 manual trucks with the shifter, and different parts for automatics. 3W and YHTAUTO list automatic only. If you have three pedals, only buy a set that names the manual."),
 ("Is there a difference between 2016–2017 and 2018–2023 Tacoma front liners?",
  "For automatics, Husky's catalog says yes. It sells front pairs listed for 2016–2017 Double and Access Cab automatics (13951, 13961) and a full set listed for 2018–2023 automatic Double Cabs (93941). The rear floor stays the same across 2016–2023. If a budget listing covers 2016–2023 in one part, check the photos around the front retention hooks and console for your year."),
 ("Do Access Cab and Double Cab share liners?",
  "Some front pairs are shared, the rear is not. The Access Cab has small rear-hinged doors and a short rear area with jump seats; the Double Cab has four full doors and a bench. All full sets on this page are Double Cab. Husky's 2016–2017 front pairs list both cabs, but buy a rear liner specific to your cab."),
 ("Are Toyota TRD Pro liners the same as regular Toyota all-weather liners?",
  "The TRD Pro liners (PT908-35200-02 in our list) are Toyota's all-weather liners with TRD Pro branding, listed for 2016–2023 automatic Tacomas. They fit like other Toyota liners. You're paying for the logo and the dealer part number. If you don't care about the branding, a Husky or 3W set costs less and has comparable or taller walls."),
 ("Will these liners fit a 2024 Tacoma?",
  "No. The 2024 Tacoma is a new generation on a new platform with a different cab floor. Buy liners listed for 2024+ trucks. Our 2024–2026 Tacoma page covers those, including hybrid-specific notes."),
 ("What is TOUGHPRO and why is it cheaper than Husky?",
  "TOUGHPRO sells heavy-duty rubber mats that its listings say are made in the USA. They're a rubber mat, not a rigid molded liner, so the walls are lower and the material is heavier and grippier. They cost less than Husky and don't curl in the cold the way cheap plastics can. For containment of deep slush, Husky's liner holds more; for grip and price, TOUGHPRO is strong."),
 ("How do I keep the liner away from the pedals?",
  "Remove the factory carpet mat, then hook the driver liner onto Toyota's retention hooks. Heel-test it toward the pedals, then press the brake and accelerator to the floor. On a manual, press the clutch to the floor too. If anything touches the liner, stop and check the fit."),
 ("How long will TPE liners last on a Tacoma?",
  "Several years for most owners. TPE handles heat and cold well and doesn't smell. The driver's heel area wears first. Husky backs WeatherBeater with a lifetime warranty against cracks and breaks; LASFIT rates its TPE for −13°F to 167°F. Budget sets rarely publish either, so treat them as replaceable."),
 ("Do TRD Off-Road and TRD Pro trucks take the same liners as the SR5?",
  "Yes, if the cab and transmission match. Trim changes seats and trim pieces, not the Double Cab floor. The TRD Pro was automatic only in some years and offered with the manual in others, so check your pedals rather than going by trim. Toyota's TRD Pro liners fit any automatic 3rd-gen Tacoma, not just the TRD Pro; the logo is cosmetic."),
 ("Can I get a liner with a cargo mat for the Tacoma?",
  "The Tacoma is a pickup, so there's no cargo area inside the cab to cover. What owners pair with floor liners is a bed mat or bed liner and, for Double Cabs, a rear under-seat storage organizer. Look for bed mats listed for your bed length: 5 ft or 6 ft."),
]

ARTICLE = {
 "dek": "Six liner sets listed for the 3rd-generation Tacoma Double Cab, from Husky WeatherBeater and Toyota's TRD Pro liners to $70 TPE. On this truck, the transmission and the model year change the front liner, so check both before you check price.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these liners ourselves. We ranked them on the fit each listing states for the 2016–2023 Tacoma (cab, transmission, year range), on published maker specs (material, origin, warranty) and on coverage in listing photos. Husky's material and warranty claims come from its own site, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**Automatic or manual first.** The manual floor differs around the clutch and shifter; most budget sets are automatic only.",
  "**2016–2017 vs 2018+ front.** Husky sells different automatic front liners for those years.",
  "**Double Cab only here.** Access Cab rears are different.",
  "**2024+ is a new truck.** Nothing here fits the 4th-gen Tacoma.",
  "**Husky WeatherBeater is the documented pick.** Made in the USA, lifetime crack warranty.",
 ],
 "top_picks": [
  {"asin": "B0F66H89GG", "role": "Best overall", "why": "Husky WeatherBeater 93941, 2018–2023 automatic Double Cab, made in USA"},
  {"asin": "B07YNZ6B8T", "role": "Best factory option", "why": "Toyota genuine TRD Pro all-weather liners, 2016–2023 automatic"},
  {"asin": "B01LJ73C6G", "role": "Best heavy rubber", "why": "TOUGHPRO rubber set listed as made in USA, Double Cab"},
  {"asin": "B0CD15B35L", "role": "Best TPE value", "why": "3W TPE liners, 2016–2023 automatic Double Cab"},
  {"asin": "B07SVTV7Z1", "role": "Best coverage", "why": "TuxMat, runs up the sidewalls, limited lifetime warranty"},
 ],
 "fit_table": {
  "caption": "2016–2023 Tacoma: the splits that change the liner",
  "head": ["Variable", "Versions", "What it means"],
  "rows": [
   ["Cab", "Access Cab, Double Cab", "All picks are Double Cab; Access Cab rears differ"],
   ["Transmission", "Automatic or 6-speed manual", "3W, YHTAUTO, Husky 93941 and TRD Pro are automatic; manual needs a manual-specific front"],
   ["Front floor (automatic)", "2016–2017 vs 2018–2023", "Husky sells separate front liners for each range"],
   ["Bed", "5 ft or 6 ft", "Doesn't affect cab liners; matters for bed mats"],
   ["2024+", "New generation", "Not compatible"],
  ],
 },
 "look_for": [
  {"h": "Transmission and pedals",
   "body": "The 3rd-gen Tacoma was sold with a six-speed automatic or a six-speed manual, and the manual stayed available on many trims into 2023. The manual's floor around the clutch pedal and shifter base is different enough that liner makers cut separate front pieces. 3W, YHTAUTO, Husky's 93941 and Toyota's TRD Pro liners are all listed for automatics. Husky sells a 2018–2024 manual front pair (13981) for trucks with the shifter. Putting an automatic liner in a manual risks the clutch pedal catching the liner edge, which is exactly the failure a custom liner exists to prevent."},
  {"h": "Model year inside the generation",
   "body": "Husky's catalog splits the automatic front liner between 2016–2017 and 2018–2023 trucks, which suggests the front floor or retention points changed. The rear floor didn't. Several budget listings cover 2016–2023 with one part. That can be fine, but look at listing photos of the driver side hooks and the edge by the console, and ask the seller if you have a 2016 or 2017. The TRD Pro liners and 3W's set list the whole 2016–2023 span; Husky's full 93941 set lists 2018–2023."},
  {"h": "Liner or heavy rubber mat",
   "body": "A molded liner like Husky's WeatherBeater or 3W's TPE has high walls that make a tray out of each footwell. A heavy rubber mat like TOUGHPRO's has lower edges but more weight and grip, and rubber stays flexible in the cold. TuxMat takes a third approach: a textured surface that climbs the sidewalls. On a Tacoma that sees trails, snow or beach sand, the tall-walled liner holds the most. For daily driving in a mild climate, rubber or TuxMat is often more pleasant underfoot."},
  {"h": "Warranty and origin",
   "body": "Husky says WeatherBeater is laser-measured, made in the USA from ProGard material, anchored with StayPut nibs and covered by a lifetime warranty against cracks and breaks. TOUGHPRO's listings say its mats are made in the USA. TuxMat offers a limited lifetime warranty and a 30-day money-back guarantee. Toyota's liners are dealer parts. The budget TPE brands, 3W, YITAMOTOR and YHTAUTO, don't publish comparable terms on the pages we checked; 3W's maker is a TPE mat manufacturer in Taizhou, China. On a truck that tends to be kept for a decade, the warranty is worth weighing."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Cab", "Double Cab named", "No cab named"],
   ["Transmission", "Automatic or manual stated", "Automatic sets in a manual truck"],
   ["Year", "Your year inside the listed range", "2024+ listings for a 3rd-gen truck"],
   ["Retention", "Hooks for Toyota's driver-side posts", "Loose mats"],
   ["Walls", "Raised lip at the sill", "Flat trim-to-fit mats"],
   ["Warranty", "Written terms", "No terms"],
  ],
 },
 "types_table": {
  "caption": "Floor protection for the 2016–2023 Tacoma Double Cab",
  "head": ["Type", "Example", "Walls", "Feel", "Price band", "Best for"],
  "rows": [
   ["USA-made molded liner", "Husky WeatherBeater 93941", "High", "Firm", "$150–$210", "Trail, snow, mud"],
   ["Factory liner", "Toyota TRD Pro", "Medium-high", "Firm", "$150–$200", "OEM look"],
   ["Heavy rubber mat", "TOUGHPRO", "Low-medium", "Grippy", "$80–$120", "Cold climates, grip"],
   ["Max-coverage mat", "TuxMat", "Sidewalls", "Textured", "$200–$260", "Interior protection"],
   ["Budget TPE liner", "3W, YITAMOTOR, YHTAUTO", "Medium-high", "Medium", "$70–$150", "Value"],
  ],
 },
 "picks": [
  {"asin": "B0F66H89GG", "role": "Best overall", "price": "$150–$210",
   "pros": ["Made in the USA from ProGard", "Lifetime warranty against cracks and breaks", "StayPut nibs grip the carpet", "Cut for 2018–2023 automatic Double Cab", "Three pieces including one-piece rear"],
   "cons": ["Automatic only", "2018+ only; 2016–2017 needs a different front", "Firm feel"],
   "body": "Husky's WeatherBeater 93941 is the most documented liner for the later 3rd-gen Tacoma. The listing is specific: 2018–2023 Tacoma, automatic transmission, Double Cab only. Husky treats 2016–2017 automatics and manual trucks as separate fits, which is why this narrow title is a strength.\n\nHusky says WeatherBeater is laser-measured with vehicle-specific data, made in the USA from its ProGard formula and anchored by StayPut nibs, with a lifetime warranty against cracks and breaks. On a truck that gets used on trails and in snow, high firm walls matter more than soft feel, and that's what this liner does best. The firmness is the trade-off: it needs a warm day to relax fully. If you have a 2016 or 2017 automatic, Husky's 13951 or 13961 front pairs plus the 14951 Double Cab rear cover you instead.",
   "who": "2018–2023 automatic Double Cab owners who drive in mud, sand or snow.",
   "specs": [["Part #", "Husky 93941"], ["Pieces", "3"], ["Fits", "2018–2023 Tacoma Double Cab, automatic"], ["Material", "ProGard"], ["Made in", "USA"], ["Warranty", "Lifetime, cracks and breaks"]]},
  {"asin": "B07YNZ6B8T", "role": "Best factory option", "price": "$150–$200",
   "pros": ["Genuine Toyota part PT908-35200-02", "TRD Pro logo", "Listed for 2016–2023 automatic Tacomas", "Designed around Toyota's retention hooks", "Dealer-supported"],
   "cons": ["Automatic only", "You pay for the logo", "Walls lower than Husky's"],
   "body": "Toyota's TRD Pro all-weather liners, part PT908-35200-02, are the factory route. The listing covers 2016–2023 automatic Tacomas, and they carry the TRD Pro logo, which suits a TRD Pro, TRD Off-Road or anyone who wants the truck to look factory.\n\nThe practical difference from Husky is containment and price. Toyota's liners fit the floor and hooks exactly, but they don't claim Husky's wall height or warranty terms, and the TRD Pro branding costs extra over Toyota's standard liners. For a manual truck, skip them; they're automatic only. For an owner who wants a dealer part number and a matching interior, they're the obvious pick.",
   "who": "Automatic Tacoma owners who want factory liners with TRD Pro branding.",
   "specs": [["Part #", "Toyota PT908-35200-02"], ["Fits", "2016–2023 Tacoma, automatic"], ["Branding", "TRD Pro logo"], ["Type", "All-weather liner"], ["Price band", "$150–$200"]]},
  {"asin": "B01LJ73C6G", "role": "Best heavy rubber", "price": "$80–$120",
   "pros": ["Listing says made in USA", "Heavy rubber grips and stays flexible in cold", "Front and 2nd row for Double Cab", "Listing spans 2016–2024 Double Cab", "Lower price than molded liners"],
   "cons": ["Lower walls than a molded liner", "Heavier to carry to the hose", "Check the 2024 claim; the 2024 Tacoma is a new generation"],
   "body": "TOUGHPRO's rubber set is the alternative for owners who want grip and cold-weather flexibility more than deep walls. The listing covers front and second row for the Tacoma Double Cab and says the mats are made in the USA.\n\nRubber mats behave differently from TPE liners. They're heavier, which keeps them planted, and they stay flexible when it's freezing. The edges are lower, so a lot of melted snow can spill over. One caution: the listing title runs to 2024, but the 2024 Tacoma is an all-new truck. Treat this as a 2016–2023 part and confirm with the seller before buying for a 2024. On a 3rd-gen Double Cab, it's a strong middle-price pick.",
   "who": "Cold-climate owners who want heavy, grippy rubber and a US-made mat.",
   "specs": [["Type", "Heavy-duty rubber mat"], ["Rows", "Front + 2nd"], ["Fits", "Tacoma Double Cab (3rd gen; confirm year)"], ["Made in", "USA (per listing)"], ["Price band", "$80–$120"]]},
  {"asin": "B0CD15B35L", "role": "Best TPE value", "price": "$110–$150",
   "pros": ["Listing covers the full 2016–2023 automatic Double Cab", "TPE flexes for cleaning", "Raised edges", "Full cabin set", "Clear automatic-only note"],
   "cons": ["Automatic only", "No published warranty", "Check front hooks on 2016–2017 trucks"],
   "body": "3W's TPE liners are listed for 2016–2023 Tacoma Double Cab automatics, with a clear note that manual trucks have a different floor. It's a full cabin set with raised edges.\n\n3W's maker specializes in TPE mats but doesn't publish warranty terms we could check. The material is light, odor-free and easy to wash. Because the listing covers both 2016–2017 and 2018+ automatics in one part, look at the listing photos of the driver side hook holes if you have an early truck, since Husky treats those years separately. At $110–$150 it's the best value among the liners with a clear transmission note.",
   "who": "Automatic Double Cab owners who want a TPE liner around $130.",
   "specs": [["Rows", "1st + 2nd"], ["Fits", "2016–2023 Tacoma Double Cab, automatic"], ["Material", "TPE"], ["Manual", "Not compatible"], ["Price band", "$110–$150"]]},
  {"asin": "B07SVTV7Z1", "role": "Best coverage", "price": "$200–$260",
   "pros": ["Extends up the sidewalls", "Laser-scanned fit", "Limited lifetime warranty", "30-day money-back guarantee", "Textured, leather-like finish"],
   "cons": ["Most expensive here", "Confirm transmission and cab with the seller", "Holds less standing water than a deep-walled liner"],
   "body": "TuxMat is for Tacoma owners who want the carpet around the footwell covered, not just the floor. TuxMat says its mats are laser-scanned and extend up the sidewalls, with a textured, leather-like surface. The listing covers first and second rows for the 2016–2023 Tacoma.\n\nTuxMat backs them with a limited lifetime warranty and a 30-day money-back guarantee. The listing doesn't name transmission or cab in its short title, so confirm both with the seller. In snow country, remember that coverage and containment aren't the same: TuxMat covers more carpet, while Husky holds more slush. For a Limited or a clean daily driver, TuxMat's look and coverage justify the price.",
   "who": "Owners who want premium coverage and looks.",
   "specs": [["Rows", "1st + 2nd"], ["Fits", "2016–2023 Tacoma (confirm cab and transmission)"], ["Coverage", "Floor and sidewalls"], ["Fit method", "Laser-scanned"], ["Warranty", "Limited lifetime + 30-day money-back"]]},
  {"asin": "B0BT92YGYN", "role": "Best budget", "price": "$70–$110",
   "pros": ["Lowest price here", "3-piece set", "Automatic Double Cab named", "TPE with raised edges", "Easy to replace"],
   "cons": ["Little maker documentation", "Automatic only", "Walls shallower than premium sets"],
   "body": "YHTAUTO's three-piece TPE set is listed for 2016–2023 Tacoma Double Cab automatics and is the cheapest raised-edge option on this page. YITAMOTOR's two-row set, in our product list, is a close alternative at a similar price.\n\nAt this price you're buying the cut and the edge, not a warranty. YHTAUTO doesn't publish material or warranty details we could confirm. For a commuter in a mild climate, it's an easy way to keep the carpet clean. For a work truck in a salt state, spending $80 more for Husky's crack warranty makes sense.",
   "who": "Commuter Double Cabs on a tight budget.",
   "specs": [["Pieces", "3"], ["Fits", "2016–2023 Tacoma Double Cab, automatic"], ["Material", "TPE"], ["Warranty", "Confirm with seller"], ["Price band", "$70–$110"]]},
 ],
 "install": [
  "Confirm cab (Double Cab), transmission and model year before ordering.",
  "Remove the factory carpet mats and vacuum the carpet.",
  "Set the driver liner onto Toyota's retention hooks and heel-test it toward the pedals.",
  "Fit the passenger liner against the sill and console.",
  "Lay the rear liner across the Double Cab floor and fold the rear seat bottoms down to check clearance.",
  "Press the brake, throttle and, on manuals, the clutch to the floor to confirm nothing touches the liner.",
 ],
 "avoid": [
  {"h": "Automatic liners in a manual", "body": "The clutch area differs. Buy a manual-specific front."},
  {"h": "Assuming 2016–2023 is one fit", "body": "Husky splits the automatic front at 2018. Check your year."},
  {"h": "Buying 2024+ listings", "body": "The 4th-gen Tacoma has a different floor."},
  {"h": "Stacking mats", "body": "Always remove the factory mat first."},
 ],
 "verdict": {
  "thesis": "Buy Husky's WeatherBeater 93941 for a 2018–2023 automatic Double Cab, Toyota's TRD Pro liners for the factory look, and TOUGHPRO rubber for grip in the cold.",
  "body": "The 3rd-gen Tacoma has more liner variants than its size suggests: automatic or manual, 2016–2017 or 2018+, Access or Double Cab. Once you match those, Husky's WeatherBeater is the best-documented set with a lifetime crack warranty, Toyota's liners are the dealer choice, TOUGHPRO covers the budget rubber route, and TuxMat is the premium coverage pick.\n\nWith the cab protected, many owners look outside next: a tonneau cover for the bed and a bed rack for overlanding gear. If you've moved to a 2024–2026 Tacoma, nothing here carries over; see our page for the new generation."},
 "sources": [
  ["Husky Liners: WeatherBeater vs X-act Contour (Husky Liners)", "https://huskyliners.com/blog/husky-liners-weatherbeater-vs-xact-contour/"],
  ["Husky Liners WeatherBeater 93941 listing", "https://www.amazon.com/dp/B0F66H89GG"],
  ["Husky Liners 13981 manual front listing", "https://www.amazon.com/dp/B079FN9488"],
  ["Husky Liners 14951 Double Cab 2nd row listing", "https://www.amazon.com/dp/B0189ZMVTU"],
  ["TuxMat home page (TuxMat)", "https://tuxmat.com/"],
  ["Toyota Tacoma, third generation (Wikipedia)", "https://en.wikipedia.org/wiki/Toyota_Tacoma_(third_generation)"],
 ],
}

FITS = [
 ("B0F66H89GG","Husky Liners WeatherBeater 93941, 2018-2023 Tacoma Double Cab, automatic","Husky Liners","$150–$210",{"cab":"Double Cab","trans":"automatic","year_from":2018},"Automatic, 2018-2023 only."),
 ("B07YNZ6B8T","Toyota Genuine TRD Pro All-Weather Floor Liners PT908-35200-02, 2016-2023 Tacoma automatic","Toyota","$150–$200",{"trans":"automatic"},"OEM TRD Pro logo liners."),
 ("B01LJ73C6G","TOUGHPRO Floor Mats Front + 2nd Row, Toyota Tacoma Double Cab, heavy-duty rubber (made in USA)","TOUGHPRO","$80–$120",{"cab":"Double Cab"},"3rd-gen fit; confirm year with seller."),
 ("B0CD15B35L","3W TPE All-Weather Floor Liners, 2016-2023 Tacoma Double Cab, automatic","3W","$110–$150",{"cab":"Double Cab","trans":"automatic"},"Automatic only (manual has a different floor)."),
 ("B07SVTV7Z1","TuxMat Custom Car Mats 1st & 2nd row, 2016-2023 Tacoma","TuxMat","$200–$260",{},"Premium coverage; confirm cab and transmission."),
 ("B0BT92YGYN","YHTAUTO TPE Floor Liners 3-piece, 2016-2023 Tacoma Double Cab automatic","YHTAUTO","$70–$110",{"cab":"Double Cab","trans":"automatic"},"Automatic only."),
 ("B081DQNXB2","YITAMOTOR TPE Floor Liners 1st & 2nd row, 2016-2023 Tacoma Double Cab","YITAMOTOR","$80–$120",{"cab":"Double Cab"},"Double Cab."),
 ("B079FN9488","Husky Liners WeatherBeater 13981 Front Row, 2018-2024 Tacoma Double & Access Cab, manual with shifter","Husky Liners","$90–$130",{"trans":"manual"},"Manual trucks; pair with 14951 rear."),
 ("B0189ZMVTU","Husky Liners WeatherBeater 14951 2nd Row, 2016-2023 Tacoma Double Cab","Husky Liners","$60–$100",{"cab":"Double Cab"},"Rear only."),
]
