"""Long-form article — Best Running Boards & Side Steps for 2022–2026 Toyota Tundra CrewMax (3rd gen).
No invented hands-on testing: fit facts from listing titles in FITS, specs from RealTruck pages in sources (checked 2026-09-24).
"""

KEY = ("toyota", "tundra", "2022-present", "running-boards")

TITLE = "Best Running Boards for 2022–2026 Toyota Tundra CrewMax: 7 Picks, Go Rhino RB20/RB30 to Drop Steps"
META = ("Seven 3rd-gen Tundra CrewMax side steps from Go Rhino, Rough Country, OTHOWE and TIEZFUL, with RB20 vs RB30 "
        "vs Slim widths, the 600 lb rating and drop-step notes.")

FAQ = [
 ("Do 2007–2021 Tundra running boards fit the 2022+ Tundra?",
  "No. The 2022 Tundra is a new generation on the TNGA-F platform with a new cab and rocker. Go Rhino sells separate brackets for 2007–2021 Tundras (such as its 6944155 bracket kit) and separate board kits for 2022+. Buy listings that name 2022 or later."),
 ("CrewMax or Double Cab?",
  "Every pick here is CrewMax, the cab with full-size rear doors. The Double Cab has shorter rear doors and needs shorter boards. Check your rear door size before ordering."),
 ("What's the difference between Go Rhino RB20, RB20 Slim and RB30?",
  "All three are galvanized 16-gauge steel with a limited lifetime structural warranty and a 5-year finish warranty, per RealTruck. RealTruck lists the RB20 at 7.5 in wide at the front and 6.5 in at the rear, the RB20 Slim at a 5.5 in step, and the RB30 at a 7 in step with open flow-through slots that shed dirt and snow, rated at 600 lb per side. The RB30 is the newer design; the Slim keeps the most clearance."),
 ("Do I need to drill?",
  "Not for the Go Rhino boards: RealTruck lists the RB20, RB20 Slim and RB30 as bolt-on with no drilling and vehicle-specific brackets. Budget boards typically use the factory mounting points too; check the listing."),
 ("Do these fit the Tundra hybrid?",
  "The i-FORCE MAX hybrid uses the same CrewMax body and rocker, so rocker-mounted boards generally fit. Listings don't always name it; confirm with the seller if the title is silent."),
 ("What about the TRD Pro and Capstone?",
  "Trims share the rocker mounting points, but some come with factory running boards, and aftermarket boards replace them. If your truck is used off-road, rock sliders protect the rocker better than boards."),
 ("Are drop steps a good idea on a Tundra?",
  "The Tundra is tall, and drop steps put a lower step at each door, which helps kids and shorter passengers. TIEZFUL's drop-down steps are listed for the CrewMax. They reduce side clearance, so they're for road use."),
 ("How much weight can the boards hold?",
  "RealTruck lists the Go Rhino RB30 at 600 lb per side. Other boards publish ratings in their listings or not at all; ask the seller if it isn't stated."),
 ("Can I install them myself?",
  "Yes, with a helper. Bolt brackets to the rocker points, set the boards, level them, torque to spec and recheck after a week. RealTruck's Go Rhino install videos are short."),
 ("Why do Go Rhino titles stop at 2024?",
  "The Go Rhino listings we found name 2022–2024 CrewMax. The 2025 and 2026 Tundra share the same generation, but confirm fit with the seller or Go Rhino's fit guide before ordering for a newer truck."),
 ("Will running boards fit with mud flaps?",
  "Usually, yes. Boards sit under the doors between the wheel wells. Large aftermarket mud flaps or wheel-well liners can crowd the board ends; check clearance at the ends before torquing the brackets."),
 ("Should I choose the bedliner or textured black finish?",
  "Both sit over galvanized steel on the Go Rhino boards. The bedliner coating is rougher and resists gravel chips; the textured black looks more finished. RealTruck lists the same structural and finish warranty for either, so choose by where you drive."),
]

ARTICLE = {
 "dek": "Seven side steps listed for the 3rd-gen Tundra CrewMax, from three Go Rhino galvanized boards to Rough Country, budget oval bars and drop steps. The choice is step width and style; every pick bolts to the factory rocker.",
 "author": "jake-morrison",
 "reviewed": "2026-09-24",
 "method": "We did not install these steps ourselves. We ranked them on the fitment each listing states for the 2022–2026 Tundra CrewMax, on published retailer specs (step width, material, finish, warranty, load rating, drilling) and on listing details. Go Rhino specs come from RealTruck's product pages, read in September 2026. Amazon prices move daily, so the button shows the live price.",
 "takeaways": [
  "**New generation in 2022.** 2007–2021 boards and brackets don't fit.",
  "**CrewMax only here.** Double Cab boards are shorter.",
  "**Three Go Rhino widths.** RB20 7.5/6.5 in, RB30 7 in, RB20 Slim 5.5 in (RealTruck).",
  "**RB30 is rated 600 lb per side.** And sheds snow through open slots.",
  "**Go Rhino titles stop at 2024.** Confirm 2025–2026.",
 ],
 "top_picks": [
  {"asin": "B0BRTBZ3QR", "role": "Best overall", "why": "Go Rhino RB30, 7 in step, 600 lb/side, flow-through slots, bedliner finish"},
  {"asin": "B09ZWTKVFN", "role": "Widest step", "why": "Go Rhino RB20, 7.5 in front / 6.5 in rear"},
  {"asin": "B09Z73KKW4", "role": "Best slim board", "why": "Go Rhino RB20 Slim, 5.5 in step for clearance"},
  {"asin": "B0B97VX42F", "role": "Best mid-price", "why": "Rough Country BA2 5 in boards, CrewMax"},
  {"asin": "B0DL5NGNXV", "role": "Best drop steps", "why": "TIEZFUL drop-down side steps, CrewMax"},
 ],
 "fit_table": {
  "caption": "2022–2026 Tundra: fit checklist",
  "head": ["Variable", "Versions", "What to buy"],
  "rows": [
   ["Generation", "2007–2021 vs 2022+", "All picks 2022+"],
   ["Cab", "Double Cab, CrewMax", "All picks CrewMax"],
   ["Powertrain", "i-FORCE or i-FORCE MAX hybrid", "Same rocker; confirm if unlisted"],
   ["Years", "2022–2024 vs 2025–2026", "Confirm Go Rhino for 2025+"],
  ],
 },
 "look_for": [
  {"h": "Step width and who rides",
   "body": "The Tundra is tall, and step width decides how easy it is to climb in. RealTruck lists the Go Rhino RB20 at 7.5 in wide at the front and 6.5 in at the rear, the RB30 at 7 in, and the RB20 Slim at 5.5 in. Rough Country's BA2 is listed at 5 in. For kids, older passengers or anyone climbing in with work boots, wider is easier. For owners who want a cleaner look and more clearance on gravel roads, the Slim is the compromise."},
  {"h": "RB30 vs RB20",
   "body": "Go Rhino's RB30 is the newer board. RealTruck describes it with open flow-through slots that keep dirt and snow from building up, a 7 in step and a 600 lb per side rating. The RB20 has a slightly wider front and a more closed top. Both are galvanized 16-gauge steel with a limited lifetime structural warranty and a 5-year finish warranty. In snow country the RB30's slots are worth having, because a packed layer of snow on a flat board turns icy."},
  {"h": "Generation and cab",
   "body": "The 2022 Tundra moved to the TNGA-F platform, and the rocker and mounting points changed. Go Rhino sells separate brackets for 2007–2021 trucks, which is a clear sign the fit changed. Every pick here is for the 2022+ CrewMax; the Double Cab needs shorter boards. The Go Rhino titles name 2022–2024, so confirm 2025 and 2026 before ordering."},
  {"h": "Finish and warranty",
   "body": "RealTruck lists every Go Rhino board here as galvanized steel under either a textured powder coat or a protective bedliner coating, with a limited lifetime structural warranty and 5-year finish warranty. The galvanizing protects the steel where the top coat chips. Rough Country, OTHOWE and TIEZFUL don't publish comparable terms on the pages we read. In salt states, galvanized steel is the durable choice."},
  {"h": "Clearance and trail use",
   "body": "Any board hangs below the rocker. The Slim keeps the most clearance; drop steps the least. On a TRD Pro that sees trails, rock sliders protect the rocker better than any running board. For a road truck, the convenience of a wide step outweighs the small clearance loss."},
 ],
 "look_table": {
  "head": ["Feature", "Look for", "Avoid"],
  "rows": [
   ["Generation", "2022+ in the title", "2007–2021 parts"],
   ["Cab", "CrewMax named", "Double Cab boards"],
   ["Width", "Matches your riders", "Guessing step width"],
   ["Finish", "Galvanized under powder or bedliner", "Bare paint in salt states"],
   ["Mounting", "Bolt-on, no drilling", "Drilling kits"],
   ["Warranty", "Stated structural and finish terms", "None"],
  ],
 },
 "types_table": {
  "caption": "Side steps for the 2022–2026 Tundra CrewMax",
  "head": ["Type", "Example", "Step", "Finish", "Price band", "Best for"],
  "rows": [
   ["Slotted board", "Go Rhino RB30", "7 in, 600 lb/side", "Bedliner over galvanized", "$450–$600", "Snow country, all-round"],
   ["Wide board", "Go Rhino RB20", "7.5 / 6.5 in", "Textured over galvanized", "$450–$600", "Widest step"],
   ["Slim board", "Go Rhino RB20 Slim", "5.5 in", "Textured over galvanized", "$430–$550", "Clearance, clean look"],
   ["Mid-price board", "Rough Country BA2", "5 in", "Per listing", "$200–$280", "Value brand"],
   ["Oval bar", "OTHOWE", "Flat oval", "Per listing", "$150–$220", "Budget"],
   ["Drop steps", "TIEZFUL", "Drop-down", "Per listing", "$180–$260", "Short riders"],
  ],
 },
 "picks": [
  {"asin": "B0BRTBZ3QR", "role": "Best overall", "price": "$450–$600",
   "pros": ["7 in step with open flow-through slots", "Rated 600 lb per side (RealTruck)", "Galvanized 16-gauge steel", "Limited lifetime structural, 5-year finish warranty", "Bedliner coating resists chips"],
   "cons": ["Title covers 2022–2024 CrewMax; confirm 2025–2026", "Costs more than budget boards", "Heavier than aluminum"],
   "body": "Go Rhino's RB30 69643687T is listed for the 2022–2024 Tundra CrewMax. RealTruck describes the RB30 as galvanized 16-gauge steel with a 7 in step, open flow-through slots that stop dirt and snow from building up, a 600 lb per side rating, a limited lifetime structural warranty and a 5-year finish warranty. This listing is the bedliner-coated version.\n\nThe slots are the reason it's the top pick for a truck that sees winter. Snow packed onto a solid board turns to ice under boots; slots let it fall through. The bedliner coating resists gravel chips, and the galvanizing protects the steel underneath where it does chip. The 600 lb rating is the only published load figure among the boards here.\n\nRealTruck lists it as a no-drill bolt-on with vehicle-specific brackets, from $441.99 on sale. The title stops at 2024; confirm 2025 and 2026 with the seller. Go Rhino also sells an RB30 Slim for more clearance.",
   "who": "CrewMax owners in snow country who want the best-documented board.",
   "specs": [["Part #", "Go Rhino 69643687T"], ["Step", "7 in, flow-through slots (RealTruck)"], ["Rating", "600 lb per side (RealTruck)"], ["Material", "Galvanized 16-ga steel"], ["Finish", "Bedliner coating"], ["Warranty", "Limited lifetime structural, 5-yr finish"], ["Fits", "2022–2024 Tundra CrewMax"]]},
  {"asin": "B09ZWTKVFN", "role": "Widest step", "price": "$450–$600",
   "pros": ["7.5 in front, 6.5 in rear step (RealTruck)", "Galvanized 16-gauge steel", "Limited lifetime structural warranty", "No drilling", "Textured black powder coat"],
   "cons": ["Closed top holds snow more than the RB30", "Confirm 2025–2026", "No published load rating on the RB20 page"],
   "body": "Go Rhino's RB20 69443687PC is listed for the 2022–2024 Tundra CrewMax. RealTruck lists the RB20's step at 7.5 in wide at the front and 6.5 in at the rear, in galvanized 16-gauge steel with a textured powder coat, a limited lifetime structural warranty and a 5-year finish warranty.\n\nThat's the widest front step here, which helps most at the front doors where the driver climbs in several times a day. The top is more closed than the RB30's, so in snow it needs a sweep more often.\n\nRealTruck lists it as no-drill with vehicle-specific brackets. If you don't deal with much snow and want the widest front step, pick this over the RB30.",
   "who": "Owners who want the widest front step.",
   "specs": [["Part #", "Go Rhino 69443687PC"], ["Width", "7.5 in front / 6.5 in rear (RealTruck)"], ["Material", "Galvanized 16-ga steel"], ["Finish", "Textured black"], ["Warranty", "Limited lifetime structural, 5-yr finish"], ["Fits", "2022–2024 Tundra CrewMax"]]},
  {"asin": "B09Z73KKW4", "role": "Best slim board", "price": "$430–$550",
   "pros": ["5.5 in step (RealTruck)", "Most side clearance of the Go Rhino boards", "Same galvanized steel and warranty", "Clean profile", "No drilling"],
   "cons": ["Narrower step", "Confirm 2025–2026", "Price close to the full-width boards"],
   "body": "Go Rhino's RB20 Slim 69443687SPC is listed for the 2022–2024 Tundra CrewMax. RealTruck describes it as a narrower RB20 with a 5.5 in step, the same galvanized 16-gauge steel and the same lifetime structural and 5-year finish warranty, from $449.99.\n\nThe Slim is the pick for owners who drive gravel roads or trails and want a step without a wide board hanging out. It also looks cleaner on a TRD Off-Road or a lifted truck.\n\nThe trade-off is foot room: 5.5 in is enough for adults in boots but less comfortable for kids. Go Rhino also sells an RB30 Slim for the Tundra.",
   "who": "Owners who want a step with the most clearance.",
   "specs": [["Part #", "Go Rhino 69443687SPC"], ["Step", "5.5 in (RealTruck)"], ["Material", "Galvanized 16-ga steel"], ["Finish", "Textured black"], ["Fits", "2022–2024 Tundra CrewMax"]]},
  {"asin": "B0B97VX42F", "role": "Best mid-price", "price": "$200–$280",
   "pros": ["Well-known brand", "5 in board", "Lists 2022–2025 CrewMax", "Half the price of Go Rhino", "Covers 2025"],
   "cons": ["Warranty terms not confirmed on pages we read", "Narrower step", "No published load rating"],
   "body": "Rough Country's BA2 5 in running boards are listed for the 2022–2025 Tundra CrewMax, which covers one more year than the Go Rhino titles. They cost about half as much.\n\nRough Country is familiar to many Tundra owners through its lifts and lights. We didn't find warranty or load terms for the BA2 on the pages we read, so check the listing. The 5 in step is narrower than the Go Rhino boards.\n\nFor a 2025 owner who wants a brand-name board without Go Rhino's price, it's the choice. If you already run Rough Country parts, one brand keeps orders and returns simple.",
   "who": "2025 owners and value buyers.",
   "specs": [["Model", "Rough Country BA2"], ["Step", "5 in"], ["Fits", "2022–2025 Tundra CrewMax"], ["Warranty", "Confirm on listing"], ["Price band", "$200–$280"]]},
  {"asin": "B0DL5NGNXV", "role": "Best drop steps", "price": "$180–$260",
   "pros": ["Drop-down step at each door", "Lists 2022–2026 CrewMax", "Lower first step on a tall truck", "Covers 2026", "Budget price"],
   "cons": ["Reduces side clearance", "No published warranty", "Less step length than a board"],
   "body": "TIEZFUL's drop-down side steps are listed for the 2022–2026 Tundra CrewMax. They put a lower step at each door, which helps kids and shorter adults into a tall truck, and the listing covers 2026.\n\nDrop steps are the lowest point on the side of the truck, so they're a road-truck choice. TIEZFUL doesn't publish warranty terms we could check.\n\nFor families who find the Tundra's step-in too high even with a board, drop steps solve the problem for less money than a power step. Check that the bracket kit and hardware are included, and heel-test each step before trusting it with full weight.",
   "who": "Families with short passengers.",
   "specs": [["Type", "Drop-down steps"], ["Fits", "2022–2026 Tundra CrewMax"], ["Warranty", "Confirm with seller"], ["Price band", "$180–$260"]]},
  {"asin": "B09Z6KMM4V", "role": "Best budget oval bar", "price": "$150–$220",
   "pros": ["Flat oval nerf-style bar", "Lists 2022–2026 CrewMax", "Low price", "Clean look", "Covers 2026"],
   "cons": ["No published warranty", "Narrower step", "Finish specs thin"],
   "body": "OTHOWE's flat oval running boards are listed for the 2022–2026 Tundra CrewMax. They're the budget route to a nerf-bar look, and the listing covers 2026.\n\nOTHOWE doesn't publish warranty or finish details we could check. In salt states, the finish is what ages first on budget steel, so rinse the undercarriage in winter.\n\nFor a truck that needs a simple step at a low price, it's a reasonable option. Check the listing for included brackets and a textured step pad.",
   "who": "Budget buyers who want a nerf-bar look.",
   "specs": [["Type", "Flat oval bar"], ["Fits", "2022–2026 Tundra CrewMax"], ["Warranty", "Confirm with seller"], ["Price band", "$150–$220"]]},
  {"asin": "B0D3X95ZRT", "role": "Budget 2-step rails", "price": "$140–$200", "pros": ["6 in 2-step side rails", "Lists 2022–2026 CrewMax", "Lowest price here", "Step pad at each door", "Covers 2026"], "cons": ["Generic brand", "No published warranty or load rating", "Less continuous step than a board"], "body": "These 6 in 2-step side rails are listed for the 2022–2026 Tundra CrewMax and are the cheapest option on this page. Each rail has a step pad at each door rather than a continuous board.\n\nThat design gives passengers a defined place to put a foot, but it covers less length than a full board, and a generic listing publishes little on materials, load rating or warranty. Check the listing for brackets and hardware before ordering.\n\nFor a work truck or a second vehicle that just needs a step, it's the budget choice; for a family truck used daily, the Go Rhino boards justify their price with galvanized steel and a structural warranty.", "who": "Budget buyers who need a basic step.", "specs": [["Type", "2-step side rails"], ["Width", "6 in"], ["Fits", "2022–2026 Tundra CrewMax"], ["Warranty", "Confirm with seller"], ["Price band", "$140–$200"]]}
 ],
 "install": [
  "Confirm a 2022+ CrewMax and remove any factory running boards.",
  "Locate the factory rocker mounting points; remove plugs if present.",
  "Bolt brackets on hand-tight.",
  "With a helper, set the board on the brackets and start all bolts.",
  "Level it and torque every bolt to spec.",
  "Recheck torque after a week.",
 ],
 "avoid": [
  {"h": "2007–2021 parts", "body": "The 2022 rocker is new."},
  {"h": "Double Cab boards", "body": "Shorter cab."},
  {"h": "Drop steps off-road", "body": "Lowest point on the side."},
  {"h": "Skipping the recheck", "body": "Brackets settle after a week."},
 ],
 "verdict": {
  "thesis": "Buy Go Rhino's RB30 for a 600 lb-rated, snow-shedding board with a lifetime structural warranty, the RB20 for the widest front step, and the RB20 Slim for clearance.",
  "body": "Tundra side steps come down to width and style, because every pick bolts to the 2022+ rocker. Go Rhino's three galvanized boards carry the strongest published warranty; the RB30 adds a load rating and slots for snow. Rough Country covers 2025 for less, TIEZFUL's drop steps help short riders, and OTHOWE is the budget bar.\n\nA step keeps mud off the sill, which helps floor liners last. The bed is the other common first upgrade: a tonneau cover sized for your 5.5, 6.5 or 8.1 ft bed."},
 "sources": [
  ["Go Rhino RB30 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb30-running-boards/"],
  ["Go Rhino RB20 running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb20-running-boards/"],
  ["Go Rhino RB20 Slim running boards (RealTruck)", "https://realtruck.com/p/go-rhino-rb20-slim-running-boards/"],
  ["Go Rhino RB30 Tundra listing", "https://www.amazon.com/dp/B0BRTBZ3QR"],
  ["Go Rhino 2007–2021 Tundra brackets listing", "https://www.amazon.com/dp/B08LF391F1"],
  ["Toyota Tundra (Wikipedia)", "https://en.wikipedia.org/wiki/Toyota_Tundra"],
 ],
}

FITS = [
 ("B0BRTBZ3QR","Go Rhino RB30 Running Boards & Brackets Bedliner 69643687T, 2022-2024 Tundra CrewMax","Go Rhino","$450–$600",{"cab":"CrewMax"},"600 lb/side; confirm 2025-2026."),
 ("B09ZWTKVFN","Go Rhino RB20 Running Boards & Brackets 69443687PC, 2022-2024 Tundra CrewMax","Go Rhino","$450–$600",{"cab":"CrewMax"},"Confirm 2025-2026."),
 ("B09Z73KKW4","Go Rhino RB20 Slim Running Boards 69443687SPC, 2022-2024 Tundra CrewMax","Go Rhino","$430–$550",{"cab":"CrewMax"},"5.5 in step."),
 ("B0B97VX42F","Rough Country BA2 5 in Running Boards, 2022-2025 Tundra CrewMax","Rough Country","$200–$280",{"cab":"CrewMax"},"Brand-name; CrewMax only."),
 ("B0DL5NGNXV","TIEZFUL Drop-Down Side Steps, 2022-2026 Tundra CrewMax","TIEZFUL","$180–$260",{"cab":"CrewMax"},"Drop steps."),
 ("B09Z6KMM4V","OTHOWE Flat Oval Running Boards, 2022-2026 Tundra CrewMax","OTHOWE","$150–$220",{"cab":"CrewMax"},"CrewMax only."),
 ("B0D3X95ZRT","6 in 2-Step Side Rails, 2022-2026 Tundra CrewMax","Generic","$140–$200",{"cab":"CrewMax"},"Budget."),
]
